### ISSUE TITLE
Website horizontal scrolling broken

### ISSUE THREAD

**Issue by jadekler** [serverless/serverless#3942] opened 2017-07-17 17:39 UTC
![screen shot 2017-07-17 at 11 38 34](https://user-images.githubusercontent.com/3584893/28281482-7bb2d492-6ae4-11e7-8428-389abe9641f2.png)

The page goes out of bounds to the right (which sucks) and I'm unable to horizontally scroll (which _really_ sucks). div._39ts3 docs-content has `overflow:hidden`.

See: https://serverless.com/framework/docs/providers/aws/guide/resources/#aws-cloudformation-resource-reference

**Comment by pmuens** [comment] 2017-07-18 07:10
Thanks for reoprting @jadekler 👍 

This is a duplicate of https://github.com/serverless/serverless/issues/3937 so I'll close it. TLDR is that there's a separate repo for the website where this bug should be fixed.

/cc @DavidWells

**Closed by pmuens** 2017-07-18 07:10 UTC
Labels: kind/docs
