### ISSUE TITLE
apigateways probably point to  latest version 

### ISSUE THREAD

**Issue by zloof** [serverless/serverless#3695] opened 2017-05-26 19:04 UTC
* What went wrong?
deploy to a stage,  changing the backhand lambda to all stages:
stapes to reproduce:
1. deploy to stage "dev" (sls deploy) new lambda function and apigateways  that return "hello1"
2. create new stage "qa" by apigateways
3. deploy to qa "hello1"  (works OK)
4. change the code in the lambda to return "hello2"
5. deploy the new version to "dev"
* What did you expect should have happened?
It should change the dav stage to  "hello2" and the qa stage need to return "hello1"
but stage "QA" return "hello2"

* What was the config you used?
   versionFunctions: true

* it seems that apigateways always point to Latest lambta function and not version base 
So when updateing a version all stages get the same lambta:latest version 
If so: need to point it to specific version and not latest  

thanks

**Comment by pmuens** [comment] 2017-05-26 19:21
Hey @zloof thanks for opening this up 👍 

So the problem is that Serverless won't recognize the API Gateway stage?

Serverless handles stages differently and doesn't consider / use API Gateway stages at all.

So if you only use the CLI and deploy to different stages then everything should be working as expected. Best is always to do everything through the CLI (or CloudFormation) since otherwise manual configs will get out of sync with the CloudFormation compilations Serverless performs.

**Comment by HyperBrain** [comment] 2017-05-27 08:20
If you want to use versions and aliases throughout your deployments, you should give the [alias plugin](https://github.com/HyperBrain/serverless-aws-alias) a try. The plugin adds full stage/alias support and does not use $LATEST at all.

**Comment by pmuens** [comment] 2017-05-28 19:29
Thanks for the addition @HyperBrain 👍 

I'll close this one since the described behavior is the way Serverless treats API Gateway stages. Furthermore the alias plugin might be a good solution here.

Feel free to reopen or comment if there's still something unclear.

**Closed by pmuens** 2017-05-28 19:29 UTC
Labels: kind/question, status/more-info-needed
