### ISSUE TITLE
V3 beta error in AJV validation: Cannot find module 'object-hash'

### ISSUE THREAD

**Issue by mnapoli** [serverless/serverless#10520] opened 2022-01-16 17:48 UTC
### Are you certain it's a bug?

- [X] Yes, it looks like a bug

### Is the issue caused by a plugin?

- [X] It is not a plugin issue

### Are you using the latest version?

- [X] Yes, I'm using the latest version

### Is there an existing issue for this?

- [X] I have searched existing issues, it hasn't been reported yet

### Issue description

My CI deploying a project with the v3 beta failed today. This doesn't seem like a random error, I tried redeploying but get the same output.

Given the error message, I wonder if there isn't anything related to the AJV changes recently?

(Note: this is running in GitHub Action, fresh container, fresh serverless install via NPM)

I can work on a reproducible case if needed, but given the error message, it might be worth a quick look to see if there isn't something obvious?

### Service configuration (serverless.yml) content

```yaml
TBD
```

### Command name and used flags

serverless deploy --stage=prod

### Command output

```shell
/opt/hostedtoolcache/node/16.13.2/x64/lib/node_modules/serverless/node_modules/essentials/index.js:21
		throw reason;
		^

Error: Cannot find module 'object-hash'
Require stack:
- /opt/hostedtoolcache/node/16.13.2/x64/lib/node_modules/serverless/lib/classes/ConfigSchemaHandler/resolveAjvValidate.js
- /opt/hostedtoolcache/node/16.13.2/x64/lib/node_modules/serverless/lib/classes/ConfigSchemaHandler/index.js
- /opt/hostedtoolcache/node/16.13.2/x64/lib/node_modules/serverless/lib/utils/telemetry/generatePayload.js
- /opt/hostedtoolcache/node/16.13.2/x64/lib/node_modules/serverless/lib/cli/handle-error.js
- /opt/hostedtoolcache/node/16.13.2/x64/lib/node_modules/serverless/scripts/serverless.js
- /opt/hostedtoolcache/node/16.13.2/x64/lib/node_modules/serverless/bin/serverless.js
    at Function.Module._resolveFilename (node:internal/modules/cjs/loader:933:15)
    at Function.Module._load (node:internal/modules/cjs/loader:778:27)
    at Module.require (node:internal/modules/cjs/loader:1005:19)
    at require (node:internal/modules/cjs/helpers:102:18)
    at Object.<anonymous> (/opt/hostedtoolcache/node/16.13.2/x64/lib/node_modules/serverless/lib/classes/ConfigSchemaHandler/resolveAjvValidate.js:4:20)
    at Module._compile (node:internal/modules/cjs/loader:1101:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1153:10)
    at Module.load (node:internal/modules/cjs/loader:981:32)
    at Function.Module._load (node:internal/modules/cjs/loader:822:12)
    at Module.require (node:internal/modules/cjs/loader:1005:19)
    at require (node:internal/modules/cjs/helpers:102:18)
    at Object.<anonymous> (/opt/hostedtoolcache/node/16.13.2/x64/lib/node_modules/serverless/lib/classes/ConfigSchemaHandler/index.js:8:28)
    at Module._compile (node:internal/modules/cjs/loader:1101:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1153:10)
    at Module.load (node:internal/modules/cjs/loader:981:32)
    at Function.Module._load (node:internal/modules/cjs/loader:822:12)
    at Module.require (node:internal/modules/cjs/loader:1005:19)
    at require (node:internal/modules/cjs/helpers:102:18)
    at Object.<anonymous> (/opt/hostedtoolcache/node/16.13.2/x64/lib/node_modules/serverless/lib/utils/telemetry/generatePayload.js:11:46)
    at Module._compile (node:internal/modules/cjs/loader:1101:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1153:10)
    at Module.load (node:internal/modules/cjs/loader:981:32)
    at Function.Module._load (node:internal/modules/cjs/loader:822:12)
    at Module.require (node:internal/modules/cjs/loader:1005:19)
    at require (node:internal/modules/cjs/helpers:102:18)
    at Object.<anonymous> (/opt/hostedtoolcache/node/16.13.2/x64/lib/node_modules/serverless/lib/cli/handle-error.js:17:34)
    at Module._compile (node:internal/modules/cjs/loader:1101:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1153:10)
    at Module.load (node:internal/modules/cjs/loader:981:32)
    at Function.Module._load (node:internal/modules/cjs/loader:822:12)
    at Module.require (node:internal/modules/cjs/loader:1005:19)
    at require (node:internal/modules/cjs/helpers:102:18)
    at Object.<anonymous> (/opt/hostedtoolcache/node/16.13.2/x64/lib/node_modules/serverless/scripts/serverless.js:15:21)
    at Module._compile (node:internal/modules/cjs/loader:1101:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1153:10)
    at Module.load (node:internal/modules/cjs/loader:981:32)
    at Function.Module._load (node:internal/modules/cjs/loader:822:12)
    at Module.require (node:internal/modules/cjs/loader:1005:19)
    at require (node:internal/modules/cjs/helpers:102:18)
    at /opt/hostedtoolcache/node/16.13.2/x64/lib/node_modules/serverless/bin/serverless.js:68:7 {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    '/opt/hostedtoolcache/node/16.13.2/x64/lib/node_modules/serverless/lib/classes/ConfigSchemaHandler/resolveAjvValidate.js',
    '/opt/hostedtoolcache/node/16.13.2/x64/lib/node_modules/serverless/lib/classes/ConfigSchemaHandler/index.js',
    '/opt/hostedtoolcache/node/16.13.2/x64/lib/node_modules/serverless/lib/utils/telemetry/generatePayload.js',
    '/opt/hostedtoolcache/node/16.13.2/x64/lib/node_modules/serverless/lib/cli/handle-error.js',
    '/opt/hostedtoolcache/node/16.13.2/x64/lib/node_modules/serverless/scripts/serverless.js',
    '/opt/hostedtoolcache/node/16.13.2/x64/lib/node_modules/serverless/bin/serverless.js'
  ]
}
```

### Environment information

```shell
Latest v3 beta
```

**Comment by pgrzesik** [comment] 2022-01-17 09:40
Good catch, it will be fixed soon 👍

**Comment by medikoo** [comment] 2022-01-17 12:07
Closing as it's fixed in v3.

It was caused by confusion. In v2 this was an unused dependency so it was removed, yet in v3 this dependency started to be used again with the upgrade of AJV, so when v3 was rebased against v2, this dependency was removed and the branch got broken.

@pgrzesik this morning, ensured that this dependency is back in v3

**Closed by medikoo** 2022-01-17 12:07 UTC
Labels: bug
