### ISSUE TITLE
Unable to invoke local Java

### ISSUE THREAD

**Issue by itonics-tbeauvais** [serverless/serverless#5030] opened 2018-06-08 09:21 UTC
I ran exactly this with version `sls@1.27.3`

`npm@5.10.0`
`node@v8.11.2`

```
sls create --template aws-java-gradle --name test --path test
cd test
./gradlew build
sls invoke local -f hello
```

And received this output
```
Serverless: Building Java bridge, first invocation might take a bit longer.
events.js:167
      throw er; // Unhandled 'error' event
      ^

Error: spawn mvn ENOENT
    at Process.ChildProcess._handle.onexit (internal/child_process.js:217:19)
    at onErrorNT (internal/child_process.js:394:16)
    at process._tickCallback (internal/process/next_tick.js:174:19)
Emitted 'error' event at:
    at Process.ChildProcess._handle.onexit (internal/child_process.js:223:12)
    at onErrorNT (internal/child_process.js:394:16)
    at process._tickCallback (internal/process/next_tick.js:174:19)
```

It looks like it's calling `mvn` and I am really not sure why. 

Also, when I do install `mvn` it just hangs.

**Comment by dbuarque** [comment] 2018-06-09 03:11
same here

**Comment by anne-nelson** [comment] 2018-06-21 13:50
The same issue is happening for me. After I installed maven it no longer gives the error but will just hang indefinitely after outputting
`Serverless: Building Java bridge, first invocation might take a bit longer.`

**Comment by anne-nelson** [comment] 2018-06-21 13:56
As seen in #4405 if you go to `${NPM_DIR}/node_modules/serverless/lib/plugins/aws/invokeLocal/java` and run `mvn package` it should get the command to stop hanging.

**Comment by bhaskarbalusani** [comment] 2018-08-06 06:46
Facing the same issue.
Root cause: spawn did not handle .bat or .cmd files.
Changes i made to resolve this issue ->
https://github.com/serverless/serverless/blob/master/lib/plugins/aws/invokeLocal/index.js#L233

Here spawn method not able to detect "mvn" as a command, When you give an argument to set shell as true like this
const mvn = spawn('mvn', [
'package',
'-f',
path.join(javaBridgePath, 'pom.xml'),
]);
], { shell: true });
It will open the cmd.exe terminal to execute the child process. There it will be able to detect .cmd and .bat files.
I made changes in my branch master...bhaskarbalusani:master

Please suggest me, how can i merge these changes

**Comment by pmuens** [comment] 2019-01-18 11:13
Thanks for opening @itonics-tbeauvais and thanks for providing a fix @bhaskarbalusani  👍

I'll close this for now since the fix has already been merged and we've already published some new versions.

**Closed by pmuens** 2019-01-18 11:13 UTC

**Comment by mrvisser** [comment] 2019-03-09 10:27
FWIW, I had this problem today still.

```
$ serverless -v
1.38.0
$ which serverless
/usr/local/bin/serverless
$ ls -l /usr/local/bin/serverless
lrwxr-xr-x  1 bvisser  admin  71  9 Mar 09:33 /usr/local/bin/serverless -> ../../../Users/bvisser/.config/yarn/global/node_modules/.bin/serverless

Went into that directory `/lib/plugins/aws/invokeLocal/java` and ran `mvn package` then it didn't hang aftward.

Is it specific to `yarn`?

**Comment by huynhhacnguyen** [comment] 2020-08-02 09:37
Just a heads up, for 1.77.1, the path was changed and you should navigate to `${NPM_DIR}/node_modules/serverless/lib/plugins/aws/invokeLocal/runtimeWrappers/java`
