### ISSUE TITLE
Tag value pattern does not respect @

### ISSUE THREAD

**Issue by mvanzoest-rcd** [serverless/serverless#8390] opened 2020-10-12 21:48 UTC
I recently deployed a serverless application and was given the following configuration validation warning:

```
Serverless: Configuration warning:
Serverless:   at 'provider.tags['team-email']': should match pattern "^(?!aws:)[\w./=+-]*$"
```

[According to AWS docs](https://docs.aws.amazon.com/general/latest/gr/aws_tagging.html#tag-conventions), "In general, allowed characters in tags are letters, numbers, spaces representable in UTF-8, and the following characters: _ . : / = + - @" 

<details>
<summary><code>serverless.yml</code></summary>

```yaml
service: foo-bar-lambda

frameworkVersion: '2'

provider:
  name: aws
  runtime: nodejs12.x
  stage: dev
  tags:
    team-email: 'foo-bar@baz.com'

functions:
  FooBar:
    handler: src/index.handler
    name: foo-bar
```

</details>

<details>
<summary><b><code>serverless deploy -v</code> output</b></summary>

```

> answer-custom-auth-lambdas@1.0.0 serverless /build
> serverless "deploy" "-v"

Serverless: Configuration warning:
Serverless:   at 'provider.tags['team-email']': should match pattern "^(?!aws:)[\w./=+-]*$"
Serverless:  
Serverless: Learn more about configuration validation here: http://slss.io/configuration-validation
Serverless:  
Serverless: Packaging service...
Serverless: Excluding development dependencies...
Serverless: Excluding development dependencies...
Serverless: Service files not changed. Skipping deployment...
Service Information
service: foo-bar-lambda
stage: dev
region: us-east-1
stack: foo-bar-lambda
resources: 4
api keys:
  None
endpoints:
  None
functions:
  FooBar: foo-bar
layers:
  None

Stack Outputs
FooBarLambdaFunctionQualifiedArn: arn:aws:lambda:us-east-1:1234567890:function:foo-bar:1
ServerlessDeploymentBucketName: foo-bar-serverlessdeploymentbuck-h4n9x164fjh7


**********
Serverless: Announcing Metrics, CI/CD, Secrets and more built into Serverless Framework. Run "serverless login" to activate for free..
**********
```

</details>

<b>Installed version</b>

```
$ serverless --version
Serverless: Running "serverless" installed locally (in service node_modules)
Framework Core: 2.4.0 (local)
Plugin: 4.0.4
SDK: 2.3.2
Components: 3.2.1
```

Other notes: I haven't actually tested that serverless.yml so the given output is a guess, but it communicates the issue.  [Here is a related (merged) PR](https://github.com/serverless/serverless/pull/8314/files#diff-271ef5d492727880dcac1b94a86c878dR359).

**Comment by medikoo** [comment] 2020-10-13 10:23
Duplicate of https://github.com/serverless/serverless/issues/8304

**Closed by medikoo** 2020-10-13 10:23 UTC
Labels: duplicate
