### ISSUE TITLE
DeletionPolicy is ignored when running sls deploy

### ISSUE THREAD

**Issue by Bjorn121** [serverless/serverless#4627] opened 2018-01-04 11:06 UTC
# This is a Bug Report

### What went wrong
My `serverless.yml` creates a DynamoDB table and the DeletionPolicy is set to Retain.  However, when I run `sls deploy` it tries to recreate the table, which results in an error.

### Expected result
`sls deploy` should not recreate the table if it's already there, but simply continue.

I've explained it into a bit more detail on the Serverless forums, but I decided to open a defect as well.  You can find the link here: https://forum.serverless.com/t/dynamodb-resource-already-exists/3428

## Additional Data

* ***Serverless Framework Version you're using***: 1.25.0
* ***Operating System***: OSX/Windows
* ***Stack Trace***: None
* ***Provider Error messages***:

**Comment by horike37** [comment] 2018-01-04 19:57
Hi @Bjorn121, thank you for reporting :smiley: 
DeletionPolicy is to decide a behavior which `sls remove` runs rather than `sls deploy`.
Therefore, it seems that the root cause you ran into is not DeletionPolicy.

>However, when I run sls deploy it tries to recreate the table, which results in an error.

What kind of the error message did you look?

**Comment by hassankhan** [comment] 2018-01-10 15:31
Hi @Bjorn121, this is actually a "feature" of CloudFormation. If you set the `DeletionPolicy` to `Retain` for any resource and that stack update fails, it will NOT remove the newly created resource.

This can be a massive pain when trying to set up a new project, my advice would be to only set `Retain` on production environments.

**Comment by horike37** [comment] 2018-01-11 00:35
Thank you for following up @hassankhan 😄 

Closing this issue for now since this is a "feature" of CloudFormation.
Feel free to reopen if you want to continue any discussion 👍

**Closed by horike37** 2018-01-11 00:35 UTC
Labels: status/more-info-needed

**Comment by daviddelucca** [comment] 2018-08-17 12:35
I'm facing the same problem. When I try to run "sls deploy" to deploy new functions on production environment, I got an error like `An error occurred: MyBucket - my-bucket-prod already exists.`.

How can I handle deploy new functions on production environment?

**Comment by darthwalsh** [comment] 2023-10-03 14:00
This looks like a duplicate of #3148 -- which was closed without providing a fix.
