### ISSUE TITLE
1.50.0 onwards includes entire project source in custom-resources.zip

### ISSUE THREAD

**Issue by seashairo** [serverless/serverless#6700] opened 2019-09-17 20:43 UTC
# This is a Bug Report

## Description

- What went wrong?
Serverless >1.50.0 packages entire project directory into the node_modules folder in custom-resources.zip when `serverless package` is run. This includes the project's node_modules folder which causes custom-resources execution to fail on AWS due to being >250MB

- What did you expect should have happened?
That the entire project directory was NOT present in custom-resources.zip.

- What was the config you used?
Close to standard getting started setup. I only have 6 functions, a Dynamo table, and a Cognito User Pool. I also have serverless-webpack installed.

- What stacktrace or error message from your provider did you see?

```

2019-09-17 21:40:55 UTC+0100
CustomDashresourceDashapigwDashcwDashroleLambdaFunction
CREATE_FAILED
Unzipped size must be smaller than 262144000 bytes (Service: AWSLambdaInternal; Status Code: 400; Error Code: InvalidParameterValueException; Request ID: e254d3b8-bda5-43b1-9984-1d8d2e9322a8)
```

## Additional Data

- **_Serverless Framework Version you're using_**: 1.50.0 onwards
- **_Operating System_**: Windows 10
- **_Stack Trace_**: n/a
- **_Provider Error messages_**: see above

This issue does not occur with Serverless version 1.49.0

**Comment by medikoo** [comment] 2019-09-17 20:50
@seashairo great thanks for report.

It looks as duplicate of #6557, see also this comment: https://github.com/serverless/serverless/issues/6557#issuecomment-531732260 We will look into it shortly.

Follow #6557 for details

**Closed by medikoo** 2019-09-17 20:50 UTC
Labels: duplicate

**Comment by Tymek** [comment] 2020-03-16 16:37
I couldn't resolve the same problem in v1.66.0. It may have something to do with serverless-webpack. I'm trying not to bundle entire AWS-SDK source into my functions

**Comment by andreigec** [comment] 2020-05-04 23:52
+1
