### ISSUE TITLE
CLI deploys whole project when `--function` present but `function` missing

### ISSUE THREAD

**Issue by eob** [serverless/serverless#3539] opened 2017-04-28 18:22 UTC
# This is a Bug Report AND Feature Proposal

(Depending on how much you value user interface)

## Description

For bug reports:
* What went wrong?

I typed `serverless deploy --function myFunction` in an attempt to deploy a single function.

* What did you expect should have happened?

An error should have been thrown saying "it appears you're trying to deploy a single function. You need to use the command `serverless deploy function --function myFunction`

Instead, serverless deployed the entire service, silently ignoring the `--function myFunction` argument.

* What was the config you used?

N/A

* What stacktrace or error message from your provider did you see?

N/A

For feature proposals:
* What is the use case that should be solved. The more detail you describe this in the easier it is to understand for us.

This is an easy sanity check that removes no capabilities from the user but prevents them from accidentally deploying the entire service when they intended to only deploy a function.

* If there is additional config how would it look

Similar or dependent issues:
* #12345

## Additional Data

* ***Serverless Framework Version you're using***:
* ***Operating System***:
* ***Stack Trace***:
* ***Provider Error messages***:

**Comment by pmuens** [comment] 2017-04-29 07:25
Thanks for opening and proposing this change @eob 👍 

Closing this one since it's a duplicate of https://github.com/serverless/serverless/issues/3204

**Closed by pmuens** 2017-04-29 07:25 UTC
