### ISSUE TITLE
AWS SAM Integration

### ISSUE THREAD

**Issue by eahefnawy** [serverless/serverless#2867] opened 2016-12-05 17:09 UTC
AWS recently announced their [Serverless Application Model](https://github.com/awslabs/serverless-application-model). This issue discusses the possibility of switching to this new model when deploying Serverless applications.

## Advantages
* Out of the box support for all event sources: -> which reduces CF template size & technical debt
  * S3
  * SNS
  * Kinesis
  * DynamoDB
  * Api
  * Schedule
  * CloudWatchEvent
  * IoTRule
  * AlexaSkill
* Events <> Lambda permissions are auto managed by AWS (I think). So no need for `Lambda::Permission` -> which reduces CF template size & technical debt
* Out of the box support for creating simple serverless databases with SimpleTable. Although we can easily support this by providing an even simpler abstraction layer on top of DynamoDB CF resource.
* Generally speaking, using the SAM model will help us outsource more technical implementation details to AWS

## Disadvantages
* The feature set and event source options might be limited since it was just released.
* The SAM model is still new and might still have some bugs that our current users don't have to worry about
* While our config interface will stay the same regardless we use SAM or not, **switching to SAM would be a breaking change** for anyone referencing one of our core resources.
* Since event sources resources are properties of functions, users will no longer be able to reference those resources. They can only reference functions.
* API Gateway config is exclusively based on Swagger. This is irrelevant for our users thanks to our abstraction layer, but do we want to be stuck with Swagger?

## Implementation
Our deployment process would still stay the same with or without SAM. The difference would be in how we compile the final CF template. We'd still need to:

* Create the core stack with the deployment bucket
* Compile CF template (this step will be different with SAM and the final template would be smaller)
* Package and upload the code and CF template to S3
* Update the CF stack

So our users won't really feel any difference after integrating SAM, and I don't think it'll provide much value to them, but integrating SAM would be valuable for us as it reduces the technical debt and implementation details.

My personal preference is to push integrating SAM to v2.0, to give it some time to mature and keep the breaking changes under semantic versioning. Also considering the time it'd take to make the switch, I don't think it's worth it. I don't feel that SAM is particularly useful for our users, but since it'll be a standard for the future, we should integrate it as some point later on.

Feedback much appreciated. cc/ @serverless/vip @serverless/team

**Comment by rowanu** [comment] 2016-12-06 01:10
Yep, agree with the conclusions: _maybe_ use it in a future version, if it makes sense.

SAM is interesting, but the complexities it was designed to address are **already** addressed by Serverless; SAM will not allow you to do anything you can't already do in CFN.

**Comment by buggy** [comment] 2016-12-09 09:57
I don't think SAM needs to be a breaking change. Isn't the whole point of multi-provider support that we can work with different backends? Can't we create a new backend called `sam` or `awssam` that uses SAM? People can chose whether they want to use AWS/CloudFormation or AWS/SAM.

We're going to need to support the old AWS/Cloudformation backend for a long time after AWS/SAM support is released and this would seem to be the simplest way. If we don't we'll risk a lot of users deciding to switch directly to SAM instead of upgrading Serverless when the breaking change is introduced. If we do support both then it may actually become a selling point.

My other advantage for SAM would be that it makes it easier for people to leave Serverless (i.e. your SAM files are ready to go) which may encourage people worried about vendor lock-in.

**Comment by kennu** [comment] 2016-12-09 12:40
+1 for @buggy's suggestion. There's already loads of 0.x projects that won't work with 1.x and no funding to upgrade them until clear added value can be seen. Same would happen to current 1.x projects. It would be good for Serverless to allow the ecosystem to grow incrementally for a while.

**Comment by nikgraf** [comment] 2016-12-09 13:01
Just to clarify: We intend to support 1.x for quite a while. @buggy spot on. I think that's the way to go. We will spend a bit more time in evaluating if and how to support both and share it here.

**Comment by eahefnawy** [comment] 2016-12-09 14:24
@buggy great thoughts! Do you think that supporting AWS/SAM under the serverless hood would add value for you as a Serverless user? I feel that it adds more value for maintaining the framework rather than for our users since our users will only deal with our abstraction layer

**Comment by kennu** [comment] 2016-12-09 14:38
I think there will be two major kinds of apps:
- Based on Serverless, deployable only with sls, but exportable as SAM
- Based on SAM and deployable with standard AWS tools

People will want to use Serverless because of the added developer experience value, but also use SAM apps because of a larger standard ecosystem.

**Comment by buggy** [comment] 2016-12-09 22:22
@eahefnawy From a user perspective my gut feeling says it will appeal to a select group of people who want to use Serverless now but may have concerns about Serverless versus SAM in the long term. They may be swayed towards SAM as the "standard". By having a backend that outputs SAM with clear instructions on how to switch from Serverless to SAM you're telling people "Hey, you get all of the advantages of Serverless now AND you can switch to SAM later if you really need to".

As you said, most of the real value will probably be under the hood for Serverless developers.

**Comment by horike37** [comment] 2016-12-13 15:16
+1 for @buggy's suggestion. 
I don't think SAM needs to be a breaking change too.
I have an application running with Serverless. I am worried about the stable operation of the application.

**Comment by vibhakant** [comment] 2016-12-19 20:28
http://forum.serverless.com/t/propagate-same-version-to-dev-uat-prod/977/2 

This is the problem we are facing which AWS SAM is resolving for us by separating the packaging and deployment as two different steps and possibly offering us the capability of parameterizing the CF template and letting us re-use the same artifacts in multiple account/stages/regions without having to rebuild them. This is very important for us in order to build a CI/CD pipeline. 

I am curious as to see what @serverless/team think about resolving this problem while continue to use Serverless Framework?

**Comment by johncmckim** [comment] 2016-12-19 21:30
@vibhakant you might be interested in #2660. That issue discuses separating package and deploy in the Serverless framework.

**Comment by DavidWells** [comment] 2017-05-05 19:38
Checkout https://github.com/SAPessi/serverless-sam just added to the plugins repo: https://github.com/serverless/plugins

**Comment by andremetzen** [comment] 2017-08-14 16:23
Cool new feature for SAM: https://aws.amazon.com/about-aws/whats-new/2017/08/introducing-aws-sam-local-a-cli-tool-to-test-aws-lambda-functions-locally/

**Comment by ceefour** [comment] 2017-08-23 10:28
Interested on this also, especially since the news @andremetzen mentioned.
I'm starting a new project and I'm trying to decide Serverless Framework vs SAM?

**Comment by erikerikson** [comment] 2017-08-23 14:21
The plugin listed above by @DavidWells produces SAM from serverless.yml.  There is no translation in reverse.  With serverless.yml you get far richer variable capabilities as well as other key features that can save a lot of time and effort.  For these reasons, there's little incentive to write SAM.  If nothing else, you always have an exit strategy.

**Comment by kbrandwijk** [comment] 2017-10-18 23:44
I have also been looking at SAM local compared to serverless-offline for example. From what I have read, and been able to find out, SAM local is a more production like local test environment than serverless-offline offers, but I'm not 100% sure.
The serverless-sam plugin actually creates a zip file that you can 'feed' into sam local. Although that approach works, making a simple change to a function requires re-exporting every time, making debugging also impossible to do (one of the other benefits of sam local).

It would seem 'natural' to have a `sls sam local` type of plugin that just creates a SAM template on the fly and starts `sam local`. I would love to hear anybody's idea on how this integration would be able to work.

**Comment by HyperBrain** [comment] 2017-10-19 10:18
I am not sure if SAM really should be part of core as a core command and not as a plugin.

The problem I see is, that lots of available plugins might not work with the functionality (e.g. `serverless-webpack` or other build-time plugins). Having SAM as core functionality would imply to the user that it will work with plugins automatically in the same way as `serverless invoke` does.

I see this functionality in a separate new plugin "sam-local" that someone has to write. Especially taking @erikerikson 's valid comments into account (reducing capabilities), it seems more to be a niche solution.

**Comment by alexcasalboni** [comment] 2017-11-17 22:32
What if the core supported only the SAM tranformation only, so that we can start using the [new serverless resources](https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#resource-types) supported by CloudFormation?

(I mean `AWS::Serverless::Api` and `AWS::Serverless::SimpleTable`, since `AWS::Serverless::Function` is already managed pretty well by the framework)

Such an integration would only require the following line to be included in the template by default:

```
Transform: 'AWS::Serverless-2016-10-31'
```

(note: nothing wrong/bad happens if you define the transformation without using any special resource)

**Comment by HyperBrain** [comment] 2017-11-18 12:32
@alexcasalboni I read a bit through the AWS docs on the topic. I came to this passage:

> To create or update a stack with transforms, you must create a change set, and then execute it. A change set describes the actions AWS CloudFormation will take based on the processed template.

See: http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/transform-aws-serverless.html

In my opinion that means, that stacks that contain SAM transforms can only be updated by changesets and not by stack updates. This statement puts the whole SAM integration (regardless if it is only very basic or not) into question. The Serverless framework only does stack updates and does not use change sets at all.

So it might be impossible to support the resources at all with the current architecture of Serverless.
If I read the statement correctly, we should evaluate if touching and changing the whole way SLS works with AWS should be changed to support a feature that is (1) not part of core and (2) too simplistic to project the capabilities of Serverless.

Any thoughts, ideas?

**Comment by thorbenheins** [comment] 2019-02-01 08:04
First things first, to every maintainer here: Thanks for the great work!

Just a thought: As servereless is function centric when it comes to deployments, it is an acceptable workaround to be able to define the cloud formation resources oneself to be able to deploy using serverless, while not deploying a lambda, see #2841. Defining an apigateway with AWS SAM is a lot easier than defining all the ApiGateway* resources themselves.

So supporting this might still be considered a good idea?

**Comment by erikerikson** [comment] 2019-02-01 14:59
Arbitrary CloudFormation can be declared under:
```
resources:
  Resources:
    [...]
```
Just like a standard CloudFormation resources section.  No requirement for a function.

**Comment by thorbenheins** [comment] 2019-02-01 15:02
That's true, yet the `Transform: AWS::Serverless-2016-10-31` failes with `Requires capabilities : [CAPABILITY_AUTO_EXPAND]`

**Comment by erikerikson** [comment] 2019-02-01 15:22
I see thanks for clarifying.  That probably deserves its own issue if you'd like to create one.

**Comment by medikoo** [comment] 2020-09-08 10:13
Closing, as (firstly) SAM feels more as an alternative to Serverless Framework, and that makes it a bit to high level abstraction to rely on, and (secondly) taking into account last years experience, it feels that most effective solution can be built only when relying on AWS SDK directly (and it's the path we've taken on with Serverless Components)

Relying on CloudFormation proven to leave us with slow deployments and hard to workaround limits. It's likely things will not be different (and even more complex) if we try to base Framework on SAM.

**Closed by medikoo** 2020-09-08 10:13 UTC
Labels: feature, needs feedback
