### ISSUE TITLE
Bug: per function permissions leads to "this.awsPackagePlugin.validateStatements is not a function"

### ISSUE THREAD

**Issue by DennisTruemperMd** [serverless/serverless#8375] opened 2020-10-09 10:40 UTC
Per Function permissons leads to Error
Serverless: Packaging service...

  Type Error ---------------------------------------------

  TypeError: this.awsPackagePlugin.validateStatements is not a function      
    

<details>
<summary><code>serverless.yml</code></summary>

```yaml
stacktrace should be enough
```

</details>

<details>
<summary><b><code>npx sls deploy -s dev</code> output</b></summary>

```
Serverless: To ensure safe major version upgrades ensure "frameworkVersion" setting in service configuration (recommended setup: "frameworkVersion: ^2.5.0")

Serverless: Load command interactiveCli
Serverless: Load command config
Serverless: Load command config:credentials
Serverless: Load command create
Serverless: Load command install
Serverless: Load command package
Serverless: Load command deploy
Serverless: Load command deploy:function
Serverless: Load command deploy:list
Serverless: Load command deploy:list:functions
Serverless: Load command invoke
Serverless: Load command invoke:local
Serverless: Load command info
Serverless: Load command logs
Serverless: Load command metrics
Serverless: Load command print
Serverless: Load command remove
Serverless: Load command rollback
Serverless: Load command rollback:function
Serverless: Load command slstats
Serverless: Load command plugin
Serverless: Load command plugin
Serverless: Load command plugin:install
Serverless: Load command plugin
Serverless: Load command plugin:uninstall
Serverless: Load command plugin
Serverless: Load command plugin:list
Serverless: Load command plugin
Serverless: Load command plugin:search
Serverless: Load command config
Serverless: Load command config:credentials
Serverless: Load command rollback
Serverless: Load command rollback:function
Serverless: Load command upgrade
Serverless: Load command uninstall
Serverless: Load command webpack
Serverless: Load command offline
Serverless: Load command offline:start
Serverless: Load command prune
Serverless: Load command create_domain
Serverless: Load command delete_domain
Serverless: Load command login
Serverless: Load command logout
Serverless: Load command generate-event
Serverless: Load command test
Serverless: Load command dashboard
Serverless: Load command output
Serverless: Load command output:get
Serverless: Load command output:list
Serverless: Load command param
Serverless: Load command param:get
Serverless: Load command param:list
Serverless: Load command studio
 
 
Serverless: [AWS cloudformation 200 0.217s 0 retries] describeStacks({ StackName: 'my-lcevent-topic-dev' })
Serverless: Invoke deploy
Serverless: Invoke package
Serverless: Invoke aws:common:validate
Serverless: Invoke aws:common:cleanupTempDir
Serverless: Invoke webpack:validate
Serverless: Invoke webpack:compile
Serverless: Bundling with Webpack...
/* WEBPACK_STUFF */
Serverless: Invoke webpack:package
Serverless: Excluding external modules: aws-sdk@2.631.0
Serverless: No external modules needed
Serverless: Packaging service...
 
  Type Error ---------------------------------------------

  TypeError: this.awsPackagePlugin.validateStatements is not a function      
      at ServerlessIamPerFunctionPlugin.validateStatements (C:\git\my-service-service\node_modules\serverless-iam-roles-per-function\src\lib\index.ts:62:27)      at ServerlessIamPerFunctionPlugin.createRoleForFunction (C:\git\my-service-service\node_modules\serverless-iam-roles-per-function\src\lib\index.ts:209:10)
      at ServerlessIamPerFunctionPlugin.createRolesPerFunction (C:\git\my-service-service\node_modules\serverless-iam-roles-per-function\src\lib\index.ts:306:12)
  From previous event:
      at PluginManager.invoke (C:\git\my-service-service\node_modules\serverless\lib\classes\PluginManager.js:510:22)
      at PluginManager.spawn (C:\git\my-service-service\node_modules\serverless\lib\classes\PluginManager.js:530:17)
      at BbPromise.try (C:\git\my-service-service\node_modules\serverless\lib\plugins\deploy\deploy.js:122:50)
  From previous event:
      at Object.before:deploy:deploy [as hook] (C:\git\my-service-service\node_modules\serverless\lib\plugins\deploy\deploy.js:102:22)
      at BbPromise.reduce (C:\git\my-service-service\node_modules\serverless\lib\classes\PluginManager.js:510:55)
  From previous event:
      at PluginManager.invoke (C:\git\my-service-service\node_modules\serverless\lib\classes\PluginManager.js:510:22)
      at getHooks.reduce.then (C:\git\my-service-service\node_modules\serverless\lib\classes\PluginManager.js:545:24)
  From previous event:
      at PluginManager.run (C:\git\my-service-service\node_modules\serverless\lib\classes\PluginManager.js:545:8)
      at variables.populateService.then (C:\git\my-service-service\node_modules\serverless\lib\Serverless.js:168:33)
  From previous event:
      at Serverless.run (C:\git\my-service-service\node_modules\serverless\lib\Serverless.js:155:74)
      at serverless.init.then.then (C:\git\my-service-service\node_modules\serverless\scripts\serverless.js:50:26)
      at runCallback (timers.js:705:18)
      at tryOnImmediate (timers.js:676:5)
      at processImmediate (timers.js:658:5)
      at process.topLevelDomainCallback (domain.js:126:23)
  From previous event:
      at Object.<anonymous> (C:\git\my-service-service\node_modules\serverless\scripts\serverless.js:50:4)
      at Module._compile (internal/modules/cjs/loader.js:778:30)
      at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
      at Module.load (internal/modules/cjs/loader.js:653:32)
      at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
      at Function.Module._load (internal/modules/cjs/loader.js:585:3)        
      at Module.require (internal/modules/cjs/loader.js:692:17)
      at require (internal/modules/cjs/helpers.js:25:18)
      at Object.<anonymous> (C:\git\my-service-service\node_modules\serverless\bin\serverless.js:47:1)
      at Module._compile (internal/modules/cjs/loader.js:778:30)
      at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
      at Module.load (internal/modules/cjs/loader.js:653:32)
      at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
      at Function.Module._load (internal/modules/cjs/loader.js:585:3)        
      at Function.Module.runMain (internal/modules/cjs/loader.js:831:12)     
      at findNodeScript.then.existing (C:\Users\dtruemper\AppData\Roaming\npm\node_modules\npm\node_modules\libnpx\index.js:268:14)

  Get Support --------------------------------------------
     Docs:          docs.serverless.com
     Bugs:          github.com/serverless/serverless/issues
     Issues:        forum.serverless.com

  Your Environment Information ---------------------------
     Operating System:          win32
     Node Version:              10.17.0
     Framework Version:         2.5.0 (local)
     Plugin Version:            4.0.4
     SDK Version:               2.3.2
     Components Version:        3.2.1
```

</details>

<b>Installed version</b>

```
Serverless: Load command interactiveCli
Serverless: Load command config
Serverless: Load command config:credentials
Serverless: Load command create
Serverless: Load command install
Serverless: Load command package
Serverless: Load command deploy
Serverless: Load command deploy:function
Serverless: Load command deploy:list
Serverless: Load command deploy:list:functions
Serverless: Load command invoke
Serverless: Load command invoke:local
Serverless: Load command info
Serverless: Load command logs
Serverless: Load command metrics
Serverless: Load command print
Serverless: Load command remove
Serverless: Load command rollback
Serverless: Load command rollback:function
Serverless: Load command slstats
Serverless: Load command plugin
Serverless: Load command plugin
Serverless: Load command plugin:install
Serverless: Load command plugin
Serverless: Load command plugin:uninstall
Serverless: Load command plugin
Serverless: Load command plugin:list
Serverless: Load command plugin
Serverless: Load command plugin:search
Serverless: Load command config
Serverless: Load command config:credentials
Serverless: Load command rollback
Serverless: Load command rollback:function
Serverless: Load command upgrade
Serverless: Load command uninstall
Serverless: Load command webpack
Serverless: Load command offline
Serverless: Load command offline:start
Serverless: Load command prune
Serverless: Load command create_domain
Serverless: Load command delete_domain
Serverless: Load command login
Serverless: Load command logout
Serverless: Load command generate-event
Serverless: Load command test
Serverless: Load command dashboard
Serverless: Load command output
Serverless: Load command output:get
Serverless: Load command output:list
Serverless: Load command param
Serverless: Load command param:get
Serverless: Load command param:list
Serverless: Load command studio
Framework Core: 2.5.0 (local)
Plugin: 4.0.4
SDK: 2.3.2
Components: 3.2.1
```

**Comment by DennisTruemperMd** [comment] 2020-10-09 11:08
I changed to service level permissons, this works fine for me. But other people might have this bug too

**Comment by medikoo** [comment] 2020-10-09 11:32
Duplicate of #8358

**Closed by medikoo** 2020-10-09 11:32 UTC
