### ISSUE TITLE
serverless command should include an argument to specify a path to the serverless directory

### ISSUE THREAD

**Issue by dugword** [serverless/serverless#4543] opened 2017-12-08 17:26 UTC
# This is a Feature Proposal

## Description

When managing complex projects that deploy multiple independent lambdas with independent serverless projects, it becomes complex to chdir into each serverless directory in order to run serverless commands.

The serverless CLI tool should include an option to pass a directory that points to where the serverless command should be run from.

This option should behave like git's "-C" option.

For bug reports:
* What went wrong?
* What did you expect should have happened?
* What was the config you used?
* What stacktrace or error message from your provider did you see?

For feature proposals:
* What is the use case that should be solved. The more detail you describe this in the easier it is to understand for us.
* If there is additional config how would it look

Similar or dependent issues:
* #12345

## Additional Data

* ***Serverless Framework Version you're using***:
* ***Operating System***:
* ***Stack Trace***:
* ***Provider Error messages***:

**Comment by pmuens** [comment] 2019-02-13 12:15
Closing this one since it's a duplicate of https://github.com/serverless/serverless/issues/4124

**Closed by pmuens** 2019-02-13 12:15 UTC
Labels: cat/dx, feature
