### ISSUE TITLE
package include/exclude not respected (master branch)

### ISSUE THREAD

**Issue by bobby-brennan** [serverless/serverless#2529] opened 2016-10-25 02:56 UTC
# This is a Bug Report
## Description

Files/directories listed under `package.exclude` in serverless.yml are not excluded from the resulting .zip artifact

For bug reports:
- What went wrong?  **Excluded files show up in .zip**
- What did you expect should have happened? **They shouldn't**
- What was the config you used? **See below**
- What stacktrace or error message from your provider did you see? **none**
## Additional Data
- **_Serverless Framework Version you're using**_: 1.0.3 (master branch)
- **_Operating System**_: Ubuntu 14.04
- **_Stack Trace**_: none
- **_Provider Error messages**_: none

Here's my (truncated) serverless.yml:

``` yml
service: posted

provider:
  name: aws
  runtime: nodejs4.3

stages:
  dev:
    vars:
      bucketname: dev
  prod:
    vars:
      bucketname: prod

package:
  exclude:
    - .git
```

Per instructions here:
https://github.com/serverless/serverless/blob/d40cf4415af52f8886cc68921694c4ad38e9dd6f/docs/providers/aws/guide/packaging.md

If I run

``` bash
serverless deploy -v --noDeploy
cp ./.serverless/posted.zip ~/test/
cd ~/test && unzip posted.zip
```

I get the entire .git directory.

Using include doesn't seem to make a difference either.

**Comment by mankins** [comment] 2016-10-25 18:13
out of curiosity, are you using any plugins?

**Comment by bobby-brennan** [comment] 2016-10-25 18:45
Nope, no plugins

**Comment by mankins** [comment] 2016-10-25 19:06
".git" ? "\.git" ? I think it uses the glob module if that helps.

**Comment by jamesmwebster** [comment] 2016-10-25 19:12
Sure does.. Thank you

James Webster



On Tue, Oct 25, 2016 at 1:06 PM -0600, "Matt Mankins" <notifications@github.com<mailto:notifications@github.com>> wrote:


".git" ? ".git" ? I think it uses the glob module if that helps.

-

**Comment by bobby-brennan** [comment] 2016-10-25 19:57
I've tried every glob pattern I can think of, with and without quotes. I can't get anything excluded from the artifact.  Other directories (e.g. node_modules) exhibit the same problem.

Anyone else seeing this or is it just me?

**Comment by DavidWittman** [comment] 2016-10-26 18:45
@bobby-brennan I'm having the same issue with version 1.0.3. Solid chance I'm doing something wrong though.

```
package:
  exclude:
    - node_modules
    - README.md
```

This config excludes neither the node_modules directory nor README.md.

**Comment by tommy8694** [comment] 2016-10-28 04:51
similar issue here,
```yml
package:
```
`package:`
    `individually: true`
`  exclude:`
`    - functions`
`functions:`
`  test:`
`    package:`
`      include:`
`        - functions/xxxfunction`
and the finally zip will not have the whole 'functions' folder
I tested the 1.0.0-rc2 is output the expected zip, but since 1.0.0 will have this issue....

**Comment by tommy8694** [comment] 2016-10-28 05:01
similar issue here, my serverless.yml:

```yml
...
package:
    individually: true
      exclude:
        - functions
functions:
    aFunction:
        package:
          include:
              - functions/aFunction
    bFunction:
        package:
          include:
              - functions/bFunction
...
```
and the final zip are not containing the whole 'functions' folder.
I tested on 1.0.0-rc.2 and the output is good. However, it's not since 1.0.0.

**Comment by ellucianBret** [comment] 2016-11-01 22:22
It is working but you will need to use a full glob. Something like:

```
functions:
  aFunction:
    package:
       include:
         - functions/aFunction
       exclude:
         - "!functions/aFunction"
```

And don't use an exclude at the top level

See - https://github.com/serverless/serverless/issues/2471#issuecomment-255014783

**Comment by tobyhede** [comment] 2016-11-02 01:12
In summary: to exclude a directory need to use `dir/**` glob.

eg:
```
.git/**
node_modules/**
```

**Comment by Si1kIfY** [comment] 2016-11-02 06:09
@ellucianBret 's answer was the only one that worked for me (you also don't seem to need the include)

To exclude everything bar a single file for eg. I had to do:

```
functions:
  jwtAuthorizer:
    handler: src/authorizer/authorizer.handler
    package:
      exclude:
        - "!src/authorizer/authorizer.js"
```

Should work with the glob pattern for a directory too

**Comment by mthenw** [comment] 2016-11-03 08:11
Duplicate of https://github.com/serverless/serverless/issues/2071.

**Closed by mthenw** 2016-11-03 08:11 UTC

**Comment by wi-ski** [comment] 2018-01-13 00:28
This is stillllll killing me

**Comment by berlinguyinca** [comment] 2018-05-17 03:06
same issues here. How hard is it to just exclude all *.pyc files for all subdirectories?

**Comment by monim67** [comment] 2021-01-27 06:25
Looks like it's pretty hard @berlinguyinca, have you found any solution? No matter what I try I can't exclude `__pycache__` directories recursively.
