### ISSUE TITLE
Getting 'provider.httpApi.authorizers.mainJwtAuthorizer.issuerUrl': should be string warning on a string variable

### ISSUE THREAD

**Issue by damien-monni** [serverless/serverless#8176] opened 2020-09-02 13:29 UTC
I am getting `Configuration warning: Serverless: at 'provider.httpApi.authorizers.mainJwtAuthorizer.issuerUrl': should be string` when I use `Fn::ImportValue` and a custom variable on a HTTP API authorizer config but issuerUrl is already a string variable.

Deployed stack works well, the warning message should not appears.

<details>
<summary><code>serverless.yml</code></summary>

```yaml
custom:
  cognitoIssuer:
    "Fn::ImportValue": ${self:custom.stage}-CognitoIssuer

provider:
  name: aws
  ...
  httpApi:
    payload: "2.0"
    cors: true
    authorizers:
      mainJwtAuthorizer:
        ...
        issuerUrl: ${self:custom.cognitoIssuer}
        ...
```

</details>

<details>
<summary><b><code>serverless deploy -v</code> output</b></summary>

```
Configuration warning: Serverless: at 'provider.httpApi.authorizers.mainJwtAuthorizer.issuerUrl': should be string
```

</details>

<b>Installed version</b>

```
Framework Core: 1.80.0
Plugin: 3.8.2
SDK: 2.3.1
Components: 2.34.9
```

**Comment by medikoo** [comment] 2020-09-02 13:32
Duplicate of #8135

**Closed by medikoo** 2020-09-02 13:32 UTC
