### ISSUE TITLE
How to restrict a lambda function to respond only to a specific origin?

### ISSUE THREAD

**Issue by THPubs** [serverless/serverless#3852] opened 2017-06-26 10:13 UTC
I want to restrict my lambda function to accept requests only from `abc.com` and `def.com`. It should reject all other requests. How can I do this? I tried setting access control origins like this:

          cors: true
          response:
            headers:
              Access-Control-Allow-Origin: "'beta.leafycode.com leafycode.com'"

and like this in the handler:

    headers: {
      "Access-Control-Allow-Origin" : "beta.leafycode.com leafycode.com" // Required for CORS support to work
    },

but nothing worked. Any idea why?

**Comment by HyperBrain** [comment] 2017-06-26 10:27
The Access-Control-Allow-Origin header can only contain exactly one URL.
See https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Access-Control-Allow-Origin

If you want to allow multiple origins, you'd either have to offer multiple endpoints, with each returning a different allowed origin, use LAMBDA_PROXY lambda functions for your OPTIONS and data endpoints that check the incoming Host header and return the allowed origin accordingly, use "*" (unsecure!!!) or use a MOCK type endpoint for OPTIONS and program the origin checks with VTL. For the data endpoint you can also use a AWS_LAMBDA (non-proxy) endpoint and handle the origin checks within VTL.

AWS_PROXY_LAMBDA:
* Pro: Handle the origin in your code.
* Con: Lambda is executed (and paid) for every call
AWS_LAMBA + MOCK:
* Pro: less costs. Fast replies.
* Con: More complex in regards of parsing and mapping results and headers.

**Comment by pmuens** [comment] 2017-06-26 10:30
@THPubs thanks for opening 👍 

@HyperBrain thanks for chiming in!

@HyperBrain is right.Adding multiple origins in one definition violates the W3C conventions.

Here are some other related issues:

- https://github.com/serverless/serverless/issues/3745
- https://github.com/serverless/serverless/issues/2476

I'll close this issue for now since @HyperBrain comment should help you with the setup. Feel free to continue the discussion.

**Closed by pmuens** 2017-06-26 10:30 UTC
Labels: kind/question

**Comment by THPubs** [comment] 2017-06-26 10:34
Hi, I just tried with one domain and sill it's not restricting the requests. :cry:

**Comment by HyperBrain** [comment] 2017-06-26 10:37
Can you post the endpoint definition from your serverless.yml? Preferably the OPTIONS and one of the other methods.

**Comment by THPubs** [comment] 2017-06-26 10:42
My serverless.yml looks like this:

    functions:
      sendMail:
        handler: handler.sendMail
        description: Send email using SES service.
        memorySize: 512
        timeout: 5
        events:
          - http:
              path: sendMail
              method: post
              integration: lambda
              cors: true
              response:
                headers:
                  Access-Control-Allow-Origin: "'leafycode.com'"


The handler response looks like this:

    const response = {
      statusCode: 200,
      headers: {
        'Access-Control-Allow-Origin': 'leafycode.com'
      },
      body: JSON.stringify({
        message: 'Mail sent'
      })
    };

Sorry guys I'm new to serverless functions :smile:

**Comment by HyperBrain** [comment] 2017-06-26 11:13
No problem :)

You should remove the integration and response properties. By default SLS uses lambda proxy integrations which let you return the responses as you declared it (statusCode, headers, body).

So you yaml should look like this for a first test:
```
sendMail:
    handler: handler.sendMail
    description: Send email using SES service.
    memorySize: 512
    timeout: 5
    events:
      - http:
          path: sendMail
          method: post
```

and try to return the other Access-Control headers in your response too (Access-Control-Allow-Methods, etc.)

This would be the first step - having a CORS enabled method withour preflight endpoint.
Please deploy and test this config (best would be with PostMan) to see if the header(s) are set correctly.

Afterwards you can add the options endpoint by setting "cors: true" and the response header as you did before. Remember to not set any integration type.

**Comment by THPubs** [comment] 2017-06-26 12:08
Hi, I removed the response and integration properties. I even tried with cors property removed. But I'm getting the following error in the browser console (I have a static react app which send requests through axios):

    No 'Access-Control-Allow-Origin' header is present on the requested resource. Origin 'http://localhost:3000' is therefore not allowed access. The response had HTTP status code 502.

In postman it simply says `Internal server error`. My response now looks like this:

    const response = {
      statusCode: 200,
      headers: {
        'Access-Control-Allow-Origin': 'http://localhost:3000',
        'Access-Control-Allow-Methods': 'POST'
      },
      body: JSON.stringify({
        message: 'Mail sent'
      })
    };

Any idea what's happening?

**Comment by HyperBrain** [comment] 2017-06-26 12:14
502 means "malformed lambda proxy response".

How do you return your response object in the lambda handler?
It should be something like this:

```
function handler(event, context, cb) {
  ...
  // do something with event
  ...
  cb(null, myResponse);
}
```

**Comment by THPubs** [comment] 2017-06-26 12:16
Here's how I return the response:

    ses.sendEmail(emailParams, (err) => {
      if (err) {
        callback(err);
      } else {
        callback(null, response);
      }
    });

**Comment by HyperBrain** [comment] 2017-06-26 12:29
You should transform the error response also to a valid proxy response, by setting the body property to err.toString() and statusCode to something appropriate (<> 200). Then errors will be sent as HTTP error responses too. It might be that the ses call returns an error.
You can find a simplistic response return in my example project https://github.com/HyperBrain/serverless-aws-alias-example. Despite being a sample for the alias plugin, it provides a working example on how to return proxy responses (it just echoes the incoming event as body). See the README about what branch creates API endpoints.

**Comment by THPubs** [comment] 2017-06-26 12:56
I found the issue. I send the data to the function like this:

    axios.post(url, {
      senderEmail: 'email',
      senderName: 'name',
      content: 'Hello there!'
    })
    .then((response) => {
      console.log(response);
    })
    .catch((error) => {
      console.log(error);
    });
};

In the function I read them like this:

    event.body.content

Now this works when I set `integration: lambda` in serverless.yml. But all those values return undefined when I remove it. Any idea why?

**Comment by THPubs** [comment] 2017-06-26 13:04
Fixed the issue! When using the `integration`, it sends event.body as an object. Without it, event.body is just a string. I used JSON.parse to convert it and then used the data. Now its working. But still it's not restricting based on the origin. Anyone can send a request. Postman works without error. When I try it in the site with a different domain, I get the following error:

     The 'Access-Control-Allow-Origin' header has a value 'http://localhost:3000' that is not equal to the supplied origin. Origin

But the functions executes and send the email.

**Comment by HyperBrain** [comment] 2017-06-26 13:07
Can you check if the sent "Origin" header is `http://localhost:3000` or just `http://localhost`?
I do not know what origin is set by your http library. You can find and log the incoming Origin header in event.headers.

**Comment by HyperBrain** [comment] 2017-06-26 13:16
Oh. regarding the execution. You have to check against a list of allowed origins in your function code and return an 403 (forbidden) if the incoming Origin header does not match an allowed one.
There is no automatics for that.

**Comment by THPubs** [comment] 2017-06-26 13:32
@HyperBrain Thanks a lot! That's the stupid mistake I made. Now I'm checking the origin before running the ses call and everything is working perfectly!

    if (config.allowedOrigins.includes(event.headers.origin))

**Comment by HyperBrain** [comment] 2017-06-26 13:34
You're welcome

**Comment by pmuens** [comment] 2017-06-26 15:24
Great to see that it's working for you @THPubs 🎉 

@HyperBrain thanks a ton for helping here! 🥇 👍

**Comment by dinvlad** [comment] 2017-09-05 02:47
@HyperBrain sorry for reviving the thread, but VTL trick is tedious for multiple origins with Mock responses I'm afraid. The problem is that Mock specifically uses VTL for setting `statusCode` in the integration request _only_, so even if you're able to add a check for an origin there, the only thing we can realistically do is provide a separate `statusCode` for each origin, then map a different allowed-origin for each `statusCode` in the integration response (the latter _must_ specify a _static_ value for allowed-origin which cannot be taken as an output from VTL unfortunately).

This approach is tedious at best, and would bloat the Swagger template unnecessarily. But if we want to avoid invoking a Lambda, this is the only way to do it at the moment it seems.

**Comment by mendoncaj** [comment] 2020-06-09 18:29
what is VTL?
