### ISSUE TITLE
Issue with number of lambda functions in Serverless

### ISSUE THREAD

**Issue by larrybek** [serverless/serverless#3976] opened 2017-07-23 11:44 UTC
Hello.

I had strange issue with quantity of lablda functions:

```
Error --------------------------------------------------
 
  The CloudFormation template is invalid: Template format error: Number of resources, 208, is greater than maximum allowed, 200
 
     For debugging logs, run again after setting the "SLS_DEBUG=*" environment variable.
```

Someone has in idea how I can handle this out.

_Note* If I comment out several functions from yml file its starts to deploy so its for sure with count of functions that I have. _

**Comment by pmuens** [comment] 2017-07-24 07:10
Hey @larrybek thanks for opening 👍

Unfortunately this is a CloudFormation limitation. A possible solution would be to split up your large Service into multiple smaller ones.

If you want smth. more automatically you should look into this plugin: https://github.com/dougmoscrop/serverless-plugin-split-stacks

You can find more information about this here:

- https://github.com/serverless/serverless/issues/3411
- https://github.com/serverless/serverless/pull/3441
- https://github.com/serverless/serverless/issues/2387

I'll close this issue for now since it's a duplicate of #3411 and #2387

**Closed by pmuens** 2017-07-24 07:10 UTC
Labels: kind/question, status/help-wanted

**Comment by larrybek** [comment] 2017-07-24 07:12
Thanks @pmuens

**Comment by larrybek** [comment] 2017-07-26 10:44
@pmuens so wanted also ask the plugin didn't worked as my stacks are more than 20 and it didn't deployed. So what youll suggest for best to solve this issue? As much as I read the open issues that already exists there are no solutions for now. Does it right?

**Comment by pmuens** [comment] 2017-07-26 13:46
@larrybek thanks for commenting 👍

> so wanted also ask the plugin didn't worked as my stacks are more than 20 and it didn't deployed. So what youll suggest for best to solve this issue? As much as I read the open issues that already exists there are no solutions for now. Does it right?

The plugin is the best way to deal with this right now in an automated fashion. Unfortunately there's no automated way to deal with this problem right now since you already exceeded the stack limit.

I'd suggest to manually split up the large service into smaller ones and then cross-reference / cross-link them via `Fn::ImportValue`.

**Comment by larrybek** [comment] 2017-07-26 13:56
@pmuens thanks for help. Is there any documentation or article how it can be done as I havent used Fn:ImportValue in serverless.yml?

**Comment by pmuens** [comment] 2017-07-26 16:26
Hey @larrybek thanks for getting back. Sure!

The best project which shows that is the `hello-retail` project by Nordstrom. It's a super sophisticated multi service Serverless setup.

Here's the Repo with the Source Code: 
https://github.com/Nordstrom/hello-retail

Additionally there's also the workshop you might want to checkout in order to understand how everything works behind the scenes:
https://github.com/Nordstrom/hello-retail-workshop

Let us know if you have any questions / need any help!
