### ISSUE TITLE
Pipeline fails to resolve the parameter 'region'  in serverless.yml file in serverless v4

### ISSUE THREAD

**Issue by sohail-norstella** [serverless/serverless#12932] opened 2024-12-03 09:21 UTC
### Issue description

After updating serverless to v4 , the pipeline fails to resolve the parameter 'region'  in serverless.yml file, although there are other parameters which gets resolved but only 'region' param not get resolved

### Context

service: nxp-search-history-service
frameworkVersion: '4.4.5'
licenseKey: ${ssm:/aws/reference/secretsmanager/Serverless/LICENSE}
params:
  default: ${file(./config/config.yml):${env:ENV, 'dev'}}
provider:
  name: aws
  endpointType: REGIONAL
  runtime: ${param:runtime}
  **region: ${param:region}**
  apiGateway:
    metrics: true
  deploymentBucket: ${param:deploymentBucket}
  tracing:
    apiGateway: true
    lambda: true
  tags: ${file(./config/tags.yml)}
  stackTags: ${file(./config/tags.yml)}
  iam:
    role:
      name: nxp-${param:application}-${param:environment}-lambda-role
      statements:
      - Effect: Allow
        Action: secretsmanager:ListSecrets
        Resource: "*"
      - Effect: Allow
        Action:
          - secretsmanager:GetSecretValue
          - secretsmanager:DescribeSecret
        Resource: arn:aws:secretsmanager:${param:region}:${param:account}:secret:*
  logs:
    restApi:
      format: >
          '{ "requestId":"$context.requestId",
          "extendedRequestId":"$context.extendedRequestId",
          "sourceIp":"$context.identity.sourceIp",
          "userAgent":"$context.identity.userAgent",
          "requestTime":"$context.requestTime",
          "httpMethod":"$context.httpMethod",
          "resourcePath":"$context.resourcePath",
          "path":"$context.path",
          "cdnBasePathMatched":"$context.customDomain.basePathMatched",
          "status":"$context.status",
          "protocol":"$context.protocol",
          "responseLength":"$context.responseLength",
          "integrationLatency":"$context.integrationLatency",
          "integration-latency":"$context.integration.latency",
          "integrationStatus":"$context.integrationStatus",
          "integration-status":"$context.integration.status",
          "responseLatency":"$context.responseLatency",
          "authorizerError":"$context.authorizer.error",
          "authorizerLatency":"$context.authorizer.latency",
          "authorizerStatus":"$context.authorizer.status",
          "authorizerRequestId":"$context.authorizer.requestId",
          "apiKeyId":"$context.identity.apiKeyId",
          "xrayTraceId":"$context.xrayTraceId",
          "wafLatency":"$context.waf.latency",
          "wafStatus":"$context.waf.status",
          "wafError":"$context.waf.error",
          "userId":"$context.authorizer.principalId"
          }'
  environment:
    environment: dev
custom:
  authorizer: ${param:customLambdaAuthorizerARN}
  prune:
    automatic: true
    includeLayers: true
    number: 5
  customDomains:
    - rest:
        stage: ${param:stage}
        domainName: searchhistoryapi.${param:domainName}
        endpointType: regional
        hostedZoneId: ${param:hostedZoneId}
        certificateDomain: searchhistoryapi.${param:domainName}
        basePath: ''
        createRoute53Record: true
        autoDomain: true
        autoDomainWaitFor: 120
    - rest:
        stage: ${param:stage}
        domainName: search-history-api.${param:domainName}
        endpointType: regional
        hostedZoneId: ${param:hostedZoneId}
        certificateDomain: search-history-api.${param:domainName}
        basePath: ''
        createRoute53Record: true
        autoDomain: true
        autoDomainWaitFor: 120
  associateWaf:
    name: ${param:wafAclName}
    version: V2
package:
  individually: true
functions:
  search-history-lambda:
    name: nxp-${param:application}-${param:environment}-lambda-v4
    handler: NXP.Search.History.Service.Api::NXP.Search.History.Service.Api.LambdaEntryPoint::FunctionHandlerAsync
    memorySize: ${param:lambda_memory}
    environment:
      RDS__CredentialsKey: ${param:rdsCredentialsKey}
    timeout: 15
    package:
      artifact: ${param:packageLocation}
    events:
      - http:
          method: get
          path: "/swagger/{proxy+}"
          integration: lambda-proxy
          cors: true
      - http:
          method: get
          path: "/api/v1/SearchHistory"
          integration: lambda-proxy
          cors: true
          authorizer:
            arn: ${self:custom.authorizer}
            managedExternally: ${param:externalAuthorizer}
      - http:
          method: post
          path: "/api/v1/SearchHistory"
          integration: lambda-proxy
          cors: true
          authorizer:
            arn: ${self:custom.authorizer}
            managedExternally: ${param:externalAuthorizer}
      - http:
          method: any
          path: "/api/v1/SearchHistory/{proxy+}"
          integration: lambda-proxy
          cors: true
          authorizer:
            arn: ${self:custom.authorizer}
            managedExternally: ${param:externalAuthorizer}
      - http:
          method: get
          path: "/api/v1/SearchHistory/ByUser/{email}/{startDate}/{endDate}"
          integration: lambda-proxy
          cors: true
          authorizer:
            arn: ${self:custom.authorizer}
            managedExternally: ${param:externalAuthorizer}
      - http:
          method: get
          path: "/api/v1/SearchHistory/ByNamespace/{namespace}/{startDate}/{endDate}"
          integration: lambda-proxy
          cors: true
          authorizer:
            arn: ${self:custom.authorizer}
            managedExternally: ${param:externalAuthorizer}
      - http:
          method: get
          path: "/api/v1/SearchHistory/ByQueryName/{queryName}/{startDate}/{endDate}"
          integration: lambda-proxy
          cors: true
          authorizer:
            arn: ${self:custom.authorizer}
            managedExternally: ${param:externalAuthorizer}
      - http:
          method: delete
          path: "/api/v1/SearchHistory/BulkDelete"
          integration: lambda-proxy
          cors: true
          authorizer:
            arn: ${self:custom.authorizer}
            managedExternally: ${param:externalAuthorizer}
    vpc:
      securityGroupIds:
        - Ref: LambdaSecurityGroup
      subnetIds:
        "Fn::Split":
          - ","
          - ${param:lambdaSubnetIds}
plugins:
  - serverless-prune-plugin
  - serverless-domain-manager
  - serverless-associate-waf
resources:
  Resources:
    LambdaSecurityGroup:
      Type: AWS::EC2::SecurityGroup
      Properties:
        GroupDescription: "Allow all outbound traffic, no inbound for Lambdas"
        SecurityGroupEgress:
          - IpProtocol: "-1"
            FromPort: "0"
            ToPort: "0"
            CidrIp: "0.0.0.0/0"
        VpcId: ${param:VpcId}
        Tags:
          - Key: "Name"
            Value: "${param:productLine}-${param:application}-${param:environment}-sg"
    AuthorizerApiGatewayAuthorizer:
      Type: AWS::ApiGateway::Authorizer
      Properties:
        AuthorizerResultTtlInSeconds: 300
        AuthorizerUri: !Join
        - ''
        - - 'arn:'
          - !Ref 'AWS::Partition'
          - ':apigateway:'
          - ${param:customLambdaAuthorizerRegion}
          - ':lambda:path/2015-03-31/functions/'
          - ${param:customLambdaAuthorizerARN}
          - /invocations
          
       
Config file screenshot given below
   
![image](https://github.com/user-attachments/assets/bfb29316-dc49-434a-86d6-44fd9aeeb2e6)

          
![image](https://github.com/user-attachments/assets/8298a80e-f0a3-4527-93cc-0fb55eebb0fa)

**Comment by czubocha** [comment] 2024-12-03 13:47
Hey @sohail-norstella, I see you're passing region as an option like `--region eu-west-1`. In this case, you need to use the `opt` resolver (`${opt:region}`). If you'd like to reference it using `${param:region}`, you'll need to pass region as a parameter, e.g., `--param region=eu-west-1`. I’m closing this issue, but feel free to reach out if you have any further questions!

**Comment by sohail-norstella** [comment] 2024-12-03 15:04
We are using same as its mentioned in yml file in v3, if downgrade the serverless version to v3 we are not facing the issue but when we upgrading to v4 then only this issue comes

**Comment by czubocha** [comment] 2024-12-03 18:41
Got it. In v4 we need to resolve `region` early (before the whole config is processed) to fetch the license key from SSM. We’re looking into how we can make it work with your setup.

**Comment by sohail-norstella** [comment] 2024-12-04 11:38
Please @czubocha help us in this we are blocked to migrate our project from dotnet 6 to dotnet 8 . Since V3 do not support dotnet 6 , thats why we used v4 but here we stucked

**Comment by sohail-norstella** [comment] 2024-12-06 13:46
Any update on this @czubocha

**Comment by czubocha** [comment] 2024-12-06 13:54
@sohail-norstella We’re planning to release a fix for this on Monday.

**Comment by czubocha** [comment] 2024-12-09 20:59
Hi @sohail-norstella, the fix for this issue has been included in Serverless Framework [v4.4.15](https://github.com/serverless/serverless/releases/tag/v4.4.15), which is now available. Once updated, try your setup again and let us know if the issue is resolved.

**Closed** 2024-12-16 18:03 UTC
Labels: V4
