### ISSUE TITLE
How to control which subdirectory of the deployment bucket things go in?

### ISSUE THREAD

**Issue by ctindel** [serverless/serverless#3060] opened 2017-01-05 22:09 UTC
I see where we can use the deploymentBucket configuration option in serverless.yml, but is there a way to pass in a path within that bucket where things should go?

**Comment by pmuens** [comment] 2017-03-09 12:35
Hey @ctindel right now there's no direct way to configure this and we're also not planning to add support for this soon.

We'll close this issue for now, but might come back to it later!

**Comment by ctindel** [comment] 2017-03-09 14:07
@pmuens is it something that is particularly difficult to implement?

**Comment by HyperBrain** [comment] 2017-03-09 14:22
In my opinion the deployment bucket contents should be opaque for anyone else than Serverless. This guarantees that the data is kept consistent. Making the structure within configurable just creates more possible risks for errors in my opinion.

**Comment by ctindel** [comment] 2017-03-09 14:36
What's the risk for error?  I just want to be able to have multiple people deploy serverless stuff to the same bucket without trampling on each other.  Like this:

bucket1/user1/serverless
bucket1/user2/serverless

**Comment by HyperBrain** [comment] 2017-03-09 14:57
The problem I see is, that all deployments are per stage. If you split deployments per user you'll lose consistency of the stack deployment information if multiple users deploy to the same stage. The deployments will end up in `bucket/user1/serverless/{stage}` and `bucket/user2/serverless/{stage}`.
Especially for more complex functionality like rollback or just display of deployment history this seems quite tricky to me.

To enable multi-user development on the same stage, I wrote the alias plugin (https://github.com/HyperBrain/serverless-aws-alias) which uses AWS aliases that enable perfect parallel development within a stage. Currently it is still alpha but I think I can release a fully functional beta in the near future.
I will add exactly this topic with the buckets there as bucket separation (with subfolder definition per alias) would make great sense within that concept - so a big thank you for the idea. In this case each user would deploy to his alias and everything will be separated automatically.

**Comment by pmuens** [comment] 2017-03-09 15:26
Yes, I agree with @HyperBrain that the content of the deployment bucket should be opaque.

@ctindel you could develop a plugin which hooks into the corresponding lifecycles and rewrites the folder structure Serverless uses behind the scenes.

**Comment by ctindel** [comment] 2017-03-09 22:41
@pmuens @HyperBrain I feel like you guys are thinking about this in the context of the "the same project".  In my case, we have hundreds of employees who might all want to deploy serverless for different totally unrelated things.  But that involves a new top level s3 bucket for each project and amazon imposes account limits.  This is cloud, so we have to understand how things would scale at a big company that wanted to have 100,000 different serverless projects spread across 10,000 different teams.  Are they to need 10,000 s3 buckets?  100,000 s3 buckets?

Why not allow them to just have one s3 bucket, and have a:

bucket/project1/serverless
bucket/project2/serverless
etc

In this case it's just "the serverless folder is opaque" but you can configure the path to the serverless folder still so you don't end up with an s3 bucket explosion.  I mean, this is the only piece of software I've worked with so far that doesn't allow you to specify a path within a bucket so that multiple pieces can use the same bucket.  Consider when you create an ELB for example, you can specify both the bucket name and the bucket prefix, that's all I'm asking for here.  Maybe it can be done by a plugin but it's such a basic thing with all these other components to be able to specify the bucket name and the prefix path, it seems like it should be an option here too.

**Comment by HyperBrain** [comment] 2017-03-09 22:51
Ok. I got into the wrong direction because of the 'user' path prefix you mentioned above. Having the same bucket with different projects makes totally sense in the environment you describe - each serverless service deploys its artifacts into a subfolder owned by that project.

From this point of view, I think it would be doable without risk -> Each serverless service could deploy automatically into "$SLS_HOME_BUCKET/$PROJECT_FOLDER/...", with
SLS_HOME_BUCKET: The bucket defined in the serverless.yml
PROJECT_FOLDER: The service name + stage (=== CF stack name)

If the automatically generated folder name would be ok, I think it would not be much of a change - just adding the CF stackname as folder into the function that returns the bucket path.

@pmuens Am I right here?

**Comment by ctindel** [comment] 2017-03-09 23:07
@HyperBrain Ideally we would have control over the naming of the prefix path and not have it be auto generated.  We can already specify a deploymentBucket option in serverless.yml, maybe just add a deploymentBucketPrefix option as well to control the path within that bucket where the serverless folder will be created?

**Comment by pmuens** [comment] 2017-03-10 08:34
@HyperBrain yes, this is the function which will generate the name: https://github.com/serverless/serverless/blob/master/lib/plugins/aws/deploy/lib/generateArtifactDirectoryName.js

So overwriting this via a plugin should do the trick.

@ctindel thanks for clarifying this. That makes sense! Would be great to have some feedback from our @serverless/vip about this feature request!

**Comment by ctindel** [comment] 2017-03-10 15:43
@pmuens did you want to re-open this issue now that things have been clarified?

**Comment by pmuens** [comment] 2017-03-13 07:02
Yes @ctindel I'll reopen this one 👍 

Let's see what other think about this!

**Comment by ryansb** [comment] 2017-03-13 14:04
I could see something like a `deploymentBucketPrefix` option, and then use that when generating the artifact dirname.

**Comment by jrasillo** [comment] 2017-03-22 14:13
We have a similar use case in that, our deployments essentially create a bucket per pull request (PR), but I would like to have a deploymentBucketPrefix such that:
deploymentBucket=<s3PRbucket>
deploymentBucketPrefix=<PRNumber>

where all of my services for my app are deployed under deploymentBucket/deploymentBucketPrefix and therefore we can avoid having to create an s3 bucket for each PR.

**Comment by dev-head** [comment] 2017-09-12 19:18
I support this update and spent a good amount of time searching for that configuration before i ended up here with the notice it's not supported. 

I understand the benefits of having some things be opinionated; the trick is finding the right balance while still giving users the ability to override the opinions of the software when at all possible.

**Comment by ctindel** [comment] 2017-09-13 03:19
@pmuens What do you think about this one?

**Comment by pmuens** [comment] 2017-09-13 06:40
Thanks for the feedback @dev-head 👍

Yes, it's always tough to find a good balance between features and maintainability / tech-debt. IMHO this would be a good use case for a Serverless Plugin.

**Comment by hybby** [comment] 2017-10-24 13:06
This would be an extremely useful configuration option.  I've got to admit, I was surprised when I got here and found out it wasn't configurable!

Agree wholeheartedly with what @ctindel mentioned.  If we've got a bunch of devs who all want to deploy their own projects, having a brand new S3 bucket-per-project is very quickly going to become unmanageable.  

It would heavily aid organisation to be able to specify one bucket and an object prefix for the project to be deployed in.

**Comment by erikerikson** [comment] 2017-10-24 15:00
As noted earlier, using the deploymentBucket configuration can avoid the creation of any new buckets.

Within that bucket, the service and stage names are used as part of the key, along with the timestamp, to ensure unique storage per deployment locations.  Given this I don't understand the use case driving this discussion.

Our engineers use the same bucket for all services and use their name as stage during development.   Our CI  pipeline uses branch name as stage following a push to SCC.  This had worked great for a while.

That said, what @ryanb wrote is sensible enough and out of the way.

p.s. @pmuens your link is dead

**Comment by hybby** [comment] 2017-10-24 15:52
@erikerikson - Thanks for clarifying! I must have missed the specific comment where that was mentioned.  Apologies for any confusion.

**Comment by erikerikson** [comment] 2017-10-24 15:59
No apologies needed.  You're clearly not the only one to have the question and all of it was figments of our collective imaginations not so long ago.  I can imagine that key prefixes could fit into IAM rights management schemes or allow for a specific directory to be very protected by resource policies than it's peers in order to protect keys or whatnot.

**Comment by ctindel** [comment] 2017-10-24 16:31
@erikerikson I mean is there some kind of difficulty in just pushing the code and things to a subpath within the bucket?  As you mentioned key prefixes for s3 buckets are used heavily for IAM and it is standard operating procedure for software that takes a bucket as a parameter to also take a prefix as a parameter.

**Comment by erikerikson** [comment] 2017-10-24 19:03
@ctindel none at all and it would be easy to implement.  I recognize(d) valid use cases (neither of which was previously mentioned).  I also responded to commentary here which seemed to show an understandable knowledge gap.  Many of the stated use cases are already facilitated by existing functionality.  If nothing else, people can use what I shared as a workaround while the prefix feature gets implemented.

For the record, although I am a contributor, I do not have the rights to decide what is accepted and defer to those who bear the responsibility to do so.  Also for the record, I work at a big company that extensively uses the Serverless framework and is one of the largest consumers of functions as a service, all with great success.

That said, there are lots of features and bug fixes that have been put on hold.  Given the resource limitations, allocation should be efficient.  Perhaps you would like to offer a contribution?

**Comment by ctindel** [comment] 2017-10-24 19:33
Can you offer a little guidance as to what you think would need to change? I would be willing to take a crack at it but I'm not sure where to start having never looked into the internals.

**Comment by erikerikson** [comment] 2017-10-24 23:23
@ctindel the key is specified here:
https://github.com/serverless/serverless/blob/master/lib/plugins/aws/deploy/lib/uploadArtifacts.js#L33

**Comment by erikerikson** [comment] 2017-10-24 23:25
not to forget https://github.com/serverless/serverless/blob/master/lib/plugins/aws/deploy/lib/uploadArtifacts.js#L62 and possibly other locations.  It would probably be best to centralize the generation of the Key value.

**Comment by vishaldesai** [comment] 2018-01-04 21:14
@erikerikson You said "people can use what I shared as a workaround while the prefix feature gets implemented." Can you elaborate about workaround to mimic prefix feature?

**Comment by ctindel** [comment] 2018-01-04 21:23
@vishaldesai He was referring to this comment:

"As noted earlier, using the deploymentBucket configuration can avoid the creation of any new buckets.

Within that bucket, the service and stage names are used as part of the key, along with the timestamp, to ensure unique storage per deployment locations. Given this I don't understand the use case driving this discussion."

**Comment by vishaldesai** [comment] 2018-01-04 21:34
Thanks @ctindel

**Comment by benbunk** [comment] 2018-08-13 20:58
This feature is critical at our company which uses a single bucket for all deployment artifacts regardless of deployment technology choice. 

Our directory structure is:
`s3://application-staging/{team-name}/*`

Our IAM policy is:
```javascript
{
    "Effect": "Allow",
    "Action": "s3:Put*",
    "Resource": "arn:aws:s3:::application-staging/alpha-team/*"
}
```

The problem is that serverless want's to be the prefix which assumes that we haven't already partitioned our deployment artifact bucket.
`s3://application-staging/serverless/{serviceName}/*`

Which would require a new IAM rule:
```javascript
{
    "Effect": "Allow",
    "Action": "s3:Put*",
    "Resource": "arn:aws:s3:::application-staging/serverless/alpha-team-*"
}
```

While the approach serverless is taking may fit organizations new to AWS without a configurable prefix it would be difficult to implement at our organization.

**Comment by benbunk** [comment] 2018-08-14 19:51
Created the plugin to fix this if anyone needs it, https://gist.github.com/benbunk/ef49242dd12f80906b46fcc4e7191b32

**Comment by weeniearms** [comment] 2018-09-16 08:09
> Created the plugin to fix this if anyone needs it, https://gist.github.com/benbunk/ef49242dd12f80906b46fcc4e7191b32

Unfortunately, this does not work in all cases where the prefix is used (e.g. `cleanupS3Bucket.js`).
Created #5293 that describes how the config might look like for this and #5299 that adds this feature.

**Comment by pmuens** [comment] 2019-07-30 09:56
Closing this issue since it's quite stale. Please refer to the [Serverless Forums](https://forum.serverless.com) or [Gitter](https://gitter.im/serverless/serverless) where issues like this can be discussed with our broad developer community.

**Closed by pmuens** 2019-07-30 09:56 UTC
Labels: cat/packaging, feature, question

**Comment by ajorpheus** [comment] 2019-11-15 13:40
The most relevant comment may not be very visible, so [note the following comment](https://github.com/serverless/serverless/issues/3060#issuecomment-339020677):

> As noted earlier, using the deploymentBucket configuration can avoid the creation of any new buckets.
> 
> Within that bucket, the service and stage names are used as part of the key, along with the timestamp, to ensure unique storage per deployment locations. Given this I don't understand the use case driving this discussion.
> 
> Our engineers use the same bucket for all services and use their name as stage during development. Our CI pipeline uses branch name as stage following a push to SCC. This has worked great for a while.
> 
> That said, what @ryanb wrote is sensible enough and out of the way.
> 
> p.s. @pmuens your link is dead
