### ISSUE TITLE
serverless remove does not show error if stack is not removed due to exported and used CF outputs

### ISSUE THREAD

**Issue by akleiber** [serverless/serverless#2984] opened 2016-12-19 22:39 UTC
# This is a Bug Report

## Description

* executing `serverless remove` reports "Stack removal finished..." but stack is not removed
* I would expect an error message if stack could not be removed
* Config: export something via Outputs - Export in one stack and import it `via Fn::Import` in another stack
* Output from CF:

```
23:23:31 UTC+0100	UPDATE_COMPLETE	AWS::CloudFormation::Stack	mystack	Export mystack:dev:SqsQueueARN cannot be deleted as it is in use by myOtherstack
23:23:30 UTC+0100	DELETE_IN_PROGRESS	AWS::CloudFormation::Stack	mystack	User Initiated
```

## Additional Data

* ***Serverless Framework Version you're using***: 1.3.0
* ***Operating System***: OSX
* ***Stack Trace***: 

> Serverless: Getting all objects in S3 bucket...
Serverless: Removing objects in S3 bucket...
Serverless: Removing Stack...
Serverless: Checking Stack removal progress...
CloudFormation - DELETE_IN_PROGRESS - AWS::CloudFormation::Stack - mystack
CloudFormation - UPDATE_COMPLETE - AWS::CloudFormation::Stack - mystack
Serverless: Stack removal finished...

* ***Provider Error messages***:

**Comment by stevecaldwell77** [comment] 2017-04-18 22:27
I'm running into this too. Looks like it happens because CloudFormation never sends back an event with a ResourceStatus that ends in 'FAILED'. The code in lib/plugins/aws/lib/monitorStack.js is looking for such an event.

I think the best way around this is for monitorStack.js to have an extra step when monitoring removals that makes sure the stack has a status of 'DELETE_COMPLETE', and if not generate an error, preferably with the value of the stack's ResourceStatusReason.

**Comment by pmuens** [comment] 2017-04-19 06:27
@stevecaldwell77 thanks for the proposal. Do you know what event CloudFormation sends back?

**Comment by HyperBrain** [comment] 2017-04-19 08:50
@pmuens We could add a more generic implementation to `monitorStacks.js`. My idea is, that we define some `cfFinalStates` map or array that defines states that should be treated as final for stack operations and cause the monitor to exit.

**Comment by HyperBrain** [comment] 2017-04-19 09:06
@pmuens Yes, that's incomplete. With my plugin I ran into the various ROLLBACK_COMPLETE states during testing too - which should be treated as final states too.

**Comment by pmuens** [comment] 2017-04-19 10:02
@HyperBrain thanks for confirming. How should this array be extended?

``` 
const validStatuses = [
  'CREATE_COMPLETE',
  'UPDATE_COMPLETE',
  'DELETE_COMPLETE',
  'ROLLBACK_COMPLETE',
];
```

or should we simple check if the string ends with `_COMPLETE` (which might be even more generic).

Here's a list with all the different statuses a stack can be in: http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/using-cfn-describing-stacks.html

**Comment by HyperBrain** [comment] 2017-04-19 10:31
@pmuens We could configure the different states completely, like

```
const statuses = {
  CREATE_COMPLETE: {
    message: 'create completed',
    isSuccess: true,
  },
  CREATE_FAILED: {
    message: 'create failed',
    isSuccess: false,
  },
  UPDATE_ROLLBACK_IN_PROGRESS: {
    isIntermediate: true,
    message: 'rollback in progress',
  },
  ...
};
```

and have each new incoming state do a lookup into the map to retrieve the type, message, etc. Then the monitor can print out the correct text and terminate itself if we reached a final state.

Imo we should ignore and finally remove the action parameter in the monitor. Semantically the monitor should not know anything about the action the caller is currently performing, but only act on CF states.

**Comment by pmuens** [comment] 2017-04-19 10:35
@HyperBrain I like this idea.

After reading the issue description and the problem @stevecaldwell77 mentioned again I have the feeling that simply adding another value for the `ROLLBACK_COMPLETE` state to the array won't resolve the issue.

Furthermore the solution with the different stack statuses seems more complete and easier to extend / modify later on.

**Comment by stevecaldwell77** [comment] 2017-04-19 13:54
@HyperBrain -

> Imo we should ignore and finally remove the action parameter in the monitor. Semantically the monitor should not know anything about the action the caller is currently performing, but only act on CF states.

I think the monitor needs to know the action for this use case - THE 'UPDATE_COMPLETE' status is an error if you're running a removal, and a success if you're running an update.

**Comment by stevecaldwell77** [comment] 2017-04-19 15:56
@pmuens - 

> Do you know what event CloudFormation sends back when the removal fails due to e.g. Fn::ImportValue dependencies.

Here you go:

```
[
    {
        StackId: "arn:aws:cloudformation:us-east-1:XXXXXXXXXXXX:stack/my-stack-name/00000000-0000-0000-0000-000000000000",
        EventId: "00000000-0000-0000-0000-000000000000",
        StackName: "my-stack-name",
        LogicalResourceId: "my-stack-name",
        PhysicalResourceId: "arn:aws:cloudformation:us-east-1:XXXXXXXXXXXX:stack/my-stack-name/00000000-0000-0000-0000-000000000000",
        ResourceType: "AWS::CloudFormation::Stack",
        Timestamp: "2017-04-19T15:46:01.526Z",
        ResourceStatus: "DELETE_IN_PROGRESS",
        ResourceStatusReason: "User Initiated"
    },
    {
        StackId: "arn:aws:cloudformation:us-east-1:XXXXXXXXXXXX:stack/my-stack-name/00000000-0000-0000-0000-000000000000",
        EventId: "00000000-0000-0000-0000-000000000000",
        StackName: "my-stack-name",
        LogicalResourceId: "my-stack-name",
        PhysicalResourceId: "arn:aws:cloudformation:us-east-1:XXXXXXXXXXXX:stack/my-stack-name/00000000-0000-0000-0000-000000000000",
        ResourceType: "AWS::CloudFormation::Stack",
        Timestamp: "2017-04-19T15:46:03.998Z",
        ResourceStatus: "UPDATE_COMPLETE",
        ResourceStatusReason: "Export my-export cannot be deleted as it is in use by my-other-stack"
    }
];
```

**Comment by frangeris** [comment] 2017-05-19 14:11
Hi guys,

**Is there any defined order or priority for remove stacks?** I'm facing the same issue and for remove completely I have to remove first manually the blocker stack before continue removing with `sls remove`.

**PS**: I'm using the plugin `serverless-aws-alias@^0.5.1-alpha1` of @HyperBrain, when I remove it, the stack is removed successfully and everything works great... any relation with the issue?

**Comment by HyperBrain** [comment] 2017-05-19 16:15
@frangeris My plugin should remove the alias stack right before the base stack. Can you give some insights, what exactly is the error message you get? If possible use --verbose, so that the detailed stack removal and update logs are shown.
I think we easily can see if your remove problem is related with the alias plugin. If that is the case you should open an issue there and I will take care of it.

**Comment by pmuens** [comment] 2019-02-07 10:50
Closing since this issue is quite old and we've published newer versions with fixes in th past.

Feel free to re-open if this problem is still around.

**Closed by pmuens** 2019-02-07 10:50 UTC
Labels: bug, help wanted

**Comment by stevecaldwell77** [comment] 2019-03-19 17:28
@pmuens - this bug still exists, we should re-open this issue. I've created a simple repo that reproduces the bug here:

https://github.com/stevecaldwell77/serverless-bug-2984
