### ISSUE TITLE
v1.0.2 won't allow two http functions with same path / different HTTP methods 

### ISSUE THREAD

**Issue by chris-hailstorm** [serverless/serverless#2469] opened 2016-10-19 18:28 UTC
Section of serverless.yml:

```
functions:
    getxml:
        name: ${self:service}-getxml---run---${opt:stage}
        handler: wsgi.strip
        timeout: 20
        events:
            - http:
                path: send-template.xml
                method: get
                integration: lambda-proxy
    postxml:
        name: ${self:service}-postxml---run---${opt:stage}
        handler: wsgi.strip
        timeout: 20
        events:
            - http:
                path: send-template.xml
                method: post
                integration: lambda-proxy
```

The paths are the same, but the methods are different, GET vs. POST.

In v.1.0.0-rc.2, this was fine -- deployed many times, ran fine.  I upgrade to v1.0.2 and now when I try to deploy, I get this error:

```
Serverless: Packaging service...
Serverless: Uploading CloudFormation file to S3...
Serverless: Uploading service .zip file to S3...
Serverless: Updating Stack...
Serverless: Checking Stack update progress...
..........................Serverless: Deployment failed!
 
  Serverless Error ---------------------------------------
 
     An error occurred while provisioning your stack: ApiGatewayResourceSendDashtemplatexml
     - Another resource with the same parent already has
     this name: send-template.xml.
 
  Get Support --------------------------------------------
     Docs:          docs.serverless.com
     Bugs:          github.com/serverless/serverless/issues
 
  Your Environment Infomation -----------------------------
     OS:                 darwin
     Node Version:       6.3.1
     Serverless Version: 1.0.2
```

It appears this happened during deployment -- SLS didn't object but AWS did.  Was there a change to the CF naming conventions or anything else between these versions that would prevent the 1.0.2 deployment from refreshing / overwriting the 1.0.0-rc.2 deployment?

Thanks

**Comment by flomotlik** [comment] 2016-10-19 19:54
@chris-hailstorm we're looking into this.

@pmuens @eahefnawy do we have an integration test covering this?

**Comment by flomotlik** [comment] 2016-10-19 20:04
@chris-hailstorm this is due to this PR: https://github.com/serverless/serverless/pull/2091

This introduced the Dash part to the CF resource name and is responsible for why this is now failing. Are you able to comment it out for one deployment, deploy so its removed and then redeploy so it gets added back in again?

The URL should actually not even go down because of a bug in Cloudformation itself (but you should test that first in case your URL needs to stay up).

We don't plan to add any breaking CF changes post V1 (and if we do we'll add warnings long before)

I also tested it locally and it definitely is not a bug as I'm able to deploy http endpoints with the same name but different methods, so I'm closing.

**Closed by flomotlik** 2016-10-19 20:04 UTC
Labels: bug-investigating

**Comment by pmuens** [comment] 2016-10-20 04:42
@flomotlik we don't cover those cases in the integration tests. Should we add a test for it?
