### ISSUE TITLE
Add support for C++

### ISSUE THREAD

**Issue by scm-ns** [serverless/serverless#5987] opened 2019-04-01 13:47 UTC
# This is a Feature Proposal
Support C++ lambda!

## Description

Given that AWS now supports C++ as exec env, will it be possible to add a C++ template to the serverless project?

I would love to work on this. Is there some arch diagram of the code base that I can look at, or any tips? 

Thanks.

**Comment by eahefnawy** [comment] 2019-04-03 10:55
Thanks for pitching in @scm-ns ... Here's an example merged PR for adding support for Ruby:
https://github.com/serverless/serverless/pull/5546

You could use that one as a reference as you add support for C++.

Looking forward for your PR!

**Comment by Chrischuck** [comment] 2019-05-07 16:27
Is this currently being worked on? I'd be happy to help.

**Comment by hk1997** [comment] 2019-09-01 11:40
Hi, is the issue still open.
I would love to work on this

**Comment by exoego** [comment] 2020-05-20 08:06
Closing as duplicate of #5576.
PR is still welcome.

**Closed by exoego** 2020-05-20 08:06 UTC
Labels: cat/template, feature, good first issue, help wanted
