### ISSUE TITLE
Package: excluding devDependencies from build not working with node v8.10.0

### ISSUE THREAD

**Issue by coreylight** [serverless/serverless#4830] opened 2018-03-14 15:58 UTC
# This is a Bug Report

## Description

The "excluding dev dependencies" feature does not seem to be working with node v8.10.0, where it does with node v6.10.3.

For bug reports:
* What went wrong?
devDependencies not excluded from sls package
* What did you expect should have happened?
devDependencies should be excluded
* What was the config you used?
```yml
service: XXX
provider:
  name: aws
  runtime: nodejs6.10
  region: us-west-2
  timeout: 30
  vpc:
    securityGroupIds:
      - XXX
    subnetIds:
      - XXX
  environment:
    XXX: YYY
  iamRoleStatements:
    - Effect: "Allow"
      Action:
        - XXX
        - YYY
      Resource:
        - XXX
package:
  exclude:
    - src/**
functions:
  schedule:
    handler: functions/schedule.handle
    events:
      - schedule:
          rate: rate(1 minute)
          enabled: ${opt:stage = "prod"}
  execute:
    handler: functions/execute.handle
custom:
  defaultStage: staging
```
* What stacktrace or error message from your provider did you see?
Everything runs without errors, but package is very large.

Similar or dependent issues:

## Additional Data

* ***Serverless Framework Version you're using***:
1.26.1
* ***Operating System***:
Mac OSX 10.13.3
* ***Stack Trace***:
* ***Provider Error messages***:
* ***Node Version***:
8.10.0

**Comment by Enalmada** [comment] 2018-09-18 21:27
serverless 1.32.0 package works fine on my local machine (both windows 10 and WSL ubuntu create zip around 40m using node 10) but when trying to run it in AWS CodeBuild (node 8 or 10) my zip file pushed automatically to s3 is over the 50m lambda limit. Downloading/unzipping it I can see that all my devDependencies are in the zip.  If anyone needs a reproducible test case for this, codebuild should provide it.

**Comment by philipbarile** [comment] 2018-09-21 15:55
Just wanted to leave another (hopefully helpful) data point: with the same version of serverless (currently using 1.32.0), I notice the issue of serverless not excluding development dependences when I run "sls deploy" on my Mac, but not on my windows virtual machine.  Both are running the same version of node/npm/serverless.  I'm also using the serverless-typescript-plugin.  On windows, the packaged code is around 4kb, on the mac its almost 13MB.

**Comment by prr19776** [comment] 2018-10-13 02:02
I see the same issue , v6.9.5/6.4.1/1.32.0 , the zip on the Win 10 box is 16MB and in Jenkins, Linux server is 35MB unable to reproduce the bug on my local laptop

**Comment by mikehanney** [comment] 2019-01-08 21:21
I have this issue on windows 10 with node v8.11.3, npm 5.6.0 and serverless 1.35.1

**Comment by ManfredLange** [comment] 2019-01-10 01:56
One more data point: serverless includes devDependencies on this config:
* Windows 10
* Node 10.14.2
* npm 6.5.0
* serverless 1.35.1

**Comment by ManfredLange** [comment] 2019-01-11 02:31
One alternative solution to this problem is using Webpack. Here is an example by The Code Barbarian:  http://thecodebarbarian.com/bundling-a-node-js-function-for-aws-lambda-with-webpack

**Comment by mikehanney** [comment] 2019-01-11 04:05
I'm using npm prune --production as an alternative.

**Comment by pmuens** [comment] 2019-01-15 13:24
Closing this since it's not an issue related to the Serverless Framework. Feel free to continue the discussion...

**Closed by pmuens** 2019-01-15 13:24 UTC

**Comment by nnyegaard** [comment] 2019-01-15 15:06
@pmuens How is this not an issue with serverless? The exclude dev dependencies flag in serverless dosn't work.

**Comment by mikehanney** [comment] 2019-01-15 15:55
I will open a new issue. I believe this **is** a new Serverless Framework issue and not a node version issue as mentioned in the original report. 

My node and npm versions are constant - windows 10 with node v8.11.3, npm 5.6.0.  My project is a constant. Remove dev dependencies does not work on or after version 1.35.0 of Serverless.

**Comment by gwiesing** [comment] 2019-01-21 12:49
I did a comparison using 1.34.1 and 1.35.0 with npm v6.4.1 and node v.8.12.0. Using serverless 1.34.1 my zip package has a size of 1.6MB with 1.35.0 it is more than 10MB (with node_modules/aws-sdk manually excluded using serverless.yml).
