### ISSUE TITLE
CI/CD logs are polluted by CLI progress in v3

### ISSUE THREAD

**Issue by 72636c** [serverless/serverless#10599] opened 2022-01-31 03:24 UTC
### Are you certain it's a bug?

- [X] Yes, it looks like a bug

### Is the issue caused by a plugin?

- [X] It is not a plugin issue

### Are you using the latest version?

- [X] Yes, I'm using the latest version

### Is there an existing issue for this?

- [X] I have searched existing issues, it hasn't been reported yet

### Issue description

Serverless v3 introduced a new logging interface that revamps progress reporting. While the progress logs look neat for interactive use, they introduce a lot of noise in CI/CD platforms that don't support e.g. carriage returns in their rendered output.

Here's an example of how they appear for us in [Buildkite](https://buildkite.com/):

<img width="1142" alt="Screen Shot 2022-01-31 at 2 20 55 pm" src="https://user-images.githubusercontent.com/25572311/151734619-68e7d67f-ce73-493e-abc1-4a798e026840.png">

Related: #9860, #9883

### Service configuration (serverless.yml) content

```yaml
N/A
```

### Command name and used flags

serverless deploy

### Command output

```shell
N/A
```

### Environment information

```shell
Framework Core: 3.0.1 (local)
Plugin: 6.0.0
SDK: 4.3.0
```

**Comment by WolfWalter** [comment] 2022-01-31 07:50
Hi,
in the [v3 release blog post](https://www.serverless.com/blog/serverless-framework-v3-is-live) the `--verbose` flag is recommend fo CI/CD. But the that did not work for me, because the cli did not accept the verbose flag.

**Comment by 72636c** [comment] 2022-01-31 11:20
Hi @WolfWalter. A bit off topic, but your issue is likely down to the order of CLI options. Try `serverless deploy --verbose`:

https://www.serverless.com/framework/docs/guides/upgrading-v3#cli-commands-and-options

**Comment by mnapoli** [comment] 2022-01-31 12:03
This is interesting, the output should automatically switch to disabled spinners when a non-interactive terminal is detected (to avoid exactly that kind of mess).
Maybe that CI/CD runs with an interactive terminal 🤔 (which would be very counterproductive)

**Comment by 72636c** [comment] 2022-01-31 12:25
@mnapoli :bulb: Ah, of course! That would be here right: https://github.com/serverless/utils/blob/v6.0.0/log-reporters/node.js#L37

It looks like Buildkite's Docker plugins default to allocating a TTY, and this is fixed by flipping to `tty: false`:

- https://github.com/buildkite-plugins/docker-buildkite-plugin#tty-optional-boolean
- https://github.com/buildkite-plugins/docker-compose-buildkite-plugin#tty-optional-run-only

**Comment by relaxdiego** [comment] 2022-02-04 06:24
Unfortunately, when using a Docker executor type[1] in Circle CI, there appears to be no option for configuring TTY. Should this issue be re-opened or a separate one created?

[1] https://circleci.com/docs/2.0/executor-types/

**Comment by pgrzesik** [comment] 2022-02-04 08:19
Hey @relaxdiego - thanks a lot for reporting. This is very surprising as it suggests that Circle CI executes jobs with interactive tty attached when there's no actual interactivity available. Did you try to contact Circle CI support about it? I'm not an expert on it so I'm not sure if/how disabling tty allocation is possible there. No need to open a new issue, we're monitoring that problem closely internally and we'll take actions if needed.

**Comment by mnapoli** [comment] 2022-02-04 09:00
If anyone else is experiencing the same problem, please post here with the name of the CI system (and other details).

What we are trying to figure out is: **is this problem happening with default configuration on major CI systems?**

**Comment by relaxdiego** [comment] 2022-02-04 09:59
Thanks for your responses @pgrzesik @mnapoli. In the meantime, I've started a discussion[1] in the Circle CI forms.

[1] https://discuss.circleci.com/t/how-to-globally-turn-off-tty/42836

**Comment by relaxdiego** [comment] 2022-02-06 11:28
Shouldn't this line[1] be checking if stdout (not stdin) is a tty instead? Right now, when I redirect stdout to a file (e.g. `sls package > /tmp/package.out`), serverless is still behaving like it's logging to a tty, doing that "spinny thingy magic output" (tail that file with `tail -f /tmp/package.out` and see) which is, I admit, pretty but not the behavior I wanted.

[1] https://github.com/serverless/utils/blob/23d35590abffb0de65e4184fc5b86bc7a7083c4a/log-reporters/node.js#L37

**Comment by pgrzesik** [comment] 2022-02-06 17:49
Hello @relaxdiego - logs are outputted to `stderr`, only substantial command output is directed to `stdout` - you might want to redirect both `stdout` and `stderr` in this case.

**Comment by relaxdiego** [comment] 2022-02-07 02:37
@pgrzesik that doesn't make any difference. Reproduce this observed behavior via:

terminal1:
```
rm -rf /tmp/package.out
touch $_
tail -f $_
```

terminal2:
```
npx sls package --stage dev  >/tmp/package.out 2>&1
```

Then observe the magic spinny thingy output(tm) in `terminal1`.

This is because this code:

```
const isInteractive = process.stdin.isTTY || process.env.SLS_INTERACTIVE_SETUP_ENABLE;
```

...just checks if stdin is a tty. It looks like that constant's purpose is to help determine if sls can prompt for user input or not.

As for the logic for deciding whether to print the magic spinny thing output(tm) or not, I think that should depend on some other constant. Specifically, one that indicates if `stderr` and `stdout` are TTYs or not.

**Comment by dashmug** [comment] 2022-02-07 06:49
Not sure if this helps but most CI systems have explicitly set `CI=true` as an environment variable. Maybe `serverless` should check that and use CI-appropriate logs.

**Comment by pgrzesik** [comment] 2022-02-07 16:50
Thanks @relaxdiego - that is a valid observation 👍 

@dashmug We're currently considering something like that but wanted to gather more feedback to see how problematic this is. We also found that not all CI systems are actually setting `CI` env var and sometimes it's tricky to properly determine it.

**Comment by relaxdiego** [comment] 2022-02-07 20:59
In the meantime, for those who can't wait, here's a workaraound: just force stdin to be a non-TTY by piping whatever to sls:

```
echo "no-magic-spinny-thingy-output-plstnxbye" | npx sls package --stage dev
```

@pgrzesik the environment var approach that @dashmug is actually easier to control because we could just set it when we run the command, whether in a CI or not:

```
CI=true npx sls package --stage dev

# ...or...

MAGICSPINNYTHINGYOUTPUT=notnxbye npx sls package --stage dev

# ...or...
export MAGICSPINNYTHINGYOUTPUT=notnxbye
npx sls package --stage dev
```

**Comment by pgrzesik** [comment] 2022-02-08 12:40
Thanks for sharing @relaxdiego - we're still evaluating it as it seems like it's mostly Circle CI that runs jobs with tty attached - if we get more reports, we will resort to detecting `CI` env var and assuming it's a noninteractive environment 👍

**Comment by robdmoore** [comment] 2022-02-18 05:29
For clarity, I'm using serverless-nextjs so the beta version of Serverless Components.

**Comment by enapupe** [comment] 2022-02-24 13:55
I'm having the related issue with CircleCI, using @relaxdiego's `echo  xxx|` hack solved it for now.

Can we just have a flag to control whether to have interactive output or not? Regardless of having the mentioned automatic detection, I like to have control over things :)

**Comment by Schparky** [comment] 2022-02-28 23:21
I also see the garbage in Cloudbees Codeship. I'm unsure why this issue is closed as I didn't see any resolution in this thread other than workarounds. Did I miss something?

**Comment by mnapoli** [comment] 2022-03-01 13:03
Thanks for the reports everyone (these help us make informed decisions), @pgrzesik what do you think about supporting the `CI` environment variable?

**Comment by pgrzesik** [comment] 2022-03-01 14:31
@Schparky There's no need to open a new issue, thanks for reporting. 

@mnapoli I guess we should do that, I can take care of it 👍

**Comment by pgrzesik** [comment] 2022-03-02 14:01
Added, will be out with a new Framework release.

**Closed by pgrzesik** 2022-03-02 14:01 UTC

**Comment by Schparky** [comment] 2022-03-03 21:31
Looks like I may have misreported the behavior in Codeship. I had Serverless 3.3 in a cached Docker layer, which must have been before the update that silenced the progress output. Just ran a deployment with version 3.7.1 and noticed that the output was neat and tidy. Still, I'm sure the use of the CI variable will help some, so it's good know this is fixed.

**Comment by pgrzesik** [comment] 2022-03-06 20:39
Hey @Schparky - 3.7.1 automatically detects the `CI` env var - it's very likely that your CI engine automatically sets this variable so the change is already in effect - thanks for confirmation 🙇

**Comment by jamiechong** [comment] 2022-06-13 16:55
Is there any way to work-around this with serverless v2.72.2? I'm getting this same problem in Bitbucket Pipelines. Like @robdmoore, I'm also using @sls-next/serverless-component, which requires me to stay on v2.x of serverless.
