### ISSUE TITLE
Missing AWS Credentials Error Is Vague and Mislabeled

### ISSUE THREAD

**Issue by ac360** [serverless/serverless#1520] opened 2016-07-09 02:57 UTC
##### Expected Behavior:
* Didn't have a `default` AWS profile set locally.  Expected an error message to tell me that I needed a `default` AWS Profile locally, or more helpful language specifying that credentials must be in a `serverless.env.yml` file.

##### Actual Behavior:

`TimeoutError: Missing credentials in config`

* Error message says nothing about needing a `default` AWS profile.
* Error message gives a vague message about missing credentials in config.
* Error message doesn't mention the provider at all, which would be helpful to include.
* Error message is labeled `TimeoutError`, which doesn't make sense.

This error message is particularly important because it's what a new user experiences if their dev environment isn't set up correctly.  A more helpful error will help new users along.

**Comment by davidjnelson** [comment] 2016-07-10 01:54
Hey Austen,

I'm hitting this too.

Serverless Framework Version: V.1 alpha 1

Operating System: OSX 10.11.5

Expected Behavior:

Setting an environment variable in ~/.bash_profile will load the aws credentials and allow serverless deploy to function.

I am using en encrypted volume to store my credentials file.

serverless.env.yaml:

```
vars:
stages:
    production:
        vars:
        regions:
            us-east-1:
                vars:
```

Environment variables tried:

```

AWS_SHARED_CREDENTIALS_FILE
SERVERLESS_ADMIN_AWS_PRODUCTION
SERVERLESS_ADMIN_AWS_production
AWS

```

Format of the config file path the above four environment variables point to:

[default]
aws_access_key_id=theaccesskeyid
aws_secret_access_key=theaccesskeysecret


Actual Behavior:

sls deploy --stage production
  Serverless Error ---------------------------------------
 
     TimeoutError: Missing credentials in config
 
  Get Support --------------------------------------------
     Docs:          v1.docs.serverless.com
     Bugs:          github.com/serverless/serverless/issues

**Comment by davidjnelson** [comment] 2016-07-10 02:59
I cloned 1.0 alpha and am debugging it, but for some reason serverless is not loading my project.

I think I've set it up right in intellij/webstorm:

![screen shot 2016-07-09 at 7 40 23 pm](https://cloud.githubusercontent.com/assets/381633/16711389/4dcb2e28-460d-11e6-8b6c-4d4ff443892c.png)

However, when I'm in lib/Serverless.js in the command method, I'm hitting this code path on line 360:

return BbPromise.reject(new SError('Command not found.  Enter "serverless help" to see all available commands.'));

because it expects arg 0 to be in the set:

![screen shot 2016-07-09 at 7 52 34 pm](https://cloud.githubusercontent.com/assets/381633/16711412/be9ad774-460e-11e6-89e8-179126eed92e.png)

Looking at the code I'm not seeing where in normal usage, ie: 

```
serverless deploy
```

The context would be set.

Would you be up for explaining how that is supposed to be set when debugging?  I guess I could pass an extra arg for one of the objects in the set that has a deploy property, but there are a few and I'm not sure which one I'm after.

Thanks :-)

**Comment by fruffin** [comment] 2016-07-20 12:17
I get the same error: 'e.message.split is not a function'.
I'm on Windows 10, using node 4.3.0

**Comment by fruffin** [comment] 2016-07-20 12:24
Actually I found what my problem was. The keys I was using were for a user with very limited access so it couldn't create the stack.
Once I fixed the permission problem it is now deploying correctly.

Still, the error message could be more explicit (I know, it's an alpha version :) )

**Comment by jeffski** [comment] 2016-08-05 02:02
I had the same problem because my profile was not called [default] in the ~/.aws/credentials file. When I copied my profile and named it [default] then `serverless deploy` worked.

You should be able to choose the profile as you might have several. It would be nice to either set this in one of the yaml files or maybe pass it in to the deploy command - i.e.

```serverless deploy --profile my-profile```

Using: 1.0.0-beta.1

**Comment by flomotlik** [comment] 2016-08-12 07:38
We added better Error messages in #1813, so closing this issue

**Closed by flomotlik** 2016-08-12 07:38 UTC
