### ISSUE TITLE
simple-git deprecation notice: git.silent: logging should be configured using the debug library / DEBUG environment variable, this will be an error in version 3

### ISSUE THREAD

**Issue by Andy-Blatecky** [serverless/serverless#8912] opened 2021-02-08 16:59 UTC
After upgrading to 2.22.0, I have started to see the following error/warning message:

```
simple-git deprecation notice: git.silent: logging should be configured using the debug library / DEBUG environment variable, this will be an error in version 3
```

```
serverless deploy
```

<b>Installed version</b>

```
2.22.0
```

**Comment by pgrzesik** [comment] 2021-02-09 15:04
Thanks for reporting, this is caused by one of our dependencies and we have a fix incoming: https://github.com/serverless/enterprise-plugin/pull/537

**Comment by alex1815** [comment] 2021-02-10 05:01
Good time of day, I see that fix was merged. Could you please say when Patch will be rolled out?

**Comment by pgrzesik** [comment] 2021-02-10 10:42
Hello @alex1815 - new version of `enterprise-plugin` has been released and all fresh Framework installations should now by default install it as a dependency. It will be explicitly bumped during next Framework release which will happen most likely at the end of this or at the beginning of next week.

**Comment by pgrzesik** [comment] 2021-02-16 17:42
We've released a new version of the Framework that includes an explicit bump to the problematic dependency. I'll close it but if anyone experiences issues please feel free to let me know so we can reopen and investigate :bow:

**Closed by pgrzesik** 2021-02-16 17:42 UTC
Labels: cat/dependency

**Comment by singhemant** [comment] 2021-02-16 22:07
After this merge, I am unable to start debugger at all, <2.25.1 I used to get the same error "**simple-git deprecation notice: git.silent: logging should be configured using the debug library / DEBUG environment variable, this will be an error in version 3**" now the process just exits out, without any error. 
This takes away ability to debug serverless code at all locally!

debug configuration: "**node --inspect-brk /Users/<user>/.npm-packages/bin/sls package**"

**Comment by pgrzesik** [comment] 2021-02-17 10:46
Hello @singhemant, could you please provide more details about your issue? Ideally if could you follow our standard template (it's available when you create a new GH issue) - that might help us out with diagnosing and reproducing your issue.
