### ISSUE TITLE
Tagging works with new lambda functions, but not the S3 bucket created for the deployment

### ISSUE THREAD

**Issue by Nedvedyy** [serverless/serverless#4148] opened 2017-08-24 08:44 UTC
# This is a Feature Proposal

## Description

Tagging works with new lambda functions, but not the S3 bucket created during the deployment

Similar or dependent issues:
* #3548

## Additional Data

Serverless version: 1.20.2

**Comment by kbariotis** [comment] 2017-09-01 23:12
Just to be clear, the S3 bucket you are talking is the one that holds the Lambda's source code, right?

**Comment by Nedvedyy** [comment] 2017-09-02 01:21
yes correct. The cost for it is minimum

**Comment by simlu** [comment] 2017-12-02 05:17
I'm super confused. This issue is not the issue discussed in the linked issue? Tempted to update a different issue "tags are not updated" when deploying to existing lambda function.

**Comment by simlu** [comment] 2017-12-02 05:20
Can you clarify what the issue is exactly?

**Comment by medikoo** [comment] 2020-12-30 12:20
#3548 Added functionality that allowed to set tags per lambda function, and such tags are not expected to leak to S3 bucket which hosts code of all functions.

Closing this, as I think it's not the thing we should do. If I misunderstood something please elaborate

**Closed by medikoo** 2020-12-30 12:20 UTC
Labels: cat/deployment, enhancement
