### ISSUE TITLE
Issue while resolving Variables

### ISSUE THREAD

**Issue by likhith-tally** [serverless/serverless#12854] opened 2024-10-08 06:59 UTC
### Issue description

While deployment serverless is able to resolve variables till a certain break point and then all variable resolution fails even if value exits for variable and defaults to null. Is there any limit on variable resolution?

### Context

```
Serverless ϟ Support

This generates a report from your last Serverless Framework command (including any errors) to use for Github Issues, debugging w/ AI, or creating a support ticket w/ Serverless Inc.

Summary Report -----------------

# Service Overview
- Serverless Framework Version: 4.4.4
- Service Config File: serverless.yaml
- Service Name: SqsPrimeFunctions
- Service App: sqs-prime-operations
- Service Runtime: python3.11
- Service Stage: dev
- Service Region: me-central-1
- Error Code: MISSING_VARIABLE_RESULT

## Service Path
/home/ec2-user/code.tpaws.backend/functions

## Command
deploy --stage dev,--region me-central-1,--aws-profile Ops-Host

## Error Message
Cannot resolve '${env:SLS_STAGE}' variable at 'provider.vpc.securityGroupIds'. No value is available for this variable, and no default value was provided. Please check your variable definitions or provide a default value.

## Error Stacktrace
```
at _ResolverManager.resolve (file:///home/ec2-user/.serverless/releases/4.4.4/package/dist/sf-core.js:655:55913)
at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
at async #handlePlaceholderNode (file:///home/ec2-user/.serverless/releases/4.4.4/package/dist/sf-core.js:655:54343)
at async file:///home/ec2-user/.serverless/releases/4.4.4/package/dist/sf-core.js:655:52335
at async processNodeAndHandleCompletion (file:///home/ec2-user/.serverless/releases/4.4.4/package/dist/sf-core.js:655:43086)
```

## Service Config
```
app: sqs-prime-operations
service: SqsPrimeFunctions
variablesResolutionMode: 20210326
provider:
  name: aws
  runtime: python3.11
  region: ${opt:region}
  stage: ${opt:stage, 'dev'}
  vpc:
    securityGroupIds: ${file(infra/config.${env:SLS_STAGE}.yaml):LambdaVpc.SecurityGroupIds}
    subnetIds: ${file(infra/config.${env:SLS_STAGE}.yaml):LambdaVpc.SubnetIds}
  memorySize: 256
  versionFunctions: false
  environment:
    STAGE: ${opt:stage, 'dev'}
    BASE_REGION: ${opt:region}
    DELIVERY_STREAM_NAME: AuthLogDeliveryFirehose
    TABLE_JOB_RESULT: JobResultTable-${sls:stage}
    TABLE_MONITORING: JobMonitoringTable-${sls:stage}
    TABLE_EVENT_HISTORY: EventHistoryTable-${sls:stage}
    TABLE_DEDUPLICATION: MsgDeduplicationTable-${sls:stage}
    TABLE_SCHEDULE_PATTERN: SchedulePattern-${sls:stage}
    TABLE_VM_DETAILS: vm_details_table
    TABLE_CUSTOMER_DETAILS: customer_details_table
    TABLE_PLAN_DETAILS: plan_table
    TABLE_INFRA_DETAILS: infra_specification_details
    TABLE_LATEST_RELEASE: latest_release
    TABLE_AWS_ACCOUNT_DETAILS: aws_account_details
    TABLE_LOAD_BALANCER: load_balancer_details
    QUEUE_NOP: PrimeNopQ
    QUEUE_NOP_URL: ${cf:SqsCorePrimeLayer-${sls:stage}.PrimeNopQUrl}
    SNS_TOPIC: ${file(infra/config.${env:SLS_STAGE}.yaml):SnsTopic}
package:
  individually: true
  patterns:
    - "!**/__pycache__/**"
    - "!infra/**"
    - "!*.yaml"
    - "!*.log"
functions: ${file(infra/lambdas.yaml):Lambdas}
resources:
  Description: Implements lambda functions.
  Resources:
    InfraLambdaRole:
      Type: AWS::IAM::Role
      Properties:
        Path: /
        RoleName: InfraLambdaRole-${sls:stage}
        AssumeRolePolicyDocument:
          Version: "2012-10-17"
          Statement:
            - Effect: Allow
              Principal:
                Service:
                  - lambda.amazonaws.com
              Action: sts:AssumeRole
        ManagedPolicyArns:
          - ${file(infra/config.${env:SLS_STAGE}.yaml):Policies.SES}
          - ${file(infra/config.${env:SLS_STAGE}.yaml):Policies.CMK}
          - ${file(infra/config.${env:SLS_STAGE}.yaml):Policies.DDB}
          - ${file(infra/config.${env:SLS_STAGE}.yaml):Policies.VPC}
          - ${file(infra/config.${env:SLS_STAGE}.yaml):Policies.LOG}
          - ${file(infra/config.${env:SLS_STAGE}.yaml):Policies.CrossAccount}
          - ${file(infra/config.${env:SLS_STAGE}.yaml):Policies.SQS}
          - ${file(infra/config.${env:SLS_STAGE}.yaml):Policies.DDBFull}
          - ${file(infra/config.${env:SLS_STAGE}.yaml):Policies.CloudWatch}
          - ${file(infra/config.${env:SLS_STAGE}.yaml):Policies.S3}
          - ${file(infra/config.${env:SLS_STAGE}.yaml):Policies.SNS}
          - ${file(infra/config.${env:SLS_STAGE}.yaml):Policies.Lambda}
          - ${file(infra/config.${env:SLS_STAGE}.yaml):Policies.LambdaFull}
```
```

**Comment by czubocha** [comment] 2024-10-08 14:40
Hey @likhith-tally, are you using Serverless Variables in the `infra/config.${env:SLS_STAGE}.yaml` file? If so, could you also share this file so we can better understand and debug the issue?

**Comment by likhith-tally** [comment] 2024-10-09 05:28
`ap-south-1:
  ADMIN: 7517xxx4125
  OPS: 174872xx191
  DEVOPS: 696xx5444759
  DOMAIN: tgoxxv.com

me-central-1:
  ADMIN: 381xxx193531
  OPS: 4711xxxx0357
  DEVOPS: 69xxxx5444759
  DOMAIN: uxxxodev.com
`

I have attached the file. 
Each time different variable resolution fails. When we checked through debug logs certain amount of variables get resolved till a break point and then after the breakpoint all variable resolution defaults to null.

**Comment by patrickbdaly** [comment] 2024-10-20 01:26
I have a similar issue since upgrading to serverless v4. I use serverless compose to deploy 6 services with a total of around 100 lambdas. Since upgrading to v4, it randomly is unable to resolve certain variables, with a different variable failing every time. If I remove one of my services, then all deploys fine. Then If I only run the one service that I had removed, it deploys fine as well. Definitely seems to be having problems resolving once the number of lambdas passes some tipping point.

**Comment by karlbernard2** [comment] 2024-11-04 21:49
We also have similar issues since v4 @czubocha , we randomly get while running locally:

Error: Cannot resolve '${self:provider.environment.WAITINQUEUE_SQS}' variable at 'functions.2.consumeQueueSQS.events.0.sqs.arn'. No value is available for this variable, and no default value was provided. Please check your variable definitions or provide a default value.

Usually running `npm i` a few times fixes the issue.

We also often have timeout while deploying at the step "Retrieving AWS CloudFormation stack". This is causing a lot of frustration while deploying in our CICD pipeline.

**Comment by czubocha** [comment] 2024-11-12 12:29
Thanks for sharing these details. We're aware of this issue and are actively investigating it.

**Comment by mishabhi** [comment] 2024-11-18 16:42
@czubocha Any luck with the fix?

**Comment by likhith-tally** [comment] 2024-11-18 16:46
I was able to get around the issue. In my case I was hitting cloud formation describe stack limit and hence after a certain point variables did not resolve. This can be solved by increasing limit by raising support or by optimising code to make lesser calls

Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________
From: Abhishek Mishra ***@***.***>
Sent: Monday, November 18, 2024 10:12:41 PM
To: serverless/serverless ***@***.***>
Cc: Likhith M ***@***.***>; Mention ***@***.***>
Subject: [EXTERNAL]:Re: [serverless/serverless] Issue while resolving Variables (Issue #12854)

Caution: This email originated from outside the organization. Do not click links or open attachments, unless you recognize the sender and know the content is safe.


@czubocha<https://github.com/czubocha> Any luck with the fix?

**Comment by karlbernard2** [comment] 2024-11-19 02:56
>In my case I was hitting cloud formation describe stack limit
>This can be solved by increasing limit by raising support

@likhith-tally I couldn't find a quota that would limit describe stack, would you remember what you had support change to solve this issue?

**Comment by czubocha** [comment] 2024-11-22 15:01
@likhith-tally Thanks for sharing! Glad to hear you found the root cause and resolved the issue.

@patrickbdaly @karlbernard2 @mishabhi Could your issues be related to rate limiting on the CloudFormation API side? Do you happen to use the `cf` resolver extensively? Unfortunately, CloudFormation API rate limits are not publicly documented. I've confirmed that the Framework doesn't currently handle CloudFormation throttling properly, leading to the `No value is available for this variable, and no default value was provided` error instead of a more descriptive message. This will be addressed in the next release, along with enhanced debug logs to make identifying root causes easier.

**Comment by patrickbdaly** [comment] 2024-11-23 02:40
@czubocha Yes, I use the cf resolver a lot. Certainly could be a CF rate limiting issue. However, I never got the issue until upgrading to v4. I deploy two services through compose to get around the issue. Will look forward to the extra debugging in the next release!

**Comment by czubocha** [comment] 2024-12-09 16:48
CloudFormation resolver errors are no longer swallowed as of [v4.4.12](https://github.com/serverless/serverless/releases/tag/v4.4.12). If you encounter CloudFromation rate limit issues, you can increase the maximum number of attempts made by the underlying AWS SDK by setting `AWS_MAX_ATTEMPTS` environment variable (default is 3).

**Closed** 2024-12-16 18:06 UTC
Labels: V4
