### ISSUE TITLE
Allow invoking function locally as in 0.5.x

### ISSUE THREAD

**Issue by demetriusnunes** [serverless/serverless#2144] opened 2016-09-15 14:47 UTC
# This is a Feature Proposal
## Description

Being able to invoke functions locally is essentials, as it greatly speeds up the development workflow.

It was possible to do it on 0.5.x by default with the `sls function run` command. 

We just need a new command argument for the new `invoke` command to do that.

**Comment by WooDzu** [comment] 2016-09-15 17:05
I completely agree. Additionally if the context and event data of functions could be built in core and exposed to plugins it would help a great deal to plugins like serverless offline!

**Comment by mthenw** [comment] 2016-11-02 06:39
Duplicate of https://github.com/serverless/serverless/issues/2531

**Closed by mthenw** 2016-11-02 06:39 UTC
