### ISSUE TITLE
Add docs in Japanese 

### ISSUE THREAD

**Issue by horike37** [serverless/serverless#2123] opened 2016-09-13 23:40 UTC
# This is a  Feature Proposal
## Description

I want to translate a official document into Japanese, because I want to spread Serverless in Japan more than now.

I will translate under the `docs` directory in my repo. Could I PR, when finish?
I think a document structure below, Is this OK?

```
docs
 ├── 01-guide
 ├── 02-providers
 ├── 03-cli-reference
 ├── 04-extending-serverless
 ├── README.md
 ├── usage-tracking.md
 └── ja
     ├── 01-guide
     ├── 02-providers
     ├── 03-cli-reference
     ├── 04-extending-serverless
     ├── README.md
     └── usage-tracking.md
```

**Comment by eahefnawy** [comment] 2016-09-14 06:04
@horike37 thanks a lot for pitching in on this 😊 ... I'd love to see our docs localized in multiple languages, especially in Japanese since I've maintaining the framework from Japan over the past few months. I'm not super sure if those localization would live in our main repo though, since they require constant maintenance from a native speaker and can go outdated pretty quickly.

@flomotlik @pmuens what you guys think about this?

**Comment by pmuens** [comment] 2016-09-14 06:17
Love the idea and the courage to jump in on this!

But I'm also a little bit nervous about the constant maintenance effort. Some of the main concepts might not change that often but some implementations could get outdated quickly.

Maybe we can introduce an i18n directory and write an "experimental" notice at the top of the file (with a link to the english docs).

I know that there are some services which will help translation projects through contributors. Not sure what's the best practice here...

**Comment by flomotlik** [comment] 2016-09-14 06:18
To start thank you for pitching in on this and your other contributions so far. Really appreciate them!

I like the idea of translating the docs, especially because a lot of the docs will probably not change a lot regularly. But the issue is that we can't really keep them up to date or take over the responsibility for them.

What would imho be a potential way to do it is if you could have a fork of serverless in your account with e.g. a docs_jp subfolder that has the translation of the docs in them. Then in the official documentation we can say @horike37 has a translation into Japanese and link to your docs.

Then we can evaluate this over time and get your feedback how Serverless is used in Japan, how its growing and what people want to learn and understand and we can decide to move the docs into the serverless repo and official docs? Does that sound like an option for now?

**Comment by eahefnawy** [comment] 2016-09-14 07:42
@flomotlik +1 ... @pmuens could also have a "translations" section or something in his [awesome-serverless repo](https://github.com/JustServerless/awesome-serverless) for more exposure 😉

**Comment by pmuens** [comment] 2016-09-14 07:57
@eahefnawy good idea!

**Comment by flomotlik** [comment] 2016-11-05 14:09
I'm closing this for now as we're not going to add the docs in other languages to core, but let us know if we can link to your translation.

**Closed by flomotlik** 2016-11-05 14:09 UTC
Labels: discussion
