### ISSUE TITLE
sls logs -f [function] -t doesn't incur tail, acts just like standard sls logs

### ISSUE THREAD

**Issue by eliliam** [serverless/serverless#5497] opened 2018-11-16 00:43 UTC
# This is a Bug Report

## Description

* What went wrong?
When using `sls logs -f [function] -t` to monitor logs on a serverless lambda function, the result is just a straight print to screen and exit, just like it would have been without the -t option. This worked perfectly in 1.32.0, but after upgrading to 1.33.1 it is broken. 
* What did you expect should have happened?
When using the `-t` option, it should constantly poll for new logs and not exit immediately. 
* What was the config you used?
* What stacktrace or error message from your provider did you see?
N/A
Similar or dependent issues:

## Additional Data

* ***Serverless Framework Version you're using***:
1.33.1
* ***Operating System***:
Ubuntu 18.04.1 64-bit
* ***Stack Trace***:
N/A
* ***Provider Error messages***:
N/A

**Comment by dschep** [comment] 2018-11-16 13:14
Is this a duplicate of #5295?

**Comment by eliliam** [comment] 2018-11-16 16:14
Not exactly, the -t option for me resulted in the same thing as without the
-t option. In #5497 he claims nothing at all happens with -t, no output.

**Comment by andrewphahn** [comment] 2018-11-16 20:46
I'm seeing the same thing, both `-t` or `--tail` seem to be ignored.

**Comment by eliliam** [comment] 2018-11-16 20:48
Changing the `-i` or `--interval` seem to have absolutely no effect as well.

**Comment by dschep** [comment] 2018-11-16 20:58
Looking into this.. Are you all using AWS?

**Comment by eliliam** [comment] 2018-11-16 21:00
Yes, I'm seeing the same result with all of my lambda functions defined in serverless.yml.

**Comment by andrewphahn** [comment] 2018-11-16 22:51
> Looking into this.. Are you all using AWS?

Yes

**Closed** 2018-11-19 16:59 UTC

**Comment by dschep** [comment] 2018-11-19 18:58
Fix released in v1.33.2

**Comment by sweepy84** [comment] 2018-11-19 22:35
Legend, love your work @dschep

**Comment by eliliam** [comment] 2018-11-19 22:40
Awesome, thanks for fixing that! Haven't tested it yet as I've reverted to
1.32.0, but will test soon. Thanks @dschep!

**Comment by micku** [comment] 2019-06-21 10:38
I'm having this same issue with Google Cloud and Serverless version 1.45.1.
Is this the right place to report the issue?

**Comment by mrashidse** [comment] 2021-04-14 10:50
I am also facing this problem in Serverless version 2.35.0
