### ISSUE TITLE
Function timeout setting (29) is greater than maximum allowed timeout for HTTP API endpoint (29s).

### ISSUE THREAD

**Issue by tommedema** [serverless/serverless#7496] opened 2020-03-22 23:42 UTC
# Bug Report

## Description

1. What did you do?
Ran `serverless deploy` with a function timeout of `29`

1. What happened?
Serverless Framework warned me:

```
Function timeout setting (29) is greater than maximum allowed timeout for HTTP API endpoint (29s). This may introduce situation where endpoint times out for succesful lambda invocation.
```

1. What should've happened?

It should not warn me because the timeout is not greater than 29 seconds. It is exactly 29 seconds.

1. What's the content of your `serverless.yml` file?

```
provider:
  name: aws
  stage: ${{opt:stage, 'local'}}
  region: ${{opt:region, 'us-west-2'}}

  # in serverless 1.59.3, provisioned concurrency cannot be used if
  # function versioning is enabled
  versionFunctions: false

  runtime: nodejs12.x
  memorySize: 256
  timeout: 29
```

Additionally, I'm getting this warning for serverless packages where I have indeed set the timeout > 30 seconds, but am NOT using API gateway to access the functions (instead am using s3 events).

**Comment by preshetin** [comment] 2020-03-23 09:25
I was able to reproduce it when using `httpApi`.

I assume the comparison operand should be adjusted from `>=` to `>` at https://github.com/serverless/serverless/blob/master/lib/plugins/aws/package/compile/events/httpApi/index.js#L406

**Comment by tommedema** [comment] 2020-03-23 18:22
Yes. It's also pretty ugly that this number is hardcoded in two different places. We should move it to a constant / configuration file

**Comment by medikoo** [comment] 2020-03-23 21:04
Problem is that error message is not precise. Technically setting timeout of `29s` on function is not safe for HTTP API (`>=` is intentional there.)

Due to how AWS processes things, you still may enter a window where function will finalize successfully right before reaching 29s timeout, but HTTP API endpoint will timeout, as there was not enough time room to process function response there.

We should probably have different special message where user decides on `29` timeout on lambda with HTTP API endpoints.

> Additionally, I'm getting this warning for serverless packages where I have indeed set the timeout > 30 seconds, but am NOT using API gateway to access the functions (instead am using s3 events).

This was fixed with v1.67.0

**Comment by tommedema** [comment] 2020-03-23 22:00
Isn't the API gateway timeout 30 seconds?

Also, if 29 secs is not safe, then what is safe?

**Comment by medikoo** [comment] 2020-03-24 00:27
> Also, if 29 secs is not safe, then what is safe?

I'm not sure which exactly margin can be considered safe (there's no guideline from AWS and I didn't attempt to reverse engineer it)
In a framework we configure the endpoint with 0.5s greater (but no greater than 29s) timeout than one as set on a function.

**Closed** 2020-04-06 21:57 UTC
