### ISSUE TITLE
Validate dependancies are present before deploying

### ISSUE THREAD

**Issue by DavidWells** [serverless/serverless#4075] opened 2017-08-11 22:13 UTC
If a user clones down a service and forgets to `npm install` they can deploy broken services.

They see this ultra vague error in lambda logs

```
START RequestId: dd920e5d-7ee0-11e7-a6f0-7fe125518660 Version: $LATEST
Unable to import module 'handler': Error
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
END RequestId: dd920e5d-7ee0-11e7-a6f0-7fe125518660
```

**This should be solved by the framework.**

1. User runs `sls deploy`
2. Framework check package.json 
3. Framework validates that the node_module folder is present

If node_modules not found, error (or automatically run `npm i`)

If node_modules good, continue with deploy as usually.

This is an easily solvable issue that causes unnecessary user pain.

**Comment by horike37** [comment] 2017-08-12 00:21
I like the idea of automatically run `npm i` instead of displaying error.

**Comment by dougmoscrop** [comment] 2017-08-12 01:05
I can see a few scenarios that would make this harder than it seems (e.g. using a linked module, or a git module) that would make it hard to know if you should `npm i` or not.

Alternatively, what if serverless generated a handler, that required() the intended handler and did try/catch or something to produce more meaningful errors?

**Comment by kbariotis** [comment] 2017-08-19 14:26
In the same sense, Serverless could also validate that the handlers defined are present and indeed exporting the required functions.

E.g., given a configuration like this:

```yaml
functions:
  install:
    handler: src/handlers/install.installHandler
    events:
      - http: GET /
```

Serverless should verify that `src/handlers/install` file exists and that also provides the `installHandler` function.

**Comment by pmuens** [comment] 2017-08-19 17:40
@kbariotis thanks for the feedback! That's a really good idea 👍.

Fortunately there's already an issue which tracks that. It's currently discussed in https://github.com/serverless/serverless/issues/3758.

**Comment by HyperBrain** [comment] 2017-08-20 11:31
@pmuens @kbariotis This is exactly what the serverless-webpack plugin does in it's latest version. *AND* this is excatly why I have to add one thing here ;-) It works perfectly with AWS and OpenWhisk, but with the Google plugin people seem to have one index file and specify only the exported function names in their handler definition, so to say: With Google the handlers do not imply any path semantics on the given handler properties.

@pmuens As you're the author of the Google plugin - is that intended or would it be possible to change the Google plugin in a way that it uses the common base and also would share the same concept of handler definitions as AWS and others?

**Comment by pmuens** [comment] 2017-08-21 12:22
> @pmuens As you're the author of the Google plugin - is that intended or would it be possible to change the Google plugin in a way that it uses the common base and also would share the same concept of handler definitions as AWS and others?

Thanks for the comment @HyperBrain 👍

🤔 so the problem with the `google` plugin right now is that it usually works without a `handler` property. The `handler` was introduced so that we have a consistent experience for users who switch between providers. In retrospect I'm not sure if that's the best approach because it introduces another layer of abstraction where there's no need for this.

Googles integration works as follows: You need to have an `index.js` or `function.js` file in your root. If you want to have a specific "handler" then you need to define that in your `package.json` file (here are the docs which describe that: https://cloud.google.com/functions/docs/deploying/).

Right now I'm not sure if we remove the `handler` concept when moving on with the Google Cloud Functions provider plugin since it doesn't do that much right now (you have to have an `index.js` file in the root right now). Furthermore it would play more nicely together with the providers concepts.

**Comment by HyperBrain** [comment] 2017-08-21 12:38
@pmuens In the meanwhile I have added an algorithm to ignore the Google handler checks in the `serverless-webpack` plugin (will be released soon). This works, but it would be great if it could be handled in the plugin in a way compatible to the other providers 😃

**Comment by pmuens** [comment] 2017-08-21 13:34
> @pmuens In the meanwhile I have added an algorithm to ignore the Google handler checks in the serverless-webpack plugin (will be released soon). This works, but it would be great if it could be handled in the plugin in a way compatible to the other providers 😃

Thanks for the update on this one @HyperBrain 👍. Yes, we should add a more powerful `handler` support in the Google Cloud Functions provider plugin soon!

**Comment by pmuens** [comment] 2019-02-12 12:00
Closing since this is a duplicate of https://github.com/serverless/serverless/issues/3270.

**Closed by pmuens** 2019-02-12 12:00 UTC
Labels: good first issue, help wanted
