### ISSUE TITLE
Plugins Are Being Loaded Twice

### ISSUE THREAD

**Issue by ac360** [serverless/serverless#1521] opened 2016-07-09 05:01 UTC
##### Expected Behavior:
* Plugins should be loaded once, causing hooks and all else to be set only once.

##### Actual Behavior:
* Plugins are loaded twice
* This is because they are each instantiated twice in the PluginManager, due to the way the Plugin commands and shortcuts code is written.  That code needs to be refactored to solve this problem and it could be improved generally.

**Comment by pmuens** [comment] 2016-07-10 09:10
Thanks for reporting! This is really not intended behavior. Will look into it ASAP.

**Comment by pmuens** [comment] 2016-07-26 09:05
Resolved with https://github.com/serverless/serverless/pull/1670

**Closed by pmuens** 2016-07-26 09:05 UTC
Labels: area/plugin-system, bug: confirmed
