### ISSUE TITLE
HTTP redirect to HTTPS

### ISSUE THREAD

**Issue by RUSHt** [serverless/serverless#5536] opened 2018-11-29 11:38 UTC
AWS CloudFormation configuration is not redirecting http to https

I built a simple service using --template aws-nodejs, it deploys successfully with a custom domain name & certificate.

The service works fine with a https://, but GET to  http://.... fails.

Usually this is resolved by configuring a cloudFront Behaviour Viewer Policy to Redirect HTTP to HTTPS, but I can’t see how to achieve the same in serverless ?

I asked this question in the forum and received the response the the framework only supports HTTPS.

( https://forum.serverless.com/t/redirect-http-requests-to-https/6581 ).

**Comment by RUSHt** [comment] 2019-01-02 16:11
Yep, that worked - thanks.  The need for HTTP > HTTPS is for clients that start a connection by typing the address on their browser, if they don't type https:// then the connection fails - unless you have a means for redirecting HTTP > HTTPS.  Since I'm providing a Nuxt App then this is essential. Since Cloudformation can build Cloudfront distributions is there a mean to extend the server less cloud formation script which would include a Cloudfront distribution ?

**Comment by dinamic** [comment] 2019-01-03 12:14
This sounds reasonable. I thought something is wrong when deploying initially with a custom domain.

I would use `wget -O - my.domain.name.com` and it would show port 80 is not available. I totally didn't expected for the lambda to be available on port 443 only.

Please, add this functionality to serverless!

**Comment by pmuens** [comment] 2019-01-16 11:08
Closing since this isn't something we can handle on the Serverless Framework side.

**Closed by pmuens** 2019-01-16 11:08 UTC

**Comment by TrejGun** [comment] 2019-05-22 12:13
@pmuens this is still a valid issue, and is in top of google search, please add some docs to here

**Comment by michaelbats** [comment] 2019-08-30 15:51
**cricket sounds**

**Comment by Keydex** [comment] 2020-01-14 19:26
Okay, I was googling this too but I believe there's a reason why we shouldn't be concerned about this.

If you are using apigateway, you should be hosting an api. An end user isn't going to type your api endpoint in their browser and expect it to be redirected to a working https link. When using an api you should always explicitly define https:// when testing or in the application anyways. 

Again this appears to be by design from AWS, not serverless.

**Comment by RUSHt** [comment] 2020-01-14 19:52
It's not just for an API endpoint - where you could simply stipulate HTTPS.

In my case I'm hosting a NUXT site, where the client might not enter https:// in their browser.

**Comment by sanddevil** [comment] 2020-04-07 07:21
@Keydex it is simply not true that API Gateway is only used for APIs. There is a use case for simple websites by Lambda / API Gateway and I have developed many. It is therefore imperative that there is a mechanism for redirecting from http to https for those who use the url bar in their browser to type the domain

**Comment by selbyk** [comment] 2020-08-20 16:29
+1

**Comment by h3smith** [comment] 2020-11-10 02:15
To be able to force HSTS redirect from port 80 to 443 would be immensely beneficial. We use API Gateway + Lambda to host websites and no port 80 support is frustrating.
