### ISSUE TITLE
[v3] Node v22.12.0 Error _serverlessExternalPluginName

### ISSUE THREAD

**Issue by DemonICOLI** [serverless/serverless#12936] opened 2024-12-04 14:54 UTC
### Issue description

Just getting this error while running v2 on the node release v22.12.0

```javascript
TypeError: Cannot redefine property: _serverlessExternalPluginName
     at Function.defineProperty (<anonymous>)
     at PluginManager.resolveServicePlugins (/api/node_modules/serverless/lib/classes/plugin-manager.js:230:14)
     at async PluginManager.loadAllPlugins (/api/node_modules/serverless/lib/classes/plugin-manager.js:136:36)
     at async Serverless.init (/api/node_modules/serverless/lib/serverless.js:146:5)
     at async /api/node_modules/serverless/scripts/serverless.js:601:7
```

**Comment by throrin19** [comment] 2024-12-05 16:02
same problem here

**Comment by eudoroolivares2016** [comment] 2024-12-05 18:00
Also seeing this issue in our CI/CD

**Comment by brunopenso** [comment] 2024-12-05 18:06
Same problem in local and CI/CD pipelines, trying to investigate here

**Comment by MordaCap** [comment] 2024-12-06 11:41
node LTS version 20.18.1 works.

**Comment by eheyder** [comment] 2024-12-06 18:16
I can see that this works on node version 22.11.0 and breaks on versions 22.12.0.

**Comment by eudoroolivares2016** [comment] 2024-12-09 18:22
[austencollins](https://github.com/austencollins) this might be a duplicate of https://github.com/serverless/serverless/issues/12922#issuecomment-2526886276 is that correct?

**Comment by austencollins** [comment] 2024-12-09 20:16
Hi @eudoroolivares2016, Nope. This appears to be an issue related to a (breaking?) change in Node.js V22, distributed in one of its minor releases. A few other projects seem affected. We'll continue to look into this.

**Closed** 2024-12-18 15:24 UTC
Labels: v3

**Comment by lucas-implanta** [comment] 2024-12-19 20:15
> Hey everyone, we’ve just released [v3.40.0](https://github.com/serverless/serverless/releases/tag/v3.40.0), which resolves the Node v22.12 incompatibility. Feel free to update and give it a try.

Works fine! There's just a warning that can be updated as well: https://github.com/serverless/serverless/issues/12963

**Comment by jackie1santana** [comment] 2024-12-20 18:49
> Hey everyone, we’ve just released [v3.40.0](https://github.com/serverless/serverless/releases/tag/v3.40.0), which resolves the Node v22.12 incompatibility. Feel free to update and give it a try.

this fixed the issue! I'm now able to use Node 22.

**Comment by joebowbeer** [comment] 2025-01-08 07:52
We're seeing ERR_REQUIRE_ASYNC_MODULE thrown at line 5 in require-with-import-fallback.js

This also happens with 3.40.0, and adding `--no-experimental-require-module` seems to make no difference.

Any insight would be appreciated.

```
4962 | Environment: linux, node 22.13.0, framework 3.39.0 (local), plugin 7.2.3, SDK 4.5.1
4963 | Docs:        docs.serverless.com
4964 | Support:     forum.serverless.com
4965 | Bugs:        github.com/serverless/serverless/issues
4966 |  
4967 | Error:
4968 | Error [ERR_REQUIRE_ASYNC_MODULE]: require() cannot be used on an ESM graph with top-level await.
  Use import() instead. To see where the top-level await comes from, use --experimental-print-required-tla.
4969 | at ModuleJobSync.runSync (node:internal/modules/esm/module_job:392:13)
4970 | at ModuleLoader.importSyncForRequire (node:internal/modules/esm/loader:329:47)
4971 | at loadESMFromCJS (node:internal/modules/cjs/loader:1411:24)
4972 | at Module._compile (node:internal/modules/cjs/loader:1544:5)
4973 | at Object..js (node:internal/modules/cjs/loader:1668:16)
4974 | at Module.load (node:internal/modules/cjs/loader:1313:32)
4975 | at Function._load (node:internal/modules/cjs/loader:1123:12)
4976 | at TracingChannel.traceSync (node:diagnostics_channel:322:14)
4977 | at wrapModuleLoad (node:internal/modules/cjs/loader:217:24)
4978 | at Module.require (node:internal/modules/cjs/loader:1335:12)
4979 | at require (node:internal/modules/helpers:136:16)
4980 | at module.exports (xxx/node_modules/serverless/lib/utils/require-with-import-fallback.js:5:12)
```

**Comment by joyeecheung** [comment] 2025-03-17 21:39
I am unfamiliar with serverless and only came across this from https://github.com/nodejs/node/issues/57520 - though from what I can tell https://github.com/serverless/serverless/pull/12950, it seems https://github.com/serverless/serverless/issues/12936#issuecomment-2576970783 could be fixed by adding `|| error.code === 'ERR_REQUIRE_ASYNC_MODULE'` in https://github.com/serverless/serverless/blob/main/lib/utils/require-with-import-fallback.js#L9 (use `import()` to handle it if it's an async ESM).

**Comment by wgomes-brain** [comment] 2025-05-12 03:19
This applies to node 20.19.x and Serverless 3.39 and 3.40. For us, rolling back to node 20.18.1 solved the problem.

The links to other tickets may make that clear, but just to be pretty explicit, as this is the only ticket that comes up on Google searches for me about this and the title may make you think otherwise.
