### ISSUE TITLE
1.33 no longer supports stage

### ISSUE THREAD

**Issue by erikhyrkas** [serverless/serverless#5496] opened 2018-11-15 19:17 UTC
# This is a Bug Report

## Description
See here for details:
https://forum.serverless.com/t/problem-with-version-1-33-serverless-deploy-fails-with-strange-error/6460

* What went wrong?

serverless is ignoring --stage and instead trying to use the stage's value as a parameter, resulting in an error: Serverless command “deploy ci” not found. Did you mean “deploy”? Run “serverless help” for a list of all available commands.

* What did you expect should have happened?
I expect the same behavior as 1.32 where you can run:
serverless deploy --verbose --stage ci

* What was the config you used?
* What stacktrace or error message from your provider did you see?
Serverless command “deploy ci” not found. Did you mean “deploy”? Run “serverless help” for a list of all available commands.

Similar or dependent issues:

## Additional Data

* ***Serverless Framework Version you're using***:
1.33
* ***Operating System***:
linux and windows
* ***Stack Trace***:
* ***Provider Error messages***:

**Comment by dschep** [comment] 2018-11-15 19:52
duplicate of #5493 and fixed in `v1.33.1`

**Closed by dschep** 2018-11-15 19:52 UTC
