### ISSUE TITLE
Question: how to retrieve the current path where the Lambda Function is running

### ISSUE THREAD

**Issue by StefH** [serverless/serverless#2009] opened 2016-09-03 13:34 UTC
# This is a Question

## Description
I'm trying to use the Amazon SNS service, and I want to load the configuration from a config.json file, like this:
```ts

exports.handleData = function(event: any, context: Context, callback: Callback) {

    // load aws config
    config.loadFromPath('config.json');

    // load AWS SES
    let ses: SES = new SES({ apiVersion: '2010-12-01' });
```

The config.json is currently correctly copied to the same folder with WebPack:
```js
new CopyWebpackPlugin([
      {
        from: 'src/config.json',
        to: 'config.json'
      }
    ]), 
```

However running my test-function:
`serverless webpack invoke --function mytestfunc`

gives this error message
```
Serverless: Bundling with Webpack...
Time: 7799ms
      Asset       Size  Chunks             Chunk Names
 handler.js    2.71 kB       0  [emitted]  main
config.json  127 bytes          [emitted]
Serverless: Run function mytestfunc...

  Error --------------------------------------------------

     ENOENT: no such file or directory, open 'C:\Users\...\my-func\config.json'
```

Any clue how to access the current path where the lambda is running ? Or is this an error from the webpack plugin ?

**Comment by andymac4182** [comment] 2016-09-03 23:10
This looks like an error from the webpack plugin. Have you tried `serverless webpack --out .webpack` and then checked in the `.webpack` folder to see what is in there?

**Comment by StefH** [comment] 2016-09-04 07:35
The command `serverless webpack --out .webpack` correctly places my **config.json** file + my **handler.js** file in the `.webpack` folder.

But running the function shows the error.

**Comment by andymac4182** [comment] 2016-09-04 07:42
I would try dumping out the current working directory to see where it is being ran from https://nodejs.org/api/process.html#process_process_cwd Probably something to be reported in the serverless-webpack repo.

**Comment by StefH** [comment] 2016-09-04 11:04
That command lists out this:
``Current directory: C:\\Users\\ . . .\\my-func` which is valid within a real AWS Lambda where everything is deployed in the root.`
However when running the function locally, it should be like `\\my-func\\.webpack` ?

Or is there another way so that I require or import that **config.json** file, so that the location resolving is done automatically?

Or is there a way that I can detect that the function is running local instead of on real AWS?

**Comment by andymac4182** [comment] 2016-09-04 11:41
Personally my functions are packaged like this and I have included where I would expect your config.json to appear. 
```
.webpack\function1\index.js
.webpack\config.json
```
Do you mind sending me your whole webpack config? You can send it in private on Gitter to stop this becoming a conversation if that is easier

**Comment by flomotlik** [comment] 2016-09-05 17:26
@StefH as this is more a discussion and not a bug/feature request would be great if this could be moved to the forum at forum.serverless.com so we only have bug reports/feature requests here in the repo.

If you want you can also add a comment here after posting in the forum to make it clear which issue it is there..

**Closed by flomotlik** 2016-09-05 17:26 UTC

**Comment by StefH** [comment] 2016-09-09 05:55
I changed my code to:

```ts 
let awsConfig: any = require('./aws-config.json');
```

and

```ts
// load AWS config
new Config(awsConfig);

// load AWS SES
let ses: SES = new SES({ apiVersion: '2010-12-01' });
```

And I removed the copy step from *CopyWebpackPlugin*.
