### ISSUE TITLE
Deploy Error: IamPolicyLambdaExecution - LogGroup doesn't exist

### ISSUE THREAD

**Issue by adambiggs** [serverless/serverless#2614] opened 2016-11-03 18:55 UTC
# This is a Bug Report

## Description

* What went wrong?
After updating to v1.1.0, adding `cfLogs: true` to my config, and deleting my existing CloudWatch log groups as instructed by the CLI, I can no longer deploy my functions.

* What did you expect should have happened?
Functions should deploy and log groups should be recreated.

* What was the config you used?
```yml
frameworkVersion: 1.1.0
service: my-service-name

provider:
  name: aws
  cfLogs: true
  runtime: nodejs4.3

  iamRoleStatements:
    - Effect: "Allow"
      Action:
        - "dynamodb:GetRecords"
        - "dynamodb:GetItem"
        - "dynamodb:Query"
        - "dynamodb:Scan"
      Resource:
        - "*"

# ...
```

* What stacktrace or error message from your provider did you see?
```
An error occurred while provisioning your stack: IamPolicyLambdaExecution
     - Template error: LogGroup /aws/lambda/my-service-name-dev-functionName
     doesn't exist.
```

## Additional Data

* ***Serverless Framework Version you're using***: v1.1.0
* ***Operating System***: OSX

**Comment by adambiggs** [comment] 2016-11-03 19:07
Seems like some kind of race condition since the log group CF is complaining about has been successfully created by that point...

```
CREATE_COMPLETE	AWS::Logs::LogGroup	FunctionNameLogGroup
```

**Comment by adambiggs** [comment] 2016-11-03 19:37
May have narrowed down the issue to a problem with function naming conventions. After commenting out the function definitions in my `serverless.yml`, I noticed that I could successfully deploy all but 2 of the 9 functions in this service.

The only thing that stands out about these two functions is that their names are a subset of two other functions in the service. E.g.:

```yml
functions:

  # This function deploys fine
  haListingContentIndex:
    # ...

  # This function fails
  haListingContent:
    # ...
```

If I remove the stage (delete the CF stack), and comment out either one of these functions, the deploy will be successful.

**Comment by martinmicunda** [comment] 2016-11-04 09:14
I have exactly the same issue with `v1.1.0` and `cfLogs` set to `true` however I am deploying these functions as separate projects.

First I deploy shift-template project:
```yml
functions:

  # This function deploys fine
  shiftTemplate:
    # ...
```

and then shift project:
```yml
functions:
  # This function fails
  shift:
    # ...
```

**Comment by faizhasim** [comment] 2016-11-06 19:05
I've verified the claims above. My workaround for this is to change the name.

So, instead of:

```yaml
someFunction:
  handler: handler.someFunction

someFunctionCallback:
  handler: handler.someFunctionCallback
```

I just rename one of the functions:

```yaml
someFunction:
  handler: handler.someFunction

2SomeFunctionCallback:
  handler: handler.someFunctionCallback
```

**Comment by acrollet** [comment] 2016-11-09 15:51
I had the same issue, changing function names to not have a common prefix worked for me as well.

**Comment by martinmicunda** [comment] 2016-11-09 15:52
changing function names is only temporary solution I think this should be mark as bug..

**Comment by ilimoinc** [comment] 2016-11-10 22:18
I have the same issue. To rename function helps me as well. Thank you.

**Comment by viz** [comment] 2016-11-10 23:11
Can we please not change the existing log group behaviour until this is fixed?

**Comment by jamesjryan** [comment] 2016-11-28 05:43
+1 renaming functions to not be a subset of each other fixes this bug.

**Comment by mzratio** [comment] 2016-12-05 05:26
+1 Same issue as well. Changing the function name fixes the problem but it is not ideal.

**Comment by antanasbrazenas** [comment] 2016-12-12 10:46
Hopefully we'll see it fixed soon, even though the workaround seems to do the thing

**Comment by eluzix** [comment] 2017-01-04 11:32
+1 same here on 1.4.0

**Comment by camhart** [comment] 2017-01-10 08:55
+1 same here on 1.5.0

**Comment by geoffdutton** [comment] 2017-01-17 03:44
The problem is AWS may update the `IamPolicyLambdaExecution` statement before all of the log groups are created, and the policy specifies all the log groups being created as resources. And then if the log group hadn't been created yet, it'll throw the error.

I wasn't able to get `DependsOn` or the `WaitHandle` to work, so for now I'm just using a wildcard for the resources: https://github.com/geoffdutton/serverless/blob/internal-master/lib/plugins/aws/deploy/lib/mergeIamTemplates.js#L132

**Comment by geoffdutton** [comment] 2017-01-18 14:40
@camhart @eluzix @mzratio How many functions are you deploying when you see this error? 

I noticed that I would be able to deploy 5-7, and then it would error out. That could be why others don't see this, or don't see this as consistently.

**Comment by eluzix** [comment] 2017-01-19 09:29
@geoffdutton I have 6 functions with the same 9 characters prefix, but the one caused me the issue shared a longer prefix with another function raised the prefix to 15 characters.

I had a function named `playlistsRemoveTrack` and the error raised while trying to add `playlistsRemove` eventually i named it `playlistRemove` which helped.

**Comment by eahefnawy** [comment] 2017-01-23 16:37
Not being able to reproduce this locally, I have been thinking hard about it for the past hour, but I can't trace this issue at the framework level. I made sure resources are created with unique names regardless of the prefix. So I'm starting to learn towards @adambiggs theory that it's a race condition on AWS. But why it only happens with prefixes? Maybe to be a naming convention issue on AWS side?

What we can do on the framework level is to add an explicitly DependOn, maybe that will kill the race condition. I'll PR soon and would love your feedback on whether that fixes this issue or not.

**Comment by geoffdutton** [comment] 2017-01-30 00:02
Here's what I've distilled it down to: https://github.com/geoffdutton/serverless-loggroup-test

It works if you use the same prefix, but as long as there more to it i.e. `someFunction` and `someFunctionAgain` will cause this, but `someFunction` and `someOtherFunction` will not cause it.

I've also checked that the log group get's created, and it does.

So weird...

**Comment by big-kahuna-burger** [comment] 2017-02-01 06:52
I can confirm this same issue as @geoffdutton commented. And it only happens when you have two functions where one function name is prefix of another function.
Example:
function1: someName,
function2: someNameExtended

Stack creation/update will fail always on adding "someName" function to yml description.

**Comment by big-kahuna-burger** [comment] 2017-02-01 07:56
What I've managed to get out from this is also that if we set existing role on provider level it succeeds.
So the issue is really with updating resources arns fails in inline policy attached to role.

**Comment by shortjared** [comment] 2017-02-01 19:16
@big-kahuna-burger This is a CloudFormation level bug, confirmed with AWS support (they were able to reproduce it).

The only quick fix besides what you did with provider level role is to rename your functions so no function is a prefix of another function.

**Comment by geoffdutton** [comment] 2017-02-01 20:46
@shortjared Thanks for finding this out. Did AWS give any idea of an ETA for a fix? I suppose it's not the end of the world now that we know it's a provider level issues...

**Comment by big-kahuna-burger** [comment] 2017-02-02 00:41
@shortjared thanks for info

**Comment by ProTip** [comment] 2017-02-17 00:45
@shortjared Is there an aws thread where they confirmed this? I'd like to get on them too.

Not too helpful that 1.6 just removed the possibility of implicit log creation :|

**Comment by rahulkulmi** [comment] 2017-02-20 10:08
I had the same issue as well. Changing the function name fixes the problem but it is not the proper solution for this bug.

**Comment by d-winter** [comment] 2017-02-20 13:14
Same problem here...

**Comment by dashmug** [comment] 2017-02-20 13:34
@shortjared Can you post the AWS thread so people can complain to AWS instead of complaining here?

**Comment by roydondsouza** [comment] 2017-02-20 14:36
Facing the same issue.

**Comment by WooDzu** [comment] 2017-02-23 16:43
Renaming helped. Renamed like this:
```
v1UsersGet => f06v1UsersGet
v1UsersPost => f07v1UsersPost
```
Hope it does not cause any blockers in the future.

**Comment by rsshilli** [comment] 2017-02-24 23:31
I feel like nobody is reading this thread, but just posting to it :-).

**Comment by dashmug** [comment] 2017-02-24 23:40
Only AWS can save us now. :-)

**Comment by jlsjonas** [comment] 2017-03-04 19:55
@rsshilli indeed 😅
@WooDzu: I actually renamed to a very similar naming to your "original" function names, and it worked fine. The issue seems to only be when you have a function that is the "base" name of another function; although your solution should prevent any issues too

**Comment by shortjared** [comment] 2017-03-06 01:44
Sorry folks, no AWS thread I am aware of... just something we had going on our support threads with them.

**Comment by pmuens** [comment] 2017-03-09 11:47
Closing this issue for now since it's something on AWS end.

Feel free to continue the discussions though!

**Closed by pmuens** 2017-03-09 11:47 UTC
Labels: status/more-info-needed

**Comment by hassankhan** [comment] 2017-03-31 10:59
Has there been any update from AWS about this?

**Comment by skbogner** [comment] 2017-04-06 15:47
What @hassankhan said.
@shortjared did you guys get anything out of AWS yet?

The workaround is nice and all, but a resolution would be awesome!

**Comment by mbruning24** [comment] 2017-05-26 15:12
+1 any word from AWS?

**Comment by bsamuel-ui** [comment] 2017-05-30 19:48
I found [this forum post](https://forums.aws.amazon.com/thread.jspa?messageID=773732&#773732) if you want to bug AWS about it.

**Comment by bsamuel-ui** [comment] 2017-07-27 17:43
Still not working. [Test with this gist.](https://gist.github.com/bsamuel-ui/cff4632e5894625bb5361646c57d1c4b)

**Comment by sharuzzaman** [comment] 2017-08-30 01:18
Hi,

I tested just now with the gist provided by @bsamuel-ui and it looks like the issue of similar name in LogGroup in Cloudformation has been fixed.

Thanks.

**Comment by noetix** [comment] 2017-10-05 04:20
Still occurring:
```
14:49:52.139      OS:                     linux
14:49:52.139      Node Version:           6.10.3
14:49:52.139      Serverless Version:     1.20.0
```
