### ISSUE TITLE
Allow multiple services behind a single API Gateway

### ISSUE THREAD

**Issue by axaubet** [serverless/serverless#3460] opened 2017-04-12 10:51 UTC
# This is a Feature Proposal

## Description
The idea would be to have several services in the same stage behind the same API Gateway instead of having each service behind it's own API Gateway. I think this should be an option as part of the stage so the Gateway gets created based just on the stage name and every service can reuse it instead of creating a new one. For example i could have a shop and user service that have been created as different sources projects and that can be deployed independently that are sharing the same API Gateway so it's easy for me to discover their location.

Possible extra config for the serverless.yml could be:
We could add and extra http event attribute called isolation
functions:
 sum:
  handler: com.gsngames.seam.services.calculator.lambda.SumOperation
  events:
    - http:
        path: calc/sum
        method: post
        **isolation: stage**

Isolation could take different values:

- stage. We deploy to an API gateway shared for the whole stage.
- service. We deploy to an API Gateway that is shared by all the endpoints inside this service definition (The current default behavior).

**Comment by pmuens** [comment] 2017-04-12 11:39
Thanks for opening @axaubet 👍 

Closing this one since it's a duplicate of https://github.com/serverless/serverless/issues/3078 where a discussion about this topic is already happening.

**Closed by pmuens** 2017-04-12 11:39 UTC
