### ISSUE TITLE
Add support for AWS CLI v2 SSO profiles

### ISSUE THREAD

**Issue by manwaring** [serverless/serverless#7567] opened 2020-04-12 03:31 UTC
# Feature Proposal
Add support for deploying with AWS credentials configured via AWS SSO (via the AWS CLI v2)

## Description

AWS CLI v2 supports setting up named credentials with temporary, assume-role access via AWS SSO.  Right now SLS is unable to use credentials setup this way to deploy.

1. What is the use case that should be solved:
- If I create an AWS profile using AWS SSO I should be able to use that profile to deploy my application

Similar or dependent issues:

- N/A (as far as I can tell from searching)

# Additional notes

This is the generic folder/file setup for AWS profiles setup via the CLI (v1 or v2, *WITHOUT SSO*)
```
# folder structure
/.aws
  config
  credentials

# config content
[profile my-profile]
region = us-east-1
output = yaml

# credentials content
[ my-profile]
aws_access_key_id = <access key id>
aws_secret_access_key =<secret access key>
```

This is the generic folder/file setup for AWS profiles setup via the CLI (v1 or v2, *WITH SSO*)
```
# folder structure
/.aws
  /sso/cache
    <hash>.json
    botocore-client-id-us-east-1.json
  config

# config content
[profile my-profile]
sso_start_url = https://<my-org-name>.awsapps.com/start
sso_region = us-east-1
sso_account_id = <aws account id>
sso_role_name = <role to assume>
region = us-east-1
output = yaml

# <hash>.json content
{
  "startUrl": "https://<my-org-name>.awsapps.com/start",
  "region": "us-east-1",
  "accessToken": "<access token>",
  "expiresAt": "2020-04-12T10:59:03UTC"
}

# botocore-client-id-us-east-1.json content
{
  "clientId": "<client id>",
  "clientSecret": "<client secret>",
  "expiresAt": "2020-07-11T02:58:59UTC"
}
```

**Comment by medikoo** [comment] 2020-04-23 14:34
@manwaring great thanks for report. Is that new method of authentication supported out of a box by `aws-sdk` ?

e.g. will following simple `aws-sdk` script just work, not requiring any further manual setup? https://github.com/medikoo/test-aws-sdk/blob/1a9f018cb571ffc21c47f22de1026443508b8db9/lambda/invoke.js#L5-L9

**Comment by manwaring** [comment] 2020-04-24 02:45
No, it looks like this would depend on https://github.com/aws/aws-sdk-js/issues/2772 for support to be added into aws-sdk

**Comment by medikoo** [comment] 2020-04-24 13:00
@manwaring in such case we depend on that. Once it's supported by `aws-sdk` it should automatically be supported in a Framework.

Also please see https://github.com/serverless/serverless/issues/7605 as final support may depend on that as well.

**Comment by gliptak** [comment] 2020-09-21 19:01
Looking at the code https://github.com/serverless/serverless/blob/master/lib/plugins/aws/provider/awsProvider.js#L84 AWS Provider seems to be reading from a single INI file. Based on https://docs.aws.amazon.com/cli/latest/userguide/cli-configure-files.html credentials might be configured either in ```~/.aws/credentials``` or ```~/.aws/config``` (and indeed ```AWS SSO``` persists configuration into ```~/.aws/config```)

**Comment by medikoo** [comment] 2020-09-22 06:47
@gliptak please see: https://github.com/serverless/serverless/issues/4838 we're working there on general improvement to how we handle AWS authentication

**Comment by urz9999** [comment] 2021-01-13 15:18
Hi guys not completely related but could it also be a viable solution for this and in general any third party tools that needs the power of AWS SSO but also wants temporary credentials in the most basic way possible, a.k.a. stored in .aws/credentials.

Check this out: https://github.com/Noovolari/leapp

**Comment by alastairmccormack** [comment] 2022-01-06 14:48
As a quick workaround, you can use: https://www.npmjs.com/package/aws-sso-creds-helper

**Comment by paulswail** [comment] 2022-03-15 20:28
It seems the dependent issue in the AWS SDK has been resolved: https://github.com/aws/aws-sdk-js/issues/2772

**Comment by ricoli** [comment] 2022-05-12 13:33
given the required changes in the AWS SDK has been merged, what needs to happen on this side to fulfil this feature request?

**Comment by PierreKiwi** [comment] 2022-08-02 21:14
Is this issue still open or should we use https://www.serverless.com/plugins/serverless-better-credentials ?

**Comment by mnapoli** [comment] 2022-08-04 09:57
Hi @PierreKiwi, the issue is currently:

<img width="94" alt="image" src="https://user-images.githubusercontent.com/720328/182819553-68f99953-b110-4fab-bb48-f1376666732f.png">

At the moment we unfortunately don't have the capacity to tackle that problem in the near future, using the plugin sounds like a good idea.

**Comment by PierreKiwi** [comment] 2022-08-04 21:59
Cool, will leverage the plugin for now. Thanks @mnapoli.

**Comment by maurostorch** [comment] 2022-10-20 17:35
https://www.npmjs.com/package/serverless-better-credentials
Very much needed! Weekly download going up on the plugin page might be a good indication to prioritize.

**Comment by erikerikson** [comment] 2022-12-13 18:36
PSA `serverless-better-credentials` [doesn't support all use cases](https://github.com/thomasmichaelwallace/serverless-better-credentials/issues/9#issuecomment-1326852460).  Perhaps its time to elevate the priority of this?

**Comment by LozanoMatheus** [comment] 2023-03-21 14:57
Hey there,

Any update on this? It would be really great to support this natively.

Also, adding one more thing to the [initial comment](https://github.com/serverless/serverless/issues/7567#issue-598401728). The AWS CLI/SSO will also create another folder after the first login attempt, it's in the `~/.aws/cli/cache/*.json`.

```text
~/.aws/
├── cli
│   └── cache
│       └── <HASH>.json
├── config
├── credentials
└── sso
    └── cache
        ├── <HASH>.json
        └── <HASH>.json
```

This file contains the `AWS_ACCESS_KEY_ID`, `AWS_SECRET_ACCESS_KEY`, and other things. You can see the example below of the file `~/.aws/cli/cache/<HASH>.json`.

```json
{
  "ProviderType": "sso",
  "Credentials": {
    "AccessKeyId": "<AccessKeyId>",
    "SecretAccessKey": "<SecretAccessKey>",
    "SessionToken": "<SessionToken>",
    "Expiration": "<Expiration>"
  }
}
```

We could use this to bind to the [AWS environment variables](https://docs.aws.amazon.com/cli/latest/userguide/cli-configure-envvars.html). So, it would support all the AWS SSO configs.

There is more info about the AWS SSO/IC here: [IAM Identity Center credential provider](https://docs.aws.amazon.com/sdkref/latest/guide/feature-sso-credentials.html).

**Comment by bneigher** [comment] 2023-08-04 18:53
any updated on if/when this will be supported?  I currently am needing to manually put in `~/.aws/credentials` mimicking the old sso mechanism to run sls commands locally

**Comment by PierreKiwi** [comment] 2023-08-04 19:47
My current approach is the following a small wrapper to export the credentials into env variables and to disable the AWS_PROFILE before calling `sls`. 

Example:

```bash
eval $(aws configure export-credentials --profile ${AWS_PROFILE} --format env) && env -u AWS_PROFILE yarn sls
```

or, in `package.json`

```json
{
  ...
  "scripts": {
    ...
    "serverless": "yarn sls",
    "sls": "eval $(aws configure export-credentials --profile ${AWS_PROFILE} --format env) && env -u AWS_PROFILE sls"
  }
}
```  


More details about `export-credentials` are available [here](https://awscli.amazonaws.com/v2/documentation/api/latest/reference/configure/export-credentials.html).

Note: I think it is available in AWS CLI v2 only but I cannot found the exact date it has been released (October 2022 ?).

**Comment by bneigher** [comment] 2023-08-05 19:55
I went with 
https://github.com/victorskl/yawsso.. makes v2 to v1 sso backwards compatible

**Comment by et304383** [comment] 2024-01-23 13:03
Apreciate all the work that goes into the serverless framework but this REALLY needs to be top priority.  AWS is driving everyone to use IAM Identity Center now and relying on third party tools like yawsso isn't great, especially since that goes against the refreshable tokens that are now supported.

**Comment by ac360** [comment] 2024-01-27 02:03
Sincere apologies for the slow action here. This has been completed in upcoming V.4.

**Comment by et304383** [comment] 2024-01-29 11:50
> Sincere apologies for the slow action here. This has been completed in upcoming V.4.

So does this mean it won't be in place until the next major serverless release (4.0+) ?

**Comment by ac360** [comment] 2024-01-30 02:37
Yes. To fix this, we had to rework the traditional credential handling that the Framework has had for many years, so it is a breaking change, fitting the criteria of a major release. FWIW, this work has been completed in V.4, and the V.4 beta is coming likely next week.

**Comment by et304383** [comment] 2024-03-21 13:49
> @et304383 Yes. To fix this, we had to rework the traditional credential handling that the Framework has had for many years, so it is a breaking change, fitting the criteria of a major release. FWIW, this work has been completed in V.4, and the V.4 beta is coming likely next week.

@ac360 is the beta out yet?  I'd like to try working with this.  I do not see any release for this yet.

**Comment by ac360** [comment] 2024-03-21 14:21
@et304383 Yep, it's here: https://github.com/serverless/serverless/tree/v4.0

**Comment by navrkald** [comment] 2024-04-17 14:32
Any plans/roadmap to release Serverless v4?

**Comment by skierkowski** [comment] 2024-08-13 17:51
This has been released in Serverless v4 GA.

**Closed by skierkowski** 2024-08-13 17:51 UTC
Labels: enhancement, question, cat/aws-auth, V4
