### ISSUE TITLE
AWS_REGION environment variable doesn't work

### ISSUE THREAD

**Issue by jamy015** [serverless/serverless#3947] opened 2017-07-18 17:15 UTC
# This is a Bug Report

## Description

For bug reports:
* What went wrong? I set the AWS_REGION environment variable to `eu-west-1` as described in the [documentation](https://github.com/serverless/serverless/blob/master/docs/providers/aws/guide/credentials.md), but my API was deployed to `us-east-1`
* What did you expect should have happened? The API should have been deployed to the `eu-west-1` AWS region
* What was the config you used? A config without a default region set
* What stacktrace or error message from your provider did you see?

For feature proposals:
* What is the use case that should be solved. The more detail you describe this in the easier it is to understand for us.
* If there is additional config how would it look

Similar or dependent issues:
* #2151

## Additional Data

* ***Serverless Framework Version you're using***: 1.17.0
* ***Operating System***: Windows 10 (1703)
* ***Stack Trace***:
* ***Provider Error messages***:

**Comment by horike37** [comment] 2017-07-19 06:54
I also have reproduced this on my local.
Here is my serverless.yml and a config without default region.

```yaml
service: aws-nodejs-testestes

provider:
  name: aws
  runtime: nodejs4.3

functions:
  hello:
    handler: handler.hello
    events:
      - http:
          path: hello
          method: get
```

@pmuens Is this bug or the document go wrong?

**Comment by pmuens** [comment] 2017-07-19 11:24
Thanks for opening @jamy015 and thanks for jumping in @horike37 👍 

🤔 AFAIK we start the Serverless process by setting the `stage` and `region` to the options or provider values (https://github.com/serverless/serverless/blob/af268cd72885aa4625819d51b0faace401359cf7/lib/plugins/aws/lib/validate.js#L12-L17).

So the env variables is never evaluated. Not sure if it's a bug since the usage of `AWS_REGION` is not documented somewhere (or I missed smth.).

/cc @eahefnawy

**Comment by eahefnawy** [comment] 2017-07-19 11:28
hmmm I thought the aws-sdk would pick this up automatically 🤔

**Comment by horike37** [comment] 2017-07-19 14:59
@eahefnawy @pmuens 

I'm doing the deep debugging on this. Seems like that would fix to add the process of picking `AWS_REGION` env var to the following 2 places.
https://github.com/serverless/serverless/blob/af268cd72885aa4625819d51b0faace401359cf7/lib/plugins/aws/lib/validate.js#L15-L16
https://github.com/serverless/serverless/blob/master/lib/plugins/aws/provider/awsProvider.js#L227-L228

Then, I'm considering the following priority to pick the region config up. What do you think?
1. CLI option like `--region=eu-west-1`
2. `AWS_REGION` env var
3. setting in serverless.yml
4. if nothing to setting, set `us-east-1` automatically

**Comment by eahefnawy** [comment] 2017-07-19 15:15
@horike37 I'm thinking the env var should go before the cli option, specially that it's an AWS env var, not Serverless.

Eitherway, I know `AWS_PROFILE` is working, so we can copy the priority from there 😊 

Thanks @horike37 🙌

**Comment by jamy015** [comment] 2017-07-19 17:35
@eahefnawy @horike37 I would think this order makes the most sense:


1.    CLI option like `--region=eu-west-1`
2.    setting in serverless.yml
3.    `AWS_REGION` env var
4.    setting in `~\.aws\config` (set by the AWS CLI)
5.    if nothing to setting, set us-east-1 automatically

My reasoning behind this is that more specific options should, IMO, get more precedence:

- the CLI option is the most specific because I'm telling serverless right there on the command line that I want to do that
- `serverless.yml` is specific to the service being deployed
- `AWS_REGION` is specific to serverless on the machine
- `~\.aws\config` is specific to the AWS config on the machine

**Comment by horike37** [comment] 2017-07-19 22:40
Thank you for the opinion @jamy015! surely, the region setting in `~\.aws\config` also doesn't work..(I have also tried)
IMO, the env vars for `aws-sdk` should be given priority over the service setting as well as `AWS_PROFILE`.

**Comment by ozbillwang** [comment] 2017-10-02 11:26
@horike37 

Here is my workaround, `AWS_DEFAULT_REGION` is an environment variable, it should be set like this:

```
provider:
  name: aws
  runtime: nodejs6.10
  region: ${env:AWS_DEFAULT_REGION}
```

**Comment by Fohlen** [comment] 2017-11-16 23:12
I can report that this also doesn't work for me.

**Comment by xgiovio** [comment] 2018-11-30 16:41
i can confirm the bug is still present on the latest version of serverless framework 1.34

**Comment by Govinda-Fichtner** [comment] 2019-11-05 15:41
This bug seems to be present in v1.56.1 as well.

**Comment by peternann** [comment] 2019-12-04 14:07
I found my way here as a new serverless user, wondering why serverless was ignoring my region setting in ~/.aws/config, even though I clearly specify the profile in serverless.yml.

I totally concur with the 5-levels of source for AWS region that @jamy015 wrote on 20 Jul 2017 (!). New users will expect sls to piggy-back off normal AWS config (including profile semantics), unless specified in the .yml.

**Comment by medikoo** [comment] 2020-11-26 12:47
AWS and Serverless CLI's never supported and does not support `AWS_REGION` variable. 

Check https://docs.aws.amazon.com/cli/latest/userguide/cli-configure-envvars.html#envvars-list for lists of all env vars as supported by AWS CLI.

AWS CLI supports `AWS_DEFAULT_REGION` of which support is broken in Framework, and matter is handled at https://github.com/serverless/serverless/issues/2151

`AWS_REGION` env variable exists in lambda environment, to indicate in which region given lambda is executed (so in Framework codebese you may see it being assigned for local invocations.

I've removed the invalid documentation which referenced this variable with https://github.com/serverless/serverless/commit/739045d9bb03ddefcacceca0bd39f188517b187d

Closing as this variable should not and was not intended to have influence on deployment process

**Closed by medikoo** 2020-11-26 12:47 UTC
Labels: bug, help wanted
