### ISSUE TITLE
Add API Gateway using WAF support

### ISSUE THREAD

**Issue by luan-cestari** [serverless/serverless#5478] opened 2018-11-12 10:52 UTC
Hi,

I saw this new feature https://aws.amazon.com/about-aws/whats-new/2018/10/amazon-api-gateway-adds-support-for-aws-waf/ and thought it would be useful if serverless could also configure WAF for API Gateway.

**Comment by dschep** [comment] 2018-11-12 13:45
Duplicate of #5452

**Closed by dschep** 2018-11-12 13:45 UTC
