### ISSUE TITLE
deploying a typescript application while using serverless.ts instead of serverless.yml

### ISSUE THREAD

**Issue by dekmakmosafa** [serverless/serverless#9339] opened 2021-04-20 21:25 UTC
I am using the latest serverless framework : 

My Environment Information ---------------------------
     Operating System:          linux
     Node Version:              14.15.1
     Framework Version:         2.37.0 (local)
     Plugin Version:            4.5.3
     SDK Version:               4.2.2
     Components Version:        3.8.3
----------------------------------------------------------------------------
while deploying my typescript application I got this error :  Error: ENOENT: no such file or directory, open '/project/serverless.yml'. which before 20/04/2021 was working perfectly normally.

Note am using the serverless-webpack plugin to compile my ts code, and I was using the serverless.ts file instead of the serverless.yml file for a long time now

this is my serverless.ts file : 
import {Serverless} from 'serverless/aws';
import UserRoutes from "./Modules/User/routes";

const serverlessConfiguration: Serverless = {
    service: {
        name: 'project',
       
    },
    frameworkVersion: '2',
    custom: {
        'serverless-offline': {
            httpPort: 4001,
            lambdaPort: 4002
        },
        webpack: {
            webpackConfig: './webpack.config.js',
            includeModules: true,
            forceInlucde: ['pg']
        }

    },
    plugins: ['serverless-webpack', 'serverless-offline', 'serverless-step-functions'],
    provider: {
        name: 'aws',
        runtime: 'nodejs12.x',
        region: 'eu-west-1',
        apiGateway: {
            minimumCompressionSize: 1024,
        },
        environment: {
            AWS_NODEJS_CONNECTION_REUSE_ENABLED: '1',
            ENVIROMENT: process.env.ENVIROMENT
        },
    },

    functions: {
        ...UserRoutes,
    },
  
};

module.exports = serverlessConfiguration;

**Comment by pgrzesik** [comment] 2021-04-21 09:37
Hello @dekmakmosafa - could you please follow the standard issue template that is visible when you try to submit a new issue? It's going to be helpful with diagnosing your issue here.

**Comment by ffxsam** [comment] 2021-04-22 02:48
I'll open an issue with all the details. This is a new bug affecting probably everyone with TypeScript projects.

Please don't take this the wrong way, but aren't tests run before new versions are published? This is a pretty glaring mistake. Granted, one can always downgrade, or deploy using `-c serverless.ts`, but still, I'm sure quite a few people with CI/CD setups got tripped up and had to spend some time figuring out what went wrong.

**Comment by ffxsam** [comment] 2021-04-22 03:01
See #9351 - same bug, full details.

**Comment by pgrzesik** [comment] 2021-04-22 07:15
Thanks @ffxsam for reporting full issue - it seems like these two are caused by the same bug, so I'm going to close this one in favor of #9351 - we should have a bugfix coming soon as well

**Closed by pgrzesik** 2021-04-22 07:15 UTC
Labels: question
