### ISSUE TITLE
Support JSON output for info command

### ISSUE THREAD

**Issue by icholy** [serverless/serverless#11610] opened 2022-12-15 02:28 UTC
### Is there an existing issue for this?

- [X] I have searched existing issues, it hasn't been reported yet

### Use case description

I have dozens of services managed with separate `serverless.yml` files and I'm wanted to write a script the enumerates all the lambdas and api gateways across all these services. It is possible to parse the output of `sls info`.

```
service: company-service
stage: dev
region: us-east-1
stack: company-service-dev
endpoints:
  ANY - https://v2olv6r5t4.execute-api.us-east-1.amazonaws.com/dev/service
  ANY - https://v2olv6r5t4.execute-api.us-east-1.amazonaws.com/dev/service/{proxy+}
functions:
  root: company-service-dev-root
  catchall: company-service-dev-catchall
  cache_refresh: company-service-dev-cache_refresh
Serverless Domain Manager:
  Domain Name: service.api.company.org
  Target Domain: d14p38johl51vr.cloudfront.net
  Hosted Zone Id: Z2FDTNDATAQYW2
```

But it would be a lot easier if could have the same info available as json:

``` json
{ 
    "service": "company-service",
    "stage": "dev",
    "region": "us-east-1",
    "stack": "company-service-dev",
    "endpoints": [
        "ANY - https://v2olv6r5t4.execute-api.us-east-1.amazonaws.com/dev/service",
        "ANY - https://v2olv6r5t4.execute-api.us-east-1.amazonaws.com/dev/service/{proxy+}"
    ],
    "functions": {
        "root": "company-service-dev-root",
        "catchall": "company-service-dev-catchall",
        "cache_refresh": "company-service-dev-cache_refresh"
    },
    "Serverless Domain Manager": {
        "Domain Name": "service.api.company.org",
        "Target Domain": "d14p38johl51vr.cloudfront.net",
        "Hosted Zone Id": "Z2FDTNDATAQYW2"
    }
}
```

### Proposed solution (optional)

There could be an optional `-json` flag added to the `info` command. 

**Example**: `sls info -json`.

**Comment by medikoo** [comment] 2022-12-15 09:31
Duplicate of https://github.com/serverless/serverless/issues/3089

**Closed by medikoo** 2022-12-15 09:31 UTC
