### ISSUE TITLE
Serverless errors on CF instruction being put into provider.httpApi.id

### ISSUE THREAD

**Issue by dotorg-hala** [serverless/serverless#7700] opened 2020-05-08 19:41 UTC
#### Q1: Describe the issue
I have a shared httpApi that I am creating externally and I export its ID to CloudFormation Exports and store the Name of that export in my Custom section in my serverless.yml file. I use this shared httpApi for all my services. I am importing the httpApi ID for reuse in my various services using `Fn::ImportValue.` When importing using the following:

```
custom:
  variables:
    ...
    httpApiGateway: servicesHttpApi-${self:provider.stage}
```

```
provider:
  ...
  httpApi:
    id: 'Fn::ImportValue': ${self:custom.variables.httpApiGateway}
```

on deploy, the stack deploys to CloudFormation successfully and completes successfully but the servlerless deploy command ends with this error:

```
Serverless Error ---------------------------------------
 
  ServerlessError: Expected params.ApiId to be a string
      at /Users/hala/.nvm/versions/node/v13.3.0/lib/node_modules/serverless/lib/plugins/aws/provider/awsProvider.js:331:27
      at processTicksAndRejections (internal/process/task_queues.js:97:5)

```
#### Q2: content of serverless.yml

<details>
<summary><code>serverless.yml</code></summary>

```yaml
service: <service_name>
org: <my_org>
app: <my_service>

frameworkVersion: ">=1.70.0 <2.0.0"

c# app and org for use with dashboard.serverless.com
service: ns-create-org
org: dotorg
app: services

# You can pin your service to only deploy with a specific Serverless version
frameworkVersion: ">=1.70.0 <2.0.0"

custom:
  # standard custom variables sourced from central file
  variables:
    DDB_MAIN_TABLE: <our_table>-${self:provider.stage}    
    httpApiGateway: servicesHttpApi-${self:provider.stage}
    LOGGING_NAME: ${self:service}


# aws specific settings
provider:
  name: aws
  runtime: python3.8
  stage: ${opt:stage, 'local'}
  log: ${opt:log, 'info'}
  region: us-west-2
  stackName: ${self:service}-${self:provider.stage}
  httpApi:
    id: 'Fn::ImportValue': agw-${self:custom.variables.httpApiGateway}-id

  iamRoleStatements:
    - Effect: Allow
      Action:
        - dynamodb:PutItem
        - dynamodb:DescribeTable
      Resource:
        - Fn::ImportValue: ddb-${self:custom.variables.DDB_MAIN_TABLE}-arn

  # you can define service wide environment variables here
  environment:
    DDB_MAIN_TABLE: ${self:custom.variables.DDB_MAIN_TABLE}
    STAGE: ${self:provider.stage}
    LOG_LEVEL: ${self:provider.log}
    LOGGING_NAME: ${self:custom.variables.LOGGING_NAME}


functions:
  createOrg:
    handler: src/createOrg.handler
    name: lambda-${self:service}-${self:provider.stage}
    events:
      - httpApi:
          method: POST
          path: /orgs

resources:
  Outputs:
    # export ARNs for cross stack references
    createOrgArn:
      Value:
        'Fn::GetAtt': [CreateOrgLambdaFunction, Arn ]
      Export:
        Name: ${self:service}-${self:provider.stage}
```
</details>

#### Q3: Provide (in below placeholder) FULL name and output of command that exposes the problem.

<details>
<summary><b><code>sls deploy -s dev</code> output</b></summary>

```
hala@halas-mbp test-auth % sls deploy --stage dev
Serverless: Load command interactiveCli
Serverless: Load command config
Serverless: Load command config:credentials
Serverless: Load command config:tabcompletion
Serverless: Load command config:tabcompletion:install
Serverless: Load command config:tabcompletion:uninstall
Serverless: Load command create
Serverless: Load command install
Serverless: Load command package
Serverless: Load command deploy
Serverless: Load command deploy:function
Serverless: Load command deploy:list
Serverless: Load command deploy:list:functions
Serverless: Load command invoke
Serverless: Load command invoke:local
Serverless: Load command info
Serverless: Load command logs
Serverless: Load command metrics
Serverless: Load command print
Serverless: Load command remove
Serverless: Load command rollback
Serverless: Load command rollback:function
Serverless: Load command slstats
Serverless: Load command plugin
Serverless: Load command plugin
Serverless: Load command plugin:install
Serverless: Load command plugin
Serverless: Load command plugin:uninstall
Serverless: Load command plugin
Serverless: Load command plugin:list
Serverless: Load command plugin
Serverless: Load command plugin:search
Serverless: Load command config
Serverless: Load command config:credentials
Serverless: Load command rollback
Serverless: Load command rollback:function
Serverless: Load command upgrade
Serverless: Load command uninstall
Serverless: Load command login
Serverless: Load command logout
Serverless: Load command generate-event
Serverless: Load command test
Serverless: Load command dashboard
Serverless: Load command output
Serverless: Load command output:get
Serverless: Load command output:list
Serverless: Load command param
Serverless: Load command param:get
Serverless: Load command param:list
Serverless: Load command studio
Serverless: Load command dev
Serverless: Invoke deploy
Serverless: Invoke package
Serverless: Invoke aws:common:validate
Serverless: Invoke aws:common:cleanupTempDir
Serverless: Packaging service...
Serverless: Excluding development dependencies...
Serverless: Invoke aws:package:finalize
Serverless: Invoke aws:common:moveArtifactsToPackage
Serverless: Invoke aws:common:validate
Serverless: Invoke aws:deploy:deploy
Serverless: [AWS cloudformation 200 0.428s 0 retries] describeStacks({ StackName: 'test-auth' })
Serverless: [AWS cloudformation 200 0.195s 0 retries] describeStackResource({
  StackName: 'test-auth',
  LogicalResourceId: 'ServerlessDeploymentBucket'
})
Serverless: [AWS s3 200 0.232s 0 retries] listObjectsV2({
  Bucket: '...',
  Key: '...'
})
Serverless: [AWS s3 200 0.202s 0 retries] headObject({
  Bucket: '...',
  Key: '...'
})
Serverless: [AWS s3 200 0.207s 0 retries] headObject({
  Bucket: '...',
  Key: '...'
})
Serverless: [AWS lambda 200 0.299s 0 retries] getFunction({ FunctionName: 'lambda-test-auth' })
Serverless: [AWS sts 200 0.315s 0 retries] getCallerIdentity({})
Serverless: Uploading CloudFormation file to S3...
Serverless: [AWS s3 200 0.235s 0 retries] putObject({
  Body: <Buffer 7b 22 41 57 53 54 65 6d 70 6c 61 74 65 46 6f 72 6d 61 74 56 65 72 73 69 6f 6e 22 3a 22 32 30 31 30 2d 30 39 2d 30 39 22 2c 22 44 65 73 63 72 69 70 74 ... 3773 more bytes>,
  Bucket: '...',
  Key: '...',
  ContentType: 'application/json',
  Metadata: { filesha256: '...' }
})
Serverless: Uploading artifacts...
Serverless: Uploading service test-auth.zip file to S3 (97.25 KB)...
Serverless: [AWS s3 200 1.033s 0 retries] putObject({
  Body: <Buffer 50 4b 03 04 14 00 08 00 08 00 00 00 21 00 00 00 00 00 00 00 00 00 00 00 00 00 09 00 00 00 52 45 41 44 4d 45 2e 6d 64 53 56 08 4e 2d 2a cb 4c 4e 2d 56 ... 99537 more bytes>,
  Bucket: '...',
  Key: '...',
  ContentType: 'application/zip',
  Metadata: { filesha256: '...' }
})
Serverless: Validating template...
Serverless: [AWS cloudformation 200 0.385s 0 retries] validateTemplate({
  TemplateURL: '.../compiled-cloudformation-template.json'
})
Serverless: Updating Stack...
Serverless: [AWS cloudformation 200 0.804s 0 retries] updateStack({
  StackName: 'test-auth',
  Capabilities: [ 'CAPABILITY_IAM', 'CAPABILITY_NAMED_IAM', [length]: 2 ],
  Parameters: [ [length]: 0 ],
  TemplateURL: '.../compiled-cloudformation-template.json',
  Tags: [ { Key: 'STAGE', Value: 'dev' }, [length]: 1 ]
})
Serverless: Checking Stack update progress...
Serverless: [AWS cloudformation 200 0.253s 0 retries] describeStackEvents({
  StackName: '...'
})
.Serverless: [AWS cloudformation 200 0.423s 0 retries] describeStackEvents({
  StackName: '...'
})
Serverless: [AWS cloudformation 200 0.228s 0 retries] describeStackEvents({
  StackName: '...'
})
Serverless: [AWS cloudformation 200 0.23s 0 retries] describeStackEvents({
  StackName: '...'
})
Serverless: [AWS cloudformation 200 0.23s 0 retries] describeStackEvents({
  StackName: '...'
})
.....Serverless: [AWS cloudformation 200 0.861s 0 retries] describeStackEvents({
  StackName: '...'
})
...
Serverless: Stack update finished...
Serverless: Invoke aws:info
Serverless: [AWS apigatewayv2 undefined 0.005s 0 retries] getApi({ ApiId: { 'Fn::ImportValue': 'servicesHttpApi-id' } })
 
  Serverless Error ---------------------------------------
 
  ServerlessError: Expected params.ApiId to be a string
      at /Users/hala/.nvm/versions/node/v13.3.0/lib/node_modules/serverless/lib/plugins/aws/provider/awsProvider.js:331:27
      at processTicksAndRejections (internal/process/task_queues.js:97:5)
 
  Get Support --------------------------------------------
     Docs:          docs.serverless.com
     Bugs:          github.com/serverless/serverless/issues
     Issues:        forum.serverless.com
 
  Your Environment Information ---------------------------
     Operating System:          darwin
     Node Version:              13.3.0
     Framework Version:         1.70.0
     Plugin Version:            3.6.11
     SDK Version:               2.3.0
     Components Version:        2.30.10
 
Serverless: [AWS cloudformation 200 0.534s 0 retries] describeStacks({ StackName: 'test-auth' })

```
</details>

#### Q4: Output of serverless --version

<b>Framework Core: 1.70.0
Plugin: 3.6.11
SDK: 2.3.0
Components: 2.30.10
</b>

This issue was happening in the previous framework version as well. And it happens whether I have my service connected to the serverless dashboard or not.

This is not a blocking error as my service stacks are deploying successfully to AWS, it's just a serverless framework error that shows all my deploys in the serverless dashboard as Failed.

**Comment by medikoo** [comment] 2020-05-09 17:22
@dotorg-hala thanks for report. Can you please respect all guidelines in bug report template and answer all questions carefully?

Unfortunately provided information is not sufficient enough to understand the source of the issue

**Comment by dotorg-hala** [comment] 2020-05-11 18:46
@medikoo apologies for not following the template. I've updated my report, thanks for your time and patience.

**Comment by medikoo** [comment] 2020-05-12 07:11
Thanks @dotorg-hala 

> I have SLS_DEBUG=* so the results are quite verbose but here's a snippet and can provide the full result of needed

Full result would be helpful, note that section is intentionally collapsed, so eventual long output doesn't interfere with issue readability.

Anyway from what I see, you've put a CloudFormation instruction at `provider.httpApi.id` while it needs to put in direct form.

Note we just pass the value as is in config directly to CF template, and it's AWS that responds with error you see

**Comment by dotorg-hala** [comment] 2020-05-14 00:51
@medikoo I've added the full SLS_DEBUG output. FWIW I don't see any errors in the CloudFormation events and the stacks complete successfully and attach the lambdas to the right API Gateway.

**Comment by medikoo** [comment] 2020-05-14 06:38
> @medikoo I've added the full SLS_DEBUG output. 

Thanks, now I can diagnose it properly. There's indeed an issue. While CF instructions seems work for deployment, it's not configured to work in further where we try to retrieve info about deployed HTTP API, and it crashes here: https://github.com/serverless/serverless/blob/522e9c0ff822295a19447939b641459118e0cb37/lib/plugins/aws/info/getStackInfo.js#L34

Issue on our side, is that we do not validate `apiId` and do not throw meaningful error if it's not passed as plain string. That can be addressed once we have schema validation mechanism in: https://github.com/serverless/serverless/issues/6562 and it should happen shortly.

Otherwise we can also add support for CF instructions, by updating code responsible for getting info about HTTP API. PR's welcome

**Comment by WSanders31** [comment] 2020-06-12 16:50
Any updates on this? This causes errors on deployments, but the actual stacks get stood up regardless. 

Anyone have a workaround to this problem?

**Comment by WSanders31** [comment] 2020-07-16 13:45
Hey! Just wanted to post that the most recent release of 1.75.x has fixed this issue. Looks great.

**Comment by medikoo** [comment] 2020-07-16 13:56
Yes, indeed, I didn't notice this issue is an actual duplicate (of issue that was addressed recently)

**Comment by medikoo** [comment] 2020-07-16 13:56
Duplicate of https://github.com/serverless/serverless/issues/7791

**Closed by medikoo** 2020-07-16 13:56 UTC
Labels: cat/aws-event-http-api, enhancement, help wanted
