### ISSUE TITLE
error message "undefined" when using sls deploy

### ISSUE THREAD

**Issue by nilskassube** [serverless/serverless#1485] opened 2016-07-05 09:00 UTC
##### Serverless Framework Version: 

1.0 alpha 1 

##### Operating System: 

Mac OS X 10.11.5

##### Expected Behavior:

Getting an error message about what is wrong.

##### Actual Behavior:

sls deploy
Serverless: Zipping functions...
Serverless: Uploading zip files to S3...
Serverless: Adding function resources to CF...
Serverless: Updating Stack...
Serverless: Checking stack update progress...
Serverless: Checking stack update progress...
  Serverless Error ---------------------------------------
 
     An error occurred while provisioning your cloudformation: undefined
 
  Get Support --------------------------------------------
     Docs:          v1.docs.serverless.com
     Bugs:          github.com/serverless/serverless/issues

**Comment by danhumphrey** [comment] 2016-07-05 09:51
I get the same error, but only after I remove, then re-deploy a service.

Steps to reproduce:

1. sls deploy

```
...
Serverless: Deployment successful!
```
2. sls remove
```
...
Serverless: Resource removal successful!
```
3. sls deploy

```
Serverless: Creating Stack...
Serverless: Checking stack creation progress...
Serverless: Checking stack creation progress...
Serverless: Checking stack creation progress...
Serverless: Checking stack creation progress...
Serverless: Checking stack creation progress...
Serverless: Checking stack creation progress...
Serverless: Checking stack creation progress...
Serverless: Checking stack creation progress...
Serverless: Checking stack creation progress...
Serverless: Checking stack creation progress...
Serverless: Checking stack creation progress...
Serverless: Checking stack creation progress...
Serverless: Checking stack creation progress...
Serverless: Checking stack creation progress...
Serverless: Checking stack creation progress...
Serverless: Checking stack creation progress...
Serverless: Stack successfully created.
Serverless: Zipping functions...
Serverless: Uploading zip files to S3...
Serverless: Adding function resources to CF...
Serverless: Updating Stack...
Serverless: Checking stack update progress...
Serverless: Checking stack update progress...
  Serverless Error ---------------------------------------

     An error occurred while provisioning your cloudformation: undefined

  Get Support --------------------------------------------
     Docs:          v1.docs.serverless.com
     Bugs:          github.com/serverless/serverless/issues
```

**Comment by pmuens** [comment] 2016-07-05 09:52
Thanks for reporting 👍

**Comment by danhumphrey** [comment] 2016-07-05 10:54
Not sure if this should be a seperate issue, but my steps above aren't quite accurate and I want to be exact...

I have reproduced the issues and these are the exact steps based upon your v1 tutorial:

```
danhumphrey$ serverless create --name whatever --provider aws
```
```
Serverless: Creating new Serverless service...
Serverless: Successfully created service "whatever"
Serverless:   |- serverless.yaml
Serverless:   |- serverless.env.yaml
Serverless:   |- handler.js
```

```
danhumphrey$ serverless deploy
```

```
Serverless: Creating Stack...
Serverless: Checking stack creation progress...
Serverless: Checking stack creation progress...
Serverless: Checking stack creation progress...
Serverless: Checking stack creation progress...
Serverless: Checking stack creation progress...
Serverless: Checking stack creation progress...
Serverless: Checking stack creation progress...
Serverless: Checking stack creation progress...
Serverless: Checking stack creation progress...
Serverless: Checking stack creation progress...
Serverless: Checking stack creation progress...
Serverless: Checking stack creation progress...
Serverless: Checking stack creation progress...
Serverless: Checking stack creation progress...
Serverless: Checking stack creation progress...
Serverless: Stack successfully created.
Serverless: Zipping functions...
Serverless: Uploading zip files to S3...
Serverless: Adding function resources to CF...
Serverless: Updating Stack...
Serverless: Checking stack update progress...
Serverless: Checking stack update progress...
Serverless: Checking stack update progress...
Serverless: Deployment successful!
```

```
danhumphrey$ sls remove
```
```
Serverless: Getting all objects in S3 bucket...
Serverless: Removing objects in S3 bucket...
Serverless: Removing Stack...
Serverless: Checking stack removal progress...
Serverless: Checking stack removal progress...
Serverless: Checking stack removal progress...
Serverless: Checking stack removal progress...
Serverless: Checking stack removal progress...
Serverless: Resource removal successful!
```

```
danhumphrey$ serverless deploy
```

```
Serverless: Creating Stack...
Serverless: Checking stack creation progress...
Serverless: Checking stack creation progress...
Serverless: Checking stack creation progress...
Serverless: Checking stack creation progress...
Serverless: Checking stack creation progress...
Serverless: Checking stack creation progress...
Serverless: Checking stack creation progress...
Serverless: Checking stack creation progress...
Serverless: Checking stack creation progress...
Serverless: Checking stack creation progress...
Serverless: Checking stack creation progress...
Serverless: Checking stack creation progress...
Serverless: Checking stack creation progress...
Serverless: Checking stack creation progress...
Serverless: Checking stack creation progress...
Serverless: Stack successfully created.
Serverless: Zipping functions...
Serverless: Uploading zip files to S3...
Serverless: Adding function resources to CF...
Serverless: Updating Stack...
Serverless: Checking stack update progress...
Serverless: Checking stack update progress...
Serverless: Checking stack update progress...
Serverless: Deployment successful!
```

I then added an events section to serverless.yaml...:

```
 events:
                - http:
                    path: greet
                    method: get
```
.. and deployed

```
danhumphrey$ serverless deploy
```
```
Serverless: Zipping functions...
Serverless: Uploading zip files to S3...
Serverless: Adding function resources to CF...
Serverless: Updating Stack...
Serverless: Checking stack update progress...
  Serverless Error ---------------------------------------

     An error occurred while provisioning your cloudformation: The following resource(s) failed to create: [RestApiApigEvent].

  Get Support --------------------------------------------
     Docs:          v1.docs.serverless.com
     Bugs:          github.com/serverless/serverless/issues
```

```
danhumphrey$ sls remove
```
```
Serverless: Getting all objects in S3 bucket...
Serverless: Removing objects in S3 bucket...
Serverless: Removing Stack...
Serverless: Checking stack removal progress...
Serverless: Checking stack removal progress...
Serverless: Checking stack removal progress...
Serverless: Checking stack removal progress...
Serverless: Checking stack removal progress...
Serverless: Resource removal successful!
```

```
danhumphrey$ sls deploy
```

```
Serverless: Creating Stack...
Serverless: Checking stack creation progress...
Serverless: Checking stack creation progress...
Serverless: Checking stack creation progress...
Serverless: Checking stack creation progress...
Serverless: Checking stack creation progress...
Serverless: Checking stack creation progress...
Serverless: Checking stack creation progress...
Serverless: Checking stack creation progress...
Serverless: Checking stack creation progress...
Serverless: Checking stack creation progress...
Serverless: Checking stack creation progress...
Serverless: Checking stack creation progress...
Serverless: Checking stack creation progress...
Serverless: Checking stack creation progress...
Serverless: Checking stack creation progress...
Serverless: Checking stack creation progress...
Serverless: Stack successfully created.
Serverless: Zipping functions...
Serverless: Uploading zip files to S3...
Serverless: Adding function resources to CF...
Serverless: Updating Stack...
Serverless: Checking stack update progress...
Serverless: Checking stack update progress...
  Serverless Error ---------------------------------------

     An error occurred while provisioning your cloudformation: undefined

  Get Support --------------------------------------------
     Docs:          v1.docs.serverless.com
     Bugs:          github.com/serverless/serverless/issues
```

As you can see, this differs from the 'deploy, remove, deploy' steps I posted above.

Hope this helps!

**Comment by pmuens** [comment] 2016-07-05 11:01
Thank you for the detailed steps to reproduce! This helps a log.

We'll look into it ASAP!

**Comment by tengis** [comment] 2016-07-20 02:45
i have exact same issue

**Comment by tengis** [comment] 2016-07-20 06:16
solved 
`
                - http:
                    path: greet
                    method: get
`

to

`
                - http:
                  path: greet
                  method: get
`

**Comment by tengis** [comment] 2016-07-21 01:29
Hey guys @pmuens @danhumphrey i think i found a answer. i saw the weird error on my console.
<img width="1194" alt="screen shot 2016-07-21 at 11 26 15 am" src="https://cloud.githubusercontent.com/assets/358442/17008592/f7647620-4f35-11e6-9970-5f1e19327752.png">

then i spoken about this AWS support. They said

> reason is because API Gateway in cloudformation is not yet supported in SYD.

> cloudformation the service endpoint is different. So not all the api call can be processed. This cause cloudformation always one step behind.

So they gonna release feature soon but no ETA

**Comment by pmuens** [comment] 2016-07-21 06:05
@tengis thanks for doing a follow up with a detailed description!

Would be interesting to know if @nilskassube is also using SYD.

**Comment by pmuens** [comment] 2016-08-19 11:26
Closing this one since we've released Serverless beta.2 (which includes some major changes to the APIG event) and are about to implement better error reporting in the future (see https://github.com/serverless/serverless/issues/1818).

**Closed by pmuens** 2016-08-19 11:26 UTC
Labels: bug

**Comment by tengis** [comment] 2016-08-23 06:31
@pmuens Thanks for update. Looks like it's fine now. So which means it's time to go V1.0 👍 🎆 🎉
