### ISSUE TITLE
Serverless exists with 0-status on failure

### ISSUE THREAD

**Issue by jpic** [serverless/serverless#6486] opened 2019-08-01 20:07 UTC
serverless command should exit with non-zero status on failure to be useable in automated processes

```
$ serverless deployaoeu
echo $?
Unhandled rejection ServerlessError: Serverless command "deployaoeu" not found. Did you mean "deploy"? Run "serverless help" for a list of all available commands.
    at _.reduce (/usr/local/lib/node_modules/serverless/lib/classes/PluginManager.js:423:15)
    at arrayReduce (/usr/local/lib/node_modules/serverless/node_modules/lodash/lodash.js:683:21)
    at Function.reduce (/usr/local/lib/node_modules/serverless/node_modules/lodash/lodash.js:9681:14)
    at PluginManager.getCommand (/usr/local/lib/node_modules/serverless/lib/classes/PluginManager.js:385:14)
    at PluginManager.validateCommand (/usr/local/lib/node_modules/serverless/lib/classes/PluginManager.js:504:10)
    at Serverless.run (/usr/local/lib/node_modules/serverless/lib/Serverless.js:99:24)
    at serverless.init.then (/usr/local/lib/node_modules/serverless/bin/serverless.js:52:28)
    at tryCatcher (/usr/local/lib/node_modules/serverless/node_modules/bluebird/js/release/util.js:16:23)
    at Promise._settlePromiseFromHandler (/usr/local/lib/node_modules/serverless/node_modules/bluebird/js/release/promise.js:517:31)
    at Promise._settlePromise (/usr/local/lib/node_modules/serverless/node_modules/bluebird/js/release/promise.js:574:18)
    at Promise._settlePromise0 (/usr/local/lib/node_modules/serverless/node_modules/bluebird/js/release/promise.js:619:10)
    at Promise._settlePromises (/usr/local/lib/node_modules/serverless/node_modules/bluebird/js/release/promise.js:699:18)
    at Promise._fulfill (/usr/local/lib/node_modules/serverless/node_modules/bluebird/js/release/promise.js:643:18)
    at /usr/local/lib/node_modules/serverless/node_modules/bluebird/js/release/nodeback.js:42:21
    at /usr/local/lib/node_modules/serverless/node_modules/graceful-fs/graceful-fs.js:111:16
    at /usr/local/lib/node_modules/serverless/node_modules/graceful-fs/graceful-fs.js:45:10
    at FSReqWrap.oncomplete (fs.js:135:15)

$ echo $?
0
```

**Comment by azastrael** [comment] 2019-08-01 20:11
Duplicate of https://github.com/serverless/serverless/issues/6441

**Comment by pmuens** [comment] 2019-08-02 04:58
Thanks for opening @jpic :+1:

Yes, this seems to be a duplicate of #6441 as @azastrael pointed out so I'll close it for now.

**Closed by pmuens** 2019-08-02 04:58 UTC

**Comment by pmuens** [comment] 2019-08-02 04:59
BTW here's a PR which attempts to fix it --> https://github.com/serverless/serverless/pull/6450
