### ISSUE TITLE
v1.18 drops dependencies; v1.17 does not

### ISSUE THREAD

**Issue by GeoffThorpeFT** [serverless/serverless#3984] opened 2017-07-24 10:55 UTC
We include be-hogan-compile is our package.json.   It has a number of dependencies including minimatch.
A serverless deploy in v1.17 will auto include minimatch; v1,18 only included be-hogan-compile

**Comment by pmuens** [comment] 2017-07-24 14:04
Hey @GeoffThorpeFT thanks for opening this issue 👍

This seems to be a duplicate of https://github.com/serverless/serverless/issues/3972. The corresponding PR with a fix can be found here: https://github.com/serverless/serverless/pull/3975

**BTW:** You can opt-out of dev dependency exclusion with the following config: https://serverless.com/framework/docs/providers/aws/guide/packaging/#development-dependencies

Closing this for now since the discussion will happen in #3972 and #3975.

**Closed by pmuens** 2017-07-24 14:04 UTC
Labels: kind/bug
