### ISSUE TITLE
Support Function level Includes/Excludes

### ISSUE THREAD

**Issue by tpj800** [serverless/serverless#1986] opened 2016-08-31 04:20 UTC
# Question
Is it possible to specify `includes` and `excludes` on a function level in v1.0?

# Background
I have a number functions, each with an endpoint in a single API.  Some have very little shared code (`node_modules` or `site-packages` for python code) others have a lot. As in, enough to reach the limit for lambda zip packages.  I dont want to include the large functions in the package of the small ones.

Using serverless 0.5.x I could include various levels of shared code by using subdirectory reference like so:

```
handler: functions/maker/handler.handler,
```

Or, for small packages not requiring shared code:

```
handler: handler.handler,
```

I could also use `excludePatterns` in the `s-function.json` to trim down the  uploaded package for each function.

It may be a reasonable argument that such different functions should be in different *services* but suppose I want to deploy them together. Is this possible with the new version of serverless?

# Proposal

1. Have a root `serverless.yml` which remains the same spec as it currently is.
2. Allow function level `serverless.yml` (perhaps `function.yml`) files which may only contain:

```
package:
  include:
    -  dir1/
  exclude:
    - dir2/

functions:
  funct1:
    handler: handler.helloworld
    memorySize: 512
    ...
```

**Comment by flomotlik** [comment] 2016-08-31 13:06
This is currently getting implemented with #1917 , would be great to get your feedback there.

Closing here as it is a duplicate of #1777

**Comment by flomotlik** [comment] 2016-08-31 13:07
Main difference to your proposal is that it is all in the same file

**Closed by flomotlik** 2016-08-31 13:06 UTC

**Comment by tpj800** [comment] 2016-08-31 14:08
@flomotlik If i followed that thread correctly, you have a pull request from @johncmckim a week ago with these features?  Can I get a look at this pre-release on a current branch?

**Comment by flomotlik** [comment] 2016-08-31 15:22
You can see it in the fork of @johncmckim : https://github.com/johncmckim/serverless/tree/issue-1777

Or in the PR: https://github.com/serverless/serverless/pull/1917/files

Is that what you were looking for, or did you want to check out something else? At the bottom of the PR there are also the commands you can use to check out the PR code.
