### ISSUE TITLE
Serverless not working behind a corporate proxy unless Cloud provider is AWS

### ISSUE THREAD

**Issue by karanrk** [serverless/serverless#5815] opened 2019-02-08 22:36 UTC
# This is a Bug Report

## Description

* What went wrong?
Serverless works perfectly fine with AWS Lambda but it does not work with other Cloud providers such as IBM Openwhisk/ Google Cloud Functions etc.

* What did you expect should have happened?
Serverless framework must use the exported proxy settings to connect from within a corporate proxy firewall. Just like how it works fine for aws Lambda.

* What was the config you used?

I used the default hello world template to deploy and test the framework.

* What stacktrace or error message from your provider did you see?

Failed to deploy function (my-service-dev-hello) due to error: Unknown Error From API: socket hang up

Similar or dependent issues:
* #12345

## Additional Data

* ***Serverless Framework Version you're using***: 1.37.0
* ***Operating System***: Linux
* ***Stack Trace***:
ServerlessError: Failed to deploy function (my-service-dev-hello) due to error: Unknown Error From API: socket hang up
    at ow.actions.create.then.catch.err (/home/kkamatgi/bluemix/Bluemix_CLI/my-service/node_modules/serverless-openwhisk/deploy/lib/deployFunctions.js:18:15)
From previous event:
    at PluginManager.invoke (/home/kkamatgi/.nvm/versions/node/v10.15.1/lib/node_modules/serverless/lib/classes/PluginManager.js:400:22)
    at PluginManager.run (/home/kkamatgi/.nvm/versions/node/v10.15.1/lib/node_modules/serverless/lib/classes/PluginManager.js:431:17)
    at variables.populateService.then.then (/home/kkamatgi/.nvm/versions/node/v10.15.1/lib/node_modules/serverless/lib/Serverless.js:114:33)
    at runCallback (timers.js:705:18)
    at tryOnImmediate (timers.js:676:5)
    at processImmediate (timers.js:658:5)
    at process.topLevelDomainCallback (domain.js:120:23)
From previous event:
    at Serverless.run (/home/kkamatgi/.nvm/versions/node/v10.15.1/lib/node_modules/serverless/lib/Serverless.js:101:6)
    at serverless.init.then (/home/kkamatgi/.nvm/versions/node/v10.15.1/lib/node_modules/serverless/bin/serverless:43:28)
    at /home/kkamatgi/.nvm/versions/node/v10.15.1/lib/node_modules/serverless/node_modules/graceful-fs/graceful-fs.js:111:16
    at /home/kkamatgi/.nvm/versions/node/v10.15.1/lib/node_modules/serverless/node_modules/graceful-fs/graceful-fs.js:45:10
    at FSReqWrap.oncomplete (fs.js:141:20)
From previous event:
    at initializeErrorReporter.then (/home/kkamatgi/.nvm/versions/node/v10.15.1/lib/node_modules/serverless/bin/serverless:43:6)
    at runCallback (timers.js:705:18)
    at tryOnImmediate (timers.js:676:5)
    at processImmediate (timers.js:658:5)
    at process.topLevelDomainCallback (domain.js:120:23)
From previous event:
    at /home/kkamatgi/.nvm/versions/node/v10.15.1/lib/node_modules/serverless/bin/serverless:28:46
    at Object.<anonymous> (/home/kkamatgi/.nvm/versions/node/v10.15.1/lib/node_modules/serverless/bin/serverless:67:4)
    at Module._compile (internal/modules/cjs/loader.js:689:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:700:10)
    at Module.load (internal/modules/cjs/loader.js:599:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:538:12)
    at Function.Module._load (internal/modules/cjs/loader.js:530:3)
    at Function.Module.runMain (internal/modules/cjs/loader.js:742:12)
    at startup (internal/bootstrap/node.js:283:19)
    at bootstrapNodeJSCore (internal/bootstrap/node.js:743:3)

* ***Provider Error messages***: Need a configuration change to make the proxy available to other Cloud providers such as IBM,Azure,GCP which is doable just as it is working for AWS.

**Comment by pmuens** [comment] 2019-02-11 13:55
Hey @karanrk thanks for opening 👍

I'll close this issue for now since it's a duplicate of https://github.com/serverless/serverless/issues/3256, https://github.com/serverless/serverless/issues/3508 and https://github.com/serverless/serverless/issues/4841.

**Closed by pmuens** 2019-02-11 13:55 UTC

**Comment by dschep** [comment] 2019-02-11 20:07
@pmuens I don't think it's a duplicate of those issues, as this issue is about non-aws providers and all of those are aws providers. 

That said, I'm leaving the issue closed. @karanrk, please reopen this issue in the appropriate repositories: 
* https://github.com/serverless/serverless-google-cloudfunctions
* https://github.com/serverless/serverless-openwhisk
* others?
