### ISSUE TITLE
How do we npm install for Linux when working on a  Mac

### ISSUE THREAD

**Issue by grandmore** [serverless/serverless#510] opened 2016-01-22 20:18 UTC
I’m on a Mac and the build and deploy process for Lambda was previously done using this process (via grunt )

1) booting up a vagrant or docker linux image. 
2) copying source files to linux image. 
3) run ```npm install``` etc
4) compress everything into a tar.gz file.
5) upload the tar.gz to lambda

How do we achieve the same results with serverless?

Specifically installing node packages compiled for linux so that the packages are comparable with Lambda.

I could create a docker image and work within the image, but I wanted to see if this is on the roadmap as docker is complicated when I want to develop locally. 

Will there be integration with [lambda-packager](https://github.com/tomdale/lambda-packager) as a possible integrated solution?

**Comment by ac360** [comment] 2016-01-22 20:25
@grandmore We do need to offer more here.  We just haven't gotten to it yet.  Could you list out some ideas as to how you wish it would work?  We have the resources to build it asap, but we want to make sure we do this the right way.

**Comment by grandmore** [comment] 2016-01-22 20:41
Following the ‘resources' deploy you’ve already created, you could have an “npm deploy”

### Lambda-Packager
Using [lambda-packager](https://github.com/tomdale/lambda-packager) you could...

1) upload the package.js to lambda
2) lambda compiles everything
3) save it to the S3

The problem I can see with this approach is the 60 second lambda execution limit.

### Docker
A docker image could be used to compile everything.

1) run docker-compose up
2) copy files to docker image
3) run npm install
4) copy files back to host computer ready for upload.

Local development would work as usual using the standard npm package paths. However you would use the new Linux versions when uploading to Lamda

**Comment by madmod** [comment] 2016-01-22 22:42
@grandmore AWS Lambda recently had the limit [increased to 5 minutes](http://docs.aws.amazon.com/lambda/latest/dg/limits.html) so lambda-packager might be a good option. Another bonus of that would be using the parallelization of Lambda to speed up deployment of multiple functions at once.

**Comment by krzysu** [comment] 2016-01-26 10:09
I think this is related to https://github.com/serverless/serverless/issues/504

**Comment by justengland** [comment] 2016-01-27 04:33
I was thinking about working on this problem, and while my first idea was something similar lambda-packager, I started thinking with the new 5 minute increase could we make lambda a build server?

**Comment by flomotlik** [comment] 2016-05-11 12:40
We're currently working on V1 and as part of that I really want to have better documentation around using Docker for building those artifacts. I'm not sure if we're going to directly integrate with Docker in any way, but we want to make it easier for you to build artifacts (in different languages and with different technologies) and then for us to deploy them for you.

**Comment by flomotlik** [comment] 2016-05-11 12:42
I'll close this as its a duplicate of #308

**Closed by flomotlik** 2016-05-11 12:42 UTC

**Comment by justengland** [comment] 2016-05-11 14:01
The approach I have been taking lately takes advantage of some of the new lambda goodness. Basically, I use codepipeline to handle the npm install. Codepipeline allows you to trigger a lambda that can call npm and deploy the dependencies from with in a lambda environment. 

I assume the same could be done with python and PIP.
