### ISSUE TITLE
GraphQL causes serverless to crash during deployment

### ISSUE THREAD

**Issue by Slymodi** [serverless/serverless#3951] opened 2017-07-19 01:31 UTC
Could I disable publishing the deploy info to serverless?
```
Serverless: Publish service to Serverless Platform...
Serverless: Couldn't publish this deploy information to the Serverless Platform.

Error --------------------------------------------------

GraphQL error: Lambda services-publishService threw an Error during invokation

 For debugging logs, run again after setting the "SLS_DEBUG=*" environment variable.
Stack Trace --------------------------------------------

Error: GraphQL error: Lambda services-publishService threw an Error during invokation
at new ApolloError (/usr/local/lib/node_modules/serverless/node_modules/apollo-client/apollo.umd.js:2075:28)
at /usr/local/lib/node_modules/serverless/node_modules/apollo-client/apollo.umd.js:2798:33
at process._tickDomainCallback (internal/process/next_tick.js:129:7)
From previous event:
at fetchEndpoint.then.endpoint (/usr/local/lib/node_modules/serverless/lib/plugins/platform/platform.js:176:16)
From previous event:
at provider.getAccountId.then.accountId (/usr/local/lib/node_modules/serverless/lib/plugins/platform/platform.js:127:51)
From previous event:
at Platform.publishService (/usr/local/lib/node_modules/serverless/lib/plugins/platform/platform.js:126:41)
at BbPromise.reduce (/usr/local/lib/node_modules/serverless/lib/classes/PluginManager.js:217:55)
From previous event:
at PluginManager.invoke (/usr/local/lib/node_modules/serverless/lib/classes/PluginManager.js:217:22)
at PluginManager.run (/usr/local/lib/node_modules/serverless/lib/classes/PluginManager.js:236:17)
at variables.populateService.then (/usr/local/lib/node_modules/serverless/lib/Serverless.js:107:33)
at runCallback (timers.js:649:20)
at tryOnImmediate (timers.js:622:5)
at processImmediate [as _immediateCallback] (timers.js:594:5)
From previous event:
at Serverless.run (/usr/local/lib/node_modules/serverless/lib/Serverless.js:94:74)
at serverless.init.then (/usr/local/lib/node_modules/serverless/bin/serverless:32:50)

Your Environment Information -----------------------------
OS: darwin
Node Version: 7.2.1
Serverless Version: 1.17.0
```

**Comment by horike37** [comment] 2017-07-19 06:16
@Slymodi 
Maybe duplicate issue of #3946 
the fix PR has already opened up, so will solve this on the upcoming release.

**Comment by pmuens** [comment] 2017-07-19 08:54
Thanks for opening @Slymodi and thanks for jumping in @horike37 👍

@horike37 is right. It's a duplicate of #3946 so I'll close this issue for now.

You can mitigate this problem by running `serverless logout`. Additionally we're currently working on a flag to opt out of publishing. The corresponding PR can be found [here](#3950).

**Closed by pmuens** 2017-07-19 08:54 UTC
