### ISSUE TITLE
Console Error upgrading to 1.7.0

### ISSUE THREAD

**Issue by shavo007** [serverless/serverless#3261] opened 2017-02-16 11:52 UTC
# This is a (Bug Report)

## Description

For bug reports:
* What went wrong?
* What did you expect should have happened?
* What was the config you used?
* What stacktrace or error message from your provider did you see?

Ran npm install -g serverless
I was previously on version 1.6.1

Error:

```
> serverless@1.6.1 preuninstall /Users/shanelee/.nvm/versions/node/v4.3.0/lib/node_modules/serverless
> node ./scripts/preuninstall.js

module.js:328
    throw err;
    ^

Error: Cannot find module 'shelljs/global'
    at Function.Module._resolveFilename (module.js:326:15)
    at Function.Module._load (module.js:277:25)
    at Module.require (module.js:354:17)
    at require (internal/module.js:12:17)
    at Object.<anonymous> (/Users/shanelee/.nvm/versions/node/v4.3.0/lib/node_modules/serverless/lib/Serverless.js:3:1)
    at Module._compile (module.js:410:26)
    at Object.Module._extensions..js (module.js:417:10)
    at Module.load (module.js:344:32)
    at Function.Module._load (module.js:301:12)
    at Module.require (module.js:354:17)
npm WARN lifecycle serverless@1.6.1~preuninstall: continuing anyway serverless@1.6.1 preuninstall: `node ./scripts/preuninstall.js`
npm WARN lifecycle Exit status 1
```

Similar or dependent issues:
* 

## Additional Data

* ***Serverless Framework Version you're using***:1.6.1
* ***Operating System***: Mac OS
* ***Stack Trace***:
* ***Provider Error messages***:

**Comment by pmuens** [comment] 2017-02-16 12:01
Thanks for reporting @shavo007 👍 

Closing this one as it's a duplicate of / related to: #3251

**Closed by pmuens** 2017-02-16 12:01 UTC

**Comment by shavo007** [comment] 2017-02-16 12:06
No worries. Didnt see that other issue!
