### ISSUE TITLE
"Fallback/Overwrite" variable technique doesn't recurse into objects

### ISSUE THREAD

**Issue by dsole** [serverless/serverless#4509] opened 2017-12-01 00:32 UTC
# This is a Bug Report

## Description

When the serverless configuration is resolving a variable that is the overwrite/default value technique, when resolving any of the options that refer to an object, it does not resolve the variables within that object.

So given a configuration:
 ```
provider:
  name: aws
  stage: dev

custom:
  test: ${env:I_DONT_EXIST, self:custom.nested}
  nested:
    child: ${self:provider.stage}
```
In my plugin I expect `serverless.service.custom.test` to be
```
{
  child: "dev"
}
```
But what I get is 
```
{
  child: "${self:provider.stage}"
}
```

Similar or dependent issues:
 * #3604

## Additional Data

* ***Serverless Framework Version you're using***: 1.24.1
* ***Operating System***: Windows 10
* ***Stack Trace***: N/A
* ***Provider Error messages***: N/A

**Comment by dsole** [comment] 2017-12-01 00:52
in `Variables.populateProperty()` when it calls `this.getVariablesFromSource()` it follows it up with a check for whether the result is an object, and if so then it populates that object

**In `Variables.populateProperty()`**
```javascript
singleValueToPopulate = this.getValueFromSource(variableString)
  .then(valueToPopulate => {
    if (typeof valueToPopulate === 'object') {
      return this.populateObject(valueToPopulate);
    }
    return valueToPopulate;
  });
```

When it resolves the options within an overwrite syntax, it doesnt do that check.

**In `Variables.overwrite()`**
```javascript
const allValuesFromSource = variableStringsArray
      .map(variableString => this.getValueFromSource(variableString));
```

I could resolve this bug easily by just adding that same object-check code into the `Variables.overwrite()` function, but it feels like it should be put into getValueFromSource() so that we're not repeating it again in future. 

Any preference ?

**Comment by horike37** [comment] 2017-12-02 06:57
Hi @dsole, thanks you for reporting :smile: 
Is it possible to share your plugin code so that we will take a look into it?

I tried to run `sls print` with your configuration and see working fine.
```
$sls print
service: test
provider:
  name: aws
  stage: dev
custom:
  test:
    child: dev
  nested:
    child: dev
```

However, something might go wrong to write it up within a plugin :thinking:

**Comment by dsole** [comment] 2017-12-04 00:29
I've put a complete example in this Gist
https://gist.github.com/dsole/bb2f7ba74f8dace2113744f3828e367a

You'll need to copy the plugin script to a .serverless-plugins directory since Gist won't do directories.
```
mkdir .serverless-plugins
cp serverless-plugin-test.js .serverless_plugins/
```

My example plugin just has a hook function that writes the variable to the console and then kills the process to avoid actually deploying anything.
```javascript
  beforeDeployResources() {
    this.serverless.cli.log(this.serverless.service.custom.test.child);
    process.exit();
}
```

`sls print` seems to resolve the config correctly. However when I access the nested variable in a plugin it still has the variable placeholder syntax. 

**`$ sls print`**
```
service: test
provider:
  name: aws
  stage: dev
plugins:
  - serverless-plugin-test
custom:
  test:
    child: dev
  nested:
    child: dev
```

**`$ sls deploy`**
```
Serverless: ${self:provider.stage}
```

**Comment by HyperBrain** [comment] 2017-12-04 08:45
Hey @dsole . Thanks for the example. You're right, at that point all variables should be resolved properly, including the ones resolved by the default mechanism.
So this is definitely a bug, that default values are not resolved at all.

**Comment by HyperBrain** [comment] 2017-12-04 17:15
@dsole Can you please verify if the problem is solved with the PR?

**Comment by dsole** [comment] 2017-12-05 00:36
The `sls deploy` now works for me but `sls print` is throwing errors.
However, tracing back through the commits it occurs in master too.
I think its related to the changes being made in master by @e-e-e 
[See the recent 'cache' related commits in Variables.js](https://github.com/serverless/serverless/commits/populate-default-objects/lib/classes/Variables.js)

The stack trace refers to line 103 or Variables.js
```javascript
        singleValueToPopulate = singleValueToPopulate.then(valueToPopulate => {
```
The `singleValueToPopulate` variable contains just the string "dev" , not a promise.
I think that's because the cache is returning the literal value, not wrapped in a promise.

in `getValueFromSource(variableString)`, 
```javascript
    if (valueFromSource) {
      const resolver = BbPromise.resolve(valueFromSource)
      .then((result) => {
        this.cache[variableString] = result;
        return result;
      });
```
the value of 'result' being put into the cache is "dev". And that's never wrapped in a Promise before being returned.
```javascript
    const cached = this.cache[variableString];
    if (cached) {
      return cached;
    }
```

### Error
**`$ sls deploy`**
```

  Type Error ---------------------------------------------

  this.getValueFromSource(...).then is not a function

     For debugging logs, run again after setting the "SLS_DEBUG=*" environment variable.

  Stack Trace --------------------------------------------

TypeError: this.getValueFromSource(...).then is not a function
    at property.match.forEach (C:\Code\PTL-567\bb2f7ba74f8dace2113744f3828e367a\node_modules\serverless\lib\classes\Variables.js:101:14)
    at Array.forEach (native)
    at Variables.populateProperty (C:\Code\PTL-567\bb2f7ba74f8dace2113744f3828e367a\node_modules\serverless\lib\classes\Variables.js:91:43)
    at deepMapValues (C:\Code\PTL-567\bb2f7ba74f8dace2113744f3828e367a\node_modules\serverless\lib\classes\Variables.js:71:45)
    at deepMapValues (C:\Code\PTL-567\bb2f7ba74f8dace2113744f3828e367a\node_modules\serverless\lib\classes\Variables.js:66:14)
    at deepMapValuesIteratee (C:\Code\PTL-567\bb2f7ba74f8dace2113744f3828e367a\node_modules\serverless\lib\classes\Variables.js:56:25)
    at C:\Code\PTL-567\bb2f7ba74f8dace2113744f3828e367a\node_modules\lodash\lodash.js:13379:38
    at C:\Code\PTL-567\bb2f7ba74f8dace2113744f3828e367a\node_modules\lodash\lodash.js:4944:15
    at baseForOwn (C:\Code\PTL-567\bb2f7ba74f8dace2113744f3828e367a\node_modules\lodash\lodash.js:3001:24)
    at Function.mapValues (C:\Code\PTL-567\bb2f7ba74f8dace2113744f3828e367a\node_modules\lodash\lodash.js:13378:7)
    at deepMapValues (C:\Code\PTL-567\bb2f7ba74f8dace2113744f3828e367a\node_modules\serverless\lib\classes\Variables.js:64:39)
    at deepMapValuesIteratee (C:\Code\PTL-567\bb2f7ba74f8dace2113744f3828e367a\node_modules\serverless\lib\classes\Variables.js:56:25)
    at C:\Code\PTL-567\bb2f7ba74f8dace2113744f3828e367a\node_modules\lodash\lodash.js:13379:38
    at C:\Code\PTL-567\bb2f7ba74f8dace2113744f3828e367a\node_modules\lodash\lodash.js:4944:15
    at baseForOwn (C:\Code\PTL-567\bb2f7ba74f8dace2113744f3828e367a\node_modules\lodash\lodash.js:3001:24)
    at Function.mapValues (C:\Code\PTL-567\bb2f7ba74f8dace2113744f3828e367a\node_modules\lodash\lodash.js:13378:7)
    at deepMapValues (C:\Code\PTL-567\bb2f7ba74f8dace2113744f3828e367a\node_modules\serverless\lib\classes\Variables.js:64:39)
    at deepMapValuesIteratee (C:\Code\PTL-567\bb2f7ba74f8dace2113744f3828e367a\node_modules\serverless\lib\classes\Variables.js:56:25)
    at C:\Code\PTL-567\bb2f7ba74f8dace2113744f3828e367a\node_modules\lodash\lodash.js:13379:38
    at C:\Code\PTL-567\bb2f7ba74f8dace2113744f3828e367a\node_modules\lodash\lodash.js:4944:15
    at baseForOwn (C:\Code\PTL-567\bb2f7ba74f8dace2113744f3828e367a\node_modules\lodash\lodash.js:3001:24)
    at Function.mapValues (C:\Code\PTL-567\bb2f7ba74f8dace2113744f3828e367a\node_modules\lodash\lodash.js:13378:7)
    at deepMapValues (C:\Code\PTL-567\bb2f7ba74f8dace2113744f3828e367a\node_modules\serverless\lib\classes\Variables.js:64:39)
    at Variables.populateObject (C:\Code\PTL-567\bb2f7ba74f8dace2113744f3828e367a\node_modules\serverless\lib\classes\Variables.js:69:5)
    at getServerlessConfigFile.then.then (C:\Code\PTL-567\bb2f7ba74f8dace2113744f3828e367a\node_modules\serverless\lib\plugins\print\print.js:39:49)
From previous event:
    at Print.print (C:\Code\PTL-567\bb2f7ba74f8dace2113744f3828e367a\node_modules\serverless\lib\plugins\print\print.js:39:8)
From previous event:
    at Object.print:print [as hook] (C:\Code\PTL-567\bb2f7ba74f8dace2113744f3828e367a\node_modules\serverless\lib\plugins\print\print.js:21:10)
    at BbPromise.reduce (C:\Code\PTL-567\bb2f7ba74f8dace2113744f3828e367a\node_modules\serverless\lib\classes\PluginManager.js:366:55)
From previous event:
    at PluginManager.invoke (C:\Code\PTL-567\bb2f7ba74f8dace2113744f3828e367a\node_modules\serverless\lib\classes\PluginManager.js:366:22)
    at PluginManager.run (C:\Code\PTL-567\bb2f7ba74f8dace2113744f3828e367a\node_modules\serverless\lib\classes\PluginManager.js:397:17)
    at variables.populateService.then (C:\Code\PTL-567\bb2f7ba74f8dace2113744f3828e367a\node_modules\serverless\lib\Serverless.js:102:33)
    at runCallback (timers.js:672:20)
    at tryOnImmediate (timers.js:645:5)
    at processImmediate [as _immediateCallback] (timers.js:617:5)
From previous event:
    at Serverless.run (C:\Code\PTL-567\bb2f7ba74f8dace2113744f3828e367a\node_modules\serverless\lib\Serverless.js:89:74)
    at serverless.init.then (C:\Code\PTL-567\bb2f7ba74f8dace2113744f3828e367a\node_modules\serverless\bin\serverless:42:50)
```

**Comment by HyperBrain** [comment] 2017-12-05 00:42
@dsole Yes, you're absolutely right. It has to be 
```
this.cache[variableString] = BbPromise.resolve(result);
```
so that the cache contains a promise for the result.

I will add the fix to #4518 , so that it is in the proper PR

**Comment by e-e-e** [comment] 2017-12-05 00:44
@dsole my bad! Thanks for picking up. Apologies.

**Comment by HyperBrain** [comment] 2017-12-05 00:50
@dsole Can you check with the branch from #4518 if that works with the print command again?

**Comment by dsole** [comment] 2017-12-05 02:09
Thanks.  I checked and yes the `cache-AWS-requests` branch works now when I run the `sls print` command.

**Closed** 2017-12-06 23:10 UTC
Labels: kind/bug
