### ISSUE TITLE
"EMFILE - too many open file" error

### ISSUE THREAD

**Issue by mnapoli** [serverless/serverless#10944] opened 2022-04-07 15:27 UTC
Previous issue: #3249, #10706 

This is a meta-issue to gather all reports about the following error:

```
EMFILE - too many open files error
```

This is a very tough issue to solve because it happens randomly. It is caused by having too many files open _on the whole machine_ (not just the `serverless` process).

A possible root cause could be synchronous usage of the `fs` API. A solution might be to use `graceful-fs` and/or the async API to access the filesystem.

We use `graceful-fs` and reduced the use of sync calls in Serverless Framework to a minimum, but some plugins might not. We're trying to identify which plugins might cause the issue.

### Workarounds

This isn't ideal, but it is possible to increase the limit of files open on Linux and macOS with `ulimit` (https://stackoverflow.com/a/21070580/245552), but not on Windows.

If you have information about more workarounds, please post them here and we'll update the issue.

### How to help?

- Add a 👍  on this issue (so that we can estimate the impact)
- Investigate if some plugins might benefit from using `graceful-fs` and/or async filesystem calls
- Fill the following form and post it as a comment:

```
OS:
Serverless Framework version ('sls --version'):
Node version ('node --version'):
Plugins used:
```

Let's try and see if there's a pattern (e.g. a plugin that comes up often).

**Comment by jrfarrant** [comment] 2022-04-11 04:23
> I was able to resolve my issue by using the serverless-plugin-common-excludes and serverless-plugin-include-dependencies plugins

Using these plugins also resolved this issue for us. The issue was triggered in our case by migrating from node runtime 12.x to 14.x (CI/CD deployment).

**Comment by tobelesa** [comment] 2022-05-30 11:43
Hello, I got the EMFILE error when launching the serverless "deploy" script. I used graceful-fs like this to solve the issue : 
1. install graceful-fs: `npm install graceful-fs`
2. go to file: `node_modules/serverless/lib/plugins/package/lib/zip-service.js`
3. replace this line : `const fs = BbPromise.promisifyAll(require('fs'));`
by this: 
```
var realFs = require('fs')
var gracefulFs = require('graceful-fs')
gracefulFs.gracefulify(realFs)
const fs = BbPromise.promisifyAll(realFs);
```

**Comment by medikoo** [comment] 2022-05-31 09:35
@tobelesa this patch shouldn't have any real effect, as we ensure `fs` is patched globally before any modules are loaded: https://github.com/serverless/serverless/blob/ed111e021b286eb4a68f9b2fce7fb641e03340bd/scripts/serverless.js#L7-L9

**Comment by tobelesa** [comment] 2022-05-31 12:48
@medikoo ok, well it didn't work for me without the patch I explained there, so I don't know, maybe this fs import in zip-service.js was not "gracefulified" as you would expect.

I would still recommend to try this patch if one has the EMFILE error during zipping phase of deploy script.

**Comment by erandakarachchi** [comment] 2022-06-11 23:03
> serverless-plugin-include-dependencies

I was able to fix this issue by using only `serverless-plugin-include-dependencies`

### Environment 

```
Serverless 
Framework Core: 3.19.0 (local) 3.19.0 (global)
Plugin: 6.2.2
SDK: 4.3.2

Node
v16.15.1
```

**Comment by erandakarachchi** [comment] 2022-06-11 23:04
> Thank you for continuing to investigate this. After a bunch of digging, I was able to resolve my issue by using the `serverless-plugin-common-excludes` and `serverless-plugin-include-dependencies` plugins. This immediately resulted in a necessary not being included, but that issue appears to be specific to the `knex` ORM library and is probably unrelated to the issue within serverless. Ultimately, that was resolved by manually importing a sub-dependency in my own project.

Thanks for sharing this. I was able to fix this issue by using only `serverless-plugin-include-dependencies`

### Environment 

```
Serverless 
Framework Core: 3.19.0 (local) 3.19.0 (global)
Plugin: 6.2.2
SDK: 4.3.2

Node
v16.15.1
```

**Comment by deep-vaibhav** [comment] 2022-07-15 06:08
> Thank you for continuing to investigate this. After a bunch of digging, I was able to resolve my issue by using the `serverless-plugin-common-excludes` and `serverless-plugin-include-dependencies` plugins. This immediately resulted in a necessary not being included, but that issue appears to be specific to the `knex` ORM library and is probably unrelated to the issue within serverless. Ultimately, that was resolved by manually importing a sub-dependency in my own project.

@nunchukgun using these packages works as the deploy script doesn't throw an error and I get a endpoint generated.
But now when I access this endpoint I get this error `{ message: 'Internal server error' }`.
Probably because `node_modules` is excluded from our package?

Is there a workaround this?

**Comment by deep-vaibhav** [comment] 2022-07-15 06:12
> > Thank you for continuing to investigate this. After a bunch of digging, I was able to resolve my issue by using the `serverless-plugin-common-excludes` and `serverless-plugin-include-dependencies` plugins. This immediately resulted in a necessary not being included, but that issue appears to be specific to the `knex` ORM library and is probably unrelated to the issue within serverless. Ultimately, that was resolved by manually importing a sub-dependency in my own project.
> 
> Thanks for sharing this. I was able to fix this issue by using only `serverless-plugin-include-dependencies`
> 
> ### Environment
> ```
> Serverless 
> Framework Core: 3.19.0 (local) 3.19.0 (global)
> Plugin: 6.2.2
> SDK: 4.3.2
> 
> Node
> v16.15.1
> ```

@erandakarachchi were you deploying to AWS Lambda here? If yes, did your endpoint work?

**Comment by kcs-kajalvasar** [comment] 2022-08-02 06:52
> Thank you for continuing to investigate this. After a bunch of digging, I was able to resolve my issue by using the `serverless-plugin-common-excludes` and `serverless-plugin-include-dependencies` plugins. This immediately resulted in a necessary not being included, but that issue appears to be specific to the `knex` ORM library and is probably unrelated to the issue within serverless. Ultimately, that was resolved by manually importing a sub-dependency in my own project.

 I was able to fix this issue by using only serverless-plugin-include-dependencies but when I run getting` "{"message": "Internal server error"}"` can anyone help?
 
 Thanks in advance!

**Comment by samskiter** [comment] 2022-08-02 10:30
Seeing this issue with python

**Comment by samskiter** [comment] 2022-08-02 11:07
also fixed with serverless-plugin-common-excludes and serverless-plugin-include-dependencies but I am planning to deploy a lot more with my lambda soon, so hoping there is a fix for this in the works?

**Comment by ccornici** [comment] 2022-08-03 17:24
I'm getting this error 3 out of 4 deploys

**Comment by mnapoli** [comment] 2022-08-04 09:51
@ccornici thanks for following the template for reporting. I note that you are still on v2: you might want to upgrade to v3 as v2 is no longer supported.

To anyone who wants to contribute to this issue, please follow the formatting/guidance written in the top comment.

**Comment by dylmye** [comment] 2022-08-16 22:23
Hey, just found this ticket after getting this error, fixes by quickly running it after restarting Windows lol. 

OS: Win 10 19043.1889
Serverless Framework version ('severless --version'):
Framework Core: 3.10.0 (local) 3.10.0 (global)
Plugin: 6.2.0
SDK: 4.3.2

Node version ('node --version') :v14.17.3
Plugins used:

* serverless-python-requirements@5.4.0

**Comment by deep-vaibhav** [comment] 2022-08-17 10:17
> > Thank you for continuing to investigate this. After a bunch of digging, I was able to resolve my issue by using the `serverless-plugin-common-excludes` and `serverless-plugin-include-dependencies` plugins. This immediately resulted in a necessary not being included, but that issue appears to be specific to the `knex` ORM library and is probably unrelated to the issue within serverless. Ultimately, that was resolved by manually importing a sub-dependency in my own project.
> 
> I was able to fix this issue by using only serverless-plugin-include-dependencies but when I run getting` "{"message": "Internal server error"}"` can anyone help?
> 
> facing this issue in Nestjs.
> 
> Thanks in advance!

What you're trying to do is not possible with Lambda. I believe you're trying to deploy your entire NestJS application to a single Lambda function. Let me tell you that there's a size limit on Lambda. A single Lambda function can NOT be more than 250MB. So, when you use `serverless-plugin-common-excludes` and `serverless-plugin-include-dependencies` it's basically excluding `node_modules` from the package thus allowing it to get to Lambda successfully.

What you might have to do is create a Lambda Layer which includes `node_modules` so that your Lambda can use it. Even that has a size limit I guess ( you can also try it via S3 ). If none of these work, you might have to create an image and push it to AWS ECR and deploy your image to Lambda. However, this has it's pros and cons.

In general, it is not advised and not ideal to deploy an entire application to Lambda. It's meant for microservices only. A Lambda can run only upto 15 minutes max, which I think you wouldn't want for your application in any case. I would suggest look into different alternatives for serverless like SAM.

**Comment by jsnavarroc** [comment] 2022-08-18 13:54
I don't know why NestJS doesn't create a single file like Webpack does when making the build file; it's demanded the dependencies directly from the node_modules folder.
There for, of course, node_module can weigh a lot!!!.
The solution I found was to implement the "serverless-plugin-typescript" plugin, which somehow makes the zip much smaller, almost reducing the weight by 50%. The fix that needs to be made is that when the project is built, the node_module files should be compressed enough not to cause this issue.

**Comment by KalanaPerera** [comment] 2022-09-17 04:17
experiencing same error: solution was https://forum.serverless.com/t/emfile-too-many-open-files-error-while-ci-cd-deploy/14245/11

**Comment by serg06** [comment] 2022-10-23 19:26
If you're running in Git Bash, the fix is to increase your file limit:

```
ulimit -n 3200  # increase file limit from 256 -> 3200
```

**Comment by serg06** [comment] 2022-10-23 19:45
I was able to solve this after hours of debugging. I don't know what fixed it, but here's what I did:

- Upgraded Node to `16.18.0`
- Uninstalled all packages
- Deleted `node_modules` and `yarn.lock`
- Reinstalled the latest version of all of them
- Opened up `node_modules/serverless/bin/serverless.js`, and right after `use strict;`, added `require('graceful-fs').gracefulify(require('fs'));`
- Ran my serverless commands in CMD instead of Git Bash

**Comment by swapnilwagh2204** [comment] 2022-10-24 03:12
if you are using python virtual environment and getting this issue
I added a virtual env folder into the package: patterns in serverless.yaml
It resolved my issue and working fine.

package:
  patterns:
    - "!exclude-me.py"
    - "!exclude-me-dir/**"
    - include-me.py
    - include-me-dir/**
    - node_modules/**
    - sls_venv/**

**Comment by serg06** [comment] 2022-10-30 05:37
Update: I got to the root of the issue. Here's the full fix for NodeJS:

1. Run `yarn add -D graceful-fs@4.2.6`.
2. Open up `node_modules/serverless/bin/serverless.js` and add this right after `use strict;`:

```js
require('../../graceful-fs/graceful-fs').gracefulify(require('fs'));
```

**Comment by enchorb** [comment] 2022-11-29 15:31
The above suggestion worked great, posted a patch file below (patch-package) 

```
diff --git a/node_modules/serverless/bin/serverless.js b/node_modules/serverless/bin/serverless.js
index b3f91c3..00cff20 100644
--- a/node_modules/serverless/bin/serverless.js
+++ b/node_modules/serverless/bin/serverless.js
@@ -5,6 +5,7 @@
 // (as constructed below) instead of the syntax error
 
 'use strict';
+require('../../graceful-fs/graceful-fs').gracefulify(require('fs'));
 
 // `EvalError` is used to not pollute global namespace but still have the value accessible globally
 // Can already be set, if we're in context of local fallback
```

**Comment by shierro** [comment] 2023-01-24 00:20
> Hello, I got the EMFILE error when launching the serverless "deploy" script. I used graceful-fs like this to solve the issue :
> 
> 1. install graceful-fs: `npm install graceful-fs`
> 2. go to file: `node_modules/serverless/lib/plugins/package/lib/zip-service.js`
> 3. replace this line : `const fs = BbPromise.promisifyAll(require('fs'));`
>    by this:
> 
> ```
> var realFs = require('fs')
> var gracefulFs = require('graceful-fs')
> gracefulFs.gracefulify(realFs)
> const fs = BbPromise.promisifyAll(realFs);
> ```

this one worked on a windows 11 machine, thank you!

serverless version: 3.25.0
nodejs: 18.12.1

**Comment by twistypigeon** [comment] 2023-02-02 11:21
OS: Windows 10 22H2 (19045.2486)
Serverless Framework version ('sls --version'): 
Framework Core: 3.26.0 (local) 3.3.0 (global)
Plugin: 6.2.2
SDK: 4.3.2
Node version ('node --version'): v18.13.0

Fresh boot of PC. EMFILE too many files error
Added workaround as suggested by @tobelesa and deployed. Worked.

**Comment by cfellin1-godaddy** [comment] 2023-02-06 23:09
OS: MacOS Big Sur
Serverless Framework version ('sls --version'): 2.72.2
Node version ('node --version'): v16.15.0

Used workaround from @tobelesa, and it fixed the problem!

**Comment by SCMG7** [comment] 2023-02-13 23:30
Nothing from the above solutions worked for me, I have run out of ideas, have no clue what to do else and how to resolve the issue :(

**Comment by jiro2017** [comment] 2023-03-30 19:14
I case you are having this problem on a windows machine when developing locally, I recommend that you delete the whole project (if you haven't gone far on it) and start all over again. Also remember to close the command prompt window and all applications that are running on your project before deleting it and start again.

**Comment by duanyuluo** [comment] 2023-05-12 12:40
❯ ulimit -a
-t: cpu time (seconds)              unlimited
-f: file size (blocks)              unlimited
-d: data seg size (kbytes)          unlimited
-s: stack size (kbytes)             8176
-c: core file size (blocks)         0
-v: address space (kbytes)          unlimited
-l: locked-in-memory size (kbytes)  unlimited
-u: processes                       1333
-n: file descriptors                256

the last line is so small, is that OK?

**Comment by MarioUnlam** [comment] 2023-05-18 14:38
I was also having this problem when trying to do "serverless deploy" with a NestJS project which also had a python virtual environment. I'm uploading it to AWS Lambda using a docker image and ECR. None of the workarounds posted here worked for me.

Patching serverless with graceful-fs gave me the same error indravijay-bot described.

Installing serverless-plugin-include-dependencies made the command crash instantly with the following error: `Cannot read properties of undefined (reading 'lastIndexOf')`

What worked for me was removing "serverless-jetpack" from my plugins list. This supposedly makes the uncompressed package smaller to avoid reaching the 250mb limit of AWS Lambda, but this wasn't necessary in my case because I'm using a docker image.

**Comment by domsew** [comment] 2023-05-22 16:06
Hello, I can also confirm the issue is real. Futhermore I confirm that the [above workaround](https://github.com/serverless/serverless/issues/10944#issuecomment-1141054993) is working. The problem occurs in medium sized NestJS application with 40 npm dependencies. For small projects problem does not occur. I did the tests on Windows 10 and Ubuntu 22 (WSL 2). The problem remains on both platforms.

`sls --version`:
Framework Core: 3.31.0 (local)
Plugin: 6.2.3
SDK: 4.3.2
`node -v`:
v18.16.0
`Plugins used`:
  serverless-offline
  serverless-dotenv-plugin
  serverless-ignore

**Comment by SandroZaninello** [comment] 2023-05-29 17:14
Hello everyone,
I have installed serverless globally (not local).

Tried to add the two sls plugins: `serverless-plugin-common-excludes` and `serverless-plugin-include-dependencies` , the deploy went OK but the API returns 502  `"{"message": "Internal server error"}"` saying missing some dependencies.

Then tried to follow the @tobelesa suggestion. Edit the zip-services.js adding the three lines with graceful-fs.
I still having errors, I got the following error:
![image](https://github.com/serverless/serverless/assets/74965414/ca5a031f-a444-4f46-84b1-57ba689d2277)

`sls -v:`
Framework Core: 3.31.0
Plugin: 6.2.3
SDK: 4.3.2

`node -v:`
19.8.1

Wich SLS v2 everything worked well. Right now, I need to deploy function x function with:
`sls deploy -s dev -f myFunction`

Anyone have update to solve this issue? or Any suggestions?
Thanks

**Comment by jbblanton** [comment] 2023-08-09 16:32
One of the few Python situations, it seems.

OS: 
WSL - Ubuntu 20.04 on Windows 10 Home machine

Serverless Framework version ('severless --version'):
Framework Core: 3.34.0
Plugin: 6.2.3
SDK: 4.3.2

Node version ('node --version') :
v14.15.5

Plugins used:
serverless-python-requirements
serverless-aim-roles-per-function
serverless-prune-versions

Based on reading this, I also added serverless-plugin-common-excludes and serverless-plugin-include-dependencies


I have tried:
- installing graceful-fs and attempting to edit the zip-service.js file, but it doesn't exist
- following all 3 options detailed in the above-mentioned SO link, with no change.  My `$ ulimit -n` still returns 1024.
- adding, and then removing, the serverless-webpack.  I just got an error for not finding webpack module
- adding the 2 additional plugins mentioned above
- working with the virtual env active and not active
- restarting my PC entirely

This isn't my typical work machine, but it is one where I have successfully deployed serverless applications many, many times.  I'm working here, because my work machine isn't using the python-requirements plugin, and all my files are being zipped inside each other, making them huge.

**Comment by neverendingqs** [comment] 2023-09-22 16:07
Encountered this issue and did some debugging, but couldn't get to the bottom of this. Leaving notes to see if maybe someone else can build upon them.

```
Framework Core: 3.35.2 (local)
Plugin: 7.0.2
SDK: 4.4.0
Node.js: v18.15.0
```
https://github.com/serverless/serverless/issues/10944#issuecomment-1141904105 is still true: https://github.com/serverless/serverless/blob/8f266af8308fa9b89327792dd037c4fe14bb14af/scripts/serverless.js#L7-L9

This workaround works for me: https://github.com/serverless/serverless/issues/10944#issuecomment-1288185586

(added to https://github.com/serverless/serverless/blob/8f266af8308fa9b89327792dd037c4fe14bb14af/bin/serverless.js#L7-L8).

If the following imports run first, it's unclear if a subsequent `gracefulify()` call will affect these imports because they've already been loaded elsewhere:
* `require('fs').promises;`
* `require('util').promisify(require('fs').copyFile);`
* `BbPromise.promisifyAll(require('fs'));`

This hunch is interesting because zip service uses the BB promisify version: https://github.com/serverless/serverless/blob/8f266af8308fa9b89327792dd037c4fe14bb14af/lib/plugins/package/lib/zip-service.js#L8

My current theory (that I can't prove) is that the issue might be some blend of the following:
* Somewhere in https://github.com/serverless/serverless/blob/8f266af8308fa9b89327792dd037c4fe14bb14af/bin/serverless.js#L1-L70, we trigger a non-`gracefulify`ed import of `fs` that doesn't get `gracefulify`ed later
* `BbPromise.promisifyAll()` caches so it doesn't promisify over and over again, but that causes it to use cache a non-`gracefulify`ed version
* `zip-service.js` gets loaded before we reach https://github.com/serverless/serverless/blob/8f266af8308fa9b89327792dd037c4fe14bb14af/scripts/serverless.js#L7-L9

**Comment by dantjackson** [comment] 2023-10-03 10:34
Tried various solutions to fix this issue from the suggestions above.  Our issue appears to be resolved by removing 
package 
  individually: true

**Comment by iwaduarte** [comment] 2023-10-03 22:28
In relation to the Node.js case, I think it is related to the node_modules (Node.js) dependency file size.

I am not using plugins.

In my case, it occurs when I am trying to set the node_modules  as a layer and I am using the package individually set true and the node_modules is massive (200MB or more I have experienced this).


```
package:
  individually: true
layers:
  nodeModules:
    path: node_modules
    description: Node.js modules for my service

```

Also, the bug is **not** **random**. I can reproduce every time that I have that set.

OS: Windows
Serverless Framework version ('sls --version'):
Node version: Node18:
Plugins used: None


@mnapoli Does that help?

**Comment by slootjes** [comment] 2023-10-09 15:12
I've been using serverless framework a lot with esbuild and never had these issues until a few weeks ago where it's randomly breaking with the "EMFILE - too many open file" error. I'm on Windows 11 and calling serverless framework from Powershell.

**Comment by davidgonghs** [comment] 2023-11-06 15:02
Environment: win32, node 16.14.1, framework 3.36.0 (local) 3.36.0v (global), plugin 7.1.0, SDK 4.4.0
Credentials: Local, "default" profile                                                                                                                                                                                                                
Docs:        docs.serverless.com
Support:     forum.serverless.com
Bugs:        github.com/serverless/serverless/issues
Error:
Error: EMFILE: too many open files, open 


I am not sure what happen for this issues, I try a lot time, only one time can push to lambda, other will show this error

**Comment by pgeimer** [comment] 2023-11-28 10:41
OS: Windows 11
Environment: win32, node 16.16.0, framework 3.35.2, plugin 7.0.5, SDK 4.4.0
Plugins used:    
    - serverless-domain-manager
    - serverless-prune-plugin
    - serverless-sentry

I also noticed that the problem occurred after I upgraded `aws-sdk` from v2 to v3 and there were still some `aws-sdk` v2 in the `node_modules`, which made them over 200 MB in size.

Deleting and reinstalling `node_modules` sometimes helps.

Sometimes the error disappears if you simply deploy a second time immediately afterwards.

**Comment by davidgonghs** [comment] 2023-11-29 01:07
for now, I found a way,  we can use aws lambda to create a layer just run our environment , then create a other layer just push our code, that will be easy to do it.

**Comment by mojoalan** [comment] 2023-12-14 15:20
> Hello, I got the EMFILE error when launching the serverless "deploy" script. I used graceful-fs like this to solve the issue :
> 
> 1. install graceful-fs: `npm install graceful-fs`
> 2. go to file: `node_modules/serverless/lib/plugins/package/lib/zip-service.js`
> 3. replace this line : `const fs = BbPromise.promisifyAll(require('fs'));`
>    by this:
> 
> ```
> var realFs = require('fs')
> var gracefulFs = require('graceful-fs')
> gracefulFs.gracefulify(realFs)
> const fs = BbPromise.promisifyAll(realFs);
> ```

FWIW, I had already done this in the past and the issue came back. I took a fresh look at my zip-service.js file and it was back to original version. Re-implemented this code change and now my deploys work properly again. So, if you have already implemented graceful-fs, double check this!

**Comment by trungyoong2** [comment] 2024-01-05 02:18
I have tried all of the suggestions above but still encountered errors. I used ECR to deploy and the issue was resolved. Here is my workaround [serverless.yml](https://hackernoon.com/serverless-nestjs-automation-on-aws-lambda)

**Comment by jzhao62** [comment] 2024-01-06 19:03
- making modification inside node_modules is not good, and is only a temporary solution
- will it be addressed in the next version or currently this is the only solution ?

**Comment by slootjes** [comment] 2024-01-10 15:16
If anyone experiences this while using the esbuild plugin, try setting a concurrency. By adding `concurrency: 5` to my config I got rid of this error completely and it's just as fast as before.

**Comment by majicmarlo** [comment] 2024-01-17 11:34
My Solution: Set package.individually to False in Serverless Lambda Deployments

We resolved a critical issue in our Lambda deployment related to an excessive number of file operations. This issue arose from having the package individually configuration set to true in our serverless setup.

Problem:
With package individually enabled, each Lambda function was packaged with its separate dependencies. In a project with numerous Node dependencies, this configuration significantly increased the number of file operations, as each dependency was processed separately for every function.

Observation:
The problem was not immediately evident as it didn't result in high CPU or RAM usage, metrics typically monitored in CircleCI. The key factor here was the number of file operations, which isn't directly reported by CircleCI.

Conclusion:
Changing the package individually setting to false drastically reduced the number of file operations. This change meant dependencies were shared across functions, thus reducing the overall file operations and resource consumption during deployment. If this doesn't work for you, investigate thoroughly to isolate what exactly is causing the large number of file operations.

**Comment by casewalker** [comment] 2024-02-02 18:10
OS: MacOS 14.2
Serverless Framework version ('sls --version'): Framework Core: 3.38.0 (local) 3.31.0 (global), Plugin: 7.2.0, SDK: 4.5.1
Node version ('node --version'): v18.12.1
Plugins used: serverless-plugin-typescript v2.1.5

From ulimit -a, I see I only have 256 file descriptors, seems like maybe I could bump that up.

**Comment by benockert** [comment] 2024-03-09 08:55
I had the same issue. I was able to resolve it and significantly improve packaging speeds by moving plugin packages such as `serverless-domain-manager` to the `devDependencies` section of my `package.json`. Serverless excludes dev dependencies by default unless `package.excludeDevDependencies` is set to false.

**Comment by kayleejacob1** [comment] 2024-03-14 21:10
OS: Windows 11
Serverless Framework version ('sls --version'): 3.38 i was using 2.56 got issue but does not seem to matter what version i have 
Node version ('node --version'): 21.71
Plugins used:  
 - serverless-prune-plugin
  - serverless-plugin-split-stacks
  - serverless-plugin-custom-roles


i tried fix below and got 
Error:
RangeError: Maximum call stack size exceeded

Hello, I got the EMFILE error when launching the serverless "deploy" script. I used graceful-fs like this to solve the issue :

install graceful-fs: npm install graceful-fs
go to file: node_modules/serverless/lib/plugins/package/lib/zip-service.js
replace this line : const fs = BbPromise.promisifyAll(require('fs'));
by this:
var realFs = require('fs')
var gracefulFs = require('graceful-fs')
gracefulFs.gracefulify(realFs)
const fs = BbPromise.promisifyAll(realFs);


package json
 "dependencies": {
    "-": "^0.0.1",
    "@aws-sdk/client-iot": "^3.501.0",
    "authorizenet": "^1.0.8",
    "aws": "0.0.3-2",
    "fs": "^0.0.1-security",
    "graceful": "^1.1.0",
    "graceful-fs": "^4.2.11",
    "mysql": "^2.18.1",
    "mysql2": "^2.3.3",
    "nodemailer": "^6.6.3",
    "nodemailer-ses-transport": "^1.5.1",
    "npm": "^9.6.7",
    "promise": "^8.1.0",
    "sequelize": "^6.35.2",
    "serverless": "^3.38.0",
    "serverless-plugin-custom-roles": "^2.0.1",
    "serverless-plugin-include-dependencies": "^6.0.0",
    "serverless-plugin-split-stacks": "^1.11.2",
    "serverless-prune-plugin": "^1.5.1",
    "togo": "^1.0.0"
  }


i excluded modules and it does work. but  i am missing my references so just giving this for info but did nothing 

serverless.yml

package:
 # excludeDevDependencies: true
  individually: false
  #exclude:
    - node_modules/**


i have tried out side of vs code same fault

I have restarted PC no result
i have uninstall npm ,node , and start fresh with latest download and install no luck
reinstalled serverless global and local

I have been unable to find fix

**Comment by ferrerjoel** [comment] 2024-05-11 13:51
Modifying the serverless folder, adding graceful-fs resulted in more errors later when deploying.

In my case, it was fixed by making sure I was using serverless installed globally and not in the node_modules folder of my project.

Remove serverless from the project and run `npm i serverless -g`.

**Comment by ledung76d** [comment] 2024-06-14 09:19
In my case, just run` rmdir .serverless` and run `serverless deploy` again.

**Comment by Rumirad64** [comment] 2024-08-01 17:33
Windows 10, Node v18, Serverless 3
A simple pc restart helped me

**Comment by Shivani-S-Patil** [comment] 2024-08-06 10:58
When I downgraded node version from Node 14.21.3 to 12.16.2, it worked for me.

**Comment by skierkowski** [comment] 2024-08-13 17:56
This was fixed and released in 4.1.12.

**Closed by skierkowski** 2024-08-13 17:56 UTC
Labels: bug

**Comment by neverendingqs** [comment] 2024-08-13 19:54
Double-check: was https://github.com/serverless/serverless/pull/12669 the fix?

**Comment by skierkowski** [comment] 2024-08-14 03:18
@neverendingqs Yes, I believe so. @Mmarzex can you verify?

**Comment by masucode** [comment] 2024-09-20 19:19
We solved this issue with
 
```
rm -rf node_modules
rm package-lock.json
npm cache clean --force
npm install

watchman watch-del-all
rm -rf /tmp/metro-*
```

i hope it will work in your machine 
thanks to my team friend @TuranBurakk 🔥
