### ISSUE TITLE
An error occurred: ApiGatewayLogGroup

### ISSUE THREAD

**Issue by TrierHealth** [serverless/serverless#8841] opened 2021-01-27 10:40 UTC
Hi,

For the past 2 days our deployments are failing with the below reason. Earlier it was absolutely fine.

An error occurred: ApiGatewayLogGroup - Resource of type 'AWS::Logs::LogGroup' with identifier '{"/properties/LogGroupName":"/aws/api-gateway/ourloggroupname"}' already exists.

Thanks,.
Ravi.

**Comment by pgrzesik** [comment] 2021-01-27 12:10
Hello @TrierHealth, sorry to hear that - could you provide a bit more details about the issue? What Framework version are you currently using?

**Comment by TrierHealth** [comment] 2021-02-01 15:23
Hi,

We are using 1.83.0. The same version has been working fine. But the issue started recently when I posted it here. Earlier api gateway loggroup wasn't enabled from serverless.yml, but later added. could that be causing something? Also, for a couple of apis we are able to run the severless yml after deleting the api gateway log group manually. But that is not working always.

Thanks,
Ravi V.

**Comment by pgrzesik** [comment] 2021-02-01 16:23
Thanks for providing more information @TrierHealth - do you have an option to upgrade to latest version of Serverless Framework (we're now on `2.21.1`) and see if the problem persists? Are you using any plugins related to `apiGateway` that might be interfering with configuration?

**Comment by TrierHealth** [comment] 2021-02-02 06:04
Hi,
I can try with 2.21.1 and let you know.
The below are the plugins we are using:
```
plugins:
  - serverless-offline
  - serverless-ignore
  - serverless-domain-manager
```
The provider config is as below

```
provider:
  name: aws
  runtime: nodejs12.x
  memorySize: 128 # optional, in MB, default is 1024
  timeout: 6 # optional, in seconds, default is 6
  versionFunctions: false # optional, default is true
  tracing:
    lambda: true # optional, enables tracing for all functions (can be true (true equals 'Active') 'Active' or 'PassThrough')
    apiGateway: true
  apiGateway:
    metrics: true
  logs:
    restApi: true
```

**Comment by TrierHealth** [comment] 2021-02-02 07:43
I tried with 2.21.1, same error: 
2021-02-02T07:30:07.4241035Z   An error occurred: ApiGatewayLogGroup - Resource of type 'AWS::Logs::LogGroup' with identifier '{"/properties/LogGroupName":"/aws/api-gateway/xxxx-service-dev"}' already exists..

**Comment by pgrzesik** [comment] 2021-02-02 09:45
Thanks for reporting back @TrierHealth - you mentioned that in some cases, you had to remove the log group manually - do you happen to know how that was created? Was it a part of a CloudFormation stack that was cleaned up incorrectly by any chance (deleted but some resources were retained, including the `LogGroup` resource? Does it surface only for existing services? I've tried to replicate your issue locally with simple example, but I didn't manage to reproduce it yet.

**Comment by TrierHealth** [comment] 2021-02-04 02:11
Hi, For newer services we haven't yet faced any issue. All our services were created using serverless yml. Regarding the incorrect deletion from cloud formation, may be when serverless yml was checking and pushing new code there was an issue. Till now we faced this issue in 3 different services.

**Comment by TrierHealth** [comment] 2021-02-04 02:18
Here is the response from AWS support on this: From investigation of the CloudFormation stacks events, and the corresponding CloudTrail logs, this issue appears to be caused due to the API Gateway re-creating the log group when it is deleted from the CloudFormation stack. As the resource is being created by the API Gateway, when the CloudFormation stack is updated and calls the CreateLogGroup API, the "Resource already exists" error is thrown.
The CloudFormation stack events show that the log group was first deleted on 2021-01-20T06:51:46.904Z. Following this deletion, the first CREATE_FAILED event occurred on 2021-01-28T10:56:35.743Z. This create failed occurred as, immediately following the deletion of the log group, it was recreated by the API Gateway. 


As a possible workaround for this issue, the IAM role used by the API Gateway, "arn:aws:iam::XXXXXXXXXX:role/serverlessApiGatewayCloudWatchRole", could be removed when the Log Group is being deleted, or could be modified in order to remove it's ability to recreate the log group, by removing the "logs:CreateLogGroup" permissions.

**Comment by TrierHealth** [comment] 2021-02-04 07:49
I think if there is an option in serverless.yml that creates LogGroup only when if it is not present, it would be good.

**Comment by pgrzesik** [comment] 2021-02-04 12:52
Hello again :wave: Thanks for being patient and for supporting us with detailed response from AWS support. I've did some extra digging and I've managed to reproduce the exact issue you're having (I believe). Unfortunately, it's a little bit more complicated. The problem is caused by the fact that when `logs.restApi: true` setting is removed, the `LogGroup` resource from `CloudFormation` is getting removed, but the API Gateway stage still has logs turned on (stage is updated via SDK call only if `logs.restApi` setting is present), which results in log group being automatically created during first API call. As for the suggestion to create `LogGroup` only if it's not present - that's going to be hard, because in this case, the automatically recreated group is not a part of CloudFormation stack.

There's an existing issue that's tracking the same bug I believe, I have an idea for a fix that I will post in the corresponding issue: https://github.com/serverless/serverless/issues/6906

**Comment by TrierHealth** [comment] 2021-02-28 13:54
Hi, any newer findings on this ? If this is exactly same as the other issue you mentioned, yes, this can be closed marking it duplicate.

**Comment by pgrzesik** [comment] 2021-03-02 12:30
Hello @TrierHealth :wave: Unfortunatelly, it seems like at the moment the only option is to use the workaround that I've linked to from other issue. Also as mentioned in the discussion in linked issue, it is unforntuatelly tricky to resolve and we will need an additional locking mechanism in order to do it properly - until we have that, this issue is going to be blocked. 

As mentioned, this is a duplicate of the same issue, I'm going to close this one. Please let me know if the workaround was helpful in your case.

**Closed by pgrzesik** 2021-03-02 12:30 UTC
Labels: bug, cat/aws-event-api-gateway
