### ISSUE TITLE
Recursive directories in function deploy build without sub-folder

### ISSUE THREAD

**Issue by cdichiara** [serverless/serverless#967] opened 2016-04-07 13:59 UTC
Hi,

Just a heads up ... I got a nasty problem that cropped up in my function deploy.

I moved our functions all into one function, in an attempt to mitigate the impact of cold container performance. I also got rid of the container from pre v0.5.0, so the function is hanging right below the parent directory. Previously the libraries for the ```clientAPI``` container were in ```/clientAPI/node_modules```, and ```serverless-optimizer-plugin``` was in ```/node_modules/``` ... the former were in ```/clientAPI/package.json```, and the latter was in ```/package.json```. I was deploying just fine back then. After I created the new package and moved the code, I moved all of the libraries into ```/node_modules/``` as there was only one ```/package.json``` left.

Well, I tried a build ... and it's been pretty horrific. I've spent about 60 minutes gettting rid of recursive directory structures that have hosed my FS & OS, looking like this:
```
/_meta/_tmp/clientAPI@143093909134/_meta/_tmp/clientAPI@143093909134/_meta/_tmp/...
```

I have little idea what caused this, because honestly I'm having difficulty cleaning up after this event. I'm thinking it has something to do with the combination of the serverless-optimizer-plugin in the same folder as the plugins specific to the lambda code? Has anyone else had this problem? I'm a little hesitant to even look for the root cause of this problem without some computer with a separate drive I can just quickformat after ```sls function deploy clientAPI``` just takes down the FS.

**Comment by cdichiara** [comment] 2016-04-07 14:31
Here's a quick glimpse of the output of ```robocopy``` as I attempt to delete these too-long files:

```
        *EXTRA Dir        -1    C:\_tmp\1\_meta\_tmp\1\_meta\_tmp\1\_meta\_tmp\1\_meta\_tmp\1\_meta\_tmp\1\_meta\_tmp\1\_meta\_tmp\1\_meta\_tmp\1\_meta\_tmp\1\_meta\_tmp\1\_meta\_tmp\clientApi@1460028544568\_meta\_tmp\clientApi@1460028544568\_meta\_tmp\clientApi@1460028544568\_meta\_tmp\clientApi@1460028544568\_meta\_tmp\clientApi@1460028544568\_meta\_tmp\clientApi@1460028544568\_meta\_tmp\clientApi@1460028544568\_meta\_tmp\clientApi@1460028544568\_meta\_tmp\clientApi@1460028544568\_meta\_tmp\clientApi@1460028544568\_meta\_tmp\clientApi@1460028544568\_meta\_tmp\clientApi@1460028544568\_meta\_tmp\clientApi@1460028544568\_meta\_tmp\clientApi@1460028544568\_meta\_tmp\clientApi@1460028544568\.git\objects\9d\
          *EXTRA File                458        2be99dfcd99c94119b8613cee8200377e4b1ac
```

**Comment by HyperBrain** [comment] 2016-04-07 14:50
The problem is, that you moved your function root to the project root. The packager will copy everything from your function directory recursively to _meta/_tmp. The bad thing is, that that also happens with _meta while it gets filled => so it leads to your result.

You should keep the old component directory as base for your function (e.g. function is in <project dir>/myFunctionGroup/function. Then it will work.

@eahefnawy We also could fix it by excluding _meta/** from the packaging, but I think having `function root === project root` in general is a bad idea as there might be other garbage or sensitive data lying around (like admin.env, etc.). What do you think?

**Comment by cdichiara** [comment] 2016-04-07 20:32
Ah, thank you, @HyperBrain. You know where I made my mistake? When you guys got rid of components, I thought I should get rid of the component directory, or at least they were optional. I don't mind putting it back there, it just wasn't clear from the v0.5.0 update notes that was still the best practice.

Also, I'm feeling the desire to put the dependencies into the root-level package.json ... if that doesn't work to have the ```node_modules``` folder at the root level, then I might have to recreate the "component-level" package.json in order to keep track of my dependencies ... any other ways you like to do it?

**Comment by erikerikson** [comment] 2016-04-14 22:54
Whether or not setting a lambda root to a project root is a good idea, the case should probably be handled.  I ran into this when I was trying to run a quick and dirty test.  I saw what was happening, ended it and cleaned up but...

**Comment by HyperBrain** [comment] 2016-04-14 23:03
I agree that it is a case that can occur and thus has to be handled somehow. Nevertheless I think the solution is not trivial and needs additional discussion and even a decision if that should be supported or not - and if not, how to prevent it...

**Comment by flomotlik** [comment] 2016-05-12 12:41
@HyperBrain @erikerikson this whole problem should be completely going away with the plans for V1 shouldn't it?

**Comment by erikerikson** [comment] 2016-05-13 03:24
Probably, I believe that it was caused by a link that serverless was creating and then not ignoring past its first ttraversa of the same.

**Comment by erikerikson** [comment] 2016-05-13 03:26
I think if users create cycles that it would be kindness to notice and behave well but if the framework creates them, it needs to properly handle them

**Comment by flomotlik** [comment] 2016-05-13 07:42
Yeah I just don't think those kinds of loops can really be created with the plans for V1. I'll leave this open to make sure we're not running into it but will close once the implementation is far enough to rule this issue out.

**Comment by DanielWeinerBT** [comment] 2016-05-24 19:37
Seeing the same issue when using the following file structure:

    <root>/
          |
          functions/
                   |--lib/
                   |--package.json
                   |--node_modules/
                   |--test/
                          |--testAll/
                                    |--handler.js
                                    |--event.json
                                    |--s-function.json



Where the `handler` property in `s-function.json` is set to `"functions/test/testAll/handler.handler"

**Comment by erikerikson** [comment] 2016-05-24 20:35
@DanielWeinerBT - Sorry you encountered this one.  It is a 0... product and efforts are focussed on building v1.
The sane workaround in the meantime is to keep your shared dependencies just below the root project folder.  We find that provides an extra layer of sanity as it firewalls the project's dependencies from the code's dependencies.  If all functions are not within the listed functions directory, I'd suggest adding a new folder and moving all functions into that new directory.

**Comment by DanielWeinerBT** [comment] 2016-05-24 20:43
This is exactly what I was attempting. The package.json is not within the root project folder, rather it is one level below it inside the functions directory, which serves as the base directory for all the functions. This should contain the code that is shared across all functions.

**Comment by HyperBrain** [comment] 2016-05-24 21:19
@DanielWeinerBT But then your handler should be set to `test/testAll/handler.handler`. Then it should work.

**Comment by erikerikson** [comment] 2016-05-24 21:19
@DanielWeinerBT in that case, you need to drop `'functions'` from your handler declaration:
`test/testAll/handler.handler`

To understand, consider what folder you would be in to write the following:
`node test/testAll/handler.handler.js`

The folder containing the `test` folder (in this case `functions`) is implied by the `test` folder being a valid name from within its context.  Because you included `functions` in your `handler` declaration, you implied that your project's root folder is to be included.

**Comment by DanielWeinerBT** [comment] 2016-05-24 21:20
thanks

**Comment by TheConnMan** [comment] 2016-06-05 17:12
@cdichiara How did you get rid of the recursive directories? I've got the same issue and so far robocopy has been running for ~45 min without any sign of stopping.

**Comment by cdichiara** [comment] 2016-06-07 01:44
Oh, yes, it took me a while, too ... sorry to hear it happened to you as well. It's possible that something's not working, but I recall it taking several hours to clean it all up, including the time spent figuring out the solution:

https://blog.bertvanlangen.com/articles/path-too-long-use-robocopy/

**Comment by TheConnMan** [comment] 2016-06-12 23:09
Thanks @cdichiara, I think that's the same blog I was looking at. Unfortunately robocopy ran for a good 90 min before quitting and I didn't even get the files deleted. I'll try it again when I get a chance.

**Comment by flomotlik** [comment] 2016-08-05 08:45
In V1 this shouldn't be an issue any more, so I'm closing.

**Closed by flomotlik** 2016-08-05 08:45 UTC
Labels: discussion
