### ISSUE TITLE
"Cannot load file from outside of service folder"

### ISSUE THREAD

**Issue by cyberfox1** [serverless/serverless#9179] opened 2021-03-25 00:01 UTC
What rubbish is this? Whose smart idea was this? Not being able to load files outside of service folder breaks my serverless architecture that uses common var files outside the service files to provide a common baseline of variables.

Why does this software keep going down the drain every release?

**Comment by medikoo** [comment] 2021-03-25 07:56
@cyberfox1 Are you using Lerna? Can we consider this as duplicate of https://github.com/serverless/serverless/issues/9095 ?

Note that there are many valid (security and portability related) reasons to not allow to reach for files from whatever system path.

**Comment by phancox** [comment] 2021-04-22 00:49
This is a breaking change for one of my clients as well.  They package multiple stacks on AWS into projects where each stack is an ansible role.  Roles might be standard cloudformation templates or serverless projects.  Each of those roles share a configuration file per environment so the various configuration files live at the overall project level and are referenced by all of the roles that make up the overall project. 

So we end up with this location in our serverless project roles: ${file(../../../vars/${env:Project}_${env:Environment}.yml)}

**Comment by medikoo** [comment] 2021-04-22 07:14
> This is a breaking change for one of my clients as well. 

Note, that this is a change announcement and not actual change. Change will happen from v3, nothing breaking at this point.

Have you checked the discussion at #9095 ? We've coined there I believe very good approach to multiple stack projects, which will be followed by Framework.

I'm closing this issue, as technically it's a duplicate of #9065 and all discussion should be done there

**Closed by medikoo** 2021-04-22 07:14 UTC
Labels: question
