### ISSUE TITLE
Can only be undefined or an object error when installing plugins which are referenced in external YAML 

### ISSUE THREAD

**Issue by jshhrrsn** [serverless/serverless#7317] opened 2020-02-11 11:55 UTC
# Bug Report

Hey guys, big fan of your work but stumbled across the following and thought it worth raising as it seems to be a bug in yamlAstParser.js. when plugins are referenced from an external file in serverless.yml.

## Description

1. What did you do?
Attempting to download serverless plugins using ` sls plugin install --name` via a script fails when plugins are stored in an external yaml file and referenced in the serverless.yml.  I'm trying to do this so that I can call the script as part of CI/CD pipeline and not have to list out the plugins in multiple locations. N.b., this script does work when using `npm install --save` rather than `sls plugin install`. 

install script: 

``` python 

import subprocess
import os
import yaml

def install_sls_plugins():
        with open('environment.yml', 'r') as source:
            environment = yaml.load(source, Loader=yaml.FullLoader)

    service = environment['service']
    try:
        os.chdir(service)
    except FileNotFoundError:
        os.chdir(f'../{service}')
    for plugin in environment['plugins']:
        subprocess.call(['sls', 'plugin', 'install', '--name', plugin]) # fails - see output below
        # subprocess.call(['npm', 'install', '--save', plugin]) - this works fine
```

N.b. running `sls plugin install -n [plugin]` manually in the terminal also fails in the same way, so the issue isn't with the install the plugins via `subprocess.call` in the script. 

2. What happened?
The install command seems to fail at the yamlAstParser.js referencing an error with `${file(environment.yml):plugins}` (which is specified in the serverless.yml for plugins).

Serverless: Installing plugin "serverless-plugin-existing-s3@latest" (this might take a few seconds...)
 
  Error --------------------------------------------------
 
  Error: ${file(environment.yml):plugins} can only be undefined or an object!
      at /usr/local/lib/node_modules/serverless/lib/utils/yamlAstParser.js:97:15
      at tryCatcher (/usr/local/lib/node_modules/serverless/node_modules/bluebird/js/release/util.js:16:23)
      at Promise._settlePromiseFromHandler (/usr/local/lib/node_modules/serverless/node_modules/bluebird/js/release/promise.js:547:31)
      at Promise._settlePromise (/usr/local/lib/node_modules/serverless/node_modules/bluebird/js/release/promise.js:604:18)
      at Promise._settlePromise0 (/usr/local/lib/node_modules/serverless/node_modules/bluebird/js/release/promise.js:649:10)
      at Promise._settlePromises (/usr/local/lib/node_modules/serverless/node_modules/bluebird/js/release/promise.js:729:18)
      at Promise._fulfill (/usr/local/lib/node_modules/serverless/node_modules/bluebird/js/release/promise.js:673:18)
      at /usr/local/lib/node_modules/serverless/node_modules/bluebird/js/release/nodeback.js:42:21
      at /usr/local/lib/node_modules/serverless/node_modules/graceful-fs/graceful-fs.js:90:16
      at FSReqCallback.readFileAfterClose [as oncomplete] (internal/fs/read_file_context.js:61:3)

N.b. The output to `sls print` shows that the referenced plugins from the enivornment.yml are read in correctly by serverless.yml:

`sls print`:
``` yaml
# REDACTED... 
package:
  include:
    - environment.yml
plugins:
  - serverless-python-requirements
  - serverless-plugin-existing-s3
```

3. What should've happened?
Plugins should have download correctly

4. What's the content of your `serverless.yml` file?

``` yaml
# REDACTED
package:
  include:
    - environment.yml

plugins: ${file(environment.yml):plugins}
```

environment.yml
``` yaml
---
plugins:
  - serverless-python-requirements
  - serverless-plugin-existing-s3
```

5. What's the output you get when you use the `SLS_DEBUG=*` environment variable (e.g. `SLS_DEBUG=* serverless deploy`)
As above. 

Similar or dependent issues:
- #3930

**Comment by medikoo** [comment] 2020-02-12 00:02
@jshhrrsn thanks for report. Unfortunately currently we do not support referencing plugins via external file. See https://github.com/serverless/serverless/issues/7203#issuecomment-573650058 for more details, and on proposal on how this will be possibly solved in a future.

I'm going to close it as duplicate of #7203

**Closed by medikoo** 2020-02-12 00:02 UTC
