### ISSUE TITLE
Approached unrecognized configuration variable sources: "git", "self"

### ISSUE THREAD

**Issue by Wurstnase** [serverless/serverless#9442] opened 2021-05-07 05:42 UTC
I'm using a plugin for serverless for git variables:
https://github.com/jacob-meacham/serverless-plugin-git-variables

Similar to this issue: https://github.com/serverless/serverless/issues/9355

I'm unsure, if this issue is a problem with the new solver, which needs to be solved by the plugin or by serverless.

<details>
<summary><code>serverless.yml</code></summary>

```yaml
service: testing

# Additional serverless plugins
plugins:
  - serverless-plugin-git-variables

custom:
  tags:
    project:
      git:
        branch: ${git:branch}

provider:
  name: aws
  runtime: python3.8
  region: eu-central-1
  stackTags:
    project_git_branch: ${self:custom.tags.project.git.branch}
```

</details>

<details>
<summary><b><code>SLS_DEBUG=* npx sls package</code> output</b></summary>

```
Serverless: To ensure safe major version upgrades ensure "frameworkVersion" setting in service configuration (recommended setup: "frameworkVersion: ^2.40.0")

Serverless: Load command interactiveCli
Serverless: Load command config
Serverless: Load command config:credentials
Serverless: Load command config:tabcompletion
Serverless: Load command config:tabcompletion:install
Serverless: Load command config:tabcompletion:uninstall
Serverless: Load command create
Serverless: Load command install
Serverless: Load command package
Serverless: Load command deploy
Serverless: Load command deploy:function
Serverless: Load command deploy:list
Serverless: Load command deploy:list:functions
Serverless: Load command invoke
Serverless: Load command invoke:local
Serverless: Load command info
Serverless: Load command logs
Serverless: Load command metrics
Serverless: Load command print
Serverless: Load command remove
Serverless: Load command rollback
Serverless: Load command rollback:function
Serverless: Load command slstats
Serverless: Load command plugin
Serverless: Load command plugin
Serverless: Load command plugin:install
Serverless: Load command plugin
Serverless: Load command plugin:uninstall
Serverless: Load command plugin
Serverless: Load command plugin:list
Serverless: Load command plugin
Serverless: Load command plugin:search
Serverless: Load command config
Serverless: Load command config:credentials
Serverless: Load command upgrade
Serverless: Load command uninstall
Serverless: Load command login
Serverless: Load command logout
Serverless: Load command generate-event
Serverless: Load command test
Serverless: Load command dashboard
Serverless: Load command output
Serverless: Load command output:get
Serverless: Load command output:list
Serverless: Load command param
Serverless: Load command param:get
Serverless: Load command param:list
Serverless: Load command studio
Serverless: Deprecation warning: Approached unrecognized configuration variable sources: "git", "self".
            From a next major this will be communicated with a thrown error.
            Set "variablesResolutionMode: 20210326" in your service config, to adapt to new behavior now
            More Info: https://www.serverless.com/framework/docs/deprecations/#NEW_VARIABLES_RESOLVER
Serverless: Invoke package
Serverless: Invoke aws:common:validate
Serverless: Invoke aws:common:cleanupTempDir
Serverless: Packaging service...
Serverless: Invoke aws:package:finalize
Serverless: Invoke aws:common:moveArtifactsToPackage
```

</details>

<b>Installed version</b>

```
Framework Core: 2.40.0 (local)
Plugin: 4.5.3
SDK: 4.2.2
Components: 3.9.2
```

**Comment by pgrzesik** [comment] 2021-05-09 18:51
Hello @Wurstnase, thanks a lot for reporting. This particular warning is caused by the fact that the `serverless-plugin-git-variables` is not adjusted to new variables resolved. Would you be able to report this issue on the plugin side?

**Comment by Wurstnase** [comment] 2021-05-09 19:13
Hello @pgrzesik,

thanks. I wasn't sure which side is responsible for this issue. I opened an issue on the plugin side. 

Are there examples, how to use this new resolver in plugins?

**Comment by medikoo** [comment] 2021-05-10 07:58
Bug on our side is that we list `self` as unrecognized source, that's not true (we'll fix it shortly).  Otherwise (when `git` source is concerned) message is valid

> Are there examples, how to use this new resolver in plugins?

Yes, it's documented here:
https://www.serverless.com/framework/docs/providers/aws/guide/plugins#custom-variable-types

**Comment by pgrzesik** [comment] 2021-05-28 16:35
I'm going to close this one as I believe it was fixed + any further changes will have to happen on plugin side.

**Closed by pgrzesik** 2021-05-28 16:35 UTC
Labels: cat/plugin, question
