### ISSUE TITLE
Invoke function command in v1.4.0 gives error

### ISSUE THREAD

**Issue by rowanu** [serverless/serverless#2986] opened 2016-12-20 01:57 UTC
# This is a Bug Report

## Description

* What went wrong?

**Invoking a deploy function displays an error using v1.4.0.**
If I revert to v1.3.0, there is no error i.e. it works as expected.
Using `invoke local` works (in that I see `console.log` output from my function handler), but displays the same error message as well (see below).

* What did you expect should have happened?

I shouldn't see an error message (see below).

Not sure if this is something specific to me, so thought I would report it incase others see it.

* What was the config you used?

A handler function that only outputs to `console.log` i.e. does nothing.
A handler config that has no event sources i.e. must be invoked manually.

* What stacktrace or error message from your provider did you see?

`generate` is the name of my function:

```
bash-3.2$ sls invoke -f generate
timers.js:435
        callback.call(immediate, arg1);
                ^

TypeError: Cannot read property 'call' of undefined
    at Immediate.immediate._onImmediate (timers.js:435:17)
    at processImmediate [as _immediateCallback] (timers.js:383:17)
```

## Additional Data

* ***Serverless Framework Version you're using***: v1.4.0
* ***Operating System***: OSX
* ***Stack Trace***: See above
* ***Provider Error messages***: NA

**Comment by eahefnawy** [comment] 2016-12-20 09:31
@rowanu could you show us the following please:

- full stack trace
- your simple function config
- your simple function handler code

also, could you try invoking by passing data with: `sls invoke -f generate -d "something"`, and let us know if you still face the error? I have some theories about this issue! 😄

**Comment by rowanu** [comment] 2016-12-20 09:44
* Full stack trace is as above - even with `SLS_DEBUG` set.
* Function config (snippet from `serverless.yml`):
```yaml
functions:
  generate:
    handler: handler.generate
```
* Function handler:
```javascript
module.exports.generate = (event, context, callback) => {
  console.log('generating');
  return callback(null);
};
```

Due to IP restrictions I can't re-run the invoke command at the moment - I will report back with result of the `-d` call, but it's something I definitely didn't try.

**Comment by rowanu** [comment] 2016-12-22 00:19
Yep, can confirm that running it with data (i.e. the `-d` argument) runs **without** the error message @eahefnawy.

**Comment by pmuens** [comment] 2016-12-22 14:10
Just tried to reproduce it today. Unfortunately I don't get an error. Using the version on `master`.

Here's my setup:

```yml
service: service

provider:
  name: aws
  runtime: nodejs4.3

functions:
  hello:
    handler: handler.hello
```

```javascript
// handler.js
module.exports.hello = (event, context, callback) => {
  console.log('generating');
  return callback(null);
};
```

I can remember that I've seen this error before. However the merged PRs from the last couple of days don't include any changes to invoke... 🤔

**Comment by mthenw** [comment] 2017-01-02 14:01
Looks like it's not longer an issue.

**Closed by mthenw** 2017-01-02 14:01 UTC
Labels: kind/bug
