### ISSUE TITLE
Serverless deploy fails after update from 1.24.1 to 1.25.0

### ISSUE THREAD

**Issue by ihorfito** [serverless/serverless#4631] opened 2018-01-05 08:45 UTC
# This is a Bug Report

## Description
Serverless application works on 1.24.1 version, after updating serverless to 1.25.0, "serverless deploy" fails with error. After changing serverless version back to 1.24.1 it works again.
For bug reports:
* What went wrong?
Deploy fails after changing serverless version from 1.24.1 to 1.25.0 
* What did you expect should have happened?
Deploy should run without errors after serverless upadte

* What stacktrace or error message from your provider did you see?

## Additional Data

* ***Serverless Framework Version you're using***: 1.25.0
Serverless Error ---------------------------------------  
An error occurred: MyLambdaVersionl7sH2kLfxNHEEk4pJj557EN0svGZitSVdsF8sksyz1I - A version for this Lambda function exists ( 53 ). Modify the function to create a new version.. 

* Stack Trace --------------------------------------------  
ServerlessError: An error occurred: CollectLambdaVersionl7sH2kLfxNHEEk4pJj557EN0svGZitSVdsF8sksyz1I - A version for this Lambda function exists ( 53 ). Modify the function to create a new version.. at provider.request.then (/usr/local/lib/node_modules/serverless/lib/plugins/aws/lib/monitorStack.js:112:33) From previous event: at AwsDeploy.monitorStack (/usr/local/lib/node_modules/serverless/lib/plugins/aws/lib/monitorStack.js:26:12) at provider.request.then (/usr/local/lib/node_modules/serverless/lib/plugins/aws/lib/updateStack.js:84:30) From previous event: at AwsDeploy.update (/usr/local/lib/node_modules/serverless/lib/plugins/aws/lib/updateStack.js:84:8) From previous event: at AwsDeploy.BbPromise.bind.then (/usr/local/lib/node_modules/serverless/lib/plugins/aws/lib/updateStack.js:101:12) From previous event: at AwsDeploy.updateStack (/usr/local/lib/node_modules/serverless/lib/plugins/aws/lib/updateStack.js:95:8) From previous event: at AwsDeploy.BbPromise.bind.then (/usr/local/lib/node_modules/serverless/lib/plugins/aws/deploy/index.js:135:39) From previous event: at Object.aws:deploy:deploy:updateStack [as hook] (/usr/local/lib/node_modules/serverless/lib/plugins/aws/deploy/index.js:131:10) at BbPromise.reduce (/usr/local/lib/node_modules/serverless/lib/classes/PluginManager.js:368:55) From previous event: at PluginManager.invoke (/usr/local/lib/node_modules/serverless/lib/classes/PluginManager.js:368:22) at PluginManager.spawn (/usr/local/lib/node_modules/serverless/lib/classes/PluginManager.js:386:17) at AwsDeploy.BbPromise.bind.then (/usr/local/lib/node_modules/serverless/lib/plugins/aws/deploy/index.js:101:48) From previous event: at Object.deploy:deploy [as hook] (/usr/local/lib/node_modules/serverless/lib/plugins/aws/deploy/index.js:97:10) at BbPromise.reduce (/usr/local/lib/node_modules/serverless/lib/classes/PluginManager.js:368:55) From previous event: at PluginManager.invoke (/usr/local/lib/node_modules/serverless/lib/classes/PluginManager.js:368:22) at PluginManager.run (/usr/local/lib/node_modules/serverless/lib/classes/PluginManager.js:399:17) at variables.populateService.then (/usr/local/lib/node_modules/serverless/lib/Serverless.js:102:33) at runCallback (timers.js:637:20) at tryOnImmediate (timers.js:610:5) at processImmediate [as _immediateCallback] (timers.js:582:5) From previous event: at Serverless.run (/usr/local/lib/node_modules/serverless/lib/Serverless.js:89:74) at serverless.init.then (/usr/local/lib/node_modules/serverless/bin/serverless:42:50)

**Comment by HyperBrain** [comment] 2018-01-05 09:18
This is a duplicate of #4599 .

There seems to be one very rare condition where this happens once, but works afterwards. Can you try the 2 steps I mentioned here: https://github.com/serverless/serverless/issues/4599#issuecomment-353354142 ?

However, to catch the root reason, do you have a detailed CloudFormation update log available? Especially the order of the resource modifications would be helpful.

**Comment by ihorfito** [comment] 2018-01-05 10:10
@HyperBrain Yes, I have access to CloudFormation update log,
Some functions are updated correctly, and some fails when I run "serverless deploy"(v1.25.0).
I am using "serverless-webpack": "4.2.0" and after source changes deploy is successful.

**Comment by HyperBrain** [comment] 2018-01-05 10:31
Good. Can you check if, for the failing functions in the CF logs, the new version resources are created _before_ the old ones are removed or if there is another obvious CF update order problem? My guess is, that in some cases when updating from 1.24.1 to 1.25.0 the implicit order is wrong because Serverless misses to add a vital dependency to its resources (which would be the root case - hidden until 1.25.0, because the version resource logical ids were wrong in case, only the configuration changed).

**Comment by ihorfito** [comment] 2018-01-05 10:37
@HyperBrain 
here is CloudFormation Log
[https://gist.github.com/ihorfito/fcf1ceeecaff820012f9eea148d8f06d](https://gist.github.com/ihorfito/fcf1ceeecaff820012f9eea148d8f06d)

**Comment by daniel-cottone** [comment] 2018-01-10 19:26
Running into this problem as well; reverting to `1.24.1` fixes.

**Comment by HyperBrain** [comment] 2018-01-11 11:23
I think I found the problem with the not automatically deleted old versions if a new one is deployed.
The reason is, that the version resources are set to RETAIN, i.e. if a function configuration is changed and a new version is created but no new function code, the replaced one does not get deleted.
As there is only one version for the same code allowed, this errors in that case.
We should set the version's DeletionPolicy to DELETE and it should work. However, side-effects should be evaluated first - the serverless-alias plugin does not have the problem, because it corrects the setting anyway.

**Comment by l-hendriks** [comment] 2018-01-23 10:11
+1 We also encounter this issue, but we don't use te alias plugin (but do use serverless-webpack)

**Comment by tgfischer** [comment] 2018-05-16 15:40
I ran into this issue today. I am using Serverless ^1.25.0, and serverless-webpack ^5.1.0

**Comment by Enase** [comment] 2018-05-16 17:01
@tgfischer do you use `serverless-aws-alias`? The [last release](https://github.com/HyperBrain/serverless-aws-alias/releases/tag/v1.7.1) fixes the [trouble](https://github.com/HyperBrain/serverless-aws-alias/issues/120)

**Comment by tgfischer** [comment] 2018-05-16 17:04
Nope. I updated to the latest versions of `serverless` and `serverless-webpack`, and I'm not getting the error so far. I'll comment if it happens again

**Comment by murtyjones** [comment] 2018-05-31 13:16
I'm getting this error with serverless 1.27.3.

```
[0]   Serverless Error ---------------------------------------
[0]  
[0]   An error occurred: ApiLambdaVersionzxSrUmhVDohdGOvyVjSxLmXvBIyXbQc8Kloi7ttpk4 - A version for this Lambda function exists ( 10 ). Modify the function to create a new version..
[0]  
[0]   Get Support --------------------------------------------
[0]      Docs:          docs.serverless.com
[0]      Bugs:          github.com/serverless/serverless/issues
[0]      Issues:        forum.serverless.com
[0]  
[0]   Your Environment Information -----------------------------
[0]      OS:                     linux
[0]      Node Version:           8.9.4
[0]      Serverless Version:     1.27.3
```

**Comment by l-hendriks** [comment] 2018-05-31 14:12
I've learned that you get this issue when you deploy the script using different roles. So if you `sls deploy` with role A and then `sls deploy` with role B, and the function code is not changed, you will get the error. If you change the function code or use the role of the previous deployment it works.

**Comment by murtyjones** [comment] 2018-05-31 18:51
@l-hendriks Thanks for the input. I'm not all that familiar with roles in this context. In your case, did a role change occur outside the scope of your `serverless.yml`? I haven't modified anything in my config relating to roles so I'm unsure how I ended up in that situation, assuming I have the same error source.

**Comment by l-hendriks** [comment] 2018-06-02 09:03
In our case it was deploying from multiple sources. For example once on my pc and then in the CI pipeline. But also when a colleague deploys and then I want to deploy as well (each of us have different keys).

**Comment by murtyjones** [comment] 2018-06-03 03:14
That's helpful, thanks. 

For anyone else struggling with this, deleting the CloudFormation templates (IE deleting the entire stack) and all S3 deployment buckets got rid of the error for now. Not a great solution for production environments though.

**Comment by l-hendriks** [comment] 2018-06-03 08:36
That does work, but as you said in a production environment this is not really feasible. Another workaround is to just modify the code a bit. We learned to just ignore the error for our CI pipeline setup. It means that it doesn't deploy when there are no code changes, but as there are no code changes it doesn't have to deploy. When there are code changes, the error is gone.

**Comment by murtyjones** [comment] 2018-06-03 15:06
In my case that techniqu yielded different errors each time I deployed. I've opened up #5016 to illustrate the issues, but for now nuking my stack was the only way to get unstuck.

**Comment by pmuens** [comment] 2019-02-08 09:58
Closing since this is a rather old issue. In the meantime we've published many different releases which should address this issue.

Feel free to re-open if this is still a problem.

**Closed by pmuens** 2019-02-08 09:58 UTC
Labels: bug, help wanted

**Comment by skydroid** [comment] 2019-03-11 21:36
Hello! I just encountered this issue with serverless version 1.38.0

I tried **sls deploy** and **sls deploy --force** to no avail.

**Comment by l-hendriks** [comment] 2019-03-12 08:57
You can just change the function code a bit (add a console.log or something) and redeploy. Then when you remove that extra bit and deploy again, it should work as well. I encounter this sometimes when serverless wants to redeploy a lambda function with identical code.

**Comment by skydroid** [comment] 2019-03-12 14:06
Thanks for your insight. While that is a workaround, I don't think that will work for automated production deployments?

**Comment by l-hendriks** [comment] 2019-03-12 14:19
Yes it is but it's not really a problem for us anymore. We get this very very seldom, if that happens in the automated deployment, we just add a useless line in production and then remove it again. Not ideal, but it works :p

**Comment by skydroid** [comment] 2019-03-12 15:23
I put in a useless (commented) line in my lambda function and the issue still persists.

**Comment by l-hendriks** [comment] 2019-03-12 15:32
try adding a console.log. If you add a commented line and webpack the function, the commented line is stripped out, leaving your code unchanged

**Comment by skydroid** [comment] 2019-03-12 16:12
Ah! Ok that did. Seemed it kicked it back into a "normal" state. I can deploy at will now.

**Comment by l-hendriks** [comment] 2019-03-13 05:44
Cool! This always works. Not really a solution, but not sure if this will ever get fixed...

**Comment by tjdavey** [comment] 2019-06-04 04:00
We're still encountering this issue on 1.42.3. The workaround of causing the checksum to change with an edit to the code/binary still works, but we would like to avoid that in the future. I've provided as much information as I think is relevant, but can provide more if that would assist. If you need the generated CloudFormation templates I also have those handy. 

**Environment**
```
     OS:                     linux
     Node Version:           10.16.0
     Serverless Version:     1.42.3
```

**Stack Trace**
```
ServerlessError: An error occurred: TilerLambdaVersionPwzE4AZGNo861yKVIaiaoDngWhVko95qcxB5XHL9uaA - A version for this Lambda function exists ( 46 ). Modify the function to create a new version..
    at provider.request.then (/home/circleci/project/node_modules/serverless/lib/plugins/aws/lib/monitorStack.js:118:33)
From previous event:
    at AwsDeploy.monitorStack (/home/circleci/project/node_modules/serverless/lib/plugins/aws/lib/monitorStack.js:31:12)
    at provider.request.then (/home/circleci/project/node_modules/serverless/lib/plugins/aws/lib/updateStack.js:105:30)
From previous event:
    at AwsDeploy.update (/home/circleci/project/node_modules/serverless/lib/plugins/aws/lib/updateStack.js:105:8)
From previous event:
    at AwsDeploy.BbPromise.bind.then (/home/circleci/project/node_modules/serverless/lib/plugins/aws/lib/updateStack.js:122:12)
From previous event:
    at AwsDeploy.updateStack (/home/circleci/project/node_modules/serverless/lib/plugins/aws/lib/updateStack.js:116:8)
From previous event:
    at AwsDeploy.BbPromise.bind.then (/home/circleci/project/node_modules/serverless/lib/plugins/aws/deploy/index.js:127:39)
From previous event:
    at Object.aws:deploy:deploy:updateStack [as hook] (/home/circleci/project/node_modules/serverless/lib/plugins/aws/deploy/index.js:123:10)
    at BbPromise.reduce (/home/circleci/project/node_modules/serverless/lib/classes/PluginManager.js:422:55)
From previous event:
    at PluginManager.invoke (/home/circleci/project/node_modules/serverless/lib/classes/PluginManager.js:422:22)
    at PluginManager.spawn (/home/circleci/project/node_modules/serverless/lib/classes/PluginManager.js:440:17)
    at AwsDeploy.BbPromise.bind.then (/home/circleci/project/node_modules/serverless/lib/plugins/aws/deploy/index.js:93:48)
From previous event:
    at Object.deploy:deploy [as hook] (/home/circleci/project/node_modules/serverless/lib/plugins/aws/deploy/index.js:89:10)
    at BbPromise.reduce (/home/circleci/project/node_modules/serverless/lib/classes/PluginManager.js:422:55)
From previous event:
    at PluginManager.invoke (/home/circleci/project/node_modules/serverless/lib/classes/PluginManager.js:422:22)
    at PluginManager.run (/home/circleci/project/node_modules/serverless/lib/classes/PluginManager.js:453:17)
    at variables.populateService.then (/home/circleci/project/node_modules/serverless/lib/Serverless.js:110:33)
    at runCallback (timers.js:705:18)
    at tryOnImmediate (timers.js:676:5)
    at processImmediate (timers.js:658:5)
    at process.topLevelDomainCallback (domain.js:126:23)
From previous event:
    at Serverless.run (/home/circleci/project/node_modules/serverless/lib/Serverless.js:97:6)
    at serverless.init.then (/home/circleci/project/node_modules/serverless/bin/serverless:43:28)
    at /home/circleci/project/node_modules/graceful-fs/graceful-fs.js:111:16
    at /home/circleci/project/node_modules/graceful-fs/graceful-fs.js:45:10
    at FSReqWrap.args [as oncomplete] (fs.js:140:20)
From previous event:
    at initializeErrorReporter.then (/home/circleci/project/node_modules/serverless/bin/serverless:43:6)
    at runCallback (timers.js:705:18)
    at tryOnImmediate (timers.js:676:5)
    at processImmediate (timers.js:658:5)
    at process.topLevelDomainCallback (domain.js:126:23)
From previous event:
    at /home/circleci/project/node_modules/serverless/bin/serverless:28:46
    at Object.<anonymous> (/home/circleci/project/node_modules/serverless/bin/serverless:65:4)
    at Module._compile (internal/modules/cjs/loader.js:776:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:787:10)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
    at Function.Module._load (internal/modules/cjs/loader.js:585:3)
    at Function.Module.runMain (internal/modules/cjs/loader.js:829:12)
    at startup (internal/bootstrap/node.js:283:19)
    at bootstrapNodeJSCore (internal/bootstrap/node.js:622:3)
```
**CloudFormation Events**
CloudFormation is showing the following order of operations for this resource:
- 04 Jun 2019 02:33:19 |  DELETE_SKIPPED
- 04 Jun 2019 02:32:57 |  CREATE_FAILED | A version for this Lambda function exists ( 46 ). Modify the function to create a new version.
- 04 Jun 2019 02:32:56 |  CREATE_IN_PROGRESS

**Comment by AnthonyWC** [comment] 2019-07-23 21:26
Just another data point but this bug also existed on 1.40.0

**Comment by smartinspereira** [comment] 2019-08-01 21:32
@pmuens  also on 1.49.0, this seems to happen more often if you change nothing but the `reservedConcurrency` of a function.

**Comment by vgaltes** [comment] 2019-11-11 09:43
Hi,

I can confirm what @smartinspereira says. If you only change the reservedConcurrency value the framework fails when deploying with something like:
```
An error occurred: WorkerLambdaVersioniM7aUiLGlRABKJ1sMuNlMeBU22uF3mN5LBXf3XGz9s - A version for this Lambda function exists ( 4 ). Modify the function to create a new version..
```

**Comment by amcappelli** [comment] 2020-01-08 16:09
I ran into this error with version 1.60.4. In my case, it was triggered by moving environment variables from the provider section to some individual functions. I was able to work around it by modifying the environment variable name, deploying, changing it back, and redeploying, but it would be nice if serverless recognized that there was no actual change so it wouldn't try to update the functions.

**Comment by Pitasi** [comment] 2020-07-23 13:30
> I ran into this error with version 1.60.4. In my case, it was triggered by moving environment variables from the provider section to some individual functions. I was able to work around it by modifying the environment variable name, deploying, changing it back, and redeploying, but it would be nice if serverless recognized that there was no actual change so it wouldn't try to update the functions.

Happened to me too after moving env variables from inside a function to outside.

I added a new temporary env variable, `sls deploy`, then removed it, and finally `sls deploy` again.
