### ISSUE TITLE
AWS: Extend ${cf} syntax to get output from another region broken

### ISSUE THREAD

**Issue by smartinspereira** [serverless/serverless#5606] opened 2018-12-17 12:04 UTC
# This is a Bug Report

## Description
@dschep @horike37 @exoego 
maybe I am missing something here, but this feature doesn't seem to be working as intended.
cf cross region is just creating a stack on the referenced region, with naming from the referencing region.

* What went wrong?
  - created stack `bar` in zone **`y`** and reference existing stack `foo` in zone `y`  
* What did you expect should have happened?
  - created stack `bar` in zone **`x`** and reference existing stack `foo` in zone `y`  
* What was the config you used?
  - this two used stacks `foo` and `bar` will cause the error. `x=us-east-1;` `y=eu-central-1;`

```
service: foo

provider:
  name: aws
  region: eu-central-1
  stage: dev
  profile: cndx-dev
  runtime: nodejs8.10
  memory: 1024

functions:
  hello:
    handler: handler.hello

resources:
  Outputs:
    foo:
      Value: foo
      Export:
        Name: foo
```

```
service: bar

provider:
  name: aws
  region: us-east-1
  stage: dev
  profile: cndx-dev
  runtime: nodejs8.10
  memory: 1024

functions:
  hello:
    handler: handler.hello

resources:
  Outputs:
    foobar:
      Value: ${self:custom.foobar}
      Export:
        Name: foobar

custom:
  foobar: ${cf.eu-central-1:foo-dev.foo}bar
  # foobar: foobar
```

* What stacktrace or error message from your provider did you see?
  - none

* Steps to reproduce:
```
version 1:
  1. `sls deploy` foo
  2. `sls deploy` bar (_with_ the stack reference in this last two lines enabled)
    -> this will lead to the creation of a new stack `bar-dev` in the same region as `foo-dev`
    -> error: _no direct error_ but stack `bar-dev` should be in  `us-east-1`
```
```
version 2:
1. `sls deploy` foo
2. `sls deploy` bar (_without_ the stack reference in this last two lines enabled)
3. `sls deploy` bar (_with_ the stack reference in this last two lines enabled)
  -> this will lead to the creation of a new stack `bar-dev` in the same region as `foo-dev`
  -> error: `An error occurred: IamRoleLambdaExecution - bar-dev-us-east-1-lambdaRole already exists.`
```

Similar or dependent issues:
* none

## Additional Data

* ***Serverless Framework Version you're using***: 1.35.0
* ***Operating System***: macos 10.14.2
* ***Stack Trace***: none
* ***Provider Error messages***: none

**Comment by efimk-lu** [comment] 2019-01-02 14:31
Hey, @smartinspereira any news about it? The same thing happens to me as well.

**Comment by dschep** [comment] 2019-01-02 14:33
Sorry, been overwhelmed without time to check this out. @exoego, any chance you have any input since you implemented this feature?

**Comment by smartinspereira** [comment] 2019-01-03 11:30
@efimk-lu unfortunately nothing new, but i also did not test this using 1.35.1 again.

**Comment by efimk-lu** [comment] 2019-01-03 11:43
We've been testing it with Version 1.35.1, the latest :-(

**Comment by exoego** [comment] 2019-01-03 12:07
I briefly tested using serverless `1.35.1` and the described serverless YAMLs while `profile: cndx-dev` were commented out (since I do not have such profile).

As far as I tested, serverless can deploy stacks to the specified regions (`foo` to eu-central-1, `bar` to us-east-1) and `${cf.REGION}` syntax works.

So I am guessing that `profile` could be suspicious.

@smartinspereira @efimk-lu 
Can you provide AWS profile ?
Please DO NOT SHARE `aws_access_key_id`, `aws_secret_access_key` or other credential information from profile.
Also, if you run `sls deploy` command with some options such as `--region` and so on, those may help too.

**Comment by efimk-lu** [comment] 2019-01-03 21:51
@exoego I'll share it shortly. We tried with --region and hard-coding region in the yaml.

**Comment by smartinspereira** [comment] 2019-01-04 10:20
@exoego what exactly do you mean with _Can you provide AWS profile ?_.
are you sure that your stack `bar` is in us-east-1? - see `version 1`, it will deploy the stack, but in the wrong region. also you could just create a profile in `~/.aws/credentials` with the name `cndx-dev` and your own credentials.

**Comment by exoego** [comment] 2019-01-04 11:16
>  are you sure that your stack bar is in us-east-1? - see version 1, 

Actually, `bar` was deployed to `eu-central-1`, not `us-east-1`.
However, serverless log says that it deployed to `us-east-1` like below:

```
Serverless: Stack update finished...
Service Information
service: bar
stage: dev
region: us-east-1
stack: bar-dev
api keys:
  None
endpoints:
  None
functions:
  hello: bar-dev-hello
layers:
  None
```

**Comment by exoego** [comment] 2019-01-04 11:17
> what exactly do you mean with Can you provide AWS profile ?

I initially thought default region or such field in profile may help to reproduce issue.
However, it seems that profile is not needed to reproduce.

**Comment by exoego** [comment] 2019-01-04 11:23
I think I found a root cause.
Will open a PR this weekend.

**Comment by exoego** [comment] 2019-01-04 12:36
I think the issue is fixed in https://github.com/serverless/serverless/pull/5650
Now `bar` is deployed to `us-east-1`, not `eu-central-1` which is referenced in `${cf.eu-central-1}`.

Thanks for trying this feature and reporting issue @smartinspereira @efimk-lu

**Comment by efimk-lu** [comment] 2019-01-04 14:09
@exoego tried the new version and it fixes the problem. Tx!

**Closed** 2019-01-07 01:49 UTC
