### ISSUE TITLE
Add support for Lambda versioning and aliases

### ISSUE THREAD

**Issue by pmuens** [serverless/serverless#1457] opened 2016-06-30 12:59 UTC
The lambda function get's replaced every time a new version is deployed.

We should keep track of the lambda versions and enable lambda versioning / alias support.

**Things to investigate:** "What about the bucket cleanup and Lambda versioning?" (https://github.com/serverless/serverless/issues/1504 / https://github.com/serverless/serverless/pull/1477)

**Comment by nicka** [comment] 2016-08-04 13:49
Simple idea... don't shoot me 😊 

Format with a hash based on `includes` dir, `handler.js` and `serverless.env.yml`?

I would also recommend enabling versioning on the Lambda S3 bucket with a lifecycle rule to remove archives older than X days on top of the keep 5 archives.

**Comment by pmuens** [comment] 2016-08-04 14:08
@nicka thanks for that idea! 👍 

Love the versioning of the S3 bucket as it's already available through AWS and also of interest if we store the CloudFormation template there (like discussed here: https://github.com/serverless/serverless/issues/1740).

Currently not quite sure if we should just version the lambda or the entire CloudFormation stack.

**Comment by svdgraaf** [comment] 2016-08-05 11:39
I second the hashing of the files as @nicka proposed, easiest solution to see if anything has changed. CF is smart enough to see that it should only update the lambda functions if the hash changed. 

I think versioning of the CF stack could be handy, as you would have the option of rolling back to some previous version.

I'm not a big fan of auto deleting older files, there could be a plugin for that though:`sls purge` or something, which could hold X amount of deploys and versions (both CF and lambda zips).

**Comment by pmuens** [comment] 2016-08-10 08:11
@nicka @svdgraaf thanks for the valuable feedback so far!

However we're not there yet as we need to understand what the exact use case for versioning is.

Maybe the @serverless/vip team can chime in here and outline the use cases / whether this feature is necessary at all.

**Comment by cagataygurturk** [comment] 2016-08-10 08:26
Are you sure about this? AFAIK for each deployment a new Lambda version is published.

**Comment by HyperBrain** [comment] 2016-08-10 08:27
For us versioning is primarily useful to be able to trace back a deployed version from build up to the AWS lambda console, with each step in-between clearly understandable.
## Versioning
So the major requirement regarding versioning at top level is, that every artifact emitted from any step in the build chain has a version attached. Any CI build system should apply a defined version (including a custom versioning scheme) to the deployed artifacts.
With AWS (whether you use API or CF) the version assigned by the deployment system can even be used as lambda version (custom versioning) and will be displayed instead of the standard AWS numeric lambda versions. This would be a great addition, as then (together with aliases, see below) a direct relat5ionship between deployment versions, uploaded lambda artifacts AND active stages can be made at one glance.
## Aliases
When handling projects that use a micro service architecture you'll end up with huge amounts of single lambda functions. Aliases help to keep the artifacts logically grouped by function and offer the ability to have an exact understanding which version of a deployed function is active on a specific stage. Having lambdas on different stages differentiated by their names makes the maintenance of the system very unhandy.
A functionality, that was not supported by SLS 0.5.x was just moving aliases back to a previously deployed version. That would be a great addition to solve emergency rollbacks (even if they theoretically cannot happen in an ideal world ;-) ) Also tagging the same version with more than one alias (e.g. shifting a lambda version on dev to prod) would speed up this use case enormously.

**Comment by jordanmack** [comment] 2016-08-10 08:29
The early versions of Serverless created a new archive for each deploy, and this was stored on S3. There was also a [plugin](https://github.com/Nopik/serverless-lambda-prune-plugin) which was created to prune old versions. Does anyone remember why this functionality was removed?

**Comment by nicka** [comment] 2016-08-10 08:33
> However we're not there yet as we need to understand what the exact use case for versioning is.

What I would like to achieve is only upload/deploy/update the Lambda archive if the code was actually updated, variables where added/changed or dependent CF resources where updated.

Based on this info we format a hash/version which stays the same between deployments. This way CF would leave the resources as is and only updated them is the hash was changed.

**Comment by HyperBrain** [comment] 2016-08-10 08:34
For the S3 storage I think it was initially meant to store the environment settings file of the lambdas, until the variable system and the JSON file population with the variables had been implemented. SLS helpers was the code to read the file from within the lambda runtime, that was copied from S3 on deploy.

**Comment by flomotlik** [comment] 2016-08-10 11:17
@jordanmack thats still how we do deployment through CF. We package, push to S3 and then set it up in cloud formation. We also remove everything but the last 5 deployments. The only difference to the old system was that we're creating one large file for the whole service now, but there are people already working on a PR that allows to create separate archives per function.

**Comment by flomotlik** [comment] 2016-08-10 11:42
Regarding Version support in Lambda my current thoughts are that we should support setting aliases for functions, so its easy to update where sources point to, but not to support Versions inside Lambda.

# Versions

The main reason I see for using Versions in Lambda is Rollback. From my experience at Codeship though I haven't seen Rollback in CI/CD to be a necessary feature. Push forward is imho the much better model to deal with issues. There are typically two cases for deployment:

**1. You've only updated Code, it fails and you need to release a new version of the code (or go back to an old version of the code). It doesn't affect stored data at all.**

You can simply rerun the last build of CI or check out the specific commit in your Repository that you want to deploy and deploy it again. This is very easy to do with Serverless through either the full serverless deploy if you want to deploy the whole service (typically better idea as your code might touch various functions) or deploy single functions only (a little faster, but not as secure)

**2. You've updated code that changes your database in a meaningful way or you've deployed new resources through Cloudformation.**

In this case you can't simply roll back. The rollback needs to involve more complex data migration or other ways how you fix your data. If you've deployed additional resources through cloud formation and you want to keep those resources, but you want to change the function code you can still do this easily by either reverting the changes to code in your repo and go through a new build, or simply deploy it locally through `serverless deploy function` to fix your function until you do a full new deployment. For this one case having versions might be helpful, but imho compared to all the effort we would have to do to get it to work it would not be worth it.

I've looked into Version support in Lambda and simply adding a version to the CF template only exports the latest version, but removes all past versions automatically. So we would basically have to read the currently deployed CF template, get all existing versions from there, merge them into the new template and redeploy. This creates a dependency between a new deployment and the existing infrastructure we don't really want. Especially if its for a feature that is kind of nice to have but can easily be accomplished in many other ways (Rollback)

# Alias

We can easily support aliases on functions so you can simply set the latest deployed version of a function should always get a specific alias (this can even be combined with #1801 so you can enable this through variables.

As we decided that every stage gets its own CF template it is not possible to deploy functions from dev to prod by simply changing the alias. They are different functions deployed in different CF stacks so a function has to be redeployed to another stage to be in production.

Imho this is a feature and not a bug. Same as with APIG stages it is imho not a good idea to merge different environments in the same basic resource on AWS (e.g. a function or API Gateway). Otherwise deploying to your dev environment would also mean changing parts of your production system (as the same function is used for dev and prod, even though with different aliases)

So I do think having the additional option of setting an alias is nice for a newly deployed version, I don't think a deeper integration with aliases to separate dev/prod or other environments or workflows is really valuable at the moment.

# 1 Caveat

The one area where I do think Versions or Labels can be helpful as a config parameter is when setting custom versions so you can e.g. set your current Commit_hash as a custom version. @HyperBrain can you point me to some docs how to set this custom version? Haven't seen that anywhere

**Comment by cagataygurturk** [comment] 2016-08-10 13:48
Versioning support in CF is a shame. Very bad implemented. Same in API Gateway deployments.

You can't remove a version once you publish them, there is no such a API call but if you remove a AWS::Lambda::Version resource from a CF template the version disappears. Totally unbelievable.

On the other hand you can embed a custom resource backed with Lambda into CF template that creates a new version of the function for each time when CF template is updated.

**Comment by HyperBrain** [comment] 2016-08-10 14:22
@flomotlik Parameter "Version":
Using the API: https://docs.aws.amazon.com/lambda/latest/dg/API_UpdateFunctionCode.html
Seems the declaration is yet missing in the CF Lambda template types.

You can set the version to an arbitrary sequence of digits up to 1024 in length (exception $LATEST) will only upload to '$LATEST'

**Comment by flomotlik** [comment] 2016-08-10 14:49
@HyperBrain I'm not sure thats possible there, I can only see version as a response parameter, not as a request parameter

**Comment by awolden** [comment] 2016-08-16 00:00
I am looking to use serverless in a large system, and the lack of versioning is troublesome for me.   I would love to be to automatically rollback a deploy if e2e tests fail. In order for us to have a true CD/CI system we need the ability to quick rollback, and I am not sure how you do that without the ability to version lambda's.

**Comment by seanohollaren** [comment] 2016-08-16 00:17
I'd echo that sentiment.  The ability to roll back is a requirement for my use case and I'd guess it's going to be a pretty common one.

**Comment by flomotlik** [comment] 2016-08-16 02:29
@awolden would love to chat about the details of that with you. Could you send me an email to flo@serverless.com to set something up?

**Comment by kurtmaile** [comment] 2016-09-08 06:51
Hi all we are setting up our versioning and rollback as depicted below.  Note:  We are using gosparta for go based lambda microservices to do below.  We are investigating serverless for our other programming languages, thus the inquiry into some of these types of capabilities.  Im new to serverless and wondering if below is possible now?

![lambda-versioning](https://cloud.githubusercontent.com/assets/20066181/18339713/0445bb22-7599-11e6-899c-c61ca618cddc.png)

**Comment by caseeker** [comment] 2016-09-16 22:18
I've been working on lambda deployment automation with boto3 :)
With the same reasons @flomotlik explained, our team decided to use aliases instead of versions.
Rollback setup and rollback becomes very easy and quick as you simply needs to capture what version the alias is pointing to. Then you can deploy new code which will publish new version if there's source code change or configuration change, move the alias to point the new published version, run test against deployed function, and simply roll back to previous version if test fails.
It is pretty easy and simple with API calls, I hope cloudformation implementation is not too hectic.
Keep in mind as you start to use aliases all the related event sources also need to be updated to point to specific alias of the function.

**Comment by kfloz** [comment] 2016-10-13 11:26
@flomotlik is there any update on roadmap for alias and/or versioning inclusion?  Be a great feature! :)

**Comment by flomotlik** [comment] 2016-10-13 11:31
@kfloz at the moment we don't have a specific Roadmap. I don't think we'll implement Lambda Versions anytime soon, I can see Aliases coming in soon though.

We have been thinking about Rollback support (which is in our experience the most requested feature with versioning in lambda) and it should be relatively straight forward to implement Rollback with Serverless because we store all resources for a Stack in S3 and can simply redeploy it.

**Comment by kfloz** [comment] 2016-10-13 11:38
Thanks heaps for the update - agree with your comments on alias' and previous s3 deployments as a option to get rollback capability.  Cheers and great work loving v1.0.0 :)

**Comment by flomotlik** [comment] 2016-10-17 08:49
Closing here because Alias support (#2411) and Rollback (#2412) will be implemented

**Closed by flomotlik** 2016-10-17 08:49 UTC
Labels: area/provider-integration, discussion

**Comment by roarkry** [comment] 2016-10-17 14:59
@flomotlik - is there any documentation on how Serverless envisions managing various Lambda/API environments and promoting code between dev and production (for example)?  The AWS docs seem to point towards versions and aliases, so i'm curious if Serverless has a POV on this?

**Comment by flomotlik** [comment] 2016-10-18 06:24
@roarkry basically through stages. When deploying you can set the stage that you want to deploy to: https://serverless.com/framework/docs/providers/aws/

**Comment by pdkn** [comment] 2017-07-04 14:32
Hi Guys, We're using serverless to deploy Lambda for Alexa skills. Amazon have recommended we start using aliasing to manage production versioning which give us ability to lock down the ARN while also allowing us to make quick hotfixes should we need to. We can only do this using serverless once there's support for updating alias version pointers. Can we kindly request this feature? Thanks

**Comment by HyperBrain** [comment] 2017-07-04 14:43
@pdkn You can try the alias plugin: https://github.com/HyperBrain/serverless-aws-alias (also on npmjs).

Please give me feedback if anything with the plugin does not meet your requirements (or directly create an issue ther)

**Comment by pmuens** [comment] 2017-07-04 14:49
> @pdkn You can try the alias plugin: https://github.com/HyperBrain/serverless-aws-alias (also on npmjs).

> Please give me feedback if anything with the plugin does not meet your requirements (or directly create an issue there)

@pdkn right now we don't have an ETA for alias support. @HyperBrain plugin is really feature rich and should do the trick in that case. So definitely give it a spin as it's the go-to solution for such a problem right now!

**Comment by pdkn** [comment] 2017-07-04 14:53
Thanks, I've tried using this plugin but can't see how to update the version an Alias points to? The Docs state: "The aliased version is read only in the AWS console, so it is guaranteed that the environment and function parameters (memory, etc.) cannot be changed for a deployed version by accident, as it can be done with the $LATEST qualifier. This adds an additional level of stability to your deployment process."

Am I missing a trick? We're after this functionality - http://docs.aws.amazon.com/lambda/latest/dg/API_UpdateAlias.html

**Comment by HyperBrain** [comment] 2017-07-04 15:02
Ok. That is a missing feature (to promote an already deployed version of a Serverless service) to a different already deployed version (alias). Technically this would be shifting the aliases.

Currently the behavior is, that you can deploy the service to different aliases, whereas each deployment will create a new function version and sets the selected alias to is. So you can deploy blue and green as different aliases, but you have to redeploy the "blue" version to the "green" alias to have it as "green" available. Then you would deploy a new test version to the "blue" alias and test it.

In general there should be no quality implications if you do it that way until an alias shift/promotion is available, if you use "serverless package" and "serverless deploy" separately, where you have a clear distinction between build and deploy. You can store the built artifacts after package and deploy them to different aliases with "serverless deploy". The only difference is, that the same ZIP is redeployed to a different version, but the alias is set there.

In general you can call your lambdas with the "Qualifier" set to the alias and the arns are just extended with ":<aliasname>"

**Comment by pdkn** [comment] 2017-07-04 15:55
Many Thanks @HyperBrain. My understanding was once an Alexa skill is released the Alias (arn) can't be redeployed (where as it's version pointer can be updated)? I'll do some more digging. In the meantime is there any aversion your end to look at adding a feature like this to the roadmap? Thanks again.

**Comment by HyperBrain** [comment] 2017-07-04 16:06
@pdkn Not at all 😃 . Also for us (and I think many more people) it would be a good addition to have a promotion feature. Please feel free to add a feature request.

Regarding the redeployment of the alias arn - that might be meant for the skill's side, which would be independent of the lambda side. You could do a test to have a skill referencing an alias (deployed with sls deploy --alias=XXXX) test it, maybe change some code and then redeploy with the same command line.
Would be interesting to know if the skill then works on the changed code.

**Comment by pdkn** [comment] 2017-07-04 16:18
Ace, will do. Our current released Alexa Skill isn't using Aliasing so I'll need to wait till we resubmit a new version with Aliasing in place to verify. In the meantime I'll reach out to Amazon for any insights. Thanks Again

**Comment by candlerb** [comment] 2017-11-26 16:53
> Ok. That is a missing feature (to promote an already deployed version of a Serverless service) to a different already deployed version (alias). Technically this would be shifting the aliases.

For me, what I want is that on every deploy, update an alias (e.g. "current") to point to the version just published.  That's it.

Aside: this is not the same as pointing the alias to `$LATEST`.  That is permitted, but an alias which points to `$LATEST` will always invoke the most-recently deployed version of that function.

If I have `current` points to the version just published, and have the clients invoke `<function>:current`, then normally clients will run the latest version; BUT it also allows me to swing the `current` alias to point to any previous version (I'm happy to use the aws cli to do this).

I looked at `serverless-aws-alias` but it seems to do a bunch of other stuff, like adding an alias equal to the name of the stage, which I don't want; after all, each stage is already in its own entirely separate CloudFormation stack, and the stage is already embedded in the function name.  I just want a single well-known alias for the version to be run.

**Comment by coderade** [comment] 2017-12-28 13:02
Hi guys, I'm trying to create a trigger automatically for each version of my lambda published.

When I deploy my serverless app, my trigger is created, but for my published version the trigger doesn't exists.

There is any way to do this?

* my `serverless.yml` file:

```yml
service: serverless-lambdas
provider:
  name: aws
  runtime: nodejs6.10
  iamRoleStatements:
    - Effect: "Allow"
      Action:
        - "ses:*"
        - "iot:*"
      Resource:
        - "*"

functions:
   function1:
    name: "function1"
    handler: function1/handler.function1
    events:
      - iot:
          name: "iotEvent1"
          sql: "SELECT EXAMPLE"
          sqlVersion: "2016-03-23"
          enabled: true
```

**Comment by justasitsounds** [comment] 2018-02-15 05:46
I'm also stuck trying to create triggers for versioned lambda functions - in my case it's for an Alexa skill and as @pdkn said above, once a skill has been certified you can't change the skill configuration with a new ARN.

**Comment by candlerb** [comment] 2018-02-15 08:55
I think there are two main things you might want to do:

1. update aliases to point to the latest versions of each deployed function
2. update aliases to point to some previous version (rollback)

There should be a simple and general way to do this, bearing in mind that a single serverless.yml may have multiple lambdas, and they may have a different set of published version numbers (this happens if you start developing and publishing one lambda, and then add another lambda)

I came up with this idea:

~~~
sls alias --update prod --at 20180214T1230 [-f foo]
~~~

This would create or update an alias `prod` on all functions (or selected function foo), pointing at the most recent version which was published on or before the given timestamp.  If you miss `--at` then it defaults now (i.e. latest published versions), and if you miss `--update` then it could use a default name e.g. `current`

Workflow then becomes:

~~~
sls deploy
# perform testing on foo:$LATEST and bar:$LATEST

sls alias --update uat
# perform testing on foo:uat and bar:uat

sls alias --update prod
# now production clients are using latest code

# panic! rollback required
sls alias --update prod --at 20180214T1230
~~~

Another useful option could be to copy aliases so that they point to the same version as an existing alias:

~~~
sls alias --update prod_safe --copy prod
sls alias --update prod
... prod is now on latest code

... rollback to known good version
sls alias --update prod --copy prod_safe
~~~

And for completeness:

~~~
# for each function show all aliases and which version number/timestamp they point to
sls alias --list

sls alias --delete prod_safe
~~~

**Comment by HyperBrain** [comment] 2018-02-15 13:58
> There should be a simple and general way to do this, bearing in mind [...]

This only is simple as long as you do not use any Lambda function event declarations in your yaml service definition. As soon as you have additional triggers like APIG endpoints, SNS or anything else, these will not call your aliased functions but still refer to and call the $LATEST version. It even becomes more tricky as soon as you start using authorizers. I.e. when you'll use a real-world project.

It was when I realized the complexity of a suitable approach that I started with the aws-alias plugin and tried to solve these dependencies properly.

**Comment by candlerb** [comment] 2018-02-15 14:46
I had a look at aws-alias, but it seems to combine deploy with changing of alias - that is, I couldn't see a way to move the alias to point back to a previous version, independently of deploying new code.  But I could have misunderstood.

**Comment by HyperBrain** [comment] 2018-02-15 15:00
Yes, that's right. It is intended to use aliases for different parallel deployments (like CI/CD environments or stages) and not specific historic versions.
However, there is a feature request open that would allow "promotion", so an alias can be copied (promoted) to a different alias, i.e. published without rebuilding/redeploying.
