### ISSUE TITLE
Wierd async behaviour when invoking locally from 1.33.0 onward

### ISSUE THREAD

**Issue by LazarDL** [serverless/serverless#5523] opened 2018-11-27 11:35 UTC
# This is a Bug Report

## Description

* What went wrong?
When **invoking locally**, promises created by async functions don't propagate past the first "then" in the chain.
(in the provided snippet the output is First, Second).
This behavior is observed from version 1.33.0(included) and up. 
* What did you expect should have happened?
The whole chain is executed (including the catch if an exception was thrown)
(in the provided snippet the output is First, Second, Third, Catch) 
* What was the config you used?
Bellow is the serverless.yml and a strip down code to illustrate the issue.
serverless.yml:
```
service: aws-nodejs
provider:
  name: aws
  runtime: nodejs8.10
  environment: 
    AWS_DEFAULT_REGION : eu-west-1
functions:
  test:
    handler: index.handler
```
index.js:
```
var first = async () => {
  console.log("First");
};
var second = async () => {
  console.log("Second");
};
var third = async () => {
  console.log("Third");
  throw { Success: false };
};
exports.handler = (event, context, callback) => {
  first()
    .then(second)
    .then(third)
    .catch(() => console.log("Catch"));
};
```

* What stacktrace or error message from your provider did you see?
No error messages.

Similar or dependent issues:
* #5522 - Seems like the issues might have common cause.

## Additional Data

* ***Serverless Framework Version you're using***:1.33.0
* ***Operating System***: Windows 10 64 bit
* ***Stack Trace***: None
* ***Provider Error messages***: None

**Comment by dschep** [comment] 2018-11-27 14:15
You are correct that this is a duplicate of #5522

**Closed by dschep** 2018-11-27 14:15 UTC

**Comment by dschep** [comment] 2018-11-27 14:17
Actually. it's not quite the same issue. but tbh, I'm not sure there's a good way to handle a function that's not ever returning a promise or calling the callback function. You should be able to fix your issue by making your handler (note the return):
```javascript
exports.handler = (event, context, callback) => {
  return first()
    .then(second)
    .then(third)
    .catch(() => console.log("Catch"));
};
```

**Comment by LazarDL** [comment] 2018-11-27 14:39
Ah yes. True that. However, in the actual code we are invoking the callback in the final "then" statement or in the catch (some of our legacy code works with callbacks and we haven't gotten around to refactoring it).
Anyway, we will either stick to 1.32 for now or do some slight refactoring.
Thanks.
