### ISSUE TITLE
Cannot run integration tests 

### ISSUE THREAD

**Issue by medikoo** [serverless/serverless#3923] opened 2017-07-10 19:33 UTC
# This is a Bug Report

## Description

I'm trying to run integration tests as documented here: https://github.com/serverless/serverless/blob/master/CONTRIBUTING.md#testing-templates

Even though I expose valid setting for `AWS_PROFILE`, they crash with:

```
ServerlessError: The AWS security token included in the request is invalid / expired.
```

Is configuration broken, or am I doing something wrong?

![screen shot 2017-07-10 at 21 31 52](https://user-images.githubusercontent.com/122434/28036100-4d4127da-65b7-11e7-8db5-04549b63afd2.png)

## Additional Data

* Serverless @ master (https://github.com/serverless/serverless/commit/f0b1474f1e49d69c39e27e3c8def929569e20bed)
* macOS v10.12.5
* Node.js v8.1.3

**Comment by pmuens** [comment] 2017-07-11 06:16
Hey @medikoo thanks for opening 👍 

Do you see the same result when you run `npm run simple-integration-test`.
What about normal deployments? Do they work for you?

**Comment by medikoo** [comment] 2017-07-11 06:25
> Do you see the same result when you run npm run simple-integration-test

Yes, exactly same error occurs:

![screen shot 2017-07-11 at 08 22 38](https://user-images.githubusercontent.com/122434/28053716-2e337fe0-6612-11e7-9322-a39f7e0f1ac1.png)

> What about normal deployments? Do they work for you?

Yes, when working normally with SLS, I have no problems deploying services with same profile.

**Comment by pmuens** [comment] 2017-07-11 19:43
@medikoo thanks for getting back!

@eahefnawy found the root cause of this. It seems like https://github.com/serverless/serverless/pull/3903 broke the `master`.

We're working on a fix in the meantime...

**Comment by pmuens** [comment] 2017-09-18 11:02
Closing this issue since the fix has been shipped in the meantime...

**Closed by pmuens** 2017-09-18 11:02 UTC
Labels: kind/bug, status/more-info-needed
