### ISSUE TITLE
filter must be double-escaped when adding cloudwatchLog events

### ISSUE THREAD

**Issue by noahmedling** [serverless/serverless#4577] opened 2017-12-14 15:29 UTC
# This is a Bug Report

## Description

When adding a cloudwatchLog event with a filter that contains double quotes, I have to add additional escapes in order to get it to work. When I use this syntax in my `serverless.yml`:

```
events:
  - cloudwatchLog:
      logGroup: "/aws/lambda/foo"
      filter: "\\\""
```

I see this output in `.serverless/serverless-state.json`:

```
"LogToElasticsearchLogsSubscriptionFilterCloudWatchLog1": {
  "Type": "AWS::Logs::SubscriptionFilter",
  "DependsOn": "LogToElasticsearchLambdaPermissionLogsSubscriptionFilterCloudWatchLog1",
  "Properties": {
    "LogGroupName": "/aws/lambda/foo",
    "FilterPattern": "\"",
    "DestinationArn": {
      "Fn::GetAtt": [
        "LogToElasticsearchLambdaFunction",
        "Arn"
      ]
    }
  }
},
```

but I would expect FilterPattern to be:

```
"FilterPattern": "\\\""
```

Additionally, if I do not double-escape my quotes, I receive an error message. This syntax in `serverless.yml`:

```
events:
  - cloudwatchLog:
      logGroup: "/aws/lambda/foo"
      filter: "\""
```

produces this output:

```
$ SLS_DEBUG=\* sls package
Serverless: Load command run
Serverless: Load command config
Serverless: Load command config:credentials
Serverless: Load command create
Serverless: Load command install
Serverless: Load command package
Serverless: Load command deploy
Serverless: Load command deploy:function
Serverless: Load command deploy:list
Serverless: Load command deploy:list:functions
Serverless: Load command invoke
Serverless: Load command invoke:local
Serverless: Load command info
Serverless: Load command logs
Serverless: Load command login
Serverless: Load command logout
Serverless: Load command metrics
Serverless: Load command print
Serverless: Load command remove
Serverless: Load command rollback
Serverless: Load command rollback:function
Serverless: Load command slstats
Serverless: Load command plugin
Serverless: Load command plugin
Serverless: Load command plugin:install
Serverless: Load command plugin
Serverless: Load command plugin:uninstall
Serverless: Load command plugin
Serverless: Load command plugin:list
Serverless: Load command plugin
Serverless: Load command plugin:search
Serverless: Load command emit
Serverless: Load command config
Serverless: Load command config:credentials
Serverless: Load command rollback
Serverless: Load command rollback:function
Serverless: Invoke package
Serverless: Invoke aws:common:validate
Serverless: Invoke aws:common:cleanupTempDir
Serverless: Packaging service...
Serverless: Excluding development dependencies...

  Syntax Error -------------------------------------------

  Unexpected string in JSON at position 299

     For debugging logs, run again after setting the "SLS_DEBUG=*" environment variable.

  Stack Trace --------------------------------------------

SyntaxError: Unexpected string in JSON at position 299
SyntaxError: Unexpected string in JSON at position 299
    at JSON.parse (<anonymous>)
    at functionObj.events.forEach.event (C:\Users\NEM0201\AppData\Roaming\npm\node_modules\serverless\lib\plugins\aws\package\compile\events\cloudWatchLog\index.js:123:46)
    at Array.forEach (<anonymous>)
    at serverless.service.getAllFunctions.forEach (C:\Users\NEM0201\AppData\Roaming\npm\node_modules\serverless\lib\plugins\aws\package\compile\events\cloudWatchLog\index.js:23:28)
    at Array.forEach (<anonymous>)
    at AwsCompileCloudWatchLogEvents.compileCloudWatchLogEvents (C:\Users\NEM0201\AppData\Roaming\npm\node_modules\serverless\lib\plugins\aws\package\compile\events\cloudWatchLog\index.js:18:47)
    at BbPromise.reduce (C:\Users\NEM0201\AppData\Roaming\npm\node_modules\serverless\lib\classes\PluginManager.js:366:55)
    at tryCatcher (C:\Users\NEM0201\AppData\Roaming\npm\node_modules\serverless\node_modules\bluebird\js\release\util.js:16:23)
    at Object.gotValue (C:\Users\NEM0201\AppData\Roaming\npm\node_modules\serverless\node_modules\bluebird\js\release\reduce.js:157:18)
    at Object.gotAccum (C:\Users\NEM0201\AppData\Roaming\npm\node_modules\serverless\node_modules\bluebird\js\release\reduce.js:144:25)
    at Object.tryCatcher (C:\Users\NEM0201\AppData\Roaming\npm\node_modules\serverless\node_modules\bluebird\js\release\util.js:16:23)
    at Promise._settlePromiseFromHandler (C:\Users\NEM0201\AppData\Roaming\npm\node_modules\serverless\node_modules\bluebird\js\release\promise.js:512:31)
    at Promise._settlePromise (C:\Users\NEM0201\AppData\Roaming\npm\node_modules\serverless\node_modules\bluebird\js\release\promise.js:569:18)
    at Promise._settlePromise0 (C:\Users\NEM0201\AppData\Roaming\npm\node_modules\serverless\node_modules\bluebird\js\release\promise.js:614:10)
    at Promise._settlePromises (C:\Users\NEM0201\AppData\Roaming\npm\node_modules\serverless\node_modules\bluebird\js\release\promise.js:693:18)
    at Async._drainQueue (C:\Users\NEM0201\AppData\Roaming\npm\node_modules\serverless\node_modules\bluebird\js\release\async.js:133:16)
    at Async._drainQueues (C:\Users\NEM0201\AppData\Roaming\npm\node_modules\serverless\node_modules\bluebird\js\release\async.js:143:10)
    at Immediate.Async.drainQueues (C:\Users\NEM0201\AppData\Roaming\npm\node_modules\serverless\node_modules\bluebird\js\release\async.js:17:14)
From previous event:
    at PluginManager.invoke (C:\Users\NEM0201\AppData\Roaming\npm\node_modules\serverless\lib\classes\PluginManager.js:366:22)
    at PluginManager.run (C:\Users\NEM0201\AppData\Roaming\npm\node_modules\serverless\lib\classes\PluginManager.js:397:17)
    at variables.populateService.then (C:\Users\NEM0201\AppData\Roaming\npm\node_modules\serverless\lib\Serverless.js:104:33)
    at runCallback (timers.js:789:20)
    at tryOnImmediate (timers.js:751:5)
    at processImmediate [as _immediateCallback] (timers.js:722:5)
From previous event:
    at Serverless.run (C:\Users\NEM0201\AppData\Roaming\npm\node_modules\serverless\lib\Serverless.js:91:74)
    at serverless.init.then (C:\Users\NEM0201\AppData\Roaming\npm\node_modules\serverless\bin\serverless:42:50)
    at <anonymous>

  Get Support --------------------------------------------
     Docs:          docs.serverless.com
     Bugs:          github.com/serverless/serverless/issues
     Forums:        forum.serverless.com
     Chat:          gitter.im/serverless/serverless

  Your Environment Information -----------------------------
     OS:                     win32
     Node Version:           8.9.0
     Serverless Version:     1.24.1
```

## Additional Data

* ***Serverless Framework Version you're using***: 1.24.1
* ***Operating System***: win32 (running on Windows 7 x64)
* ***Stack Trace***: see above
* ***Provider Error messages***: none (sls tool dies before provider is contacted)

**Comment by horike37** [comment] 2017-12-15 09:02
Thank you for opening this issue @noahmedling :+1: 
Closing for now since it seems this is a duplicate of #4569

**Closed by horike37** 2017-12-15 09:02 UTC
