### ISSUE TITLE
Empty environment variables are set as `null` in cloudformation script and fails to deploy

### ISSUE THREAD

**Issue by bytesnz** [serverless/serverless#3007] opened 2016-12-22 10:10 UTC
# This is a (Bug Report)

## Description
When trying to deploy a configuration with an empty environment variable, the following error is produced:
```
  Serverless Error ---------------------------------------

     [/Resources/DemosLambdaFunction/Type/Environment/Variables/SNS_PORT]
     'null' values are not allowed in templates

  Get Support --------------------------------------------
     Docs:          docs.serverless.com
     Bugs:          github.com/serverless/serverless/issues

  Your Environment Information -----------------------------
     OS:                 linux
     Node Version:       4.3.2
     Serverless Version: 1.4.0
```

Expected result is empty environment variables are set to "" and it deploys with no issue

Extract of `serverless.yml` file:
`serverless.yml`
```yaml
provider:
  name: aws
  timeout: 20
  memorySize: 1536
  environment:
    # Storage Environment Vars
    STORAGE_BUCKET: ${file(env.yml):STORAGE_BUCKET}
    SNS_PORT: ${file(env.yml):SNS_PORT}
```

`env.yml`
```yaml
STORAGE_BUCKET: //example.com
SNS_PORT:
```

Similar or dependent issues:

## Additional Data

* ***Serverless Framework Version you're using***: 1.4.0
* ***Operating System***: Ubuntu 16.04
* ***Stack Trace***:
* ***Provider Error messages***:

**Comment by pmuens** [comment] 2016-12-22 11:25
Hey @bytesnz thanks for raising this issue.

Yes, using Serverless variables in combination with environment variables can yield to such a surprising behavior.

IMHO we should keep it that way and don't add defaults which might cause unexpected behavior / other issues. What do you think @eahefnawy @nikgraf @mthenw ?

**Comment by bytesnz** [comment] 2016-12-22 11:54
@pmuens I agree with not adding defaults, though making the empty environment variables an empty string (rather than `null`), would fix this issue and produce the expected environment variable on the deployment. From the other side, they could instead not be set in the cloudformation script if they are empty (`null` from parsing yaml)l. That way you could set a variable to "" explicitly and be able to have them not set dependant on for example stage variables (as above).

**Comment by pmuens** [comment] 2017-03-09 12:23
Closing this issue for now since it's unintended usage and a rare edge case.

**Closed by pmuens** 2017-03-09 12:23 UTC
Labels: status/more-info-needed

**Comment by AnthonyWC** [comment] 2019-03-26 18:32
Interestingly I just ran into this and got `"remoteFunctionData": null,` in `serverless-state.json`.  The template deployed fine but would fail CF linter such as https://github.com/aws-cloudformation/cfn-python-lint.
