### ISSUE TITLE
Using `variablesResolutionMode: 20210219` prevents loading external configuration files outside of service folder

### ISSUE THREAD

**Issue by laurynas-karvelis** [serverless/serverless#9141] opened 2021-03-18 13:13 UTC
Hello,
First of all I wanted to thank everyone involved creating such a great tool!

After upgrading to the latest serverless version `2.30.3` and applying `variablesResolutionMode: 20210219` to service `serverless.yml` in preparation for `serverless@v3` causes `serverless offline` and `serverless deploy` invocations to throw following error(s) when trying to load configuration files sourced **outside** serverless main service folder:

```
Cannot resolve serverless.yml: Variables resolution errored with:
    - Cannot resolve variable at "custom.globals": Cannot load file from outside of service folder
```

Loading complementary config files from outside service folder usually is very helpful way for developers who maintain mono repos that contain number of individual serverless services where all or some share common configuration values used across the project. Preventing such possibility introduces unnecessary config duplication and unwanted future misconfigurations due to configs being out of sync.

I searched your repository for this error and found a check that causes this error here: https://github.com/serverless/serverless/blob/68de8bdeed0545e6868c72806340e96f90f808cf/lib/configuration/variables/sources/file.js#L40-L45

<details>
<summary><code>serverless.yml</code></summary>

```yaml
service: service-name
variablesResolutionMode: 20210219

provider:
  name: aws
  lambdaHashingVersion: 20201221
  stage: local
custom:
  globals: ${file(../../serverless/globals.yml)}
```

</details>

<details>
<summary><b><code> <local_monorepo_path>/<service_name>/node_modules/.bin/serverless offline</code> output</b></summary>

```
 Serverless Error ----------------------------------------
 
  Cannot resolve serverless.yml: Variables resolution errored with:
    - Cannot resolve variable at "custom.globals": Cannot load file from outside of service folder
 
  Get Support --------------------------------------------
     Docs:          docs.serverless.com
     Bugs:          github.com/serverless/serverless/issues
     Issues:        forum.serverless.com
 
  Your Environment Information ---------------------------
     Operating System:          darwin
     Node Version:              12.20.1
     Framework Version:         2.30.3 (local)
     Plugin Version:            4.5.1
     SDK Version:               4.2.0
     Components Version:        3.7.5
 
error Command failed with exit code 1.
```

</details>

<b>Installed version</b>

```
Framework Core: 2.30.3 (local)
Plugin: 4.5.1
SDK: 4.2.0
Components: 3.7.5
```

**Comment by medikoo** [comment] 2021-03-18 13:40
@laurynas-karvelis great thanks for report!

Can we consider this as duplicate of https://github.com/serverless/serverless/issues/9095 ?

**Comment by laurynas-karvelis** [comment] 2021-03-18 14:09
By looking at the ticket you linked it is indeed the same issue. Thanks for such quick response @medikoo!

**Comment by medikoo** [comment] 2021-03-18 14:10
Thanks for confirmation.

I'm closing this as duplicate then

**Closed by medikoo** 2021-03-18 14:10 UTC
Labels: duplicate
