### ISSUE TITLE
Can't deploy a service after removing it

### ISSUE THREAD

**Issue by nikgraf** [serverless/serverless#1393] opened 2016-06-24 12:03 UTC
```
➜  telescope git:(master) ✗ ../bin/serverless remove           
 _______                             __
|   _   .-----.----.--.--.-----.----|  .-----.-----.-----.
|   |___|  -__|   _|  |  |  -__|   _|  |  -__|__ --|__ --|
|____   |_____|__|  \___/|_____|__| |__|_____|_____|_____|
|   |   |             The Serverless Application Framework
|       |                           serverless.com, v1.0.0
 -------'

Serverless: Getting all objects in S3 bucket...
Serverless: Removing objects in S3 bucket...
Serverless: Removing Stack...
Serverless: Checking stack removal progress...
Serverless: Resource removal successful!
➜  telescope git:(master) ✗ ../bin/serverless deploy           
 _______                             __
|   _   .-----.----.--.--.-----.----|  .-----.-----.-----.
|   |___|  -__|   _|  |  |  -__|   _|  |  -__|__ --|__ --|
|____   |_____|__|  \___/|_____|__| |__|_____|_____|_____|
|   |   |             The Serverless Application Framework
|       |                           serverless.com, v1.0.0
 -------'

Serverless: Creating Stack...
  Already Exists Exception -------------------------------
 
     Stack [telescope-dev] already exists
 
     For debugging logs, run again after setting SLS_DEBUG env var.
 
  Get Support --------------------------------------------
     Docs:          v1.docs.serverless.com
     Bugs:          github.com/serverless/serverless/issues
 
     Please report this error. We think it might be a bug.
 
➜  telescope git:(master) ✗ 
```

Keep in mind I removed the app from the file-system and created a new one.
This is only relevant to v1.0

**Comment by nikgraf** [comment] 2016-06-24 12:19
Now I'm getting another error:

```
➜  telescope git:(master) ✗ ../bin/serverless remove
➜  telescope git:(master) ✗ ../bin/serverless deploy
```
Serverless: Zipping functions...
Serverless: Uploading zip files to S3...
  No Such Bucket -----------------------------------------
 
     The specified bucket does not exist
 
     For debugging logs, run again after setting SLS_DEBUG env var.
 
  Get Support --------------------------------------------
     Docs:          v1.docs.serverless.com
     Bugs:          github.com/serverless/serverless/issues
 
     Please report this error. We think it might be a bug.
```

```

**Comment by pmuens** [comment] 2016-06-24 12:31
Might be related to https://github.com/serverless/serverless/issues/1370

**Comment by pmuens** [comment] 2016-06-27 08:08
Closing this as it's a duplicate of #1370

**Closed by pmuens** 2016-06-27 08:08 UTC
