### ISSUE TITLE
Type Error bug when runing "sls invoke local -f ..." @version2.1.0.  Not problem on version 1.80.0

### ISSUE THREAD

**Issue by jimfang** [serverless/serverless#8263] opened 2020-09-17 22:13 UTC
Serverless Warning --------------------------------------

  A valid SSM parameter to satisfy the declaration 'ssm:/conf-nonprod/config/mgmt/filter/guidewire/enable' could not be found.

 Serverless Warning --------------------------------------

  A valid SSM parameter to satisfy the declaration 'ssm:/conf-nonprod/config/mgmt/filter/guidewire/enable' could not be found.

 Serverless Warning --------------------------------------

  A valid SSM parameter to satisfy the declaration 'ssm:/conf-nonprod/config/mgmt/filter/guidewire/filename' could not be found.

 Serverless Warning --------------------------------------
 
  A valid SSM parameter to satisfy the declaration 'ssm:/conf-nonprod/config/mgmt/filter/guidewire/filename' could not be found.

Serverless: Configuration warning at 'service.awsKmsKeyArn': should match pattern "^arn:(aws[a-zA-Z-]*)?:kms:[a-z0-9-]+-\d+:\d{12}:[^\s]+$"
Serverless:  
Serverless: Learn more about configuration validation here: http://slss.io/configuration-validation
Serverless:  
 
  Type Error ---------------------------------------------

  TypeError: Cannot read property 'Fn::ImportValue' of undefined
      at C:\Users\fangj\AppData\Roaming\npm\node_modules\serverless\lib\plugins\aws\invokeLocal\index.js:188:18
      at Array.map (<anonymous>)
      at C:\Users\fangj\AppData\Roaming\npm\node_modules\serverless\lib\plugins\aws\invokeLocal\index.js:186:53
      at tryCatcher (C:\Users\fangj\AppData\Roaming\npm\node_modules\serverless\node_modules\bluebird\js\release\util.js:16:23)
      at Function.Promise.attempt.Promise.try (C:\Users\fangj\AppData\Roaming\npm\node_modules\serverless\node_modules\bluebird\js\release\method.js:39:29)     
      at AwsInvokeLocal.loadEnvVars (C:\Users\fangj\AppData\Roaming\npm\node_modules\serverless\lib\plugins\aws\invokeLocal\index.js:153:25)
      at AwsInvokeLocal.tryCatcher (C:\Users\fangj\AppData\Roaming\npm\node_modules\serverless\node_modules\bluebird\js\release\util.js:16:23)
      at Promise._settlePromiseFromHandler (C:\Users\fangj\AppData\Roaming\npm\node_modules\serverless\node_modules\bluebird\js\release\promise.js:547:31)      
      at Promise._settlePromise (C:\Users\fangj\AppData\Roaming\npm\node_modules\serverless\node_modules\bluebird\js\release\promise.js:604:18)
      at Promise._settlePromise0 (C:\Users\fangj\AppData\Roaming\npm\node_modules\serverless\node_modules\bluebird\js\release\promise.js:649:10)
      at Promise._settlePromises (C:\Users\fangj\AppData\Roaming\npm\node_modules\serverless\node_modules\bluebird\js\release\promise.js:729:18)
      at _drainQueueStep (C:\Users\fangj\AppData\Roaming\npm\node_modules\serverless\node_modules\bluebird\js\release\async.js:93:12)
      at _drainQueue (C:\Users\fangj\AppData\Roaming\npm\node_modules\serverless\node_modules\bluebird\js\release\async.js:86:9)
      at Async._drainQueues (C:\Users\fangj\AppData\Roaming\npm\node_modules\serverless\node_modules\bluebird\js\release\async.js:102:5)
      at Immediate.Async.drainQueues [as _onImmediate] (C:\Users\fangj\AppData\Roaming\npm\node_modules\serverless\node_modules\bluebird\js\release\async.js:15:14)
      at processImmediate (internal/timers.js:456:21)

     For debugging logs, run again after setting the "SLS_DEBUG=*" environment variable.

  Get Support --------------------------------------------
     Docs:          docs.serverless.com
     Bugs:          github.com/serverless/serverless/issues
     Issues:        forum.serverless.com

  Your Environment Information ---------------------------
     Operating System:          win32
     Node Version:              12.18.3
     Framework Version:         2.1.0
     Plugin Version:            4.0.3
     SDK Version:               2.3.2
     Components Version:        3.1.3

⚠️⚠️ REPLACE WITH DESCRIPTION

<details>
<summary><code>serverless.yml</code></summary>

```yaml
# ⚠️⚠️ REPLACE THIS COMMENT WITH FULL serverless.yml CONTENT
```

</details>

<details>
<summary><b><code>⚠️⚠️ REPLACE WITH FULL COMMAND NAME</code> output</b></summary>

```
⚠️⚠️ REPLACE WITH FULL COMMAND OUTPUT
```

</details>

<b>Installed version</b>

```
⚠️⚠️ REPLACE WITH `serverless --version` OUTPUT
```

**Comment by medikoo** [comment] 2020-09-18 08:32
@jimfang I believe error is caused due to env var values not being resolved from SSM (as warnings in your logs signal).

Bug on Framework side, is that:
- it doesn't crash when variable resolution fails (dedicated issue: https://github.com/serverless/serverless/issues/3367)
- `null` value for env var is not reported as invalid (dedicated issue: https://github.com/serverless/serverless/issues/8017, being solved at https://github.com/serverless/serverless/pull/8222)

as addressing above issues will present you with meaningful error information, I'm closing it on _duplicate_ grounds

**Comment by medikoo** [comment] 2020-09-18 08:32
Duplicate of #3367

**Closed by medikoo** 2020-09-18 08:32 UTC
Labels: duplicate
