### ISSUE TITLE
JavaScript heap out of memory

### ISSUE THREAD

**Issue by erikerikson** [serverless/serverless#3740] opened 2017-06-07 00:06 UTC
# This is a Bug Report

## Description

Endless recursive file loading exceeds process memory limits.

When trying to remove the serverless.yml here:
https://github.com/Nordstrom/hello-retail/tree/master/web

With the command (STAGE is properly defined and references an existing stack):
```
../node_modules/.bin/sls remove -s $STAGE -v
```

* What went wrong?

```
<--- Last few GCs --->

[22378:0x102804600]   192582 ms: Mark-sweep 1484.5 (1567.0) -> 1484.5 (1567.0) MB, 2065.8 / 0.0 ms  allocation failure GC in old space requested
[22378:0x102804600]   194638 ms: Mark-sweep 1484.5 (1567.0) -> 1484.4 (1536.0) MB, 2056.4 / 0.0 ms  last resort gc 
[22378:0x102804600]   196780 ms: Mark-sweep 1484.4 (1536.0) -> 1484.4 (1536.0) MB, 2141.0 / 0.0 ms  last resort gc 


<--- JS stacktrace --->

==== JS stack trace =========================================

    2: arguments adaptor frame: 1->2
Security context: 0x90122ec0d31 <JS Object>
    3: _settlePromiseFromHandler [<src-root>/hello-retail/node_modules/serverless/node_modules/bluebird/js/release/promise.js:~496] [pc=0x20e01cfbd1f3](this=0x2d4a7d8ea59 <a Promise with map 0x17140f73cc21>,handler=0x2d4a7d97671 <JS Function getValueFromSource.then.valueToPopulate (SharedFunctionInfo 0x2b325a77f011)>,receiver=0x90122e04311 <undefined>,val...

FATAL ERROR: CALL_AND_RETRY_LAST Allocation failed - JavaScript heap out of memory
 1: node::Abort() [~/.nvm/versions/node/v7.2.0/bin/node]
 2: node::FatalException(v8::Isolate*, v8::Local<v8::Value>, v8::Local<v8::Message>) [~/.nvm/versions/node/v7.2.0/bin/node]
 3: v8::internal::V8::FatalProcessOutOfMemory(char const*, bool) [~/.nvm/versions/node/v7.2.0/bin/node]
 4: v8::internal::Factory::NewByteArray(int, v8::internal::PretenureFlag) [~/.nvm/versions/node/v7.2.0/bin/node]
 5: v8::internal::SourcePositionTableBuilder::ToSourcePositionTable(v8::internal::Isolate*, v8::internal::Handle<v8::internal::AbstractCode>) [~/.nvm/versions/node/v7.2.0/bin/node]
 6: v8::internal::FullCodeGenerator::MakeCode(v8::internal::CompilationInfo*) [~/.nvm/versions/node/v7.2.0/bin/node]
 7: v8::internal::(anonymous namespace)::GenerateUnoptimizedCode(v8::internal::CompilationInfo*) [~/.nvm/versions/node/v7.2.0/bin/node]
 8: v8::internal::(anonymous namespace)::GetUnoptimizedCode(v8::internal::CompilationInfo*) [~/.nvm/versions/node/v7.2.0/bin/node]
 9: v8::internal::Compiler::Compile(v8::internal::Handle<v8::internal::JSFunction>, v8::internal::Compiler::ClearExceptionFlag) [~/.nvm/versions/node/v7.2.0/bin/node]
10: v8::internal::Runtime_CompileLazy(int, v8::internal::Object**, v8::internal::Isolate*) [~/.nvm/versions/node/v7.2.0/bin/node]
11: 0x20e01ca063a7
12: 0x20e01ca0675a
13: 0x20e01ca07e55
14: 0x20e01cfbd1f3
15: 0x20e01cfe1eb4
Abort trap: 6
```

* What did you expect should have happened?

Expected: removal of stack

Downgrading to serverless@1.11.0 allowed this to proceed as expected.

* What was the config you used?

https://github.com/Nordstrom/hello-retail/blob/master/web/serverless.yml

* What stacktrace or error message from your provider did you see?

see above.

## Additional Data

I suspect that this change may have introduced the new behavior but am not certain:
https://github.com/serverless/serverless/commit/971a27994c3566d9904f166a2e943c21ba4dfe54#diff-b921cbcedd2151d24391fb39acb84adeR88

* ***Serverless Framework Version you're using***: 1.13.2, 1.14.0
* ***Operating System***: osx
* ***Stack Trace***: see above
* ***Provider Error messages***: n/a

**Comment by erikerikson** [comment] 2017-06-07 00:19
This appears to be the result of changing the strategy of the variable resolution code so that it doesn't “replace in place”  before recursively populating the resolved value (i.e. instead one should return the result and modify the original containing object before then trying to resolve the child).

I haven't tried but the following seems like it would reproduce:

~/config.yml
```
someVal: ${self:custom.config.anotherVal}
anotherVal: foo
```

~/serverless.yml
```
custom:
  config: ${file(./config.yml)}
```

1. sls loads `~/serverless.yml`
2. sls loads `config.yml`
3. sls hasn't updated the original serverless.yml-based object but begins populating what was loaded in 2.  Namely `${self:custom.config.anotherVal}`
4. sls loads `self` and finds that the custom.config value is `${file(./config.yml)}`: goto 2.

entirely speculation.

**Comment by pmuens** [comment] 2017-06-07 06:22
Hey @erikerikson thanks for opening 👍 

Yes, I think you're right. We've just merged a fix for this recently (which will be included in v1.15).

Could you try it with the recent `master` or check again once we've published `v1.15` later today?

**Comment by HyperBrain** [comment] 2017-06-07 15:52
In general, I think that a recursive approach for the variable substitution is not the best way (populateObject and populateProperty are calling themselves). It would be better to implement that traversing with an iterative approach (breadth or depth first does not really matter).
With such an approach it is also easier to keep a map of visited objects locally.

**Comment by erikerikson** [comment] 2017-06-07 21:17
I tried this with the latest master and wasn't patient enough for it to blow up.  Repetitive messages were written.  Does not appear to be fixed in master.

**Comment by pmuens** [comment] 2017-06-08 06:16
Thanks for testing that out @erikerikson 

I think @HyperBrain has a valid point about recursion here. Seems like that's the root issue. Maybe we should change it to the propose BFS or DFS.

/cc @eahefnawy

**Comment by erikerikson** [comment] 2017-06-09 20:55
Maybe.  The issue is a result of the ability to do things like `${self:custom.mySetting.${opt:stage}}`.  Breadth vs depth first is irrelevant in such a "rewind" and "reevaluate" case.  It's simply that in a world allowing self-reference, that the referent must be replaced in place of the original reference before the original is processed further.

**Comment by HyperBrain** [comment] 2017-06-10 09:05
@erikerikson Exactly. The inner references have to be resolved first as their values build up the outer references. So the dereferencing itself has to work with states that are stored on a stack in this case and the system would be rewinded to that state after the inner reference has been evaluated.

Additionally the newly generated references can cause circular references depending on the value of the inner reference(s). The algorithm should be able to detect that, i.e. the dynamically generated reference has to be put into the map of visited objects.
A point here is, that it is quite easy to detect these circular references and stop processing, but for the user it should show a kind of stack trace (i.e. the states that triggered a "rewind" or "reevaluate") to really show where the root of the circle is located.

**Comment by iwllyu** [comment] 2017-06-22 21:13
We're seeing a similar issue, the cause is a cyclic reference. I tried this with 1.16 running `sls deploy --acct dev --noDeploy`

serverless.yml

```
provider:
  acct: ${opt:acct, self:provider.profile}
  vars: ${self:provider.accounts.${self:provider.acct}}    
  accounts:
    dev:
      publicStreamArn: arn:aws:kinesis:x:x:stream/${self:provider.vars.publicStreamName}
      privateStreamArn: arn:aws:kinesis:x:stream/${self:provider.vars.privateStreamName}
      privateStreamName: dev_stream
      publicStreamName: dev_stream
    prod:
      publicStreamArn: arn:aws:kinesis:x:x:stream/${self:provider.vars.publicStreamName}
      privateStreamArn: arn:aws:kinesis:x:x:stream/${self:provider.vars.privateStreamName}
      privateStreamName: private_stream
      publicStreamName: public_stream
```
replacing `${self:provider.vars.publicStreamName}` with `${self:provider.accounts.dev.publicStreamName}` or
`dev_stream` no longer produces the error

**Comment by kaihendry** [comment] 2017-08-17 09:16
Whilst trying to deploy https://github.com/laardee/serverless-authentication-boilerplate
```
~/serverless-authentication-boilerplate/authentication$ sls deploy
^E



<--- Last few GCs --->

[1763:0x77e0886bb0]   464860 ms: Mark-sweep 1935.7 (2020.2) -> 1935.4 (2000.7) MB, 2310.7 / 0.0 ms  (+ 0.0 ms in 0 steps since start of marking, biggest step $
.0 ms, walltime since start of marking 2311 ms) last resort
[1763:0x77e0886bb0]   468052 ms: Mark-sweep 1935.4 (2000.7) -> 1935.7 (2001.7) MB, 3190.0 / 0.0 ms  last resort


<--- JS stacktrace --->

==== JS stack trace =========================================

Security context: 0x394c3289cef1 <JSObject>
    0: builtin exit frame: captureStackTrace(aka captureStackTrace)(this=0x394c32882241 <undefined>,0x1179e377dd99 <JSFunction CapturedTrace (sfi = 0x2c1f8a45$
71)>,0x1cdf2d0cf9b1 <CapturedTrace map = 0x3014df317651>)

    1: _then [/home/hendry/.node_modules/lib/node_modules/serverless/node_modules/bluebird/js/release/promise.js:~219] [pc=0x2e99750076c1](this=0x1cdf2d0bd4f9
<Promise map = 0x3014...

FATAL ERROR: CALL_AND_RETRY_LAST Allocation failed - JavaScript heap out of memory
 1: node::Abort() [node]
 2: 0x77dfaf553f [node]
 3: v8::Utils::ReportOOMFailure(char const*, bool) [node]
 4: v8::internal::V8::FatalProcessOutOfMemory(char const*, bool) [node]
 5: v8::internal::Factory::NewRawOneByteString(int, v8::internal::PretenureFlag) [node]
 6: v8::internal::Factory::NewStringFromOneByte(v8::internal::Vector<unsigned char const>, v8::internal::PretenureFlag) [node]
 7: v8::internal::Factory::NumberToString(v8::internal::Handle<v8::internal::Object>, bool) [node]
 8: 0x77df7c9d7a [node]
 9: v8::internal::JSStackFrame::ToString() [node]
10: v8::internal::ErrorUtils::FormatStackTrace(v8::internal::Isolate*, v8::internal::Handle<v8::internal::JSObject>, v8::internal::Handle<v8::internal::Object>
) [node]
11: 0x77df39ed70 [node]
12: 0x2e9974ebc8dd
Aborted (core dumped)
```

**Comment by eahefnawy** [comment] 2017-08-23 13:31
@erikerikson I just PRed a fix for this, could you try out #4144 ? 😊

**Comment by erikerikson** [comment] 2017-08-23 14:23
I'm excited to!  Will report results.

**Comment by erikerikson** [comment] 2017-08-23 21:00
I have been able to validate this fix plus a small delta (#4146) as resolving the matter for both the entirety of Hello, Retail! as well as our latest internal project that was also subject to the problem.  Thanks @eahefnawy!

**Comment by Eli-Goldberg** [comment] 2017-10-07 10:05
Happens to me as well

**Comment by fruffin** [comment] 2017-10-17 02:41
Same problem here. That would be great to get this fix reviewed soon (I can confirm the fix works for my projects as well).
Workaround for now was to downgrade serverless back to a working version

**Comment by Greenginer** [comment] 2017-10-25 19:34
👍 for getting this fix out. This is starting to become a blocker to certain serverless deployments that are requiring difficult workarounds to utilize features that are available in later versions.

**Closed** 2017-12-11 09:55 UTC
Labels: kind/bug, stage/in-progress

**Comment by dashmug** [comment] 2018-01-30 05:58
I'm getting this error *randomly* during `sls deploy` with my project. 

```
node v6.10.3
serverless v1.26.0
serverless-webpack v4.2.0
```

I usually just restart the deploy and it's goes through the second time. This is probably caused by something else but I don't know where to start to investigate.

On successful builds, the output is like this:

```
...
Serverless: Copy modules: /codebuild/output/src172916450/src/build/audit-worker [4775 ms]
Serverless: Prune: /codebuild/output/src172916450/src/build/audit-worker [1517 ms]
Serverless: Zip function: /codebuild/output/src172916450/src/build/audit-worker [5635 ms]
...
... (this continues until the deploy succeeds)
```

On failed builds, the output is like this:

```
Serverless: Copy modules: /codebuild/output/src237433561/src/build/audit-worker [3144 ms]
Serverless: Prune: /codebuild/output/src237433561/src/build/audit-worker [1611 ms]

<--- Last few GCs --->

126575 ms: Mark-sweep 1331.3 (1434.9) -> 1326.6 (1434.9) MB, 2159.0 / 0.0 ms [allocation failure] [GC in old space requested].
128838 ms: Mark-sweep 1326.6 (1434.9) -> 1327.0 (1434.9) MB, 2262.4 / 0.0 ms [allocation failure] [GC in old space requested].
130681 ms: Mark-sweep 1327.0 (1434.9) -> 1331.8 (1411.9) MB, 1842.6 / 0.0 ms [last resort gc].
132121 ms: Mark-sweep 1331.8 (1411.9) -> 1336.5 (1411.9) MB, 1440.3 / 0.0 ms [last resort gc].


<--- JS stacktrace --->

==== JS stack trace =========================================

Security context: 0x1a8f0c2cfb39 <JS Object>
1: onwrite(aka onwrite) [/codebuild/output/src237433561/src/node_modules/readable-stream/lib/_stream_writable.js:~440] [pc=0xbec57fd33dc] (this=0x1a8f0c204381 <undefined>,stream=0x1c436ce99581 <an Archiver with map 0x2cf623834091>,er=0x1a8f0c204201 <null>)
2: /* anonymous */(aka /* anonymous */) [/codebuild/output/src237433561/src/node_modules/readable-stream/lib/_stream_writable.js:~16...

FATAL ERROR: CALL_AND_RETRY_LAST Allocation failed - JavaScript heap out of memory
Aborted
```

**Comment by HyperBrain** [comment] 2018-01-30 11:29
Hi @dashmug . Is the issue restricted to CodeBuild or does it happen in other environments too, and which loaders do you use in your project (e.g. TypeScript has some memory issues, where an issue already exists in the webpack repository). If the compile step scatters around in the Node heap, it might leave not enough memory afterwards.

**Comment by dashmug** [comment] 2018-01-30 22:41
@HyperBrain 

I only build my projects through CodeBuild and that's where it happens randomly in around 1 out of 10 builds. I'll try to do some `sls deploys` from my local to see if it happens locally.

I do use Typescript with Webpack so this must be the reason. And this error hasn't happened for me in my non-Typescript Lambdas (though my non-typescript projects are relatively tiny compared to the typescript one).

Could the occurrence of this error increase with the number of Lambdas I have? I started having this failure right after I added a 5th Lambda function (each Lambda is an entry point in Webpack).

Are there known workarounds for this?

**Comment by HyperBrain** [comment] 2018-01-31 11:33
@dashmug You can check the comments in https://github.com/serverless-heaven/serverless-webpack/issues/299. There has been a lengthy discussion of people facing the TypeScript memory problem and I remember there was some workaround that did the job.

**Comment by alonsoir** [comment] 2018-06-01 10:15
Hi, i am getting this exception with the getting-started example:

https://serverless.com/getting-started/

npm@5.0.3 /usr/local/lib/node_modules/npm
MacBook-Pro-Retina-de-Alonso:~ aironman$ npm version
{ npm: '5.0.3',
  ares: '1.10.1-DEV',
  cldr: '30.0.3',
  http_parser: '2.7.0',
  icu: '58.2',
  modules: '57',
  node: '8.1.4',
  openssl: '1.0.2l',
  tz: '2016j',
  unicode: '9.0',
  uv: '1.12.0',
  v8: '5.8.283.41',
  zlib: '1.2.11' }

https://pastebin.com/yb6ZTxjH

**Comment by odykyi** [comment] 2020-02-10 09:37
An update: it works when I set transpileOnly: true for ts-loader.

**Comment by Berger92** [comment] 2020-07-27 13:10
@odykyi where did you set it? Could you show the whole thing please?

**Comment by talaikis** [comment] 2021-07-21 16:16
Mhm..., 32 Gb RAM, out of memory after removing serverlesss-plugin-include-packages.

**Comment by pgrzesik** [comment] 2021-07-21 17:31
Hello @talaikis :wave: Could you share more details about your case? What version of the Framework are you on? Any chance for a reproducible example that consumes a lot of memory? Thanks in advance :bow:
