### ISSUE TITLE
AWS API Gateway stages and names are separated

### ISSUE THREAD

**Issue by mtomic** [serverless/serverless#2445] opened 2016-10-19 00:24 UTC
# This is a (Bug Report)
## Description

I'm not sure if this is by design, but one of the major differences between deploying 0.5.6 serverless functions and v1 is that AWS API Gateway names are prefixed with stage.  AWS recommend creating generic API Gateway names, with multiple stages inside it.  Image below shows how v1 deployment works:
![screen shot 2016-10-19 at 11 05 59 am](https://cloud.githubusercontent.com/assets/1195051/19500916/2d103d9c-95ed-11e6-9575-2e8e72c11f22.png)

0.5.6 version would deploy it within a single API, but have multiple stages inside it.  This feels more correct, see below:
![screen shot 2016-10-19 at 11 16 07 am](https://cloud.githubusercontent.com/assets/1195051/19500960/793dbea6-95ed-11e6-92d6-caa276f3aa48.png)

Is there a way to achieve this structure with v1?

Similarly, Lambda functions aren't versioned and Aliased the way they were in 0.5.6.  Currently all function names are prefixed with a stage, which creates a large number of lambda functions.  Is there a way to achieve function aliasing in the deploy process so that the API gateway references the correctly  aliased function by setting the correct stage Variable like this:
![screen shot 2016-10-19 at 11 20 31 am](https://cloud.githubusercontent.com/assets/1195051/19501118/977958a2-95ee-11e6-9622-a5719c57dffc.png)

![screen shot 2016-10-19 at 11 22 07 am](https://cloud.githubusercontent.com/assets/1195051/19501120/9b1c87b8-95ee-11e6-8787-cad401866c76.png)

**Comment by hereandnow** [comment] 2016-10-20 11:16
I wanted to open excactly the same Issue. APIG has the concept of Stages, we really should use that!

i tried to overwrite the name in the serverless.yml file:

    resources:
     Resources:
       ApiGatewayRestApi:
         Type: AWS::ApiGateway::RestApi
           Properties:
             Name: my-service-name

didnt work. the `cloudformation-template-create-stack.json` created has that name:

    {
      "ApiGatewayRestApi": {
        "Type": "AWS::ApiGateway::RestApi",
        "Properties": {
          "Name": "my-service-name"
        }
      }
    }

the `cloudformation-template-update-stack.json` not ;-(

    {
      "ApiGatewayRestApi": {
        "Type": "AWS::ApiGateway::RestApi",
        "Properties": {
          "Name": "develop-elaine-service"
        }
      }
    }


at least that workaround should do!

**Comment by leonardoalifraco** [comment] 2016-11-01 02:57
This is happening to me to. Is this by design?

**Comment by andymac4182** [comment] 2016-11-01 03:18
This is by design. @leonardoalifraco

**Comment by leonardoalifraco** [comment] 2016-11-01 12:42
Makes sense. Thanks!

**Comment by andymac4182** [comment] 2016-11-02 01:43
@dashmug Is there anything else I can cover to help explain this?

**Comment by dashmug** [comment] 2016-11-02 01:56
@andymac4182 I'm sure you guys have thought this through but it's not very clear to me yet. What's the problem with the way serverless v0.5.6 does it (using API Gateway's "Stages") versus version 1's one-stage, one-gateway approach?

**Comment by 18BEA442** [comment] 2016-11-23 11:07
@hereandnow's workaround works for me in Serverless 1.2.0. Hopefully it's here to stay (?)

**Comment by arabold** [comment] 2016-12-30 14:44
This relates to #2411 in Serverless. I don't think API Gateway stages make sense without having alias support in first place.

**Comment by dncrews** [comment] 2017-02-02 00:21
In regards to #2918 (since that was marked as a duplicate to this), can we at least have the ability to change how the stage's name gets attached to the APIG api? So that I can use

`api-name-${opt:stage}` instead of `${opt:stage}-api-name`, so I end up with

```
sls-auth-development
sls-auth-production
sls-auth-staging
some-other-api-development
some-other-api-production
some-other-api-staging
```

instead of 
```
development-api-one
development-other-api
development-sls-auth
development-some-other-api
production-api-one
production-other-api
etc
```

**Comment by smalltown** [comment] 2017-02-28 07:43
If the stage is for api version, e.g. customized.domain.com/base_path/v1, customized.domain.com/base_path/v2, then it needs to deploy different stages into the same api, or  it can not be achieved...

**Comment by pmuens** [comment] 2017-03-23 11:23
Hey everyone! Thanks for the in-depth discussions.

Could you please get into more detail why this feature is necessary / needed?
What are your use-cases? Why is the current approach not appropriate?

**Comment by HyperBrain** [comment] 2017-03-23 11:34
@smalltown To deploy different APIG "stages" to the same API you could utilize the alias plugin. It will allow you, e.g. deploy different branches (v1/v2) of a project independently as APIG stages "v1" or "v2".
Additionally the lambda functions get tagged with aliases, so every APIG stage automatically calls the right version of the lambda (in case you have multiple versions of a lambda). The same works if you have new lambdas or endpoints in your v2 version.
See https://github.com/HyperBrain/serverless-aws-alias. Don't be confused about the "alpha" - I will release a beta as soon as also mandatory advanced functions for a release version (like alias rollback, single function deploy, etc.) are implemented.

**Comment by mtomic** [comment] 2017-03-23 11:39
@pmuens We've since refactored our APIs to be separated by environment/stage so this is no longer an issue for us. As some of the other guys have mentioned, when AWS environments are created under different accounts (the approach we've taken), having API stages combined is no longer needed.

**Comment by pmuens** [comment] 2017-03-23 12:07
Thanks for the response @mtomic 👍

**Comment by hereandnow** [comment] 2017-03-23 12:15
@pmuens: the usecase @HyperBrain describes in his plugin is basically the one we have. it doesnt really have to be branches, it is just our way of working that every developer has his own stage, works on that stage before pushing to the remote develop branch. develop-branch will have its own stage and so on. 

see more here: https://github.com/HyperBrain/serverless-aws-alias#multiple-developers-work-on-different-branches

with the current approach of serverless we can basically do the same, but for every developer it will create a completely new apig environement. we do have a couple of services > 10 running on lambda (and the number of services is increasing), working with 4 developers, and as you can expect it really is getting messy...

**Comment by dncrews** [comment] 2017-03-23 12:25
Our use-case:

We're doing most new development with Serverless. We a dozen or so lambda functions, each with multiple lanes (e.g. dev, stage, prod, test). When one full set has to be worked with, it's a real pain to have to have to figure out what all lanes is in and then scan the list for 4-5 lambdas that "should be there". Organizationally, it would be easier for us to order them by project name first, then lane, but renaming them doesn't exist or work.

I know everyone else is talking about APIG stages (and I'm asking for the ability to rename APIG APIs), but the real issue I'm having was marked as a duplicate of this one.

**Comment by arabold** [comment] 2017-03-23 12:36
I really think that the [serverless-alias plugin](https://github.com/HyperBrain/serverless-aws-alias) solves the original problem description as well as the follow up comments in a very elegant way without forcing developers to use it if they do want to keep a strict separation as the original Serverless implementation provides. 

If you want to have all "stages" (dev, stage, prod, test) be represented in a single Lambda function and a single API Gateway endpoint, then simply use "aliases" instead. So you would only have a single stage, e.g. name it something like "default" or just keep it as "dev", and use `serverless deploy --alias=dev` and `serverless deploy --alias=prod` in future (without discussing if this is a good or a bad architectural decision). This will work very similar to how Serverless 0.5 operated.

In fact, I think the alias plugin works so well it should become a standard feature of Serverless ;)

**Comment by eric-tucker** [comment] 2017-04-26 11:56
Having the ability to at least name the API Gateway objects `api-name-${opt:stage}` instead of `${opt:stage}-api-name` would be greatly appreciated.  If I have multiple APIs in the same account, I don't want all the dev ones grouped together in the console.  I want to see all of the different environments for API 1 followed by all the environments for API 2.

**Comment by iddrew** [comment] 2017-09-27 14:14
Agreed with @et304383 . Do we have the ability to name APi Gateway objects as api-name-${opt:stage} instead of ${opt:stage}-api-name ? At the moment my AWS account is full of API-Gateways starting with v1, v1, v1 which is a bit insane. thanks

**Comment by brianmanifold** [comment] 2017-09-29 02:43
@et304383 @iddrew 

We have been naming our API Gateway objects as api-name-${stage} using this:

```
custom:
  stage: "${opt:stage, self:provider.stage}"

resources:
  Resources:
    ApiGatewayRestApi:
      Type: AWS::ApiGateway::RestApi
      Properties:
        Name: ${self:service}-${self:custom.stage}
```

Also follow similar convention for the lambda IAM roles - got to have those consoles sorted properly!

No idea if this is the best way to do this, found this solution in some blog post ages ago and haven't revisited it.

**Comment by celicoo** [comment] 2018-03-13 20:08
Is this going anywhere? It's really weird to have several APIs for each stage, and actually seems wrong since API Gateway has feature to achieve that without creating multiple apis...

In my case I'm using Go, and I'm separating in services, example:

```
| extractions/
| - serverless.yml
| exports/
| - serverless.yml
| etc...
```

I think that's better since I'm using Go.... and because of that, the API Gateway looks like a hell, I have two environments for each service.... if I have 10 services, I have 20 APIs to take care... :(.

**Comment by gandhik** [comment] 2018-04-18 21:16
I agree with you @celicoo - duplicating all our lambda definitions for each stage seems to be a big waste.   I am looking into using stage variables to reference lambda aliases in stead.  So each stage refs a lambda alias in stead of the lambda, that way only the alias is duplicated.

**Comment by gerryburtenshaw** [comment] 2018-04-20 15:15
I tried the alias plugin way back when but it seemed to have a limitation in the Lambda/endpoint definition (according to my notes..). Haven't looked in a while and just ended up living with it as is.

```
#plugins:
# Experimented with Alias plugin - Didn't work because the API Gateway Endpoint was hardcoded by Serverless.
# Needed something that considered the "stage" context/variable to execute the lambda function {function:stage}
#  - serverless-aws-alias
```

**Comment by adjavaherian** [comment] 2018-04-25 15:40
I guess this is by design, huh?  So is Serverless suggesting the APIG stages should just not be used in favor of multiple gateways and stacks?

**Comment by HyperBrain** [comment] 2018-04-25 15:49
@adjavaherian Yes, that's the design - and the reason for the serverless-aws-alias plugin that exactly adds that functionality (and a complete code separation, not only for the API stages).

**Comment by adjavaherian** [comment] 2018-04-26 20:54
@HyperBrain can you please point us to some examples of how to use aws-alias plugin to create one APIG and stack with multiple stages?

**Comment by dashmug** [comment] 2018-04-26 21:17
@adjavaherian LGTFY https://github.com/HyperBrain/serverless-aws-alias-example

**Comment by gabe-villarreal** [comment] 2018-10-02 19:07
https://serverless.com/framework/docs/providers/aws/events/apigateway#share-api-gateway-and-api-resources

Documentation should probably be updated to better reflect the workarounds mentioned here to accomplish a true shared APIG. The documentation makes it seem likes its possible with vanilla SLS which after trying to do so, is not the case :/

**Comment by michelem09** [comment] 2020-03-19 09:29
So we are on 2020 and this issue is still open, is there a way to have every stages under the same API?
Thanks

**Comment by cldsnchz** [comment] 2020-05-30 14:47
Sorry if this is off-topic but I guess it is somehow related.

Currently the provider stage is also used to configure the APIG stage name
Is there any way to customize the APIG stage name?, something like having:
```
provider:
  apiGateway:
    stageName: xxxxxxxxxx
```
I would like to configure the stages dev, test, etc but all of them with v1 as APIG stage name, but I haven't found a way to do that.

**Comment by tomaszdudek7** [comment] 2020-08-03 14:28
@michelem09 Duh, we're closer to 2021 now.

@cldsnchz (How) did you solve it? It has been a few months. :)

**Comment by medikoo** [comment] 2020-08-19 16:18
Closing, for reasons listed here: https://github.com/serverless/serverless/issues/2445#issuecomment-257479953

Still I believe _stage_ and_service_ tokens order in API name is indeed confusing, and doesn't seem right (not sure why it was decided to have `{stage}-{service}` instead of `{service}-{stage}` as in all other cases) for that issue please track https://github.com/serverless/serverless/issues/2918

**Closed by medikoo** 2020-08-19 16:18 UTC
Labels: cat/aws-event-api-gateway

**Comment by caligo-erik** [comment] 2020-10-02 13:32
> @et304383 @iddrew
> 
> We have been naming our API Gateway objects as api-name-${stage} using this:
> 
> ```
> custom:
>   stage: "${opt:stage, self:provider.stage}"
> 
> resources:
>   Resources:
>     ApiGatewayRestApi:
>       Type: AWS::ApiGateway::RestApi
>       Properties:
>         Name: ${self:service}-${self:custom.stage}
> ```
> 
> Also follow similar convention for the lambda IAM roles - got to have those consoles sorted properly!
> 
> No idea if this is the best way to do this, found this solution in some blog post ages ago and haven't revisited it.

This solves my problem perfectly! 

Since I'm using custom domain names, and the basepath for versions/stages, it looks like this:
api.domain.com/v1
and 
api.domain.com/v2

Without your suggested modification, each stage would be uploaded as a separate gateway, and the custom domain DNS entry would work only for the first version / api gateway.

Great, thanks!

**Comment by sc0ttdav3y** [comment] 2021-04-28 05:08
For those coming to this ticket in 2021 looking for answers, it looks like V3 of serverless will implement API gateway naming as `${service}-${stage}` as many have asked for. You can adopt this now with a config setting.

See https://www.serverless.com/framework/docs/deprecations/#PROVIDER_IAM_SETTINGS

**Comment by medikoo** [comment] 2021-04-28 07:46
> it looks like V3 of serverless will implement API gateway naming as ${service}-${stage} as many have asked for. You can adopt this now with a config setting.

We actually decided to revert from that, as migration from already deployed API gateway requires API to be removed and re-created, and also we'd rather push users to migrate to HTTP API instead. Still the setting will remain working.

Reference: https://github.com/serverless/serverless/pull/9160#issuecomment-805608103

**Comment by sc0ttdav3y** [comment] 2021-04-28 08:52
Thanks for the response @medikoo.

I’m only 1 week in as a serverless dev, so here are my take-aways:

- The `shouldStartNameWithService` setting works, will still be supported and gives me a consistent name that doesn’t grate my type-A personality :tada:
- It’s not the preferred way to do it though.
- There is a new `httpAPI` 

I didn’t know about `httpAPI` — all the getting started recipes and tutorials I’ve come across talk about `http`.

Thanks again for following up.
