### ISSUE TITLE
Stream permissions

### ISSUE THREAD

**Issue by evheniy** [serverless/serverless#7018] opened 2019-11-27 08:04 UTC
If I have more than 1 dynamodb stream per serverless.yml each function has permissions for all streams:

````
functions:
  test1:
    handler: test1.handler
    tags:
      type: test
    events:
      - stream: "arn:aws:dynamodb:${self:provider.region}:${self:custom.accountId}:table/test1/stream/timestamp"

  test2:
    handler: test2.handler
    tags:
      type: test
    events:
      - stream: "arn:aws:dynamodb:${self:provider.region}:${self:custom.accountId}:table/test2/stream/timestamp"
````
And results in aws console:

````
Lambda -> Functions -> test1

Resource: Actions

arn:aws:dynamodb:region:accountId:table/test1/stream/timestamp:
Allow: dynamodb:GetRecords
Allow: dynamodb:GetShardIterator
Allow: dynamodb:DescribeStream
Allow: dynamodb:ListStreams

arn:aws:dynamodb:region:accountId:table/test2/stream/timestamp:
Allow: dynamodb:GetRecords
Allow: dynamodb:GetShardIterator
Allow: dynamodb:DescribeStream
Allow: dynamodb:ListStreams

````

Each function should have only own permissions. It's a good practice. 
success Installed "serverless@1.58.0" with binaries...

**Comment by medikoo** [comment] 2019-11-27 12:10
@evheniy thanks for report. Currently Framework setups access with one IAM role that's used for all lambdas.

We know there's a demand to make it more fine grain, so each function can have different access rules. See https://github.com/serverless/serverless/issues/4313 We look forward to provide that, but delivery date is uncertain.

I'm going to close this as duplicate of https://github.com/serverless/serverless/issues/4313

**Closed** 2019-11-27 12:11 UTC
Labels: duplicate
