### ISSUE TITLE
Use stage as parameter when building package

### ISSUE THREAD

**Issue by dmeiser** [serverless/serverless#8435] opened 2020-10-23 15:49 UTC
### Use case description

I want to use serverless to deploy to non-production accounts, but then build a production package to be deployed multiple times, sometimes in the same account and region.

Currently, the CloudFormation template has stage name hard coded into multiple places, including LogGroupName and FunctionName. This prevents me from deploying the production package without doing string substitution on the CF template prior to deployment.

### Proposed solution

Move stage name to a parameter. Give the parameter the default value of the stage. For example:

`"LogGroupName": "/aws/lambda/project_name-prod-function_name"`
becomes
`{ "Fn::Sub": "/aws/lambda/project_name-${StageName}-function_name" }`

And Parameters would look like:
```javascript
  "Parameters": {
    "StageName": {
      "Type": "String",
      "Description": "The stage name to use for the deployment",
      "Default": "prod"
    }
  }
```

**Comment by dmeiser** [comment] 2020-10-23 19:27
I just wanted to clarify how this is slightly different from other bugs and feature requests. My intent is to treat the CloudFormation template as an artifact.  There are (at least) 2 ways the current CloudFormation prevents Same Region - Same Account loading:

1. FunctionName would be reused,
1. LogGroupName would be reused.

**Comment by medikoo** [comment] 2020-10-28 11:10
Duplicate of https://github.com/serverless/serverless/issues/3528

**Closed by medikoo** 2020-10-28 11:10 UTC
Labels: duplicate
