### ISSUE TITLE
Allow to escape variables format

### ISSUE THREAD

**Issue by 0ptional** [serverless/serverless#8116] opened 2020-08-21 13:52 UTC
Source of a reported issue was that `"${StepFunctionArn}"` in CF template was attempted to be resolved by our variable resolver, when it was unexpected.

_Proposed solution:_

We probably should support escaping such case, so "\${StepFunctionArn}" will not invoke variable resolver but just strip leading slash.

--- 

_Original report_:

Using custom variableSyntax, serverless can't resolve variable value if it contains another variable:

<details>
<summary><code>serverless.yml</code></summary>

```yaml
service: test

provider:
  name: aws
  stage: dev
  variableSyntax: "\\${((env|self|opt|file|cf|s3)[:\\(][ :a-zA-Z0-9._,\\-\\/\\(\\)]*?)}"
  environment:
    VAR: ${self:custom.bucketName}
  
custom:
  bucketName: mytest-bucket-${self:provider.stage}
```

</details>

<details>
<summary><b><code>sls package</code> .serverless/serverless-stage.json</b></summary>

Custom variable `bucketName` gets correctly resolved to `mytest-bucket-dev`. But environment variable in `provider` gets resolved to `${deep:0}`. See `serverless-stage.json`:
```
{
  "service": {
    "service": "test",
    "serviceObject": {
      "name": "test"
    },
    "provider": {
      "stage": "dev",
      "variableSyntax": "\\${((env|self|opt|file|cf|s3)[:\\(][ :a-zA-Z0-9._,\\-\\/\\(\\)]*?)}",
      "name": "aws",
      "environment": {
        "VAR": "${deep:0}"
      },
      "region": "us-east-1",
      "versionFunctions": true,
      "compiledCloudFormationTemplate": {
        "AWSTemplateFormatVersion": "2010-09-09",
        "Description": "The AWS CloudFormation template for this Serverless application",
        "Resources": {
          "ServerlessDeploymentBucket": {
            "Type": "AWS::S3::Bucket",
            "Properties": {
              "BucketEncryption": {
                "ServerSideEncryptionConfiguration": [
                  {
                    "ServerSideEncryptionByDefault": {
                      "SSEAlgorithm": "AES256"
                    }
                  }
                ]
              }
            }
          },
          "ServerlessDeploymentBucketPolicy": {
            "Type": "AWS::S3::BucketPolicy",
            "Properties": {
              "Bucket": {
                "Ref": "ServerlessDeploymentBucket"
              },
              "PolicyDocument": {
                "Statement": [
                  {
                    "Action": "s3:*",
                    "Effect": "Deny",
                    "Principal": "*",
                    "Resource": [
                      {
                        "Fn::Join": [
                          "",
                          [
                            "arn:",
                            {
                              "Ref": "AWS::Partition"
                            },
                            ":s3:::",
                            {
                              "Ref": "ServerlessDeploymentBucket"
                            },
                            "/*"
                          ]
                        ]
                      }
                    ],
                    "Condition": {
                      "Bool": {
                        "aws:SecureTransport": false
                      }
                    }
                  }
                ]
              }
            }
          }
        },
        "Outputs": {
          "ServerlessDeploymentBucketName": {
            "Value": {
              "Ref": "ServerlessDeploymentBucket"
            }
          }
        }
      },
      "coreCloudFormationTemplate": {
        "AWSTemplateFormatVersion": "2010-09-09",
        "Description": "The AWS CloudFormation template for this Serverless application",
        "Resources": {
          "ServerlessDeploymentBucket": {
            "Type": "AWS::S3::Bucket",
            "Properties": {
              "BucketEncryption": {
                "ServerSideEncryptionConfiguration": [
                  {
                    "ServerSideEncryptionByDefault": {
                      "SSEAlgorithm": "AES256"
                    }
                  }
                ]
              }
            }
          },
          "ServerlessDeploymentBucketPolicy": {
            "Type": "AWS::S3::BucketPolicy",
            "Properties": {
              "Bucket": {
                "Ref": "ServerlessDeploymentBucket"
              },
              "PolicyDocument": {
                "Statement": [
                  {
                    "Action": "s3:*",
                    "Effect": "Deny",
                    "Principal": "*",
                    "Resource": [
                      {
                        "Fn::Join": [
                          "",
                          [
                            "arn:",
                            {
                              "Ref": "AWS::Partition"
                            },
                            ":s3:::",
                            {
                              "Ref": "ServerlessDeploymentBucket"
                            },
                            "/*"
                          ]
                        ]
                      }
                    ],
                    "Condition": {
                      "Bool": {
                        "aws:SecureTransport": false
                      }
                    }
                  }
                ]
              }
            }
          }
        },
        "Outputs": {
          "ServerlessDeploymentBucketName": {
            "Value": {
              "Ref": "ServerlessDeploymentBucket"
            }
          }
        }
      }
    },
    "custom": {
      "bucketName": "mytest-bucket-dev"
    },
    "pluginsData": {},
    "functions": {},
    "configValidationMode": "warn",
    "serviceFilename": "serverless.yml",
    "layers": {},
    "initialServerlessConfig": {
      "service": {
        "$ref": "$[\"service\"][\"serviceObject\"]"
      },
      "provider": {
        "$ref": "$[\"service\"][\"provider\"]"
      },
      "custom": {
        "$ref": "$[\"service\"][\"custom\"]"
      },
      "functions": {
        "$ref": "$[\"service\"][\"functions\"]"
      },
      "package": {
        "artifactDirectoryName": "serverless/test/dev/1598020300313-2020-08-21T14:31:40.313Z"
      },
      "layers": {
        "$ref": "$[\"service\"][\"layers\"]"
      },
      "configValidationMode": "warn"
    },
    "isDashboardMonitoringPreconfigured": false
  },
  "package": {
    "artifactDirectoryName": "serverless/test/dev/1598020300313-2020-08-21T14:31:40.313Z",
    "artifact": ""
  }
}
```

</details>

<b>Installed version</b>

```
Framework Core: 1.79.0
Plugin: 3.7.1
SDK: 2.3.1
Components: 2.34.6
```

**Comment by medikoo** [comment] 2020-09-23 12:13
Closing in favor of #3184, which is about same thing and has already involved discussion

**Comment by medikoo** [comment] 2020-09-23 12:13
Duplicate of #3184

**Closed by medikoo** 2020-09-23 12:13 UTC
Labels: bug/design, cat/variable, needs feedback
