### ISSUE TITLE
How to deploy a single function without deploying other functions on the api using serverless framework

### ISSUE THREAD

**Issue by Erandakuruneru** [serverless/serverless#4269] opened 2017-09-15 11:00 UTC
The function "get-relationships" you want to update is not yet deployed. Please run "serverless deploy" to deploy your service. After that you can re
deploy your services functions with the "serverless deploy function" command.

  Get Support --------------------------------------------
     Docs:          docs.serverless.com
     Bugs:          github.com/serverless/serverless/issues
     Forums:        forum.serverless.com
     Chat:          gitter.im/serverless/serverless

  Your Environment Information -----------------------------
     OS:                     win32
     Node Version:           8.4.0
     Serverless Version:     1.22.0

**Comment by HyperBrain** [comment] 2017-09-15 11:10
@Erandakuruneru That's not possible, as `deploy function` only deploys the new function code to an existing function. With Serverless your service including all functions is controlled by CloudFormation and the CloudFormation stack is set up, when you do a `serverless deploy`.

The `deploy function` mechanism is only a lightweight metod to just upload a function's code and replace it within AWS Lambda. But, special care has to be taken and `deploy function` should not be used for production deployments, because the deployed function code is completely outside of CloudFormation control. Whenever CF decides to to a stack update, rollback or correction, your code will be lost and reverted to the last full deployment -> The deployed CF template is not changed by deploying a single function that way!

In general, `deploy function` is currently a debug helper, to get functions deployed quickly without the need to deploy the whole service. In production environments this should never be used, because you'll end up with deployments uncontrolled by CF which is most likely not what you want on production.

**Comment by Erandakuruneru** [comment] 2017-09-15 11:19
Is there any way we can deploy the single function in service. Because we have special requirement to deploy new function rather than deploying all the functions to the service

**Comment by wenderjean** [comment] 2017-09-15 12:22
@Erandakuruneru You can perform a `sls deploy function yourfunctionname` but the point is, you can only do that after an initial full deploy.

**Comment by pmuens** [comment] 2017-09-15 14:22
Thanks for opening @Erandakuruneru and thanks for the comments @HyperBrain and @wenderjean 👍

Yes, that's correct. The Serverless Framework AWS integration is based upon CloudFormation so you need to have a stack with functions in place to update functions via direct code pushes to Lambda (the `Serverless deploy function` command pushed the code and config update directly to Lambda via the AWS SDK without going through CloudFormation).

I hope that helps.

Closing this one since using this w/o an initial deploy is currently not possible.

**Closed by pmuens** 2017-09-15 14:22 UTC
Labels: kind/question, status/help-wanted

**Comment by dfloresgonz** [comment] 2018-05-31 16:08
I have three functions function1, function2 and functionUtil both function1 and 2 call funcitonUtil is there a way to change functionUtil and the change to take effect on both function1 and 2 without having to deploy function1 and 2 each one by one?

**Comment by mrdulin** [comment] 2019-04-01 10:30
same issue. How to deploy a single cloud function in GCP?

`sls deploy -f <functionName>` does not work.

**Comment by yogesh-mhaskule404** [comment] 2019-08-14 07:08
@Erandakuruneru Do you get any solution for this issue?

**Comment by Erandakuruneru** [comment] 2019-08-15 09:29
Still could not find the solution,
now we are deploying the multiples functions,which functions are related to the one module.

**Comment by nikhilbhalwankar** [comment] 2019-09-13 09:09
Facing the same issue. I have 10 lambda functions under serverless. If I update one more lambda function in serverless.yml, all 11 functions are to be deployed. Very time consuming.

**Comment by exoego** [comment] 2019-09-13 09:14
Updating single function is already possible if provider is AWS, so this issue had been closed.

If you need same feature in other providers, I think opening a separate issue is good since we can track issue per

**Comment by yogesh-mhaskule404** [comment] 2019-09-13 09:20
@nikhilbhalwankar You can achieve using this by create separate .yaml file for each function. While deploying specific function, you can pass this  respective .yaml file of function to the command "sls deploy function -f <function_name> --config <'.yaml file path'>"

**Comment by nikhilbhalwankar** [comment] 2019-09-13 09:55
> @nikhilbhalwankar You can achieve using this by create separate .yaml file for each function. While deploying specific function, you can pass this respective .yaml file of function to the command "sls deploy function -f <function_name> --config <'.yaml file path'>"

Thanks for this. Very helpful. However, I have custom authorizer for every function. How can I handle such case?

**Comment by yogesh-mhaskule404** [comment] 2019-09-13 10:39
@nikhilbhalwankar The custom authorizer is lambda function or normal python function, if it's normal function then you don't require to make it is lambda as well as .yaml file. You can just import this function in your lambda function file for your purpose.

**Comment by stevematdavies** [comment] 2020-11-09 11:28
I can confirm sls deploy -f <functionName> does not work on 2,8.0, it ends up deploying all functions even when an initial deploy has been done

**Comment by Satyam8891** [comment] 2023-05-05 10:15
Maybe I am doing something wrong because while deploying python lambda, it zip all the code and deployed for all the lambdas.
Example- let's suppose I have 3 lambda **A**, **B** and **C**. first time I have to deploy all together that's fine but when I check on aws console then every lambda has all the code that means **A** has handler functions those are specific for b and c lambda..
even for each lambda I have separate file
