### ISSUE TITLE
Issue with serverless deploy with version 1.75.0

### ISSUE THREAD

**Issue by MyMaloks** [serverless/serverless#7952] opened 2020-07-16 14:25 UTC
The command `serverless deploy` no more deploy the template after version 1.74.1.

<details>
<summary><code>serverless.yml</code></summary>

```yaml
# ⚠️⚠️ REPLACE THIS COMMENT WITH FULL serverless.yml CONTENT
```

</details>

<details>
<summary><b><code>serverless deploy -v</code> output</b></summary>

```
[2020-07-16T10:15:58.393Z] + serverless deploy -v
[2020-07-16T10:16:00.928Z] Framework Core: 1.75.0
[2020-07-16T10:16:00.928Z] Plugin: 3.6.16
[2020-07-16T10:16:00.928Z] SDK: 2.3.1
[2020-07-16T10:16:00.928Z] Components: 2.32.0
```

</details>

<b>Installed version</b>

```
1.75.0
```

**Comment by medikoo** [comment] 2020-07-16 14:51
Duplicate of #7944

**Closed by medikoo** 2020-07-16 14:51 UTC
