### ISSUE TITLE
Discussion: Use API Gateway Importer

### ISSUE THREAD

**Issue by breandr** [serverless/serverless#963] opened 2016-04-07 04:13 UTC
Yesterday, API Gateway launched their official API Importer that utilises Swagger 2.0. One advantage to using this importer is it will keep your API in sync. My experience so far is that serverless will not remove resources/methods/etc. if you delete them from your `s-function.json` and then deploy all. If instead we built up a swagger file and imported using that, we would not only be able to keep our APIs in sync with serverless, but also generate docs based on Swagger (and whatever other benefits that may come from having a Swagger file). Finally, I believe this will greatly simplify the serverless codebase by letting API Gateway do the heavy-lifting.

To achieve deploying individual endpoints, we can build up partial swagger files and use the `merge` mode of the importer. If on the other hand you just want to overwrite everything on API Gateway with what is in your serverless config, simply use the `overwrite` mode. On this note, what are the use-cases for deploying individual endpoints, as opposed to treating your API Gateway config as immutable?

**Comment by ac360** [comment] 2016-04-07 05:13
We expected this and we've planned for it.  Now, we are just waiting to hear what the community wants.

**Comment by HyperBrain** [comment] 2016-04-07 08:17
Currently we use swagger to define our API's and deploy them with the old API Gateway importer, whereas we deploy our functions completely with Serverless. The general problem here is that the lambda names are not strictly bound to Serverless' defined in the `s-function.json`. This currently leads to double efforts and risk.
Additionally we have some endpoints that are defined and deployed with Serverless already - what turned out to be a good solution.

I would expect an implementation to have the possibility to define the API in Swagger format.
To get rid of the synchonization problem we could let the API definition walk the same road as the templates, i.e. you'd have some root API definition (base paths, general Swagger project definitions, etc.) in our project's root directory and can refine the API setup moving further down the directories up to the function definition directories. This would be the 'truth' of the API, i.e. the only official reference that would update/overwrite the API on deploy.
Upon build the merged and complete Swagger API definition file is generated in meta/tmp and then pushed to the API GW.

I set up our build system (with the current Swagger definitions we have) so that our different Swagger files (YAML/JSON) support `json-ref` to link/merge separate files where e.g. models and parameter definitions are included ($ref). It turned out that this works very well for us, as we also generate client SDK's for mobile clients that then map their classes correctly to the models. An approach like this could be used to realize the template like inheritance structure.

I would see the SLS API definitions somehow like this in the future:
```
+--SLS project root
   +-- s-project.json
   +-- s-api.[yaml|json]
   +--My endpoint group
      +-- s-api.[yaml|json]
      +-- My function
         +-- s-function.json
         +-- ...
```

Please comment :-)

**Comment by goncaloneves** [comment] 2016-04-07 10:09
For me the best feature of using Swagger is that we can compile easily to API Docs/Mocks and have synchronization between both, it just works. 
Using Swagger outside AWS environment will make people less reluctant to start building their next project with Serverless/API Gateway too.

Amazon made the move and it will be great for Serverless.

In terms of implementation, I would give option for comforting both cases. One big parent Swagger with all definitions or several files similar to `s-function.json` but with the option to export the compiled version outside `_tmp` folder to a dir of our choice, for the purpose of generating Docs/Mocks.

Very important discussion 👍

**Comment by doapp-ryanp** [comment] 2016-04-07 14:04
My vote is to adopt the use of the Swagger 2.0 open standard throughout serverless and use the new [APIG import](http://docs.aws.amazon.com/apigateway/latest/developerguide/api-gateway-import-api.html) APIs to manage endpoints.  Benefits:

  - Allow for interoperability between AWS and other cloud providers (they will eventually support swagger if they don't already).
  - Will allow the serverless dev community to focus more on other aspects of the product
  -  "free" API docs per @goncaloneves 

As for how serverless implements the use of swagger 2.0:

I think one of the most powerful aspects of sls is the templates and use of overrideable vars that can be injected into the templates.  I think we should leverage swagger's template support (`$ref` etc) and mix in sls's template & multi-level var support.

The way we pull this off, is much like sls does this today for the `s-resources-cf.json`. It in itself is not a valid CloudFormation file - the valid one gets generated by sls.

1. There is a `s-swagger.json` file at the project root, has sls variable support.
1. Each of the `s-function.json`.`endpoints` are swagger 2.0 snippets. They support sls variables and sls templates
1. `sls endpoint deploy` by default uses APIG `merge` (`PUT`).  Has a new option to use overwrite (`POST`) if desired.
1.  The swagger JSON request body to be `PUT|POST`ed will be generated and put into the `_meta/_tmp` dir
1.  A `_meta/resources/swagger-<stage>-<region>.json` file with the **FULL** API will always be created.  This will allow for API doc/mocks and will allow tracking in version control (note: I check in most of `_meta` but thats a diff discussion)

**Comment by breandr** [comment] 2016-04-07 18:23
Keep in mind the migration cost. If serverless 0.x launches with Swagger+Import, and in order to migrate you need to create `s-swagger.json` AND update all your `s-function.json` `endpoints` to a new format... That's significant friction. I think it's worth exploring the possibility of generating Swagger files using the existing format. You are all more experienced with serverless than I, so you may say, "Brett, this is no issue!" - in which case - Great! 

Personally, I have no production serverless projects, so migration is not a concern for me; I also prefer Swagger to define endpoints. :) If migration is an issue, we could probably just add a command to the CLI to transpile the existing format into Swagger and modify the source.

@doapp-ryanp why do you suggest using `merge` by default? As I stated up top, I'm interested in use-cases for deploying individual endpoints as opposed to overwriting your entire configuration. :) (clarification: it's always `PUT` when importing to an existing api, and `POST` to import a new API; the `mode` query string is used to define `merge` or `overwrite`)

**Comment by doapp-ryanp** [comment] 2016-04-07 18:51
@breandr ah good clarification.  I was not aware.  I'm of the same mindset you are. I only want to touch exactly what I'm deploying not the entire API Gateway API stage.

**Comment by doapp-ryanp** [comment] 2016-04-07 18:54
@breandr and re: the migration cost. I feel ya, I had production projects on JAWS, just migrated this week v0.5.  

IMO, earlier in the serverless product lifecycle the better.  I think people using a <v1.0 product realize its still young, and if you show a benefit (my pts above) they should be OK with it.  

I'm a big fan of using open standards over custom (where it makes sense).  swagger is clearly the market leader (which AWS has just confirmed with officially adopting support).

**Comment by breandr** [comment] 2016-04-07 19:44
Sounds like we're of opposite mindsets. ;) I'm interested in why you would want to deploy individual endpoints rather than everything? One benefit of deploying everything (overwrite) is keeping in sync (eg. I delete an endpoint in my `s-function.json` or modify something via the console, but serverless doesn't know about it). IMO, serverless should be the single source of truth, and any external modifications should be destroyed.

**Comment by doapp-ryanp** [comment] 2016-04-07 21:28
@breandr when in a production environment you don't want to touch things you are not working on - sort of the 'not broken dont fix it' mentality...

If I'm working on `GET /users` and has been running for months `POST /payment`, when I go to deploy `GET /users` I don't want anything touching my `/payment` enpoints. 

Few (of many reasons) why you don't want to touch things ur not working on:
*  Imagine there was some bug introduced in your config/template accidentally when you were working on `GET /users` that applied to all endpoints
*  during the APIG update it craps out updating endpoint 10 out of 250.  They dont have transaction/rollback support
*  speed.  We have 250 endpoints, I have to run update logic to 249 to update just one.  More time executing the more time your code is in limbo as well.

**Comment by breandr** [comment] 2016-04-07 21:53
Better it breaks now, than breaking when you deploy `/payments` next month and you have no idea why. ;) It sounds like there's a more fundamental issue to be resolved here - why are you so concerned about things randomly breaking? Is there something else that can be added/changed in serverless to improve this?

Points 2 and 3 are valid, but do not apply to the new import functionality - do you agree?

Thanks.

**Comment by HyperBrain** [comment] 2016-04-07 22:25
@breandr @doapp-ryanp I think there are the two ideologies that propose, the "update all" and the "update partially" paradigms. Each of them has its pros and cons and can discussed endlessly. Our users will see the framework from their point of view, no matter which one they live.
So we should find solutions for the following problems to have the framework not dictate the use but support the users:

(1) Support of partial updates via function endpoints
(2) Support of full updates
(3) Support of snchronization of APIG console changes

If we manage to find solutions for exactly these problems, then we have passed our goal.

**Comment by breandr** [comment] 2016-04-07 22:54
@HyperBrain Right, we should support as many use cases as possible, but serverless should probably have an opinion on best practices (which informs docs, tutorials, defaults, etc.). Mostly I'm concerned about the comment about the possibility of random things breaking. Is this a common feeling amongst serverless users? If so, let's start a new thread to discuss.

**Comment by doapp-ryanp** [comment] 2016-04-08 13:44
@breandr pts 2 and 3 apply if the strategy is to always update all.  It will be an endless task to enumerate everything that could go wrong - but the fact is the more that is done, the more that could go wrong. IMO the best practice is don't touch resources that are already working in the field.  If you don't touch there is close to 0 chance something breaks. If you do touch its > 0.

**Comment by breandr** [comment] 2016-04-08 17:31
@doapp-ryanp let's talk about this in a separate thread (https://github.com/serverless/serverless/issues/973) so we don't rathole on this specific point, and the discussion can continue around the larger implementation details. As I mentioned, I think it's an important discussion to inform best practices, docs, defaults, etc. I'm interested to know why 2 and 3 still apply since import is very fast and will fail and not modify anything if it encounters errors. Mostly interested in point 1.

**Comment by JamieCressey** [comment] 2016-04-13 20:24
+1 for Serverless building Swagger spec's based on excerpts from s-project/s-function.json files.

We have an ever growing Serverless project, which multiple users contribute to. In our use case, it makes sense for changes to be as isolated as possible.

**Comment by doapp-ryanp** [comment] 2016-04-20 15:40
Some data points pertinent to this discussion:

- I have a swagger file that consists of roughly 400 methods (1/2 of them are OPTIONS methods).  File is `1.1M`
- `aws apigateway put-rest-api --mode overwrite` takes about 30 seconds to complete. Some of this is my slow 5 megabit upload.
- deploying the API to a stage takes about 30 seconds as well
- I have requested a feature for [catch all CORS](https://forums.aws.amazon.com/thread.jspa?threadID=229732&tstart=0)
- I have [requested a feature to support the full swagger 2.0 spec](https://forums.aws.amazon.com/thread.jspa?threadID=229230&tstart=25), specifically [response objects](http://swagger.io/specification/#responsesObject) not supporting Reference Objects.

Some non-pertinent but nice to know info:

- APIG does [not sort the resources in the APIG console UI](https://forums.aws.amazon.com/thread.jspa?threadID=222384&tstart=0). This gets nasty when you have lots of resources/methods
- APIG console UI preforms slower, but useable when you get to this level of resources/methods

**Comment by HyperBrain** [comment] 2016-04-20 17:35
I think it would also be good to follow the hierarchical approach found everywhere in Serverless, i.e. not handling one big Swagger file in the project, but have Swagger snippets, that will be compiled to the resulting upload at build/deploy time. Especially for handling models this is a must as it is much easier to maintain. There may be complex model references (model->model) and the build must make sure that on the API side the same model is used throughout all its used, otherwise the mobile SDKs would be messed up.

**Comment by flomotlik** [comment] 2016-05-12 12:36
We've discussed this quite extensively recently and our current thoughts are that we're going to use Cloudformation instead of swagger for deploying endpoints. The main reason is that cloudformation is deeply integrated into many other services on AWS so we could deliver everything at once.

I do think we should have some way of supporting swagger as well, I don't know how yet though.

**Closed** 2016-08-05 08:46 UTC
Labels: discussion

**Comment by davidjnelson** [comment] 2016-08-11 20:14
Swagger would be awesome.  A good point raised here is the issue of non atomic endpoint deployment, ie: the use case where aws chokes when deploying endpoint 10 of 250.  Not sure if there's an issue for that, I'll do a search.  The simplest fix seems to be using one graphql endpoint for all data, and one one server side rendering endpoint for all presentation.  2 endpoints is easier to manage manual rollbacks for than 250+.  Doesn't work for many existing apps though.

**Comment by flomotlik** [comment] 2016-08-15 12:33
> A good point raised here is the issue of non atomic endpoint deployment, ie: the use case where aws chokes when deploying endpoint 10 of 250

I'm not sure if this should still be a problem with CloudFormation. Basically CF should take care of deploying the whole set of services, if its not possible to do it it will simply fail the whole deployment and revert.
