### ISSUE TITLE
bug report: EMFILE: too many open file (Too many files)

### ISSUE THREAD

**Issue by AnthonyWC** [serverless/serverless#5075] opened 2018-06-25 20:01 UTC
## Description

There are similar issues here:
https://github.com/serverless/serverless/issues/3249
https://github.com/serverless/serverless/issues/4266

In my case, I had a serverless.yml that had multiple lambdas and each has their npm dependency.
My workaround was to separate out those lambda into individual serverless deployment, which ultimately worked.

I suspect serverless doesn't do any sort of maximum file check before deploying to package/deploy the deployment file?  Not sure if that error is actually from NPM (https://github.com/npm/npm/issues/3433) as it looks like they have an open issue going way back to 2013(!) 

What was more worrying was that I had 2 separate build environment that was dockerized; the issue was resolved in dev by deleting some unneeded files in package.json but persisted in my prod environment (which is very odd for docker..).

## Additional Data

```
docker exec -it $(basename $(pwd)) serverless package
--
  | Serverless: Packaging service...
  | Serverless: Excluding development dependencies...
  | Serverless: Excluding development dependencies...
  |  
  | Error --------------------------------------------------
  |  
  | EMFILE: too many open files, scandir '/app/src/lambda-functions/retrieve-objects'
  |  
  | For debugging logs, run again after setting the "SLS_DEBUG=*" environment variable.
  |  
  | Get Support --------------------------------------------
  | Docs:          docs.serverless.com
  | Bugs:          github.com/serverless/serverless/issues
  | Issues:        forum.serverless.com
  |  
  | Your Environment Information -----------------------------
  | OS:                     linux
  | Node Version:           8.11.3
  | Serverless Version:     1.27.3

```

Things to rule out: ulimit on the host was increased to >10000 and container is running alpine with also >10000 ulimit.

**Comment by mkondel** [comment] 2018-07-13 17:22
Setting this to false gets me past the 'too many files' error. I have been using it with ```true``` for many weeks. I already had ulimit at 'unlimited' and this: ```fs.inotify.max_user_watches = 68222222```. Deploying was working fine today, until it stopped with this error.
 ```yaml
package:
  individually: false
```

**Comment by 1jkunz1** [comment] 2018-09-17 17:05
I am attempting to run both sls deploy & sls package via jenkins and have run into the same issue. It works fine locally, but on my jenkins server (AMI / Linux) I get the following error:

  Error --------------------------------------------------
 
  EMFILE: too many open files, scandir '/mnt/vol-02915b57741ce0793/builds/workspace/ena-Ops-Multibranch_develop-PZV62BV2RISCJBAYUHJL67QKTYOTAXCNMGDHI6ERL5QAAU6VRW6Q/.coverage'
 
     For debugging logs, run again after setting the "SLS_DEBUG=*" environment variable.
 
  Get Support --------------------------------------------
     Docs:          docs.serverless.com
     Bugs:          github.com/serverless/serverless/issues
     Issues:        forum.serverless.com
 
  Your Environment Information -----------------------------
     OS:                     linux
     Node Version:           8.12.0
     Serverless Version:     1.32.0



I have tried a variety of things (increase ulimit) - no luck so far. I have an API that contains 10-12 Lambda functions and need them to be packaged and deployed individually, so unfortunately setting 'package individually = false' does not work.

**Comment by pmuens** [comment] 2019-01-18 11:01
Thanks for opening @AnthonyWC 👍

Yes, this really looks like a duplicate of https://github.com/serverless/serverless/issues/4266 so I'll close this for now. Feel free to continue the discussion here.

**Closed by pmuens** 2019-01-18 11:01 UTC
Labels: bug

**Comment by carlosfer02** [comment] 2021-10-22 00:52
I am getting 

> EMFILE: too many open files

. I am using windows with `serverless@2.64.1`
Setting 
```
package:
 individually: false
```

Makes no difference

**Comment by fsobh** [comment] 2021-12-21 20:25
> @carlosfer02 Actually, Upgrading node from `v14.15.4` to `v14.18.1` appears to help significantly...

This didn't make a difference

**Comment by superern** [comment] 2022-01-05 11:35
> > Setting 'individually' to false gets me past the 'too many files' error. I have been using it with `true` for many weeks. I already had ulimit at 'unlimited' and this: `fs.inotify.max_user_watches = 68222222`. Deploying was working fine today, until it stopped with this error.
> > ```yaml
> > package:
> >  individually: false
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > Earler today I added the 'request' module to one of my existing lambdas.
> 
> It's the best answer!

this works for me too.

**Comment by tuannpa** [comment] 2022-01-14 04:45
> im running latest serverless serverless@2.64.1 on windows 10 pro and nodejsv 14.18.1 still constantly getting this error no matter what i do. it randomly once in a while after i try enough will get past, but for the most part fails this too many files open error.
> 
> even setting that individually: false | true has zero affect for me. this is super frustrating.
> 
> UPDATE: had several back to back subsequent success deployments in a row after applying this monkeypatch from https://stackoverflow.com/a/38099737
> 
> I basically patched the real fs module within my serverless global install. wherever your global serverless is installed to just head to that dir and into \node_modules\serverless\node_modules\fs.realpath\index.js
> 
> at the top was
> 
> ```
> var fs = require('fs')
> var origRealpath = fs.realpath
> var origRealpathSync = fs.realpathSync
> ```
> 
> and is now
> 
> ```
> var fs = require('fs')
> var gracefulFs = require('graceful-fs')
> gracefulFs.gracefulify(fs)
> var origRealpath = fs.realpath
> var origRealpathSync = fs.realpathSync
> ```

Thanks mate :) This solution actually fixes the issue.

**Comment by mnavon** [comment] 2022-01-17 21:48
> > im running latest serverless serverless@2.64.1 on windows 10 pro and nodejsv 14.18.1 still constantly getting this error no matter what i do. it randomly once in a while after i try enough will get past, but for the most part fails this too many files open error.
> > even setting that individually: false | true has zero affect for me. this is super frustrating.
> > UPDATE: had several back to back subsequent success deployments in a row after applying this monkeypatch from https://stackoverflow.com/a/38099737
> > I basically patched the real fs module within my serverless global install. wherever your global serverless is installed to just head to that dir and into \node_modules\serverless\node_modules\fs.realpath\index.js
> > at the top was
> > ```
> > var fs = require('fs')
> > var origRealpath = fs.realpath
> > var origRealpathSync = fs.realpathSync
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > and is now
> > ```
> > var fs = require('fs')
> > var gracefulFs = require('graceful-fs')
> > gracefulFs.gracefulify(fs)
> > var origRealpath = fs.realpath
> > var origRealpathSync = fs.realpathSync
> > ```
> 
> Thanks mate :) This solution actually fixes the issue.

Me two, I think this bug should reopened
PC Windows 10
serverless: 2.71.0
node 16.13.2
