### ISSUE TITLE
Add support for AWS x-ray on AWS API Gateway

### ISSUE THREAD

**Issue by mikeblakeney** [serverless/serverless#5564] opened 2018-12-05 14:24 UTC
# This is a Feature Proposal

## Description
Adding support for enabling tracing on an API Gateway would help enrich the information returned when using API Gateway with lambdas leveraging X-ray.  Particularly because when enabling tracing through the CloudFormation template it is done on the API Gateway Deployment object which is not easy to override due to the random string appended to the object name by the serverless framework.  

One particular useful gain with using x-ray with API Gateway is that it resolves issues of x-ray returning successes when API Gateway fails but a lambda responding to the gateway event doesn't.  This happens in instances when the lambda may return a malformed response to the Gateway.

Additionally, as a side note, using X-ray with lambdas and serverless could be done by overriding the function with the appropriate configuration for x-ray.  This could be a work around until x-ray is supported in serverless.

Enabling X-ray for gateway would be done with a `stageDescription` object 
```
stageDescription:
   tracingEnabled: boolean
```
The idea is to allow for extending the `stageDescription` with additional properties in future pull requests.
  
References:
* API Gateway Deployment CFT Spec: https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-apigateway-deployment.html
* API Gateway Stage Description CFT Spec: https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-apigateway-deployment-stagedescription.html

Similar or dependent issues:
* Support for x-ray with Lambdas #3495, PR #3742 
* Different proposal for adding stage description in stage property: #5400

**Comment by jaikdean** [comment] 2018-12-19 13:09
This would be brilliant to have.

**Comment by dschep** [comment] 2018-12-19 22:03
Duplicate of #3495

**Comment by mikeblakeney** [comment] 2018-12-20 11:16
@dschep how is this a duplicate of #3495 ?   AWS Lambda and Gateway are two distinct services that offer X-ray support

**Comment by dschep** [comment] 2018-12-20 14:12
Doh. Sorry. misread the issue titles.

**Comment by mikeblakeney** [comment] 2018-12-21 11:36
no problem.  thank you for re-opening the issue.

**Comment by softprops** [comment] 2019-02-21 14:47
still trying to figure the best approach for this in https://github.com/serverless/serverless/pull/5692

**Closed** 2019-04-15 10:26 UTC
Labels: cat/api-gw, feature
