### ISSUE TITLE
Function zip files using `artifact` overwrite each other in ServerlessDeploymentBucket

### ISSUE THREAD

**Issue by mariusmarais** [serverless/serverless#2837] opened 2016-12-01 13:51 UTC
# This is a Bug Report

## Description
Given the `serverless.yml`:
```yaml
...
package:
  individually: true

functions:
  thing1:
     ...
     package:
       artifact: thing1/dist/package.zip

  thing2:
     ...
     package:
       artifact: thing2/dist/package.zip
```

Serverless uploads the zip files to `${ServerlessDeploymentBucketName}/${stage}/xxx/` without changing the filenames, causing all defined functions to run the code from the last-uploaded `package.zip`. Hilarity ensues.

* What went wrong?
    Last-uploaded function package overwrites other functions' packages, causing all functions to run the same code
* What did you expect should have happened?
    Filenames in the S3 bucket should be replaced / prepended with the function name or otherwise uniqueified.
* What was the config you used?
    See above.
* What stacktrace or error message from your provider did you see?
    None.

## Workaround
Rather use a `serverless.yml` like:
```yaml
...
package:
  individually: true

functions:
  thing1:
     ...
     package:
       artifact: thing1/dist/package1.zip

  thing2:
     ...
     package:
       artifact: thing2/dist/package2.zip
```

But this is error-prone and slightly cumbersome with a standardized function build process.

## Additional Data

* ***Serverless Framework Version you're using***: 1.2.1
* ***Operating System***: OSX 10.12.1 (Sierra)
* ***Stack Trace***: None
* ***Provider Error messages***: None

**Comment by pmuens** [comment] 2016-12-13 09:22
Thanks for reporting @mariusmarais!

That's actually a good catch. Not sure if we should change this behavior since it's something the user controls / takes care of. We should definitely document that somehow.

I move this to the v2.0 milestone since changing this behavior might be a breaking change.

**Comment by mariusmarais** [comment] 2016-12-13 09:34
I don't think this should be a breaking change, since the user isn't in control of what happens inside the ServerlessDeploymentBucket, as that's all handled internally.

Either way, we're working around it at the moment 😄

**Comment by pmuens** [comment] 2016-12-13 09:49
Yes.

The way it works right now is that Serverless will .zip up the service (or the functions) in a zip file with e.g. the name of the service. This file is stored in the `.serverless` directory and then uploaded to S3. We could update the code so that the zip file gets e.g. the timestamp attached.

The problem is that other users might rely on this deployment artifact if they e.g. use other plugins together with Serverless or have an automation which will pick the zip file and does something with it.

Renaming it would break those uses cases.

BTW thanks for providing a workaround. You might also want to consider the recently introduced JavaScript support for Serverless variables. This way you could e.g. generate the name of your zip file more granular --> https://serverless.com/framework/docs/providers/aws/guide/variables#reference-variables-in-javascript-files

**Comment by pmuens** [comment] 2017-05-19 14:36
Closing this for now since we've pushed lots of changes to the packaging in the past. Furthermore it seems to be more like expected behavior.

**Closed by pmuens** 2017-05-19 14:36 UTC
Labels: kind/bug

**Comment by vectorjohn** [comment] 2022-09-30 22:59
It is crazy not expected behavior for Serverless to silently choose one of my packages to discard and use a different one if the artifact happens to have the same basename. Anybody who actually ran into this issue, if their application even works, would not be getting any meaningful behavior. 
Maybe the initial problem wasn't explained well, or maybe I'm misunderstanding, but this is not correct behavior if it is what it sounds like.
This page makes no mention of this behavior where an undefined one of your packages "wins" if you have artifacts with the same basename:
https://www.serverless.com/framework/docs/providers/aws/guide/packaging#artifact
