### ISSUE TITLE
Service with Step Function Fails Deployment for v2.28.1

### ISSUE THREAD

**Issue by tquintans** [serverless/serverless#9049] opened 2021-03-02 19:38 UTC
Services with Step Function is failing to build with a vague error:
```

Serverless Error ---------------------------------------
--
90 |  
91 | Invalid variable reference syntax for variable . You can only reference env vars, options, & files. You can check our docs for more info.
92 |  
93 | Get Support --------------------------------------------
94 | Docs:          docs.serverless.com
95 | Bugs:          github.com/serverless/serverless/issues
96 | Issues:        forum.serverless.com
97 |  
98 | Your Environment Information ---------------------------
99 | Operating System:          linux
100 | Node Version:              12.16.1
101 | Framework Version:         2.28.1
102 | Plugin Version:            4.4.3
103 | SDK Version:               2.3.2
104 | Components Version:        3.7.1
105 |  

```

No code changes were made just using the latest version. When forced to install with `v2.28.0`, deployment ran successfully. 

Plugin used for step function in serverless.yml: `"serverless-step-functions": "^2.26.0"`

**Comment by medikoo** [comment] 2021-03-02 19:42
@tquintans thanks for report. Can you post full content of `serverless.yml` with sensitive content masked out?

**Comment by medikoo** [comment] 2021-03-02 21:16
@tquintans we've fixed one critical issue with just released v2.28.2. Please check whether that fixed the issue on your side.

If it's not the case, then we need more information from your side. Especially what are the variable references in the configuration, as due to introduced new variables resolver, it's were eventual (unexpected) change in processing might have happened

**Comment by abbassnass** [comment] 2021-03-02 22:52
same issue here! 
![image](https://user-images.githubusercontent.com/79102593/109726045-52e3fb80-7bb2-11eb-9d3a-fa27c31d3f69.png)

**Comment by vtr-rivia** [comment] 2021-03-02 23:28
Same issue here, running on Serverless Dashboard
<img width="1059" alt="image" src="https://user-images.githubusercontent.com/67164852/109728916-d80ce780-7b95-11eb-89c9-2de3fc593823.png">

**Comment by medikoo** [comment] 2021-03-03 07:42
@abbassnass @vtr-rivia Can you provide a `servelress.yml` content (with sensitive content masked out), Without that I'm not able to diagnose anything.

Also Ideally if you prepare a new bug reports, while you receive similar error it doesn't mean it's caused by very same issue, and we have no details from @tquintans either to be able to tell what is the issue on its side.

**Comment by abbassnass** [comment] 2021-03-03 08:03
Hello! Thanks for your help! Thats my serverless.yml file:

service: SrvWWDashboard

frameworkVersion: "^2.1.0" # >=2.1.0 && <3.0.0

package:
  individually: true
  exclude:
    - artifacts/**

provider:
  name: aws
  runtime: python3.8
  stage: ${opt:stage,'dev'}
  region: ${opt:region, 'eu-central-1'}
  versionFunctions: true
  logRetentionInDays: 90 # Set the default RetentionInDays for a CloudWatch LogGroup
  tracing:
    lambda: true
  iamRoleStatements:
    - Effect: "Allow"
      Action: [ "ssm:Describe*",
                "ssm:Get*",
                "ssm:List*" ]
      Resource: "*"
    - Effect: "Allow"
      Action:
        - "xray:PutTraceSegments"
        - "xray:PutTelemetryRecords"
      Resource: "*"
    - Effect: "Allow"
      Action:
        - redshift-data:*
      Resource: "*"
    - Effect: "Allow"
      Action:
        - secretsmanager:GetSecretValue
      Resource: "arn:aws:secretsmanager:eu-central-1:227956463654:secret:/redshift/masteruser/credentials-yyNJKc"
    - Effect: "Allow"
      Action:
        - s3:*
      Resource: [ "arn:aws:s3:::msc-lambda-config",
                    "arn:aws:s3:::msc-lambda-config/*" ]

  deploymentBucket:
    name: mediascale-serverless-deployments-bucket # Deployment bucket name.
    maxPreviousDeploymentArtifacts: 10 # On every deployment the framework prunes the bucket to remove artifacts older than this limit.
    blockPublicAccess: true # Prevents public access via ACLs or bucket policies.
  stackTags:
    PROJECT: "weight-watchers"
    LAMBDA-PURPOSE: "data-transformation"
    CONNECTED-TO-EXTERNAL-APIS: "true"
    TRIGGER: "cloudwatch-scheduled-event"
    RUN-FREQUENCY: "daily"
    USE-LAYERS: "true"

resources:
  Mappings:
    ################### PIPELINE CONFIG PHASE PARAMETERS #########################
    entryPointParameters:
      dev:
        bucket: 'msc-lambda-config'
        object: 'ww-dashboard/dev/state_machine_config.json'
      prod:
        bucket: 'msc-lambda-config'
        object: 'ww-dashboard/prod/state_machine_config.json'

  # Custom Cloudformation resources
  Resources:
    wwDashboardStateMachineLogGroup:
      Type: AWS::Logs::LogGroup
      Properties:
        RetentionInDays: 90 # keep CW logs for 3 months
        LogGroupName: "/step-functions/ww-dashboard-${opt:stage,'dev'}"

stepFunctions:
  validate: true # enable pre-deployment definition validation (disabled by default)
  stateMachines:
    wwDashboardStateMachine:
      alarms:
        topics:
          alarm: arn:aws:sns:eu-central-1:227956463654:step-functions-data-pipelines-alarms-notifications
        metrics:
          - executionsTimedOut
          - executionsFailed
          - executionsAborted
          - executionThrottled
        treatMissingData: missing
      tracingConfig:
        enabled: true
      loggingConfig:
        level: ERROR
        includeExecutionData: true
        destinations:
          - Fn::GetAtt: [ wwDashboardStateMachineLogGroup, Arn ]
      events:
        - schedule:
            description: 'WW dashboard scheduled event'
            rate: cron(0 6 * * ? *) # Run every day at 8am (belgium time)
      name: "weight-watchers-dashboard-${opt:stage,'dev'}"

      definition:
        Comment: "The WW dashboard state machine definition"
        StartAt: EntryPointState
        States:
          ################### PIPELINE CONFIG PHASE STATE #########################
          EntryPointState:
            Type: Task
            Retry:
              - ErrorEquals:
                  - Lambda.SdkClientException
                  - Lambda.AWSLambdaException
                  - Lambda.ServiceException
                IntervalSeconds: 2
                MaxAttempts: 6
                BackoffRate: 2
            Resource:
              Fn::GetAtt: [ EntryPoint, Arn ]
            Next: BuildStagingTablesState

          ################### STAGING TABLES BUILD STATE #########################

          BuildStagingTablesState:
            Type: Task
            InputPath: "$.config.states.build_staging_tables_state"
            ResultPath: "$.results.states.build_staging_tables_state"
            Retry:
              - ErrorEquals:
                  - Lambda.SdkClientException
                  - Lambda.AWSLambdaException
                  - Lambda.ServiceException
                IntervalSeconds: 2
                MaxAttempts: 6
                BackoffRate: 2
            Resource:
              Fn::GetAtt: [ RedshiftAsynchExec, Arn ]
            Next: Wait1MinStagingState

          ################### WAIT 1 MINUTE STATE #########################
          Wait1MinStagingState:
            Type: Wait
            Seconds: 60
            Next: StagingTablesExecutionValidationState

          ###################  STAGING TABLES BUILD QUERIES EXECUTION VALIDATION STATE #########################
          StagingTablesExecutionValidationState:
            Type: Task
            InputPath: "$.results.states.build_staging_tables_state"
            ResultPath: "$.results.states.build_staging_tables_state"
            Retry:
              - ErrorEquals:
                  - Lambda.SdkClientException
                  - Lambda.AWSLambdaException
                  - Lambda.ServiceException
                IntervalSeconds: 2
                MaxAttempts: 6
                BackoffRate: 2
              - ErrorEquals:
                  - AsynchronousQueriesValidationInProgressException
                IntervalSeconds: 10
                MaxAttempts: 6
                BackoffRate: 4
            Resource:
              Fn::GetAtt: [ RedshiftAsynchReport, Arn ]
            Next: BuildDashboardTablesState

          ################### DASHBOARD TABLES BUILD STATE #########################
          BuildDashboardTablesState:
            Type: Task
            InputPath: "$.config.states.build_dashboard_tables_state"
            ResultPath: "$.results.states.build_dashboard_tables_state"
            Retry:
              - ErrorEquals:
                  - Lambda.SdkClientException
                  - Lambda.AWSLambdaException
                  - Lambda.ServiceException
                IntervalSeconds: 2
                MaxAttempts: 6
                BackoffRate: 2
            Resource:
              Fn::GetAtt: [ RedshiftAsynchExec, Arn ]
            Next: Wait3MinuteDashboardState

          ################### WAIT 1 MINUTE DASH STATE #########################
          Wait3MinuteDashboardState:
            Type: Wait
            Seconds: 180
            Next: DashboardQueriesExecutionValidationState

          ################### DASHBOARD QUERIES EXECUTION VALIDATION STATE #########################
          DashboardQueriesExecutionValidationState:
            Type: Task
            InputPath: "$.results.states.build_dashboard_tables_state"
            ResultPath: "$.results.states.build_dashboard_tables_state"
            OutputPath: "$.results"
            Retry:
              - ErrorEquals:
                  - Lambda.SdkClientException
                  - Lambda.AWSLambdaException
                  - Lambda.ServiceException
                IntervalSeconds: 2
                MaxAttempts: 6
                BackoffRate: 2
              - ErrorEquals:
                  - AsynchronousQueriesValidationInProgressException
                IntervalSeconds: 10
                MaxAttempts: 6
                BackoffRate: 4
            Resource:
              Fn::GetAtt: [ RedshiftAsynchReport, Arn ]
            End: True

functions:
  EntryPoint:
    module: entry-point
    handler: handler.run
    environment:
      LOG_LEVEL: INFO
      S3_CONFIG_BUCKET: !FindInMap [ entryPointParameters, '${self:provider.stage}', bucket ]
      S3_CONFIG_KEY: !FindInMap [ entryPointParameters, '${self:provider.stage}', object ]
    timeout: 60
    memorySize: 128
    layers:
      - arn:aws:lambda:eu-central-1:770693421928:layer:Klayers-python38-aws-lambda-powertools:56

  RedshiftAsynchExec:
    module: asynch-redshift-modules/asynch-redshift-exec
    handler: handler.run
    environment:
      LOG_LEVEL: INFO
    timeout: 60
    memorySize: 256
    layers:
      - arn:aws:lambda:eu-central-1:770693421928:layer:Klayers-python38-aws-lambda-powertools:56
      - arn:aws:lambda:eu-central-1:770693421928:layer:Klayers-python38-boto3:56

  RedshiftAsynchReport:
    module: asynch-redshift-modules/asynch-redshift-report
    handler: handler.run
    environment:
      LOG_LEVEL: INFO
    timeout: 60
    memorySize: 256
    layers:
      - arn:aws:lambda:eu-central-1:770693421928:layer:Klayers-python38-aws-lambda-powertools:56
      - arn:aws:lambda:eu-central-1:770693421928:layer:Klayers-python38-boto3:56

plugins:
  - serverless-python-requirements
  - serverless-step-functions
custom:
  pythonRequirements:
    dockerizePip: non-linux

**Comment by medikoo** [comment] 2021-03-03 08:08
@abbassnass great thanks! Is there a chance you can fix formatting in this comment? Ideally if all `serverless.yml` content is put between markdown yaml formatting brackets as bellow

````
```yaml
service: SrvWWDashboard

frameworkVersion: "^2.1.0" # >=2.1.0 && <3.0.0

...
```
````

And that proper indentation is respected, currently it's hard to read how properties are indented in above comment

**Comment by abbassnass** [comment] 2021-03-03 08:11
Done! Thanks!

**Comment by medikoo** [comment] 2021-03-03 08:39
@abbassnass great thanks. Still unfortunately that configuration doesn't reproduce any issue for me.

I've prepared a repository (it also has versioned dependencies) here: https://github.com/medikoo/test-serverless/tree/issue-9049 with exactly same config as you provided above and e.g. `sls print` works without any issues (and variables resolver which triggers the error that you see, is also run with this command).

Can you confirm that you see same error with `sls print` and eventually update the configuration above, so error is reproduced?

**Comment by abbassnass** [comment] 2021-03-03 09:50
This is the only error log I receive upon testing with sls print.
```


simple-git deprecation notice: git.silent: logging should be configured using the `debug` library / `DEBUG` environment variable, this will be an error in version 3
Serverless: Deprecation warning: Starting with next major version, default value of provider.lambdaHashingVersion will be equal to "20201221"
            More Info: https://www.serverless.com/framework/docs/deprecations/#LAMBDA_HASHING_VERSION_V2

```
![Screenshot 2021-03-03 at 10 47 08](https://user-images.githubusercontent.com/79102593/109786923-f9111f00-7c0d-11eb-9b23-075d221c0902.png)

**Comment by medikoo** [comment] 2021-03-03 09:54
@abbassnass Ok I got it reproduced with `sls package`.. looking into it

**Comment by vtr-rivia** [comment] 2021-03-03 10:08
This is my serverless.yml content

`frameworkVersion: '2'
org: vtroliveira
app: hsm
service: bi-ebradi
configValidationMode: off

provider:
  name: aws
  runtime: nodejs12.x
  versionFunctions: false
  stage: ${opt:stage, 'dev'}
  logRetentionInDays: 1

plugins:
  - serverless-plugin-optimize
  - serverless-pseudo-parameters
  - serverless-iam-roles-per-function
  - serverless-step-functions

package:
  individually: true

custom:
  DataMigrationStateMachineArn: "arn:aws:states:#{AWS::Region}:#{AWS::AccountId}:stateMachine:${self:provider.stage}-data-migration"

functions:
  - ${file(ymls/steps.yml)}
  - ${file(ymls/triggers.yml)}

resources:
  - ${file(ymls/resources.yml)}
  - ${file(ymls/outputs.yml)}

stepFunctions:
  stateMachines: 
    DataMigration: ${file(ymls/dataMigrationSteps.yml)}`

**Comment by medikoo** [comment] 2021-03-03 11:08
Thanks for all the information, issue is specific to `serverless-step-functions` usage, and will be fixed shortly with https://github.com/serverless/serverless/pull/9060

**Comment by abbassnass** [comment] 2021-03-03 11:16
Amazing! Thanks a lot and keep up the great work!

**Closed** 2021-03-03 12:09 UTC
Labels: bug, cat/plugin, cat/variable
