### ISSUE TITLE
Duplicate Export naming error for exported ServerlessDeploymentBucket value

### ISSUE THREAD

**Issue by cameroncf** [serverless/serverless#9365] opened 2021-04-24 18:49 UTC
Exported value ServerlessDeploymentBucket is not specific enough. Namely, it does not include the app name, which causes errors when two different apps have a service with the same name in the same AWS account. 

[Permalink of offending code](https://github.com/serverless/serverless/blob/31a51e21396dba8ca4ad4d22c023a8a63960a40c/lib/plugins/aws/package/lib/addExportNameForOutputs.js#L9). Tagging @js-cha as comitter for this change two days ago.

Note: 
`sls-${this.serverless.service.service}-${this.provider.getStage()}-${key}` should probably be `sls-${this.serverless.service.app}-${this.serverless.service.service}-${this.provider.getStage()}-${key}` so that it's specific enough to avoid this problem.

<details>
<summary><code>app-one-serverless.yml</code></summary>

```yaml
org: myorg
app : app-one
service: foo
```

</details>

<details>
<summary><code>app-one-serverless.yml</code></summary>

```yaml
org: myorg
app : app-two
service: foo
```

</details>

<details>
<summary><b><code>sls deploy</code> output</b></summary>

```
An error occurred: app-two-foo-stagename-stack - Export with name sls-foo-stagename-ServerlessDeploymentBucketName is already exported by stack app-one-foo-stagename-stack
```

</details>

<b>Installed version</b>

```
Framework Core: 2.38.0
Plugin: 4.5.3
SDK: 4.2.2
Components: 3.9.0
```

**Comment by cameroncf** [comment] 2021-04-24 18:52
Linking to PR: https://github.com/serverless/serverless/pull/9313

**Comment by cameroncf** [comment] 2021-04-24 18:59
I can confirm that reverting to serverless@2.37.2 resolves the error.

**Comment by pgrzesik** [comment] 2021-04-25 18:08
Thanks for reporting - it looks like a duplicate of an issue here: https://github.com/serverless/serverless/issues/9361 

I'm closing this one and let's continue discussion in the linked thread

**Closed by pgrzesik** 2021-04-25 18:08 UTC
