### ISSUE TITLE
Exception adding requirements for Pillow

### ISSUE THREAD

**Issue by yuvarajgopal** [serverless/serverless#7123] opened 2019-12-20 15:47 UTC
Serverless: Installing required Python packages for runtime python2.7...
 
 Exception -----------------------------------------------
 
  <Buffer 64 6f 63 6b 65 72 3a 20 43 61 6e 6e 6f 74 20 63 6f 6e 6e 65 63 74 20 74 6f 20 74 68 65 20 44 6f 63 6b 65 72 20 64 61 65 6d 6f 6e 20 61 74 20 75 6e 69 ... 82 more bytes>

plugins:
  - serverless-python-requirements

cat requirements.txt 
Pillow

If i remove the dependencies i dont see this error. Its failing on running sls deploy -v

**Comment by medikoo** [comment] 2019-12-20 15:54
Duplicate of #7084

**Closed by medikoo** 2019-12-20 15:54 UTC
Labels: duplicate

**Comment by yuvarajgopal** [comment] 2019-12-20 17:52
i get ride of the error by upgrading nodejs, now im getting different error

when i test the lamda.



START RequestId: d808fdcd-022b-4fba-8079-79ef0aad0263 Version: $LATEST

Unable to import module 'handler': No module named handler



END RequestId: d808fdcd-022b-4fba-8079-79ef0aad0263

REPORT RequestId: d808fdcd-022b-4fba-8079-79ef0aad0263	Duration: 0.40 ms	Billed Duration: 100 ms	Memory Size: 128 MB	Max Memory Used: 43 MB



YG
Add reply

**Comment by medikoo** [comment] 2019-12-23 07:45
> Unable to import module 'handler': No module named handler

This looks as an error in your lambda configuration
