### ISSUE TITLE
Cron scheduled syntax is rejected

### ISSUE THREAD

**Issue by chris-hailstorm** [serverless/serverless#2344] opened 2016-10-12 17:06 UTC
Maybe a bug in the service, maybe a doco bug, I can't tell --
1. Using this serverless.yml:

```
service: xxxxxxxx

provider:
    name: aws
    runtime: python2.7
    stage: prod
    region: us-east-1

package:
    exclude:
        - __vendored-**

functions:
    run:
        handler: handler.run
        timeout: 20
        events:
            - schedule:
                cron: cron(5 8 * * ? *)
                enabled: false
```

Produces this error:
  Serverless Error ---------------------------------------

```
 Missing "rate" property for schedule event in function
 run The correct syntax is: schedule: rate(10 minutes)
 OR an object with "rate" property. Please check the
 docs for more info.
```

The documentation at https://serverless.com/framework/docs/providers/aws/events/schedule/ suggests this events / schedule / cron syntax would be OK.
1.  Single-line variation (with no enabled field):

```
service: xxxxxxxx

provider:
    name: aws
    runtime: python2.7
    stage: prod
    region: us-east-1

package:
    exclude:
        - __vendored-**

functions:
    run:
        handler: handler.run
        timeout: 250
        events:
            - schedule: cron(5 8 * * ? *)
```

This variation works fine.

**Comment by rowanu** [comment] 2016-10-12 23:42
Yep, this is a bug bug. It's an issue with [the schedule object check](https://github.com/serverless/serverless/blob/master/lib/plugins/aws/deploy/compile/events/schedule/index.js#L29).

I will submit a fix.

**Comment by rowanu** [comment] 2016-10-13 00:35
Upon closer inspection, this is **not a bug** 😕 Probably just needs some better examples in the docs using the cron syntax.

Change your `cron` property name in your schedule event to `rate` and it will work i.e.:

```yaml
...
        events:
            - schedule:
                rate: cron(5 8 * * ? *)
                enabled: false
```

**Comment by chris-hailstorm** [comment] 2016-10-16 17:12
Confirmed

**Comment by chris-hailstorm** [comment] 2016-11-07 07:27
Now using Serverless v1.1.0, this cron syntax is failing:

```
    funcname:
        events:
            - schedule:
                rate: cron(0 5 * * * ?)
```

with this error message:

```
Serverless: Deployment failed!
 
  Serverless Error ---------------------------------------
 
     An error occurred while provisioning your stack: SenderEventsRuleSchedule1
     - Parameter ScheduleExpression is not valid..
```

The `rate: rate(5 minutes)` syntax is working, but the cron-ized version version.

**Comment by rowanu** [comment] 2016-11-07 09:20
You cannot have a "?" in the year (last) field (as per [the docs](http://docs.aws.amazon.com/AmazonCloudWatch/latest/events/ScheduledEvents.html)).

I think you mean to use:

```
rate: cron(0 5 * * ? *)
```

**Comment by pmuens** [comment] 2016-11-18 07:09
Closing this one as @rowanu provided a solution 👍 

Let us know if this is still an issue!

**Closed by pmuens** 2016-11-18 07:09 UTC

**Comment by veerarajuthuta** [comment] 2021-07-19 06:28
schedule rate "cron" not yet supported!
scheduler: invalid, schedule syntax
Scheduling [pullDataFromQueue] cron: [undefined] input: undefined

**Comment by pgrzesik** [comment] 2021-07-19 07:17
Hello @veerarajuthuta - could you please share full details about your problem? It would be great to include reproducible example as well as the full output with the error.

**Comment by milkstork-kevin** [comment] 2022-04-14 19:25
The error "scheduler: invalid, schedule syntax" is coming from the `serverless-offline` package and it seems to be due to the fact that scheduling isn't supported by the package right now.

**Comment by RavenHursT** [comment] 2022-08-03 04:26
```yml
events:
    - schedule: rate(10 minutes)
```

works just fine for `serverless-offline`... So it's just `rate: cron([whatever])` that isn't supported?

Is this documented anywhere?

**Comment by mnapoli** [comment] 2022-08-04 09:52
@RavenHursT you can open an issue in the plugin's repository.

**Comment by RavenHursT** [comment] 2022-08-04 21:49
@mnapoli So... I take it that's a "no"?

**Comment by mnapoli** [comment] 2022-08-05 08:20
@RavenHursT that is an issue with the plugin. I don't know if it's documented in the plugin or not, but in any case this should be discussed there.

I don't think pinging people on an unrelated issue from 2016 will yield changes on the plugin.

**Comment by RavenHursT** [comment] 2022-08-05 10:12
@mnapoli my mistake.. I was under the impression that `serverless-offline` was a package maintained by the serverless org.

@dherault any change you could shed light onto whether or not this caveat it documented somewhere.

Given that so many devs rely upon `serverless-offline` for local development would it possibly be prudent upon the `serverless` org to ingest `serverless-offline` into their ecosystem?  🤔
