### ISSUE TITLE
Add support for AWS Kinesis enhanced stream consumer for Lambda

### ISSUE THREAD

**Issue by fastfiveoh** [serverless/serverless#5510] opened 2018-11-20 16:43 UTC
# This is a Feature Proposal

## Description

* Provide support for configuring AWS enhanced fan out Kinesis stream consumers for Lambda that was released:

https://aws.amazon.com/about-aws/whats-new/2018/11/aws-lambda-supports-kinesis-data-streams-enhanced-fan-out-and-http2/
https://docs.aws.amazon.com/lambda/latest/dg/with-kinesis.html#services-kinesis-configure

* The configuration takes streams Event Source options:
--Kinesis Stream
--Consumer (this is what needs to be added)
--Batch Size
--Starting Position
--Enabled

Related Serverless Docs:
https://serverless.com/framework/docs/providers/aws/events/streams/

Similar or dependent issues:

**Comment by zaccharles** [comment] 2019-05-22 22:01
I ran in to this today and am interested in raising a PR to prove the experience.

The things I noticed when switching from a shard iterator to a stream consumer were that yes, you can put a stream consumer ARN instead of the stream ARN, but then you have to do two things:

1. Manually create a KinesisStreamConsumer in the resources section (assuming one doesn't already exist).
2. Manually add the iamRoleStatements @bnayalivne listed.

The first problem could be solved by creating a stream consumer resource automatically. 

The second is an issue caused by putting a stream consumer ARN instead of the stream's ARN. Serverless is still creating an IAM policy with `kinesis:GetRecords`, `kinesis:GetShardIterator`, `kinesis:DescribeStream`, and `kinesis:ListStreams`, but it's now allowing those on the stream consumer instead of the stream, which is wrong. On top of that, it doesn't know that it should add a policy allowing `kinesis:SubscribeToShard` on the stream consumer.  

To solve these I think we'd need new event syntax. Right now we basically have something like this, for example:
```yaml
functions:
  hello:
    handler: handler.hello
    events:
      - stream:
          type: kinesis
          arn: arn:aws:kinesis:region:account-id:stream/stream-name
```

That example would create a shard iterator based trigger. To do some nice automation, we need to know both the stream ARN and the consumer ARN, so I suggest we leave that `arn` as the stream ARN, and add a new property: `consumer`.

In the below example, `consumer` is simply set to `true`. This means Serverless should autmatically create a new KinesisStreamConsumer resource.
```yaml
functions:
  hello:
    handler: handler.hello
    events:
      - stream:
          type: kinesis
          arn: arn:aws:kinesis:region:account-id:stream/stream-name
          consumer: true
```

Here's another example, but this time we specify the consumer ARN too:

```yaml
functions:
  hello:
    handler: handler.hello
    events:
      - stream:
          type: kinesis
          arn: arn:aws:kinesis:region:account-id:stream/stream-name
          consumer:
            arn: arn:aws:kinesis:region:account-id:stream/stream-name/consumer/consumer-name
```

The consumer ARN could just go in the `consumer` property, but I'm not sure that's the best approach?

As for the name of the consumer, which is required, it could just be made by convention. It could be overridden using a `name` property under `consumer`, or maybe just by declaring the CF resource and merging it with the automatic one, as is already common.

Thoughts? :)

**Comment by neverendingqs** [comment] 2019-10-13 19:06
@zaccharles - are you still interested in creating that PR?

**Comment by neverendingqs** [comment] 2019-10-13 19:11
Hmmm technically each function can subscribe to multiple fan-out consumers. It might need to be an array of consumers ARNs instead of just one.

**Comment by zaccharles** [comment] 2019-10-15 09:50
>are you still interested in creating that PR?
Yes, still interested. I'm moving to a new apartment this week, so it won't be soon. I'm also happy for someone else to do it if they have more time.

>Hmmm technically each function can subscribe to multiple fan-out consumers. It might need to be an array of consumers ARNs instead of just one.
That's true, but wouldn't you just add another object to the handler's `events` array?

Looking at my last example, the ARN of the stream and consumer is very similar. I wonder if it's worth  allowing a `name` property instead of `arn` and building it based on the stream ARN?

**Comment by neverendingqs** [comment] 2019-10-15 13:49
> I wonder if it's worth allowing a name property instead of arn and building it based on the stream ARN?

It will need region as well if we go that route.

**Comment by zaccharles** [comment] 2019-10-15 13:57
>It will need region as well if we go that route.

Correct me if I'm wrong, but you use [RegisterStreamConsumer](https://docs.aws.amazon.com/kinesis/latest/APIReference/API_RegisterStreamConsumer.html) to create a consumer. That API call takes the stream ARN and a name for the consumer. I don't see how you could end up with a consumer in a different region to the stream? Keeping in mind the region is already in the stream ARN, I don't see the need?

**Comment by neverendingqs** [comment] 2019-10-15 14:29
Right sorry. I confused the two ARNs.

**Comment by zaccharles** [comment] 2019-10-15 14:48
No problem.

I'm not sure I'd actually looked at that API before. But now that I have, it seems like it'd be better to specify a name instead of `true`. Using the [SNS event](https://serverless.com/framework/docs/providers/aws/events/sns/) as inspiration.

Examples:

**Create new consumer**
Generate name
```yaml
- stream:
    type: kinesis
    consumer: true
```
or specify name
```yaml
- stream:
    type: kinesis
    consumer: consumer-name
```

**Use existing consumer**
```yaml
- stream:
    type: kinesis
    arn: arn:aws:kinesis:region:account-id:stream/stream-name
    consumer: arn:aws:kinesis:region:account-id:stream/stream-name/consumer/consumer-name
```
or
```yaml
- stream:
    type: kinesis
    arn: arn:aws:kinesis:region:account-id:stream/stream-name
    consumer:
        arn: arn:aws:kinesis:region:account-id:stream/stream-name/consumer/consumer-name
```

Thoughts?

**Comment by dougmoscrop** [comment] 2019-10-15 15:08
This matches what I did with my plugin: https://github.com/dougmoscrop/serverless-plugin-kinesis-consumer (don't use it - it predates CloudFormation support)

**Comment by zaccharles** [comment] 2019-10-15 15:50
One day I'll have an original idea @dougmoscrop :P That's a good sanity check, though!

**Comment by dougmoscrop** [comment] 2019-10-15 15:53
Ah sorry I didn't mean it like that - yes, sanity check.

**Comment by aat2703** [comment] 2019-11-14 14:29
Any news on this issue?

**Comment by Barhuumi** [comment] 2020-02-10 17:25
Any update?

**Comment by sugarandmagic** [comment] 2020-02-11 12:41
Hoping for an update too 🤞

**Comment by zaccharles** [comment] 2020-02-11 18:24
Thanks for the reminder. I'm working on this right now and will submit a PR soon. 

I've just stumbled upon the fact that you can't just specify the name of an existing consumer. You must provide the full ARN because each time you create a stream consumer it generates a unique ARN that contains a timestamp. Not a big problem.

**Closed** 2020-02-14 00:09 UTC
Labels: cat/event-src, enhancement
