### ISSUE TITLE
AWS: Java lambda not updated after modification

### ISSUE THREAD

**Issue by kaklakariada** [serverless/serverless#1862] opened 2016-08-15 17:40 UTC
##### Serverless Framework Version:
1.0.0-beta.1.1

##### Operating System:
Mac OSX 10.11.6

##### Expected Behavior:
After modifying Java sources and rebuilding the zip file and running `sls deploy` the lambda should be updated with the new version of the Java code.

##### Actual Behavior:
The lambda is only created during the initial deploy. Following deploys don't update the lambda. The new version of the zip is uploaded to s3 but the lambda is not updated.

##### Reproduction:
1. Clone https://github.com/kaklakariada/serverless-java-test
2. Run `gradlew deploy`
3. Run the lambda
4. Modify the handler `src/main/java/hello/Handler.java`
5. Run `gradlew deploy` again
  * ZIP is uploaded to s3
  * CF stack is updated but event log shows that only ApiGateway is updated
  * Last modified timestamp of lambda is not updated
6. Run the lambda again.
  * Old version is still active.

**Comment by flomotlik** [comment] 2016-08-16 02:57
@kaklakariada is Gradle recompiling the code as well as part of your script? Serverless itself wouldn't trigger this rebuild in Gradle. As I don't think this is a Serverless internal issue, but probably some config Issue in the CI/CD pipeline I'm going to close the issue here. 

You can add updates here or jump into our forum at http://forum.serverless.com which is monitored by our team and the community as well for help.

**Comment by kaklakariada** [comment] 2016-08-17 18:42
@flomotlik thank you for your reply!
This is not an issue of the Gradle script. The zip file is rebuilt after code changes and updated on s3. I just verified that the ETag on s3 changes.

I guess CF is not smart enough to check that the file content has changed. A possible solution could be to append a timestamp to the filename when uploading the zip. This way CF will detect the change and update the lambda.

**Comment by flomotlik** [comment] 2016-08-18 09:09
CF should automatically pick up the file that was uploaded to S3. There is no specific intelligence built into it there so it will pick up that latest version. Can you install the latest master with `npm install serverless/serverless` and after `serverless deploy` a zip file should be created in the `.serverless` folder. Can you check this file for content and that it is correctly changed. My assumption is still that for some reason the zip isn't correctly updated and therefore doesn't get deployed.

**Comment by kaklakariada** [comment] 2016-08-18 16:22
See https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-lambda-function-code.html

> To update a Lambda function whose source code is in an S3 bucket, you must trigger an update by updating the S3Bucket, S3Key, or S3ObjectVersion property. Updating the source code alone doesn't update the function.

**Comment by flomotlik** [comment] 2016-08-19 09:52
@kaklakariada sorry forgot to update this issue. You're completely right, this is a bug in Serverless. When setting the artefact in packaging/artefact we're simply using its name when uploading to S3. The problem is then CF doesn't change so the deployment doesn't update. This will be fixed soon. Thank you for reporting this!

**Comment by pmuens** [comment] 2016-08-22 09:03
Fixed with https://github.com/serverless/serverless/pull/1906

**Closed by pmuens** 2016-08-22 09:03 UTC
Labels: bug
