### ISSUE TITLE
Failed to Build Docker image (Exit Code 1)

### ISSUE THREAD

**Issue by 50l3r** [serverless/serverless#7794] opened 2020-05-29 15:22 UTC
I have a problem deploying in local mode in a Windows 10 x64

`serverless invoke local -f init`

```
Serverless: Load command interactiveCli
Serverless: Load command config
Serverless: Load command config:credentials
Serverless: Load command create
Serverless: Load command install
Serverless: Load command package
Serverless: Load command deploy
Serverless: Load command deploy:function
Serverless: Load command deploy:list
Serverless: Load command deploy:list:functions
Serverless: Load command invoke
Serverless: Load command invoke:local
Serverless: Load command info
Serverless: Load command logs
Serverless: Load command metrics
Serverless: Load command print
Serverless: Load command remove
Serverless: Load command rollback
Serverless: Load command rollback:function
Serverless: Load command slstats
Serverless: Load command plugin
Serverless: Load command plugin
Serverless: Load command plugin:install
Serverless: Load command plugin
Serverless: Load command plugin:uninstall
Serverless: Load command plugin
Serverless: Load command plugin:list
Serverless: Load command plugin
Serverless: Load command plugin:search
Serverless: Load command config
Serverless: Load command config:credentials
Serverless: Load command rollback
Serverless: Load command rollback:function
Serverless: Load command upgrade
Serverless: Load command uninstall
Serverless: Load command login
Serverless: Load command logout
Serverless: Load command generate-event
Serverless: Load command test
Serverless: Load command dashboard
Serverless: Load command output
Serverless: Load command output:get
Serverless: Load command output:list
Serverless: Load command param
Serverless: Load command param:get
Serverless: Load command param:list
Serverless: Load command studio
Serverless: Load command dev
Serverless: Invoke invoke:local
Serverless: Invoke package
Serverless: Invoke aws:common:validate
Serverless: Invoke aws:common:cleanupTempDir
Serverless: Packaging service...
Serverless: Excluding development dependencies...
Serverless: Invoke aws:package:finalize
Serverless: Invoke aws:common:moveArtifactsToPackage
Serverless: Writing Dockerfile...
Serverless: Building Docker image...
Sending build context to Docker daemon  122.4MB
Step 1/2 : FROM lambci/lambda:provided
 ---> 81c66411cd01
Step 2/2 : ADD --chown=sbx_user1051:495 .serverless\layers\php-73-fpm\25 /opt
ADD failed: stat /var/lib/docker/tmp/docker-builder527297806/.serverlesslayersphp-73-fpm25: no such file or directory
 
  Error --------------------------------------------------

  Error: Failed to build docker image (exit code 1})
      at C:\Users\50l3r\AppData\Roaming\npm\node_modules\serverless\lib\plugins\aws\invokeLocal\index.js:380:23
      at runMicrotasks (<anonymous>)
      at processTicksAndRejections (internal/process/task_queues.js:97:5)
  From previous event:
      at processImmediate (internal/timers.js:456:21)
      at process.topLevelDomainCallback (domain.js:137:15)
  From previous event:
      at C:\Users\50l3r\AppData\Roaming\npm\node_modules\serverless\lib\plugins\aws\invokeLocal\index.js:363:12
      at runMicrotasks (<anonymous>)
      at processTicksAndRejections (internal/process/task_queues.js:97:5)
```

**Environment Information**

- Operating System:          win32
- Node Version:              12.16.3
- Framework Version:         1.71.3
- Plugin Version:            3.6.12
- SDK Version:               2.3.1
- Components Version:        2.30.11

**Comment by medikoo** [comment] 2020-06-01 11:17
@50l3r please respect all issue template remarks and answer all its questions

**Comment by leogono** [comment] 2020-07-14 06:21
I have the same error. Trying out bref. This line of code stands out: ```ADD failed: stat /var/lib/docker/tmp/docker-builder527297806/.serverlesslayersphp-73-fpm25: no such file or directory```

Serverless.yml is as follows: 
```
service: app

provider:
  name: aws
  region: us-east-1
  runtime: provided

plugins:
  - ./vendor/bref/bref

functions:
  myFunction:
    handler: index.php
    description: ""
    layers:
      - ${bref:layer.php-73}

# Exclude files from deployment
package:
  exclude:
    - "tests/**"
```

**Comment by leogono** [comment] 2020-07-14 07:04
I just noticed that this is the same issue as #7489

**Comment by medikoo** [comment] 2020-07-14 10:08
Duplicate of #7489

**Closed by medikoo** 2020-07-14 10:08 UTC
Labels: duplicate
