### ISSUE TITLE
Not able to create project via template.

### ISSUE THREAD

**Issue by ravikantk42** [serverless/serverless#11607] opened 2022-12-14 05:37 UTC
### Are you certain it's a bug?

- [X] Yes, it looks like a bug

### Is the issue caused by a plugin?

- [X] It is not a plugin issue

### Are you using the latest v3 release?

- [X] Yes, I'm using the latest v3 release

### Is there an existing issue for this?

- [X] I have searched existing issues, it hasn't been reported yet

### Issue description

![image](https://user-images.githubusercontent.com/80306841/207514518-7c3606b8-aab0-409d-9080-0950bc271fd3.png)

### Service configuration (serverless.yml) content

```yaml
N/A
```

### Command name and used flags

serverless

### Command output

```shell
NA
```

### Environment information

```shell
Framework Core: 3.25.1
Plugin: 6.2.2
SDK: 4.3.2
```

**Comment by medikoo** [comment] 2022-12-14 10:10
Duplicate of #11606

**Closed by medikoo** 2022-12-14 10:10 UTC
