### ISSUE TITLE
referenced configuration files with ${file} directive in serverless.yml are not parsed for rc1

### ISSUE THREAD

**Issue by Bilal-S** [serverless/serverless#2094] opened 2016-09-12 02:31 UTC
Following example in documentation: 
[serverless docs](https://github.com/serverless/serverless/blob/master/docs/01-guide/08-serverless-variables.md)

using this in serverless.yml
````
provider: aws
custom: ${file(serverless.env.yml)}  
````

Expected the content of serverless.env.yml to be parsed and available under the custom key. Instead an object literal is provided:
![ymlparsing](https://cloud.githubusercontent.com/assets/668901/18423025/2c901860-786f-11e6-962c-d6fb798df0e7.PNG)

Am I just reading the docs wrong?

**Comment by andymac4182** [comment] 2016-09-12 03:23
I am using `custom: ${file(./serverless.vars.yml)}` in mine currently. It looks like you might need to add `./` to the start of your file reference.

**Comment by Bilal-S** [comment] 2016-09-12 12:29
Thanks @andymac4182 I have tried multiple variations. All result in the same outcome.

**Comment by andymac4182** [comment] 2016-09-12 12:42
Where are you getting that object @Bilal-S ?

**Comment by eahefnawy** [comment] 2016-09-12 12:52
@Bilal-S what exactly do you mean by `Instead an object literal is provided`?  how are you seeing the output eitherway?

I tried to reproduce based on the config you provided, but it seems to be working.

**Comment by flomotlik** [comment] 2016-09-12 18:39
Yup that happens right afterwards:

```
    return this.service.load(this.processedInput.options)
      .then(() => {
        // set the provider of the service (so that the PluginManager takes care to
        // execute the correct provider specific plugins)
        this.pluginManager.setProvider(this.service.provider.name);

        // load all plugins
        this.pluginManager.loadAllPlugins(this.service.plugins);

        // give the CLI the plugins so that it can print out plugin information
        // such as options when the user enters --help
        this.cli.setLoadedPlugins(this.pluginManager.getPlugins());

        // populate variables after processing options
        return this.variables.populateService(this.pluginManager.cliOptions);
      });
```

Not sure if this is really a bug as the config is properly loaded so closing. I also don't think plugins should necessarily rely on specific config in their constructor and should rather rely on config once their functions are called as other plugins could change configuration before your plugin is running.

**Closed by flomotlik** 2016-09-12 18:39 UTC
