### ISSUE TITLE
Missing handling for I/O errors when packaging

### ISSUE THREAD

**Issue by qqjameqq1** [serverless/serverless#8518] opened 2020-11-18 06:48 UTC
Error --------------------------------------------------

  Error: EIO: i/o error, open '/var/www/html/dentCoNew/api/src/vendor/aws/aws-sdk-php/src/data/sso/2019-06-10/paginators-1.json.php'
      at Package.getFileContent (/home/laradock/.nvm/versions/node/v14.7.0/lib/node_modules/serverless/lib/plugins/package/lib/zipService.js:140:15)
      at Package.getFileContentAndStat (/home/laradock/.nvm/versions/node/v14.7.0/lib/node_modules/serverless/lib/plugins/package/lib/zipService.js:129:12)
      at Array.map (<anonymous>)
      at WriteStream.<anonymous> (/home/laradock/.nvm/versions/node/v14.7.0/lib/node_modules/serverless/lib/plugins/package/lib/zipService.js:97:46)
      at WriteStream.emit (events.js:314:20)
      at WriteStream.EventEmitter.emit (domain.js:486:12)
      at /var/www/html/dentCoNew/api/src/node_modules/@auth0/s3/node_modules/graceful-fs/graceful-fs.js:231:14
      at /var/www/html/dentCoNew/api/src/node_modules/@auth0/s3/node_modules/graceful-fs/graceful-fs.js:258:16
      at /home/laradock/.nvm/versions/node/v14.7.0/lib/node_modules/serverless/node_modules/graceful-fs/graceful-fs.js:333:16
      at FSReqCallback.oncomplete (fs.js:164:23)

  Your Environment Information ---------------------------
     Operating System:          linux
     Node Version:              14.7.0
     Framework Version:         2.11.1
     Plugin Version:            4.1.2
     SDK Version:               2.3.2
     Components Version:        3.3.1

**Comment by medikoo** [comment] 2020-11-20 12:36
@qqjameqq1 it indicates problem in your environment. See https://stackoverflow.com/a/953131/96806

Still definitely error reporting could be improved on our side. Such errors should be caught and thrown with `ServerlessError` with meaningful message. PR that improves that is welcome!

**Comment by medikoo** [comment] 2020-12-01 14:28
Fix implementation spec:

Ensure that any error originating from [reading file content and stats](https://github.com/serverless/serverless/blob/84bcc1e26a0ea84a7cc665670c187ba4bd7c07fc/lib/plugins/package/lib/zipService.js#L121-L122), is reported via `ServerlessError` with meaningful message like:

```
Cannot read file ${filePath} due to: ${error.nessage}`
```

**Comment by scadu** [comment] 2020-12-06 09:58
@medikoo, I might take a look if the issue is still relevant (I haven't seen any PRs opened, nor commits in this area).

**Comment by medikoo** [comment] 2020-12-06 10:09
@scadu yes, it was not addressed yet. PR will be highly appreciated! Thank you

**Comment by scadu** [comment] 2020-12-07 16:22
@medikoo, I think this issue can be closed now? It didn't trigger the auto-close rule since I left `addresses` in the PR.

**Comment by medikoo** [comment] 2020-12-08 08:45
@scadu indeed, thanks for pinging. Closing

**Closed by medikoo** 2020-12-08 08:45 UTC
Labels: bug, cat/dx, cat/packaging, good first issue, help wanted
