### ISSUE TITLE
[BUG] Run serverless encounter Cannot find module 'graceful-fs'

### ISSUE THREAD

**Issue by c19** [serverless/serverless#7758] opened 2020-05-21 10:39 UTC
a clean serverless install will reproduce
```
> serverless
pkg/prelude/bootstrap.js:1244
      throw error;
      ^

Error: Cannot find module 'graceful-fs'
Require stack:
- /snapshot/serverless/bin/serverless.js
1) If you want to compile the package/file into executable, please pay attention to compilation warnings and specify a literal in 'require' call. 2) If you don't want to compile the package/file into executable and want to 'require' it from filesystem (likely plugin), specify an absolute path in 'require' call using process.cwd() or process.execPath.
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:980:15)
    at Function.Module._resolveFilename (pkg/prelude/bootstrap.js:1346:46)
    at Function.Module._load (internal/modules/cjs/loader.js:862:27)
    at Module.require (internal/modules/cjs/loader.js:1042:19)
    at Module.require (pkg/prelude/bootstrap.js:1225:31)
    at require (internal/modules/cjs/helpers.js:77:18)
    at Object.<anonymous> (/snapshot/serverless/bin/serverless.js:18:20)
    at Module._compile (pkg/prelude/bootstrap.js:1320:22)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1176:10)
    at Module.load (internal/modules/cjs/loader.js:1000:32) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [ '/snapshot/serverless/bin/serverless.js' ],
  pkg: true
}
```

**Comment by medikoo** [comment] 2020-05-21 10:58
@c19 how did you install Serverless Fremework, and what OS are you using?

**Comment by medikoo** [comment] 2020-05-21 10:59
I see you're based in China so it might be related to China mirror, cc @yugasun

**Comment by c19** [comment] 2020-05-21 12:07
> @c19 how did you install Serverless Fremework, and what OS are you using?

Mac.

**Comment by c19** [comment] 2020-05-21 12:40
I tried `curl -o- -L https://slss.io/install | bash` but got `Error: Cannot find module 'chalk'`
```
curl -o- -L https://slss.io/install | bash
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100   178  100   178    0     0     87      0  0:00:02  0:00:02 --:--:--    87
  0     0    0     0    0     0      0      0 --:--:--  0:00:03 --:--:--     0
100  3059  100  3059    0     0    637      0  0:00:04  0:00:04 --:--:--  3962

 Installing Serverless!

 Downloading binary...
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100  132M  100  132M    0     0  1932k      0  0:01:10  0:01:10 --:--:-- 2569k
pkg/prelude/bootstrap.js:1244
      throw error;
      ^

Error: Cannot find module 'chalk'
Require stack:
- /snapshot/serverless/scripts/postinstall.js
- /snapshot/serverless/bin/serverless.js
1) If you want to compile the package/file into executable, please pay attention to compilation warnings and specify a literal in 'require' call. 2) If you don't want to compile the package/file into executable and want to 'require' it from filesystem (likely plugin), specify an absolute path in 'require' call using process.cwd() or process.execPath.
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:980:15)
    at Function.Module._resolveFilename (pkg/prelude/bootstrap.js:1346:46)
    at Function.Module._load (internal/modules/cjs/loader.js:862:27)
    at Module.require (internal/modules/cjs/loader.js:1042:19)
    at Module.require (pkg/prelude/bootstrap.js:1225:31)
    at require (internal/modules/cjs/helpers.js:77:18)
    at Object.<anonymous> (/snapshot/serverless/scripts/postinstall.js:4:15)
    at Module._compile (pkg/prelude/bootstrap.js:1320:22)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1176:10)
    at Module.load (internal/modules/cjs/loader.js:1000:32) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    '/snapshot/serverless/scripts/postinstall.js',
    '/snapshot/serverless/bin/serverless.js'
  ],
  pkg: true
}
```

Tried `npm i -g serverless` install succeeded 

```
npm install -g serverless
npm WARN deprecated request@2.88.2: request has been deprecated, see https://github.com/request/request/issues/3142
npm WARN deprecated resolve-url@0.2.1: https://github.com/lydell/resolve-url#deprecated
npm WARN deprecated urix@0.1.0: Please see https://github.com/lydell/urix#deprecated
/usr/local/bin/sls -> /usr/local/lib/node_modules/serverless/bin/serverless.js
/usr/local/bin/slss -> /usr/local/lib/node_modules/serverless/bin/serverless.js
/usr/local/bin/serverless -> /usr/local/lib/node_modules/serverless/bin/serverless.js

> serverless@1.71.3 postinstall /usr/local/lib/node_modules/serverless
> node ./scripts/postinstall.js


   ┌───────────────────────────────────────────────────┐
   │                                                   │
   │   Serverless Framework successfully installed!    │
   │                                                   │
   │   To start your first project run 'serverless'.   │
   │                                                   │
   └───────────────────────────────────────────────────┘

+ serverless@1.71.3
added 823 packages from 515 contributors in 88.75s
```

but run serverless return error

```
serverless
pkg/prelude/bootstrap.js:1244
      throw error;
      ^

Error: Cannot find module 'graceful-fs'
Require stack:
- /snapshot/serverless/bin/serverless.js
1) If you want to compile the package/file into executable, please pay attention to compilation warnings and specify a literal in 'require' call. 2) If you don't want to compile the package/file into executable and want to 'require' it from filesystem (likely plugin), specify an absolute path in 'require' call using process.cwd() or process.execPath.
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:980:15)
    at Function.Module._resolveFilename (pkg/prelude/bootstrap.js:1346:46)
    at Function.Module._load (internal/modules/cjs/loader.js:862:27)
    at Module.require (internal/modules/cjs/loader.js:1042:19)
    at Module.require (pkg/prelude/bootstrap.js:1225:31)
    at require (internal/modules/cjs/helpers.js:77:18)
    at Object.<anonymous> (/snapshot/serverless/bin/serverless.js:18:20)
    at Module._compile (pkg/prelude/bootstrap.js:1320:22)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1176:10)
    at Module.load (internal/modules/cjs/loader.js:1000:32) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [ '/snapshot/serverless/bin/serverless.js' ],
  pkg: true
}
```

**Comment by medikoo** [comment] 2020-05-21 13:06
@c19 are you installing from China?

**Comment by medikoo** [comment] 2020-05-21 13:34
I have confirmed that it's a problem of Chinese mirror hosting broken standalone binary.

For a meantime resort to npm installation, for that you need to manually uninstall standalone installation via:

```
$ rm -rf ~/.serverless/bin
```

**Comment by yugasun** [comment] 2020-05-21 14:02
@c19 We recommend to install `serverless` by `npm`, you can just remove serverless command.

**Comment by medikoo** [comment] 2020-05-21 14:07
@yugasun problem is with binary that was built for Chinese mirror. There's no such issue with binary built on our side.

Do you suggest that we should remove support for Chinese mirror in our standalone url resolution?

**Comment by yugasun** [comment] 2020-05-21 14:11
@medikoo Yeah, I'm checking why, I use the same Nodejs version and linux system. Just run `pkg:build`, and it build success, but I don't know why it throw a `missing module` error.

**Comment by medikoo** [comment] 2020-05-21 14:14
@yugasun it might be an issue with `serverless` installation prior `pkg:build` is being run. AFAIK `pkg` will just warn if it approaches that some modules doesn't resolve, so it can build _successfully_ a broken binary

**Comment by yugasun** [comment] 2020-05-21 14:16
@medikoo Before the `pkg:build`, I have installed all the node modules.

**Comment by yugasun** [comment] 2020-05-21 14:36
Well solved by running `pkg:build` again.

**Comment by medikoo** [comment] 2020-05-22 07:40
@yugasun as I check the https://binary.serverlesscloud.cn/v1.71.3/serverless-macos-x64 still points to broken binary.

Also it'll be great to figure out why broken built was generated, without that I think we'll be constantly exposed to the issue.

**Comment by yugasun** [comment] 2020-05-22 10:47
@medikoo I will replace rebuilding binary to downloading binary from github release.

**Comment by medikoo** [comment] 2020-05-22 11:02
@yugasun That's great idea, just ensure that it handles well current scenario, where first release is created on GitHub and after that binaries are uploaded to it.

AFAIK webhook is triggered on release creation, which means that most likely it's triggered before binaries are there. I think you need to incorporate logic where you check for existence of binary and if it's not there wait for e.g. 1s, and eventually repeat that process until binaries are available

**Comment by yugasun** [comment] 2020-05-22 12:16
@medikoo I resolved the binary for version `v1.71.3`, and validate it on my MacOS.

**Comment by medikoo** [comment] 2020-05-22 12:26
@yugasun I've just downloaded https://binary.serverlesscloud.cn/v1.71.3/serverless-macos-x64 still  again, and it's still broken

**Comment by yugasun** [comment] 2020-05-22 14:52
@medikoo I figured out the problem, it's about the CDN cache. I have cleared the cache, and try again and again, and success in 3 times.

**Comment by medikoo** [comment] 2020-05-25 06:39
> @medikoo I figured out the problem, it's about the CDN cache. I have cleared the cache, and try again and again, and success in 3 times.

I take then, that this fix will work only for those which didn't download new binary yet. And those which did need to wait new version or ensure their cache is cleared?

**Comment by yugasun** [comment] 2020-05-25 11:57
@medikoo We can pay attention on this issue continuously for weeks.

**Comment by Ksmike** [comment] 2020-06-01 11:10
@yugasun Hi, I'm having a similar issue. I just upgraded from a previous version to a newer version via `npm i -g serverless` and now I'm experiencing - >
```
Error: No valid exports main found for '/.nvm/versions/node/v13.5.0/lib/node_modules/serverless/node_modules/uuid'
    at resolveExportsTarget (internal/modules/cjs/loader.js:622:9)
    at applyExports (internal/modules/cjs/loader.js:499:14)
    at resolveExports (internal/modules/cjs/loader.js:548:12)
    at Function.Module._findPath (internal/modules/cjs/loader.js:654:22)
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:953:27)
    at Function.Module._load (internal/modules/cjs/loader.js:859:27)
    at Module.require (internal/modules/cjs/loader.js:1028:19)
    at require (internal/modules/cjs/helpers.js:72:18)
    at Object.<anonymous> (/.nvm/versions/node/v13.5.0/lib/node_modules/serverless/node_modules/@serverless/lib/deployment/createAndSetUid.js:3:14)
```
I tried deleting the serverless via `rm -rf` then install from scratch, but the issue is persisting, 

I was using it this morning, so it's been introduced with the latest release, I'll watch this thread, or if you recommend, I can create a separate issue, 
Cheers

**Comment by medikoo** [comment] 2020-07-07 14:17
It was addressed by changing source of binaries when downloading in China

**Closed by medikoo** 2020-07-07 14:17 UTC
Labels: bug, cat/standalone, provider/tencent
