### ISSUE TITLE
Serverless Commands should ask for confirmation and Should show plan of execution

### ISSUE THREAD

**Issue by ddbhagat** [serverless/serverless#12021] opened 2023-06-13 08:45 UTC
### Is there an existing issue for this?

- [X] I have searched existing issues, it hasn't been reported yet

### Use case description

Serveless is heavily used for creating, deploying and destroying the resources. So all these operations are really crtitical. So ideally any such costructive operation should ask for a confirmation and should also show the possible impact/plan for it.

This will also save any accidental destuctions.

**Comment by medikoo** [comment] 2023-06-13 09:16
Duplicate of https://github.com/serverless/serverless/issues/10139

**Closed by medikoo** 2023-06-13 09:16 UTC
Labels: duplicate
