### ISSUE TITLE
Update to resource type AWS::Lambda::Version is not supported

### ISSUE THREAD

**Issue by Pjack** [serverless/serverless#4519] opened 2017-12-04 09:50 UTC
# This is a Bug Report

## Description

For bug reports:
* What went wrong?
   There are two functions in the serverless.xml. 
   We modified one of the functions, i.e. another function is identical with before.
   But when we deploy the service, it will deploy fail
   
   sls deploy -s alpha

   I suspect it is caused by the option "individually" in serverless.yml
   Is it the expected behavior  or a bug?
 
* What did you expect should have happened?
 
I expect the identical function will not be deployed

* What was the config you used?
<pre>
provider:
  name: aws
  region: ap-northeast-1
  runtime: nodejs6.10
  memorySize: 128
  timeout: 3

package:
  individually: true
  exclude:
    - function1/**
    - function2/**
    - test/**
    - Makefile
  include:
    - config.yml

functions:
  function1:
    handler: function1/index.handler
    timeout: 120
    events:
      - stream:
          type: kinesis
          arn: ${self:custom.config.kinesis.dailyEvents.arn}
          batchSize: 100
          startingPosition: TRIM_HORIZON
          enabled: true
    package:
      include:
        - function1/**

  function2:
    handler: function2/index.handler
    timeout: 120
    events:
      - stream:
          type: kinesis
          arn: ${self:custom.config.kinesis.dailyEvents.arn}
          batchSize: 100
          startingPosition: TRIM_HORIZON
          enabled: true
    package:
      include:
        - function2/**
</pre>

* What stacktrace or error message from your provider did you see?
An error occurred: AggregateLambdaVersionxlLCwdjyFiAJ08Phnp5rUCkcrKGghbeFQ4VOl7MOGo - Update to resource type AWS::Lambda::Version is not supported..

## Additional Data

* ***Serverless Framework Version you're using***: 1.24.1
* ***Operating System***: Ubuntu 14.04
* ***Stack Trace***: nope
* ***Provider Error messages***: nope

**Comment by HyperBrain** [comment] 2017-12-04 09:58
Hi @Pjack, thanks for reporting the issue 😄 .
This might be an issue with the ap-northeast-1, i.e. maybe not all operations are supported there.
@horike37 Do you have some experience with that region?

**Comment by horike37** [comment] 2017-12-05 12:12
Umm :thinking: 
I have never faced such a problem with ap-northeast-1.

**Comment by dynamikus** [comment] 2017-12-08 20:40
It might not be a region thing I am having the same problem in us-east-1, but it fails only when I try to update an existing project. When I deploy for the first time it works just fine.

```
Serverless: Operation failed!
 
  Serverless Error ---------------------------------------
 
  An error occurred: JobsubmitLambdaVersionIgGQw2gI6oL9U94w3HHxzyaeMy1iVdYdIq6AmUZvms - Update to resource type AWS::Lambda::Version is not supported..
```
**My serverless file:**
```yaml
provider:
  name: aws
  runtime: nodejs6.10  
  region: us-east-1
  stage: ${opt:stage, 'Development'}
  apiKeys: 
    - batch-dispatch-api-${self:provider.stage}
  iamRoleStatements: 
    - Effect: 'Allow'
      Action:
        - 'batch:SubmitJob'
        - 'batch:DescribeJobDefinitions'
      Resource: '*'        

functions:
  jobsubmit:
    handler: λ/job.submit
    name: ${self:service}-submit-${self:provider.stage}
    description: Responsible for submiting a job to the job queue. Repo- ${self:custom.packageJson.homepage} 
    memorySize: 128
    timeout: 3 
    tags: 
      System: Dex     
      Environment: ${self:provider.stage}
    events:
      - http:
          path: aws/batch/job/submit
          method: post
          cors: true
          private: true
```

**Comment by HyperBrain** [comment] 2017-12-08 20:45
Can you try if it is solved when using the master branch of serverless?

Namik <notifications@github.com> schrieb am Fr., 8. Dez. 2017, 9:40 nachm.:

**Comment by dynamikus** [comment] 2017-12-08 22:12
@HyperBrain I just finished doing multiple consequent deploys using the master branch and did not have any failure at all. So it looks whatever is wrong with 1.24.1 works fine with :latest . 

The problem that with 1.24.1 is that I can't reproduce the bug consistently some time the update deploy works fine.

**Comment by HyperBrain** [comment] 2017-12-09 11:12
@dynamikus The reason why I asked cou to test with master is, that I think, that the problem is fixed with my PR https://github.com/serverless/serverless/pull/4510.

Your test results definitely point to that.

**Comment by dynamikus** [comment] 2017-12-11 15:34
@HyperBrain cool. Yep indeed I could not reproduce the lambda versioning on the master branch. When are you guys planing the next release?

**Comment by HyperBrain** [comment] 2017-12-11 15:43
@dynamikus Very soon 😄 Probably by next week.

@horike37 This one seems also to be fixed in master, so we should close it as soon as we prepare the release.

**Comment by horike37** [comment] 2017-12-11 16:11
OK @HyperBrain and thank you for confirming it @dynamikus 
Closing for now since we can re-open if we find regressions related to this.

**Closed by horike37** 2017-12-11 16:11 UTC
Labels: kind/bug, stage/needs-feedback

**Comment by Pjack** [comment] 2017-12-12 00:18
Sorry for late response. I'll verify it today.

**Comment by Pjack** [comment] 2017-12-14 03:37
This issue is fixed in the latest master branch. 
Thanks for help!

**Comment by horike37** [comment] 2017-12-14 03:50
Glad to hear that your problem has been resolved :+1:
