### ISSUE TITLE
Stage Variables

### ISSUE THREAD

**Issue by big-kahuna-burger** [serverless/serverless#2665] opened 2016-11-08 13:00 UTC
## Description

* We are looking into migrating to serverless and everything is going smooth so far except the part with "stages" on APIG

Our use case:
We are managing secrets trough a Stage/Stage Variables on APIG that get transformed in each request by default body request pass trough template on APIG. Is there an option to do this with serverless (manage APIG Stage Variables (keys/values)) ? 

I've looked into docs about variables but found nothing about it. 
Also, some kind of temp solution with .env file would also work, in a sense that we can just load the environment variables into lambda function but that's breaking the separation of concerns that we are going for. (single place to handle them all)

Thanks

**Comment by flomotlik** [comment] 2016-11-08 16:40
You can get Stage variables working through custom resources at the moment by overwriting things. We will definitely support Environment variable handling as soon as its available and I just created a proposal for a possible design in #2673 to discuss and implement as soon as its available. For now the best thing to do is use something like dotenv to get this up and running: https://serverless.com/framework/docs/providers/aws/guide/functions#environment-variables

Closing here as its a duplicate of #2673 as soon as thats in.

**Closed by flomotlik** 2016-11-08 16:40 UTC
