### ISSUE TITLE
Eventual Consistency in S3

### ISSUE THREAD

**Issue by patrickheeney** [serverless/serverless#4236] opened 2017-09-09 01:51 UTC
# This is a Bug Report

## Description

When running `serverless remove` multiple times (due to some plugin errors), it causes the following error:

```
The specified bucket does not exist
```

This is because bucket deletion is eventually consistent and takes some time to propagate everywhere.

I wonder if this problem exists elsewhere in the stack as well, but maybe [this section](https://github.com/serverless/serverless/blob/master/lib/plugins/aws/remove/lib/bucket.js#L22) should catch any errors like it doesn't exist and just return `Promise.resolve()`?

## Additional Data

* ***Serverless Framework Version you're using***:
* ***Operating System***:
* ***Stack Trace***:
* ***Provider Error messages***:

**Comment by pmuens** [comment] 2017-09-10 13:22
Thanks for opening @patrickheeney 👍

Looks like it's a duplicate of https://github.com/serverless/serverless/issues/3964. I'll close this issue for now. Let's continue the discussion over there.

**Closed by pmuens** 2017-09-10 13:22 UTC
Labels: kind/bug, status/help-wanted
