### ISSUE TITLE
Can't install sls for Apple Silicon M1 McBookAir 

### ISSUE THREAD

**Issue by moadij** [serverless/serverless#8737] opened 2021-01-09 20:16 UTC
It seems like it isn't possible to install sls on the new macs with the M1 chip. I got this error when I tired to install it:
"Sorry, there's no serverless binary installer available for arm64 architecture."

**Comment by pgrzesik** [comment] 2021-01-10 15:27
Hello @moadij, thanks for reporting. This is a known problem and we already have a similar issue reported: https://github.com/serverless/serverless/issues/8696 let's keep the whole discussion on the original issue.

**Comment by pgrzesik** [comment] 2021-01-10 15:27
Duplicate of: #8696

**Closed by pgrzesik** 2021-01-10 15:27 UTC
