### ISSUE TITLE
Using -v argument in serverless deploy function causes entire stack to be deployed

### ISSUE THREAD

**Issue by patrickbrandt** [serverless/serverless#2550] opened 2016-10-26 15:23 UTC
# This is a Bug Report

## Description

* What went wrong?
I ran the following command: `sls deploy -v function -f ping`
and it deployed the entire stack:
![image](https://cloud.githubusercontent.com/assets/11197026/19732455/cde5e5ec-9b6e-11e6-9d76-149bc283b5c3.png)

* What did you expect should have happened?
The same behavior as `sls deploy function -f ping`, but with verbose output. Here's non-verbose output for reference:
![image](https://cloud.githubusercontent.com/assets/11197026/19732300/6560d090-9b6e-11e6-9fc9-b9afcd3e0a9d.png)
* What was the config you used?
My serverless.yml file:
![image](https://cloud.githubusercontent.com/assets/11197026/19732326/791c87fa-9b6e-11e6-90c4-bed1321e93bc.png)

* What stacktrace or error message from your provider did you see?
N/A

## Additional Data

* ***Serverless Framework Version you're using***: 1.0.3
* ***Operating System***: Mac El Capitan 10.11.6

**Comment by eahefnawy** [comment] 2016-10-28 06:05
If you want to deploy a single function, the command is `sls deploy function` ... the keyword `function` must be right after `deploy` because it's a sub command of `deploy` ... you can then add any options for that `sls deploy function` command. So in this case you can just do:

```
sls deploy function -f ping
```
**Note:** There's no -v option for `deploy function` ... because there's no stack to be deployed

**Comment by mthenw** [comment] 2016-10-28 08:01
The problem is here that we are not returning error when unrecognized CLI option is passed. That causes a lot of confusion. 

It has been already reported with https://github.com/serverless/serverless/issues/2282. Closing this as duplicate.

**Closed by mthenw** 2016-10-28 08:01 UTC

**Comment by eahefnawy** [comment] 2016-10-28 08:12
@mthenw allowing users to use unrecognized options makes it possible to pass any option to Serverless Variables. Throwing an error would limit this use case.
