### ISSUE TITLE
Cannot override aws-profile with empty value after updating from v2.23 to v2.27.1

### ISSUE THREAD

**Issue by coyoteecd** [serverless/serverless#9013] opened 2021-02-25 12:53 UTC
As explained in #9010, our frontend repo is using provider.profile when deploying from local dev PCs (for convenience) whereas the CI/CD pipeline overrides the profile setting with an empty string so that serverless picks up credentials from environment variables set by Jenkins. 

This got broken in v2.24, and it is still broken in v2.27.1. While in v2.24 it complains about sub command not being valid, in v2.27.1 it just won't override anymore; the provider.profile is always resolved to whatever fallback there is in the yml file (could be some empty string vs null/undefined somewhere?).

<details>
<summary><code>serverless.yml</code></summary>

```yaml
plugins:
  - serverless-s3-sync

provider:
  name: aws
  stage: ${opt:stage, 'dev'}
  region: ${opt:region, 'us-east-1'}
  profile: ${opt:aws-profile, 'devprofile'}
```

</details>

<details>
<summary><code>serverless s3sync --stage mystage --aws-profile=</code> output</b></summary>

```
  Serverless Error ---------------------------------------

  "--aws-profile=" is not a valid sub command. Run "serverless s3sync" to see a more helpful error message for this command.
```

</details>

I installed latest master (2.27.1, commit [551ddd2](https://github.com/serverless/serverless/commit/551ddd23afe6d960e350a1227654c5466c43dc8e) and here the validation error is gone; however, the aws-profile is no longer overridden, so my deployment fails later with an error that shows the provider.profile was resolved to the default value from serverless.yml.

```
  Error: Profile devprofile does not exist
      at Object.addProfileCredentials (K:\SWS\sws-admin\node_modules\serverless\lib\plugins\aws\provider.js:146:15)
      at AwsProvider.getCredentials (K:\SWS\sws-admin\node_modules\serverless\lib\plugins\aws\provider.js:1508:12)
      at AwsProvider.request (K:\SWS\sws-admin\node_modules\serverless\lib\plugins\aws\provider.js:1350:48)
```

<b>Installed version</b>

Multiple versions, see above.

**Comment by medikoo** [comment] 2021-02-25 13:47
@coyoteecd  Thanks for opening, still above information is not sufficient for me to reproduce the issue.

The error `"--aws-profile=" is not a valid sub command. ` doesn't look as one that can come out of v2.27.1.
There was a known issue where param as `--aws-profile=` was not recognized, but that was fixed with https://github.com/serverless/serverless/pull/8978 (which was released with v2.26.0)

Can you present a complete test case? Above seems just a fraction of config, which cannot be used as is, as it's incomplete.

Also let's focus on latest v2.27.1 version, and do not put any other versions into picture

**Comment by coyoteecd** [comment] 2021-02-25 14:34
Fair enough, I built a complete example that I tested and gives the described behavior:

**serverless.yml**
```yml
service: example
plugins:
  - serverless-s3-sync

provider:
  name: aws
  stage: ${opt:stage, 'dev'}
  region: ${opt:region, 'us-east-1'}
  profile: ${opt:aws-profile, 'devprofile'}

custom:
  s3Sync:
    - bucketName: ${cf:backendstack.WebsiteBucketName}
      localDir: dist
```

**package.json**
```json
{
  "name": "example",
  "version": "1.0.0",
  "description": "",
  "main": "index.js",
  "scripts": {
    "test": "serverless s3sync --aws-profile="
  },
  "author": "",
  "license": "ISC",
  "devDependencies": {
    "serverless": "github:serverless/serverless#master",
    "serverless-s3-sync": "^1.16.1"
  }
}
```

Run `npm install` and `npm test`. I get the following error:

```
  Error: Profile devprofile does not exist
      at Object.addProfileCredentials (K:\example\node_modules\serverless\lib\plugins\aws\provider.js:146:15)
      at AwsProvider.getCredentials (K:\example\node_modules\serverless\lib\plugins\aws\provider.js:1515:12)
      at AwsProvider.request (K:\example\node_modules\serverless\lib\plugins\aws\provider.js:1350:48)
      at Variables.getValueFromCf (K:\example\node_modules\serverless\lib\classes\Variables.js:763:8)
      at Variables.getValueFromSource (K:\example\node_modules\serverless\lib\classes\Variables.js:579:17)
      at Variables.splitAndGet (K:\example\node_modules\serverless\lib\classes\Variables.js:448:17)
      at K:\example\node_modules\serverless\lib\classes\Variables.js:387:40
      at Array.map (<anonymous>)
      at Variables.populateMatches (K:\example\node_modules\serverless\lib\classes\Variables.js:387:20)
      at Variables.populateValue (K:\example\node_modules\serverless\lib\classes\Variables.js:418:30)
      at K:\example\node_modules\serverless\lib\classes\Variables.js:300:38
      at Array.map (<anonymous>)
      at Variables.populateVariables (K:\example\node_modules\serverless\lib\classes\Variables.js:299:8)
      at Variables.populateObjectImpl (K:\example\node_modules\serverless\lib\classes\Variables.js:333:30)
      at K:\example\node_modules\serverless\lib\classes\Variables.js:213:20
      at Variables.initialCall (K:\example\node_modules\serverless\lib\classes\Variables.js:112:14)
      at Serverless.run (K:\example\node_modules\serverless\lib\Serverless.js:261:5)
      at K:\example\node_modules\serverless\scripts\serverless.js:175:7
```

**Comment by medikoo** [comment] 2021-02-25 14:43
@coyoteecd this error signals, that AWS profile `devprofile` is not configured your environment. Do you find it unexpected?

Still, I see one UX related error on our side. We should throw there `ServerlessError`, so it's presented without stack trace (I'd also improve wording to `AWS profile "devprofile" is not found to be configured in local environment`.
It can be fixed here: https://github.com/serverless/serverless/blob/551ddd23afe6d960e350a1227654c5466c43dc8e/lib/plugins/aws/provider.js#L146

PR that improves that is welcome.

**Comment by coyoteecd** [comment] 2021-02-25 14:52
It's not the error message, that one is pretty clear (for me). 

In v2.23 and older, passing `--aws-profile=` is treated as empty (but *present*) value and overrides the "devprofile" fallback value, so you would get another error depending on whether you have environment variable set or not. Now it doesn't, it resolves to the fallback value, which is exactly what I was trying to override.

**Comment by medikoo** [comment] 2021-02-25 15:12
> In v2.23 and older, passing --aws-profile= is treated as empty (but present) value and overrides the "devprofile" fallback 

Ok got it. So with new parser not passing `--aws-profile` and passing it as `--aws-profile=` doesn't make real difference (internally first resolves to `undefined` second to `null` and both are handled same).

Thing is that new parser unified how results from sources are handled. If source (no matter which). resolves with `null`, it requires fallback to be validated.

I think there's no easy fix to your case. I would however rethink your config as it doesn't seem intuitive, and more importantly we plan to _deprecate_ support for both `--aws-profile` and `provider.profile`. Thing is that since we've introduced support for `.env` files, it's way better to handle any environment variables configuration that way.

So I propose that you:

1. Replace `provider.profile`  with setting of `AWS_PROFILE` in `.env` file (still at this point it requires `useDotenv: true` in configuration to work)
2. Replace `--aws-profile` with `AWS_PROFILE=profile` env var
3. In CI do not use `.env` and do not set `AWS_PROFILE`

**Comment by medikoo** [comment] 2021-02-25 15:25
@coyoteecd still give us a moment. I'm having a second thoughts, and considering supporting intentional `null` as value from which we should not fallback. It actually makes sense in many scenarios

**Comment by medikoo** [comment] 2021-02-26 11:53
@coyoteecd I've looked into it closer and situation is a follows:

1. After thinking it through (and discussing with @pgrzesik), I think we should not make `null` as value from which no fallback occurs. Firstly in old resolver `null` is a value for which fallback is applied, and secondly this blocks some valid scenarios. Note that in configuration we support just JSON values (so you cannot set properties to `undefined`, just `null`), and having that, if `null` won't trigger fallback, we would be limited in falling back from properties that are defined but resolve to empty values, e.g.:

```yaml
foo: ${some-var, null}
bar: ${self:foo, "fallback"} // No chance for a fallback to be applied
```

2. It's true though that `--aws-profile=` in versions prior v2.24.0,resolved with a value that was immune to fallback. It was due to change in how parser handles such notation. Before it was translated to `''` (empty string), and now it's translated to `null`. I believe that new way is more accurate, and makes more sense. So technically you got bitten by a quirk of old resolution rules.

Ideally to recover from that, if you'd adapt to suggestions as proposed in [previous comment](https://github.com/serverless/serverless/issues/9013#issuecomment-785974575), as aside of quirky resolution pattern used, we consider `--aws-profile` and `provider.profile` properties as to be deprecated.

**Comment by coyoteecd** [comment] 2021-02-26 14:24
OK, thanks for taking the time to consider it.

Aside of not enough time, I avoided switching to env files because on the backend I also have a plugin that in combination with serverless-offline, provides env vars to the lambdas when running locally, and that plugin also writes its own .env vars locally. Thus not helping with the "confusing part" at all. But yeah, this is a plugin issue and not something to be addressed by serverless core package.

**Closed** 2021-02-26 16:04 UTC
Labels: bug, cat/aws-auth, good first issue, help wanted

**Comment by coyoteecd** [comment] 2021-02-26 16:31
@medikoo just FYI, the env var approach is less usable for my setup, and the reason is provider.profile would let you select a profile name that's dynamically built on stage and account being deployed, whereas with env files, I have to ask each dev to create these files manually. This is because useDotenv supports .env.{stage} files with fallback to dev, but you cannot put a stage-specific profile name within the .env.dev fallback file - something I could do with `provider.profile`.

So I understand why you're deprecating it, but it is a step back as I see it.

**Comment by medikoo** [comment] 2021-02-26 16:41
> @medikoo just FYI, the env var approach is less usable for my setup, and the reason is provider.profile would let you select a profile name that's dynamically built on stage and account being deployed

with `.env` file's approach, you can load different `.env` file per _stage_, by creating `.env.dev`, `.env.prod` etc.

>  I have to ask each dev to create these files manually.

Ok, how do they then make different AWS_PROFILE settings work on their side? Do you also provide some automation for it? Or do they maintain `~/.aws` manually?

> but you cannot put a stage-specific profile name within the .env.dev fallback file - something I could do with provider.profile.

How do you then ensure stage-specific AWS profile always exists? e.g. if someone puts `--stage=foo` , how it happens that suddenly there's `fooprofile` for AWS configured?

**Comment by coyoteecd** [comment] 2021-02-26 17:09
> Ok, how do they then make different AWS_PROFILE settings work on their side? Do you also provide some automation for it? Or do they maintain `~/.aws` manually?

I have some scripts that use the AWS CLI to ensure the profile is created before serverless deploy. So what I have to do is to create an env.stage file for it as part of that script, make that plugin write his own .env file with another name and notify everybody not to confuse the two kinds of env files.

I will find a workable solution, at this point I am just venting because of unexpected work :). Please do not break your refactoring because of this, I am a dev too and can understand what it means to break a nicely designed logical model.

**Comment by medikoo** [comment] 2021-03-01 11:49
Thanks @coyoteecd for explanation. To be honest, this setup it still quite vague to me, and I need to understand it, to understand well the use case, hence my questions


> I have some scripts that use the AWS CLI to ensure the profile is created before serverless deploy.

And what about AWS credentials? Technically AWS profiles map specific credentials, so I believe scripts have some hard-coded set of credentials, which are distributed across created AWS profiles, right? Or do those scripts also create AWS access key in context of some account to which it have access to?

> and then the frontend repositories can re-use the already existing profiles

In my understanding AWS profiles are a local thing. So not a thing that if on creates on server A, can be used on server B. Profile is technically a local configuration in context of `~/.aws` which allows to address specific AWS credentials (and other settings) via some simple name.

If that's the case, what do you mean by "frontend repositories can re-use the already existing profiles" ? Do you mean that they can reuse those profiles in context of the server on which they were setup? (which means services are configured not as  portable to other environments), or do you mean that developers copy content of `~/.aws` as generated on remote server to their local machine, and through that rely on "generated" profiles?

**Comment by coyoteecd** [comment] 2021-03-02 08:15
My setup is as follows:
- backend git repo that deploys all the AWS resources, including buckets for frontend/documentation repos.
- 4 repos with frontend apps/documentation websites, that get deployed via serverless s3sync to the existing buckets.

We have a master AWS account that holds the IAM users, and additional accounts for dev/staging/prod. In each account, there are roles named according to conventions, so the CI/CD knows what role it should assume based on the git branch name being deployed. IAM access key of each account is stored in CI/CD.

Dev account is "free for all", at least at the moment. Each dev has the access key/secret used by CI/CD to deploy, and they add them in a fixed profile in `.aws/credentials` on their dev PC. When they want to deploy a dev stage, they run a script on the backend repo (which consists of multiple serverless deploys); this script creates AWS profiles in `.aws/config` for that stage, using the fixed profile as `source_profile`. The profile name is based on a naming convention based on stage that matches the provider.profile setting in serverless.yml script.

The result is that once somebody gets the IAM deploy credentials to the dev account and adds them to their local `.aws/config`, they can:
- deploy as many dev stages of the backend without messing with the .aws/config file (the script does it)
-- redeploy only the lambda stack of the backend (so, without running the entire backend script), because the profile is already there and the serverless.yml refers to it using the correct name
- debug the backend lambda code with serverless-offline in combination with serverless-offline-assume-role plugin, which reads the profile and assumes it at runtime (so that if e.g. my lambda does not have permissions to write to Dynamo, I will get an error without waiting for a deploy cycle)
- deploy any of the frontend/doc repos, provided that they've deployed backend from my dev PC first (which happens naturally since the backend creates the buckets and the frontend repo)
- easily run AWS CLI commands locally under the same permissions as the deployment user, by passing the --profile parameter to them

With env files, the above will add an extra step of writing the correct .env.stage file when deploying the backend, and copying it to the other frontend/documentation repos checked out locally before you can deploy them.

I'm afraid I can't go in too much more detail in public; if the above still sounds unclear and you're still curious about my setup, we could continue the discussion via email.

To your specific questions:

> And what about AWS credentials? Technically AWS profiles map specific credentials, so I believe scripts have some hard-coded set of credentials, which are distributed across created AWS profiles, right? Or do those scripts also create AWS access key in context of some account to which it have access to?

The scripts are in the source control, so obviously they do not have credentials in them. We use `aws configure list --profile` to detect whether the profile is already created, and if not, prompt the user to enter their access key/secret. AWS SDK will write them in `.aws/config` so in principle you don't even have to know where it's located.

> If that's the case, what do you mean by "frontend repositories can re-use the already existing profiles" ? Do you mean that they can reuse those profiles in context of the server on which they were setup?

I mean in our team, everybody has all the repos cloned on their local dev PC, they make changes and deploy to their own personal stage in the dev account. So deploying frontend changes reuses the profile already set up when you deployed the backend.

-----
Again, all the above is just convenience for devs, created on what was available in serverless v1.5x. 
The CI/CD does not use profiles whatsoever, so I do not understand what you mean by portability. Ability to deploy to a completely new account?

**Comment by medikoo** [comment] 2021-03-02 09:42
@coyoteecd thanks for thorough explanations. So If I understand correctly situation is as follows:

1. Developers on their side run scripts to configure content of `~/.aws` on their local machines with all the needed AWS profiles configuration.
2. Developers choose profile with which application is to be deployed by passing `--aws-profile` option to `sls` comand, and if this option is not passed, then assumed AWS profile is `devprofile`
3. CI doesn't use profiles, it has hardcoded secret and key id, and therefore it needs to be ensured that no profile is resolved there.

Is that correct?

If it's the case, wouldn't same be achieved via:

1. Scripts which configures content of `~/.aws` also ensures that developers their shell have a environemtn variable `AWS_DEFAULT_PROFILE` configured to `devprofile` value (it can be done by e.g. tweaking `.profile` file content, e.g. in Serverless Framework we add such environment variables when setting tabtab completion)
2. Developers instead of using `--aws-profile=<profile>` CLI param, prepend sls command with `AWS_PROFILE=<profile>` when deploying services
3. CI naturally works as it works, as with above there's no need to have `provider.profile` configured directly in a service (so there's no need to reset this setting).

Above doesn't involve any service level `.env` files 

What do you think? Could that work, all did I miss anything?

**Comment by medikoo** [comment] 2021-03-02 09:48
And if you'd prefer to have `AWS_DEFAULT_PROFILE` set per service and not for user globally. Then you can put it into `.env` file, which technically can also be versioned in repository (so effect would be same as now when storing this value in serverless config)

**Comment by coyoteecd** [comment] 2021-03-02 14:40
> Developers choose profile with which application is to be deployed by passing --aws-profile option to sls comand, and if this option is not passed, then assumed AWS profile is devprofile

No, the developers just pass in the stage parameter. The profile that serverless uses is inferred from the stage parameter, using the naming conventions. I'll give an example here:
```
profile: ${opt:aws-profile, self:custom.config.myProfile}
```
where `myProfile` is further resolved based on the environment (aka AWS account) being deployed; for dev being something along the lines of `deploy-app-${self:provider.stage}` (backend sls profile) or `deploy-frontend-${self:provider.stage}` (frontend sls profile).

So all they need to do is `sls deploy --stage mystage` for backend, and `sls s3sync --stage mystage` for frontends, respectively and deployment will automatically use the `deploy-backend-mystage` profile, or `deploy-frontend-mystage` profile. Sounds complicated to set up, but is really easy to use in practice (imo) and worked well for us in the past year.

> Developers instead of using --aws-profile=<profile> CLI param, prepend sls command with AWS_PROFILE=<profile> when deploying services

It is possible, but then you have to remember the naming convention. For example, frontend deploys with a profile that assumes a role with access only to the S3 bucket for that stage. And entering it by hand leaves it open to mistakes/typos, something the provider.profile setting avoided.

Maybe I did not stress the fact that each stage comes with its own sls deployment role/corresponding profile.

> And if you'd prefer to have AWS_DEFAULT_PROFILE set per service and not for user globally. Then you can put it into .env file, which technically can also be versioned in repository (so effect would be same as now when storing this value in serverless config)

That would break the CI/CD deploy, since serverless will find and load those .env files, correct? Unless I "override" them by temp-deleting them during the build. And at any rate, I cannot do this for dev stages, because stage names are left at developer's whim.

**Comment by medikoo** [comment] 2021-03-02 15:21
> for dev being something along the lines of deploy-app-${self:provider.stage} (backend sls profile) or deploy-frontend-${self:provider.stage} (frontend sls profile).

So in that case, it probably can be solved by same script which does `~/.aws` setup. It can also create `.env.<stage>` files in the service folder, through which AWS profile will be chosen depending on stage (?)

> That would break the CI/CD deploy, since serverless will find and load those .env files, correct? 

True, and anyway versioning `.env` doesn't feel right. Still it can be generated for service folder by script as above.

**Comment by danmoore83** [comment] 2021-06-30 21:56
I had a similar use case as coyoteecd, where we wanted to have a profile set in serverless config, so it was easy for developers who generate temporary credentials from AWS using specific profile names. We also used seperate profiles used for each stage.

Whereas in our CI/CD  (Bamboo) we didnt want to use that same profile setup.
Originally i wanted to use solely was AWS_ACCESS_KEY_ID & AWS_SECRET_ACCESS_KEY environment variables, however that wasnt possible when specifying a profile.

How i achieved it was:

Serverless.yml
`profile: ${self:custom.profiles.${self:provider.stage}}`

Bamboo Deploy script:
```
echo "create aws credentials profile"
export AWS_ACCESS_KEY_ID=${bamboo.access.key}
export AWS_SECRET_ACCESS_KEY=${bamboo.secret.password}

serverless config credentials --provider aws --key "$AWS_ACCESS_KEY_ID" --secret "$AWS_SECRET_ACCESS_KEY" --profile bamboo

echo "Deploy with bamboo profile"
yarn deploy --aws-profile bamboo --verbose

```

I assume the above approach would work with other CI/CD pipelines

**Comment by medikoo** [comment] 2021-07-01 07:31
> so it was easy for developers who generate temporary credentials from AWS using specific profile names

@danmoore83 we plan to [deprecate `provider.profile` setting](https://github.com/serverless/serverless/issues/8356). 
Have you considered relying on `AWS_PROFILE` env var instead and `.env.<stage>` files?

**Comment by coyoteecd** [comment] 2021-07-06 17:19
@danmoore83 What you described causes the CI/CD pipeline to have side-effects (the config credentials modifies the aws/config on the server). But it is a valid workaround, at least while the provider.profile setting is still there.

**Comment by coyoteecd** [comment] 2021-07-06 17:50
Another workaround that does not have side-effects (but still relies on the deprecated profile setting) which I've successfully tried is to convert serverless.yml to TypeScript. This way I have direct access to the args via `process.argv`, so I can override the profile myself as follows:

```serverless.ts
import type { AWS } from '@serverless/typescript';

// Override profile via CLI param
const profile = process.argv.includes('--no-aws-profile') ? undefined : 'profile-example-stack-${self:provider.stage}';

const serverlessConfig: AWS = {
  service: 'example'
  plugins: [
    'serverless-s3-sync'
  ],
  provider: {
    name: 'aws'
    stage: '${opt:stage, "dev"}'
    region: '${opt:region, "us-east-1"}'
    profile,

  custom: {
    s3Sync: [{
      bucketName: '${cf:backendstack.WebsiteBucketName}',
      localDir: dist
    }]
  }
};

module.exports = serverlessConfig;
```
