### ISSUE TITLE
Request: CLI command for printing computed variables

### ISSUE THREAD

**Issue by marshall007** [serverless/serverless#4125] opened 2017-08-18 19:32 UTC
# Feature Proposal

## Description

I may have missed something, but I haven't found a way to debug the result of various templated variables in `serverless.yml`. It would be nice if there were a CLI command that simply read through all the configuration, computes all templated values, and dumps the resulting YAML and/or JSON.

This would help debug complex variable configurations.

For example, given the following `serverless.yml` template:

```yaml
service: my-service

custom: ${file(config.yml):${opt:stage, self:provider.stage}}

provider:
  name: aws
  runtime: nodejs6.10
  stage: dev
  profile: ${self:custom.aws_profile}
  timeout: 15
  environment:
    S3_BUCKET: ${self:custom.s3_bucket}
  apiKeys:
    - "${self:custom.api_key}"

# ...
```

I would want to see the this kind of output:

```yaml
opt: ...
env: ...
cf: ...
self:
  service: "my-service"
  custom:
    s3_bucket: "my-s3-bucket"
    api_key: "TEST_API_KEY"
    aws_profile: "test"
  provider:
    # ...
    environment:
      S3_BUCKET: "my-s3-bucket"
    apiKeys:
      - "TEST_API_KEY"
```

**Comment by marshall007** [comment] 2017-08-18 19:36
Somewhat related to #1260.

**Comment by cardoni** [comment] 2017-08-18 22:39
In the meantime, @marshall007, you can get something close to what you'd like right now:

1. Download / install [`jq`](https://stedolan.github.io/jq/).  If you're on macOS and have [homebrew](https://brew.sh/) installed, run: 

        brew update && brew install jq

2. Run this in your project directory:

        serverless package && jq "{service}" .serverless/serverless-state.json

The `sls package` command will create a fresh `serverless-state.json` in its own `.serverless/` folder within your project root. The `jq` query sucks out and pretty-prints the `service` section of the json file.

**Comment by pmuens** [comment] 2017-08-19 16:43
Thanks for creating @marshall007 and thanks for commenting @cardoni 👍

I'll close this one since it's a duplicate of https://github.com/serverless/serverless/issues/3224 and we'll continue the discussion over there. I'll cross-link this issue in #3224 so that we don't lose the good conversation here.

**Closed by pmuens** 2017-08-19 16:43 UTC
Labels: kind/feature, status/help-wanted
