### ISSUE TITLE
Invoke local AWS function ImportValue, GetAtt, Ref resolution

### ISSUE THREAD

**Issue by fredericbarthelet** [serverless/serverless#8147] opened 2020-08-28 12:34 UTC
### Use case description

Considering the following function configuration :
```
myFunction:
  handler: myHandler.main
  environment:
    stringEnv: 'myEnv'
    importValueEnv:
      Fn::ImportValue: 'import-key' 
    getAttEnv:
      Get::Att: ['resource', 'arn']
```

Invoking this function locally will not resolve AWS functions before inserting those in lambda env context : `process.env.importValueEnv` and `process.env.getAttEnv` will be object. In order for this function to be invoked locally properly, one would have to run the following command :

`sls invoke local -f myFunction -e importValueEnv="import-value" -e getAttEnv="resourceArn"`

where `import-value` and `resourceArn` have to be manually retrieved (through the AWS web console for exemple).

### Proposed solution

Resolving AWS magical functions when found within function or provider environment configuration.

Modifying existing `getConfiguredEnvVars` function at https://github.com/serverless/serverless/blob/ffd1b362621ba01ee3e423a9483178927c73583d/lib/plugins/aws/invokeLocal/index.js#L146-L150 by using `/Users/Frederic/Sites/serverless/lib/plugins/aws/utils/resolveCfImportValue.js`

After such feature, it won't be needed to override manually AWS resolvable env variable and the following command `sls invoke local -f myFunction` will work out of the box.

The issue could be split in :
- implementing this solution for Fn::ImportValue
- implementing the util for GetAtt resolution and implementing it in invoke local env resolution
- implementing the util for any other required AWS magical function resolution ( Ref especially ? ) and implementing it in invoke local env resolution

**Comment by medikoo** [comment] 2020-08-28 12:52
@fredericbarthelet this feels as duplicate of https://github.com/serverless/serverless/issues/7087 which has open PR here: https://github.com/serverless/serverless/pull/7147

Did you have a chance to look into it?

**Comment by fredericbarthelet** [comment] 2020-08-31 09:03
Thanks for the link @medikoo I'll have a look

**Comment by medikoo** [comment] 2020-08-31 11:21
Sure, if you feel it's a duplicate please close the issue, otherwise let's elaborate :)

**Comment by medikoo** [comment] 2020-09-07 10:15
To avoid confusion, I'm going to close it as duplicate of #7087, at least in my eyes, it's exactly about same thing

**Closed by medikoo** 2020-09-07 10:15 UTC
Labels: question
