### ISSUE TITLE
Multiple Endpoints to same lambda?

### ISSUE THREAD

**Issue by radhomero** [serverless/serverless#278] opened 2015-10-29 11:06 UTC
Hi,

I'm working on a Lambda for an API GET method, and I want to use the path variables to make the request more specific if needed.

Example: `/specialReport/{year}` and `/specialReport/{year}/{month}`

So I know how to pass the path variables to the Lambda through the API Gateway integration, but what I can't find is how to repeat my Lambda code to the 2 paths above. To API Gateway, the former resource Endpoint is different than the latter, so I just have 1 GET method deployed.

Any tips?

**Comment by eahefnawy** [comment] 2015-10-29 11:50
that's an interesting use case! right now since CloudFormation doesn't support API Gateway, we're mocking the process with our own template. To make it work for your case, I think we need to have an **array of paths** or something, in the `lambda.awsm.json` file.

For now, you either have to do it manually with the AWS console, or duplicate the lambda. Not a great, sorry! :D

**Comment by radhomero** [comment] 2015-10-29 18:03
Good and bad news:

I was able to copy my awsm.son config file to other folders besides my original Lambda API, repeating the Lambda path, and the deploy just went ok! Multiple Endpoints for a single Lambda.

BUT, JAWS was only able to set permission for just 1 Resource to access my single Lambda (each Endpoint deploy replaced the last).

The funny thing is, if I set each Endpoint via the API Gateway console, all Endpoints could reach the same Lambda successfully.

**Comment by eahefnawy** [comment] 2015-10-29 21:36
oh yeah right! I guess that's an expected behavior from the current codebase. This was bit of a hack, so not really recommended. The best thing you could do now is define your API endpoint through the management console till we figure this out. Thanks for trying it out! ;)

**Comment by alexwillingham** [comment] 2015-11-18 20:55
I think an array of paths as described by @eahefnawy above would also help solve the CORS issues folks are having: https://github.com/jaws-framework/JAWS/issues/222

With an array of paths, one could make a "no-op" jaws module of type OPTIONS, and deploy it to multiple resource paths with CORS headers

```
"responseParameters": {
   "method.response.header.Access-Control-Allow-Headers": "'Content-Type,X-Amz-Date,Authorization,x-api-key,x-amz-security-token'",
   "method.response.header.Access-Control-Allow-Methods": "'POST, OPTIONS'",
   "method.response.header.Access-Control-Allow-Origin": "'*'"
},
```

enabling CORS for multiple endpoints.

**Comment by ac360** [comment] 2015-11-19 05:41
:+1:  If we allow multiple paths, that will force people to use all of the other same configurations.

I think the best way to handle it is to have the `apiGateway` property accept an array.

**Comment by kennu** [comment] 2015-11-19 13:25
Ran into the same issue in my first JAWS project; not too keen on creating a separate Lambda for every individual HTTP method. I'd rather have one Lambda for one service which connects to the database and performs several CRUD operations with it.

**Comment by alexwillingham** [comment] 2015-11-19 14:42
apiGateway array suits me well :+1:  It's a great point that the CORS 'everything the same but the path' need may be a very special case.

**Comment by kennu** [comment] 2015-11-19 23:44
Btw, I noticed that Lambda/API Gateway resources are treated specially, as you can modify and re-deploy them at any time. Meanwhile, if you want to add a module that creates some other types of resources (in my case, a S3 bucket and CloudFront distribution for the static parts of the website), the only way to modify and redeploy these resources is to rm -rf that module from aws_modules and run the npm postinstall script again so that awsm.json is re-merged. Any plans to make resources more equally treated in AWSM modules? Or am I missing something obvious?

**Closed** 2016-03-27 11:49 UTC
Labels: enhancement
