### ISSUE TITLE
Bitbucket pipeline fail

### ISSUE THREAD

**Issue by teddynted** [serverless/serverless#5932] opened 2019-03-16 09:04 UTC
My pipeline just started failing out of the blue, I didn't install any new package nor make to the yaml file

I am getting this error:

ENOENT: no such file or directory, stat '/opt/atlassian/pipelines/agent/build/.serverless/.serverless/yalu.zip'

**Comment by ReidWeb** [comment] 2019-03-16 16:11
Looks like a duplicate of #5928 - the issue not being with your BB pipeline, but the version of serverless you are using - roll back to using an older version for now.

```
yarn global add serverless@1.38.0
```
or
```
npm install -g serverless@1.38.0
````

**Comment by teddynted** [comment] 2019-03-18 08:49
Hey ReidWeb,

Thanks for your timeous response, my serverless package is 1.26.1.

**Comment by teddynted** [comment] 2019-03-18 09:20
I fixed it by changing serverless to serverless@1.37.1, Thanks ReidWeb.

**Comment by pmuens** [comment] 2019-03-18 10:16
Just reverted #4188 which seems to be the root cause. Patch release should be out in ~30 minutes...

**Closed** 2019-03-18 10:24 UTC
Labels: bug, cat/packaging
