### ISSUE TITLE
DX: Verify if npm install were done before an sls deploy

### ISSUE THREAD

**Issue by konstantinvlasenko** [serverless/serverless#3270] opened 2017-02-19 17:34 UTC
# This is a Feature Proposal

## Description

For feature proposals:
* **deploy** command should fail if no node_modules
* use _-force_ and if you really want to deploy w/o node_modules
* this will prevent a lot of wrong deployments

**Comment by andymac4182** [comment] 2017-02-20 08:41
A simple solution to this is to use something like `npm deploy` alias instead of using the sls one to handle extra commands. This is also language dependant. Also the location of node_modules is different at different companies as well.

**Comment by pmuens** [comment] 2017-02-20 09:53
Hey @konstantinvlasenko you might also want to look into:

https://github.com/mvila/serverless-plugin-scripts

and

https://github.com/weixu365/serverless-scriptable-plugin

**Comment by konstantinvlasenko** [comment] 2017-02-21 01:25
@andymac4182 Eventually **node_modules** should be inside  a **./serverless/*.zip** file. So we can have it available as a core feature of serverless.

**Comment by andymac4182** [comment] 2017-02-21 04:19
@konstantinvlasenko Personally at the company I work for we don't deploy any node_modules directory. We use webpack to minify the files and combine them to reduce the package size. I also have some dotnet based services that have some nodejs functions that do basic processing so don't require a `node_modules` directory. Really comes down to how you are personally setting out your code and how your particular situation requires everything to be set out.

**Comment by DavidWells** [comment] 2017-05-18 16:20
I want this too. 

I wonder if there is a way we can make it work with webpack and non webpack users alike...

**Comment by pmuens** [comment] 2017-05-19 05:56
Furthermore we should abstract this later on so that it supports other runtimes as well.

**Comment by washedrepent** [comment] 2019-04-01 15:01
Is their a solution to this. I am in the process of deploying an api via serverless on aws. There will be multiple developers working on the same project. This issue will happen. We have it setup to package each function individually, and since that is the case their will be a node_modules folder for each function. (node_modules are ignored in the git repo.) So if any of the devs pull in the changes but forget to run npm install in each of the function folders (everytime they deploy) they can accidentally deploy functions missing the required dependencies. The lambda functions would then fail and break the application.

**Comment by garethmcc** [comment] 2019-04-02 08:50
@washedrepent One way that steps around the problem is not to have the developers be deploying to shared resources or production. Make it so that if they need to deploy to shared infra they commit and push changes to the git repo on a specific branch for that environment (for example, a `staging` branch for stuff going onto a staging environment) and let an automated build process enforce the process of running `npm install` first before `sls deploy`.

If a developer is deploying to their own AWS environments for their own testing, then if they break it they break just their own stuff not everyone else's and they learn a valuable lesson.

**Comment by medikoo** [comment] 2020-10-01 14:02
Closing, as this is not a thing for which _ultimate_ solution can be found. Many setups do not require `node_modules` and even if, we do not have guarantee that what's installed in `node_modules` is up to date with `package.json`, then confirming that with npm is performance killer etc.

Instead we should simply embrace the practice of automated deployments via CI/CD, as @garethmcc pointed

**Closed by medikoo** 2020-10-01 14:02 UTC
Labels: cat/dx, enhancement, wontfix
