### ISSUE TITLE
Setup with serverless config credentials command fail.

### ISSUE THREAD

**Issue by maxirozay** [serverless/serverless#2921] opened 2016-12-12 13:18 UTC
# This is a Bug Report

## Description

For bug reports:
* What went wrong?
  * When creating a new AWS profile with `serverless config credentials --provider aws --key xxx --secret xxx`, I get the success message then an error says that the credential file doesn't exist (which is true)
* What did you expect should have happened?
  * I expected serverless to create the file.
* What was the config you used?
  * Serverless 1.3.0
* What stacktrace or error message from your provider did you see? 
  * ENOENT: no such file or directory, open '/home/user/.aws/credentials'

For feature proposals:
* What is the use case that should be solved. The more detail you describe this in the easier it is to understand for us.
* If there is additional config how would it look

Similar or dependent issues:

## Additional Data

* ***Serverless Framework Version you're using***: 1.3.0
* ***Operating System***: Linux Solus
* ***Stack Trace***: Serverless: Setting up AWS...
Serverless: Saving your AWS profile in "~/.aws/credentials"...
Serverless: Success! Your AWS access keys were stored under the "default" profile.
 
  Error --------------------------------------------------
 
     ENOENT: no such file or directory, open '/home/user/.aws/credentials'
 
     For debugging logs, run again after setting the "SLS_DEBUG=*" environment variable.
 
  Get Support --------------------------------------------
     Docs:          docs.serverless.com
     Bugs:          github.com/serverless/serverless/issues
 
     Please report this error. We think it might be a bug.
 
  Your Environment Information -----------------------------
     OS:                 linux
     Node Version:       7.2.0
     Serverless Version: 1.3.0
* ***Provider Error messages***: ENOENT: no such file or directory, open '/home/user/.aws/credentials'

**Comment by mthenw** [comment] 2016-12-12 13:34
Duplicate of https://github.com/serverless/serverless/issues/2878. Fix will be released in 1.4 version.

**Closed by mthenw** 2016-12-12 13:34 UTC
