### ISSUE TITLE
Problem with the mapping template value $input.json('$') in the API Gateway POST method Integration Request  (the value of the requestTemplates key in s.function.json in Serverless)

### ISSUE THREAD

**Issue by msteckyefantis** [serverless/serverless#537] opened 2016-01-30 02:49 UTC
### What I want to do: 

Get the JSON body sent through a POST request to an API gateway endpoint, and being able to access it in the event variable of the lambda function at that endpoint.

### My problem: 

The JSON must be stringified if I want to use the $input.json('$') value in the requestTemplate in the s-function.json file.

For example:

In the s-function.json file, you CANNOT do this in Serverless:

**----figure** **A----**

"requestTemplates": {
        "application/json": {  "body" :  $input.json('$')   }
}

In the AWS browser console:

**----figure** **B----**

{  "body" :  $input.json('$')   }

 is how you would enter a mapping template to an API gateway endpoint with a POST request that has a lambda function. The resulting event variable will work like this:

event.body = the JSON body of the POST request

If you try to upload it like in figure A using Serverless, it fails when you try to deploy the endpoint (probably related to the fact that putting the requestTemplate in this form makes the s-function.json file no longer a valid JSON file).

In the Serverlss s-function.json file, I MUST provide the mapping template in this form:

**----figure** **C----**

"requestTemplates": {
        "application/json": "{ \"body\": $input.json('$') }"
}

i.e. the JSON must be stringified before it is put into the requestTemplates in the s-function.json file.

As far as I know, you only have to do this when using the $input.json('$') value in the request template. This is because for this value, you CANNOT put quotations around it in the mapping template, or else it will not work. Check out the AWS instructions for reference:

http://docs.aws.amazon.com/apigateway/latest/developerguide/api-gateway-mapping-template-reference.html

for most (all?) of the other possible variables for the mapping template, you are required to put quotation marks around them, for example:

"requestTemplates": {
     "application/json" :  { "name" : "$input.params('name')"}
}

### My point and my questions:

Will this issue be fixed? That is, will I be able to have my s-function.json file in the form of figure A?

This may not seem like that much of an issue for simple mapping templates with one key-value pair like in figure A or C. But when people want to use Serverless with more complex mapping templates, they have to format them like this all the time. It's a drag and a tedious task, and perhaps something that is worth fixing because it would improve usability and cause less confusion.

**Looking** **at** **http://docs.serverless.com/docs/templates-variables,**

I also tried doing it like in the Serverless documentation creating an s-templates.json in the function folder that has the following as its contents:
{
  "apiGatewayRequestTemplate":   "{ \"body\": $input.json('$') }"
}

and in the s-function.json file:

"requestTemplates":
 {
        "application/json": "$${apiGatewayRequestTemplate}"
  }

this worked in the same way as manually inputing figure B into the integration request mapping template for the API gateway endpoint using the browser. But if the acceptable form for the s-templates.json file were like this:

{
  "apiGatewayRequestTemplate": { ”body” : $input.json('$') }
}

AND/OR once again, if we were able to input the $input.json(‘$') variable like this with no quotations around it in the s-function.json JSON requestTemplate (i.e. without it having to be stringified), that would be super awesome.

Any help would be greatly appreciated, thank you very much for your time!

p.s. Serverless is super cool, and so are the creators of it!!

**Comment by erikerikson** [comment] 2016-01-30 04:22
The problem here is that s-function.json is a JSON file and the possible values for a request template (such as 'application/json') include any valid Apache Velocity document.  Valid JSON documents are a subset of valid Apache Velocity documents.  So it is that without major changes this won't be possible.

I think a possible workaround is creating separate documents with your Apache Velocity document and fs.readFileSync'ing that file in (doing, in effect, the stringification) to a template but that would require a change in how Serverless defines the config files or the creation of a third template type.  ($P{}, $T{}, and now $F{} where P is project, T is template, and F is file).

**Comment by erikerikson** [comment] 2016-01-30 17:06
To get background, see http://docs.aws.amazon.com/apigateway/latest/developerguide/models-mappings.html, search for Apache to find the part where it discusses the content of the integratinos.

There are example templates provided by Amazon that may be of interest.

You will find it just next to a link to the Apache Velocity documentation:
http://velocity.apache.org/engine/devel/vtl-reference-guide.html

To approximate if you're not familiar with VTL, think php/asp/jsp.

**Comment by msteckyefantis** [comment] 2016-01-30 23:08
Okay thanks Erik, I see the issue. And thanks for the reading material, I will take a more in-depth look through it and perhaps I can find some type of solution using the stuff you provided.

Here is a suggestion, perhaps, instead of having an s-templates.json file to specific the mapping template for the API Gateway endpoint using Serverless (or as you suggested having an s-templates.json AND another file). Just have one Apache Velocity document as the s-template file. This would allow users to use JSON given that valid JSON documents are a subset of valid Apache Velocity documents. This would also allow Serverless users like me to use other types of mapping templates that are valid API Gateway integration request mapping templates, instead of having to do these tedious, messy workarounds into to make their mapping templates valid.

**Comment by erikerikson** [comment] 2016-01-30 23:31
I like the thinking although this would further tie Serverless to Amazon.
Not sure exactly what would be required to use it locally.

**Comment by jeremydaly** [comment] 2016-01-31 21:52
I prefer the flexibility of the Apache Velocity Templates, it allows me to do all my variable parsing at the API Gateway level before passing it into my Lambda functions. For application/json requests I use the following:

`"apiGatewayRequestTemplate": {
    "application/json": "{\n  \"body\" : $input.json('$'),\n  \"headers\": {\n    #foreach($header in $input.params().header.keySet())\n    \"$header\": \"$util.escapeJavaScript($input.params().header.get($header))\" #if($foreach.hasNext),#end\n    \n    #end\n  },\n  \"method\": \"$context.httpMethod\",\n  \"params\": {\n    #foreach($param in $input.params().path.keySet())\n    \"$param\": \"$util.escapeJavaScript($input.params().path.get($param))\" #if($foreach.hasNext),#end\n    \n    #end\n  },\n  \"query\": {\n    #foreach($queryParam in $input.params().querystring.keySet())\n    \"$queryParam\": \"$util.escapeJavaScript($input.params().querystring.get($queryParam))\" #if($foreach.hasNext),#end\n    \n    #end\n  }  \n}"
}`

And if I am expecting an application/x-www-form-urlencoded input, I use:

`"apiGatewayRequestTemplatePOSTVAR": {
    "application/x-www-form-urlencoded": "{\n  \"body\" : {\n    #foreach($keypair in $input.path('$').split(\"&\"))\n      \"$util.urlDecode($keypair.split(\"=\")[0])\":\"$util.escapeJavaScript($util.urlDecode($keypair.split(\"=\")[1]))\" #if($foreach.hasNext),#end\n    #end\n  },\n  \"headers\": {\n    #foreach($header in $input.params().header.keySet())\n    \"$header\": \"$util.escapeJavaScript($input.params().header.get($header))\" #if($foreach.hasNext),#end\n    \n    #end\n  },\n  \"method\": \"$context.httpMethod\",\n  \"params\": {\n    #foreach($param in $input.params().path.keySet())\n    \"$param\": \"$util.escapeJavaScript($input.params().path.get($param))\" #if($foreach.hasNext),#end\n    \n    #end\n  },\n  \"query\": {\n    #foreach($queryParam in $input.params().querystring.keySet())\n    \"$queryParam\": \"$util.escapeJavaScript($input.params().querystring.get($queryParam))\" #if($foreach.hasNext),#end\n    \n    #end\n  }  \n}"
}`

**Comment by hobbs** [comment] 2016-01-31 22:27
Great example @jeremydaly (and I'm stealing that template for my projects :smile:). I think the main pain point with these templates is the escaped quotes and \n\t formatting, etc. So I like the idea of supporting blob partials with the $${template} or explicity having VTL templates

**Comment by msteckyefantis** [comment] 2016-02-01 03:11
@hobbs: "the main pain point with these templates is the escaped quotes and \n\t formatting, etc."

Yes, I think that is a good way of describing the situation @hobbs.

**Comment by rentrop** [comment] 2016-04-20 22:06
+1 just ran into this problem using the `$util.urlDecode`-function.

I ended up using:
"requestTemplates": {
        "application/json": "{ \"json\": $util.urlDecode($input.params().querystring.json) }"
      }

Here is the full Q&A on SO
http://stackoverflow.com/questions/36748324/how-to-pass-a-json-string-to-api-gateway-as-query-parameter/36754695#36754695

**Comment by HyperBrain** [comment] 2016-04-20 22:20
Instead of the stringify hell you also can use a `s-templates.yaml` instead of the `s-templates.json` and put your stuff just in there (including VTL) - since 0.5.5:

Then reference it in your `s-function.json` just with:
```
"requestTemplates": "$${myRequestTemplate}"
```

Sample:
```
myRequestTemplate:
  application/json: |
    #set($inputRoot = $input.path('$'))
    {
      "userId": "$input.params('userId')"
    #set( $limit = $input.params('limit') )
    #if( $limit.toString() != "" )
      ,"limit": "$input.params('limit')"
    #end
    #set( $skip = $input.params('skip') )
    #if( $skip.toString() != "" )
      ,"skip": "$input.params('skip')"
    #end
    }
```

**Comment by rentrop** [comment] 2016-04-21 09:52
That is great! Thank you so much. Also for your example on how to a) use it and b) how to use if.

**Comment by eahefnawy** [comment] 2016-04-22 05:06
@HyperBrain this awesome PR you submitted that makes this work should be documented! Sorry about that! This looks beautiful!

FYI, here's a teaser: we've decided to completely switch to YAML in v1 😉

**Comment by flomotlik** [comment] 2016-05-11 12:51
I'm closing this issue for now as it seems it was resolved.

**Closed by flomotlik** 2016-05-11 12:51 UTC

**Comment by amkuipers** [comment] 2019-07-10 12:13
https://docs.aws.amazon.com/apigateway/latest/developerguide/api-gateway-mapping-template-reference.html

**Comment by khordoo** [comment] 2023-04-04 02:07
For those who are working with the SAm template and Python, I can confirm that this works:

```
              x-amazon-apigateway-integration:
                type: aws
                uri: !Sub arn:aws:apigateway:${AWS::Region}:lambda:path/2015-03-31/functions/${WebhookLambda.Arn}/invocations
                httpMethod: POST
                passthroughBehavior: when_no_match
                requestTemplates:
                  application/json: >
                    {
                      "body": "$util.base64Encode($input.body)",
                      "headers": {
                        #foreach($param in $input.params().header.keySet())
                        "$param": "$util.escapeJavaScript($input.params().header.get($param))"
                        #if($foreach.hasNext),#end
                        #end
                      }
                    }
```
and in your lambda:

```
stripe_webhook_secret = 'YOUR_WEBHOOK_SECRET'.   # See note below
def lambda_handler(event, context):
    print('Webhook event received. :', event)
    header_signature = event['headers']['Stripe-Signature']
    body_str = base64.b64decode(event['body']).decode('utf-8')
    try:
        event = stripe.Webhook.construct_event(
            body_str, header_signature, stripe_webhook_secret
        )
    except ValueError:
        print('invalid payment')
        return {
            'statusCode': 400,
            'body': json.dumps({'error': 'Invalid payload'}),
            'headers': {'Content-Type': 'application/json'}
        }
    except stripe.error.SignatureVerificationError:
        print('invalid signature')
        return {
            'statusCode': 400,
            'body': json.dumps({'error': 'Invalid signature'}),
            'headers': {'Content-Type': 'application/json'}
        }
    print('Successfully verified the payment signature')
```
Also in the stripe console, DO not copy the small text that looks like a signing key in front of the webhook ULR. Make sure You click on `reveal secret` to show the webhook signing key and use that in your code
