### ISSUE TITLE
IntegrationRequest and IntegrationResponse are not deployed

### ISSUE THREAD

**Issue by vlamic** [serverless/serverless#382] opened 2015-12-15 10:14 UTC
Hi,

When I'm deploying my function the IntegrationRequest and IntegrationResponse are not deployed (`sls function deploy -s dev`). I have installed the latest version of serverless today and it's the same issue. I've been using jaws before and it worked fine there.

Let me know if you need more info.

Best,
Vlad

**Comment by yaochen** [comment] 2015-12-15 14:29
from what i see, 

```
cat ~/.node/lib/node_modules/serverless/lib/actions/EndpointBuildApiGateway.js | grep -in requestParameter
148:    if (!evt.endpoint.requestParameters) { <- this guy was fixed
149:      throw new SError('Endpoint does not have a "requestParameters" property');
334:        requestParameters = {};
337:    if (endpoint.RequestParameters) { <-- this guy was not
340:      for (let prop in endpoint.requestParameters) {
341:        let requestParam                = endpoint.requestParameters[prop];
342:        requestParameters[requestParam] = true;
378:                  requestParameters:  requestParameters
394:            requestParameters:  requestParameters
442:      requestParameters:      endpoint.requestParameters || {},
```

it looks like @ac360 fixed one of the capitalization issues but missed the other; i think this is the cause.

if you want, @vlamic revert back to .12 and use this workaround in https://github.com/serverless/serverless/issues/366

**Comment by ac360** [comment] 2015-12-15 16:45
Thanks Vlad.  I'll look into this today.  Sorry for the inconvenience.

**Comment by eahefnawy** [comment] 2015-12-18 06:53
@vlamic we're currently investigating this issue ... could you clear up a little what exactly of the `s-function.json` that doesn't get deployed? I'm guessing you mean `responseTemplates` but I can't reproduce. It seem to be working for me.

**Closed** 2016-04-04 01:45 UTC
Labels: bug
