### ISSUE TITLE
ECMAScript modules template without transpiling

### ISSUE THREAD

**Issue by nponeccop** [serverless/serverless#9283] opened 2021-04-09 18:35 UTC
### Use case description

- I want to write code using the ECMAScript modules (`export`/`import`) instead of CommonJS modules (`module.exports`/`require`)
- I don't want to use any transpilers such as `babel` 
- I want to use the native support present in recent NodeJS. E.g. the 14.x runtime does have it, so why not?

### Proposed solution

I have made a sample project: [nponeccop/serverless-openapi-templates/esmodules/][1]

Key findings:

- The AWS 14.x runtime does already support working with the newer and better module syntax
- Direct imports of ES modules are supported neither by AWS nor by `serverless-offline`
- An indirect import does work:
   - we write the `esm/handler.js` module using the ES syntax
   - to tell `node` that it's ES we need a folder with a fake `package.json` with `type: module` in it
   - we use a separate async `import()` call in `wrapesm.js`
- It does work in both live AWS and in `serverless-offline`
- AWS `BilledDuration` is 1500ms ~~for a yet unknown reason~~; `serverless offline` shows ~28 ms which is what you normally 

[1]: https://github.com/nponeccop/serverless-openapi-templates/tree/f756e9721f86663c9fbe46d6c25889a4cdf84525/esmodules

Upd: performance is fixed. ~5ms in both `serverless-offline` and AWS

**Comment by medikoo** [comment] 2021-04-12 08:22
> Direct imports of ES modules are supported neither by AWS

@nponeccop if that's the case, then I believe we cannot do anything about it (introducing ESM -> CJS transpilation for lambda packages is definitely not on a table)

Still, we can ensure that ESM is supported for input `serverless.js` configuration file. If Node.js supports that natively, Framework should also. That may require adding conditional logic and reading `package.json` to know whether `serverless.js` is ESM or not, as in ESM case I believe we need to use `import` function to load module

**Comment by nponeccop** [comment] 2021-04-12 11:32
> introducing ESM -> CJS transpilation for lambda packages is definitely not on a table

The transpilation approach already works btw. My point is that it isn't needed. 

The example project works as is, without any transpilation. The only thing it needed was a small wrapper, I only want that piece of knowledge to be more visible - e.g. to make a template, or a blog post, or put it into documentation.

**Comment by o5** [comment] 2021-08-31 16:03
@nponeccop I would like to use `export/import` without plugins like `serverless-plugin-typescript`. It looks like `serverless-offline` is needed in your linked sample project, or not? Because I get this error when I try to locally invoke.

```
Error [ERR_REQUIRE_ESM]: Must use import to load ES Module: /src/uep/handler.js
require() of ES modules is not supported.
require() of /src/uep/handler.js from /usr/local/lib/node_modules/serverless/lib/plugins/aws/invokeLocal/index.js is an ES module file as it is a .js file whose nearest parent package.json contains "type": "module" which defines all .js files in that package scope as ES modules.
Instead rename handler.js to end in .cjs, change the requiring code to use import(), or remove "type": "module" from /src/uep/package.json.

    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1089:13)
    at Module.load (internal/modules/cjs/loader.js:937:32)
    at Function.Module._load (internal/modules/cjs/loader.js:778:12)
    at Module.require (internal/modules/cjs/loader.js:961:19)
    at require (internal/modules/cjs/helpers.js:92:18)
    at AwsInvokeLocal.invokeLocalNodeJs (/usr/local/lib/node_modules/serverless/lib/plugins/aws/invokeLocal/index.js:773:33)
    at AwsInvokeLocal.invokeLocal (/usr/local/lib/node_modules/serverless/lib/plugins/aws/invokeLocal/index.js:240:19)
    at Object.invoke:local:invoke [as hook] (/usr/local/lib/node_modules/serverless/lib/plugins/aws/invokeLocal/index.js:50:47)
    at PluginManager.invoke (/usr/local/lib/node_modules/serverless/lib/classes/PluginManager.js:579:20)
    at async PluginManager.run (/usr/local/lib/node_modules/serverless/lib/classes/PluginManager.js:639:7)
    at async Serverless.run (/usr/local/lib/node_modules/serverless/lib/Serverless.js:452:5)
    at async /usr/local/lib/node_modules/serverless/scripts/serverless.js:751:9 {
  code: 'ERR_REQUIRE_ESM'
}

 Serverless Error ----------------------------------------

  Exception encountered when loading /src/uep/handler

  Get Support --------------------------------------------
     Docs:          docs.serverless.com
     Bugs:          github.com/serverless/serverless/issues
     Issues:        forum.serverless.com

  Your Environment Information ---------------------------
     Operating System:          linux
     Node Version:              14.17.5
     Framework Version:         2.56.0
     Plugin Version:            5.4.4
     SDK Version:               4.3.0
     Components Version:        3.16.0
```

I have both of `package.json` with `type:module` which I hoped does this trick.

**Comment by razor-x** [comment] 2021-12-30 05:50
I am working around this by putting all of my handler entry points in their own folder with an "empty" package.json. If you want ES modules in the same folder as the handlers, you can use the .mjs extension. For a working example, see https://github.com/makenew/serverless-nodejs/blob/fa148a9dd210c21736c84014c32f6da151176aba/handlers/todo.js

**Comment by nponeccop** [comment] 2022-01-01 21:12
@o5
> I have both of `package.json` with `type:module` which I hoped does this trick.

The outer package can't have `type: module`. That is the trick. Just use the repo as is. `sls offline` isn't needed but works.

**Comment by ZebraFlesh** [comment] 2022-01-07 17:00
Lambda now offers native support for ESM and top-level await: https://aws.amazon.com/about-aws/whats-new/2022/01/aws-lambda-es-modules-top-level-await-node-js-14/

**Comment by medikoo** [comment] 2022-01-07 17:11
Indeed, AWS now supports ESM as an entry point, and we can take advantage of top-level await for more sophisticated lambda initialization.

I'm closing this issue, as Framework supports that out of a box, you just need to follow AWS instructions and add `package.json` with `"type": "module"` aside of lambda handler, and ensure you're relying on `nodejs.14x`  runtime (which will be the default in v3).

**Closed by medikoo** 2022-01-07 17:11 UTC
Labels: documentation, cat/lambda

**Comment by dkebler** [comment] 2022-01-12 04:29
"Framework supports that out of a box, you just need to follow AWS instructions and add package.json with "type": "module" aside of lambda handler, and ensure you're relying on nodejs.14x runtime (which will be the default in v3)."

I've done all three with 2.71 and it's not working local or deployed (same esm error).  Do I need to be running V3?  If so how do I get that loaded.  Tried checking out V3 branch but it still says 2.71.   V3 is not at npm.

**Comment by medikoo** [comment] 2022-01-12 11:21
> I'd already done as you say before with 2.71 and it's not working local or deployed (same esm error) that's why I ended up here. 

Inspect in AWS console how your lambda is packaged (whether `package.json` is actually included, and configured properly, and that you're relying on node14.x runtime).

It just goes down to packaging `package.json` file, which was always done, so it'll work with v2 and v3 (pre-install version can be installed via `npm install serverless@pre-3`).

Additionally inspect wether the issue is not created by any of the plugins you rely on

**Comment by zirkelc** [comment] 2022-02-26 08:23
I'm also facing an issue with support for ESModules in Serverless. I created the following test project with the Typescript starter templates `sls create -aws-nodejs-typescript`: https://github.com/zirkelc/serverless-esm-test

I added `"type": "module"` to the `package.json`, switched the module export of `serverless.ts` to `export default serverlessConfiguration;`, and set `"module": "ES2022"` in `tsconfig.json`.

When I run `sls package`, I get the following error:

![2022-02-26_09-16-23](https://user-images.githubusercontent.com/950244/155835871-0ee256c8-4481-4265-ab3e-c84970a0f8fd.png)

**Comment by pgrzesik** [comment] 2022-02-27 22:22
Hey @zirkelc - ES Modules are supported for your lambda code, not for the `serverless.ts` configuration format file at the moment

**Comment by zirkelc** [comment] 2022-02-28 06:44
@pgrzesik are there any plans to support it any time soon? Or are you aware of any workarounds?

**Comment by pgrzesik** [comment] 2022-02-28 10:43
No immediate plans and I'm personally not aware of any workarounds, but maybe someone with more knowledge in the area will be able to suggest something in this thread

**Comment by alexcroox** [comment] 2022-06-24 21:06
Still looking to resolve this. Has anyone got it working or know of an alternative packager that supports modern ESM? 

I'm not using typescript or bundling in anyway and I get this error:

```
service: exchange-api
frameworkVersion: '3'

provider:
  name: aws
  runtime: nodejs16.x

plugins:
  - serverless-offline

functions:
  api:
    handler: src/lambda.handler
    events:
      - http:
          path: /{proxy+}
          method: ANY
          cors: true
```

```
✖ require() of ES Module /Users/alex/Projects/exchange/server-esm/src/lambda.js from /Users/alex/Projects/exchange/server-esm/node_modules/serverless-offline/dist/lambda/handler-runner/in-process-runner/InProcessRunner.js not supported.
  Instead change the require of lambda.js in /Users/alex/Projects/exchange/server-esm/node_modules/serverless-offline/dist/lambda/handler-runner/in-process-runner/InProcessRunner.js to a dynamic import() which is available in all CommonJS modules.
✖ Error [ERR_REQUIRE_ESM]: require() of ES Module /Users/alex/Projects/exchange/server-esm/src/lambda.js from /Users/alex/Projects/exchange/server-esm/node_modules/serverless-offline/dist/lambda/handler-runner/in-process-runner/InProcessRunner.js not supported.
```

**Comment by pgrzesik** [comment] 2022-06-24 21:22
Hey @alexcroox - the issue you're running into is a bit different - in your case adding `"type": "module"` in `package.json` should do the trick

**Comment by alexcroox** [comment] 2022-06-24 21:26
@pgrzesik already have that thanks. I'm using serverless offline and I believe I'll have to wait for this PR to be merged https://github.com/dherault/serverless-offline/pull/1397

**Comment by pgrzesik** [comment] 2022-06-24 21:32
No worries @alexcroox, but yeah, it seems like it's `serverless-offline`-related issue there
