### ISSUE TITLE
Must explicitly use `--stage` for `${opt:stage}` to work

### ISSUE THREAD

**Issue by flux627** [serverless/serverless#3210] opened 2017-02-08 12:15 UTC
# This is a Bug Report

## Description

* What went wrong?
When using `${opt:stage}` in my `serverless.yml`, I get an error if I don't use `--stage` when deploying.

* What did you expect should have happened?
I expect it to use the default (`dev`) when I don't explicitly use `--stage`

* What was the config you used?
I am trying to get versioning to only be applied to production, like so:

```
custom:
  ...
  dev_versioning: false
  prod_versioning: true

...

provider:
  ...
  versionFunctions: ${self:custom.${opt:stage}_versioning}
```

* What stacktrace or error message from your provider did you see?
```
  Serverless Error ---------------------------------------

     Trying to populate non string value into a string for
     variable ${opt:stage}. Please make sure the value of
     the property is a string.
```

* ***Serverless Framework Version you're using***: 1.6.0
* ***Operating System***: OSX 10.12.2 Sierra

**Comment by andymac4182** [comment] 2017-02-08 12:24
`${opt:stage}` loads from the options provided to the CLI. If you want it to default to something you need to provide that. 

Something like `${opt:stage, self:provider.stage}` will probably provide what you are looking for.

**Comment by pmuens** [comment] 2017-02-08 12:29
Thanks for jumping in @andymac4182 👍 

Yes, that should solve the problem (assuming you've defined the `stage` in the `provider` section).

**Comment by eahefnawy** [comment] 2017-02-08 13:26
@flux627  yep as @andymac4182 mentioned, this is by design.

Thanks for reaching out 🙌 ... Closing...

**Closed by eahefnawy** 2017-02-08 13:26 UTC
Labels: status/more-info-needed
