### ISSUE TITLE
Serverless shows offline not installed even after installing offline

### ISSUE THREAD

**Issue by farzidev** [serverless/serverless#6247] opened 2019-06-13 09:06 UTC
* ***Operating System***: Mac os mojave
* ***Stack Trace***:
* ***Provider Error messages***: 

  Serverless Error ---------------------------------------
 
  Serverless command "offline" not found. Did you mean "config"? Run "serverless help" for a list of all available commands.
 
  Get Support --------------------------------------------
     Docs:          docs.serverless.com
     Bugs:          github.com/serverless/serverless/issues
     Issues:        forum.serverless.com
 
  Your Environment Information ---------------------------
     OS:                     darwin
     Node Version:           10.16.0
     Serverless Version:     1.45.1
 

<img width="491" alt="Screenshot 2019-06-13 at 2 14 33 PM" src="https://user-images.githubusercontent.com/50396017/59419445-96983f80-8de8-11e9-9f6d-ca7659a3c74b.png">

**Comment by pmuens** [comment] 2019-06-17 11:24
Hey @farzidev thanks for opening.

Can you share your `serverless.yml` file? Thanks!

**Comment by GreatEarl** [comment] 2020-02-07 05:43
I'm facing the same issue on Win, is there any update on that?

**Comment by shantanu-saag** [comment] 2020-03-23 08:25
Please check your serverless.yml file. There might be a problem with indentation or spacing.Post here if the problem is not resolved.

**Comment by arslanalidev** [comment] 2021-03-17 07:35
I am still facing the same issue on **Mar, 2021**
Can anyone let me know how to resolve it?

**Comment by pgrzesik** [comment] 2021-03-17 08:03
Hello @arslanalidev - what version of the Framework and plugin are you using?

**Comment by arslanalidev** [comment] 2021-03-17 10:31
Framework Core: 2.30.2
Plugin: 4.5.1
SDK: 4.2.0
Components: 3.7.4 

> Hello @arslanalidev - what version of the Framework and plugin are you using?

**Comment by pgrzesik** [comment] 2021-03-17 10:39
@arslanalidev Could you also share what version of `serverless-offline` are you using and the problematic `serverless.yml` configuration with all sensitive parts masked out?

**Comment by arslanalidev** [comment] 2021-03-17 11:37
I got it. My issue is fixed
Thank You so much

> @arslanalidev Could you also share what version of `serverless-offline` are you using and the problematic `serverless.yml` configuration with all sensitive parts masked out?

**Comment by pgrzesik** [comment] 2021-03-17 11:41
Happy to hear that :partying_face: I'm going to close this issue as it seems to be outdated.

**Closed by pgrzesik** 2021-03-17 11:41 UTC
Labels: bug, cat/local-dev

**Comment by gowthamkumard** [comment] 2021-04-09 11:52
> I got it. My issue is fixed
> Thank You so much
> 
> > @arslanalidev Could you also share what version of `serverless-offline` are you using and the problematic `serverless.yml` configuration with all sensitive parts masked out?

what was issue, how did u fix it?

**Comment by araratmartirossyan** [comment] 2021-09-02 14:23
Same here, i don't know how to fix this issue
