### ISSUE TITLE
Exit status for deploy

### ISSUE THREAD

**Issue by sebastianarena** [serverless/serverless#6441] opened 2019-07-24 23:58 UTC
# This is a Bug Report

## Description

- What went wrong?
Run `serverless deploy` and failed for reasons not important to this bug report
The exit code in BASH for the failure was still 0, like nothing happened

- What did you expect should have happened?
The exit code of anything you run throw the `serverless` command should be not 0 in case of an error

- What was the config you used?
Doesn't matter, even a failed config should work in this case as a failed `serverless deploy` should throw some sort of error code, not 0

## Additional Data

- **_Serverless Framework Version you're using_**:
1.48.2 (Enterprise Plugin: 1.3.2, Platform SDK: 2.0.4)

- **_Operating System_**:
macOS, Linux

**Comment by ahanoff** [comment] 2019-07-25 03:22
Happened to me as well, invalid role assignment, but deploy marked as successful

**Comment by manchuck** [comment] 2019-07-25 18:13
I can reproduce this every time a promise fails

**Comment by manchuck** [comment] 2019-07-25 18:23
This has been present since 1.48.1. Downgrading to 1.48.0 reports the correct error code

**Comment by ndanielsen** [comment] 2019-07-26 19:57
Agree. Coming over here to create this issue.

**Comment by jpic** [comment] 2019-08-01 20:13
Still present in 1.49.0 (Enterprise Plugin: 1.3.5, Platform SDK: 2.1.0)

**Comment by medikoo** [comment] 2019-08-05 11:42
I've investigated that, and found out, it happens only with [serverless-offline](https://github.com/dherault/serverless-offline), and it's due to implied [reset of `unhandledRejection` events](https://github.com/dherault/serverless-offline/blob/05dd367030ff6ae91aafc7fb4f31263e036559be/src/index.js#L5-L7)

I proposed PR there: https://github.com/dherault/serverless-offline/pull/767

We will also improve handling of promise rejections with another PR, which may also be treated as _partial fix_. Still the complete fix cannot be achieved reliably without merging https://github.com/dherault/serverless-offline/pull/767.

**Comment by kaitlynbrown** [comment] 2019-08-07 21:29
Thank you so much @medikoo this was driving me nuts!

**Comment by rodrigodgm** [comment] 2020-01-30 22:36
This is still happening to me

**Comment by phil-andrews** [comment] 2020-02-17 04:45
I can get the error to stop by setting `package: individually` to false. This seems in line with the JS heap running out of memory. 

I think this is possibly due to recently adding Epsagon. Which forces you to include `node_modules` in the package. Though I could be wrong and not entirely understanding what is being packaged there. I'd check but I'm outta steam today, just wanted to leave a note

**Closed** 2022-06-30 15:57 UTC
Labels: bug, cat/dx
