### ISSUE TITLE
Referencing external files using default stage doesn't work

### ISSUE THREAD

**Issue by trondhindenes** [serverless/serverless#3305] opened 2017-02-27 16:16 UTC
# Bug Report

## Description
When given the following serverless.yaml snippet:
```yaml
provider:
  name: aws
  runtime: python2.7
  stage: dev
functions:
  dump-es:
    handler: handler.run
    events:
      - schedule: rate(5 minutes)
    environment:
      elasticsearch_username: ${file(credentials.yml):${opt:stage}.elasticsearch_username}
      elasticsearch_password: ${file(credentials.yml):${opt:stage}.elasticsearch_password}
```

And the following credentials.yml file:
```yaml
---
prod:
    elasticsearch_username: dumdidum
    elasticsearch_password: lalala
dev:
    elasticsearch_username: deeev
    elasticsearch_password: devvvv
```

Serverless deploy fails unless I expclicitly specifies the stage when deploying.
Expected results: serverless should use the default stage configured, instead of stopping on error

## Additional Data

* ***Serverless Framework Version you're using***: 1.7.0

**Comment by pmuens** [comment] 2017-02-27 16:29
Hey @trondhindenes thanks for reporting. 👍 

Closing this one since it's a duplicate of https://github.com/serverless/serverless/issues/3293

**Closed by pmuens** 2017-02-27 16:29 UTC
Labels: kind/bug
