### ISSUE TITLE
2.32.0 seems to break serverless-jest-plugin's ability to invoke an individual test/function

### ISSUE THREAD

**Issue by aardvarkk** [serverless/serverless#9400] opened 2021-04-29 18:02 UTC
When I run the following command in 2.31.0, it executes a single, individual test/function:

`yarn sls invoke test -f foobar`

However, when I run the same command in 2.32.0, it executes every single test.

<details>
<summary><code>serverless.yml</code></summary>

```yaml
I don't currently have time to create a minimal reproducing YAML file, but I have verified that just changing serverless from 2.31.0 to 2.32.0 causes this to break.
```

</details>

<details>
<summary><b><code>yarn sls invoke test -f foobar</code> output</b></summary>

```
RUNS /__tests__/foobar.test
RUNS /__tests__/helloworld.test
```

</details>

<b>Installed version</b>

```
Framework Core: 2.32.0 (local)
Plugin: 4.5.3
SDK: 4.2.2
Components: 3.9.1
```

**Comment by pgrzesik** [comment] 2021-04-29 18:57
Hello @aardvarkk :wave: Thanks for reporting. Generally, issues with plugin should be reported at plugin's repostitory, could you please move that issue there? Additionally, could you check the behavior for `2.38.0` version which is the latest one of the Framework? Preparing a reproducible example would be useful as well for a person debugging it. Thanks in advance :bow:

**Comment by pgrzesik** [comment] 2021-05-28 16:37
Hello @aardvarkk :wave: I'm going to close this issue as it seems that it should be reported on plugin side. If you feel like it's a problem on the Framework side, please report with details and we'll open it again. :bow:

**Closed by pgrzesik** 2021-05-28 16:37 UTC
Labels: question

**Comment by aardvarkk** [comment] 2021-06-29 18:49
@pgrzesik I dug into the serverless-jest-plugin source code and I think I've identified the issue. It looks like in v2.31.0 of Serverless the `options` object that is passed to the plugin looks like this:

```
[Object: null prototype] {
  f: 'foo',
  function: 'foo'
}
```

However, in newer versions the mapping of the "shortcut" to the full option name does not automatically take place. 

```
{ f: 'foo' }
```

It looks like it's available, but you now have to look at `serverless.processedInput.options` instead. The plugin only looks for the full option name as passed in the `options` object, so it breaks when that mapping no longer occurs. Is this new lack of mapping intentional from Serverless, such that the only way forward would be to change the source code of the jest plugin?

**Comment by pgrzesik** [comment] 2021-06-30 09:31
Hey @aardvarkk :wave: Thanks for digging into the issue. I believe it should be addressed on the plugin side. 

>  it just seems like version 2.32.0 broke the contract of how options were passed to plugins.

We always try to not do that, but unfortunately, at the moment there's no defined "contract" of what internal parts plugins can safely depend on and from time to time something in the plugin might break due to dependency on some internal parts. We aim to improve on that with the release of `v3` by estabilishing more clear interface that plugin authors can depend on.
