### ISSUE TITLE
SQS trigger not added by the provisioned lambda and should be removed by the non-provisioned lambda.

### ISSUE THREAD

**Issue by MicMonen** [serverless/serverless#7278] opened 2020-01-31 14:37 UTC
1. What did you do?
```
test:
  handler: testHandler.default
  name: test
  reservedConcurrency: 1
  provisionedConcurrency: 1
  events:
    - sqs:
        batchSize: 1
        arn: !GetAtt SomeQueue.Arn
```

2. What happened?
Both the lambda and the provisioned lambda are created. The SQS trigger is only created with the non-provisioned lambda and not with the provisioned one. 
This should be the other way around because of reservedConcurrency = 1 setting. You want the faster provisioned lambda to handle the request.

3. What should've happened?
The SQS trigger should only be created on the provisioned lambda.

**Comment by medikoo** [comment] 2020-02-10 00:23
Thanks @MicMonen for request. It's probably because incorrect alias is targetted by SQS with provisionedConcurrency setting.

We'll try to fix it shortly, otherwise PR's welcome

**Comment by medikoo** [comment] 2020-08-06 11:50
Duplicate of #7371

**Closed by medikoo** 2020-08-06 11:50 UTC
Labels: bug, cat/lambda, help wanted
