### ISSUE TITLE
Create reusable templates with sls package

### ISSUE THREAD

**Issue by henrymunro** [serverless/serverless#6568] opened 2019-08-21 08:58 UTC
# This is a Bug Report

## Description

- What went wrong?
Upgraded from `1.27.3` to `1.50.0` and the `stage` name is validated to ensure it meets API Gateways criteria when we run `sls package`. 

Validation was introduced here: https://github.com/serverless/serverless/pull/5639
And updated here: https://github.com/serverless/serverless/pull/5686

- What did you expect should have happened?
`stage` should only be validated when we run `sls deploy` 

- What was the config you used?
We're attempting to pass through a template to the `stage` variable i.e. `sls package --stage '$<stage>'`. The purpose of this is to allow us to provide an environment-specific `stage` when we deploy later. See background below for more details.

- What stacktrace or error message from your provider did you see?
![image](https://user-images.githubusercontent.com/11618615/63417208-bbb4ba00-c3f8-11e9-9ae2-558272eef4e5.png)

## Additional Data

**_Background_**:
We've come up with a system that allows us to build our serverless projects once, then inject the relevant environment config at deploy time.

This process is as follows: 
- Build assets
  - Upon merging to `master` we run `sls package --stage '\$<stage>' --package packaged-assets`  (This is now broken after upgrading to `1.50.0`)
     - In our `serverless.yml` all the environment-specific config is templated out using a `$<variable_name>` syntax 
  - After the package step has completed we copy the contents of the `./packaged-assets` (CloudFront `json` and `zip` archives containing JS) up to a partition in an S3 bucket
- Deploy assets
  - To deploy a version to an environment we pull down the relevant files from the S3 bucket
  - We then traverse any `json` files and resolve `$<variable_name>` templates for the correct values for the environment 
  - Finally, we run `yarn serverless deploy --stage environment-stage --package ./path-to-assets` to deploy to AWS

- **_Serverless Framework Version you're using_**:
`1.50.0`

**Comment by medikoo** [comment] 2019-08-21 15:26
@henrymunro so to my understanding, you use `sls package` more as a template generator, of which outcome you update with help some automated scripts, and pass to `sls deploy`.

I think problem is that `sls package` command was intended to produce a valid input for `sls deploy`, so one which doesn't need any further processing.  It was not designed to be a template generator.

Still I'd like to understand your use case better. Can you explain why have you decided to prebuild the artifacts and reuse them, instead of building them at _deploy_ step?

**Comment by henrymunro** [comment] 2019-08-21 16:02
@medikoo you're spot on.

We do this for 2 reasons, both boil down to 'build once, deploy multiple times': 
1) Improved performance at deploy time
   - We deploy each version of our services up through a number of environments, deploys now only involve standing up infrastructure on AWS, not bundling code
2) Ensure identical code across deployments
   - This is a pretty minor and we could live without. But if we have to re-build the application each time we deploy we run the risk of npm dependencies varying (by minor versions) across deployments.


We use `sls` with `serverless-webpack` to build and deploy a number of our microservices. Some of our more complex services have 20+ functions, which we package individually to reduce the size of any one handler. Despite this, we also have some large individual functions. We found the combination of these factors meant deploy times were becoming a bottleneck for some of our larger services, hence our solution.

**Comment by henrymunro** [comment] 2019-08-22 14:53
1. Do you have a timeline on the packaging performance improvements? As I say the packaging before each deploy was becoming a bottleneck and moving back to doing that would be a regression that I don't think would be acceptable for us.

2. Splitting hairs here, yes `package-lock.json` ensures that versions don't drift across deploys but doesn't protect against something like the notorious [leftPad](http://left-pad.io/) incident. Although, that risk is pretty minor and we'd be happy accepting it if we have to revert to package on each deploy. So our main issue is that of deploy performance.


As a general question, what is the purpose of the `sls package` command if not to allow you to deploy the same assets multiple times? And is there a way to specify differing configuration at deploy time (other than manually updating the `CF.json`)?

**Comment by medikoo** [comment] 2019-08-22 15:34
I do not reject the the idea of `sls package` being a sort of _template generator_. It's just that I think it wasn't designed with that in mind (altough @pmuens please correct me if I'm wrong).. and other case is, that trying to improve it so it's flexible to serve as _template generator_, may appear time taking (that could be a real blocker)

Now understanding your use case, It appears to me that you've gone that route, because slow packaging times appeared as an obstacle. So real solution would be to fix those packaging times. While we definitely have that on a agenda, delivery date of that is uncertain at this point - anyway I've created an issue which you may track now -> https://github.com/serverless/serverless/issues/6580

So we have on our agenda improvements to packaging definitely, while whether we're open to relax `sls package` is a thing we should further discuss. @pmuens what do you think?

**Comment by JamieCressey** [comment] 2019-10-02 13:56
+1 this. We build code and infra once, and deploy that through test/stage/prod environments. Whilst we could rely on git commit hashes to rebuild each time, "build once, deploy multiple times" has always been the rule of thumb here too.

**Comment by medikoo** [comment] 2020-10-12 13:54
Duplicate of #3528

**Closed by medikoo** 2020-10-12 13:54 UTC
Labels: cat/deployment, cat/packaging, help wanted, needs feedback
