### ISSUE TITLE
HTTP headers should be case-insensitive

### ISSUE THREAD

**Issue by montao** [serverless/serverless#6558] opened 2019-08-18 10:58 UTC
# Case-insensitive HTTP headers

## Details

- For example, the HTTP headers "Content-Type" and "content-type" should be treated the same
- Maybe just make them all lower-case

Similar or dependent issues:

- #2765 (?)
- #251 (?)

**Comment by medikoo** [comment] 2019-08-19 07:51
@montao in which exactly case they're not treated as same by Framework Core. Can you provide some example, or test case that exposes it?

**Comment by montao** [comment] 2019-08-20 13:50
If I understand correctly I need to do something like the following in Python 3.7 with AWS Lambda.
```
def get_case_insensitive_key_value(input_dict, key):
    return next((value for dict_key, value in input_dict.items() if dict_key.lower() == key.lower()), None)
```

and then use the value from the above function

`if get_case_insensitive_key_value(event['headers'], "content-type") == "application/xml":`

If I did not then I would not follow spec and only match for my exact string e.g. an http header with "Content-Type" instead of "content-type" would not work.

I am not 100 % sure about this but I can run some more test cases to display it.

**Comment by medikoo** [comment] 2019-08-20 14:32
`event['headers']` is what's generated on AWS side and passed to lambda, I believe casing of `headers` reflects what was send by the client.

Serverless Framework normally doesn't wrap in any way lambda handlers - there's no Framework code that's bundled together with deployed lambda (the only scenario when it's the case, is when you want to rely on our monitoring service - Serverless Dashboard)

I think you may ask on AWS forums whether they consider some setting for AWS to unify (lower-case) the headers as they come, it might be a nice option.

I also posted some clarifications at https://github.com/serverless/serverless/issues/2765#issuecomment-523042063

I'm going to close it as duplicate of #2765 which I believe is about same thing

**Closed by medikoo** 2019-08-20 14:32 UTC
Labels: bug
