### ISSUE TITLE
Invoke local --contextPath not working with relative paths

### ISSUE THREAD

**Issue by QAnders** [serverless/serverless#4310] opened 2017-09-25 08:26 UTC
# This is a Bug Report

## Description

Using `--contextPath ../test.createinvoice.context.json` is not working. There is an error stating "file not found". The `--path` works with relative paths so below is working:

`sls invoke local --function createeInvoice --path ../test.createinvoice.json  --contextPath /mnt/GitHub-Repos/test.createeinvoice.context.json`

## Additional Data

* ***Serverless Framework Version you're using***: 1.17.0
* ***Operating System***: Linux
* ***Stack Trace***:
```
  Serverless Error ---------------------------------------

  The file you provided does not exist.

  Stack Trace --------------------------------------------

ServerlessError: The file you provided does not exist.
    at AwsInvokeLocal.validateFile (/mnt/npm/node_modules/serverless/lib/plugins/aws/invokeLocal/index.js:33:13)
    at resolve (/mnt/npm/node_modules/serverless/lib/plugins/aws/invokeLocal/index.js:53:14)
    at AwsInvokeLocal.extendedValidate (/mnt/npm/node_modules/serverless/lib/plugins/aws/invokeLocal/index.js:51:12)
From previous event:
    at Object.invoke:local:invoke [as hook] (/mnt/npm/node_modules/serverless/lib/plugins/aws/invokeLocal/index.js:22:10)
    at BbPromise.reduce (/mnt/npm/node_modules/serverless/lib/classes/PluginManager.js:217:55)
From previous event:
    at PluginManager.invoke (/mnt/npm/node_modules/serverless/lib/classes/PluginManager.js:217:22)
    at PluginManager.run (/mnt/npm/node_modules/serverless/lib/classes/PluginManager.js:236:17)
    at variables.populateService.then (/mnt/npm/node_modules/serverless/lib/Serverless.js:107:33)
    at runCallback (timers.js:781:20)
    at tryOnImmediate (timers.js:743:5)
    at processImmediate [as _immediateCallback] (timers.js:714:5)
From previous event:
    at Serverless.run (/mnt/npm/node_modules/serverless/lib/Serverless.js:94:74)
    at serverless.init.then (/mnt/npm/node_modules/serverless/bin/serverless:32:50)
    at <anonymous>

  Get Support --------------------------------------------
     Docs:          docs.serverless.com
     Bugs:          github.com/serverless/serverless/issues
     Forums:        forum.serverless.com
     Chat:          gitter.im/serverless/serverless

  Your Environment Information -----------------------------
     OS:                     linux
     Node Version:           8.4.0
     Serverless Version:     1.17.0
```
* ***Provider Error messages***:

**Comment by RafalWilinski** [comment] 2017-09-25 09:58
Thanks for reporting issue @QAnders 🙌

I'll submit a fix asap, hopefully it will be included in next release.

**Comment by RafalWilinski** [comment] 2017-09-25 10:07
I've tried to reproduce the issue, however, everything is working fine for me.

My steps to reproduce:
```bash
serverless create -t aws-nodejs
touch ../test.createeinvoice.context.json
echo "{}" > ../test.createeinvoice.context.json
serverless invoke local -f hello -contextPath ../test.createeinvoice.context.json
```

Can you try @QAnders with version 1.22/23?

**Comment by QAnders** [comment] 2017-09-26 09:28
It seems to be related to Webpack!

Running a "non-webpack" SLS works but not when bundled with Webpack...

**Comment by HyperBrain** [comment] 2017-09-28 09:56
@QAnders It might be that the relative path is the issue with `serverless-webpack` because the files are loaded (invoked) from the location where the compiled files are. This might break the relative path in your case. However it works, if you add a `--path` option with a relative path to an event json file.
Can you add `--verbose` to the command line and check if there are any additional hints?

**Comment by QAnders** [comment] 2017-09-28 14:03
--verbose did not add any information unfortunately.

**Comment by QAnders** [comment] 2017-10-05 12:42
I have now upgraded to v1.23.0 but still the same I am afraid...
```
anders@qip-lambda-invoice-routing$ sls invoke local --function createeInvoice --path ../test.createeinvoice.json  --contextPath ../test.createeinvoice.context.json
Serverless: Bundling with Webpack...
Time: 12475ms
         Asset     Size  Chunks                    Chunk Names
    handler.js  7.67 MB       0  [emitted]  [big]  handler
handler.js.map  9.79 MB       0  [emitted]         handler
  [45] ./node_modules/babel-runtime/regenerator/index.js 49 bytes {0} [built]
  [46] ./node_modules/babel-runtime/helpers/asyncToGenerator.js 906 bytes {0} [built]
 [554] ./src/utils/responseHelper.js 1.92 kB {0} [built]
 [569] ./handler.js 13.2 kB {0} [built]
 [593] ./src/functions/internal/createeInvoice/index.js 182 bytes {0} [built]
[1262] ./src/functions/internal/routeInvoice/index.js 174 bytes {0} [built]
[1373] ./src/functions/internal/updateOcrCustomers/index.js 198 bytes {0} [built]
[1375] ./src/functions/internal/processOcrZip/index.js 178 bytes {0} [built]
[1421] ./src/functions/internal/crushFtp/index.js 158 bytes {0} [built]
[1423] ./src/functions/external/receivePdfEmail/index.js 186 bytes {0} [built]
[1430] ./src/functions/external/companySearch/index.js 178 bytes {0} [built]
[1436] ./src/functions/authorizers/mailchimpAuth/index.js 178 bytes {0} [built]
[1438] ./src/utils/logHelper.js 805 bytes {0} [built]
[1497] ./src/utils/errorReporter.js 601 bytes {0} [built]
[1509] ./src/utils/queryHelper.js 558 bytes {0} [built]
    + 1495 hidden modules

  Serverless Error ---------------------------------------

  The file you provided does not exist.

  Get Support --------------------------------------------
     Docs:          docs.serverless.com
     Bugs:          github.com/serverless/serverless/issues
     Forums:        forum.serverless.com
     Chat:          gitter.im/serverless/serverless

  Your Environment Information -----------------------------
     OS:                     linux
     Node Version:           6.9.1
     Serverless Version:     1.23.0
```

**Comment by QAnders** [comment] 2017-10-05 12:43
Running with absolut path works though:

`sls invoke local --function createeInvoice --path ../test.createeinvoice.json  --contextPath /mnt/Q/GitHub-Repos/test.createeinvoice.context.json`

**Comment by HyperBrain** [comment] 2017-10-05 12:59
@RafalWilinski @pmuens I think we had this relative vs. absolute path issue already with the `--path` option. We should make the handling exactly the same, i.e. convert the path to an absolute one internally by using `path.resolve()`.

**Comment by pmuens** [comment] 2017-10-06 14:56
> @RafalWilinski @pmuens I think we had this relative vs. absolute path issue already with the --path option. We should make the handling exactly the same, i.e. convert the path to an absolute one internally by using path.resolve().

100% agree @HyperBrain 👍. We could write a quick utils function which takes the path parameter and auto-converts it since `--path` is used in other places as well.

**Comment by kbariotis** [comment] 2017-10-15 14:11
Is this still holds? @RafalWilinski 's steps to reproduce seem to work fine.

**Comment by tsdorsey** [comment] 2018-12-14 19:36
I'm on 1.34.1
It looks like this should work. Both path and contextPath run through validateFile which seems should handle relative paths... Am I missing something?
https://github.com/serverless/serverless/blob/v1.34.1/lib/plugins/aws/invokeLocal/index.js#L30

**Comment by pmuens** [comment] 2019-02-06 13:08
Closing since this shou've been fixed in the past.

Feel free to re-open if this issue is still persisting.

**Closed by pmuens** 2019-02-06 13:08 UTC
Labels: bug, cat/local-dev, pr/more-info-needed
