### ISSUE TITLE
Option to fail fast on missing configuration files

### ISSUE THREAD

**Issue by biddster** [serverless/serverless#7863] opened 2020-06-23 10:21 UTC
### Use case description

I have a serverless project where I use multiple configuration files to manage the stack. Due to a refactoring error, I didn't create a yml file in the correct place. Consequently, my ${file} include from serverless.yml pointed to a non-existent file. I didn't spot the warning when I ran sls deploy...

```
Serverless Warning --------------------------------------
  A valid file to satisfy the declaration 'file(./stack/root.yml)' could not be found.
```
...and ctrl+c wasn't quick enough. Unfortunately that meant half my stack was deleted.

So it's no big deal as it was only a development env, but it got me thinking about a way to mark ${file} includes as mandatory. I'd really like serverless to fail fast on any missing file include. If there's already a way to do this, apologies.

### Proposed solution

Perhaps something like:

```
 ${mandatory_file:/blah/blah/blah}
```
Don't mind how it's done really. I just want a way to ensure integrity of the stack.

**Comment by medikoo** [comment] 2020-06-23 11:38
@biddster great thanks for that proposal. We're definitely open for that, and we already have such request at https://github.com/serverless/serverless/issues/3367

**Comment by medikoo** [comment] 2020-06-23 11:38
Duplicate of #3367

**Closed by medikoo** 2020-06-23 11:38 UTC
