### ISSUE TITLE
serverless framework support Step functions?

### ISSUE THREAD

**Issue by arunsubbanna** [serverless/serverless#3815] opened 2017-06-20 11:51 UTC
HI,
Do serverless framework support Step functions? If yes, please lead me to some examples.
Thanks
Arun

**Comment by pmuens** [comment] 2017-06-20 12:29
Hey @arunsubbanna thanks for opening 👍 

Currently we've no core support for AWS step functions. However @horike37 build an amazing plugin to use step function with Serverless --> https://github.com/horike37/serverless-step-functions

You might also want to look into this discussion: https://github.com/serverless/serverless/issues/3024

Closing this for now since it's a duplicate of #3024

**Closed by pmuens** 2017-06-20 12:29 UTC

**Comment by horike37** [comment] 2017-06-20 13:51
@pmuens thank you for introducing step functiong plugin!

@arunsubbanna 
Could you please try this plugin?
Let me know if you have some oininons or feedback!!

**Comment by pmuens** [comment] 2017-06-20 16:19
> @pmuens thank you for introducing step functiong plugin!

Thanks for providing this plugin @horike37 🙌 

> @arunsubbanna Could you please try this plugin? Let me know if you have some oininons or feedbacks!!

Yes, feedback on this would be nice! Let us know if you need any help with setting this up 👍

**Comment by arunsubbanna** [comment] 2017-07-04 10:11
@pmuens Plugin works great, thanks!

**Comment by pmuens** [comment] 2017-07-04 11:53
> @pmuens Plugin works great, thanks!

Nice @arunsubbanna thanks for confirming and shoutouts to the author @horike37 🙌 !
