### ISSUE TITLE
Add back support for `include` option and support for symlinks

### ISSUE THREAD

**Issue by tolbahadi** [serverless/serverless#2264] opened 2016-10-05 03:24 UTC
# This is a Feature Proposal
# 2194 Added support for excluding files/folders with glob statements. However, with [the negate option `!` being deprecated from `node-glob`](https://github.com/isaacs/node-glob#comments-and-negation) it will be difficult to specifically include something instead of always excluding. This brings back the need for `include` option so packaging functions is a little more flexible, especially for the cases where people  are packaging their functions individually.

Related discussions: https://github.com/serverless/serverless/pull/2194#issuecomment-251467198

Also, we can use node-glob's option `follow: true,` to follow symlinked directories. This is needed for packages that are installed locally with `npm link`. (note: I believe this option will only be needed in a development environment where someone is linking a local package they deploy it, so if it has serious performance impact on how fast node-glob does the search, we should not add it or at least optionalize it)

**Comment by jonsharratt** [comment] 2016-10-05 18:17
@tolbahadi I have taken a look to see if we can make the exclude glob patterns terse and just support `!` glob patterns using a different node module (that wraps node-glob under the hood).

Take a look at the PR and let me know what you think and everyone else 👍 or 👎 

I have not had chance to take a look at the other request, re: following symlinks, shouldn't be a big job at all if people deem it worth adding (seems so if you have a use case for it 🎉 ).

If we can get consensus to either have it as an option or just have it on by default I can raise a cheeky pull request.

Thanks for the feedback on the change, much appreciated!

**Comment by ianserlin** [comment] 2016-10-12 16:17
We are stuck on version `1.0.0-rc.2` until support for `npm link` is back.

The alternatives are: 

* platform specific filesystem linking scripts, which are more brittle; or 
* publishing private npm modules and reinstalling them constantly, which has a significant effect on time-to-implement

**Comment by jordanmack** [comment] 2016-10-14 22:50
On Windows directory symlinks and directory junctions are also not followed.

**Comment by mthenw** [comment] 2016-11-02 06:43
Duplicate of https://github.com/serverless/serverless/issues/2472. Already solved.

**Closed by mthenw** 2016-11-02 06:43 UTC
