### ISSUE TITLE
ApiGateway option to block overwriting of log settings and prevent custom resource from overwriting existing CloudwatchLogRole ARN

### ISSUE THREAD

**Issue by gmetzker** [serverless/serverless#6756] opened 2019-09-25 18:49 UTC
# Feature Proposal

## Description

I'm having issues with Api Gateway Log settings with serverless >= 1.42.

Previously I would use the plugin `serverless-plugin-stage-variables` which allowed me to set ApiGateway log settings in a CF resource as follows:

 ```
 ApiGatewayStage:
  Type: "AWS::ApiGateway::Stage"
  Properties:
   MethodSettings:
    - DataTraceEnabled: true
      HttpMethod: "*"
      LoggingLevel: INFO
      ResourcePath: "/*"
      MetricsEnabled: false
   TracingEnabled: false
```

Since v1.42 (and specifically tested on 1.52) the new logs `provider/logs/restApi` feature seems to be causing two issues:

1. In the file `/lib/plugins/aws/package/compile/events/apiGateway/lib/hack/updateStage.js` there appears to be code sending API comments to update the log settings (independent of Cloudformation).  This overwrites my log settings defined in my `AWS::ApiGateway::Stage` resource even if I comment out the log/restApi settings or mark them = false.

Reading through the code I couldn't find anyway to disable this behavior.

2.  If I choose to use this new feature to assign log settings it has a side effect.  It appears to create custom lambda resource to assign the global Api Gateway CloudWatch log role ARN.  In my case the role was already set so it's a bit aggressive to overwrite it at a global level.  Additionally when we promote this to our other accounts we won't have rights to change this.

I understand both of these are probably by design but it's causing issues none the less.

## Proposed Solutions / Requests

1. For `hack/updateStage.js` would it be possible to skip the call to update stage log settings if the `provider/logs` section in serverless.yml is missing?  This would restore the previous behavior and the deployment should function as in previous versions.  A few scenarios:

- User who doesn't want post-deploy log settings assigned:  Don't add `provider/logs` to serverless.
- User who wants post-deploy log settings disabled:  Add `provider/logs: false` or `provider/logs: null`
- User who wants post-deploy log settings enabled:  Fill in logs/respApi as currently documented.

2. Users should be able to prevent serverless from assigning the global cloudwatch log arn.
```
  provider:
    logs:
      restApi:
        assignGlobalCloudwatchLogRole: false
```

3. If #2 can/should not be implemented then at the very least there should be a check to the global ApiGateway cloudwatch role ARN.  If the role is already assigned then the custom resource should not try and assign/overwrite it.

Thanks in advance for consideration.

**Comment by gmetzker** [comment] 2019-09-25 19:01
Related Issue #6165

**Comment by medikoo** [comment] 2019-09-26 07:43
@gmetzker great thanks for opening this, and outlining the issues, it's indeed problems that we need to solve.
 
1) Here I believe the problem of design is that those settings have effect when not set, which is quite controversial. Logging is setup when there's _logs: true_, and logs setup is removed unconditionally when there's _log: false_ or there's no logs setting at all (!)

For settings handled via CloudFormation template, AWS detects that settings were removed or changed by inspecting the previous template, and on that basis detect whether any update is needed.

With `hack/updateStage` the problem is that we do not inspect the previous state, we just unconditionally update setup if given settings are missing.

I believe that right fix for that, is to move this hack into a custom resource. Having that we will have access to old and new configuration and we will be able to decide whether we should do any changes at all.

_While above is certainly an issue that needs solving, I believe you can have issue fixed in your case, just by relying on our settings, and no trying to apply those settings via custom `resources` setup (especially that at CF level there's no support for changes to those settings)_

2) I agree, I believe we should offer the way to opt out from this. This PR is also related: https://github.com/serverless/serverless/pull/6747
I would though name this option probably as:

```yaml
provider:
    logs:
       assumeApiGatewayCloudWatchLogRole: true
```

Not nested in `restApiI`, as it also applies to `websocket`.

Still not perfectly sure about this name, but open for further suggestions.

@pmuens what do you think?

**Comment by gmetzker** [comment] 2019-09-26 23:19
Sounds good to me.  

Just curious though why the api call hack is needed to assign the log settings to the stage?  It seems to work ok with a CF resource using `AWS::ApiGateway::Stage`.  Or am I missing something?

**Comment by medikoo** [comment] 2019-09-27 08:29
> It seems to work ok with a CF resource using AWS::ApiGateway::Stage. Or am I missing something?

Via CF no updates can be applied, e.g. you may initialize the stack with logging, tracking, but you're unable to fine tune those settings without removing and re-creating the stack.

This is the sole reason why we apply those setting not via CF template channel.
Still it's possible that soon all of that will be supported in CF, then we can safely move to CF

**Comment by medikoo** [comment] 2021-12-03 15:15
Closing, as I believe this issue was fixed with https://github.com/serverless/serverless/pull/7033

**Closed by medikoo** 2021-12-03 15:15 UTC
Labels: bug, help wanted, cat/aws-event-api-gateway
