### ISSUE TITLE
Support for AWS_DEFAULT_REGION and "region" in "~/.aws/config"

### ISSUE THREAD

**Issue by rudpot** [serverless/serverless#8490] opened 2020-11-09 14:54 UTC
Just ran into an issue that suggests that serverless has serious issues with credential / region handling. This may be related to https://github.com/serverless/serverless/issues/7570 although comments there suggest that region settings in `~/.aws/` and `AWS_DEFAULT_REGION` should have _no_ impact at all.

 I have credentials configured in `~/.aws/config`:

```
[profile ct-acct1]
region=us-west-2
account=111122223333
```
and access keys in`~/aws/credentials`.

Testing serverless using a net new directory and instantiating a python runtime and calling I get the following results:

* Setting `AWS_PROFILE` to `ct-acct1` uses the right credentials. `serverless deploy` works but it deploys to the wrong region `us-east-1` instead of `us-west-2` as per the config file

* Setting `AWS_PROFILE=ct-acct1` and `AWS_DEFAULT_REGION=sa-east-1` (Sao Paolo) uses the right credentials. `serverless deploy` fails. It deploys the initial serverless bucket to `us-east-1`(VIrginia) and then hangs when trying to validate the template at `validateTemplate({
  TemplateURL: 'https://s3.amazonaws.com/apigw-bug-demo-dev-serverlessdeploymentbucket-ni1esi6z02k5/serverless/apigw-bug-demo/dev/1604697072411-2020-11-06T21:11:12.411Z/compiled-cloudformation-template.json'`

* Setting `AWS_PROFILE=ct-acct1` and `AWS_DEFAULT_REGION=sa-east-1` (Sao Paolo) uses the right credentials. `serverless deploy --region us-east-1` (Virginia) works and it correctly deploys everything to `us-east-1` ignoring the environment variable.

* Setting `AWS_PROFILE=ct-acct1` and `AWS_DEFAULT_REGION=sa-east-1` (Sao Paolo) uses the right credentials. `serverless deploy --region sa-east-1` (Sao Paolo) fails. It correctly deploys the base S3 bucket to `sa-east-1` but then hangs when trying to validate the template at `validateTemplate({
  TemplateURL: 'https://s3.amazonaws.com/apigw-bug-demo-dev-serverlessdeploymentbucket-r0davwuv51xz/serverless/apigw-bug-demo/dev/1604697665226-2020-11-06T21:21:05.226Z/compiled-cloudformation-template.json'`

* Setting `AWS_PROFILE=ct-acct1` and unsetting `AWS_DEFAULT_REGION` uses the right credentials. `serverless deploy --region sa-east-1` (Sao Paolo) and it correctly deploys everything to `sa-east-1` (Sao Paolo).

_Originally posted by @rudpot in https://github.com/serverless/serverless/issues/7570#issuecomment-723310336_

**Comment by medikoo** [comment] 2020-11-10 09:14
Framework doesn't support `AWS_DEFAULT_REGION` and also doesn't read `region` as set for chosen profile in `~/.aws/config`.

If having those make deployment behave differently, it could be only because some dependencies (`aws-sdk` or some plugins) are referring to those and mismatch is created.

We're open to bring support for both, and I believe both should be handled with different PR's.

#### Support for `AWS_DEFAULT_REGION`

It probably can be ensured simply by introducing recognition of it in [`getRegionSourceValue`](https://github.com/serverless/serverless/blob/bde334c10f33a813a16e158832eb61c56e77d822/lib/plugins/aws/provider/awsProvider.js#L1377-L1383)

Still ideally we should address it after `awsProvider` tests are refactored (handled here: https://github.com/serverless/serverless/issues/8446)

#### Support for `profile` as set in  `~/.aws/config`

This should be integrated with credentials resolution from `~/.aws`. We have already planned refactor of that logic (check https://github.com/serverless/serverless/issues/4838#issuecomment-724570266) and I will address this after it's finalized

**Comment by medikoo** [comment] 2020-11-12 10:50
I've just realized we have already open issue for that. Check https://github.com/serverless/serverless/issues/2151

**Comment by medikoo** [comment] 2020-11-12 10:50
Duplicate of https://github.com/serverless/serverless/issues/2151

**Closed by medikoo** 2020-11-12 10:50 UTC
Labels: cat/deployment, enhancement
