### ISSUE TITLE
Local invoke error on Windows 10 using Python 3.6

### ISSUE THREAD

**Issue by dyakhnov** [serverless/serverless#3710] opened 2017-05-31 05:54 UTC
I have created my first serverless function in Python using

* Windows 10 (with NodeJS 8.0)
* Python 3.6

and try to run it locally with

> sls invoke local -f hello

but getting following error

```
events.js:182
      throw er; // Unhandled 'error' event
      ^

Error: spawn python3.6 ENOENT
    at exports._errnoException (util.js:1026:11)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:189:19)
    at onErrorNT (internal/child_process.js:366:16)
    at _combinedTickCallback (internal/process/next_tick.js:102:11)
    at process._tickDomainCallback (internal/process/next_tick.js:198:9)
```

I am no expert in NodeJS, but it looks like Windows 10 does not allow to run "pyhon3.6" command without (a) full path and (b) executable .exe file in the end.

Workaround:

1. Create environment variable PYTHON, which points directly to your python.exe file (by default %USERPROFILE%\AppData\Local\Programs\Python\Python36-32\python.exe)

2. Patch serverless\lib\plugins\aws\invokeLocal\index.js (function invokeLocalPython, just before return) with

```
    if (process.platform == 'win32') {
      runtime = process.env.PYTHON || runtime;
    }
```
and voilà!

**Comment by srp-synengco** [comment] 2017-06-19 23:45
This is an issue for me as well on windows 7 with python2.7, also a little beyond my understanding but I can confirm that @dyakhnov's workaround worked for me <- thanks for that :smile:

**Comment by dschep** [comment] 2017-06-22 18:55
Dupe of #3167

**Comment by pmuens** [comment] 2017-06-23 07:07
> Dupe of #3167 

Thanks for noting @dschep 👍 

Closing this one in favor or #3167 and #3832 

Thanks for opening @dyakhnov 👍

**Closed by pmuens** 2017-06-23 07:07 UTC
Labels: kind/bug, status/help-wanted
