### ISSUE TITLE
CLI menu options crash on windows (10) 

### ISSUE THREAD

**Issue by mikeRead** [serverless/serverless#1189] opened 2016-05-26 21:24 UTC
I am getting this issue for a lot of the CLI commands. Everything works great on OSX or when using command options like ```serverless stage create -s production -r us-east-1 -p default`` on windows, but that is a bit annoying . 

for example 

1. ```sls stage create```
2. [ENTER] to create dev stage
3. error is thrown

![515202c62d230aad444c66bbcb642054](https://cloud.githubusercontent.com/assets/3676392/15590463/8de714d6-235d-11e6-89d0-6630a2b2e336.gif)

```
S:\_github>sls stage create
Serverless: Enter a new stage name for this project:  (dev) [ENTER]

Serverless: For the "dev" stage, do you want to use an existing Amazon Web Services profile or create a new one?
  > Existing Profile
    Create A New Profile
C:\Users\Mike Read\AppData\Roaming\npm\node_modules\serverless\node_modules\bluebird\js\release\async.js:61
        fn = function () { throw arg; };
                           ^

TypeError: Cannot read property 'value' of undefined
  at C:\Users\Mike Read\AppData\Roaming\npm\node_modules\serverless\lib\actions\StageCreate.js:156:32
  at processImmediate [as _immediateCallback] (timers.js:374:17)
From previous event:
  at C:\Users\Mike Read\AppData\Roaming\npm\node_modules\serverless\lib\actions\StageCreate.js:153:18
  at C:\Users\Mike Read\AppData\Roaming\npm\node_modules\serverless\node_modules\prompt\lib\prompt.js:335:32
  at C:\Users\Mike Read\AppData\Roaming\npm\node_modules\serverless\node_modules\utile\node_modules\async\lib\async.js:142:25
  at assembler (C:\Users\Mike Read\AppData\Roaming\npm\node_modules\serverless\node_modules\prompt\lib\prompt.js:332:9)
  at C:\Users\Mike Read\AppData\Roaming\npm\node_modules\serverless\node_modules\prompt\lib\prompt.js:341:32
  at C:\Users\Mike Read\AppData\Roaming\npm\node_modules\serverless\node_modules\prompt\lib\prompt.js:624:5
  at Interface.onLine (C:\Users\Mike Read\AppData\Roaming\npm\node_modules\serverless\node_modules\read\lib\read.js:111:5)
  at emitOne (events.js:77:13)
  at Interface.emit (events.js:169:7)
  at Interface._onLine (readline.js:210:10)
  at Interface._line (readline.js:549:8)
  at Interface._ttyWrite (readline.js:826:14)
  at ReadStream.onkeypress (readline.js:105:10)
  at emitTwo (events.js:87:13)
  at ReadStream.emit (events.js:172:7)
  at emitKeys (readline.js:1250:14)
  at [object Generator].next (native)
  at ReadStream.onData (readline.js:918:36)
  at emitOne (events.js:77:13)
  at ReadStream.emit (events.js:169:7)
  at readableAddChunk (_stream_readable.js:146:16)
  at ReadStream.Readable.push (_stream_readable.js:110:10)
  at TTY.onread (net.js:523:20)
From previous event:
  at StageCreate._prompt (C:\Users\Mike Read\AppData\Roaming\npm\node_modules\serverless\lib\actions\StageCreate.js:134:12)
  at StageCreate.stageCreate (C:\Users\Mike Read\AppData\Roaming\npm\node_modules\serverless\lib\actions\StageCreate.js:77:20)
From previous event:
  at C:\Users\Mike Read\AppData\Roaming\npm\node_modules\serverless\lib\Serverless.js:186:31
  at Array.reduce (native)
  at C:\Users\Mike Read\AppData\Roaming\npm\node_modules\serverless\lib\Serverless.js:185:32
From previous event:
  at Serverless._execute (C:\Users\Mike Read\AppData\Roaming\npm\node_modules\serverless\lib\Serverless.js:183:12)
  at Serverless.actions.(anonymous function) (C:\Users\Mike Read\AppData\Roaming\npm\node_modules\serverless\lib\Serverless.js:429:20)
  at Serverless.command (C:\Users\Mike Read\AppData\Roaming\npm\node_modules\serverless\lib\Serverless.js:398:38)
  at C:\Users\Mike Read\AppData\Roaming\npm\node_modules\serverless\bin\serverless:19:16
  at processImmediate [as _immediateCallback] (timers.js:374:17)
From previous event:
  at Object.<anonymous> (C:\Users\Mike Read\AppData\Roaming\npm\node_modules\serverless\bin\serverless:18:4)
  at Module._compile (module.js:434:26)
  at Object.Module._extensions..js (module.js:452:10)
  at Module.load (module.js:355:32)
  at Function.Module._load (module.js:310:12)
  at Function.Module.runMain (module.js:475:10)
  at startup (node.js:117:18)
  at node.js:951:3
```

**Comment by jordanmack** [comment] 2016-05-26 22:44
@mikeRead  I wasn't able to reproduce this one. Did I get the steps right below?

```
C:\Users\username\Desktop>sls project create -n serverless-8675309 -s dev -r us-east-1 -p default
 _______                             __
|   _   .-----.----.--.--.-----.----|  .-----.-----.-----.
|   |___|  -__|   _|  |  |  -__|   _|  |  -__|__ --|__ --|
|____   |_____|__|  \___/|_____|__| |__|_____|_____|_____|
|   |   |             The Serverless Application Framework
|       |                           serverless.com, v0.5.5
`-------'

Serverless: Initializing Serverless Project...
Serverless: Creating stage "dev"...
Serverless: Creating region "us-east-1" in stage "dev"...
Serverless: Deploying resources to stage "dev" in region "us-east-1" via Cloudformation (~3 minutes)...
Serverless: Successfully deployed "dev" resources to "us-east-1"
Serverless: Successfully created region "us-east-1" within stage "dev"
Serverless: Successfully created stage "dev"
Serverless: Successfully initialized project "serverless-8675309"

C:\Users\username\Desktop>cd serverless-8675309

C:\Users\username\Desktop\serverless-8675309>sls stage create
Serverless: Enter a new stage name for this project:  (dev) dev2
Serverless: For the "dev2" stage, do you want to use an existing Amazon Web Services profile or create a new one?
  > Existing Profile
    Create A New Profile
Serverless: Select a profile for your project:
  > default
Serverless: Creating stage "dev2"...
Serverless: Select a new region for your stage:
  > us-east-1
    us-west-2
    eu-west-1
    eu-central-1
    ap-northeast-1
Serverless: Creating region "us-east-1" in stage "dev2"...
Serverless: Deploying resources to stage "dev2" in region "us-east-1" via Cloudformation (~3 minutes)...
Serverless: Successfully deployed "dev2" resources to "us-east-1"
Serverless: Successfully created region "us-east-1" within stage "dev2"
Serverless: Successfully created stage "dev2"
```


```
C:\Users\username>ver
Microsoft Windows [Version 10.0.10240]

C:\Users\username>node -v
v5.10.1

C:\Users\username>sls -v
0.5.5
```

**Comment by mikeRead** [comment] 2016-05-27 01:04
Thanks so much you actually really helped my node version was 4 something I updated to 6 and its running great. Sorry for bothering you :100:

**Comment by hakenmt** [comment] 2016-06-02 04:06
@mikeRead I had the same issue on Windows 10 running Node 5.6.0

**Comment by flomotlik** [comment] 2016-07-14 12:07
Ok great, looks like this was resolved and I'm closing the issue.

**Closed by flomotlik** 2016-07-14 12:07 UTC
