### ISSUE TITLE
Serverless package command fails on 1.75.0 

### ISSUE THREAD

**Issue by tomaszdudek7** [serverless/serverless#7948] opened 2020-07-16 07:06 UTC
Previously(on `serverless@1.74.1`), `serverless package command` worked as follows( I am using some plugins but that does not really matter I guess):
```
>>> serverless package --package target/nightly --stage nightly -v -r eu-west-1
Serverless: Generated requirements from /codebuild/output/src743139278/src/personalize_api/requirements.txt in /codebuild/output/src743139278/src/personalize_api/.serverless/requirements.txt...
Serverless: Installing requirements from /root/.cache/serverless-python-requirements/a337e502086d0fefce1f94ad52c69cae916af2fa7f6626d090eaa499875e1836_slspyc/requirements.txt ...
Serverless: Using download cache directory /root/.cache/serverless-python-requirements/downloadCacheslspyc
Serverless: Running ...
Serverless: Packaging service...
Serverless: Excluding development dependencies...
Serverless: Injecting required Python packages to package...
```
resulting in a zip file containing all the stuff needed to perform a deploy.

I upgraded my CI to use the `serverless@1.75.0`. Nothing else has changed in the code but the same command:
```
>>> serverless package --package ../target/nightly --stage nightly -v -r eu-west-1
Framework Core: 1.75.0
Plugin: 3.6.16
SDK: 2.3.1
Components: 2.32.0
```
does not seem to work anymore. Neither zip file was created nor anything was changed at all. The command just spits out the versions of everything.

**Comment by medikoo** [comment] 2020-07-16 07:42
Duplicate of #7944

**Closed by medikoo** 2020-07-16 07:42 UTC
