### ISSUE TITLE
DX: Use YAML validator before running any Serverless command

### ISSUE THREAD

**Issue by pmuens** [serverless/serverless#3398] opened 2017-03-23 08:24 UTC
# This is a Feature Proposal

## Description

A YAML validator should be run when the YAML is parsed to capture some nasty bugs such as the typical indentation problem described in https://github.com/serverless/serverless/issues/3394

Brought up by @HyperBrain in https://github.com/serverless/serverless/issues/3394#issuecomment-288522493

**Comment by HyperBrain** [comment] 2017-03-29 08:49
Maybe we can use https://www.npmjs.com/package/yaml-validator. Although I never checked the module, it claims to offer even providing a structure, similar to XSD for XML, that allows to test for semantic errors.

**Comment by softprops** [comment] 2018-11-05 02:46
Does a formal schema for serverless.yml exist?

**Comment by gndelia** [comment] 2019-11-11 15:14
This would be great: not only parse yaml but also validate serverless schema. Any progress on that?

**Comment by medikoo** [comment] 2020-10-01 14:12
YAML syntax errors are already reported at process of converting YAML to JSON via `js-yaml` package.

I believe these report is more about configuration errors, so on reporting on YAML valid, but not recognized by Serverless configuration structures. 

In this case it can be considered as duplicate of https://github.com/serverless/serverless/issues/6562 which was already solved

**Closed by medikoo** 2020-10-01 14:12 UTC
Labels: cat/dx, feature
