### ISSUE TITLE
add list of AWS permissions required for deploying service to docs

### ISSUE THREAD

**Issue by mthenw** [serverless/serverless#1674] opened 2016-07-26 12:53 UTC
Those permissions are required fro deploying Serverless service
```
        "cloudformation:CreateStack",
        "cloudformation:DescribeStacks",
        "cloudformation:DescribeStackResources",
        "cloudformation:UpdateStack",
        "cloudformation:ListStacks",
        "iam:GetRole",
        "lambda:UpdateFunctionCode",
        "lambda:UpdateFunctionConfig",
        "lambda:GetFunctionConfiguration",
        "lambda:AddPermission",
        "s3:DeleteObject",
        "s3:GetObject",
        "s3:ListBucket",
        "s3:PutObject"
```

Eventually this should be specified somewhere in the docs.

**Comment by flomotlik** [comment] 2016-08-19 14:52
duplicate of #1439 and well keep working there. Thanks for listing out the rights here!

**Closed by flomotlik** 2016-08-19 14:52 UTC

**Comment by uclaeagit** [comment] 2018-11-08 02:18
For what it's worth, this is the final list of permissions I had to add to get **serverless deploy** to work with AWS CodeBuild:

```
{
    "Sid": "NonDestructiveCoreReaderActionsUsedThroughoutServerless",
    "Effect": "Allow",
    "Action": [
        "cloudformation:CreateStack",
        "cloudformation:DescribeStacks",
        "cloudformation:DescribeStackEvents",
        "cloudformation:DescribeStackResource",
        "cloudformation:ValidateTemplate",
        "cloudformation:UpdateStack",
        "cloudformation:ListStacks",
        "iam:GetRole",
        "lambda:UpdateFunctionCode",
        "lambda:UpdateFunctionConfig",
        "lambda:GetFunctionConfiguration",
        "lambda:ListVersionsByFunction",
        "lambda:AddPermission",
        "s3:DeleteObject",
        "s3:GetObject",
        "s3:ListBucket",
        "s3:PutObject"
    ],
    "Resource": "*"
},
```

Notice that entry #4 for is not plural, which was a typo from the OP of this thread. Hope this helps anyone!

**Comment by hymloth** [comment] 2019-07-19 07:26
There is another typo, "lambda:UpdateFunctionConfig" must become "lambda:UpdateFunctionConfiguration"

**Comment by rmurillo21** [comment] 2020-08-12 19:30
We use an API gateway implementation, and found this policy works for us.
```
{
    "Version": "2012-10-17",
    "Statement": [
        {
            "Sid": "NonDestructiveCoreReaderActionsUsedThroughoutServerless",
            "Effect": "Allow",
            "Action": [
                "cloudformation:CreateStack",
                "cloudformation:DescribeStacks",
                "cloudformation:DescribeStackEvents",
                "cloudformation:DescribeStackResource",
                "cloudformation:DescribeStackResources",
                "cloudformation:ValidateTemplate",
                "cloudformation:UpdateStack",
                "cloudformation:ListStacks",
                "cloudformation:ListStackResources",
                "iam:GetRole",
                "lambda:UpdateFunctionCode",
                "lambda:UpdateFunctionConfiguration",
                "lambda:GetFunctionConfiguration",
                "lambda:ListVersionsByFunction",
                "lambda:AddPermission",
                "lambda:PublishVersion",
                "s3:DeleteObject",
                "s3:GetObject",
                "s3:ListBucket",
                "s3:PutObject"
            ],
            "Resource": "*"
        },
        {
            "Effect": "Allow",
            "Action": [
                "apigateway:GET",
                "apigateway:POST",
                "apigateway:PUT",
                "apigateway:PATCH",
                "apigateway:DELETE"
            ],
            "Resource": [
                "arn:aws:apigateway:*::/restapis",
                "arn:aws:apigateway:*::/restapis/*",
                "arn:aws:apigateway:*::/apikeys/*"
            ]
        }
    ]
}
```

**Comment by ffxsam** [comment] 2020-08-25 23:49
There's no one right answer for this, if I'm not mistaken. It all depends on what your serverless.yml is creating. If it's creating RDS clusters, for example, then your serverless IAM user will need permissions to do so.

**Comment by ap0h** [comment] 2023-02-09 17:34
Update: For Serverless v3 additional permissions are needed

```typescript
      "cloudformation:CreateChangeSet",
      "cloudformation:DeleteChangeSet",
      "cloudformation:ExecuteChangeSet"
```

**Comment by kielboy8** [comment] 2023-06-05 04:07
Just to share mine this is what I've used:

```
{
  "Sid": "ServerlessBasePolicies",
  "Action": [
    "cloudformation:CreateStack",
    "cloudformation:DescribeStacks",
    "cloudformation:DescribeStackEvents",
    "cloudformation:DescribeStackResource",
    "cloudformation:ListStackResources",
    "cloudformation:ValidateTemplate",
    "cloudformation:UpdateStack",
    "cloudformation:ListStacks",
    "cloudformation:CreateChangeSet",
    "cloudformation:DeleteChangeSet",
    "cloudformation:ExecuteChangeSet",
    "iam:GetRole",
    "iam:CreateRole",
    "iam:DeleteRole",
    "iam:PassRole",
    "iam:PutRolePolicy",
    "iam:GetRolePolicy",
    "iam:DeleteRolePolicy",
    "iam:TagRole",
    "iam:TagPolicy",
    "lambda:CreateFunction",
    "lambda:DeleteFunction",
    "lambda:GetFunction",
    "lambda:UpdateFunctionCode",
    "lambda:UpdateFunctionConfig",
    "lambda:GetFunctionConfiguration",
    "lambda:PublishVersion",
    "lambda:ListVersionsByFunction",
    "lambda:AddPermission",
    "lambda:RemovePermission",
    "lambda:ListTags",
    "lambda:TagResource",
    "logs:CreateLogGroup",
    "logs:DeleteLogGroup",
    "logs:TagResource",
    "s3:DeleteObject",
    "s3:GetObject",
    "s3:ListBucket",
    "s3:PutObject",
    "s3:CreateBucket",
    "s3:SetBucketEncryption",
    "s3:GetEncryptionConfiguration",
    "s3:PutEncryptionConfiguration",
    "s3:GetBucketPolicy",
    "s3:PutBucketPolicy"
  ],
  "Effect": "Allow",
  "Resource": "*"
},
{
  "Sid": "ServerlessApiPolicies",
  "Action": [
    "apigateway:GET",
    "apigateway:POST",
    "apigateway:PUT",
    "apigateway:PATCH",
    "apigateway:DELETE"
  ],
  "Effect": "Allow",
  "Resource": [
    "arn:aws:apigateway:${AWS::Region}::/restapis",
    "arn:aws:apigateway:${AWS::Region}::/restapis/*",
    "arn:aws:apigateway:${AWS::Region}::/apikeys",
    "arn:aws:apigateway:${AWS::Region}::/apikeys/*",
    "arn:aws:apigateway:${AWS::Region}::/usageplans",
    "arn:aws:apigateway:${AWS::Region}::/usageplans/*"
  ]
},
{
  "Sid": "ServerlessResourcePolicies",
  "Action": [
    "ssm:PutParameter",
    "ssm:DeleteParameter",
    "ssm:AddTagsToResource",
    "events:DescribeRule",
    "events:PutRule",
    "events:PutTargets",
    "lambda:GetLayerVersion",
    "lambda:PublishLayerVersion",
    "lambda:DeleteLayerVersion"
  ],
  "Effect": "Allow",
  "Resource": "*"
}
```

**Comment by kielboy8** [comment] 2023-06-05 04:10
Just to share mine. This is what I've used (P.S. `ServerlessResourcePolicies` are just the policies where I had to use Lambda layers and use the `schedule` event type. I also had to declare permissions for apikeys and usageplans since I was using the `serverless-add-api-key` plugin):

```
{
  "Sid": "ServerlessBasePolicies",
  "Action": [
    "cloudformation:CreateStack",
    "cloudformation:DescribeStacks",
    "cloudformation:DescribeStackEvents",
    "cloudformation:DescribeStackResource",
    "cloudformation:ListStackResources",
    "cloudformation:ValidateTemplate",
    "cloudformation:UpdateStack",
    "cloudformation:ListStacks",
    "cloudformation:CreateChangeSet",
    "cloudformation:DeleteChangeSet",
    "cloudformation:ExecuteChangeSet",
    "iam:GetRole",
    "iam:CreateRole",
    "iam:DeleteRole",
    "iam:PassRole",
    "iam:PutRolePolicy",
    "iam:GetRolePolicy",
    "iam:DeleteRolePolicy",
    "iam:TagRole",
    "iam:TagPolicy",
    "lambda:CreateFunction",
    "lambda:DeleteFunction",
    "lambda:GetFunction",
    "lambda:UpdateFunctionCode",
    "lambda:UpdateFunctionConfig",
    "lambda:GetFunctionConfiguration",
    "lambda:PublishVersion",
    "lambda:ListVersionsByFunction",
    "lambda:AddPermission",
    "lambda:RemovePermission",
    "lambda:ListTags",
    "lambda:TagResource",
    "logs:CreateLogGroup",
    "logs:DeleteLogGroup",
    "logs:TagResource",
    "s3:DeleteObject",
    "s3:GetObject",
    "s3:ListBucket",
    "s3:PutObject",
    "s3:CreateBucket",
    "s3:SetBucketEncryption",
    "s3:GetEncryptionConfiguration",
    "s3:PutEncryptionConfiguration",
    "s3:GetBucketPolicy",
    "s3:PutBucketPolicy"
  ],
  "Effect": "Allow",
  "Resource": "*"
},
{
  "Sid": "ServerlessApiPolicies",
  "Action": [
    "apigateway:GET",
    "apigateway:POST",
    "apigateway:PUT",
    "apigateway:PATCH",
    "apigateway:DELETE"
  ],
  "Effect": "Allow",
  "Resource": [
    "arn:aws:apigateway:${AWS::Region}::/restapis",
    "arn:aws:apigateway:${AWS::Region}::/restapis/*",
    "arn:aws:apigateway:${AWS::Region}::/apikeys",
    "arn:aws:apigateway:${AWS::Region}::/apikeys/*",
    "arn:aws:apigateway:${AWS::Region}::/usageplans",
    "arn:aws:apigateway:${AWS::Region}::/usageplans/*"
  ]
},
{
  "Sid": "ServerlessResourcePolicies",
  "Action": [
    "ssm:PutParameter",
    "ssm:DeleteParameter",
    "ssm:AddTagsToResource",
    "events:DescribeRule",
    "events:PutRule",
    "events:PutTargets",
    "lambda:GetLayerVersion",
    "lambda:PublishLayerVersion",
    "lambda:DeleteLayerVersion"
  ],
  "Effect": "Allow",
  "Resource": "*"
}
```

**Comment by sayopip** [comment] 2023-08-22 05:26
FYI
In my case, the following permissions were additionally required.

```txt
cloudformation:GetTemplate
cloudformation:DescribeChangeSet
```

**Comment by wmik** [comment] 2023-09-06 14:02
Had to update https://github.com/serverless/serverless/issues/1674#issuecomment-1576013924
```
lambda:UpdateFunctionConfig -> lambda:UpdateFunctionConfiguration
```
Reference: [AWS Docs](https://docs.aws.amazon.com/lambda/latest/dg/API_UpdateFunctionConfiguration.html)
