### ISSUE TITLE
Serverless deploy not working

### ISSUE THREAD

**Issue by sosickstudio** [serverless/serverless#8547] opened 2020-11-25 16:01 UTC
Hi Everyone, 

For some reasons I cannot deploy anymore, sls deploy returns an "Internal Server error".

Results of SLS_DEBUG:

Serverless: To ensure safe major version upgrades ensure "frameworkVersion" setting in service configuration (recommended setup: "frameworkVersion: ^2.12.0")

Serverless: Load command interactiveCli
Serverless: Load command config
Serverless: Load command config:credentials
Serverless: Load command config:tabcompletion
Serverless: Load command config:tabcompletion:install
Serverless: Load command config:tabcompletion:uninstall
Serverless: Load command create
Serverless: Load command install
Serverless: Load command package
Serverless: Load command deploy
Serverless: Load command deploy:function
Serverless: Load command deploy:list
Serverless: Load command deploy:list:functions
Serverless: Load command invoke
Serverless: Load command invoke:local
Serverless: Load command info
Serverless: Load command logs
Serverless: Load command metrics
Serverless: Load command print
Serverless: Load command remove
Serverless: Load command rollback
Serverless: Load command rollback:function
Serverless: Load command slstats
Serverless: Load command plugin
Serverless: Load command plugin
Serverless: Load command plugin:install
Serverless: Load command plugin
Serverless: Load command plugin:uninstall
Serverless: Load command plugin
Serverless: Load command plugin:list
Serverless: Load command plugin
Serverless: Load command plugin:search
Serverless: Load command config
Serverless: Load command config:credentials
Serverless: Load command rollback
Serverless: Load command rollback:function
Serverless: Load command upgrade
Serverless: Load command uninstall
Serverless: Load command offline
Serverless: Load command offline:start
Serverless: Load command create_domain
Serverless: Load command delete_domain
Serverless: Load command login
Serverless: Load command logout
Serverless: Load command generate-event
Serverless: Load command test
Serverless: Load command dashboard
Serverless: Load command output
Serverless: Load command output:get
Serverless: Load command output:list
Serverless: Load command param
Serverless: Load command param:get
Serverless: Load command param:list
Serverless: Load command studio
platform-sdk fetching: POST https://api.serverless.com/core/tenants/sosickstudio/applications/my-first-app/profileValue
Serverless: Deprecation warning: Starting with next major version, API Gateway naming will be changed from "{stage}-{service}" to "{service}-{stage}".
            Set "provider.apiGateway.shouldStartNameWithService" to "true" to adapt to the new behavior now.
            More Info: https://www.serverless.com/framework/docs/deprecations/#AWS_API_GATEWAY_NAME_STARTING_WITH_SERVICE
Serverless: Invoke deploy
Serverless: Invoke package
Serverless: Invoke aws:common:validate
Serverless: Invoke aws:common:cleanupTempDir
platform-sdk fetching: GET https://api.serverless.com/core/meta
platform-sdk fetching: GET https://api.serverless.com/core/tenants/sosickstudio/applications/my-first-app
platform-sdk fetching: GET https://api.serverless.com/core/meta
Serverless: Packaging service...
Serverless: Excluding development dependencies...
Serverless: Installing dependencies for custom CloudFormation resources...
Serverless: Invoke aws:package:finalize
Serverless: [AWS sts 200 0.746s 0 retries] getCallerIdentity({})
platform-sdk fetching: POST https://api.serverless.com/malt/destinations/create

  Error --------------------------------------------------

  Error: {"message": "Internal server error"}
      at module.exports (/usr/local/lib/node_modules/serverless/node_modules/@serverless/enterprise-plugin/lib/logsCollection.js:74:11)
      at processTicksAndRejections (internal/process/task_queues.js:93:5)
      at ServerlessEnterprisePlugin.<anonymous> (/usr/local/lib/node_modules/serverless/node_modules/@serverless/enterprise-plugin/lib/plugin.js:432:11)
  From previous event:
      at PluginManager.invoke (/usr/local/lib/node_modules/serverless/lib/classes/PluginManager.js:510:22)
      at PluginManager.spawn (/usr/local/lib/node_modules/serverless/lib/classes/PluginManager.js:530:17)
      at AwsPackage.<anonymous> (/usr/local/lib/node_modules/serverless/lib/plugins/aws/package/index.js:70:41)
  From previous event:
      at Object.package:finalize [as hook] (/usr/local/lib/node_modules/serverless/lib/plugins/aws/package/index.js:69:30)
  From previous event:
      at PluginManager.invoke (/usr/local/lib/node_modules/serverless/lib/classes/PluginManager.js:510:22)
      at /usr/local/lib/node_modules/serverless/lib/classes/PluginManager.js:545:24
  From previous event:
      at PluginManager.run (/usr/local/lib/node_modules/serverless/lib/classes/PluginManager.js:545:8)
      at /usr/local/lib/node_modules/serverless/lib/Serverless.js:170:33
      at processImmediate (internal/timers.js:458:21)
  From previous event:
      at Serverless.run (/usr/local/lib/node_modules/serverless/lib/Serverless.js:157:74)
      at /usr/local/lib/node_modules/serverless/scripts/serverless.js:50:26

  Get Support --------------------------------------------
     Docs:          docs.serverless.com
     Bugs:          github.com/serverless/serverless/issues
     Issues:        forum.serverless.com

  Your Environment Information ---------------------------
     Operating System:          darwin
     Node Version:              14.7.0
     Framework Version:         2.12.0
     Plugin Version:            4.1.2
     SDK Version:               2.3.2
     Components Version:        3.4.2

**Comment by raduoprea** [comment] 2020-11-25 16:13
@sosickstudio AWS is having some issues right now in N. Virginia, and those issues are affecting the deployments. The SF guys are in contact with AWS hoping to fix it faster but by the looks of it, all we can do right now is wait for AWS.

https://status.aws.amazon.com/

**Comment by kodev-de** [comment] 2020-11-25 16:15
Same here... thanks for the Info @raduoprea

**Comment by medikoo** [comment] 2020-11-25 17:50
Duplicate of #8545

**Closed by medikoo** 2020-11-25 17:50 UTC
