### ISSUE TITLE
Unable to use `deploy function` after updating to 1.38.0

### ISSUE THREAD

**Issue by arnagarjun** [serverless/serverless#5891] opened 2019-03-03 08:29 UTC
# This is a Bug Report

## Description

* What went wrong?

```
Type Error ---------------------------------------------

  Cannot read property 'startsWith' of undefined
```
Getting an error while trying to update the function using the command : 
`sls deploy function -f functionName`
Until i updated to 1.38.0 it was working fine. Now i am forced to go to 1.37.1
Tried with all functions and none of them can be deployed.
However, `sls deploy` works just fine.

* What did you expect should have happened?

> Function to have been deployed ( or updated ) without any error

* What was the config you used?

```
service: p2k19

########################## Plugins ########################## 
plugins:
  - serverless-iam-roles-per-function
############################################################


############################# Custom #########################
custom:

  tables: ${file(Resources/dynamodb.yml):${opt:stage, self:provider.stage}}

  secrets: ${file(./secrets.yml):${opt:stage, self:provider.stage}}

##############################################################


########################## Core Settings ########################
provider:
  name: aws
  stage: dev
  region: ap-south-1
  endpointType: REGIONAL

package:
  exclude:
    - secrets.yml

################################################################


########################## Functions ##########################
functions: 
  eventsList: ${file(Functions/Guest/EventList/EventList.yml):${opt:stage, self:provider.stage}.eventList}
  ...
  ...
  ( List of Other functions )
##############################################################


########################## Resources ########################## 
resources:
  Resources:
    users: ${self:custom.tables.users}
###############################################################
```

* What stacktrace or error message from your provider did you see?
```
 Stack Trace --------------------------------------------

TypeError: Cannot read property 'startsWith' of undefined
    at Package.packageFunction (C:\Users\Nagarjun\AppData\Roaming\npm\node_modules\serverless\lib\plugins\package\lib\packageService.js:132:19)
    at Object.package:function:package [as hook] (C:\Users\Nagarjun\AppData\Roaming\npm\node_modules\serverless\lib\plugins\package\package.js:69:41)
From previous event:
    at PluginManager.invoke (C:\Users\Nagarjun\AppData\Roaming\npm\node_modules\serverless\lib\classes\PluginManager.js:407:22)
    at PluginManager.run (C:\Users\Nagarjun\AppData\Roaming\npm\node_modules\serverless\lib\classes\PluginManager.js:438:17)
    at variables.populateService.then.then (C:\Users\Nagarjun\AppData\Roaming\npm\node_modules\serverless\lib\Serverless.js:114:33)
    at runCallback (timers.js:705:18)
    at tryOnImmediate (timers.js:676:5)
    at processImmediate (timers.js:658:5)
    at process.topLevelDomainCallback (domain.js:120:23)
From previous event:
    at Serverless.run (C:\Users\Nagarjun\AppData\Roaming\npm\node_modules\serverless\lib\Serverless.js:101:6)
    at serverless.init.then (C:\Users\Nagarjun\AppData\Roaming\npm\node_modules\serverless\bin\serverless:43:28)
    at C:\Users\Nagarjun\AppData\Roaming\npm\node_modules\serverless\node_modules\graceful-fs\graceful-fs.js:111:16
    at C:\Users\Nagarjun\AppData\Roaming\npm\node_modules\serverless\node_modules\graceful-fs\graceful-fs.js:45:10
    at FSReqWrap.oncomplete (fs.js:141:20)
From previous event:
    at initializeErrorReporter.then (C:\Users\Nagarjun\AppData\Roaming\npm\node_modules\serverless\bin\serverless:43:6)
    at runCallback (timers.js:705:18)
    at tryOnImmediate (timers.js:676:5)
    at processImmediate (timers.js:658:5)
    at process.topLevelDomainCallback (domain.js:120:23)
From previous event:
    at C:\Users\Nagarjun\AppData\Roaming\npm\node_modules\serverless\bin\serverless:28:46
    at Object.<anonymous> (C:\Users\Nagarjun\AppData\Roaming\npm\node_modules\serverless\bin\serverless:67:4)
    at Module._compile (internal/modules/cjs/loader.js:689:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:700:10)
    at Module.load (internal/modules/cjs/loader.js:599:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:538:12)
    at Function.Module._load (internal/modules/cjs/loader.js:530:3)
    at Function.Module.runMain (internal/modules/cjs/loader.js:742:12)
    at startup (internal/bootstrap/node.js:282:19)
    at bootstrapNodeJSCore (internal/bootstrap/node.js:743:3)
```

Similar or dependent issues:
* #5847

## Additional Data

* ***Serverless Framework Version you're using***: 1.38.0
* ***Operating System***: Windows 10 Pro x64
* ***Stack Trace***:
* ***Provider Error messages***: `Cannot read property 'startsWith' of undefined`

**Comment by pmuens** [comment] 2019-03-04 11:58
Hey @arnagarjun thanks for opening 👍

I tried to reproduce this issue with the configuration you've provided above. (Un)fortuantely I'm not able to break the current `master`. I also looked into the `packageService` code which causes the problems according to your stack trace but couldn't find anything suspicious.

Mu hunch is that the `serverless-iam-roles-per-function` plugin causes some problems. Could you try to run your service without the plugin?

**Comment by leisyka** [comment] 2019-03-05 13:29
Hello @arnagarjun and @pmuens,
I had exactly the same error trying to update serverless plugin from 1.32.0 to 1.38.0; at the end, I had to return to 1.32.0 version.
After running serverless in debug mode, I notice the problem was happenning when servesless tried to package the function into https://github.com/serverless/serverless/blob/master/lib/plugins/package/lib/packageService.js

For any reason, into line 141 is trying to look for a runtime which starts with "go" and it simply doesn't find it.

Let me know if you find a fix for this problem. 

Regards

**Comment by arnagarjun** [comment] 2019-03-05 20:40
@pmuens 
I removed the `serverless-iam-roles-per-function` and tried to deploy the function. Same error.
I also tried creating new project and tried to deploy only the function. But failed with same reason.

**Comment by dschep** [comment] 2019-03-05 20:42
I'll have a PR to fix this shortly. For the time being, make sure you have a runtime defined in the provider section.

**Comment by vallabhvrao** [comment] 2019-03-06 11:10
I am facing same issue on windows

**Closed** 2019-03-14 12:27 UTC
Labels: bug/confirmed, cat/deployment, os/windows

**Comment by scottalan** [comment] 2019-05-14 17:16
Visually validate your `serverless.yml` file. This was happening to me and I had a typo. :wink:
