### ISSUE TITLE
Serverless CLI should work without having us-east-1 defined

### ISSUE THREAD

**Issue by nikgraf** [serverless/serverless#1555] opened 2016-07-13 05:59 UTC
```
➜  test serverless --help
  Serverless Error ---------------------------------------
 
     region us-east-1 doesn't exist in stage dev
 
  Get Support --------------------------------------------
     Docs:          v1.docs.serverless.com
     Bugs:          github.com/serverless/serverless/issues
```

**Comment by mt-sergio** [comment] 2016-07-15 06:19
I had the same problem because I work with ap-northeast-1, so I removed us-east-1.
But I found this was solved in the master branch but not yet in the serverless@alpha.
You have the solution here: https://github.com/serverless/serverless/blob/v1.0/lib/plugins/create/templates/aws-nodejs/serverless.yaml
Just copy this template and set your defaults. (I guess you need at least one region... and maybe then we are talking about different bugs)

**Comment by janaka** [comment] 2016-07-16 23:13
The problem I'm seeing is NOT that I have to have us-east-1 defined rather if all I had was one region other than us-east-1 then I have to specify the region when deploying.

I feel the safest behaviour is 
1) if there only one region then default to that i.e. --region param not needed.
2) if there's more than one region specified in serverless.env.yaml then --region must be specified. No default.  

serverless.env.yaml
```
vars: null
stages:
    dev:
        vars: null
        regions:
            eu-west-1:
                vars:
```

This will complain with the error stated above.
`sls deploy` 

This works
`sls deploy --region eu-west-1`

**Comment by pmuens** [comment] 2016-07-27 12:48
Thank you guys for reporting and elaborating on this!

@eahefnawy could you please look into it if it's already fixed / an intentional behavior?

**Comment by eahefnawy** [comment] 2016-07-29 10:14
Yeah we decided to make it easier for people by having `dev` and `us-east-1` as defaults **that you can overwrite**. So basically if you haven't overwritten any stage/region defaults, we're assuming you have this default region defined, otherwise, which region are we gonna deploy to?

So basically if you don't have the `us-east-1` defined in `serverless.env.yml` and have other region instead, you gotta make sure you overwrite this default in the `defaults` object in `serverless.yml`.

So it's sort of by design. I hope this makes sense 😊

**Comment by eahefnawy** [comment] 2016-07-29 11:09
I'm gonna close this issue and start discussing the higher level issue of stage/region handling in issue #1707 

Thanks for bringing this up everyone 😊

**Closed by eahefnawy** 2016-07-29 11:09 UTC
Labels: area/cli
