### ISSUE TITLE
Default Output Export Name Collision

### ISSUE THREAD

**Issue by mscharp** [serverless/serverless#9498] opened 2021-05-18 21:14 UTC
Release 2.38.0 included a "feature" to add default export names to all of the outputs.  This is breaking my application as I get the following error "Export with name sls-someServiceName-src-CallbackDashdataDashpacketDashcreatorLambdaFunctionQualifiedArn is already exported by stack AP13333-SLS-someServiceName-dev-src." when deploying a second stack to the same aws account.

My application setup is multiple environments (dev, qa) within a single AWS account.  Each environment has multiple stages (dev, uat, prd).  And each env-stage combo is a separate CFN stack.  So when I deploy the "Dev-src" stack and then try to deploy the "QA-src" stack, i get the above error because the default export names only take into consideration the "stage" property of SLS.

This setup worked fine before.  As a work around, I have downgraded my app to use 2.37.x version of SLS.  

I propose that this feature should be able to be turned off, or that the export prefix can be customized.

This is similar in nature to #9361 

<details>
<summary><code>serverless.yml</code></summary>

```yaml
# ⚠️⚠️ REPLACE THIS COMMENT WITH FULL serverless.yml CONTENT
```

</details>

<details>
<summary><b><code>sls deploy --stage src --region us-east-1 --verbose</code> output</b></summary>

```
Serverless: Deprecation warning: Variables resolver reports following resolution errors:
              - Cannot resolve variable at "provider.stackName": String value consist of variable which resolve with non-string value
            From a next major this will be communicated with a thrown error.
            Set "variablesResolutionMode: 20210326" in your service config, to adapt to new behavior now
            More Info: https://www.serverless.com/framework/docs/deprecations/#NEW_VARIABLES_RESOLVER
Serverless: Running "serverless" installed locally (in service node_modules)
Serverless: Deprecation warning: Starting from next major object notation for "service" property will no longer be recognized. Set "service" property directly with service name.
            More Info: https://www.serverless.com/framework/docs/deprecations/#SERVICE_OBJECT_NOTATION

Serverless: Deprecation warning: CLI options definitions were upgraded with "type" property (which could be one of "string", "boolean", "multiple"). Below listed plugins do not predefine type for introduced options:
             - ServerlessOffline for "apiKey", "corsAllowHeaders", "corsAllowOrigin", "corsDisallowCredentials", "corsExposedHeaders", "disableCookieValidation", "enforceSecureCookies", "hideStackTraces", "host", "httpPort", "httpsProtocol", "lambdaPort", "noPrependStageInUrl", "noAuth", "ignoreJWTSignature", "noTimeout", "prefix", "printOutput", "resourceRoutes", "useChildProcesses", "useWorkerThreads", "websocketPort", "webSocketHardTimeout", "webSocketIdleTimeout", "useDocker", "layersDir", "dockerReadOnly", "functionCleanupIdleTimeSeconds", "allowCache", "dockerHost", "dockerHostServicePath", "dockerNetwork"
            Please report this issue in plugin issue tracker.
            Starting with next major release, this will be communicated with a thrown error.
            More Info: https://www.serverless.com/framework/docs/deprecations/#CLI_OPTIONS_SCHEMA
Serverless: Deprecation warning: CLI options definitions were upgraded with "type" property (which could be one of "string", "boolean", "multiple"). Below listed plugins do not predefine type for introduced options:
             - ServerlessOffline for "apiKey", "corsAllowHeaders", "corsAllowOrigin", "corsDisallowCredentials", "corsExposedHeaders", "disableCookieValidation", "enforceSecureCookies", "hideStackTraces", "host", "httpPort", "httpsProtocol", "lambdaPort", "noPrependStageInUrl", "noAuth", "ignoreJWTSignature", "noTimeout", "prefix", "printOutput", "resourceRoutes", "useChildProcesses", "useWorkerThreads", "websocketPort", "webSocketHardTimeout", "webSocketIdleTimeout", "useDocker", "layersDir", "dockerReadOnly", "functionCleanupIdleTimeSeconds", "allowCache", "dockerHost", "dockerHostServicePath", "dockerNetwork"
            Please report this issue in plugin issue tracker.
            Starting with next major release, this will be communicated with a thrown error.
            More Info: https://www.serverless.com/framework/docs/deprecations/#CLI_OPTIONS_SCHEMA
Serverless: Deprecation warning: Support for "package.include" and "package.exclude" will be removed with next major release. Please use "package.patterns" instead
            More Info: https://www.serverless.com/framework/docs/deprecations/#NEW_PACKAGE_PATTERNS
Serverless: Deprecation warning: Starting with next major version, "awsKmsKeyArn" service property will be replaced by "provider.kmsKeyArn"
            More Info: https://www.serverless.com/framework/docs/deprecations/#AWS_KMS_KEY_ARN
Serverless: Deprecation warning: Resolution of lambda version hashes was improved with better algorithm, which will be used in next major release.
            Switch to it now by setting "provider.lambdaHashingVersion" to "20201221"
            More Info: https://www.serverless.com/framework/docs/deprecations/#LAMBDA_HASHING_VERSION_V2
Serverless: Deprecation warning: Starting with next major version, API Gateway-specific configuration keys "apiKeys", "resourcePolicy" and "usagePlan" will be relocated from "provider" to "provider.apiGateway"
            More Info: https://www.serverless.com/framework/docs/deprecations/#AWS_API_GATEWAY_SPECIFIC_KEYS
Serverless: Auto instrumenting functions with Datadog
Serverless: Adding Lambda Library Layers to functions
Serverless: Skipping adding Lambda Extension Layer
Serverless: Compiling with Typescript...
Serverless: Using local tsconfig.json
Serverless: Typescript compiled.
Serverless: Packaging service...
Serverless: Excluding development dependencies...
Serverless: Adding Plugin Version 2.22.0
Serverless: Adding service and environment tags to functions
Serverless: Adding Plugin Version 2.22.0
Serverless: Adding service and environment tags to functions
Serverless: collect-task-events dependsOn collect-events
Serverless: api dependsOn collect-task-events
Serverless: subscription-api dependsOn api
Serverless: processing-queue-forwarder dependsOn subscription-api
Serverless: callback-data-packet-creator dependsOn processing-queue-forwarder

Serverless: Uploading CloudFormation file to S3...
Serverless: Uploading artifacts...
Serverless: Uploading service event-management.zip file to S3 (3.36 MB)...
Serverless: Validating template...
Serverless: Updating Stack...
Serverless: Checking Stack update progress...
CloudFormation - UPDATE_IN_PROGRESS - AWS::CloudFormation::Stack - AP133333-SLS-someServiceName-qa-src
CloudFormation - UPDATE_ROLLBACK_IN_PROGRESS - AWS::CloudFormation::Stack - AP133333-SLS-someServiceName-qa-src
CloudFormation - UPDATE_ROLLBACK_COMPLETE_CLEANUP_IN_PROGRESS - AWS::CloudFormation::Stack - AP133333-SLS-someServiceName-qa-src
CloudFormation - UPDATE_ROLLBACK_COMPLETE - AWS::CloudFormation::Stack - AP133333-SLS-someServiceName-dit-src
Serverless: Operation failed!
Serverless: View the full error output: https://us-east-1.console.aws.amazon.com/cloudformation/home?region=us-east-1#/stack/detail?stackId=arn%3Aaws%3Acloudformation%3Aus-east-1%3AXXXXXXXXXXXXX%3Astack%2FAP133333-SLS-someServiceName-qa-src%2F4f4b91d0-b763-11eb-bbac-3dffsd35b
 
 Serverless Error ----------------------------------------
 
  An error occurred: AP133333-SLS-someServiceName-qa-src - Export with name sls-someServiceName-src-CallbackDashdataDashpacketDashcreatorLambdaFunctionQualifiedArn is already exported by stack AP133333-SLS-someServiceName-dev-src.
 
  Get Support --------------------------------------------
     Docs:          docs.serverless.com
     Bugs:          github.com/serverless/serverless/issues
     Issues:        forum.serverless.com
 
  Your Environment Information ---------------------------
     Operating System:          linux
     Node Version:              10.24.1
     Framework Version:         2.41.2 (local)
     Plugin Version:            5.0.0
     SDK Version:               4.2.2
     Components Version:        3.9.2
```

</details>

<b>Installed version</b>

```
  Your Environment Information ---------------------------
     Operating System:          linux
     Node Version:              10.24.1
     Framework Version:         2.41.2 (local)
     Plugin Version:            5.0.0
     SDK Version:               4.2.2
     Components Version:        3.9.2
```

**Comment by pgrzesik** [comment] 2021-05-19 12:27
Hello @mscharp - could you please share a bit more about your setup? Export names are generated based on `service` and `stage`, which is supposed to be unique for each deployment and a lot of Framework internals depend on that. Could you share an example `serverless.yml` configs that are causing issue for you? Are you overriding `stackName` manually? 

Also, could we move this conversation to the issue you've linked as it seems like a duplicate of the same issue.

**Comment by dorankangwai** [comment] 2021-05-19 21:26
We too are encountering this issue with the ServerlessDeploymentBucketName colliding with an export in another stack. Ideally we would like an "do not automatically export outputs" option for serverless.

**Comment by pgrzesik** [comment] 2021-05-20 07:11
Hello @dorankangwai - could you please share a bit more about your specific issue in https://github.com/serverless/serverless/issues/9361? What is your setup? How are you deploying multiple stacks that are colliding?

**Comment by mscharp** [comment] 2021-05-20 20:36
Hi @pgrzesik.  Yes I'm ok to move this conversation over to the other issue.  I wasn't sure if it was close enough to just start posting in it, which is why I created this one.  I will post early next week more info to help show this.  But for now, yes we are overriding our stackname...although our stack name is not the problem.

`stackName: ${file(./config.json):appId}-SLS-${self:service}-${self:custom.environment}-${self:provider.stage}`

**Comment by dorankangwai** [comment] 2021-05-21 00:32
Hi @pgrzesik we are also specifying the stackName but using the same service for 2 different serverless deployments

Example serverless configs
```
service: s1

provider:
  name: aws
  region: us-west-2
  deploymentBucket:
    name: doran-deploy
  stackName: s1-init

resources:
  Resources:
    b1:
      Type: AWS::S3::Bucket
      Properties:
        BucketName: doran-b1
```

and
```
service: s1

provider:
  name: aws
  region: us-west-2
  deploymentBucket:
    name: doran-deploy

resources:
  Resources:
    b1:
      Type: AWS::S3::Bucket
      Properties:
        BucketName: doran-b2
```

with the newer version of serverless this leads to the export collision for ServerlessDeploymentBucketName export.
```
Export with name sls-s1-dev-ServerlessDeploymentBucketName is already exported by stack s1-init. Delete requested by user.
```

**Comment by pgrzesik** [comment] 2021-05-21 06:52
Thank you @mscharp :bow: I'm waiting for more details - it will help understand the issue better. 

> although our stack name is not the problem

Could you also clarify what do you mean by the above?

**Comment by medikoo** [comment] 2021-07-06 07:57
Duplicate of #9361

**Closed by medikoo** 2021-07-06 07:57 UTC
Labels: question
