### ISSUE TITLE
v0.5 - Error when rate limited by AWS API

### ISSUE THREAD

**Issue by marekmenhart-boa** [serverless/serverless#885] opened 2016-03-24 20:27 UTC
I'm seeing an issue with deploying all endpoints and hitting the API Gateway rate limit. I believe Serverless is set up to sleep for 5 seconds after getting a 429 error status and then retrying the request, but I get this error:
```
Wed, 23 Mar 2016 20:49:58 GMT serverless:lib.node_modules.serverless.lib.actions.EndpointDeployApiGateway 'Too many requests' received, sleeping 5 seconds
/scratch/jenkins/tools/jenkins.plugins.nodejs.tools.NodeJSInstallation/Node_Default/lib/node_modules/serverless/node_modules/bluebird/js/release/async.js:49
        fn = function () { throw arg; };
                           ^

ServerlessError: No integration defined for method
    at new ServerlessError (/scratch/jenkins/tools/jenkins.plugins.nodejs.tools.NodeJSInstallation/Node_Default/lib/node_modules/serverless/lib/Error.js:17:11)
    at /scratch/jenkins/tools/jenkins.plugins.nodejs.tools.NodeJSInstallation/Node_Default/lib/node_modules/serverless/lib/actions/EndpointDeployApiGateway.js:461:25
From previous event:
    at EndpointDeployApiGateway._createDeployment (/scratch/jenkins/tools/jenkins.plugins.nodejs.tools.NodeJSInstallation/Node_Default/lib/node_modules/serverless/lib/actions/EndpointDeployApiGateway.js:424:14)
    at EndpointDeployApiGateway.<anonymous> (/scratch/jenkins/tools/jenkins.plugins.nodejs.tools.NodeJSInstallation/Node_Default/lib/node_modules/serverless/lib/actions/EndpointDeployApiGateway.js:213:24)
From previous event:
    at EndpointDeployApiGateway._processRegionDeployment (/scratch/jenkins/tools/jenkins.plugins.nodejs.tools.NodeJSInstallation/Node_Default/lib/node_modules/serverless/lib/actions/EndpointDeployApiGateway.js:207:10)
    at EndpointDeployApiGateway.<anonymous> (/scratch/jenkins/tools/jenkins.plugins.nodejs.tools.NodeJSInstallation/Node_Default/lib/node_modules/serverless/lib/actions/EndpointDeployApiGateway.js:94:24)
From previous event:
    at EndpointDeployApiGateway._processDeployment (/scratch/jenkins/tools/jenkins.plugins.nodejs.tools.NodeJSInstallation/Node_Default/lib/node_modules/serverless/lib/actions/EndpointDeployApiGateway.js:91:10)
From previous event:
    at EndpointDeployApiGateway.endpointDeployApiGateway (/scratch/jenkins/tools/jenkins.plugins.nodejs.tools.NodeJSInstallation/Node_Default/lib/node_modules/serverless/lib/actions/EndpointDeployApiGateway.js:55:10)
From previous event:
    at /scratch/jenkins/tools/jenkins.plugins.nodejs.tools.NodeJSInstallation/Node_Default/lib/node_modules/serverless/lib/Serverless.js:206:25
    at Array.reduce (native)
    at Serverless._execute (/scratch/jenkins/tools/jenkins.plugins.nodejs.tools.NodeJSInstallation/Node_Default/lib/node_modules/serverless/lib/Serverless.js:205:26)
    at Object.actions.(anonymous function) [as endpointDeployApiGateway] (/scratch/jenkins/tools/jenkins.plugins.nodejs.tools.NodeJSInstallation/Node_Default/lib/node_modules/serverless/lib/Serverless.js:424:20)
    at EndpointDeploy._processDeployment (/scratch/jenkins/tools/jenkins.plugins.nodejs.tools.NodeJSInstallation/Node_Default/lib/node_modules/serverless/lib/actions/EndpointDeploy.js:212:24)
From previous event:
    at EndpointDeploy.endpointDeploy (/scratch/jenkins/tools/jenkins.plugins.nodejs.tools.NodeJSInstallation/Node_Default/lib/node_modules/serverless/lib/actions/EndpointDeploy.js:101:12)
From previous event:
    at /scratch/jenkins/tools/jenkins.plugins.nodejs.tools.NodeJSInstallation/Node_Default/lib/node_modules/serverless/lib/Serverless.js:181:31
    at Array.reduce (native)
    at /scratch/jenkins/tools/jenkins.plugins.nodejs.tools.NodeJSInstallation/Node_Default/lib/node_modules/serverless/lib/Serverless.js:180:32
From previous event:
    at Serverless._execute (/scratch/jenkins/tools/jenkins.plugins.nodejs.tools.NodeJSInstallation/Node_Default/lib/node_modules/serverless/lib/Serverless.js:178:12)
    at Serverless.actions.(anonymous function) (/scratch/jenkins/tools/jenkins.plugins.nodejs.tools.NodeJSInstallation/Node_Default/lib/node_modules/serverless/lib/Serverless.js:424:20)
    at Serverless.command (/scratch/jenkins/tools/jenkins.plugins.nodejs.tools.NodeJSInstallation/Node_Default/lib/node_modules/serverless/lib/Serverless.js:393:38)
    at /scratch/jenkins/tools/jenkins.plugins.nodejs.tools.NodeJSInstallation/Node_Default/lib/node_modules/serverless/bin/serverless:19:16
    at processImmediate [as _immediateCallback] (timers.js:383:17)
From previous event:
    at Object.<anonymous> (/scratch/jenkins/tools/jenkins.plugins.nodejs.tools.NodeJSInstallation/Node_Default/lib/node_modules/serverless/bin/serverless:18:4)
    at Module._compile (module.js:398:26)
    at Object.Module._extensions..js (module.js:405:10)
    at Module.load (module.js:344:32)
    at Function.Module._load (module.js:301:12)
    at Function.Module.runMain (module.js:430:10)
    at startup (node.js:141:18)
    at node.js:980:3
```

There was a bug related to dealing with rate limit errors in version 0.4 that was fixed in #688, but now it looks like there's a new problem in version 0.5.

**Comment by eahefnawy** [comment] 2016-03-28 08:54
@marekmenhart-boa the error message that you get doesn't seem to be related to the rate limits. Are you able to deploy the exact same endpoint/function configuration when you're not hitting the rate limits? Just wanna make sure nothing is missing from the config :)

Sorry for the rate reply, and thanks for reporing :blush:

**Comment by marekmenhart-boa** [comment] 2016-03-28 17:50
@eahefnawy Thanks for your response. I'm able to deploy the same project without any issues as long as I don't hit the rate limit.

I noticed I get a different stack trace depending on whether I include the --all flag. My original error stack trace was generated after running the command
```
serverless endpoint deploy --all -s <myStage> --debug
```

If I don't include the --all flag and run this instead
```
serverless endpoint deploy -s <myStage> --debug
```
I get this output:
```
Serverless:   POST - /dspCloud/govern/1_0/{companyId}/customAttributes/values: Too Many Requests  
Mon, 28 Mar 2016 16:25:57 GMT serverless:lib.node_modules.serverless.lib.actions.EndpointDeploy TooManyRequestsException: Too Many Requests
    at Object.extractError (/scratch/jenkins/tools/jenkins.plugins.nodejs.tools.NodeJSInstallation/Node_Default/lib/node_modules/serverless/node_modules/aws-sdk/lib/protocol/json.js:43:27)
    at Request.extractError (/scratch/jenkins/tools/jenkins.plugins.nodejs.tools.NodeJSInstallation/Node_Default/lib/node_modules/serverless/node_modules/aws-sdk/lib/protocol/rest_json.js:37:8)
    at Request.callListeners (/scratch/jenkins/tools/jenkins.plugins.nodejs.tools.NodeJSInstallation/Node_Default/lib/node_modules/serverless/node_modules/aws-sdk/lib/sequential_executor.js:105:20)
    at Request.emit (/scratch/jenkins/tools/jenkins.plugins.nodejs.tools.NodeJSInstallation/Node_Default/lib/node_modules/serverless/node_modules/aws-sdk/lib/sequential_executor.js:77:10)
    at Request.emit (/scratch/jenkins/tools/jenkins.plugins.nodejs.tools.NodeJSInstallation/Node_Default/lib/node_modules/serverless/node_modules/aws-sdk/lib/request.js:596:14)
    at Request.transition (/scratch/jenkins/tools/jenkins.plugins.nodejs.tools.NodeJSInstallation/Node_Default/lib/node_modules/serverless/node_modules/aws-sdk/lib/request.js:21:10)
    at AcceptorStateMachine.runTo (/scratch/jenkins/tools/jenkins.plugins.nodejs.tools.NodeJSInstallation/Node_Default/lib/node_modules/serverless/node_modules/aws-sdk/lib/state_machine.js:14:12)
    at /scratch/jenkins/tools/jenkins.plugins.nodejs.tools.NodeJSInstallation/Node_Default/lib/node_modules/serverless/node_modules/aws-sdk/lib/state_machine.js:26:10
    at Request.<anonymous> (/scratch/jenkins/tools/jenkins.plugins.nodejs.tools.NodeJSInstallation/Node_Default/lib/node_modules/serverless/node_modules/aws-sdk/lib/request.js:37:9)
    at Request.<anonymous> (/scratch/jenkins/tools/jenkins.plugins.nodejs.tools.NodeJSInstallation/Node_Default/lib/node_modules/serverless/node_modules/aws-sdk/lib/request.js:598:12)
    at Request.callListeners (/scratch/jenkins/tools/jenkins.plugins.nodejs.tools.NodeJSInstallation/Node_Default/lib/node_modules/serverless/node_modules/aws-sdk/lib/sequential_executor.js:115:18)
    at Request.emit (/scratch/jenkins/tools/jenkins.plugins.nodejs.tools.NodeJSInstallation/Node_Default/lib/node_modules/serverless/node_modules/aws-sdk/lib/sequential_executor.js:77:10)
    at Request.emit (/scratch/jenkins/tools/jenkins.plugins.nodejs.tools.NodeJSInstallation/Node_Default/lib/node_modules/serverless/node_modules/aws-sdk/lib/request.js:596:14)
    at Request.transition (/scratch/jenkins/tools/jenkins.plugins.nodejs.tools.NodeJSInstallation/Node_Default/lib/node_modules/serverless/node_modules/aws-sdk/lib/request.js:21:10)
    at AcceptorStateMachine.runTo (/scratch/jenkins/tools/jenkins.plugins.nodejs.tools.NodeJSInstallation/Node_Default/lib/node_modules/serverless/node_modules/aws-sdk/lib/state_machine.js:14:12)
    at /scratch/jenkins/tools/jenkins.plugins.nodejs.tools.NodeJSInstallation/Node_Default/lib/node_modules/serverless/node_modules/aws-sdk/lib/state_machine.js:26:10
From previous event:
    at ServerlessProviderAws.request (/scratch/jenkins/tools/jenkins.plugins.nodejs.tools.NodeJSInstallation/Node_Default/lib/node_modules/serverless/lib/ProviderAws.js:65:14)
    at ServerlessProviderAws.getApiByName (/scratch/jenkins/tools/jenkins.plugins.nodejs.tools.NodeJSInstallation/Node_Default/lib/node_modules/serverless/lib/ProviderAws.js:302:19)
    at Builder._getRestApi (/scratch/jenkins/tools/jenkins.plugins.nodejs.tools.NodeJSInstallation/Node_Default/lib/node_modules/serverless/lib/actions/EndpointBuildApiGateway.js:193:18)
From previous event:
    at Builder.build (/scratch/jenkins/tools/jenkins.plugins.nodejs.tools.NodeJSInstallation/Node_Default/lib/node_modules/serverless/lib/actions/EndpointBuildApiGateway.js:71:10)
    at EndpointBuildApiGateway.endpointBuildApiGateway (/scratch/jenkins/tools/jenkins.plugins.nodejs.tools.NodeJSInstallation/Node_Default/lib/node_modules/serverless/lib/actions/EndpointBuildApiGateway.js:53:22)
    at processImmediate [as _immediateCallback] (timers.js:383:17)
From previous event:
    at /scratch/jenkins/tools/jenkins.plugins.nodejs.tools.NodeJSInstallation/Node_Default/lib/node_modules/serverless/lib/Serverless.js:206:25
    at Array.reduce (native)
    at Serverless._execute (/scratch/jenkins/tools/jenkins.plugins.nodejs.tools.NodeJSInstallation/Node_Default/lib/node_modules/serverless/lib/Serverless.js:205:26)
    at Object.actions.(anonymous function) [as endpointBuildApiGateway] (/scratch/jenkins/tools/jenkins.plugins.nodejs.tools.NodeJSInstallation/Node_Default/lib/node_modules/serverless/lib/Serverless.js:424:20)
    at /scratch/jenkins/tools/jenkins.plugins.nodejs.tools.NodeJSInstallation/Node_Default/lib/node_modules/serverless/lib/actions/EndpointDeployApiGateway.js:172:36
From previous event:
    at /scratch/jenkins/tools/jenkins.plugins.nodejs.tools.NodeJSInstallation/Node_Default/lib/node_modules/serverless/lib/actions/EndpointDeployApiGateway.js:146:35
    at /scratch/jenkins/tools/jenkins.plugins.nodejs.tools.NodeJSInstallation/Node_Default/lib/node_modules/serverless/node_modules/async/lib/async.js:181:20
    at iterate (/scratch/jenkins/tools/jenkins.plugins.nodejs.tools.NodeJSInstallation/Node_Default/lib/node_modules/serverless/node_modules/async/lib/async.js:262:13)
    at /scratch/jenkins/tools/jenkins.plugins.nodejs.tools.NodeJSInstallation/Node_Default/lib/node_modules/serverless/node_modules/async/lib/async.js:274:29
    at /scratch/jenkins/tools/jenkins.plugins.nodejs.tools.NodeJSInstallation/Node_Default/lib/node_modules/serverless/node_modules/async/lib/async.js:44:16
    at /scratch/jenkins/tools/jenkins.plugins.nodejs.tools.NodeJSInstallation/Node_Default/lib/node_modules/serverless/lib/actions/EndpointDeployApiGateway.js:199:26
    at processImmediate [as _immediateCallback] (timers.js:383:17)
```
The same error is given for every subsequent endpoint in my project. It doesn't look like there's any attempt to sleep and retry, it simply logs the failure and proceeds to the next endpoint.

**Comment by ac360** [comment] 2016-03-30 14:44
We used to have our own sleep function, but removed it since the `aws-sdk` now has retry logic built in.  Perhaps this retry logic is not configured correctly in `ProviderAWS`.

**Comment by xzyfer** [comment] 2016-04-04 03:33
I can confirm the try settings do not appear to be [passed to the services](https://github.com/serverless/serverless/blob/master/lib/ProviderAws.js#L59)

>- retryDelayOptions (map) — A set of options to configure the retry delay on retryable errors. Currently supported options are:
>  - base [Integer] — The base number of milliseconds to use in the exponential backoff for operation retries. Defaults to 100 ms.
>  - customBackoff [function] — A custom function that accepts a retry count and returns the amount of time to delay in milliseconds. The base option will be ignored if this option is supplied.

I'd you could get away with hardcoding a sane set of default values and later expose the ability to configure it.

**Comment by eahefnawy** [comment] 2016-04-11 11:29
@marekmenhart-boa I just pushed a fix that I think should resolve your issue. However I can't really reproduce the issue easily. Could you try from the master branch and see if you're still seeing this issue?

FYI: You have to set a new env var: `AWS_RETRY_DELAY=300` (or some other value u like, we dont have a default)

**Comment by eahefnawy** [comment] 2016-04-15 11:28
We released the fix, I'm gonna close this and reopen if its still not working for u.

**Closed by eahefnawy** 2016-04-15 11:28 UTC
Labels: bug: confirmed, discussion, effort: easy, in progress, priority: medium

**Comment by marekmenhart-boa** [comment] 2016-04-18 22:42
@eahefnawy I tried it out today after updating to the latest Serverless version and setting the AWS_RETRY_DELAY environment variable, but I still run into the same error.

Here's a stack trace when I run 
serverless endpoint deploy -s <myStage> --debug
at the root of my project:
http://pastebin.com/wA51PpbH

And here's a stack trace when I run the same command inside one of my function directories:
http://pastebin.com/BZEV9prY

If I modify my function file so that it contains only the 3 endpoints that failed to deploy, they deploy successfully. This tells me the problem isn't with my function configuration, but rather the total number of endpoints causing me to hit the rate limit and then failing.

Thanks for your help so far.

**Comment by HyperBrain** [comment] 2016-04-22 13:59
@eahefnawy @marekmenhart-boa I ran into the issue too, today. Tried to deploy 50+ endpoints and after some it always fails with 0.5.5.
I switched to `master` and then it worked. I assume that the APIG REST API caching fix that's applied there solved the problem. The question now is, if it solves the problem under all conditions.

I think this is critical and the fix should be released asap.

**Comment by HyperBrain** [comment] 2016-04-22 14:06
UPDATE: Seems to be fixed by this PR
https://github.com/serverless/serverless/pull/1025

**Comment by marekmenhart-boa** [comment] 2016-04-22 15:36
I can confirm the latest version in master fixes the issue I was seeing. 

I did a full deployment of all endpoints in my project, and on every 429 response Serverless slept for 5 seconds before retrying successfully. It's working as it should.

**Comment by OneMuppet** [comment] 2016-06-02 22:50
@marekmenhart-boa  I'm running this from jenkins using version 0.5.5 of serverless and I'm still seeing this error.

First I run this command which is successfull:
node_modules/serverless/bin/serverless function deploy -s test -r eu-west-1 -a

Then I run this:
node_modules/serverless/bin/serverless endpoint deploy -s test -r eu-west-1 -a

Which gives this error (even though it looks like a success at the top):

Serverless: Deploying endpoints in "test" to the following regions: eu-west-1  
Serverless: Loading... Done!
Serverless: Successfully deployed endpoints in "test" to the following regions:  
Serverless: eu-west-1 ------------------------  
Serverless:   GET - getCustomer/{customerId} - https://0tq2m1by5c.execute-api.eu-west-1.amazonaws.com/test/getCustomer/{customerId}  
Serverless:   OPTIONS - getCustomer/{customerId} - https://0tq2m1by5c.execute-api.eu-west-1.amazonaws.com/test/getCustomer/{customerId}  
Serverless:   GET - getMyCustomerInfo/{customerId} - https://0tq2m1by5c.execute-api.eu-west-1.amazonaws.com/test/getMyCustomerInfo/{customerId}  
Serverless:   OPTIONS - getMyCustomerInfo/{customerId} - https://0tq2m1by5c.execute-api.eu-west-1.amazonaws.com/test/getMyCustomerInfo/{customerId}  
Serverless:   GET - getMyInfo/{userName} - https://0tq2m1by5c.execute-api.eu-west-1.amazonaws.com/test/getMyInfo/{userName}  
Serverless:   OPTIONS - getMyInfo/{userName} - https://0tq2m1by5c.execute-api.eu-west-1.amazonaws.com/test/getMyInfo/{userName}  

**Serverless: Failed to deploy endpoints in "test" to the following regions:  
Serverless: eu-west-1** ------------------------  
Serverless:   GET - getUser/{userName}: Too Many Requests  
Serverless:   OPTIONS - getUser/{userName}: Too Many Requests  
Serverless:   POST - resetPassword: Too Many Requests  
Serverless:   OPTIONS - resetPassword: Too Many Requests  
Serverless:   GET - searchUsers/{searchQuery}: Too Many Requests  
Serverless:   OPTIONS - searchUsers/{searchQuery}: Too Many Requests  
Serverless:   POST - updateUser: Too Many Requests  
Serverless:   OPTIONS - updateUser: Too Many Requests  
Serverless:   GET - AdministrateUserAccountServiceWSDL: Too Many Requests  
Serverless:   OPTIONS - AdministrateUserAccountServiceWSDL: Too Many Requests  
Serverless:   
Serverless: Run this again with --debug to get more error information...  
Finished: SUCCESS

did you have to set the AWS_RETRY_DELAY and where did you set this? Any help would be awesome! :)

**Comment by HyperBrain** [comment] 2016-06-02 22:53
0.5.5 has this bug. it is fixed in the master branch.

**Comment by OneMuppet** [comment] 2016-06-02 22:56
@HyperBrain Then I will sleep better tonight! I have a customer sprint demo tomorrow and was hoping to get the auto build for our serverless applications in place. I really appreciate your help and the laser quick response time! :)

**Comment by marcelog** [comment] 2017-04-04 17:57
Hi guys!

I'm seeing the "Too Many Requests" error when deploying with 1.9.0. I'm setting the environment variable `AWS_RETRY_DELAY=30` but it's not helping. Anything else I can try to solve this issue?

Thanks!

**Comment by pmuens** [comment] 2017-04-05 07:57
@marcelog do you know the root cause of this problem? Is there a way to reproduce this?

I'm curious because we've migrated the `v0` codebase to `v1` and the fix described above should also be available in `v1`.

**Comment by marcelog** [comment] 2017-04-05 18:13
Hi @pmuens,

So this is not currently happening, but it did happen in 3 different times right at the end of the deploy (i.e: everything was being deployed correctly, and just before returning to the shell, I got the error after the "Stack Outputs" part).

I'm trying to reproduce it so I can post the logs. I'm using the [serverless-aws-documentation plugin](https://github.com/9cookies/serverless-aws-documentation) and I do have *a lot* of models, I'm not sure if plugins can trigger this error.

I'll keep you guys posted if it happens again. Thank you :)

**Comment by HyperBrain** [comment] 2017-04-05 18:17
Yes, that can be caused by the plugin. Especially models generate lots of additional resources in the generated CF template. If they are not made dependent by the plugin to serialize the creation by CloudFormation, it can happen that CF internally receives a 429 (Too many requests) error, from which it cannot recover.

**Comment by pmuens** [comment] 2017-04-06 07:13
@marcelog yes, I think @HyperBrain is right. This is very likely the cause of the documentation plugin. Maybe it's worth to open up an issue over there.

Let us know if this is still an issue if you don't use that plugin. 👍

**Comment by marcelog** [comment] 2017-04-06 13:36
Thanks for your help @pmuens and @HyperBrain, I've opened 9cookies/serverless-aws-documentation#34 to follow up on this.

Best!
