### ISSUE TITLE
stream-event compiler fails to parse non-string arn parameter

### ISSUE THREAD

**Issue by jjuitt** [serverless/serverless#2812] opened 2016-11-28 10:49 UTC
# This is a Bug Report

## Description

For bug reports:
* What went wrong?
Generating handler for stream event fails with error  
`EventSourceArn.split is not a function`
* What did you expect should have happened?
Cloudformation template would have been successfully generated and function deployed.
* What was the config you used?
```yml
  dynamoTrigger:
    handler: handler.trigger
    description: "Neat description"
    events:
      - stream:
          arn:
            Fn::GetAtt:
              - DynamoTableInResources
              - StreamArn
```
Current [documentation](https://serverless.com/framework/docs/providers/aws/events/streams/) shows that it is fine to generate the ARN using CF functions.
* Serverless stacktrace (relevant parts)
```
TypeError: EventSourceArn.split is not a function
    at functionObj.events.forEach.event (/node_modules/serverless/lib/plugins/aws/deploy/compile/events/stream/index.js:60:47)
    at Array.forEach (native)
    at serverless.service.getAllFunctions.forEach (/node_modules/serverless/lib/plugins/aws/deploy/compile/events/stream/index.js:20:28)
    at Array.forEach (native)
    at AwsCompileStreamEvents.compileStreamEvents (/node_modules/serverless/lib/plugins/aws/deploy/compile/events/stream/index.js:16:47)
    at BbPromise.reduce (/node_modules/serverless/lib/classes/PluginManager.js:160:50)
    at tryCatcher 
```

Similar or dependent issues:
* [#2365](https://github.com/serverless/serverless/issues/2365)
Seems like I jumped the gun a little, since that is an exact clone.

## Additional Data

* ***Serverless Framework Version you're using***:
1.2
* ***Operating System***:
Ubuntu 16.04

**Comment by jjuitt** [comment] 2016-11-28 12:25
Seems like this bug is being worked on in [#2488](https://github.com/serverless/serverless/pull/2488).
However, I didn't see any test cases for
```yml
dynamoTrigger:
    handler: handler.trigger
    description: "Neat description"
    events:
      - dynamodb:
          arn:
            Fn::GetAtt:
              - DynamoTableInResources
              - StreamArn
```
while event `kinesis` had a test case for `Fn::GetAtt:` structure. Will it not support GetAtt for DynamoDB streams?

**Comment by pmuens** [comment] 2016-11-28 15:44
@jjuitt thanks for bringing this up 👍 

Yes, @eahefnawy is currently working on this in #2488. Unfortunately we're currently a little bit blocked because of a race-condition during initial deployment.

The first deployment fails, however the second one succeeds. We're currently looking into this issue so that `Kinesis` and `DynamoDB` stream support is working fine soon again!

**Comment by pmuens** [comment] 2016-12-06 10:56
@jjuitt Thanks again for bringing this up and providing information on how to reporduce it.

I'll close this one as it's a duplicate of #2365 and @eahefnawy is already working on it in #2488.

Hopefully we get something in place here pretty soon!

**Closed by pmuens** 2016-12-06 10:56 UTC
Labels: kind/bug, status/more-info-needed

**Comment by SwanandBhuskute** [comment] 2025-01-07 12:30
is this error solved?
I got the same error
TypeError: EventSourceArn.split is not a function
while working on serverless
