### ISSUE TITLE
Precedence of AWS_PROFILE and AWS_ACCESS_KEY_ID in Serverless is the reverse of AWS CLI

### ISSUE THREAD

**Issue by duboisj-illuminate** [serverless/serverless#9091] opened 2021-03-09 07:14 UTC
In the AWS CLI, a user may authenticate by setting either AWS_PROFILE or both AWS_ACCESS_KEY_ID and AWS_SECRET_ACCESS_KEY in the environment.  If AWS_PROFILE is set, it must match the name of a profile set in the user's AWS credentials configuration.

Using Serverless 2.28.7 (and past versions as well), if both AWS_PROFILE and the AWS_ACCESS_KEY_ID/AWS_SECRET_ACCESS_KEY pair are set, then using the AWS CLI (for instance, aws sts get-caller-identity), the AWS_ACCESS_KEY_ID/AWS_SECRET_ACCESS_KEY pair "win" and are used to authenticate.  Using Serverless, if both AWS_PROFILE and the AWS_ACCESS_KEY_ID/AWS_SECRET_ACCESS_KEY pair are set, then the AWS_PROFILE "wins" and is used to authenticate.

I would expect that the order of preference of these authentication mechanisms in Serverless would match the AWS CLI.  In other words, in Serverless, if the AWS_ACCESS_KEY_ID/AWS_SECRET_ACCESS_KEY pair are set, those credentials should be used in preference to AWS_PROFILE, even if AWS_PROFILE is set.

<details>
<summary><code>serverless.yml</code></summary>

```yaml
# ⚠️⚠️ REPLACE THIS COMMENT WITH FULL serverless.yml CONTENT
```

</details>

<details>
<summary><b><code>⚠️⚠️ REPLACE WITH FULL COMMAND NAME</code> output</b></summary>

```
⚠️⚠️ REPLACE WITH FULL COMMAND OUTPUT
```

</details>

<b>Installed version</b>

```
⚠️⚠️ REPLACE WITH `serverless --version` OUTPUT
```

**Comment by pgrzesik** [comment] 2021-03-11 10:09
Thanks for reporting @duboisj-illuminate :bow: I've managed to replicate that behavior - @medikoo Do you happen to know the reason behind not following the standard credentials precedence for AWS (https://docs.aws.amazon.com/cli/latest/topic/config-vars.html#id1) but rather "promoting" profile use?

**Comment by medikoo** [comment] 2021-03-11 10:17
>@medikoo Do you happen to know the reason behind not following the standard credentials precedence for AWS (https://docs.aws.amazon.com/cli/latest/topic/config-vars.html#id1) 

@pgrzesik not really, I think it was some unfortunate decision of the past.

I would definitely rework our credentials resolution so it closely matches what's happening when `aws-sdk` is used, still ofc that's a breaking change.

I believe first good step is to seclude credentials resolution from `Serverless` class, and placing it into `lib/aws/resolve-credentials.js` util (that should be not breaking). Thank having that in we can introduce necessary changes behind deprecation flag.

Related issue: https://github.com/serverless/serverless/issues/3415

**Comment by pgrzesik** [comment] 2021-03-15 12:30
Thanks for clarification @medikoo - I agree that it would be good to first refactor the current piece of logic and they introduce a deprecation and allow to opt-in to new behavior (default by AWS) :+1:

**Comment by medikoo** [comment] 2021-06-07 11:22
Closing as duplicate of https://github.com/serverless/serverless/issues/9290

**Closed by medikoo** 2021-06-07 11:22 UTC
Labels: cat/aws-auth, help wanted
