### ISSUE TITLE
404 Not Found: @serverless/fdk@^0.5.1

### ISSUE THREAD

**Issue by 29er** [serverless/serverless#4495] opened 2017-11-26 00:58 UTC
upon **npm install serverless -g** , I get this error .
_404 Not Found: @serverless/fdk@^0.5.1_
does anyone know what this is about ?

**Comment by horike37** [comment] 2017-11-27 15:16
Thank you for opening up @29er :+1: 
Could you please re-write this issue according to the issue template?
Otherwise, we can not take a look at the cause.

**Comment by hwangar** [comment] 2017-11-29 20:39
I'm having same issue while trying to npm i --save serverless, tracking the error it seems related to fdk:

`
npm install @serverless/fdk
npm ERR! registry error parsing json
npm ERR! Darwin 15.6.0
npm ERR! argv "/Users/hwangar/.nvm/versions/node/v6.12.0/bin/node" "/Users/hwangar/.nvm/versions/node/v6.12.0/bin/npm" "install" "@serverless/fdk"
npm ERR! node v6.12.0
npm ERR! npm  v3.10.10

npm ERR! Unexpected token < in JSON at position 0
npm ERR! <!DOCTYPE HTML PUBLIC "-//IETF//DTD HTML 2.0//EN">
npm ERR! <html><head>
npm ERR! <title>404 Not Found</title>
npm ERR! </head><body>
npm ERR! <h1>Not Found</h1>
npm ERR! <p>The requested URL /repository/npm-private/@serverless/fdk was not found on this server.</p>
npm ERR! </body></html>
`

**Comment by hwangar** [comment] 2017-11-29 20:44
Same error here: guilty... a .npmrc custom configuration to a private npm repo :(

**Comment by HyperBrain** [comment] 2017-12-01 13:38
Could be related to this https://github.com/npm/npm/issues/19254

**Comment by horike37** [comment] 2017-12-02 05:37
Thanks @HyperBrain for providing the info.
Closing this issue for now since it seems the root cause is on npm end

**Closed by horike37** 2017-12-02 05:37 UTC
Labels: kind/bug, status/more-info-needed
