### ISSUE TITLE
service.package.artifact Doesn't get set on `sls deploy -f`

### ISSUE THREAD

**Issue by dschep** [serverless/serverless#4898] opened 2018-04-10 12:18 UTC
# This is a Bug Report

## Description

For bug reports:
* [serverless-python-requirements](https://github.com/UnitedIncome/serverless-python-requirements) expects to be able to use `service.package.artifact` to reference the zip artifact that serverless creates. This works file with `sls package` and `sls deploy` but is set to `undefined` when invoking `sls deploy -f somefunc`

Similar or dependent issues:
* UnitedIncome/serverless-python-requirements#161

## Additional Data

* ***Serverless Framework Version you're using***: v1.26.1
* ***Operating System***: All
* ***Stack Trace***:
* ***Provider Error messages***:

**Comment by horike37** [comment] 2018-04-10 19:30
Thanks @dschep for the bug report :+1: 
I just reproduced this one on my laptop too and added help-wanted tag so that someone can pick it up.

**Comment by tavin** [comment] 2019-09-14 11:26
Reproduced with serverless 1.52.0 and serverless-python-requirements 5.0.0. Cannot use deploy -f anymore due to the exception `TypeError: Cannot read property 'artifact' of undefined` on L176 of `serverless-python-requirements/index.js`. It used to work with older versions of serverless but I'm not sure of the exact version number.

**Comment by zmoog** [comment] 2019-09-20 23:23
I'm having the same error using serverless-python-requirements@5.0.0:

* serverless@1.51.0 : works
* serverless@1.52.1 : `typeError: Cannot read property 'artifact' of undefined`

**Comment by pgrzesik** [comment] 2021-12-03 14:13
Hello everyone, I'm closing this issue as it was originally a bug on plugin side and it should be already addressed: https://github.com/serverless/serverless-python-requirements/issues/414

**Closed by pgrzesik** 2021-12-03 14:13 UTC
Labels: bug, help wanted, cat/packaging
