### ISSUE TITLE
Benchmark codebase to analyze slow parts

### ISSUE THREAD

**Issue by pmuens** [serverless/serverless#1080] opened 2016-05-10 15:06 UTC
We want the CLI to be extremely fast. To make sure we're optimising the right areas we need to create benchmarks that can show us which part of the tool are slow and where we can improve to deliver a great experience to customers.

We need to be able to run those benchmarks with various plugins loaded to measure speed and added slowness of any plugin.

This might help while investigating: https://nodejs.org/en/docs/guides/simple-profiling/ and https://github.com/escomplex/complexity-report

**Comment by flomotlik** [comment] 2016-11-04 13:31
duplicate of #2609 so closing

**Closed by flomotlik** 2016-11-04 13:31 UTC
Labels: help-wanted
