### ISSUE TITLE
Exception append: entry name must be a non-empty string value while deploying a function

### ISSUE THREAD

**Issue by MrCoffey** [serverless/serverless#4437] opened 2017-11-02 22:45 UTC
HI there!, I am receiving a `append: entry name must be a non-empty string value` exception while trying to deploy a function to aws lambda. Nevertheless, after some handcraft, I could make it run after downgrade the serverless version to `1.23.0`.

My serverless.yml I am using looks like:

```yml
service: lambdas
provider:
  name: aws
  runtime: python3.6

functions:
  function_name:
    handler: function_name.run
    runtime: python3.6
```

Following is the full stack trace after running the command `SLS_DEBUG=* serverless deploy -v`:
```
Serverless: Load command run
Serverless: Load command config
Serverless: Load command config:credentials
Serverless: Load command create
Serverless: Load command install
Serverless: Load command package
Serverless: Load command deploy
Serverless: Load command deploy:function
Serverless: Load command deploy:list
Serverless: Load command deploy:list:functions
Serverless: Load command invoke
Serverless: Load command invoke:local
Serverless: Load command info
Serverless: Load command logs
Serverless: Load command login
Serverless: Load command logout
Serverless: Load command metrics
Serverless: Load command print
Serverless: Load command remove
Serverless: Load command rollback
Serverless: Load command rollback:function
Serverless: Load command slstats
Serverless: Load command plugin
Serverless: Load command plugin
Serverless: Load command plugin:install
Serverless: Load command plugin
Serverless: Load command plugin:uninstall
Serverless: Load command plugin
Serverless: Load command plugin:list
Serverless: Load command plugin
Serverless: Load command plugin:search
Serverless: Load command emit
Serverless: Load command config
Serverless: Load command config:credentials
Serverless: Load command rollback
Serverless: Load command rollback:function
Serverless: Invoke deploy
Serverless: Invoke package
Serverless: Invoke aws:common:validate
Serverless: Invoke aws:common:cleanupTempDir
Serverless: Packaging service...
Serverless: Excluding development dependencies...

  Error --------------------------------------------------

  append: entry name must be a non-empty string value

     For debugging logs, run again after setting the "SLS_DEBUG=*" environment variable.

  Stack Trace --------------------------------------------

Error: append: entry name must be a non-empty string value
    at Archiver.append (/Users/coffey/.nvm/versions/node/v8.8.1/lib/node_modules/serverless/node_modules/archiver/lib/core.js:509:24)
    at _.forEach (/Users/coffey/.nvm/versions/node/v8.8.1/lib/node_modules/serverless/lib/plugins/package/lib/zipService.js:85:17)
    at arrayEach (/Users/coffey/.nvm/versions/node/v8.8.1/lib/node_modules/serverless/node_modules/lodash/lodash.js:537:11)
    at Function.forEach (/Users/coffey/.nvm/versions/node/v8.8.1/lib/node_modules/serverless/node_modules/lodash/lodash.js:9359:14)
    at BbPromise.all.then (/Users/coffey/.nvm/versions/node/v8.8.1/lib/node_modules/serverless/lib/plugins/package/lib/zipService.js:84:13)
    at /Users/coffey/.nvm/versions/node/v8.8.1/lib/node_modules/serverless/node_modules/graceful-fs/graceful-fs.js:78:16
    at FSReqWrap.readFileAfterClose [as oncomplete] (fs.js:513:3)
From previous event:
    at Package.zipFiles (/Users/coffey/.nvm/versions/node/v8.8.1/lib/node_modules/serverless/lib/plugins/package/lib/zipService.js:74:12)
    at Package.resolveFilePathsAll.then.filePaths (/Users/coffey/.nvm/versions/node/v8.8.1/lib/node_modules/serverless/lib/plugins/package/lib/packageService.js:67:12)
From previous event:
    at Package.packageAll (/Users/coffey/.nvm/versions/node/v8.8.1/lib/node_modules/serverless/lib/plugins/package/lib/packageService.js:66:39)
    at BbPromise.all.then (/Users/coffey/.nvm/versions/node/v8.8.1/lib/node_modules/serverless/lib/plugins/package/lib/packageService.js:57:21)
From previous event:
    at Package.packageService (/Users/coffey/.nvm/versions/node/v8.8.1/lib/node_modules/serverless/lib/plugins/package/lib/packageService.js:55:43)
From previous event:
    at Object.package:createDeploymentArtifacts [as hook] (/Users/coffey/.nvm/versions/node/v8.8.1/lib/node_modules/serverless/lib/plugins/package/package.js:67:10)
    at BbPromise.reduce (/Users/coffey/.nvm/versions/node/v8.8.1/lib/node_modules/serverless/lib/classes/PluginManager.js:366:55)
From previous event:
    at PluginManager.invoke (/Users/coffey/.nvm/versions/node/v8.8.1/lib/node_modules/serverless/lib/classes/PluginManager.js:366:22)
    at PluginManager.spawn (/Users/coffey/.nvm/versions/node/v8.8.1/lib/node_modules/serverless/lib/classes/PluginManager.js:384:17)
    at Deploy.BbPromise.bind.then.then (/Users/coffey/.nvm/versions/node/v8.8.1/lib/node_modules/serverless/lib/plugins/deploy/deploy.js:120:50)
From previous event:
    at Object.before:deploy:deploy [as hook] (/Users/coffey/.nvm/versions/node/v8.8.1/lib/node_modules/serverless/lib/plugins/deploy/deploy.js:110:10)
    at BbPromise.reduce (/Users/coffey/.nvm/versions/node/v8.8.1/lib/node_modules/serverless/lib/classes/PluginManager.js:366:55)
From previous event:
    at PluginManager.invoke (/Users/coffey/.nvm/versions/node/v8.8.1/lib/node_modules/serverless/lib/classes/PluginManager.js:366:22)
    at PluginManager.run (/Users/coffey/.nvm/versions/node/v8.8.1/lib/node_modules/serverless/lib/classes/PluginManager.js:397:17)
    at variables.populateService.then (/Users/coffey/.nvm/versions/node/v8.8.1/lib/node_modules/serverless/lib/Serverless.js:104:33)
    at runCallback (timers.js:785:20)
    at tryOnImmediate (timers.js:747:5)
    at processImmediate [as _immediateCallback] (timers.js:718:5)
From previous event:
    at Serverless.run (/Users/coffey/.nvm/versions/node/v8.8.1/lib/node_modules/serverless/lib/Serverless.js:91:74)
    at serverless.init.then (/Users/coffey/.nvm/versions/node/v8.8.1/lib/node_modules/serverless/bin/serverless:42:50)
    at <anonymous>
```
## Local system info

OS: darwin
Node Version: 8.8.1
Serverless Version: 1.24.0

Please let me know if there is something missing in my report and I will be happy to update it. THANKS!

**Comment by HyperBrain** [comment] 2017-11-03 12:36
Hi @MrCoffey thanks for submitting the issue.

Can you please give a bit more information about the `append: entry name must be a non-empty string value`? The stacktrace you posted contains

> ServerlessError: The security token included in the request is invalid.

which points to an error with the AWS credentials used to deploy the function (either in the environment AWS_XXX or in the used profile). I do not see a relation to the exception, or am I missing something here?

**Comment by MrCoffey** [comment] 2017-11-03 14:07
Hi there @HyperBrain, so sorry I copy paste the wrong stacktrace, I just update it.

**Comment by HyperBrain** [comment] 2017-11-03 14:11
@serverless/framework-maintainers  It seems that this happens because SLS tries to add an empty filename to the ZIP archive using the Archiver. Were there any changes in that area for the 1.24 release?

**Comment by horike37** [comment] 2017-11-06 13:28
>Were there any changes in that area for the 1.24 release?

Umm, I can't remember anything for that :thinking: 

Hey @MrCoffey, Thank you for reporting that :+1: 
I tried to reproduce it with using node v8.8.1 and sls framework v1.24.0, but I was not able to see it.

We need any information more than what you already provided.
Could you share the pointer where your project is stored so that we can get a way which reproduce it?

**Comment by HyperBrain** [comment] 2017-11-06 13:32
@MrCoffey Could you post a list of your dependencies from package.json? I assume that one of them triggers the problem.

**Comment by MrCoffey** [comment] 2017-11-08 21:01
@horike37, @HyperBrain, I tried to reproduce the exception but looks like it was something with my local configuration, so if you don't mind I will close this for now.

**Comment by HyperBrain** [comment] 2017-11-08 21:07
@MrCoffey Thanks for the feedback 👍 . Just close it.

**Closed** 2017-11-09 17:43 UTC
Labels: kind/bug

**Comment by vladaman** [comment] 2018-02-22 17:24
Had a same problem. I accidentally had file named "\" in the folder and file could not be packed.

**Solution**: Check folder structure fro invalid file names.

**Comment by errordeveloper** [comment] 2018-08-17 13:11
I also encountered this. with a new keyboard I end up accidentally creating a file called `\` all the time.

The simplest way to reproduce this is `touch \ && serverless deploy`. I think the issue should be re-opend and this exception handled more gracefully.

**Comment by dhilst** [comment] 2019-02-18 16:50
I had the same problem as vladamn, if anyone is struggling trying to remove with '' name, `find . -inum 11837081 -exec rm {} \+` command can be used, where 11837081 is the file inone, that can be obtained from `ls -i`
