### ISSUE TITLE
Installing plugin provider bundles unnecessary dependencies into deployment artifact.

### ISSUE THREAD

**Issue by jthomas** [serverless/serverless#2895] opened 2016-12-08 16:09 UTC
# This is a (Bug Report / Feature Proposal)

Bug Report.

## Description

Provider plugins are now bundled as separate NPM modules and installed using `npm install`. 
This puts the provider module and it's dependencies inside the service's `node_modules` directory. When the service is packaged for deployment, these additional modules will be included in the zip file. 

Here's an example of the openwhisk boilerplate:
https://github.com/jthomas/serverless-openwhisk-boilerplate

Run `npm install` to see the output in `node_modules`. 

I did try to counter this by manually updating the `excludes` value to include the module name but with NPM3's module flattening, this doesn't work as all the child dependencies aren't excluded. 
https://github.com/serverless/serverless-openwhisk/blob/master/compile/functions/index.js#L21-L25

Looking at the framework's plugin registration mechanism, I was wondering whether this could be managed by having a new command, install-provider, which installs the provider plugins to a new `.` directory (`.serverless-providers`). The plugin manager would include this in the search path for plugin registration. The excludes paths would be updated to include this directory. 

I'm sure you have better ideas than I do for how to handle this :)

**Comment by pmuens** [comment] 2016-12-08 21:17
Thanks for reporting and giving such a detailed and helpful description (as usual!) @jthomas 👍 🎆  

I've faced exactly the same problem during the development of the Google Cloud plugin integration (see: https://github.com/serverless/serverless-google-cloudfunctions/issues/5).

Definitely a high priority as it is a usual problem when offering multi provider support through external Serverless plugins.

**Comment by mthenw** [comment] 2016-12-13 12:00
Maybe we could use special [`.serverless_plugins` folder](https://github.com/serverless/serverless/blob/dce44fc2493839bd93d1c21c5312035f72f91e64/docs/providers/aws/guide/plugins.md#service-local-plugin)?

**Comment by jthomas** [comment] 2016-12-13 12:28
Would a short term fix be to add a `--provider` flag to the `install` command which changed the output directory for the downloaded artifact to that folder?

**Comment by pmuens** [comment] 2017-01-05 14:16
Hey @jthomas sorry for the delay here. Let's pick this issue up again! 💯 

I think right now the best solution / workaround would be what @mthenw mentioned:
The provider plugin should be installed in the `.serverless_plugins` directory and then exclude it this directory from the packaging.

We need to think this through for a good, stable long term solution as this seems to be an general problem when integrating other providers through plugins.

The problem is that moving it to another place which is excluded from the build means that users don't have access to all the SDK functions anymore which they might want to use inside their functions to call other provider specific services. That was the idea when we implented the `getProvider('<provider-name-here>')` function.

Here are some possible solutions (summarized from this thread):

1. Create `.serverless_providers` directory in the Serverless and let developers install provider plugins with the Serverless CLI
2. Add a `--provider` flag to the `install` command
3. Put provider plugins in the `.serverless_plugins` directory and exclude them (no long-term fix) 👎 
4. Add a logic to the packaging mechanism which detects a provider plugin (e.g. based on the naming schema) and excludes it automatically (maybe surprising for the user)
...

I'll put this issue to the v1.6 milestone as it's an important feature!

**Comment by jthomas** [comment] 2017-01-05 15:35
Ignoring the implementation challenges, I think a combination of 1 & 2 would be the best developer experience. 

I can just `serverless install --provider openwhisk` and this plugin will be imported into `.serverless_providers`.

**Comment by nikgraf** [comment] 2017-01-05 17:40
@pmuens How would `.serverless_providers` work? Plugins often come with node_module dependencies or would this directory has it's own node_module dependencies? How does a user then know how to install them?

@jthomas It's an issue for all plugins and we need to find a solution that works also for all languages.
Main question: Is it a blocker to ship the plugin? Would it be okayish to ship it like this?

**Comment by pmuens** [comment] 2017-01-05 18:18
Thanks for the response @jthomas the suggestions sounds good!

Just wanted to link to this PR https://github.com/serverless/serverless/pull/2907 which implemented a plugin discovery and installation process through the CLI.

This could be easily extended (we could e.g. flag plugins as `provider` and `extension` plugins in the plugins registry) so that Serverless will automatically move the file in the `.serverless_provider` directory.

Additionally it would be convenient for the developer / the user to install provider plugins.

**Comment by jthomas** [comment] 2017-01-06 09:48
`npm install --production` on the openwhisk provider plugin installs a `node_modules` directory with ~22MB. 

This is nearly half the [maximum deployment package size](https://github.com/openwhisk/openwhisk/blob/master/docs/reference.md#system-limits) of 48MB.

It does work as is but will drastically slow down deployments and users will run into size limit issues much faster.

I assumed `.serverless_providers` directory would have it's own `node_modules` as @pmuens suggested.

**Comment by nikgraf** [comment] 2017-01-19 17:14
Now that I investigated a bit further @pmuens suggestion seems to be the best.

We would to do these things:
1. Ignore `.serverless_plugins` when packaged by default (useful for every plugin with Node & Python Packaging). Just add it to this list: https://github.com/serverless/serverless/blob/master/lib/plugins/package/lib/packageService.js#L7-L14
2. Ever template should have a `.serverless_plugins/package.json`. This is necessary so you can do `npm install --save-dev serverless-openwhisk` and it doesn't install it in the parent `node_modules` folder, but rather in `.serverless_plugins/node_modules`.
3. We also add `.serverless_plugins/node_modules` to that module.paths here https://github.com/serverless/serverless/blob/5b8aacf4d8caf3dc35063c28c269d8a09645cb1a/lib/classes/PluginManager.js#L80-L83

This way people can install plugins without the getting packaged. We don't break the process installing a plugin directly into `node_modules`, but in the docs we encourage the `.serverless_plugins/node_modules` way. I would love to go without it, but this seems to be the best solution I could come up with.

@pmuens @eahefnawy @jthomas @DavidWells What do you guys think?

**Comment by pmuens** [comment] 2017-01-20 08:30
@nikgraf thanks for the proposal 👍 

I like the solution because it doesn't introduce a large rewrite and won't break the existing packaging process. This is only one solution and might not be the prettiest but it does it's thing and provides a quick way to solve the multi-provider plugin issue (we also face with other provider plugins BTW).

Furthermore the whole packaging process benefits from that as we introduce a natural way / best practice how to add dependencies which are not bundled up into the deployment artifact.

I would propose that we go this way so that we have something in place soon.

We can continue the discussion to find a long-term strategy / solution.

**Comment by jthomas** [comment] 2017-01-23 13:53
LGTM - good compromise and minimal changes.
Will test this out when it's available.

**Comment by pmuens** [comment] 2017-01-23 14:03
Great! Thanks @jthomas 🙌

**Comment by pmuens** [comment] 2017-01-30 10:02
Moving this to the next milestone so that we can think it more through and work on this issue there...

**Comment by pmuens** [comment] 2017-02-03 09:58
@jthomas we got an interesting PR (#3180) which might be helpful for provider plugins and this issue in general...

**Comment by nrako** [comment] 2017-02-03 19:15
@jthomas thanks for your comment. 🤡.

I believe my PR opens up "new" possibilities. One could argue that will add complexity but I don't really think so. That small changes only allow the normal/expected behaviour of [node modules loading](https://nodejs.org/api/modules.html#modules_loading_from_node_modules_folders) to work. IMHO working against this well known node principle is counter-intuitive.

For inexperienced user, the documented way of installing plugins can stay the same and maybe leverage behind the scene something like the `.serverless_plugins` folder or something similar...

I believe more experienced user of JS will quickly look for solutions to transpile & bundle (i.e babel & webpack) their source into an optimised `handler.js` files with chunks for shared code. Possibly only having [native modules built with docker](https://github.com/serverless/serverless/issues/308#issuecomment-255626650) in the `node_modules` of the service folder to be packaged for deployment.

I'm only starting to play with serverless so I might miss something in the bigger picture...?

--- 

By the way I don't really understand the need for new folder conventions `.serverless_plugins` or `.serverless_providers`, the package script could simply excludes all `devDependencies` if a `package.json` is found no? I'll come with a PR soonish.

**Comment by nrako** [comment] 2017-02-03 19:20
oups about excluding all `devDependencies` I forgot NPM3 flattening... will think a bit more about this.

**Closed** 2018-06-12 16:03 UTC
Labels: kind/feature, stage/needs-feedback

**Comment by t-buss** [comment] 2018-11-12 13:15
The quickstart guide (https://serverless.com/framework/docs/providers/openwhisk/guide/quick-start/) still references this issue:

>Due to an outstanding issue with provider plugins, the OpenWhisk provider must be installed as a global module.

 Can one safely ignore this hint or is it still relevant?

**Comment by jthomas** [comment] 2018-11-12 14:45
@t-buss Ignore the docs - I need to update them.
