### ISSUE TITLE
npm-conf breaking change: Path must be a string. Received undefined

### ISSUE THREAD

**Issue by koterpillar** [serverless/serverless#3978] opened 2017-07-24 05:27 UTC
# This is a Bug Report

## Description

For bug reports:
* What went wrong?

`npm-conf` version 1.1.1 causes the following message on deployment:

```
  Type Error ---------------------------------------------
  Path must be a string. Received undefined
     For debugging logs, run again after setting the "SLS_DEBUG=*" environment variable.
  Stack Trace --------------------------------------------

  Get Support --------------------------------------------
     Docs:          docs.serverless.com
     Bugs:          github.com/serverless/serverless/issues
     Forums:        forum.serverless.com
     Chat:          gitter.im/serverless/serverless
  Your Environment Information -----------------------------
     OS:                     linux
     Node Version:           8.2.1
     Serverless Version:     1.18.0
```

* What did you expect should have happened?

Successful deploy.

## Additional Data

* ***Serverless Framework Version you're using***: 1.18.0
* ***Operating System***: Linux
* ***Stack Trace***:

```
TypeError: Path must be a string. Received undefined
    at assertPath (path.js:28:11)
    at Object.resolve (path.js:1167:7)
    at Conf.loadUser (/usr/local/lib/node_modules/serverless/node_modules/npm-conf/lib/conf.js:159:23)
    at module.exports.opts (/usr/local/lib/node_modules/serverless/node_modules/npm-conf/index.js:36:7)
    at Object.<anonymous> (/usr/local/lib/node_modules/serverless/node_modules/get-proxy/index.js:2:36)
    at Module._compile (module.js:569:30)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:503:32)
    at tryModuleLoad (module.js:466:12)
    at Function.Module._load (module.js:458:3)
    at Module.require (module.js:513:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/usr/local/lib/node_modules/serverless/node_modules/caw/index.js:3:18)
    at Module._compile (module.js:569:30)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:503:32)
    at tryModuleLoad (module.js:466:12)
    at Function.Module._load (module.js:458:3)
    at Module.require (module.js:513:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/usr/local/lib/node_modules/serverless/node_modules/download/index.js:5:13)
    at Module._compile (module.js:569:30)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:503:32)
    at tryModuleLoad (module.js:466:12)
    at Function.Module._load (module.js:458:3)
    at Module.require (module.js:513:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/usr/local/lib/node_modules/serverless/lib/plugins/install/install.js:6:18)
    at Module._compile (module.js:569:30)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:503:32)
    at tryModuleLoad (module.js:466:12)
    at Function.Module._load (module.js:458:3)
    at Module.require (module.js:513:17)
    at require (internal/module.js:11:18)
    at plugins.forEach (/usr/local/lib/node_modules/serverless/lib/classes/PluginManager.js:65:22)
    at Array.forEach (native)
    at PluginManager.loadPlugins (/usr/local/lib/node_modules/serverless/lib/classes/PluginManager.js:64:13)
    at PluginManager.loadCorePlugins (/usr/local/lib/node_modules/serverless/lib/classes/PluginManager.js:77:10)
    at PluginManager.loadAllPlugins (/usr/local/lib/node_modules/serverless/lib/classes/PluginManager.js:59:10)
    at service.load.then (/usr/local/lib/node_modules/serverless/lib/Serverless.js:64:28)
    at <anonymous>
From previous event:
    at runCallback (timers.js:781:20)
    at tryOnImmediate (timers.js:743:5)
    at processImmediate [as _immediateCallback] (timers.js:714:5)
From previous event:
    at __dirname (/usr/local/lib/node_modules/serverless/bin/serverless:25:46)
    at Object.<anonymous> (/usr/local/lib/node_modules/serverless/bin/serverless:43:4)
    at Module._compile (module.js:569:30)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:503:32)
    at tryModuleLoad (module.js:466:12)
    at Function.Module._load (module.js:458:3)
    at Function.Module.runMain (module.js:605:10)
    at startup (bootstrap_node.js:158:16)
    at bootstrap_node.js:575:3
```

Downgrading `npm-conf` to `1.1.0` makes a successful deployment again.

**Comment by kevva** [comment] 2017-07-24 05:58
I've published `1.1.2`, could you try again?

**Comment by huysamen** [comment] 2017-07-24 06:01
Just checked, working 100% again thanks.

**Comment by pmuens** [comment] 2017-07-24 06:25
Thanks for opening @koterpillar and thanks for fixing @kevva 👍

Closing this for now since it looks like `npm-conf` `1.1.2` has fixed the bug.

Furthermore it's not directly related to the Serverless Framework core. Feel free to continue the discussion / comment if you still face some issues.

**Closed by pmuens** 2017-07-24 06:25 UTC

**Comment by dashmug** [comment] 2017-07-25 04:21
I'm having this same problem but it seems like the cause is different.

I don't have `npm-conf` in my `node_modules`. I'm using `serverless-webpack` but I don't think that's the culprit.

```
Serverless: Packaging service...
TypeError: Path must be a string. Received undefined
    at assertPath (path.js:7:11)
    at Object.basename (path.js:1355:5)
    at functionNames.forEach.name (/Users/dashmug/Documents/workspace/project/node_modules/serverless-webpack/lib/cleanup.js:27:28)
    at Array.forEach (native)
    at fse.copy (/Users/dashmug/Documents/workspace/project/node_modules/serverless-webpack/lib/cleanup.js:23:31)
    at doneOne (/Users/dashmug/Documents/workspace/project/node_modules/fs-extra/lib/copy/ncp.js:237:40)
    at /Users/dashmug/Documents/workspace/project/node_modules/fs-extra/lib/copy/ncp.js:122:11
    at /Users/dashmug/Documents/workspace/project/node_modules/graceful-fs/polyfills.js:239:18
    at FSReqWrap.oncomplete (fs.js:123:15)
```

`node v6.10.1`
`yarn v0.27.5`
`serverless v1.18.0`

**Comment by HyperBrain** [comment] 2017-07-25 09:22
According to @dashmug 's comment (https://github.com/elastic-coders/serverless-webpack/issues/159#issuecomment-317630614) it did not appear with Serverless 1.17.
