### ISSUE TITLE
Configuration warning: unrecognized property 'module'

### ISSUE THREAD

**Issue by luislhl** [serverless/serverless#8423] opened 2020-10-21 03:41 UTC
I'm getting this warning during deploys when trying to use the functions `module` option, since version 2.7.0.
The same thing works with 2.6.0

<details>
<summary><code>serverless.yml</code></summary>

```yaml
service: boilerplate-lambda

provider:
  name: aws
  runtime: python3.7
  stage: dev

package:
  individually: true

functions:
  lambda-1:
    module: lambda1 
    handler: src/main.main

  lambda-2:
    module: lambda2
    handler: src/main.main

plugins:
  - serverless-python-requirements
```

</details>

<details>
<summary><b><code>serverless deploy</code> output</b></summary>

```
Serverless: Configuration warning:
Serverless:   at 'functions['lambda-1']': unrecognized property 'module'
Serverless:   at 'functions['lambda-2']': unrecognized property 'module'
Serverless:  
Serverless: Learn more about configuration validation here: http://slss.io/configuration-validation
```

</details>

<b>Installed version</b>

```
Framework Core: 2.7.0
Plugin: 4.1.1
SDK: 2.3.2
Components: 3.2.4
```

**Comment by luislhl** [comment] 2020-10-21 03:44
I'm not sure if this was the cause, but this commit seems to have changed something related to this validation: https://github.com/serverless/serverless/commit/719fa3a3bf8e5d5dfa135a8225519fc77b719c8e

**Comment by fredericbarthelet** [comment] 2020-10-25 17:31
Hi @luislhl , thanks for reporting your issue.

The commit you reference did in fact remove validation relaxation on function definitions.
You can see the full schema used for validation in https://github.com/serverless/serverless/blob/2d6824cde531ba56758f441b39b5ab018702e866/lib/plugins/aws/provider/awsProvider.js#L776-L845

The `module` property is not defined as a valid function property.
I don't see any reference of this property within the Serverless documentation.

I see the use of `serverless-python-requirements` plugin in your exemple file. Plugin developers should add definition for properties used by their plugin within their code base following https://www.serverless.com/framework/docs/providers/aws/guide/plugins/#extending-validation-schema documentation.

As of today, you can add in `serverless.yaml` root `configValidationMode: off` and it will disable display of those error messages. You however won't benefit from JSON schema validation for other properties of your service file.

@medikoo do you think, similarly to #8438, that an additional method defineFunctionProperties should be implemented ? The idea would be to allow `serverless-python-requirements` plugin to enrich function common schema with their `module` property schema.

**Comment by luislhl** [comment] 2020-10-27 16:07
Thanks for your reponse, @fredericbarthelet 

> I don't see any reference of this property within the Serverless documentation.
Indeed, I didn't find it either. It only exists in the serverless-python-requirements plugin docs: https://www.serverless.com/plugins/serverless-python-requirements

But it is now clearer to me what happened for this to break and that this is a custom field used only by the plugin.

I'll think about the best option for me. Feel free to close the issue if you need to.

**Comment by medikoo** [comment] 2020-10-28 08:49
This issue is about same issue as we discuss at https://github.com/serverless/serverless/issues/8422, I'm going to close it, and let's follow discussion over there.

**Comment by medikoo** [comment] 2020-10-28 08:49
Duplicate of #8422

**Closed by medikoo** 2020-10-28 08:49 UTC
