### ISSUE TITLE
Allow array of `${file(..)}` for `provider` and `custom` config

### ISSUE THREAD

**Issue by mikestopcontinues** [serverless/serverless#6677] opened 2019-09-12 15:32 UTC
# This is a Feature Proposal

## Description

We can already merge config objects for  `resources` and `functions` fields, but `provider` and `custom` can prove just as unwieldy. We should have an easy way to reuse and merge config for this field.

My particular use case is very basic. I share a lot of boilerplate config between services, and I just want to be able to add or overwrite a handful of options between them.

**Comment by gdraynz** [comment] 2019-10-01 12:14
I stumbled upon this issue as well when trying to split things from my `serverless.yml` file, just like this:
```yaml
service: testing

provider:
  name: aws
  runtime: python3.7

layers:
  - ${file(myfile.yml):layers}

functions:
  - ${file(myfile.yml):functions}
```
```yaml
functions:
  myfunction:
    handler: myfunction.handler
    layers: { Ref: MyRequirementsLambdaLayer }

layers:
  myRequirements:
    path: requirements
```
This example will work just fine for functions, but not for the layers:
```
TypeError [ERR_INVALID_ARG_TYPE]: The "path" argument must be of type string. Received type undefined
```

**Comment by medikoo** [comment] 2021-04-12 15:25
Closing as duplicate of #8037

**Closed by medikoo** 2021-04-12 15:25 UTC
Labels: cat/variable, enhancement
