### ISSUE TITLE
Jar not deployed to Lambda after first deployment 

### ISSUE THREAD

**Issue by rickydunn** [serverless/serverless#1888] opened 2016-08-17 20:38 UTC
##### Serverless Framework Version: 

v1.0.0-beta.1.1

##### Actual Behaviour:

Currently experiencing an issue on subsequent `mvn package` and `sls deploy` (post first deployment) on AWS which copies a Jar from the `Target` folder to the S3 bucket but does not deploy it to Lambda.

The deployment appears successful (no errors) and the Jar exists on S3 in the correct bucket, but the new Jar is not deployed as a version to Lambda, I've verified this by downloading the latest package from the AWS Lambda Console GUI and inspecting it.

Other things to note:

- If I download the Jar from S3, and manually upload via the GUI it works correctly
- I only see 1 Jar in the S3 bucket, it does not seem to maintain the last 5 versions, as per the docs (it replaces the previous Jar in all cases)
- This does not occur with Node.js - it deploys correctly and maintains the last 5 versions
- A `mvn clean` does not make a difference. 

If I remove the function and re-deploy it works correctly for the first deployment - subsequent deployments this issue continues to occur.

If I edit `serverless.yml` and reference another Jar name under the `artifact` key I can then deploy the Jar, but again only the first time, subsequent attempts using the same Jar name causes the same issues.

The lambda is invoked via a HTTP event.

Please let me know if you'd like any more information and keep up the good work 👍🏻

**Comment by flomotlik** [comment] 2016-08-18 14:39
This is a duplicate of #1862 and the issue is that as the artefact isn't renamed the Cloudformation stack has no updates and thus doesn't actually do the update. Will be fixed soon and discussed in the other issue.

**Closed by flomotlik** 2016-08-18 14:39 UTC
