### ISSUE TITLE
serverless deprecation warning

### ISSUE THREAD

**Issue by codepreneur** [serverless/serverless#1796] opened 2016-08-08 20:55 UTC
I get the below every time I run `env SLS_DEBUG=true sls invoke -f loadvideos -l`

```
Deprecation warning: moment construction falls back to js Date. This is discouraged and will be removed in upcoming major release. Please refer to http://momentjs.com/guides/#/warnings/js-date/ for more info.
Arguments: [object Object]
Error
    at Function.createFromInputFallback (/usr/local/lib/node_modules/serverless/node_modules/moment/moment.js:285:105)
    at configFromString (/usr/local/lib/node_modules/serverless/node_modules/moment/moment.js:2015:32)
    at configFromInput (/usr/local/lib/node_modules/serverless/node_modules/moment/moment.js:2375:13)
    at prepareConfig (/usr/local/lib/node_modules/serverless/node_modules/moment/moment.js:2358:13)
    at createFromConfig (/usr/local/lib/node_modules/serverless/node_modules/moment/moment.js:2325:44)
    at createLocalOrUTC (/usr/local/lib/node_modules/serverless/node_modules/moment/moment.js:2412:16)
    at local__createLocal (/usr/local/lib/node_modules/serverless/node_modules/moment/moment.js:2416:16)
    at utils_hooks__hooks (/usr/local/lib/node_modules/serverless/node_modules/moment/moment.js:16:29)
    at formatLambdaLogEvent (/usr/local/lib/node_modules/serverless/lib/plugins/aws/invoke/index.js:89:32)
    at logResult.split.forEach.line (/usr/local/lib/node_modules/serverless/lib/plugins/aws/invoke/index.js:99:61)
    at Array.forEach (native)
    at AwsInvoke.log (/usr/local/lib/node_modules/serverless/lib/plugins/aws/invoke/index.js:99:29)
    at AwsInvoke.tryCatcher (/usr/local/lib/node_modules/serverless/node_modules/bluebird/js/release/util.js:16:23)
    at Promise._settlePromiseFromHandler (/usr/local/lib/node_modules/serverless/node_modules/bluebird/js/release/promise.js:504:31)
    at Promise._settlePromise (/usr/local/lib/node_modules/serverless/node_modules/bluebird/js/release/promise.js:561:18)
    at Promise._settlePromise0 (/usr/local/lib/node_modules/serverless/node_modules/bluebird/js/release/promise.js:606:10)
```

**Comment by flomotlik** [comment] 2016-08-19 13:27
I just tested it with the latest master and this doesn't happen anymore (probably because we updated dependencies). Could you try this again and report in case this still happens. Until then I'm closing.

**Comment by joh-mue** [comment] 2016-10-12 13:42
Unfortunately for serverless v1.0.0-rc2 and v1.0.0 this is happening for me too:

```
sls invoke --function benchmark --path event.json --log true | tee -a responses.log
{
    "test": "v0.1",
    "event": {
        "key1": "value1",
        "payloadName": "payload.py",
        "bucketName": "python-benchmark-bucket"
    }
}
--------------------------------------------------------------------
START RequestId: 16029e66-9081-11e6-afa1-d9e0167c69c1 Version: $LATEST
Deprecation warning: value provided is not in a recognized ISO format. moment construction falls back to js Date(), which is not reliable across all browsers and versions. Non ISO date formats are discouraged and will be removed in an upcoming major release. Please refer to http://momentjs.com/guides/#/warnings/js-date/ for more info.
Arguments:
[0] _isAMomentObject: true, _isUTC: false, _useUTC: false, _l: undefined, _i: [INFO], _f: undefined, _strict: undefined, _locale: [object Object]
Error
    at Function.createFromInputFallback (/usr/local/lib/node_modules/serverless/node_modules/moment/moment.js:309:98)
    at configFromString (/usr/local/lib/node_modules/serverless/node_modules/moment/moment.js:2048:32)
    at configFromInput (/usr/local/lib/node_modules/serverless/node_modules/moment/moment.js:2408:13)
    at prepareConfig (/usr/local/lib/node_modules/serverless/node_modules/moment/moment.js:2391:13)
    at createFromConfig (/usr/local/lib/node_modules/serverless/node_modules/moment/moment.js:2358:44)
    at createLocalOrUTC (/usr/local/lib/node_modules/serverless/node_modules/moment/moment.js:2445:16)
    at local__createLocal (/usr/local/lib/node_modules/serverless/node_modules/moment/moment.js:2449:16)
    at utils_hooks__hooks (/usr/local/lib/node_modules/serverless/node_modules/moment/moment.js:16:29)
    at formatLambdaLogEvent (/usr/local/lib/node_modules/serverless/lib/plugins/aws/invoke/index.js:89:32)
    at logResult.split.forEach.line (/usr/local/lib/node_modules/serverless/lib/plugins/aws/invoke/index.js:99:61)
    at Array.forEach (native)
    at AwsInvoke.log (/usr/local/lib/node_modules/serverless/lib/plugins/aws/invoke/index.js:99:29)
    at AwsInvoke.tryCatcher (/usr/local/lib/node_modules/serverless/node_modules/bluebird/js/release/util.js:16:23)
    at Promise._settlePromiseFromHandler (/usr/local/lib/node_modules/serverless/node_modules/bluebird/js/release/promise.js:510:31)
    at Promise._settlePromise (/usr/local/lib/node_modules/serverless/node_modules/bluebird/js/release/promise.js:567:18)
    at Promise._settlePromise0 (/usr/local/lib/node_modules/serverless/node_modules/bluebird/js/release/promise.js:612:10)
Invalid date	2016-10-12T13:37:57.601Z	16029e66-9081-11e6-afa1-d9e0167c69c1	Running Benchmark.
END RequestId: 16029e66-9081-11e6-afa1-d9e0167c69c1
REPORT RequestId: 16029e66-9081-11e6-afa1-d9e0167c69c1	Duration: 0.54 ms	Billed Duration: 100 ms 	Memory Size: 512 MB	Max Memory Used: 14 MB
```
the code causing this is appears to be my logger output
```
logger = logging.getLogger()
logger.setLevel(logging.INFO)
logger.info("Any Log message")
```

**Comment by flomotlik** [comment] 2016-10-12 13:45
@joh-mue as this is a problem in code and not in the Framework we can't really give too much support on this here, but could you post this into the Forum: forum.serverless.com . You should be able to get some more help there.

**Comment by joh-mue** [comment] 2016-10-12 13:50
thanks for the fast feedback.
it does comes back clean when I test it through the AWS console directly, so I figured it must be sth in the framework. I'll give the forum a shot though

**Comment by flomotlik** [comment] 2016-10-12 13:52
@joh-mue Sorry yeah you're completely right, my bad. This is something in the framework. Which version of Serverless are you using? And is it installed globally or locally? (lg aus Wien übrigens)

**Comment by joh-mue** [comment] 2016-10-12 13:54
@flomotlik v1.0.0-rc2 and v1.0.0 installed globally
(👋)

**Comment by pas256** [comment] 2016-11-01 05:31
Are we reopening this bug or is there a new one?

**Comment by flomotlik** [comment] 2016-11-01 08:43
@pas256 good poing, forgot to reopen

**Comment by pas256** [comment] 2016-11-01 15:43
Thanks. With a bit of luck, it's a quick fix. Please let me know if you need help reproducing

**Comment by flomotlik** [comment] 2016-11-05 13:33
@pas256 @joh-mue can you guys provide more details how you can trigger this? I've tried and couldn't reproduce with a small test service and invoking the function. Could you provide a sample serverless.yml and event.json file you've used. I'm closing for now until we can reproduce.

**Comment by joh-mue** [comment] 2016-11-08 10:18
@flomotlik feel free to look at my test code at [github.com/joh-mue/aws-lambda-benchmark-py/blob/master/handler.py](https://github.com/joh-mue/aws-lambda-benchmark-py/blob)

**Comment by flomotlik** [comment] 2016-11-08 10:38
@joh-mue is this private? Gettting a 404

**Comment by joh-mue** [comment] 2016-11-08 10:41
it is not. I messed up the link. Should be corrected now. Either way:
https://github.com/joh-mue/aws-lambda-benchmark-py

**Comment by sbv-csis** [comment] 2016-11-09 09:20
I'm seeing this as well. Seems to be around the log format coming out for python logging

**Comment by svrist** [comment] 2016-11-09 21:27
I see it when I run `serverless logs -f ...` (version 1.1.0)

``` 
...
Deprecation warning: value provided is not in a recognized ISO format. moment construction falls back to js Date(), which is not reliable across all browsers and versions. Non ISO date formats are discouraged and will be removed in an upcoming major release. Please refer to http://momentjs.com/guides/#/warnings/js-date/ for more info.
Arguments: 
[0] _isAMomentObject: true, _isUTC: false, _useUTC: false, _l: undefined, _i: [INFO], _f: undefined, _strict: undefined, _locale: [object Object]
Error
    at Function.createFromInputFallback (/usr/lib/node_modules/serverless/node_modules/moment/moment.js:309:98)
    at configFromString (/usr/lib/node_modules/serverless/node_modules/moment/moment.js:2048:32)
    at configFromInput (/usr/lib/node_modules/serverless/node_modules/moment/moment.js:2408:13)
    at prepareConfig (/usr/lib/node_modules/serverless/node_modules/moment/moment.js:2391:13)
    at createFromConfig (/usr/lib/node_modules/serverless/node_modules/moment/moment.js:2358:44)
    at createLocalOrUTC (/usr/lib/node_modules/serverless/node_modules/moment/moment.js:2445:16)
    at local__createLocal (/usr/lib/node_modules/serverless/node_modules/moment/moment.js:2449:16)
    at utils_hooks__hooks (/usr/lib/node_modules/serverless/node_modules/moment/moment.js:16:29)
    at formatLambdaLogEvent (/usr/lib/node_modules/serverless/lib/plugins/aws/logs/index.js:94:32)
    at results.events.forEach.e (/usr/lib/node_modules/serverless/lib/plugins/aws/logs/index.js:130:34)
    at Array.forEach (native)
    at provider.request.then.results (/usr/lib/node_modules/serverless/lib/plugins/aws/logs/index.js:129:26)
    at tryCatcher (/usr/lib/node_modules/serverless/node_modules/bluebird/js/release/util.js:16:23)
    at Promise._settlePromiseFromHandler (/usr/lib/node_modules/serverless/node_modules/bluebird/js/release/promise.js:510:31)
    at Promise._settlePromise (/usr/lib/node_modules/serverless/node_modules/bluebird/js/release/promise.js:567:18)
    at Promise._settlePromise0 (/usr/lib/node_modules/serverless/node_modules/bluebird/js/release/promise.js:612:10)
Invalid date	2016-11-08T12:55:46.751Z		.env file /.env does not exist, not loading.
Invalid date	2016-11-08T12:55:46.751Z		.env file /var/.env does not exist, not loading.
...
``` 

The default logger format given by the lambda environment is:
```
[%(levelname)s]\t%(asctime)s.%(msecs)dZ\t%(aws_request_id)s\t%(message)s\n
```
with a asctime format like: 
```
%Y-%m-%dT%H:%M:%S
```

So, by looking where the error comes from I can see what the format should be:

(in my handler.py)
```
import logging
logger = logging.getLogger()                                                      
FORMAT = (                                                                        
    '%(asctime)s.%(msecs)3d (Z)\t%(aws_request_id)s\t'                            
    '[%(levelname)s]\t%(message)s\n'                                              
)                                                                                 
datefmt = '%Y-%m-%d %H:%M:%S'                                                     
for hand in [h for h in logger.handlers]:                                         
    hand.setFormatter(logging.Formatter(FORMAT, datefmt=datefmt))    
``` 
I get no more  errors

**Comment by Deamoner** [comment] 2017-03-27 19:17
I had this happening in node whenever I log via console.log during certain calls.  

Any idea how I fix this in node?

**Comment by Deamoner** [comment] 2017-03-27 19:39
FYI I only get this locally invoking "serverless invoke -f hello -l" but when I run it from the aws console I do not get an error and everything works.

**Comment by pmuens** [comment] 2017-03-28 07:30
Hmm. Yes, we're using `moment` in `serverless invoke` to show the logs one receives after invoking a function.

Thanks for reporting @Deamoner 👍 

Reopening...

**Comment by daroot** [comment] 2017-05-18 22:49
I just ran into this one and spent a few hours investigating.

Ultimately the problem stems from the default logging config for Python in lambda.

```
[INFO]  2017-05-18T22:25:24.742Z        e2f2211e-3c18-11e7-8fd4-e5bc5ba8fe25    {'message': 'Processed'}
```

Unlike the node console.log shim, this adds an additional level to the front of the log format.   That in turn messes up the logic in `aws/{invoke,logs}/index.js:formatLambdaLogEvent`.   Both of those automatically assume the first field (`splitted[0]`) must be the date like node's console output, and thus try to format the [INFO] string as a Date.  
```js
     if (splitted.length < 3 || new Date(splitted[0]) === 'Invalid Date') {
       return msg;
     }
```
This fails, but the second bug is that it's comparing the resulting Date object to "Invalid Date" using the identity `===`, which is false, rather than using equality `==` which would be true.   Due to this bug, rather than returning the raw msg as intended, it continues on into the next block, where it assumes the Date object is valid, and then calls moment on it.  Which then produces the moment warning and backtrace.

The first and easy fix is to correct the quality/identity comparison, which would eliminate the moment backtrace and warning.

The second fix for properly colorizing Python logging output is a bit harder, and requires checking if either the first or second field is a date, and then correctly ordering the other fields.

**Comment by pmuens** [comment] 2017-05-19 07:53
Thanks for investigating @daroot 👍 

Would you be so kind and submit a PR to fix this? We could work collaboratively on this if you face any problems / issues!

**Comment by daroot** [comment] 2017-05-19 20:13
@pmuens Done.   Got a little carried away, though I'm not exactly an expert with chai or even node, but I think this should fix most of the Invalid Date related errors.

**Comment by pmuens** [comment] 2017-05-20 07:12
Awesome @daroot 👍

We'll look into your PR ASAP.

**Closed** 2017-05-25 09:30 UTC
Labels: kind/refactoring, status/help-wanted
