### ISSUE TITLE
Custom authorizer - Does not get triggered

### ISSUE THREAD

**Issue by sajeetharan** [serverless/serverless#3828] opened 2017-06-22 05:44 UTC
I am  using a custom authorize lambda function with Node to authenticate the apis, after deploying i can manually test authorize function and it logs the errors in cloud watch. But when i request the same api through postman, it does not log anything on the cloud watch. It always returns the error 401 unauthorized.

Here is the code:

```
functions:
 testAuthorize:
    handler: handler.testAuthorize
accountFunctions:
    handler: handler.accountFunctions
    events:
      - http:
            path: account/testApi
            method : get
            authorizer: testAuthorize
```

**Comment by pmuens** [comment] 2017-06-22 06:36
Thanks for opening @sajeetharan 👍 

What headers are you sending? How does the request look like?

**Comment by sajeetharan** [comment] 2017-06-22 06:44
@pmuens 

These are the headers in the request

> { type: 'TOKEN',
>   authorizationToken: 'EAAGHdoRnp1YBAKmOUzApmEfiH3TUbBksdPOkEZBfj2Gb9gf1lbSFyBl8Op71xtDXQKM05dnbgzEkaEOH4jIuKQPZBZBaprNTjePU6t2hSDu4ligAkDPqYzXZC5K4uXf9nxnEEnxphIG6yfKrM5uZBtyxfUhGst5IZBZCmjukvWIeT7i7CjCISRu9Uz0rcbsZD',
>   methodArn: 'arn:aws:......:random-account-id:random-api-id/dev/GET/account/testApi' }

and the request is 

https://ouuhhj.execute-api.eu-central-1.amazonaws.com/dev/account/testApi?id=d3b700f-66f-4abf-944d-d79f562390b1

**Comment by HyperBrain** [comment] 2017-06-22 08:30
This sounds more like your authorizer does not return a valid principal. The 401 is emitted as soon as the authorizer's result is explicitly forbidden or wrong.

You can see in the docs at http://docs.aws.amazon.com/apigateway/latest/developerguide/use-custom-authorizer.html#api-gateway-custom-authorizer-output how the JSON returned from the authorizer has to be formatted (note the Resource in the statement that has to match the requested one at least). The context is optional and will be transferred to the endpoint lambda as is:

```
{
  "principalId": "yyyyyyyy", // The principal user identification associated with the token sent by the client.
  "policyDocument": {
    "Version": "2012-10-17",
    "Statement": [
      {
        "Action": "execute-api:Invoke",
        "Effect": "Allow|Deny",
        "Resource": "arn:aws:execute-api:<regionId>:<accountId>:<appId>/<stage>/<httpVerb>/[<resource>/<httpVerb>/[...]]"
      }
    ]
  },
  "context": {
    "stringKey": "value",
    "numberKey": "1",
    "booleanKey": "true"
  }
}
```

My [alias plugin example project](https://github.com/HyperBrain/serverless-aws-alias-example) contains a working/simple one in the _authorizer_ branch (I think the authorizer is named testauth there).

**Comment by sajeetharan** [comment] 2017-06-22 08:44
@HyperBrain  where should i modify this ?

**Comment by HyperBrain** [comment] 2017-06-22 08:53
The authorizer lambda (your _testAuthorize_ handler) has to return a JSON as above. The input event of the lambda looks like this:
```
{
    "type":"TOKEN",
    "authorizationToken":"<caller-supplied-token>",
    "methodArn":"arn:aws:execute-api:<regionId>:<accountId>:<apiId>/<stage>/<method>/<resourcePath>"
}
```

In your handler it should be:
```
function testAuthorizer(event, context, cb) {
  // event contains the incoming token, type and the arn
  // Do something that creates the result object
  cb(null, result);
}
```

**Comment by sajeetharan** [comment] 2017-06-22 09:01
@HyperBrain  yes thats how it is right now,

module.exports.testAuthorizer = (event, context, callback) => {
    var token = event.authorizationToken;
    var aws = require('amazon-cognito-identity-js');
    AWS.config.region = commonServices.AWS_CONFIG.REGION; //'eu-central-1';
    AWS.config.credentials = new AWS.CognitoIdentityCredentials({
      IdentityPoolId: commonServices.AWS_CONFIG.IDENTITY_POOL_ID, 
      Logins: {
        'graph.facebook.com': token
      }
    });
     AWS.config.credentials.refresh(function (error) {
      if (error) {
        console.log(error);
        callback("Unauthorized");
      } else if (AWS.config.credentials.identityId) {
         callback(null, generatePolicy('user', 'Allow', event.methodArn, AWS.config.credentials.identityId));
      } else {
        callback("Missing authentication ID");
      }
    });
  };

**Comment by HyperBrain** [comment] 2017-06-22 09:21
Now I understand what you try to achieve here.
I think the problem that you have here, is that you rely on the custom authorizer to set the global AWS credentials from an authorizer. The authorizer is a separate lambda function, so you cannot set any globals here and rely on them to be present in your other lambdas.

If you use Cognito, you normally should do the credential generation on the client with AWS and use AWS_IAM authorization on your other lambdas with the client credentials (AWS session credentials). In that case you will not need any custom authorizer. In my opinion the problem is an architectural problem - not an issue in the Serverless framework itself.

If you just want to map a given FB token to allowed/forbidden, to create new Cognito Ids, you can use AWS.CognitoIdentity.getId() and return the cognito id as principal. But that would be no access control at all.

BTW: amazon-cognito-identity-js is for accessing user pools (and is missing . To use Cognito Identity you should use the aws-sdk.

**Comment by sajeetharan** [comment] 2017-06-22 09:23
@HyperBrain  Thanks for the update, it was working well before few day!  one more question, is there a way to fix this?

**Comment by pmuens** [comment] 2017-06-22 12:53
Nice! Thanks for jumping in @HyperBrain 👍 

Does this (:top:) resolve your problem @sajeetharan ?

**Comment by sajeetharan** [comment] 2017-06-22 17:08
@pmuens  It did not resolve my issue, still in the same state

**Comment by sajeetharan** [comment] 2017-06-23 07:32
Sorry guys, i had to add the custom headers in the cloud front distribution to get it worked . thanks @HyperBrain  and  @pmuens  cheers!

**Closed** 2017-06-23 07:32 UTC
Labels: kind/bug, status/more-info-needed

**Comment by pmuens** [comment] 2017-06-23 14:01
> Sorry guys, i had to add the custom headers in the cloud front distribution to get it worked . thanks @HyperBrain and @pmuens cheers!

Great! Thanks for adding a comment you you were able to resolve it! Glad to hear that it's working for you now.

**Comment by jonathanlarav** [comment] 2019-02-20 00:21
@sajeetharan which custom headers?

**Comment by jonathanlarav** [comment] 2019-02-20 00:50
Nvm, I realize that cloudfront needs the Authorization header whitelisted in order to forward it to api gateway.
