### ISSUE TITLE
authorizer: aws_iam doesn't work

### ISSUE THREAD

**Issue by rogemita** [serverless/serverless#3623] opened 2017-05-15 15:46 UTC
## Description

authorizer: aws_iam config into serverless.yml doesn't work.

* What did you expect should have happened?
It should set up Authorization = AWS_IAM into the api gateway's resource.
* What was the config you used?
That one mentioned here in doc: https://serverless.com/framework/docs/providers/aws/events/apigateway#http-endpoints-with-aws_iam-authorizers
```
functions:
  hello:
    handler: handler.hello
    events:
      - http:
          path: ''
          method: get
          authorizer: aws_iam
```
* What stacktrace or error message from your provider did you see?
```
Serverless: Packaging service...

  Serverless Error ---------------------------------------

     Function "aws_iam" doesn't exist in this Service

  Get Support --------------------------------------------
     Docs:          docs.serverless.com
     Bugs:          github.com/serverless/serverless/issues
     Forums:        forum.serverless.com
     Chat:          gitter.im/serverless/serverless

  Your Environment Information -----------------------------
     OS:                 darwin
     Node Version:       4.4.3
     Serverless Version: 1.13.0
```

**Comment by pmuens** [comment] 2017-05-15 16:07
Hey @rogemita thanks for opening! 👍 

Closing since it's a duplicate of #3619 

The gist is that we've not release 1.14 yet (see: https://github.com/serverless/serverless/issues/3619#issuecomment-301453308)

**Closed by pmuens** 2017-05-15 16:07 UTC

**Comment by AnandSoniMize** [comment] 2018-01-10 07:14
Here is the sol for above issue. Hope that useful 
https://forum.serverless.com/t/solved-api-gateway-how-to-set-authorization-in-method-request-to-aws-iam/175
