### ISSUE TITLE
S3 Event Compile Fails If Event Is Declared In Function And in Resources

### ISSUE THREAD

**Issue by davidwilcox** [serverless/serverless#2967] opened 2016-12-16 20:48 UTC
Very probably related to https://github.com/serverless/serverless/issues/1823 (but that one was closed).

# This is a Bug Report

## Description

If I declare an s3 bucket as an event inside of a function (attached to that function), as well as declare it in the resources section, I get an error saying that <bucket-name> already exists in stack.

For bug reports:
* What went wrong?
If I declare an s3 bucket as an event inside of a function (attached to that function), as well as declare it in the resources section, I get an error saying that <bucket-name> already exists in stack.

* What did you expect should have happened?
I would've expected that it would've found the same logical bucket and not tried to create the bucket twice.
* What was the config you used?

```
functions:
  first:
      handler: handler.first
      events:
        - s3: mybucket

resources:
  Resources:
    newCoolResource:
      Type: AWS::S3::Bucket
      Properties:
        BucketName: mybucket
```

* What stacktrace or error message from your provider did you see?

``` 
  Serverless Error ---------------------------------------
 
     An error occurred while provisioning your stack: S3BucketDawilcoxawesomeaxcadfasdf
     - dawilcox-awesome-axcadfasdf already exists in stack
     arn:aws:cloudformation:us-east-1:272016194640:stack/aws-nodejs-dev/3af04030-a527-11e6-ac5e-50d5ca632682.
 
  Get Support --------------------------------------------
     Docs:          docs.serverless.com
     Bugs:          github.com/serverless/serverless/issues
 
  Your Environment Information -----------------------------
     OS:                 darwin
     Node Version:       6.2.1
     Serverless Version: 1.4.0
```

For feature proposals:
* What is the use case that should be solved. The more detail you describe this in the easier it is to understand for us.

I want to have a way to have the entire service own the bucket (as the bucket is used by multiple functions). Then, I want one of the functions to be triggered by the bucket (but not own it).

* If there is additional config how would it look
N/A

Similar or dependent issues:
* #1823

## Additional Data

* ***Serverless Framework Version you're using***:
1.4.0
* ***Operating System***:
Mac
* ***Stack Trace***:
Shown above.
* ***Provider Error messages***:
Shown Above.

**Comment by davidwilcox** [comment] 2016-12-16 21:29
I should note that it's even worse than the writeup... If you create a service first having an S3 bucket as a resource. Then, if you want that S3 bucket to be an event to a function, serverless already thinks it's exclusively owned by the resources section. It's very hard to get it onto the events section. You have to delete the resource, then readd it later. This may not be feasible if the resource has data that you need to keep.

**Comment by eahefnawy** [comment] 2016-12-19 12:21
@davidwilcox imo it would be pretty hacky to filter thorugh for all your custom resources and check if you're referencing the same bucket.

You can do one of two things:

1. You can create the event source mapping yourself completely and not declare an S3 event in the function config. If you do that you'll need to provide ALL the required properties.

2. OR, you can overwrite the CF template generated by Serverless for the S3 event. You do that by using the same logicalID of the S3 event [with the help of this logical ID guide](https://serverless.com/framework/docs/providers/aws/guide/resources/#aws-cloudformation-resource-reference). If you do that you don't need to provide all the properties, but only what you want to overwrite. The framework will just merge your changes.

For both of these cases, you can find all the info you need in the generated CF template in `.serverless` directory.

Out of curiosity though, why are you declaring the bucket as custom resources? It already gets created for you

Thanks for using Serverless 🙌

**Comment by davidwilcox** [comment] 2016-12-19 14:46
@eahefnawy 

The problem is that I'm "evolving" a service. Particularly, what I'm doing is I'm showing some other people how serverless works. The first thing we're doing is we create an S3 bucket to put files into. At that point, the S3 bucket in the resources section makes the most sense.

After we have that done, I want to hook up a function to be triggered when that is done.

The problem with your response is that it assumes that everyone is going to have their serverless.yml the right way the first time they *ever* hit deploy. That's just not reasonable (to me). People are going to want to make modifications to serverless.yml. One modification that they might want to do is they say (Oh! I have this S3 Bucket! Let's trigger on it now!). There's absolutely no way to evolve your service to do this without doing some awful hack on the client side by modifying the .serverless directory.

If modifying the .serverless directory is the vision of normal workflow, then I guess I can show 200 people how to do it in a 30 minute lab. That in itself seems pretty "hacky", though.

**Comment by eahefnawy** [comment] 2016-12-19 17:39
@davidwilcox yep I totally understand your concern. It is mainly due to the fact that you can only have S3 events **for newly created buckets** (buckets that the framework will create for you), not existing bucket. This is a CloudFormation limitation though, because the event source mapping is not a separate resource like other events, but rather just a property in the S3 resource template. So a bucket has to be created from scratch.

I should note that we're currently investigating supporting AWS SAM under the hood, which might kill that limitation, but that's not yet confirmed.

**Comment by getshort** [comment] 2016-12-19 17:46
hey so I think i might be able to help with this see . I was the one that started that serverless commit yesterday and then right after doing it the whole idea weirded me out because i dont know much about this stuff but i really want to learn. so i dissabled it right after basically from being able to accecc through my gmail acount do you think that mighf have anything to do with it?
________________________________

**Comment by mfrankwork** [comment] 2017-01-13 19:30
@davidwilcox I followed the first recommendation from @eahefnawy to resolve the same issue.  The answer is not to define an S3 event with the function...since serverless attempts to create a new S3 bucket...but to manually define the _NotificationConfiguration_ in the S3 bucket resource, as well as a corresponding Lambda permission resource. (This solution relies on the [CloudFormation naming convention used by serverless](https://serverless.com/framework/docs/providers/aws/guide/resources#aws-cloudformation-resource-reference) for Lambda functions.) In your case, it would look something like:

```yaml
functions:
  foo:
    handler: handler.foo

resources:
  Resources:
    newCoolResource:
      DependsOn:
        - FirstLambdaFunction
      Type: AWS::S3::Bucket
      Properties:
        BucketName: mybucket
        NotificationConfiguration:
          LambdaConfigurations:
            - Event: "s3:ObjectCreated:*"
              Function:
                "Fn::GetAtt": [ FirstLambdaFunction, Arn ]
    FirstLambdaPermissionMyBucketS3:
      DependsOn:
        - FirstLambdaFunction
      Type: AWS::Lambda::Permission
      Properties:
        FunctionName:
          "Fn::GetAtt": [ FirstLambdaFunction, Arn ]
        Action: "lambda:InvokeFunction"
        Principal: "s3.amazonaws.com"
        SourceArn: "arn:aws:s3:::mybucket"
```

**Comment by klebermagno** [comment] 2017-02-01 15:02
@mfrankwork I try do this but don't work for me.
SLS say "Template error: instance of Fn::GetAtt references undefined
     resource FirstLambdaFunction"
I don't understood how they associate the function with the event.

 
`functions:
  stored: 
      handler: com.hexagonagriculture.handler.AckUploadedTiFileHandler

resources:
  Resources:
    newCoolResource:
      DependsOn:
        - FirstLambdaPermissionMyBucketS3
      Type: AWS::S3::Bucket
      Properties:
        BucketName: mybucket
        NotificationConfiguration:
          LambdaConfigurations:
            - Event: "s3:ObjectCreated:*"
              Function:
                "Fn::GetAtt": [ FirstLambdaFunction, Arn ]
    FirstLambdaPermissionMyBucketS3:
      DependsOn:
        - FirstLambdaFunction
      Type: AWS::Lambda::Permission
      Properties:
        FunctionName:
          "Fn::GetAtt": [ FirstLambdaFunction, Arn ]
        Action: "lambda:InvokeFunction"
        Principal: "s3.amazonaws.com"
        SourceArn: "arn:aws:s3:::mybucket"
 `

**Comment by mfrankwork** [comment] 2017-02-03 14:35
The [normalized name](https://serverless.com/framework/docs/providers/aws/guide/resources/#aws-cloudformation-resource-reference) that serverless generates for your Lambda function follows this convention:
  `{normalizedFunctionName}LambdaFunction`
In your case, the Lambda function name should be `StoredLambdaFunction`, not `FirstLambdaFunction`.

The `AWS::Lambda::Permission` resource should also be renamed to `StoredLambdaPermissionMybucketS3` instead of `FirstLambdaPermissionMyBucketS3`.  It's supposed to use this convention:
  `{normalizedFunctionName}LambdaPermission{normalizedBucketName}S3`

**Comment by bdruth** [comment] 2017-02-10 15:35
So - just wanted to chime in on this issue. I believe #2732 ultimately introduced a regression in that configurations that worked in serverless < 1.2, stopped working. Specifically, configurations that used a logical name for the S3 bucket defined as event sources for functions, and specifically named in the ``Resources:`` using ``S3Bucket{normalizedBucketName}.Properties.BucketName``. The ``SourceArn`` on the permission now references the logical name, not the actual name.

Example:

```yaml
functions:
  myFunction:
    events:
      - s3:
          bucket: mylogicalbucket
[...]
resources:
  S3BucketMylogicalbucket:
    Properties:
      BucketName: ${self:custom.vars.bucketIn}
```
Results in the following CF snippet:
```javascript
    "MyFunctionLambdaPermissionMylogicalbucketS3": {
      "Type": "AWS::Lambda::Permission",
      "Properties": {
        "FunctionName": {
          "Fn::GetAtt": [
            "MyFunctionLambdaFunction",
            "Arn"
          ]
        },
        "Action": "lambda:InvokeFunction",
        "Principal": "s3.amazonaws.com",
        "SourceArn": {
          "Fn::Join": [
            "",
            [
              "arn:aws:s3:::mylogicalbucket"
            ]
          ]
        }
      }
    },
```
Instead of using ``Fn::Join`` for the ``SourceArn``, can't we just use ``Fn::GetAtt`` of ``S3BucketMylogicalbucket``? Everything else seems to line up correctly, I'm just not understanding why we're composing the ``SourceArn`` manually here.

**Comment by bdruth** [comment] 2017-02-10 16:13
It turns out that the reason this is using a hard-coded string is because of circular dependencies. I _think_ the only solution is to have *everything* that can be configured on an S3 bucket be configurable when defining the event source - like CORS - instead of needing to merge additional configuration in later.

**Comment by obezuk** [comment] 2017-03-13 05:33
I'm affected by this issue as well. My use case requires creating a bucket with specific CORS, Versioning and BucketPolicy configuration.

From what I can gather it's not possible to perform this configuration within the Function/Event/S3.

How can I help provide more information to resolve this issue?

**Comment by pmuens** [comment] 2017-03-13 06:59
@obezuk how does your `serverless.yml` and your `handler(s)` look like?

**Comment by obezuk** [comment] 2017-03-13 07:48
@pmuens Here is a gist of the two files I'm trying.

https://gist.github.com/obezuk/c3807f145f309b80607510c5145ee5fe

**Comment by pmuens** [comment] 2017-03-13 13:01
Thanks for sharing the files @obezuk 👍 

I think the problem is that you're trying to access the `resources` with the help of the variable system (which AFAIK is not possible). Can you run `serverless deploy --noDeploy` and inspect the generated CloudFormation template in the services `.serverless` directory to see if the variable system has replaced the placeholders?

**Comment by obezuk** [comment] 2017-03-14 10:30
Hi @pmuens,

From what I can see the variable system is replacing the resource names as I intended, it's just attempting to create a resource twice.

My use case is to create a bucket with CORS/BucketPolicy configuration to allow end-users to upload files for processing directly to a bucket.

https://gist.github.com/obezuk/cb8e7863366feeba8e60f0f1daec7b0c

Let me know how I can be of any further assistance.

````serverless deploy
Serverless: Packaging service...
Serverless: Uploading CloudFormation file to S3...
Serverless: Uploading service .zip file to S3 (5.45 MB)...
Serverless: Updating Stack...
Serverless: Checking Stack update progress...
....................................Serverless: Deployment failed!

  Serverless Error ---------------------------------------

     An error occurred while provisioning your stack: S3BucketApplicationuploadsstage
     - application-uploads-stage already exists in stack
     arn:aws:cloudformation:us-east-1:638204833713:stack/application-stage/b28d4020-07a1-11e7-bcb4-500c289032fe.

  Get Support --------------------------------------------
     Docs:          docs.serverless.com
     Bugs:          github.com/serverless/serverless/issues

  Your Environment Information -----------------------------
     OS:                 darwin
     Node Version:       7.6.0
     Serverless Version: 1.8.0

**Comment by pmuens** [comment] 2017-03-14 12:44
@obezuk ah shoot. Yes, I confused smth. yesterday...

🤔 @eahefnawy could you have a look? Seems to be related to: https://github.com/serverless/serverless/pull/2750#issuecomment-286171134

**Comment by pmuens** [comment] 2017-09-18 11:10
Closing this issue for now since we've pushed a couple of fixes for this in the meantime.

Feel free to comment / re-open if this issue is still around...

**Closed by pmuens** 2017-09-18 11:10 UTC
Labels: kind/bug, status/more-info-needed

**Comment by 4bakker** [comment] 2017-09-21 17:54
Could you point me to the "couple of fixes for this in the meantime." See a lot of discussion and PR but no fix for the event vs resource. Need to add CORS config on S3 bucket.

**Comment by pmuens** [comment] 2017-09-22 07:37
> Could you point me to the "couple of fixes for this in the meantime." See a lot of discussion and PR but no fix for the event vs resource. Need to add CORS config on S3 bucket.

Thanks for commenting @4bakker 👍. Could you share your `serverless.yml` real quick so that we can take a look at it and point in the right direction? Thanks in advance!

**Comment by akiskin** [comment] 2017-11-15 01:36
Hello everybody. The same issue here. In the CF template my bucket is declared twice - one from Resource section (with CORS stuff enabled), second - from s3 event added to function.
Any workarounds on this?

`service: pervichka-aws

provider:
  name: aws
  runtime: nodejs6.10
  environment:
    TEMP_FILES_TABLE: "temp-urls-${self:service}-${opt:stage, self:provider.stage}"
    TEMP_FILES_BUCKET: "temp-files-${self:service}-${opt:stage, self:provider.stage}"
    UPLOADED_FILES_TABLE: "uploaded-urls-${self:service}-${opt:stage, self:provider.stage}"
  iamRoleStatements:
    - Effect: Allow
      Action:
        - dynamodb:Query
        - dynamodb:Scan
        - dynamodb:GetItem
        - dynamodb:PutItem
      Resource: "*"
    - Effect: "Allow"
      Action:
        - s3:*
      Resource: "arn:aws:s3:::${self:provider.environment.TEMP_FILES_BUCKET}/*"
  stage: dev
  region: us-east-2



functions:
  hello:
    handler: handler.hello
    events: 
      - http: get hello
  prepare-new-file-url:
    handler: prepare-new-file-url.main
    events: 
      - http:  
          path: prepare-new-file-url
          method: get
          cors: true
  confirm-upload:
    handler: confirm-upload.main
    events: 
      - s3:
          bucket: ${self:provider.environment.TEMP_FILES_BUCKET}
          event: s3:ObjectCreated:*

# you can add CloudFormation resource templates here
#resources:
#  Resources:
#    NewResource:
#      Type: AWS::S3::Bucket
#      Properties:
#        BucketName: my-new-bucket
#  Outputs:
#     NewOutput:
#       Description: "Description for the output"
#       Value: "Some output value"
resources:
  Resources:
    TempUserFilesBucket:
      Type: AWS::S3::Bucket
      Properties:
        BucketName: ${self:provider.environment.TEMP_FILES_BUCKET}
        CorsConfiguration:
          CorsRules:
          - AllowedHeaders: ['*']
            AllowedMethods: [GET, PUT, HEAD, POST, DELETE]
            AllowedOrigins: ['*']   
      DeletionPolicy: Retain


    TempFilesDynamoDbTable:
      Type: AWS::DynamoDB::Table
      DeletionPolicy: Retain
      Properties:
        AttributeDefinitions:
          -
            AttributeName: "id"
            AttributeType: "S"   
        KeySchema:
          -
            AttributeName: "id"
            KeyType: "HASH"
        ProvisionedThroughput:
          ReadCapacityUnits: 1
          WriteCapacityUnits: 1
        StreamSpecification:
          StreamViewType: "NEW_AND_OLD_IMAGES"
        TableName: ${self:provider.environment.TEMP_FILES_TABLE}
    
    UploadedFilesDynamoDbTable:
      Type: AWS::DynamoDB::Table
      DeletionPolicy: Retain
      Properties:
        AttributeDefinitions:
          -
            AttributeName: "id"
            AttributeType: "S"   
        KeySchema:
          -
            AttributeName: "id"
            KeyType: "HASH"
        ProvisionedThroughput:
          ReadCapacityUnits: 1
          WriteCapacityUnits: 1
        StreamSpecification:
          StreamViewType: "NEW_AND_OLD_IMAGES"
        TableName: ${self:provider.environment.UPLOADED_FILES_TABLE}`

**Comment by harleyguru** [comment] 2018-07-10 20:53
@akiskin You don't have to declare the S3 bucket and Lambda Permission in resources section again since serverless will generate them based on your function S3 event configuration automatically.
If you just specify S3 event in functions section, serverless will do everything. 
This is very cool. But they didn't update their documentation regarding this.

**Comment by tommedema** [comment] 2018-08-14 19:54
Since function events dont work with custom buckets I followed people's advice to setup the `NotificationConfiguration` myself. However, I'm getting a cryptic error now:

`An error occurred: DiyBucket - Unable to validate the following destination configurations (Service: Amazon S3; Status Code: 400; Error Code: InvalidArgument; Request ID: 6516C03FC6506837; S3 Extended Request ID: RD1gHlYOOA+DRL7J8vg1MIf6xnPkDQ28p+lAkZOzgJijzalp/z6i1u1CaXUslLIzrmZ6Y4glYFE=).`

My complete Serverless.yml looks like [this](https://forum.serverless.com/t/add-additional-configuration-to-an-s3-bucket-with-a-dynamic-name/705/6?u=tommedema).
