### ISSUE TITLE
error in deploying individual function

### ISSUE THREAD

**Issue by keyurbhole** [serverless/serverless#9302] opened 2021-04-15 04:41 UTC
<details>
<summary><b><code> sls deploy function -f function1</code> output</b></summary>

```
  Error: ENOENT: no such file or directory, copyfile '/home/keyur/Desktop/SN/serverless/.webpack/function2.zip' -> '.serverless/function2.zip'

this is looking for another function that is not even mentioned in the command
```

</details>

<b>Installed version</b>

```
Serverless: Running "serverless" installed locally (in service node_modules)
Framework Core: 2.35.0 (local)
Plugin: 4.5.3
SDK: 4.2.2
Components: 3.8.3
```

**Comment by pgrzesik** [comment] 2021-04-15 07:16
Hello, this is a duplicate of https://github.com/serverless/serverless/issues/9252 which is itself an issue in `serverless-webpack`, not in the framework. I'm closing this one, please follow the corresponding issue in `serverless-webpack` repository. Also, for the future, please follow the issue template that is presented when you create a new one.

**Closed by pgrzesik** 2021-04-15 07:16 UTC
