### ISSUE TITLE
Config credentials doesn't work with SSM variables

### ISSUE THREAD

**Issue by umzegher** [serverless/serverless#4597] opened 2017-12-20 19:39 UTC
# This is a Bug Report

## Description

For bug reports:
* What went wrong? Config credentials fails when resolving SSM variables because the credentials are not available.
* What did you expect should have happened? Config credentials succeeds without error.
* What was the config you used?
```
service: test

provider:
  name: aws
  runtime: python3.6
  profile: test
  environment:
    variable2: ${ssm:test}

functions:
  hello:
    handler: handler.hello
```

* What stacktrace or error message from your provider did you see?
```
$ sls config credentials -p aws --profile=test --key=test --secret=test
 
  Error --------------------------------------------------
 
  Profile test does not exist
 
     For debugging logs, run again after setting the "SLS_DEBUG=*" environment variable.
 
  Get Support --------------------------------------------
     Docs:          docs.serverless.com
     Bugs:          github.com/serverless/serverless/issues
     Forums:        forum.serverless.com
     Chat:          gitter.im/serverless/serverless
 
  Your Environment Information -----------------------------
     OS:                     linux
     Node Version:           9.3.0
     Serverless Version:     1.25.0
```

Similar or dependent issues:
* #2041

## Additional Data

* ***Serverless Framework Version you're using***: 1.25.0
* ***Operating System***: Ubuntu 17.04
* ***Stack Trace***:
```
Error: Profile test does not exist
    at Object.addProfileCredentials (/usr/lib/node_modules/serverless/lib/plugins/aws/provider/awsProvider.js:85:15)
    at AwsProvider.getCredentials (/usr/lib/node_modules/serverless/lib/plugins/aws/provider/awsProvider.js:289:12)
    at AwsProvider.request (/usr/lib/node_modules/serverless/lib/plugins/aws/provider/awsProvider.js:198:30)
    at Variables.getValueFromSsm (/usr/lib/node_modules/serverless/lib/classes/Variables.js:402:6)
    at Variables.getValueFromSource (/usr/lib/node_modules/serverless/lib/classes/Variables.js:205:22)
    at property.match.forEach (/usr/lib/node_modules/serverless/lib/classes/Variables.js:120:29)
    at Array.forEach (<anonymous>)
    at Variables.populateProperty (/usr/lib/node_modules/serverless/lib/classes/Variables.js:111:41)
    at forEachLeaf (/usr/lib/node_modules/serverless/lib/classes/Variables.js:85:14)
    at forEachLeaf (/usr/lib/node_modules/serverless/lib/classes/Variables.js:75:14)
    at addContext (/usr/lib/node_modules/serverless/lib/classes/Variables.js:62:42)
    at /usr/lib/node_modules/serverless/node_modules/lodash/lodash.js:13379:38
    at /usr/lib/node_modules/serverless/node_modules/lodash/lodash.js:4944:15
    at baseForOwn (/usr/lib/node_modules/serverless/node_modules/lodash/lodash.js:3001:24)
    at Function.mapValues (/usr/lib/node_modules/serverless/node_modules/lodash/lodash.js:13378:7)
    at forEachLeaf (/usr/lib/node_modules/serverless/lib/classes/Variables.js:73:37)
    at addContext (/usr/lib/node_modules/serverless/lib/classes/Variables.js:62:42)
    at /usr/lib/node_modules/serverless/node_modules/lodash/lodash.js:13379:38
    at /usr/lib/node_modules/serverless/node_modules/lodash/lodash.js:4944:15
    at baseForOwn (/usr/lib/node_modules/serverless/node_modules/lodash/lodash.js:3001:24)
    at Function.mapValues (/usr/lib/node_modules/serverless/node_modules/lodash/lodash.js:13378:7)
    at forEachLeaf (/usr/lib/node_modules/serverless/lib/classes/Variables.js:73:37)
    at addContext (/usr/lib/node_modules/serverless/lib/classes/Variables.js:62:42)
    at /usr/lib/node_modules/serverless/node_modules/lodash/lodash.js:13379:38
    at /usr/lib/node_modules/serverless/node_modules/lodash/lodash.js:4944:15
    at baseForOwn (/usr/lib/node_modules/serverless/node_modules/lodash/lodash.js:3001:24)
    at Function.mapValues (/usr/lib/node_modules/serverless/node_modules/lodash/lodash.js:13378:7)
    at forEachLeaf (/usr/lib/node_modules/serverless/lib/classes/Variables.js:73:37)
    at Variables.populateObject (/usr/lib/node_modules/serverless/lib/classes/Variables.js:79:5)
    at Variables.populateService (/usr/lib/node_modules/serverless/lib/classes/Variables.js:47:17)
    at Serverless.run (/usr/lib/node_modules/serverless/lib/Serverless.js:89:27)
    at serverless.init.then (/usr/lib/node_modules/serverless/bin/serverless:42:50)
    at <anonymous>
From previous event:
    at runCallback (timers.js:773:18)
    at tryOnImmediate (timers.js:734:5)
    at processImmediate [as _immediateCallback] (timers.js:711:5)
From previous event:
    at __dirname (/usr/lib/node_modules/serverless/bin/serverless:28:46)
    at Object.<anonymous> (/usr/lib/node_modules/serverless/bin/serverless:46:4)
    at Module._compile (module.js:660:30)
    at Object.Module._extensions..js (module.js:671:10)
    at Module.load (module.js:573:32)
    at tryModuleLoad (module.js:513:12)
    at Function.Module._load (module.js:505:3)
    at Function.Module.runMain (module.js:701:10)
    at startup (bootstrap_node.js:194:16)
    at bootstrap_node.js:618:3
```

* ***Provider Error messages***:
`Profile test does not exist`

**Comment by HyperBrain** [comment] 2017-12-20 19:58
Hi @umzegher , thanks for the report.

Ok, that's a good point. The `config credentials` call should not do any variable resolutions at all. Not only `${ssm:}` references will fail in this case, but also `${cf:}` references as long as there are no credentials available.

@horike37 @erikerikson Do you have an idea how the best way would be to handle such cases, where the whole variable resolution should be skipped for specific commands, that set or modify the credentials themselves.
I might be not useful at all to trigger _any_ algorithms that rely on availability of the credentials then.

**Comment by erikerikson** [comment] 2017-12-21 02:19
The problem is that init both processes the command line and loads the service (implying many things such as variable resolution) before invoking the command.  It should be straightforward to add a flag to SLS commands, with a default value indicating "yes, load", that controls whether loading occurs for the given command.

**Comment by HyperBrain** [comment] 2017-12-22 09:23
@horike37 I agree with @erikerikson , that we should add an optional property to the command definitions. I remember you did a quick fix for the plugins plugin commands (the if), which also should be changed accordingly then, because it had the same issue.

**Comment by aliatsis** [comment] 2017-12-24 23:31
Is there any workaround for this that can use variables?

I'm trying to set the provider profile value with a variable like
`profile: ${self:custom.stages.${self:provider.stage}.profile}`
but packaging fails now since I am using `ssm:` as a variable source.

The only thing that gets package to pass, for instance, is to hardcode the value for `profile` to a particular stage's profile name

**Comment by erikerikson** [comment] 2017-12-25 03:52
You could use a variable list and supply an environment variable that you define so it resolves, functionally "disabling" the ssm variable.

Something like:
```
${env:DISABLE, ssm:parameter.var}
```

**Comment by deftomat** [comment] 2018-11-16 09:00
Any news? It is quite annoying that introducing the SSM broke the whole config. Especially things like
`profile: ${self:custom.stages.${self:provider.stage}.profile}`

**Comment by dschep** [comment] 2019-01-31 15:02
This should be fixed by #5744. Could you please verify by installing sls with `npm i -g serverless/serverless`

**Comment by umzegher** [comment] 2019-02-05 19:46
Nope, I'm still seeing the same error.

```
$ npm list -g serverless
/usr/lib
└── serverless@1.36.3  (github:serverless/serverless#3b9957f0725ac7ebf48d60e1c14d0cba096aa57c)

$ sls config credentials -p aws --profile=test --key=test --secret=test
 
  Error --------------------------------------------------
 
  Profile test does not exist
 
     For debugging logs, run again after setting the "SLS_DEBUG=*" environment variable.
 
  Get Support --------------------------------------------
     Docs:          docs.serverless.com
     Bugs:          github.com/serverless/serverless/issues
     Issues:        forum.serverless.com
 
  Your Environment Information -----------------------------
     OS:                     linux
     Node Version:           10.15.1
     Serverless Version:     1.36.3
```

**Comment by erikerikson** [comment] 2019-02-05 23:00
This fix was enabled by a change a bit back...  (#5298)

Looks like this config is the problem:
https://github.com/serverless/serverless/blob/3b9957f0725ac7ebf48d60e1c14d0cba096aa57c/lib/plugins/config/config.js#L24

`config` is not dependent on the configuration files, it just wants to set you up for CLI usage.  Quick PR to fix.

**Comment by erikerikson** [comment] 2019-02-05 23:01
@dschep 's commits let the profile attribute contain variables

**Comment by erikerikson** [comment] 2019-02-05 23:37
@umzegher can you try my branch?  I'm not certain it resolves your issue.

**Comment by erikerikson** [comment] 2019-02-06 00:20
NM @umzegher - I can confirm it doesn't.  That flag simply controls whether a check for valid serverless.* exists.  It does not currently control whether the file, if it exists, is loaded (though this may be sensible).

**Comment by erikerikson** [comment] 2019-02-06 00:32
This bug lives in the entangled concern space between `~/lib/Serverless.js`, `~/lib/classes/PluginManager.js`, and `~/lib/classes/Service.js`.  There needs to be the creation of an explicit contract between plugins and their requirements, with the framework offering to satisfy a subset of those as generally possible and appropriate but this is not the current factoring of the problem.

**Closed** 2019-02-07 10:21 UTC
Labels: bug, cat/variable

**Comment by kdybicz** [comment] 2020-06-24 10:23
I just upgrades SLS to 1.73.1 where this change was tagged and release, but I'm still having exactly same issue.
