### ISSUE TITLE
Cannot deploy different stage with Shared API Gateway

### ISSUE THREAD

**Issue by kyeljmd** [serverless/serverless#5347] opened 2018-10-02 10:40 UTC
This is my cloudformation script

`{  
   "AWSTemplateFormatVersion":"2010-09-09",
   "Description":"API",
   "Resources":{
      "APIGw":{  
         "Type":"AWS::ApiGateway::RestApi",
         "Properties":{  
            "Name":"API-GW"
         }
      }
   },
   "Outputs":{
      "ApiGwRestApiId":{  
         "Value":{  
            "Ref":"APIGw"
         },
         "Export":{  
            "Name":"apigw-restApiId"
         }
      },
      "eyesApiGwRestApiRootResourceId":{  
         "Value":{  
            "Fn::GetAtt":[  
               "APIGw",
               "RootResourceId"
            ]
         },
         "Export":{  
            "Name":"apigw-rootResourceId"
         }
      }
   }
}`

```
service: template-test-service

provider:
  name: aws
  runtime: python3.6
  region: eu-central-1
  stage: ${self:custom.environment.stage}
  environment:
    stage: ${self:custom.environment.stage}
  apiGateway:
    restApiId:
      'Fn::ImportValue': apigw-restApiId
    restApiRootResourceId:
      'Fn::ImportValue': apigw-rootResourceId

```

When I perform an sls deploy --stage dev this works however when I perform an sls deploy --stage prod it fails. with this error 

`Another resource with the same parent already has this name`

What is a way to work around this?

**Comment by mskutin** [comment] 2019-01-23 10:48
This is not a bug, each stage should have its own API Gateway, so you can reference restApiId and rootResourceId of each stage in your template. Consider the following example:

```yaml
service: master-api
provider:
  name: aws
custom:
  stage: ${opt:stage, self:provider.stage}
  region: ${opt:region, self:provider.region}
  prefix: ${self:service}-${self:custom.region}-${self:custom.stage}
resources:
  Resources:
    rootApiGateway:
      Type: AWS::ApiGateway::RestApi
      Properties:
        Name: ${self:custom.prefix}
  Outputs:
    rootApiGatewayId:
      Value:
        Ref: rootApiGateway
      Export:
        Name: ${self:custom.prefix}-restApiId
    rootApiGatewayResourceId:
      Value:
         Fn::GetAtt:
          - rootApiGateway
          - RootResourceId
      Export:
        Name: ${self:custom.prefix}-rootResourceId
```

```yaml
service: service-a
custom:
  stage: "${opt:stage, self:provider.stage}"
  region: ${opt:region, self:provider.region}
  prefix: ${self:service}-${self:custom.region}-${self:custom.stage}
  rootApiGatewayId: "master-api-${self:custom.region}-${self:custom.stage}-restApiId"
  rootApiGatewayResourceId: "master-api-${self:custom.region}-${self:custom.stage}-rootResourceId"
provider:
  name: aws
  apiGateway:
    restApiId:
      'Fn::ImportValue': ${self:custom.rootApiGatewayId}
    restApiRootResourceId:
      'Fn::ImportValue': ${self:custom.rootApiGatewayResourceId}
```

Once you deploy master-api stack for dev and for prod stages you will be able to use exported references across your AWS account.

**Comment by pmuens** [comment] 2019-02-06 11:54
Thanks for opening @kyeljmd 👍

This is not a bug as @mskutin correclty pointed out. Since @mskutin gave a nice explanation for a solution I'll close this issue for now. Feel free to continue the discussion! 👍

**Closed by pmuens** 2019-02-06 11:54 UTC
Labels: bug, cat/api-gw

**Comment by FabWild** [comment] 2019-09-26 08:00
It is possible to share a single api gateway between stages or projects, but as it creates a dependence between serverless projects, they just ignored that.
A hint is here:
https://forum.serverless.com/t/deploy-to-multiple-stages-with-shared-api-gateway/5356/2?u=dfweb
-> Put two stages and two deployments in the CLoudFront templates in the resources section of your serverless.yml. The api must have at least one method to be deployed.
