### ISSUE TITLE
My .zip file size is 45mb and unzipped size is 130mb on windows but it's showing the error of large file size on AWS

### ISSUE THREAD

**Issue by arslanalidev** [serverless/serverless#9417] opened 2021-05-03 07:08 UTC
I am using the serverless framework for the deployment. It's throwing the following error while we are deploying it on the AWS. But my file size is 45mb.

Serverless Error ----------------------------------------

An error occurred: SharedLambdaLayer - Unzipped size must be smaller than 262144000 bytes (Service: AWSLambdaInternal; Status Code: 400; Error Code: InvalidParameterValueException; Request ID: 27f9378e-b9ea-42c5-ad73-a3b7cf9d584c).

This is my environment
Operating System: win32
Node Version: 12.19.0
Framework Version: 2.35.0
Plugin Version: 4.5.3
SDK Version: 4.2.2
Components Version: 3.8.2

<details>
     <summary>
<pre>
<code> 
service: rxd-layers

frameworkVersion: '2'
useDotenv: true
unresolvedVariablesNotificationMode: error
configValidationMode: error

plugins:
  - serverless-plugin-git-variables
  - serverless-dotenv-plugin

custom:
  stageVariables:
    gitBranch: ${opt:stage, git:branch}

package:
  include:
    - /nodejs/node_modules/shared # no need to add this yourself, this plugin does it for you
  exclude:
    - /nodejs/node_modules/**
    - /nodejs/shared/**

provider:
  stage: ${opt:stage, git:branch}
  name: aws
  runtime: nodejs12.x
  region: ${env:AWS_REGION_CRED, 'us-east-1'}
  versionFunctions: true
  lambdaHashingVersion: 20201221

layers:
  shared:
    path: shared
    description: This layer is for node packages of all services

resources:
    Outputs:
      SharedLayerExport:
        Value:
          Ref: SharedLambdaLayer
        Export:
          Name: SharedLambdaLayer
</code>

</pre>

</summary>
</details>

<b>
Framework Core: 2.35.0
Plugin: 4.5.3
SDK: 4.2.2
Components: 3.8.2
</b>

**Comment by pgrzesik** [comment] 2021-05-03 07:31
Hello @arslanalidev - please follow the issue template that is visible when creating a new issue. As for the issue itself - looks like the layer that you're trying to use is too big after unzipping (there's a limit not only to size of ZIPped files, but also after unzipping them).

**Comment by arslanalidev** [comment] 2021-05-03 07:33
I had also checked it by unzip it. It was around 130mb with unzip file size.

**Comment by pgrzesik** [comment] 2021-05-03 07:38
Are you talking about the `zip` for your service or the lambda layer? Looks like the lambda layer artifact is too big

**Comment by arslanalidev** [comment] 2021-05-03 07:43
Yes, but lambda layer allow upto around 262mb but My size is 130mb.

**Comment by pgrzesik** [comment] 2021-05-03 08:54
@arslanalidev In this situation, could you please provide a reproducible example that I can execute on my side? Otherwise, it's going to be quite hard to try to replicate the problem you're experiencing

**Comment by rcldesign** [comment] 2021-05-05 03:45
I started having the exact same issue out of the blue today (granted, I hadn't tried to deploy the project for the last 3 days). I *literally* added ~4 lines of code to my project and ran in to this issue. I then deleted ~100 lines of code, and the issue persists. My entire project on disk is about ~160MB, so it's not possible for it to be >260MB when "unzipped". The generated .zip file is ~42MB.

Here are some things that I have tried that did not help:
1. Deploy to a different stage
2. Deploy to a different AWS account
3. Remove all dev libraries (I think serverless does this already)

What can I share to help with troubleshooting this issue? Seems like I'd need to share my whole project? Similar environment to the OP:

Your Environment Information ---------------------------
     Operating System:          win32
     Node Version:              12.19.0
     Framework Version:         2.39.2
     Plugin Version:            4.5.3
     SDK Version:               4.2.2
     Components Version:        3.9.1

**Comment by pgrzesik** [comment] 2021-05-06 07:23
Hello @rcldesign :wave: Did you upgrade any of the dependencies in the meantime? What version of `npm` are you using? Could you check if the dev dependencies are not included the generated zip artifact?

**Comment by rcldesign** [comment] 2021-05-06 17:09
Hi, @pgrzesik !

- I did not upgrade any dependencies, though as part of my troubleshooting, I had deleted all of node_modules and then re-installed them which *may* have upgraded some of them
- My npm version is 6.14.8 (I had experienced issues with npm 7.x more than a month ago, so I rolled back to 6.x at that time)
- dev dependencies are NOT included in the .zip artifact (when extracted, this .zip file is about 117MB)

Please advise on the next steps to troubleshoot.

**Comment by pgrzesik** [comment] 2021-05-06 17:25
Hello @rcldesign, thanks for the answers :bow: Do you think you could be able to prepare a reproducible example with a super simple config, but with all your dependencies in `package.json`? That would allow me to run it on my side and see if I can reproduce the same issue that you're having. Here's an example how that can look like - https://github.com/janpio/repro6644_3 - that's a reproducible example from https://github.com/serverless/serverless/issues/9340 issue. It would be really appreciated :bow:

**Comment by arslanalidev** [comment] 2021-05-10 10:52
@pgrzesik  this is the output of the deploy command.

**Comment by pgrzesik** [comment] 2021-05-10 10:58
@arslanalidev That does not answer the question of how big the zip that was uploaded - could you please send the full output, ideally with `SLS_DEBUG`, as in the issue template? Thanks in advance :bow:

**Comment by rcldesign** [comment] 2021-05-10 17:15
Hi @pgrzesik - as stated in my first comment, compressed size is about 42MB, and uncompressed is about 160MB. Here's the output with debugging on. I don't have any issue sharing access to the code base (there are no secrets in there); it is more important to solve this issue (or find a work around) as quickly as possible.

`> fitpet-backend@1.4.0 deploy-prod C:\Users\tophe\Documents\dev\fitpet-backend
> sls deploy --stage prod

Serverless: To ensure safe major version upgrades ensure "frameworkVersion" setting in service configuration (recommended setup: "frameworkVersion: ^2.39.2")

Serverless: Load command interactiveCli
Serverless: Load command config
Serverless: Load command config:credentials
Serverless: Load command config:tabcompletion
Serverless: Load command config:tabcompletion:install  
Serverless: Load command config:tabcompletion:uninstall
Serverless: Load command create
Serverless: Load command install
Serverless: Load command package
Serverless: Load command deploy
Serverless: Load command deploy:function
Serverless: Load command deploy:list
Serverless: Load command deploy:list:functions
Serverless: Load command invoke
Serverless: Load command invoke:local
Serverless: Load command info
Serverless: Load command logs
Serverless: Load command metrics
Serverless: Load command print
Serverless: Load command remove
Serverless: Load command rollback
Serverless: Load command rollback:function 
Serverless: Load command slstats
Serverless: Load command plugin
Serverless: Load command plugin
Serverless: Load command plugin:install    
Serverless: Load command plugin
Serverless: Load command plugin:uninstall  
Serverless: Load command plugin
Serverless: Load command plugin:list       
Serverless: Load command plugin
Serverless: Load command plugin:search     
Serverless: Load command config
Serverless: Load command config:credentials
Serverless: Load command upgrade  
Serverless: Load command uninstall
Serverless: Load command login
Serverless: Load command logout        
Serverless: Load command generate-event
Serverless: Load command test
Serverless: Load command dashboard     
Serverless: Load command output        
Serverless: Load command output:get
Serverless: Load command output:list
Serverless: Load command param
Serverless: Load command param:get
Serverless: Load command param:list
Serverless: Load command studio
Serverless: Skipping variables resolution with old resolver (new resolver reported no more variables to resolve)
Serverless: Deprecation warning: Support for "package.include" and "package.exclude" will be removed with next major release. Please use "package.patterns" instead
            More Info: https://www.serverless.com/framework/docs/deprecations/#NEW_PACKAGE_PATTERNS
Serverless: Deprecation warning: Starting with version 3.0.0, following property will be replaced:
              "provider.iamRoleStatements" -> "provider.iam.role.statements"
            More Info: https://www.serverless.com/framework/docs/deprecations/#PROVIDER_IAM_SETTINGS
Serverless: Invoke deploy
Serverless: Invoke package
Serverless: Invoke aws:common:validate
Serverless: Invoke aws:common:cleanupTempDir
Serverless: Packaging service...
Serverless: Excluding development dependencies...
Serverless: Invoke aws:package:finalize
Serverless: Invoke aws:common:moveArtifactsToPackage
Serverless: Invoke aws:common:validate
Serverless: Invoke aws:deploy:deploy
Serverless: Uploading CloudFormation file to S3...
Serverless: Uploading artifacts...
Serverless: Uploading service fit-pet.zip file to S3 (42.04 MB)...
Serverless: Validating template...
Serverless: Updating Stack...
Serverless: Checking Stack update progress...
.......................................
Serverless: Operation failed!
Serverless: View the full error output: https://us-west-2.console.aws.amazon.com/cloudformation/home?region=us-west-2#/stack/detail?stackId=arn%3Aaws%3Acloudformation%3Aus-west-2%3A670055954663%3Astack%2Ffit-pet-prod%2Fe479faa0-add5-11ea-82e8-0284c9f60df0

 Serverless Error ----------------------------------------

  ServerlessError: An error occurred: RouteCoachesLambdaFunction - Resource handler returned message: "Code uncompressed size is greater than max allowed size of 272629760. (Service: Lambda, Status Code: 400, Request ID: fb65d3e2-1552-4395-8609-e8978255770a, Extended Request ID: null)" (RequestToken: aee6f4f8-ee6e-aefb-22c9-1872efc1e97c, HandlerErrorCode: InvalidRequest).
      at C:\Users\tophe\AppData\Roaming\npm\node_modules\serverless\lib\plugins\aws\lib\monitorStack.js:94:23
      at processTicksAndRejections (internal/process/task_queues.js:97:5)
      at async AwsDeploy.update (C:\Users\tophe\AppData\Roaming\npm\node_modules\serverless\lib\plugins\aws\lib\updateStack.js:144:5)
  From previous event:
      at AwsDeploy.<anonymous> (C:\Users\tophe\AppData\Roaming\npm\node_modules\serverless\lib\plugins\aws\lib\updateStack.js:152:35)
  From previous event:
      at AwsDeploy.updateStack (C:\Users\tophe\AppData\Roaming\npm\node_modules\serverless\lib\plugins\aws\lib\updateStack.js:148:33)
  From previous event:
      at AwsDeploy.<anonymous> (C:\Users\tophe\AppData\Roaming\npm\node_modules\serverless\lib\plugins\aws\deploy\index.js:122:39)
      at processImmediate (internal/timers.js:461:21)
  From previous event:
      at Object.aws:deploy:deploy:updateStack [as hook] (C:\Users\tophe\AppData\Roaming\npm\node_modules\serverless\lib\plugins\aws\deploy\index.js:118:30)
      at PluginManager.invoke (C:\Users\tophe\AppData\Roaming\npm\node_modules\serverless\lib\classes\PluginManager.js:565:20)
      at async PluginManager.spawn (C:\Users\tophe\AppData\Roaming\npm\node_modules\serverless\lib\classes\PluginManager.js:587:5)

  Get Support --------------------------------------------
     Docs:          docs.serverless.com
     Bugs:          github.com/serverless/serverless/issues
     Issues:        forum.serverless.com

  Your Environment Information ---------------------------
     Operating System:          win32
     Node Version:              12.19.0
     Framework Version:         2.39.2
     Plugin Version:            4.5.3
     SDK Version:               4.2.2
     Components Version:        3.9.1`

**Comment by rcldesign** [comment] 2021-05-10 17:21
Not sure if it is relevant or not, but the update rollback fails every time as well, and I have to manually skip most of the resources to get the rollback to complete so that I can try to deploy again (see image). Also, just a reminder that I am also not able to deploy to entirely different AWS accounts either.

![image](https://user-images.githubusercontent.com/1377385/117699305-88d8c980-b179-11eb-9021-01fa32d417c8.png)

**Comment by rcldesign** [comment] 2021-05-13 17:57
Hi @pgrzesik - what are the next steps for troubleshooting this issue?

**Comment by FanFataL** [comment] 2021-05-13 19:23
@rcldesign I don't know if its helps but according to the documentation 250MB is a size for lambda code with the layers.

https://docs.aws.amazon.com/lambda/latest/dg/gettingstarted-limits.html
```250 MB (unzipped, including layers)```

**Comment by rcldesign** [comment] 2021-05-13 19:27
Thanks, @FanFataL - Zipped, my project is 42MB, unzipped it is 160MB -> well below the limit. Something else is causing the issue.

**Comment by FanFataL** [comment] 2021-05-13 19:29
Insted of zipping this on your own try use `sls package` to check what kind of code package / layer package has been prepared.
You can find this under the `.serverless` directory

**Comment by rcldesign** [comment] 2021-05-13 19:46
Hi @FanFataL, I did not create the package on my own. This is the package generated by serverless. It is 42 MB, and when unzipped, it is 160MB. From my log (above) you can see serverless report that the package is 42.04 MB.

**Comment by FanFataL** [comment] 2021-05-13 20:35
I have installed your node modules and made the package and the reslult after unpacking is 654M - on ubuntu.

Maybe your windows is showing wrong values. Or its a different file system

**Comment by pgrzesik** [comment] 2021-05-13 20:56
Hello @rcldesign - sorry for not responding sooner, I've had a pretty busy last few days. I've dug a bit deeper into the issue and tried to reproduce the problem on my side and while in fact, zipped version of the package has ~42M, it's over 340M after unzipping. Digging into the dependencies, the `geo-tz` dependency has size of 245M, so I believe it's the problematic dependency. You've mentioned that you might've upgraded the dependencies - could you try to see if the problem persists with the older version? Also, could you download the packaged artifact from S3 file and unzip it and check it's contents? I've tried reproducing it also on older version of the Framework (I've tested `2.30.0`, `2.20.0` and `2.10.0` and in all cases the size of unzipped package is the same, so it's probably not a bug introduced in recent versions of the Framework).

**Comment by rcldesign** [comment] 2021-05-13 22:43
Hi @pgrzesik and @FanFataL - thank you both for your suggestions. @FanFataL was right - Windows was showing an unzipped size of ~120MB, but when I unzipped on Ubuntu, it was like @pgrzesik saw - just over 340MB. I dropped the geo-tz library and I was able to deploy again without issue.

Interestingly, NPM shows that library as having an uncompressed size of 25MB, which is about what I observe in Windows. On Linux, I also observe the library to be 245MB. Crazy that there would be a 10x difference in file size between the two OSes. On the other hand, the library contains some (relatively) large .zip files of data that might be getting extracted and included in the file size somewhere.

**Comment by pgrzesik** [comment] 2021-05-14 08:57
Hey @rcldesign :wave: The behavior of that library is a bit surprising - according to their `package.json`, they have a `prepublish` script that will unzip the data stored in repo (24.8M of zipped data), but I'm not sure why that's not included on Windows.

@arslanalidev - are you by any chance, using `geo-tz` as well? Would you be able to share the list of dependencies used in your project?

**Comment by arslanalidev** [comment] 2021-05-14 17:16
Hi @pgrzesik, Yes I am also using the the `geo-tz` library in my project. Below is the dependencies in my project.
`{
  "name": "shared",
  "version": "1.0.0",
  "description": "All Node Packages for services",
  "main": "handler.js",
  "dependencies": {
    "amazon-cognito-identity-js": "^4.6.0",
    "axios": "^0.21.1",
    "config": "^3.3.3",
    "dotenv": "^8.2.0",
    "geo-tz": "^6.0.1",
    "http-status-codes": "^2.1.2",
    "joi": "^17.4.0",
    "jsonapi-serializer": "^3.6.5",
    "jsonschema": "^1.2.6",
    "jsonwebtoken": "^8.5.1",
    "jwk-to-pem": "^2.0.4",
    "jwt-decode": "^2.2.0",
    "lodash": "^4.17.21",
    "moment-timezone": "^0.5.33",
    "njwt": "^1.0.0",
    "random-words": "^1.1.1",
    "request": "^2.88.2",
    "uuid": "^8.3.2",
    "validate.js": "^0.13.1",
    "winston": "^3.3.3",
    "winston-aws-cloudwatch": "^3.0.0",
    "winston-cloudwatch": "^0.9.0"
  },
  "author": "Rashid",
  "license": "ISC"
}`

**Comment by pgrzesik** [comment] 2021-05-17 10:12
Thanks for sharing @arslanalidev - as said above - it looks like it's not a problem with the Framework itself but rather with the library `geo-tz`, which unzipped has size of 245M.

**Comment by arslanalidev** [comment] 2021-05-17 11:12
Yes, I had removed the `geo-tz` library. Instead of `geo-tz` now I am using `tz-lookup` library for this purpose.

**Comment by pgrzesik** [comment] 2021-05-17 11:53
Appreciate the update @arslanalidev - I'm going to close this one as it seems it's a problem with an external dependency and not the Framework itself. Thanks to everyone involved :bow:

**Closed by pgrzesik** 2021-05-17 11:53 UTC
Labels: question
