### ISSUE TITLE
Init Hook

### ISSUE THREAD

**Issue by Squareomatic** [serverless/serverless#3144] opened 2017-01-26 10:18 UTC
# This is a Bug Report / Question

## Description

For bug reports:
* What went wrong? 

**I create my infrastructure outside from serverless to have more flexibility (mainly because of the CF template size limitations). Using the scriptable plugin I download some files and save them in the project to reference those through serverless variables:**

```
scriptHooks:
    before:deploy:cleanup: scripts/discover.js
```

```
provider:
  name: aws
  runtime: nodejs4.3
  stage:  ${opt:stage, ${self:custom.stage}}
  region: ${opt:region, ${self:custom.region}}
  profile: ${self:custom.profiles.${self:provider.stage}}
  environment: ${file(./global-lambda-variables-${self:provider.stage}.yml):environment}
```

**thing is that I have always the outdated version of the variables and I have to deploy twice because the serverless.yml file has been already filled in when I get the actual files from remote.**

* What did you expect should have happened?

**The latest version of the serverless.yml object after the files were downloaded.**

* What was the config you used?
* What stacktrace or error message from your provider did you see? 

**no error**

For feature proposals:
* What is the use case that should be solved. The more detail you describe this in the easier it is to understand for us.

**Have a blocking hook that is always run before anything else to allow to download config info from remote and then returning a promise to tell serverless that the work has been done.**

**Is there already something similar?**

**thanks!**

## Additional Data

* ***Serverless Framework Version you're using***: 1.3
* ***Operating System***: mac os

**Comment by pmuens** [comment] 2017-01-26 10:26
Hmm 🤔 could you try to run the `discover.js` before actually running the Serverless CLI?

Something like `node scripts/discover.js && serverless deploy`. The problem is that Serverless plugins will be run after all the Variables are populated (see this file for the whole process: https://github.com/serverless/serverless/blob/master/lib/Serverless.js).

Furthermore it would be interesting if you could go into a little bit more details about the CloudFormation limitations you face. Is it because you reach the `Resources` limits or `Outputs` limits?

Serverless v1.6 will include some fixes to solve the `Outputs` limits.

**Comment by Squareomatic** [comment] 2017-01-26 10:39
@pmuens yes you are right! it is just a nice to have so I could do **sls deploy** and have all my things hooked to the serverless event, but I can actually create a wrapper to the serverless deploy that indeed download things before hand and then run sls deploy :D thanks, sometimes I just overthink on stuff ehehehe

Regarding the CF limitations, I have encountered that issue while I was using the standard LAMBDA type (not the PROXY) so I had to setup parameters for the methods and CORS for different statusses and the template has become huge really quickly. 

Since I use LAMBDA PROXY it has been far more easier to handle CORS setup, anyway I decided to move out from serverless CF style of managing the infrastructure mainly because I have seen that having everything outside makes easier to keep up to date with sls framework updates without breaking stuff so I use serverless to manage for me just API GATEWAY and LAMBDAS.

At the very end if there are breaking changes in the framework I can always put everything down, update the version e reput everything up in a matter of minutes, thing that I cannot do easily if I keep stateful stuff in the same CF stack of api gateway and lambdas.

@pmuens thanks for the help!

cheers,

R

**Comment by pmuens** [comment] 2017-01-26 11:32
Good to hear that the external script invoking resolved your issue!

Thanks for the detailed description how you separate CloudFormation / Infrastructure and Serverless Framework usage! 👍 

I'll close this issue since for now. Let us know if you need any help somewhere...

**Closed by pmuens** 2017-01-26 11:32 UTC
Labels: kind/question, status/more-info-needed
