### ISSUE TITLE
serverless 4 deploy after package does not work

### ISSUE THREAD

**Issue by zoli-kasa** [serverless/serverless#12931] opened 2024-11-29 14:15 UTC
### Issue description

i'm just trying to switch our repos to serverless 4. our cd pipeline uses
`serverless package --stage dev --package sls-package-output`
and
`serverless deploy --verbose --stage dev --package sls-package-output`
but this gives me an error, if `package.individually` is not set to true
```
✖ ServerlessError2: No xxxx.zip file found in the package path you provided.
    at file:///Users/xxxx/.serverless/releases/4.4.13/package/dist/sf-core.js:724:2729
```

### Context

Serverless ϟ Support

This generates a report from your last Serverless Framework command (including any errors) to use for Github Issues, debugging w/ AI, or creating a support ticket w/ Serverless Inc.

Summary Report -----------------

# Service Overview
- Serverless Framework Version: 4.4.13
- Service Path: /Users/xxx/xxxx
- Service Config File: serverless.yml
- Service Name: xxxx
- Service App: xxxx
- Service Runtime: nodejs20.x
- Service Stage: dev
- Service Region: us-west-2
- Error Code: MISSING_ARTIFACT_FILE

## Command
deploy --verbose true,--stage dev,--package sls-package-output

## Error Message
No device-service.zip file found in the package path you provided.

## Error Stacktrace
```
at file:///Users/xxx/.serverless/releases/4.4.13/package/dist/sf-core.js:724:2729
at Array.forEach (<anonymous>)
at AwsDeploy.extendedValidate (file:///Users/xxx/.serverless/releases/4.4.13/package/dist/sf-core.js:724:1767)
at before:deploy:deploy (file:///Users/xxx/.serverless/releases/4.4.13/package/dist/sf-core.js:738:4651)
at async PluginManager.runHooks (file:///Users/xxx/.serverless/releases/4.4.13/package/dist/sf-core.js:925:9311)
at async PluginManager.invoke (file:///Users/xxx/.serverless/releases/4.4.13/package/dist/sf-core.js:925:10023)
at async PluginManager.run (file:///Users/xxx/.serverless/releases/4.4.13/package/dist/sf-core.js:925:10813)
at async Serverless.run (file:///Users/xxx/.serverless/releases/4.4.13/package/dist/sf-core.js:932:10667)
at async runFramework (file:///Users/xxx/.serverless/releases/4.4.13/package/dist/sf-core.js:980:2770)
at async route (file:///Users/xxx/.serverless/releases/4.4.13/package/dist/sf-core.js:1010:14772)
at async Object.run2 [as run] (file:///Users/xxx/.serverless/releases/4.4.13/package/dist/sf-core.js:1010:15173)
at async run3 (file:///Users/xxx/.serverless/releases/4.4.13/package/dist/sf-core.js:1010:16435)
```

i can not share other parts of serverless.yml :(

**Comment by aidmax** [comment] 2024-12-02 10:39
+1 came across the same issue

**Comment by czubocha** [comment] 2024-12-02 11:32
Hey, this seems to be a duplicate of https://github.com/serverless/serverless/issues/12775. We’re looking into it.

**Closed by czubocha** 2024-12-02 11:32 UTC
