### ISSUE TITLE
Skip deployment only if previous deployment was successful

### ISSUE THREAD

**Issue by mthenw** [serverless/serverless#4030] opened 2017-08-02 21:29 UTC
# This is a Bug Report

## Description

* What went wrong?

`sls deploy` has a built-in mechanism for skipping deploys when files haven't changed. In most cases, it works well but in case of deployment failure the next `sls deploy` should always run the whole process even though files are not changed. That's because CF might not be fully applied.

* What did you expect should have happened?

`sls deploy` after failed deployment should always run full deployment process.

* What stacktrace or error message from your provider did you see?
`Serverless: Service files not changed. Skipping deployment...`

**Comment by pmuens** [comment] 2017-08-03 06:43
Thanks for opening @mthenw 👍

Yes, that's definitely an area for improvement (Fortunately one can force a deployment with the `--force` flag which is a workaround for now).

I'll close this for now since it's a duplicate of https://github.com/serverless/serverless/issues/3983.

**Closed by pmuens** 2017-08-03 06:43 UTC
Labels: kind/bug
