### ISSUE TITLE
Breaking change when using --noDeploy, it now requires valid aws credentials.

### ISSUE THREAD

**Issue by gertjvr** [serverless/serverless#2648] opened 2016-11-07 04:44 UTC
# This is a Bug Report 

## Description

Running `serverless deploy --noDeploy` throws error requiring valid aws credentials this wasn't required in previous version v1.0.3 or v1.0.2

```
 sls deploy -v "--noDeploy"


  Error --------------------------------------------------

     ServerlessError: ServerlessError: The security token
     included in the request is invalid.

     For debugging logs, run again after setting SLS_DEBUG env var.

  Get Support --------------------------------------------
     Docs:          docs.serverless.com
     Bugs:          github.com/serverless/serverless/issues

     Please report this error. We think it might be a bug.

  Your Environment Information -----------------------------
     OS:                 win32
     Node Version:       4.6.1
     Serverless Version: 1.1.0
```

## Additional Data

* ***Serverless Framework Version you're using***:
* ***Operating System***: Windows 10
* ***Stack Trace***: snippet above
* ***Provider Error messages***: ServerlessError: ServerlessError: The security token included in the request is invalid.

**Comment by laardee** [comment] 2016-11-07 06:57
I noticed that the `--noDeploy` switch requires internet connection. I started to working on the fix for that https://github.com/serverless/serverless/compare/master...laardee:deploy-offline , and it should fix also missing credentials issue, because after that fix no request is made to AWS when using the `--noDeploy switch`. @flomotlik, is there a reason why the request is made to AWS when using `--noDeploy`?

**Comment by rowanu** [comment] 2016-11-07 09:04
Just linking #2473 here - splitting build and deploy into distinct steps would fix this issue.

**Comment by laardee** [comment] 2016-11-07 09:44
I noticed the same discussion also, that's why I haven't push the development of my branch any further.

**Comment by gertjvr** [comment] 2016-11-07 09:51
That discussion has gone very quite, unsure which direction @flomotlik would like to go with it. I automated our serverless deployment packaging everything and running sls deploy. But there some big issues with consistently.

**Comment by flomotlik** [comment] 2016-11-07 10:25
I just checked and I got the same error in 1.0.3, but not 1.0.2. The problem is in this commit: https://github.com/serverless/serverless/commit/296810c8b3c27864222a0209d8dde7f8ea709a11

We need to return after writing to disk in case --noDeploy is set. And we need to add an integration test that makes sure this works. Added to bugs to fix.

**Comment by laardee** [comment] 2016-11-07 11:41
@flomotlik, I could do this, is the fix https://github.com/serverless/serverless/compare/master...laardee:deploy-offline that I already started to do something that I should continue with?

**Comment by flomotlik** [comment] 2016-11-07 11:51
@laardee yup that looks pretty reasonable. Could you open a PR with that so we can review. It would be great if we could add an integration test in the same repo, that makes sure this works without any credentials in place. Happy to help with that, we can discuss it in the PR.

**Comment by laardee** [comment] 2016-11-07 12:25
@flomotlik, here is the PR https://github.com/serverless/serverless/pull/2651

**Comment by pmuens** [comment] 2016-11-18 12:11
Just did a code review. @eahefnawy will look into it as well. Will be resolved in one of the upcoming releases! 💪  @laardee thanks for working on the fix!

**Closed** 2016-11-21 08:33 UTC
Labels: kind/bug, priority/P1, status/confirmed
