### ISSUE TITLE
Plugins missing in Node V5

### ISSUE THREAD

**Issue by jghaines** [serverless/serverless#904] opened 2016-03-29 01:28 UTC
See also: https://github.com/serverless/serverless-starter/issues/12
serverless project install gives an error. I get the same result with projects serverless-starter and serverless-graphql-blog

I ran the following install on Mac OS X v10.11.4:

$ sudo n latest
...
$ node --version
v5.9.1
$ sudo rm -rf /usr/local/lib/node_modules/serverless/
$ sudo npm install serverless --global
$ serverless --version
0.5.1
$ serverless project install serverless-starter
...
serverless.com, v0.5.1
...
Serverless: Installing Serverless Project "serverless-starter"...

Serverless: Downloading project and installing dependencies...

/usr/local/lib/node_modules/serverless/node_modules/bluebird/js/release/async.js:49
fn = function () { throw arg; };
^

ServerlessError: This plugin could not be found: serverless-optimizer-plugin
at new ServerlessError (/usr/local/lib/node_modules/serverless/lib/Error.js:17:11)
at Serverless._loadPlugins (/usr/local/lib/node_modules/serverless/lib/Serverless.js:293:17)
at Serverless.loadProjectPlugins (/usr/local/lib/node_modules/serverless/lib/Serverless.js:240:10)
at /usr/local/lib/node_modules/serverless/lib/Serverless.js:77:41
From previous event:
at Serverless.init (/usr/local/lib/node_modules/serverless/lib/Serverless.js:73:25)
at /usr/local/lib/node_modules/serverless/lib/actions/ProjectInstall.js:213:24
From previous event:
at ProjectInstall._initProject (/usr/local/lib/node_modules/serverless/lib/actions/ProjectInstall.js:208:27)
From previous event:
at ProjectInstall.installProject (/usr/local/lib/node_modules/serverless/lib/actions/ProjectInstall.js:110:12)
From previous event:
at /usr/local/lib/node_modules/serverless/lib/Serverless.js:181:31
at Array.reduce (native)
at /usr/local/lib/node_modules/serverless/lib/Serverless.js:180:32
From previous event:
at Serverless._execute (/usr/local/lib/node_modules/serverless/lib/Serverless.js:178:12)
at Serverless.actions.(anonymous function) (/usr/local/lib/node_modules/serverless/lib/Serverless.js:424:20)
at Serverless.command (/usr/local/lib/node_modules/serverless/lib/Serverless.js:393:38)
at /usr/local/lib/node_modules/serverless/bin/serverless:19:16
at tryOnImmediate (timers.js:534:15)
at processImmediate as _immediateCallback
From previous event:
at Object. (/usr/local/lib/node_modules/serverless/bin/serverless:18:4)
at Module._compile (module.js:413:34)
at Object.Module._extensions..js (module.js:422:10)
at Module.load (module.js:357:32)
at Function.Module._load (module.js:314:12)
at Function.Module.runMain (module.js:447:10)
at startup (node.js:142:18)
at node.js:939:3

**Comment by ac360** [comment] 2016-03-29 01:45
@jghaines I've been able to reproduce this issue w/ Node V5.9.1, but all is working w/ Node V4.

**Comment by jghaines** [comment] 2016-03-29 01:51
Confirmed that the original scenario works with
$ sudo n 4.4.1

**Comment by eahefnawy** [comment] 2016-03-30 10:59
@jghaines @ac360 I wasn't able to reproduce this issue with Node v5.9.1. Am I missing something?!

```
Eslams-MacBook-Pro:test-projects eslam$ serverless project install serverless-starter
 _______                             __
|   _   .-----.----.--.--.-----.----|  .-----.-----.-----.
|   |___|  -__|   _|  |  |  -__|   _|  |  -__|__ --|__ --|
|____   |_____|__|  \___/|_____|__| |__|_____|_____|_____|
|   |   |             The Serverless Application Framework
|       |                           serverless.com, v0.5.1
`-------'

Serverless: Installing Serverless Project "serverless-starter"...  
Serverless: Downloading project and installing dependencies...  

Serverless: Initializing Serverless Project...  
Serverless: Enter a new stage name for this project:  dev
Serverless: For the "dev" stage, do you want to use an existing Amazon Web Services profile or create a new one?
  > Existing Profile
    Create A New Profile
Serverless: Select a profile for your project: 
  > default
    serverlesstest
Serverless: Creating stage "dev"...  
Serverless: Select a new region for your stage: 
  > us-east-1
    us-west-2
    eu-west-1
    eu-central-1
    ap-northeast-1
Serverless: Creating region "us-east-1" in stage "dev"...  
Serverless: Deploying resources to stage "dev" in region "us-east-1" via Cloudformation (~3 minutes)...  
Serverless: No resource updates are to be performed.  
Serverless: Successfully created region "us-east-1" within stage "dev"  
Serverless: Successfully created stage "dev"  
Serverless: Successfully initialized project "serverless-starter"  
Serverless: Successfully installed project "serverless-starter"  
Eslams-MacBook-Pro:test-projects eslam$ node -v
v5.9.1
Eslams-MacBook-Pro:test-projects eslam$ 
```

**Comment by minibikini** [comment] 2016-03-30 13:21
Fixed. 
Turns out that the problem was because of NPM v3, not Node v5:
> While npm2 installs all dependencies in a nested way, npm3 tries to mitigate the deep trees and redundancy that such nesting causes. npm3 attempts this by installing some secondary dependencies (dependencies of dependencies) in a flat way, in the same directory as the primary dependency that requires it.

So the framework was copying the project folder but not its dependencies, since they are stored in the same folder as the `${projectFolder}/` and not under `${projectFolder}/node_modules`.

**Comment by eahefnawy** [comment] 2016-03-30 13:22
Thanks tons @minibikini :blush: ... Closing...

**Comment by eahefnawy** [comment] 2016-03-30 13:23
I should also add that the reason it was working for me is because I was still using NPM v2 with Node v5.

**Closed by eahefnawy** 2016-03-30 13:22 UTC
Labels: bug
