### ISSUE TITLE
Serverless build failing while deploying through bitbucket to aws.

### ISSUE THREAD

**Issue by bharadwaj-poduri** [serverless/serverless#8058] opened 2020-08-06 10:32 UTC
npm WARN deprecated resolve-url@0.2.1: https://github.com/lydell/resolve-url#deprecated
npm WARN deprecated urix@0.1.0: Please see https://github.com/lydell/urix#deprecated
npm ERR! code E404
npm ERR! 404 Not Found - GET https://registry.npmjs.org/@serverless%2futils - Not found
npm ERR! 404 
npm ERR! 404  '@serverless/utils@^1.2.0' is not in the npm registry.
npm ERR! 404 You should bug the author to publish it (or use the name yourself!)
npm ERR! 404 It was specified as a dependency of 'serverless'
npm ERR! 404 
npm ERR! 404 Note that you can also install from a
npm ERR! 404 tarball, folder, http url, or git url.
npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2020-08-06T10_27_29_764Z-debug.log

anyone facing this issue?

**Comment by medikoo** [comment] 2020-08-06 10:35
Duplicate of #8054

**Closed by medikoo** 2020-08-06 10:35 UTC
