### ISSUE TITLE
DeploymentBucket parameters not being replaced

### ISSUE THREAD

**Issue by mcshiz** [serverless/serverless#8951] opened 2021-02-16 16:29 UTC
I've noticed that when I try and do parameter replacement for the `provider.deploymentBucket` or `provider.deploymentBucket.name` property I am getting errors. <br />
I receive these error with and without the serverless-psuedo-parameters plugin.
**Configuration:** (Same error when nesting `name` or omitting it or using `Fn::Sub`)
```
  deploymentBucket: 
    name: !Sub 'development-team-deployment-bucket-${AWS::AccountId}'
```
**Result:**
`Configuration warning at 'provider.deploymentBucket.name': should be string`

**Configuration:**
```
  deploymentBucket: ${self:provider.stage}-brandzooka-deployment-bucket-#{AWS::AccountId}
```
**Result:**
`
Configuration warning at 'provider.deploymentBucket': should match pattern "(?!^(\d{1,3}\.){3}\d{1,3}$)(^(([a-z0-9]|[a-z0-9][a-z0-9-]*[a-z0-9])\.)*([a-z0-9]|[a-z0-9][a-z0-9-]*[a-z0-9])$)"
`

**Configuration** Where `${self:custom.accountId}` = `${AWS::AccountId}`
```
  deploymentBucket: 
    name: !Sub ${self:provider.stage}-brandzooka-deployment-bucket-${self:custom.accountId}
```
**Result**
This is what wound up in the `.serverless/serverless-state.json` file which looks like it should work BUT I get a fatal error from serverless ` Could not locate deployment bucket. Error: str.indexOf is not a function`
```
      "deploymentBucket": {
        "Fn::Sub": "development-brandzooka-deployment-bucket-${AWS::AccountId}"
      },
```      

However this works, so I believe the issue lies in the recent integration of serverless pseudo parameters.
```
${self:provider.stage}-brandzooka-deployment-bucket-413466xxxxxx
```

Framework Core: 2.23.0 (local)
Plugin: 4.4.2
SDK: 2.3.2
Components: 3.6.2

Command used to run `sls deploy --stage development --region us-east-1 --aws-profile me`

**Comment by pgrzesik** [comment] 2021-02-17 14:22
Hello @mcshiz :wave: Thanks a lot for reporting and sorry to hear that you've run into trouble with it. At the moment, we're not supporting `Sub` for `deploymentBucket` as we're relying on resolved name during the deployment process and `Sub` will be resolved by CloudFormation. So for this particular case, you'll need to supply AccountID in some other way.

**Comment by jwthomp** [comment] 2021-03-11 23:27
I spun my wheels quite a bit today on the same issue. When I restore the deprecated `serverless-pseudo-parameters` plugin then it works again.

**Comment by pgrzesik** [comment] 2021-03-15 13:05
Hello @jwthomp - did you have issue with `deploymentBucket` setting as well? What version of the Framework are you using?

**Comment by jwthomp** [comment] 2021-03-15 17:46
Mine was trying to use !Sub in the custom parameters for serverless-plugin-datadog plugin. Specifically:
custom:
  datadog:
    forwarder: !Sub... (or #{AWS::AccountId})

I wound up having to re-enable serverless-pseudo-parameters to get #{AWS::AccountId} to work.

**Comment by pgrzesik** [comment] 2021-03-17 10:13
Hello @jwthomp - thanks for the explanation, the built-in notation for pseudo-params is a bit different: https://www.serverless.com/framework/docs/providers/aws/guide/variables/#pseudo-parameters-reference did you try that one as well? Additionally, what error did you experience? Did it come from the plugin directly?

**Comment by HaaLeo** [comment] 2021-04-13 14:12
I experience a similar issue when I try to set the `deploymentBucket.name` via an environment variable:
```
  deploymentBucket: 
    name: ${env:S3_BUCKET}
```

Serverless then simply ignores this setting and tries to create its own `ServerlessDeploymentBucket` instead.

**Comment by pgrzesik** [comment] 2021-04-13 14:15
Hello @HaaLeo, what version of Framework are you using?

**Comment by HaaLeo** [comment] 2021-04-13 14:16
v2.34.0 Updated my previous comment

**Comment by pgrzesik** [comment] 2021-04-13 14:21
Thank you @HaaLeo - I've just tried to reproduce your issue but I'm observing correct behavior on my side. Could you provide a reproducible example with minimal `serverless.yml` and output of `sls deploy`? Maybe that will make it easier to reproduce the problem and diagnose the potential bug.

**Comment by HaaLeo** [comment] 2021-04-13 14:46
My setup is the following
I run the following two commands in two separate CodeBuild steps:
1. `sls package args...`
1. `sls deploy --package .serverless/`

The deployment was failing. Therefore, I only checked those logs 🤦🏼‍♂️. However, taking a closer look at the packaging step it indeed warns me about the missing parameter:

```
Serverless Warning --------------------------------------
 
A valid environment variable to satisfy the declaration 'env:S3_BUCKET' could not be found.
```

So my mistake was to set the environment variable during the deploy step but not for the packaging step where it is actually needed. Changing this fixed my issue.

Sorry @pgrzesik for over eagerly commenting on this issue.

**Comment by pgrzesik** [comment] 2021-04-14 08:25
No worries @HaaLeo, happy to hear you've been able to resolve your issue :+1:

**Comment by mahendraramesh** [comment] 2021-06-11 06:23
I'm having the same issue. Trying to use the AWS account id in the deployment bucket name so that the bucket is unique across accounts. Is there any way to achieve this? 

@pgrzesik you mentioned "you'll need to supply AccountID in some other way", can you suggest other ways to do it?

**Comment by pgrzesik** [comment] 2021-06-11 07:29
@mahendraramesh you can for example pass it via env variable and use that variable during resolution

**Comment by lludovic** [comment] 2021-07-21 18:22
I have the same issue:
`Framework Core: 2.52.0
Plugin: 5.4.3
SDK: 4.2.4
Components: 3.13.4
`

In my env.dev file I have var
`
DEPLOYMENT_BUCKET=${cf:dev-artifacts.ArtifactBucketName}
`
serveless.yml
`
provider:
 deploymentBucket: ${env:DEPLOYMENT_BUCKET}
`

Then I Got:
`
 Serverless Error ----------------------------------------
 
  Could not locate deployment bucket. Error: The specified bucket is not valid.
`

NB: Everything was fine until I update serverless version

**Comment by pgrzesik** [comment] 2021-07-21 18:36
Hey @lludovic - what version of the Framework were you using previously?

**Comment by lludovic** [comment] 2021-07-21 21:43
> Hey @lludovic - what version of the Framework were you using previously?
The previous version was
Framework Core: 2.39.1
Plugin: 4.5.3
SDK: 4.2.2
Components: 3.9.1

**Comment by pgrzesik** [comment] 2021-07-26 12:34
Thanks for sharing, could you also share to which value is `deploymentBucket` resolved for you at the moment in comparison to previously resolved value?

**Comment by lludovic** [comment] 2021-07-27 11:03
The previous resolved value was dev-artifacts-storage the now it's ${cf:dev-artifacts.ArtifactBucketName}

**Comment by pgrzesik** [comment] 2021-07-27 13:28
Thanks for sharing all that additional information - it looks like it's specific to the use case where variable is defined as a part of ENV VAR - during dotenv resolution, it tries to expand the value but fails to do so which alters the original value. Expansion change has been introduced recently as a part of this PR https://github.com/serverless/serverless/pull/9615

I believe the only way to support this would be to either make the variable expansion via `dotenv-expand` optional, or you would have to use a different way to pass it than the current approach you're using.

**Comment by pgrzesik** [comment] 2021-08-09 11:32
I'm going to close this ticket as original issue has been clarified and there's a way to achieve that now with `aws` variable source. As for your problem @lludovic - if you haven't been able to resolve it, please feel free to open a dedicated issue. Thanks in advance :bow:

**Closed by pgrzesik** 2021-08-09 11:32 UTC
Labels: needs feedback
