### ISSUE TITLE
Serverless overwrites existing ignore file

### ISSUE THREAD

**Issue by Calrion** [serverless/serverless#3582] opened 2017-05-10 04:49 UTC
# This is a Bug Report

## Description
My existing `.gitignore` file was overwritten when I ran `serverless create --template aws-nodejs`. I expected that Serverless would append to any existing file.

No error message was reported, I noticed when I went to commit Serverless' changes that it had overwritten the existing `.gitignore` file.

Yes, this happened when I started a new project but there was an existing ignore file because I'm using Vagrant; I'd already committed the `Vagrantfile` and added the `.vagrant` folder to the `.gitignore` file. This is actually the first time I've used Serverless (but this issue seemed like something you'd want to know about).

Similar or dependent issues: I didn't notice any when I searched.

## Additional Data

* ***Serverless Framework Version you're using***: v1.12.1
* ***Operating System***: Ubuntu 16.04 LTS Server (in a Vagrant-built VirtualBox VM hosted by OS X 10.11)
* ***Stack Trace***: N/A
* ***Provider Error messages***: N/A

**Comment by pmuens** [comment] 2017-05-10 07:42
Thanks for reporting @Calrion 👍 

This behavior is caused by https://github.com/serverless/serverless/pull/3065. We could fix the code there to support the appending mechanism.

**Comment by andymac4182** [comment] 2017-05-10 07:59
Probably should check if you want to merge or replace or do nothing.

**Comment by Calrion** [comment] 2017-05-12 01:15
My expectation was a straight append; I hadn't considered the advanced cases where a merge may be more appropriate. That said, I'd prefer even a straight replace over a failed merge that subtly broke my advanced ignore rules and accidentally commited secrets to the repository. :wink:

I'm only just getting started with Serverless, so I'm more-than-happy to defer to the better judgement of others.

**Comment by pmuens** [comment] 2017-05-12 05:38
@andymac4182 a merge sounds like a good solution here! +1 for that.

> I'm only just getting started with Serverless, so I'm more-than-happy to defer to the better judgement of others.

@Calrion Thanks for giving Serverless a spin and providing such feedback 👍

**Comment by pmuens** [comment] 2019-02-07 10:55
Closing since this issue is quite old and there are no future plans to change the behavoir of this in the foreseeable future.

**Closed by pmuens** 2019-02-07 10:55 UTC
Labels: bug, help wanted
