### ISSUE TITLE
DX: Helpful output when serverless.yml is malformed

### ISSUE THREAD

**Issue by seanohollaren** [serverless/serverless#3994] opened 2017-07-25 23:01 UTC
# This is a Feature Proposal

## Description
If a user attempts to put a user-defined top-level property in serverless.yml (other than one called `custom`), it is silently ignored while packaging and anything referencing that property will fail down the line, potentially not until deployment time.

I think this issue is compounded by the fact that the documentation isn't entirely clear on the fact that a custom top-level property in the yml file **must** be called `custom`.

* What went wrong?
`serverless package` does not call out that an improperly named top-level property is defined and will be ignored.  Instead, there is only a warning that properties referencing this top-level property have no value.

* What did you expect should have happened?
  - If `custom` is the only name allowed for user-defined top level properties, I would expect a warning or error at the `serverless package` step to alert the user that what they're trying to do isn't going to work.
  - I'd also expect that the [documentation](https://serverless.com/framework/docs/providers/aws/guide/variables/) would have a sentence explicitly calling out that this naming restriction exists.

* What was the config you used?

Example serverless.yml exerpt:
```yaml
service: foo

# This will work
custom: someValue

# This will not
bar: someValue

provider:
...
```

## Feature proposals:
* `serverless package` prints a warning or error when it detects a top-level property which it's going to ignore.
* Documentation is improved to be more explicit about the `custom` naming convention.
  - If this is desired, I can look at putting in a PR.

## Additional Data

* ***Serverless Framework Version you're using***: 1.18

**Comment by pmuens** [comment] 2017-07-26 06:36
Thanks for opening @seanohollaren 👍

Related issues are:
- https://github.com/serverless/serverless/issues/2008
- https://github.com/serverless/serverless/issues/3758

**Comment by kbariotis** [comment] 2017-07-29 11:05
I took the initiative and tried to resolve this @seanohollaren. Hope its ok :)

**Comment by pmuens** [comment] 2017-07-29 21:08
> I took the initiative and tried to resolve this @seanohollaren. Hope its ok :)

Nice! Thanks for taking the initiative and jumping into this one @kbariotis 👍

**Comment by horike37** [comment] 2017-07-30 17:45
>serverless package prints a warning or error when it detects a top-level property which it's going to ignore.

There is a case which a new property is added by a plugin.
[Serverless Step Functions](https://github.com/horike37/serverless-step-functions) add `stepFunctions` property to top-level. In the case, we should consider not to print a warning.

**Comment by kbariotis** [comment] 2017-07-30 17:53
Hmm yes thats interesting. Isnt custom what is there for? 3rd party plugins shouldnt introduce new properties under root. Otherwise they can also mess with the main properties and break things.

**Comment by pmuens** [comment] 2017-07-31 10:44
Good point @horike37 👍

> Isnt custom what is there for? 3rd party plugins shouldnt introduce new properties under root. Otherwise they can also mess with the main properties and break things.

@kbariotis is right here. The `custom` property was designed for 3rd party plugins to store their plugin specific configuration.

**Comment by horike37** [comment] 2017-07-31 12:06
@pmuens @kbariotis 
>However @kbariotis is right here. The custom property was designed for 3rd party plugins to store >their plugin specific configuration.

Thank you for letting me know this. 
Ohh, I didn't know it :scream: However, I have already set the property on the top-level. If I change it, would be BREAKING..

**Comment by pmuens** [comment] 2017-08-01 05:55
> Thank you for letting me know this.
> Ohh, I didn't know it 😱 However, I have already set the property on the top-level. If I change it, would be BREAKING.. 😥

🤔 yes, I think the docs might be lacking a callout to put 3rd party plugin config into the `custom` section. Maybe we should update them...

A possible transition for your plugin could be to support both configs for e.g. two minor versions and then update the major and drop the old config.

**Comment by seanohollaren** [comment] 2017-08-01 06:26
Talking about third party plugins is actually the one explicit call out
that `custom` gets in the docs, I think.

https://serverless.com/framework/docs/providers/aws/guide/plugins/

**Comment by seanohollaren** [comment] 2017-08-01 06:27
Talking about third party plugins is actually the one explicit call out
that `custom` gets in the docs, I think.

https://serverless.com/framework/docs/providers/aws/guide/plugins/

**Comment by seanohollaren** [comment] 2017-08-01 17:43
Do you think it'd be worth adding a section which explicitly calls out the purpose of the `custom` section, like the "Defining Custom Variables" section in my fork?

https://github.com/seanohollaren/serverless/blob/master/docs/providers/aws/guide/variables.md

**Comment by pmuens** [comment] 2017-08-01 18:57
> Do you think it'd be worth adding a section which explicitly calls out the purpose of the custom section, like the "Defining Custom Variables" section in my fork?

Hey @seanohollaren good idea! Thanks for getting this started.

IMHO we should add another separate section (separate headline) in the plugin development doc about the purpose of the `custom` section. This way we'd have both. Your addition to the `variables` guide and a separate section in the `plugins` guide.

What do you think about this?

**Comment by seanohollaren** [comment] 2017-08-01 19:40
I think that's a great idea, since people will end up at the Variables doc and the Plug-ins doc for very different reasons, but both need to get the basic idea.

**Comment by horike37** [comment] 2017-08-02 01:06
I think that's a great idea too. I misunderstood that `custom` section is for only framework users.

**Comment by pmuens** [comment] 2017-08-02 05:32
@seanohollaren @horike37 thanks for the feedback 👍!

@seanohollaren do you want to include this in your branch and PR it? (also note that this should be changed in the other provider docs as well).

**Comment by seanohollaren** [comment] 2017-08-02 16:11
Sure thing.  I'll get those updated and open a PR.

**Comment by pmuens** [comment] 2017-08-02 18:55
> Sure thing. I'll get those updated and open a PR.

Thanks for that @seanohollaren 👍

**Comment by romankoval** [comment] 2018-06-18 12:03
Any updates on useful validation messages?

**Comment by apoorvparijat** [comment] 2018-11-20 03:01
Is this validation still desired? I am happy to open a PR if it is.

**Comment by softprops** [comment] 2018-11-20 03:17
I asked a potentially related question on the forum a while back https://forum.serverless.com/t/formal-specification-of-serverless-yml/6285

Having a json schema representation would enable a feature this gh is asking for as well as tooling for vscode I'm working on

**Comment by pmuens** [comment] 2019-02-08 10:04
Closing since this is related to the issue of "`serverless.yml` validation before deployment".

**Closed by pmuens** 2019-02-08 10:04 UTC
Labels: feature, help wanted
