### ISSUE TITLE
Error running integration tests

### ISSUE THREAD

**Issue by adrianmaurer** [serverless/serverless#2216] opened 2016-09-26 20:54 UTC
# This is a Bug Report

## Description
I'm creating a new template for serverless and I'm unable to run integrations tests.

For bug reports:
* What went wrong?
Saw the error `Cannot find module 'lodash/object/assign'` when running `integration-test-template` tests
* What did you expect should have happened?
Run all the integration tests
* What was the config you used?
Current master version
* What stacktrace or error message from your provider did you see?
N/A

## Additional Data

I've installed lodash.assign w/o luck

* ***Serverless Framework Version you're using***:
1.0.0-rc.2
* ***Operating System***:
Ubuntu Trusty
* ***Stack Trace***:
N/A
* ***Provider Error messages***:
```
Creating Application
 
  Error --------------------------------------------------
 
     Cannot find module 'lodash/object/assign'
 
     For debugging logs, run again after setting SLS_DEBUG env var.
 
  Get Support --------------------------------------------
     Docs:          docs.serverless.com
     Bugs:          github.com/serverless/serverless/issues
 
     Please report this error. We think it might be a bug.
```

**Comment by flomotlik** [comment] 2016-09-27 07:36
@adrianmaurer could you share the template you're implementing and the config for it? Is that a Node template, or failing due to other reasons? Can you try with the current master?

**Comment by adrianmaurer** [comment] 2016-09-27 12:57
Sure, below is the config. I've tested with and without my change adding scala.

test_all_templates
```
#!/bin/bash

set -e

DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"

function integration-test {
  $DIR/integration-test-template $@
}

integration-test aws-java-gradle build
integration-test aws-java-maven mvn package
integration-test aws-scala-sbt sbt package
integration-test aws-nodejs
integration-test aws-python
```

**Comment by adrianmaurer** [comment] 2016-09-27 16:07
one other thing I failed to mention is that this operation is being run on a virtual machine. Not sure if that has any affect.

**Comment by flomotlik** [comment] 2016-09-28 06:42
@adrianmaurer I've just merged the Scala/SBT template and reran the tests on my local machine. It passed here. Could you try running with the latest master? As this is also not reproducible and we already to got the template merged I'm not sure if we need to invest more time here, but happy to help on that.

**Comment by mthenw** [comment] 2016-10-14 20:44
@adrianmaurer any news?

**Closed** 2016-10-18 17:41 UTC
Labels: bug
