### ISSUE TITLE
Function deploy with invalid stage fails but doesn't exit with error

### ISSUE THREAD

**Issue by haack** [serverless/serverless#893] opened 2016-03-25 17:45 UTC
Attempting to deploy with an invalid stage will fail however the exit status doesn't indicate so. Could be a problem for CI tool's that try to deploy automatically.

E.g:
```
$ sls function deploy -a --stage stagethatdoesntexist
...
Serverless: Failed to deploy...
...
$ echo $?
0
```

**Comment by HyperBrain** [comment] 2016-03-26 10:20
Duplicate of #773

**Comment by ac360** [comment] 2016-03-26 16:18
Closing because this is aduplicate

**Closed by ac360** 2016-03-26 16:18 UTC
