### ISSUE TITLE
When invoking locally hangs on "Serverless: Installing dependencies for custom CloudFormation resources..."

### ISSUE THREAD

**Issue by mcaubrey** [serverless/serverless#8879] opened 2021-02-03 01:38 UTC
When invoking locally via a command such as `SLS_DEBUG=* sls invoke local -f login -d "{ \"key\": \"foobar\" }" -vvv` it hangs on `Serverless: Invoke aws:common:moveArtifactsToPackage` without ever throwing an error (after leaving it that way for an hour, it is yet to be seen if it might eventually throw some error). This occurred only when data was passed. When do data was passed (`SLS_DEBUG=* sls invoke local -f login -vvv`) it invoked without a problem. 

In the process of writing this bug report. I made a copy of my project, removed plugins and sensitive information, and tried to reproduce the problem. Upon trying to reproduce the problem from a different folder, the invocation hanged at `Serverless: Installing dependencies for custom CloudFormation resources...` This seems to occur without regard to whether or not data is passed. 

<details>
<summary><code>serverless.yml</code></summary>

```yaml
service: dummy-for-reproduction

frameworkVersion: "2"

package:
  exclude:
    - ./**
  include:
    - ./bin/**

custom: ${file(./config.json)}

provider:
  name: aws
  runtime: go1.x
  stage: ${opt:stage, self:custom.stage}
  lambdaHashingVersion: 20201221
  region: ap-northeast-1
  memorySize: 128
  logs:
    restApi: true
  stackTags:
    squad: Test
  apiGateway:
    minimumCompressionSize: 1024
    shouldStartNameWithService: true
  environment: ${opt:environment, self:custom.environment}

functions:
  login:
    handler: bin/login
    events:
      - http:
          path: login
          method: get
          cors: true
    environment:
      reference: "http://example.com/interal-wiki-url"

```

</details>

<details>
<summary><b><code>SLS_DEBUG=* sls invoke local -f login -d "{ \"key\": \"foobar\" }" -vvv</code> output</b></summary>

```
Serverless: Running "serverless" installed locally (in service node_modules)
Serverless: Deprecation warning: Serverless constructor expects resolved service configuration path to be provided via "config.configurationPath".
            Starting from next major Serverless will no longer auto resolve that path internally.
            More Info: https://www.serverless.com/framework/docs/deprecations/#MISSING_SERVICE_CONFIGURATION_PATH
Serverless: Packaging service...
Serverless: Excluding development dependencies...
Serverless: Installing dependencies for custom CloudFormation resources...
```

</details>

<b>Installed version</b>

```
Framework Core: 2.22.0
Plugin: 4.4.2
SDK: 2.3.2
Components: 3.6.1
```

**Comment by pgrzesik** [comment] 2021-02-03 11:20
Hello @mcaubrey, thanks a lot for reporting your issue, sorry to hear that you're having troubles. 

I've tried to reproduce that issue locally with `aws-go` template, however, I'm not able to reproduce it and everything is working as intended, both for `invoke local` with params or without them. I've also tried to use your example and it worked correctly, with `Installing dependencies for custom CloudFormation resources...` passing correctly (it's needed for `apiGatewayCloudWatchRole`). Both these cases have to do with local file manipulation which might be related to your local configuration. What operating system are you using? What Node version are you on? Would you be willing to prepare a small reproducible example for me to try out on my side (e.g. as a simple github repo)? 

Thanks in advance :bow:

**Comment by mcaubrey** [comment] 2021-02-04 12:19
Hey thanks for your response.

I tried making a new project with the `aws-go-mod` template to see if I could edit it little by little until it reproduced the error. I was never able to. I went back to the actual project I'm working on and tried invoking it locally again... and suddenly it's not hanging anymore.

So it fixed itself I guess?

You can go ahead and close this, but if you have any idea what could've caused that, or some sort of troubleshooting action I can take in case it happens again, that would be awesome.

**Comment by pgrzesik** [comment] 2021-02-04 12:43
Hello again :wave: The only thing I can think of is that there was an issue with local filesystem permissions as it was hanging on operations related to file manipulation (moving artifacts, installing custom resources), but that's all I got :joy: 

I'm closing this one and if I ever see as similar issue along with the cause I'll do my best to remember and link it here. Cheers :wave:

**Closed by pgrzesik** 2021-02-04 12:43 UTC
Labels: needs feedback
