### ISSUE TITLE
Create self suficient packages (which does not leave service context requirement) with `sls package`

### ISSUE THREAD

**Issue by anantab** [serverless/serverless#7259] opened 2020-01-27 06:15 UTC
# Bug Report
serverless deploy from package requires serverless.yml file
## Description
I run  serverless package to create a package, upload the package to artifactory use it to deploy in production. But When I tried to deploy from the package, serverless throws error
```
Serverless Error ---------------------------------------
  This command can only be run in a Serverless service directory
```
I think, if we are deploying from a package, serverless should not be looking for serverless.yml file.

I tried to copy the project serverless.yml file with the package. But when there is a serverless.yml file in the directory, serverless  unnecessarily compiles the yml file.  So I ran into another issue because serverless could not reference to all the variables from other config file, because they were not copied into the package.  I had to create a dummy serverless.yml file just to get around the issue.

1. What did you do?
 Tried to run ```serverless deploy --package /tmp/my-package```

1. What happened?
Got Error:
```
Serverless Error ---------------------------------------
  This command can only be run in a Serverless service directory
```
1. What should've happened?
Should have depoyed without requiring ```serverless.yml``` file
1. What's the content of your `serverless.yml` file?
1. What's the output you get when you use the `SLS_DEBUG=*` environment variable (e.g. `SLS_DEBUG=* serverless deploy`)

Similar or dependent issues:

- #12345

**Comment by medikoo** [comment] 2020-01-28 12:39
@anantab `--package` param only reads artifacts to be uploaded to AWS, and it doesn't apply to `serverless.yml` configuration, which still needs to be read to resolve the needed _stage_, _service name_ etc. Hence`serverless.yml` is expected to be provided.

This is the current design, while of course we're open for improvement suggestions.

**Comment by anantab** [comment] 2020-01-29 00:07
> @anantab `--package` param only reads artifacts to be uploaded to AWS, and it doesn't apply to `serverless.yml` configuration, which still needs to be read to resolve the needed _stage_, _service name_ etc. Hence`serverless.yml` is expected to be provided.
> * When running serverless package, all the required configurations are already resolved including service, stage etc and compiled to cloudformation . All serverless needs to do to deploy a package is to copy the package to aws and run the cloudformation template. I don't see a point for serverless to look for serverless yml again.   Most of the time, the package feature will be used to create a package that will later be used to deploy to aws outside of the scope of serverless project (hence no serverless.yml).
* In my usecase, we have separate production CI/CD. From Non Production CI/CD, we create a package and upload the package to artifactory. The production CI/CD downloads the package from artifactory and deploys it and does not use the project code. This is the pattern we need to follow.
* I am facing 2 serverless issues for my requirements and have work arounds for them:

1.  Serverless needs a serverless.yml file even when deploying from a package. So I am creating a dummy serverless file that does nothing to fool serverless. 

2. Another issue is in ```serverless-state.json``` in packaged file. The path to artifact  is wrong. It always assumes .serverless directory in the project directory.
 I am running 
```serverless package --package /path-to-package-dir```.
But in ```serverless-state.json```, the artifact path is 
```
  },
    "artifact": "/path-to-project-dir/.serverless/MYPROJECT.zip"
  },
```
I have to read the json file and update the path before running
```serverless deploy --package /path-to-package-dir```.



> This is the current design, while of course we're open for improvement suggestions.

I think with the current design, the package feature is almost useless, other than just to to verify the generated cloudformation template.

**Comment by medikoo** [comment] 2020-01-29 11:22
Packaging serves different use cases. e.g. other request we have is to ability to reuse the packaged files for deploys to different regions and stages (#6568).

This request is about packaging that creates self sufficient package for complete deploy (so no service context is needed for deployment).

We're definitely open for that improvement, still first it'll be good to spec how it should work to not be breaking against how packaging works now, having that we'll be open for PR's

**Comment by medikoo** [comment] 2021-12-08 14:42
Closing as duplicate of #3421

**Closed by medikoo** 2021-12-08 14:42 UTC
Labels: enhancement, help wanted
