### ISSUE TITLE
Error: Cannot find module spawn-sync/postinstall

### ISSUE THREAD

**Issue by HostOnNet** [serverless/serverless#4319] opened 2017-09-28 09:29 UTC
# This is a Bug Report

## Description

For bug reports:
* What went wrong?

when running "npm install -g serverless", it fail.

```
root@backup:~# npm install -g serverless
npm WARN registry Unexpected warning for https://registry.npmjs.org/: Miscellaneous Warning EINTEGRITY: sha1-wZyd+aAocC1nhhI4SmVSQExjbRU= integrity checksum failed when using sha1: wanted sha1-wZyd+aAocC1nhhI4SmVSQExjbRU= but got sha512-MJTUg1kjuLeQCJ+ccE4Vpa6kKVXkPYJ2mOCQyUuKLcLQsdrMCpBPUi8qVE6+YuaJkozeA9NusTAw3hLr8Xe5EQ==. (15621 bytes)
npm WARN registry Using stale package data from https://registry.npmjs.org/ due to a request error during revalidation.
/root/.nvm/versions/node/v8.1.4/bin/serverless -> /root/.nvm/versions/node/v8.1.4/lib/node_modules/serverless/bin/serverless
/root/.nvm/versions/node/v8.1.4/bin/slss -> /root/.nvm/versions/node/v8.1.4/lib/node_modules/serverless/bin/serverless
/root/.nvm/versions/node/v8.1.4/bin/sls -> /root/.nvm/versions/node/v8.1.4/lib/node_modules/serverless/bin/serverless

> spawn-sync@1.0.15 postinstall /root/.nvm/versions/node/v8.1.4/lib/node_modules/serverless/node_modules/spawn-sync
> node postinstall

module.js:328
    throw err;
    ^

Error: Cannot find module '/root/.nvm/versions/node/v8.1.4/lib/node_modules/serverless/node_modules/spawn-sync/postinstall'
    at Function.Module._resolveFilename (module.js:326:15)
    at Function.Module._load (module.js:277:25)
    at Function.Module.runMain (module.js:442:10)
    at startup (node.js:136:18)
    at node.js:966:3
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! spawn-sync@1.0.15 postinstall: `node postinstall`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the spawn-sync@1.0.15 postinstall script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2017-09-28T09_13_12_283Z-debug.log
root@backup:~# 
````

* What did you expect should have happened?

Install serverless with out error.

* What was the config you used?

```
root@backup:~# node --version
v8.1.4
root@backup:~# which node
/root/.nvm/versions/node/v8.1.4/bin/node
root@backup:~# 
````

* What stacktrace or error message from your provider did you see?

## Additional Data

* ***Serverless Framework Version you're using***:

Install failed.

* ***Operating System***:

Ubuntu 16.04

* ***Stack Trace***:

Posted full error above, if any other info required, let me know.

* ***Provider Error messages***:

**Comment by RafalWilinski** [comment] 2017-09-28 10:55
Thanks for reporting issue @HostOnNet 💯.

Unfortunately, I wasn't able to reproduce this issue, here's my log:
```
$ nvm install 8.1.4
Downloading https://nodejs.org/dist/v8.1.4/node-v8.1.4-darwin-x64.tar.xz...
######################################################################## 100.0%
Now using node v8.1.4 (npm v5.0.3)
$ nvm use 8.1.4
Now using node v8.1.4 (npm v5.0.3)
$ npm install serverless -g
npm WARN registry Unexpected warning for https://registry.npmjs.org/: Miscellaneous Warning EINTEGRITY: sha1-wZyd+aAocC1nhhI4SmVSQExjbRU= integrity checksum failed when using sha1: wanted sha1-wZyd+aAocC1nhhI4SmVSQExjbRU= but got sha512-MJTUg1kjuLeQCJ+ccE4Vpa6kKVXkPYJ2mOCQyUuKLcLQsdrMCpBPUi8qVE6+YuaJkozeA9NusTAw3hLr8Xe5EQ==. (15621 bytes)
/Users/Rafal/.nvm/versions/node/v8.1.4/bin/slss -> /Users/Rafal/.nvm/versions/node/v8.1.4/lib/node_modules/serverless/bin/serverless
/Users/Rafal/.nvm/versions/node/v8.1.4/bin/serverless -> /Users/Rafal/.nvm/versions/node/v8.1.4/lib/node_modules/serverless/bin/serverless
/Users/Rafal/.nvm/versions/node/v8.1.4/bin/sls -> /Users/Rafal/.nvm/versions/node/v8.1.4/lib/node_modules/serverless/bin/serverless

> serverless@1.23.0 postinstall /Users/Rafal/.nvm/versions/node/v8.1.4/lib/node_modules/serverless
> node ./scripts/postinstall.js


> spawn-sync@1.0.15 postinstall /Users/Rafal/.nvm/versions/node/v8.1.4/lib/node_modules/serverless/node_modules/spawn-sync
> node postinstall

+ serverless@1.23.0
added 249 packages in 20.862s
```

But that was on OS X, I'll try to reproduce that on Ubuntu 16.04 today and post results.

**Comment by RafalWilinski** [comment] 2017-09-29 08:34
I've managed to reproduce the issue on Ubuntu 16.04. Here's more detailed log:
```
78 verbose linkBins serverless@1.23.0
79 verbose linkBins [ { serverless: './bin/serverless',
79 verbose linkBins     slss: './bin/serverless',
79 verbose linkBins     sls: './bin/serverless' },
79 verbose linkBins   '/root/.nvm/versions/node/v8.1.4/bin',
79 verbose linkBins   true ]
80 verbose linkMans serverless@1.23.0
81 silly doSerial global-link 7
82 silly doParallel update-linked 7
83 silly doSerial install 7
84 silly install serverless@1.23.0
85 info lifecycle serverless@1.23.0~install: serverless@1.23.0
86 silly lifecycle serverless@1.23.0~install: no script for install, continuing
87 silly doSerial postinstall 7
88 silly postinstall serverless@1.23.0
89 info lifecycle serverless@1.23.0~postinstall: serverless@1.23.0
90 verbose lifecycle serverless@1.23.0~postinstall: unsafe-perm in lifecycle false
91 verbose lifecycle serverless@1.23.0~postinstall: PATH: /root/.nvm/versions/node/v8.1.4/lib/node_modules/npm/bin/node-gyp-bin:/root/.nvm/versions/node/v8.1.4/lib/node_modules/serverless/node_modules/.bin:/root/.nvm/versions/node/v8.1.4/lib/node_modules/.bin:/root/.nvm/versions/node/v8.1.4/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
92 verbose lifecycle serverless@1.23.0~postinstall: CWD: /root/.nvm/versions/node/v8.1.4/lib/node_modules/serverless
93 silly lifecycle serverless@1.23.0~postinstall: Args: [ '-c', 'node ./scripts/postinstall.js' ]
94 info lifecycle serverless@1.23.0~postinstall: Failed to exec postinstall script
95 verbose unlock done using /root/.npm/_locks/staging-5afb08c33fded910.lock for /root/.nvm/versions/node/v8.1.4/lib/node_modules/.staging
96 verbose stack Error: serverless@1.23.0 postinstall: `node ./scripts/postinstall.js`
96 verbose stack spawn ENOENT
96 verbose stack     at ChildProcess.<anonymous> (/root/.nvm/versions/node/v8.1.4/lib/node_modules/npm/lib/utils/spawn.js:33:16)
96 verbose stack     at emitTwo (events.js:125:13)
96 verbose stack     at ChildProcess.emit (events.js:213:7)
96 verbose stack     at maybeClose (internal/child_process.js:897:16)
96 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:208:5)
97 verbose pkgid serverless@1.23.0
98 verbose cwd /
99 verbose Linux 4.9.49-moby
100 verbose argv "/root/.nvm/versions/node/v8.1.4/bin/node" "/root/.nvm/versions/node/v8.1.4/bin/npm" "install" "-g" "serverless"
101 verbose node v8.1.4
102 verbose npm  v5.0.3
103 error file sh
104 error code ELIFECYCLE
105 error errno ENOENT
106 error syscall spawn
107 error serverless@1.23.0 postinstall: `node ./scripts/postinstall.js`
107 error spawn ENOENT
108 error Failed at the serverless@1.23.0 postinstall script.
108 error This is probably not a problem with npm. There is likely additional logging output above.
109 verbose exit [ 1, true ]
```

**Comment by ezeql** [comment] 2017-12-06 18:26
hitting this issue too

**Comment by JohnathanKong** [comment] 2017-12-21 14:32
Same issue here on Ubuntu 16.04

**Comment by JohnathanKong** [comment] 2017-12-21 14:50
Finally found the solution, https://github.com/ForbesLindesay/spawn-sync/issues/42#issuecomment-236502384. Exact commands I executed:

npm install -g try-thread-sleep
npm install -g serverless --ignore-scripts spawn-sync

and now serverless is working. It installed 1.25.0 successfully.

**Comment by arnoldgr** [comment] 2018-06-15 18:51
did not work for me :(

**Comment by badiuddinlinux** [comment] 2019-01-15 04:00
adding a symbolic link  solved the issue for me on linux.
sudo ln -s /usr/local/lib/nodejs/node-$VERSION/bin/serverless /usr/bin/serverless

**Comment by samjmckenzie** [comment] 2019-01-22 20:43
Experiencing this issue here as well. Using macOS.

**Comment by DWboutin** [comment] 2019-02-03 21:01
Same on macOS

**Comment by svavar** [comment] 2019-04-08 08:36
The commands from @JohnathanKong worked for me on Ubuntu 18.10. I also had to run them as sudo.

**Comment by umutykaya** [comment] 2019-06-25 08:31
Same issue raise for me

**Comment by sergioregueira** [comment] 2019-07-19 10:45
Same error on Docker image `node:10-alpine` when I try to deploy.

```
internal/modules/cjs/loader.js:638
    throw err;
    ^

Error: Cannot find module '/root/.npm/_npx/17/lib/node_modules/serverless/node_modules/spawn-sync/postinstall'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:636:15)
    at Function.Module._load (internal/modules/cjs/loader.js:562:25)
    at Function.Module.runMain (internal/modules/cjs/loader.js:829:12)
    at startup (internal/bootstrap/node.js:283:19)
    at bootstrapNodeJSCore (internal/bootstrap/node.js:622:3)
```

**Comment by alex-percayso** [comment] 2019-08-15 09:36
I had the same issue and realised that I had not have serverless within my package.json so on CI/CD deployment it couldn't find serverless whereas when I run locally I have it installed globally.

**Comment by Ashishtantram** [comment] 2019-09-24 09:18
Try npm install with --unsafe-perm 

it works for me..

**Comment by medikoo** [comment] 2021-01-19 09:03
Closing, as I believe it was specific to older Node.js version, and also our postinstall script was very simplified since it was reported.

Anyway please comment if you still find it happening.

**Closed by medikoo** 2021-01-19 09:03 UTC
Labels: bug, cat/dx, help wanted

**Comment by ranjanrahul910** [comment] 2021-04-26 09:24
when i am running below to install yomen and superset generator in superset folder in linux
**npm install -g yo @superset-ui/generator-superset** 

getting below error 

npm ERR! code 127
npm ERR! path /root/.nvm/versions/node/v12.19.0/lib/node_modules/yo/node_modules/spawn-sync

npm ERR! command failed
npm ERR! command sh -c node postinstall
npm ERR! sh: node: command not found

Anyone please suggest what i have missed.

**Comment by eduardolucioac** [comment] 2022-01-11 18:40
The **_--ignore-scripts_** option worked for me! =D

```
npm install -g serverless --ignore-scripts
```

SPECIFICATIONS:

**Ubuntu Server 20.04**

```
root@us-bp-o:/home/brasilprev# node -v
v16.13.2
root@us-bp-o:/home/brasilprev# npm -v
8.1.2
```

Thanks! =D
