### ISSUE TITLE
V 0.5.2 - `serverless function deploy` is not working

### ISSUE THREAD

**Issue by nirmalgoswami** [serverless/serverless#954] opened 2016-04-06 05:13 UTC
running it  in a Function, it should deploy only function.but it is deploying all functions.

**Comment by eahefnawy** [comment] 2016-04-06 12:51
Thanks for reporting! I was able to reproduce, investigating now...

**Comment by eahefnawy** [comment] 2016-04-06 13:23
hmmm actually I wasn't able to reproduce, but I thought I'm producing cause of this confusing message:

```
Deploying functions in "dev" to the following regions: us-east-1 
```
It says "functions" even though it's just one function, but at the end of the deployment it shows only one function of CWD is deployed. So I guess this is where the confusion is.

Could you confirm that it's just the prompt message that is confusing, and you that it's actually one function is getting deployed after all? 

I just pushed a fix for the confusing messages.

Thanks for reporting :blush:

**Comment by nirmalgoswami** [comment] 2016-04-07 07:53
@eahefnawy acutally its not just prompt message that is confusing but i can see so many deployed function list after successfully deployed functions to aws,let me show that process so you can investigate  

```
E:\wamp\www\project\api\function1>serverless function deploy
Serverless: Deploying functions in "prod" to the following regions: us-west-2
Serverless: ------------------------
Serverless: Successfully deployed functions in "prod" to the following regions:
Serverless: us-west-2 ------------------------
Serverless:   function2(project-function2): arn:aws:lambda:us-west-2:345345:function:project-function2
Serverless:   function3(project-function3): arn:aws:lambda:us-west-2:345345:function:project-function3
Serverless:   function1(project-function1): arn:aws:lambda:us-west-2:345:function:project-function1
Serverless:   function4(project-function4): arn:aws:lambda:us-west-2:345345:function:project-function4
Serverless:   function5(project-function5): arn:aws:lambda:us-west-2:345345:function:project-function5
Serverless:   function6(project-function6): arn:aws:lambda:us-west-2:345345:function:project-function6
```

i have changed original name of function but you can see my all functions are deploying

**Comment by eahefnawy** [comment] 2016-04-07 09:15
ahaa I figured it out. It's a windows bug that has something to do with backward vs. forward slash for file paths. Just pushed a fix. Could you try from our master branch and let us know if it's now working? (we don't have access to windows machines :disappointed: )

**Comment by nirmalgoswami** [comment] 2016-04-07 09:21
@eahefnawy Thanks for quick fix,i will check and let you know

**Comment by nirmalgoswami** [comment] 2016-04-07 12:05
@eahefnawy 
Just checked by installing `master` branch using `npm install -g git://github.com/serverless/serverless.git`

i can see you have changed prompt message also i can see your changes related `path.sep` in my serverless package

`Deploying the specified functions in "prod" to the following regions: us-west-2`

but the fix is not working using latest code

**Comment by c-knowles** [comment] 2016-04-07 13:51
I saw something related to extra functions displaying on a pull from master last week. It seemed like the functions from the `tests` directory were being picked up. I had assumed it was due to local installation though at the time but I've just installed 0.5.2 globally and gotten the same issue. I'm running on Mac OS X. Inside a serverless project with zero functions:

```
$ npm i serverless -g
...

$ sls --version
0.5.2

$ sls dash summary
...
Serverless: 5 functions --------------------------  
Serverless:     |_ function0 (1 endpoints - 0 events)  
Serverless:             |_ GET function0 (endpoint)  
Serverless:     |_ function1 (1 endpoints - 4 events)  
Serverless:             |_ GET group1/function1 (endpoint)  
Serverless:             |_ dynamodb (dynamoDBstream event)  
Serverless:             |_ s3 (s3 event)  
Serverless:             |_ sns (sns event)  
Serverless:             |_ schedule (schedule event)  
Serverless:     |_ function2 (1 endpoints - 0 events)  
Serverless:             |_ GET group1/function2 (endpoint)  
Serverless:     |_ function3 (2 endpoints - 0 events)  
Serverless:             |_ GET group1/function3 (endpoint)  
Serverless:             |_ POST group1/function3 (endpoint)  
Serverless:     |_ function4 (2 endpoints - 0 events)  
Serverless:             |_ GET group2/function4 (endpoint)  
Serverless:             |_ POST group2/function4 (endpoint)  
```

**Comment by eahefnawy** [comment] 2016-04-07 17:23
Yikes! is this another bug? I can't reproduce it. And you're running on OSX!

The only way I could think of that would cause the test functions to be picked up is if the serverless repo is inside your serverless project. We recursively look for all `s-function.json` files inside the project.

**Comment by c-knowles** [comment] 2016-04-08 03:20
I had another look at this today. I think it was potentially related to my usage of nvm since it's gone away after I've changed versions of node. I'm going to write it off as something I did while trying to work with master on the previous version of node.

**Comment by nirmalgoswami** [comment] 2016-04-15 13:46
@eahefnawy please open this issue,still its not fixed !

**Comment by flomotlik** [comment] 2016-05-12 12:29
@nirmalgoswami at the moment we don't have enough resources to track this bug down on windows. If you could look into it and provide a patch I'd love to look into it, but it seems to be an edge case that we currently can't look into due to time constraints.

**Closed by flomotlik** 2016-05-12 12:29 UTC
Labels: bug: can't reproduce, priority: medium
