### ISSUE TITLE
Dayjs >=1.9.2 is incompatible with serverless

### ISSUE THREAD

**Issue by EnoF** [serverless/serverless#8394] opened 2020-10-13 10:00 UTC
Dayjs version >= 1.9.2 causes problems with serverless. Running `sls help` returns the following error:
```
$ sls help
  Type Error ---------------------------------------------
 
  TypeError: t is not a function
```

I resolved the issue by installing dayjs@1.9.1, `npm i -D dayjs@1.9.1`

<details>
<summary><code>serverless.yml</code></summary>

```yaml
N/A
```

</details>

<details>
<summary><b><code>sls help</code> output</b></summary>

```
  Type Error ---------------------------------------------
 
  TypeError: t is not a function
```

</details>

<b>Installed version</b>

```
  Your Environment Information ---------------------------
     Operating System:          linux
     Node Version:              10.17.0
     Framework Version:         2.3.0 (local)
     Plugin Version:            4.0.4
     SDK Version:               2.3.2
     Components Version:        3.2.1
```

**Comment by medikoo** [comment] 2020-10-13 10:07
Duplicate of #8393

**Closed by medikoo** 2020-10-13 10:07 UTC
Labels: duplicate
