### ISSUE TITLE
Add the enabled flag to API key settings

### ISSUE THREAD

**Issue by JorisPhilipsen** [serverless/serverless#8791] opened 2021-01-20 10:50 UTC
### Use case description

I was wondering if it would be possible to add the enabled boolean flag to the API key settings in the serverless.yml file. 

### Proposed solution

My proposal would be creating something like this:

```
provider:
  name: aws
  apiKeys:
    - name: ${self:provider.stage}-test-a
      description: Api key test a
      enabled: true
    - name: ${self:provider.stage}-test-b
      description: Api key test b
      enabled: false
   - name: ${self:provider.stage}-test-c
      description: Api key test c
```

If you don't provide an enabled flag, it would be true by default.

Thanks a lot for the great framework you've all made,

Joris

**Comment by pgrzesik** [comment] 2021-01-20 12:05
Hello @JorisPhilipsen, thanks for submitting your request. I believe it would make sense to add such optional flag to `apiKeys`, as currently we're always setting `Enabled: true` in CloudFormation `AWS::ApiGateway::ApiKey` resource. One thing to note, recently, the `apiKey` on `provider` level was deprecated, so it should instead be defined on `provider.apiGateway.apiKeys`. As suggested, the default value should be `true` to maintain the same behavior for people that won't use it explicitly.

We'd be happy to accept a PR :raised_hands:

**Comment by yeukfei02** [comment] 2021-01-21 17:15
@pgrzesik 

which file can change/update this feature? maybe I can help..

**Comment by pgrzesik** [comment] 2021-01-21 17:30
Hey @yeukfei02, that would be awesome :raised_hands: We create the `AWS::ApiGateway::ApiKey` resource here: https://github.com/serverless/serverless/blob/7d2ca04d7f72981c422fb8f9c25ae4699aedffba/lib/plugins/aws/package/compile/events/apiGateway/lib/apiKeys.js#L6 
You will also need to adjust the schema here: https://github.com/serverless/serverless/blob/master/lib/plugins/aws/provider.js#L259 

While writing new tests, please remember that all new tests should be written with `runServerless`

**Comment by beccslee** [comment] 2021-03-17 05:02
Hi @pgrzesik, I'm new to contributing and was wondering if this issue is still relevant? If no one has submitted a PR for it yet, I think I have one to submit for review.

**Comment by pgrzesik** [comment] 2021-03-17 08:10
Hello @beccslee :wave: The issue is still relevant and we'd be more than happy to accept a PR for this one :raised_hands:

**Comment by beccslee** [comment] 2021-03-18 06:02
@pgrzesik I submitted a PR based on the proposed solution and your previous comment for changes in files. I saw the part about using runServerless with new tests, but I happened to modify the existing tests in apiKeys.test.js, as that was mostly where I saw  to the api keys test and it seemed to have been a good fit. Please comment and redirect in review if that is not the case. Thank you!

**Comment by pgrzesik** [comment] 2021-03-18 10:24
Thank you @beccslee :bow: I've responded in PR review - please let me know what do you think. Feel free to reach out if you have any questions, too :100:

**Comment by medikoo** [comment] 2021-12-08 16:40
Addressed in https://github.com/serverless/serverless/pull/9918

**Closed by medikoo** 2021-12-08 16:40 UTC
Labels: good first issue, enhancement, help wanted, cat/aws-event-api-gateway
