### ISSUE TITLE
If a deploymentBucket is set, stack creation fails when creating IAM Roles

### ISSUE THREAD

**Issue by fleeco** [serverless/serverless#2944] opened 2016-12-14 10:43 UTC
# This is a (Bug Report)

## Description

For bug reports:
* What went wrong?

Started using serverless this evening, and wanted to keep my bucket limit down.  It appears that there was a patch to allow passing in a custom bucket, but it doesn't seem to function as expected (Trying to stay well under my 100 bucket limit).  If I don't pass in a deployment bucket, everything works as expected

* What did you expect should have happened?

I expected the deployment bucket to work :)

* What was the config you used?

```
provider:
  name: aws
  runtime: nodejs4.3
  stage: dev
  region: us-east-1
  deploymentBucket: adrizer.builds
```

* What stacktrace or error message from your provider did you see?

```
  Serverless Error ---------------------------------------
 
     Requires capabilities : [CAPABILITY_NAMED_IAM]
 
  Get Support --------------------------------------------
     Docs:          docs.serverless.com
     Bugs:          github.com/serverless/serverless/issues
 
  Your Environment Information -----------------------------
     OS:                 darwin
     Node Version:       5.10.1
     Serverless Version: 1.3.0
 

```

**Comment by fleeco** [comment] 2016-12-14 10:43
Have a fix for this, opening a pull request now.

**Comment by eahefnawy** [comment] 2016-12-19 13:03
@fleeco I wasn't able to reproduce this issue. Is there anything unique/specific about your service?

**Comment by jdchmiel** [comment] 2017-01-03 15:52
I also just began using serverless.  I was able to set a bucket with a dash in the name, but no period, ex: adrizer-builds which might be completely irrelevant, but who knows.  I am using full admin credentials ( but not root account) to play in a sandbox.  Your error looks like it might actually just need more permission than it has ??

**Comment by tgjorgoski** [comment] 2017-01-03 16:01
FWIW I also encountered this issue with an older version of serverless, but it is working now.
Looks that it has been fixed by https://github.com/serverless/serverless/commit/b69790e7661984e0bd49e2909c0f6b2d7d4a2a6b

**Closed** 2017-03-03 03:30 UTC
Labels: kind/bug, status/more-info-needed
