### ISSUE TITLE
serverless deploy gives authentication error (also after renewing aws credentials)

### ISSUE THREAD

**Issue by vincentclaes** [serverless/serverless#5296] opened 2018-09-15 05:36 UTC
**`serverless deploy` cannot authenticate**

- i tried renewing my aws keys
- i tried updating the serverless package

I should contact support with the following reference **VS43B1KGCCRM**

**stacktrace:**

Error: {"errorMessage":"Authentication failed. - Please contact support and provide this identifier to reference this issue -
 VS43B1KGCCRM"}
    at _callee$ (/usr/local/lib/node_modules/serverless/node_modules/@serverless/platform-sdk/src/tenants/listTenants.js:17:1
1)
    at tryCatch (/usr/local/lib/node_modules/serverless/node_modules/regenerator-runtime/runtime.js:65:40)
    at Generator.invoke [as _invoke] (/usr/local/lib/node_modules/serverless/node_modules/regenerator-runtime/runtime.js:303:
22)
    at Generator.prototype.(anonymous function) [as next] (/usr/local/lib/node_modules/serverless/node_modules/regenerator-ru
ntime/runtime.js:117:21)

    at step (/usr/local/lib/node_modules/serverless/node_modules/@serverless/platform-sdk/dist/tenants/listTenants.js:7:191)
    at /usr/local/lib/node_modules/serverless/node_modules/@serverless/platform-sdk/dist/tenants/listTenants.js:7:361
    at <anonymous>
    at process._tickDomainCallback (internal/process/next_tick.js:228:7)
From previous event:
    at variables.populateService.then (/usr/local/lib/node_modules/serverless/lib/Serverless.js:117:24)
    at runCallback (timers.js:794:20)
    at tryOnImmediate (timers.js:752:5)
    at processImmediate [as _immediateCallback] (timers.js:729:5)
From previous event:
    at Serverless.run (/usr/local/lib/node_modules/serverless/lib/Serverless.js:111:74)
    at serverless.init.then (/usr/local/lib/node_modules/serverless/bin/serverless:43:50)
    at <anonymous>

**env**

 Your Environment Information -----------------------------
     OS:                     darwin
     Node Version:           8.11.1
     Serverless Version:     1.31.0

**Comment by vincentclaes** [comment] 2018-09-15 08:46
ok very strange, now it works. I tried again a few hours later and everything worked again. i didn't change anything ...

**Comment by ac360** [comment] 2018-11-19 02:40
I have been getting this on and off consistently for over a month.  It has to do with out Serverless Platform auth service and we'll fix it ASAP.

Serverless Version: 1.33.1

**Comment by b0123498765** [comment] 2019-01-10 11:10
@ac360 any update on this? it's now happening nightly for us and always around this time.

**Comment by pmuens** [comment] 2019-07-08 10:33
Closing this since we've pushed a lot of fixes in the past. Feel free to re-open if this issue is still around.

**Closed by pmuens** 2019-07-08 10:33 UTC
Labels: bug, cat/enterprise

**Comment by asakapab0i** [comment] 2019-08-28 10:57
Please re-open, somehow I'm getting the same error. I'm ff the instruction but still the same.

**Comment by jsphkhan** [comment] 2020-06-09 18:58
This issue still exists.

**Comment by yuklia** [comment] 2020-06-22 10:02
have the same issue:
  Your Environment Information ---------------------------
     Operating System:          darwin
     Node Version:              12.9.0
     Framework Version:         1.73.1
     Plugin Version:            3.6.13
     SDK Version:               2.3.1
     Components Version:        2.30.20

**Comment by rodgeraraujo** [comment] 2020-10-15 21:21
I have the same issue.

```
Error --------------------------------------------------

  Error: {"errorMessage":"Authentication failed. - Please contact support and provide this identifier to reference this issue - 7WHJBZL2SK65"}
      at _callee$ (/usr/local/lib/node_modules/serverless/node_modules/@serverless/platform-sdk/src/utils/checkHttpResponse.js:19:9)
      at tryCatch (/usr/local/lib/node_modules/serverless/node_modules/regenerator-runtime/runtime.js:63:40)
      at Generator.invoke [as _invoke] (/usr/local/lib/node_modules/serverless/node_modules/regenerator-runtime/runtime.js:293:22)
      at Generator.next (/usr/local/lib/node_modules/serverless/node_modules/regenerator-runtime/runtime.js:118:21)
      at step (/usr/local/lib/node_modules/serverless/node_modules/@serverless/platform-sdk/dist/utils/checkHttpResponse.js:7:191)
      at /usr/local/lib/node_modules/serverless/node_modules/@serverless/platform-sdk/dist/utils/checkHttpResponse.js:7:361
      at processTicksAndRejections (internal/process/task_queues.js:93:5)

     For debugging logs, run again after setting the "SLS_DEBUG=*" environment variable.

  Get Support --------------------------------------------
     Docs:          docs.serverless.com
     Bugs:          github.com/serverless/serverless/issues
     Issues:        forum.serverless.com

  Your Environment Information ---------------------------
     Operating System:          darwin
     Node Version:              14.9.0
     Framework Version:         2.3.0
     Plugin Version:            4.0.4
     SDK Version:               2.3.2
     Components Version:        3.2.1
```

**Comment by MaheshManthini** [comment] 2020-11-08 10:42
I have the same issue while invoking function locally as **invoke local -f myFunction -p test.json**. 
  Error: {"errorMessage":"Authentication failed. - Please contact support and provide this identifier to reference this issue - BWL8QNT1M2RR"}

**Comment by Tom5om** [comment] 2020-12-02 10:24
I had the error because I didn't have the serverless access key set, this is what I got from support:

_In order for the headless CI/CD system to work you will need to create an access key in your dashboard account. 
Click the org  menu option on the left hand side, then choose the access keys tab. Go ahead and create a new access key and name it appropriately then make sure to copy the key into your clipboard. 

In your CI/CD system you are using, there should be some way to add a variable that gets exposed as an environment variable to the build container. You want to add the variable SERVERLESS_ACCESS_KEY with the value of the key you just created._

This fixed it for me

**Comment by slarge08** [comment] 2021-04-25 16:44
i have also have this error

**Comment by BG687** [comment] 2021-04-27 17:10
I also have this issue, though one of my deploys in my CI/CD env did go through, the vast majority of them are failing. 

I have SERVERLESS_ACCESS_KEY set

**Comment by zeajuniordev** [comment] 2022-01-21 04:49
Hi there. If you delete the ~/.serverlessrc file and then run serverless login again this problem should be resolved.

**Comment by zele9** [comment] 2024-12-05 18:20
I had the issue and I was stuck for a while, I deleted every .serverless folder i could find on my computer but nothing work. AI couldn't ID the root caused and neither could I find it on Youtube but the solution from Tom5om made sense and it worked to a T.
![Screenshot 2024-12-05 124017](https://github.com/user-attachments/assets/954b2982-97c1-42f9-947a-0bbf9511356b)
