### ISSUE TITLE
Undefined variables being casted to the "undefined" string

### ISSUE THREAD

**Issue by lukejagodzinski** [serverless/serverless#3491] opened 2017-04-19 11:03 UTC
# This is a Bug Report

## Description

* What went wrong?

In the `serverless.yml` file I have defined some environment variables:

```yml
provider:
  name: aws
  runtime: nodejs6.10
  profile: jagi
  environment:
    STAGE: ${opt:stage}
```

In some cases `${opt:stage}` may be `undefined`, for example on localhost when using `serverless-offline`. When it's `undefined` it gets converted to the `"undefined"` string.

* What did you expect should have happened?

I would expect it to be just `undefined`. It's kinda weird to make comparisons like:

```js
if (process.env.STAGE === 'undefined')
```

instead

```js
if (process.env.STAGE === undefined)
```

## Additional Data

* ***Serverless Framework Version you're using***: 1.10.2
* ***Operating System***: MacOS 10.12.4

**Comment by skewart** [comment] 2017-06-25 22:01
Hi, I'm new to the Serverless framework, but really liking it so far, and I thought I'd contribute a little.  This issue seems like it might be a good place to start.      So, per your contributing guide, I just thought I'd drop a note here.   I take it the issue is still relevant?

**Comment by pmuens** [comment] 2017-06-27 07:44
> Hi, I'm new to the Serverless framework, but really liking it so far, and I thought I'd contribute a little. This issue seems like it might be a good place to start. So, per your contributing guide, I just thought I'd drop a note here. I take it the issue is still relevant?

Hey @skewart thank you very much for the kind words! Really appreciate that 😊 👍 

Great to hear that you want to contribute to Serverless! 💪 

---

This is a good issue to start. I only have one question when thinking about this issue.

My concern with changing this is that this won't be language independent anymore, right?

Let's assume we have a Java service where the environment variable is not set. The current implementation would work since it's just a plain string I can check. But how would this work if this is updated to be `undefined`?

Do you have any thoughts around that? Thanks again for reaching out! Great to have you in the community!

**Comment by skewart** [comment] 2017-06-28 01:13
Hi @pmuens  thanks for the warm welcome!

As for your concern about language independence, I was thinking about two different ways to approach this:  

1. Just don't add the key/value pair to the environment object/hash/dictionary if the input from `serverless.yaml` is undefined.   So, from @jagi's example, if `${opt:stage}` evaluated to `undefined` then you simply wouldn't put a `"STAGE"` key in the environment object.    Doing so would mean that `process.env.STAGE === undefined` would be true.   In Python: `os.environ.get("STAGE") is None`.   And in Java: `System.getenv().get("STAGE") == null`.  This makes it really clear that the env var was never set, but it's less immediately clear where the problem is.  New Serverless developers might not be sure whether they messed something up in the yaml file or if the problem was upstream in their local environment.  

2. Go ahead and set the key but make the value an empty string.  Checking if an env var is 'null or empty' is pretty common across languages too.  And I can see how that might be more expected as a developer using Serverless - you know at least something is working, since the key is getting from `serverless.yaml` into the env, but there clearly is a problem with the key, so you'd look at what was being templated into the yaml file.  That said, people would have to check null-or-empty if they wanted to be safe before using an env var.

Overall I'm slightly more in favor of 1) just because it seems more straightforward.  It's a pretty natural thing to think that maybe empty / null / `undefined` values aren't added to the environment. And it requires less work of developers who want to add checks around env vars - just check if it's `undefined`/`None`/`null`.

That said, I am pretty  maybe I'm missing something?   I'm pretty new to the framework.

**Comment by HyperBrain** [comment] 2017-06-28 09:06
I think there is an option 3:

Given that setting environment variables to _undefined_ is most likely a variable resolution error, imo it would be better from a DX perspective if Serverless would end up with an error in case it finds any variable that does not exist (value === undefined). This will prevent coming into situations where questions like 1 and 2 come up at all. These decisions (if null, undefeined or skipping a variable is the right solution to proceed with) cannot be taken by an automated system, as it implies special semantics on the user side. Dictating a user procedure is not really helpful in that case.

**Comment by skewart** [comment] 2017-06-28 17:30
That seems reasonable.    So, just throw an error at build time if an env var wasn't set?    

One concern that comes to mind though is that would make it impossible to deliberately omit an environment variable, no?  And sometimes people do want to pass in an empty or null value to an environment variable, say if there's a default that can optionally be overridden (e.g. use the hardcoded default in staging and override through an env var in prod, or, looking at it again, @jagi's case on this issue, where `${opt:staging}` isn't set when running locally with `serverless-offline`).

Or, maybe I'm misunderstanding option 3?

**Comment by pmuens** [comment] 2017-06-29 07:24
Thanks for working on proposals and all the different options @skewart 👍 Great discussion and great job showing the up- and downsides 🥇!

Thanks @HyperBrain for providing an option 3 👍 

I agree that from a DX perspective it would be really nice if the Framework simply throws an error.

@skewart What are some real world use cases where one wants to omit an environment variable?

**Comment by HyperBrain** [comment] 2017-06-29 08:45
@skewart The `serverless-offline` problem is perfectly solved with the https://github.com/arabold/serverless-export-env plugin (@arabold). We use it for exactly that reason. It sets the env variables for local runs (sls invoke local and offline plugin), so that a local run exactly resembles what happens for a deployed version.

**Comment by skewart** [comment] 2017-06-29 20:56
@pmuens @HyperBrain tbh, I'm not sure if there's a situation where you really would _have_ to let an env var be null.   

Use cases that come to mind maybe some optional parameters for configuring some service - e.g. some query limit or debounce window or even an S3 prefix used to find something.   I'm thinking less about writing a service for myself and more about writing a service that could be cloned and used by other people.   For example, if you had a service that grabbed documents from S3, transformed them somehow, filtered them for ones that met certain criteria, and then notified people about those documents.  You might have adjustable parameters, and also have reasonable defaults so that it would just work right out of the box for most people - e.g. "by default this looks for everything in your bucket prefixed with /input/reports, sends them to the OCR service, looks for the keyword 'urgent' in the results, and emails people on the notification list if there are more than five matching documents.  But you can override the prefix, the target keywords, and the notification threshold if you want."

That said, maybe there's just a different, better way to allow passing in optional arguments to Serverless apps?

Part of where I'm coming from is that one thing that seems super cool about Serverless is that it makes it easy to run short-lived services in the cloud.  Serverless makes it so fast and easy to spin up and tear down infra that you can basically have a little command line app that implements a fairly complex and powerful workflow and then tears it down when you're done.   In the same way that I might write a shell script that does on my local machine I can write one that does things on AWS (or wherever) at a massive scale.   That's incredible!

I realize that compiling scripts for the could is not the typical way of using Serverless, but I do think it's pretty cool and I would be bummed to see it become a little harder.    Of course, even if Serverless didn't allow optional arguments then I could still just wrap invocation in a script that checks for command line args and implements the defaults.   But that's a little clunkier.

All that said, probably nine times out of ten when an env var isn't set the developer meant for it to be set, and throwing an error might save them time.

Maybe it's something that would be better surfaced with a linter?

This is getting to be a pretty long comment.    So I'll wrap it up.  I'm happy to implement throwing an error if you guys think that's best.    Just wanted to really think through the different tradeoffs.

**Comment by HyperBrain** [comment] 2017-06-29 21:05
@skewart I would differentiate between `null` und `undefined`. For me `null` is a valid variable value, whereas `undefined` is not. I would throw the error if a variable's value is `undefined`, not `null`.

So it is still possible to set vars to `null` if you need to.

BTW: Great comment 🙌 . I think using `null` as explicit value would enable your use case, and support the error on `undefined` var values at the same time. What do you think?

**Comment by skewart** [comment] 2017-06-30 04:48
@HyperBrain thanks!    So, you're suggesting that `${opt:example}` would resolve to `null` if `--example value` was not one of the command line args?   (And the same thing for `${env:example}` for environment variables.)   That would address the use cases I was thinking perfectly.  Or is there some other way to cause omitted args and variables to be interpreted as `null` as opposed to `undefined`?

Just to be super clear, I was thinking of a situation when you would want to have the option of not setting a bunch of arguments or variables.   I put together a tiny example service here:  https://github.com/skewart/foo-service to make things more concrete.    There is a default "foo path" of `"data/foo"`, which can be overridden with the command line argument `--foo-path`.      I want to be able to just do `sls invoke -f hello` if I'm happy with using `data/foo` for the foo path, but also be able to do `sls invoke -f hello --foo-path some/other/place/to/find/foos` if I want to use a different value.   (And, obviously, the current status quo is that https://github.com/skewart/foo-service/blob/master/handler.js#L7 won't work because `process.env.FOO_PATH` will never be falsey, since it will be set to the string `"undefined"` if `--foo-path` was not given when invoking or deploying the function.)

**Comment by skewart** [comment] 2017-06-30 06:24
Whelp.  I feel a little silly.  Just realized that you can do the whole overwrite thing with custom YAML properties - for example:

```yaml
custom:
  foo_path: input/bar

functions:
  hello:
    handler: handler.hello
    environment:
     FOO_PATH: ${opt:foo-path, env:FOO_PATH, self:custom.foo_path}
```

That makes my comment above a non-issue.   You can just as easily set defaults in `serverless.yaml` as doing it in your function code.   I suppose there _might_ be some situation where you'd want to dynamically figure out a default, but that seems like a pretty extreme edge case, and I can't think of any actual scenarios.

So, given all that, throwing an error if a variable value resolves to `undefined` seems totally reasonable.

**Comment by pmuens** [comment] 2017-06-30 15:14
Thanks for the great discussion guys! 👍 🙌 

Really great thinking and insights into different mindsets and use cases here! Great read!

In conclusion I agree with @HyperBrain that `null` is a valid variable whereas `undefined` is not.

That's why I agree with @skewart that we should just throw an error if a value is `undefined`.

**Comment by skewart** [comment] 2017-06-30 22:45
Sounds great.      

Just to recap, if you explicitly set a value to `null` in your `serverless.yml` then the framework won't throw an error at build time.  However, if you simply omit a value, causing the `${}` variable to resolve to `undefined`, then the framework _will_ throw an error - as opposed to just the warning that it currently logs today.

I think that gives strong feedback to users that something is wrong, but it also does allow enough flexibility to handle any edge cases where for some reason you _do_ want to have a default null env var.

**Comment by pmuens** [comment] 2017-07-02 14:05
> Just to recap, if you explicitly set a value to null in your serverless.yml then the framework won't throw an error at build time. However, if you simply omit a value, causing the ${} variable to resolve to undefined, then the framework will throw an error - as opposed to just the warning that it currently logs today.

> I think that gives strong feedback to users that something is wrong, but it also does allow enough flexibility to handle any edge cases where for some reason you do want to have a default null env var.

@skewart jep, that's exactly how I think about this as well 👍 I like the solution since it's rather simple and enforces a stricter use of Serverless Varaibles.

**Comment by pmuens** [comment] 2019-02-07 11:05
Closing since changing this behavior would result in a breaking change.

We'll re-visit this when working on `v2`.

**Closed by pmuens** 2019-02-07 11:05 UTC
Labels: bug, good first issue
