### ISSUE TITLE
Broken linter

### ISSUE THREAD

**Issue by pmuens** [serverless/serverless#2187] opened 2016-09-22 13:18 UTC
# This is a Bug Report

## Description

Seems like the linter related packages are not working anymore. You can see it in this build: https://travis-ci.org/serverless/serverless/jobs/161901985#L1805

I'm facing the same on my local machine...

**Comment by dougmoscrop** [comment] 2016-09-24 21:11
No, these are legitimate linting failures. It says missing semicolon, and I look at the commit that triggered the build and it's missing a semicolon..

**Comment by dougmoscrop** [comment] 2016-09-24 21:13
(This should be closed, not a bug - read the console output of npm run lint, it gives clear filenames, line numbers and what the issue is)

**Comment by andymac4182** [comment] 2016-09-25 12:52
@dougmoscrop He is referring to the NPM errors that start at line 1805. These shouldn't be there. When linting fails it throws those errors.

**Comment by dougmoscrop** [comment] 2016-09-25 13:31
Yes they should.. it's the difference between

```
npm install -g eslint
eslint .
```
(Which is running eslint directly because global node module bin is in your path)

and

```
npm install eslint
(add script "lint: eslint ." to package json)
npm run lint
```
(Which is npm running a script where local node module bin is put in to your path.)


When any npm script execution returns a nonzero status code (or linting failed) npm prints that debug info.

**Comment by andymac4182** [comment] 2016-09-25 21:04
@dougmoscrop You can do something like https://github.com/eslint/eslint/issues/2409#issuecomment-103768546 to stop it throwing the npm errors 😄

**Comment by dougmoscrop** [comment] 2016-09-25 22:05
It's not... "throwing errors" though, it's telling you the command failed -
and the command DID fail. That hack just conceals the return code of the
command. That means it won't fail CI builds or stop command chains.

The verbose logs seem to bother people so it is being looked at: (
https://github.com/npm/npm/issues/8821
https://github.com/npm/npm/issues/8821)

So if you implement any return code hacks I suggest changing CI not to rely
on npm run lint.

**Comment by dougmoscrop** [comment] 2016-09-25 22:16
Also I use 'posttest' to lint my code (so just always npm test) and it does
not spit out this extra info. If you're ok with always running lint after
test (I think it's better than pre) then it would "fix" this.

You could keep the lint command with the hack so people who just want to
see listing errors can call it. CI would not call lint directly anymore.

**Comment by flomotlik** [comment] 2016-09-27 10:49
Ok so it sounds like we don't really have anything actionable here, this is just "npm being npm". I personally prefer to keep the different CI commands separate and then actually have CI run them together, so people can be more specific what exactly they want to run (e.g. only tests without linters). So I'm closing. Unless I got something wrong here let me know and we can reopen.

**Closed by flomotlik** 2016-09-27 10:49 UTC
Labels: bug
