### ISSUE TITLE
Error provisioning Usage: API Stage not found: 63zybslnqk:demo.

### ISSUE THREAD

**Issue by sime** [serverless/serverless#2831] opened 2016-11-30 15:38 UTC
# This is a Bug Report

## Description
I hope to deploy and remove a stack as a part of our CI environment. The stack includes an Api Gateway with a Usage Plan. Creating the Api Gateway and Usage Plan together fails. If I break up the process over two deploys and firstly comment out the Cloudformation directive specific to Usage Plan the creation of the stack is successful. Following that I remove the commented Usage Plan configuration and deploy again, the deployment works with the included UsagePlan.

The workaround of multiple deployments for new a stack is not optimal.

* What went wrong?
Deploying a brand new stack with API Gateway and a Usage Plan fails.

* What did you expect should have happened?
For the CloudFormation to honor the UsagePlan directive

* What was the config you used?
```yaml
service: usage-plan-fail

provider:
  name: aws
  runtime: nodejs4.3
  stage: demo

functions:
  hello:
    handler: handler.hello
    events:
      - http:
          path: usage
          method: get
          private: true

resources:
  Resources:
    UsagePlan:
      Type: AWS::ApiGateway::UsagePlan
      Properties:
        ApiStages:
        - ApiId:
            Ref: "ApiGatewayRestApi"
          Stage: ${self:provider.stage}
        Description: ${self:provider.stage} usage plan
        UsagePlanName: "${self:service}-${self:provider.stage}"
```
* What stacktrace or error message from your provider did you see?
```
CloudFormation - CREATE_FAILED - AWS::ApiGateway::UsagePlan - UsagePlan
```

Similar or dependent issues:
* #2539

## Additional Data

* ***Serverless Framework Version you're using***:
1.2.1
* ***Operating System***:
OS X
* ***Stack Trace***:
```bash
$ sls deploy -v
Serverless: Creating Stack...
Serverless: Checking Stack create progress...
CloudFormation - CREATE_IN_PROGRESS - AWS::CloudFormation::Stack - usage-plan-fail-demo
CloudFormation - CREATE_IN_PROGRESS - AWS::S3::Bucket - ServerlessDeploymentBucket
CloudFormation - CREATE_IN_PROGRESS - AWS::S3::Bucket - ServerlessDeploymentBucket
CloudFormation - CREATE_COMPLETE - AWS::S3::Bucket - ServerlessDeploymentBucket
CloudFormation - CREATE_COMPLETE - AWS::CloudFormation::Stack - usage-plan-fail-demo
Serverless: Stack create finished...
Serverless: Packaging service...
Serverless: Uploading CloudFormation file to S3...
Serverless: Uploading service .zip file to S3 (733 B)...
Serverless: Updating Stack...
Serverless: Checking Stack update progress...
CloudFormation - UPDATE_IN_PROGRESS - AWS::CloudFormation::Stack - usage-plan-fail-demo
CloudFormation - CREATE_IN_PROGRESS - AWS::ApiGateway::RestApi - ApiGatewayRestApi
CloudFormation - CREATE_IN_PROGRESS - AWS::IAM::Role - IamRoleLambdaExecution
CloudFormation - CREATE_IN_PROGRESS - AWS::IAM::Role - IamRoleLambdaExecution
CloudFormation - CREATE_IN_PROGRESS - AWS::ApiGateway::RestApi - ApiGatewayRestApi
CloudFormation - CREATE_COMPLETE - AWS::ApiGateway::RestApi - ApiGatewayRestApi
CloudFormation - CREATE_IN_PROGRESS - AWS::ApiGateway::UsagePlan - UsagePlan
CloudFormation - CREATE_FAILED - AWS::ApiGateway::UsagePlan - UsagePlan
CloudFormation - CREATE_IN_PROGRESS - AWS::ApiGateway::Resource - ApiGatewayResourceUsage
CloudFormation - CREATE_IN_PROGRESS - AWS::ApiGateway::Resource - ApiGatewayResourceUsage
CloudFormation - CREATE_COMPLETE - AWS::ApiGateway::Resource - ApiGatewayResourceUsage
CloudFormation - CREATE_FAILED - AWS::IAM::Role - IamRoleLambdaExecution
CloudFormation - UPDATE_ROLLBACK_IN_PROGRESS - AWS::CloudFormation::Stack - usage-plan-fail-demo
CloudFormation - UPDATE_ROLLBACK_COMPLETE_CLEANUP_IN_PROGRESS - AWS::CloudFormation::Stack - usage-plan-fail-demo
CloudFormation - DELETE_IN_PROGRESS - AWS::ApiGateway::Resource - ApiGatewayResourceUsage
CloudFormation - DELETE_COMPLETE - AWS::ApiGateway::UsagePlan - UsagePlan
CloudFormation - DELETE_COMPLETE - AWS::ApiGateway::Resource - ApiGatewayResourceUsage
CloudFormation - DELETE_IN_PROGRESS - AWS::IAM::Role - IamRoleLambdaExecution
CloudFormation - DELETE_IN_PROGRESS - AWS::ApiGateway::RestApi - ApiGatewayRestApi
CloudFormation - DELETE_COMPLETE - AWS::IAM::Role - IamRoleLambdaExecution
CloudFormation - DELETE_COMPLETE - AWS::ApiGateway::RestApi - ApiGatewayRestApi
CloudFormation - UPDATE_ROLLBACK_COMPLETE - AWS::CloudFormation::Stack - usage-plan-fail-demo
Serverless: Deployment failed!

  Serverless Error ---------------------------------------

     An error occurred while provisioning your stack: UsagePlan
     - API Stage not found: 63zybslnqk:demo.

  Get Support --------------------------------------------
     Docs:          docs.serverless.com
     Bugs:          github.com/serverless/serverless/issues

  Your Environment Information -----------------------------
     OS:                 darwin
     Node Version:       6.7.0
     Serverless Version: 1.2.1

```
* ***Provider Error messages***:
```
     An error occurred while provisioning your stack: UsagePlan
     - API Stage not found: 63zybslnqk:demo.
```

**Comment by sime** [comment] 2016-12-01 11:22
If I remove the following block, the deployment is successful:
```yml
         ApiStages:
         - ApiId:
             Ref: "ApiGatewayRestApi"
           Stage: ${self:custom.env.stage}
```

Which will successfully create a usage plan, but no associate it with any stages.

**Comment by pmuens** [comment] 2016-12-06 10:42
Thanks for reporting @sime 

Looks like a kind of race condition to me.
Could you add a `DependsOn` on the REST API to the `UsagePlan` so that CloudFormation knows that the REST API should be in place before creating the `UsagePlan`.

**Comment by sime** [comment] 2016-12-06 11:21
@pmuens I add a `DependsOn` to `UsagePlan` and got the same problem.

```yaml
resources:
  Resources:
    UsagePlan:
      Type: AWS::ApiGateway::UsagePlan
      DependsOn:
        - "ApiGatewayRestApi"
      Properties:
        ApiStages:
        - ApiId:
            Ref: "ApiGatewayRestApi"
          Stage: ${self:provider.stage}
        Description: ${self:provider.stage} usage plan
        UsagePlanName: "${self:service}-${self:provider.stage}"

```

**Comment by pmuens** [comment] 2016-12-06 12:50
Hmm.

Can you take a look at the stage of your api? Is the name of this stage `demo`?

**Comment by sime** [comment] 2016-12-06 13:21
@pmuens This is a new stack, so the stage should be newly created.

If I remove the `ApiStages` block, the "demo" stage is created.

**Comment by pmuens** [comment] 2016-12-07 09:48
I reproduced this one today and the issue is that the stage is not in placed when the usage plan creation kicks in.

The stage is defined and created in the `AWS::ApiGateway::Deployment` template which got a random id so we cannot reference it through Custom Resources 😞 

I think that this PR https://github.com/serverless/serverless/pull/2234 goes into the same direction / problem space.

**Comment by sime** [comment] 2016-12-15 09:59
I've had a plugin to get around this, if there is interest I can package it.

Used in combination with the above mentioned `serverless.yml` with the following addition:
```yaml
plugins:
  - usage-plan-injection-plugin
```
The plugin lives in `.serverless_plugins/usage-plan-injection-plugin.js`:
```js
'use strict';

class UsagePlanInjectionPlugin {
  constructor(serverless, options) {
    this.serverless = serverless;
    this.options = options;
    this.provider = 'aws';

    if (this.options.noDeploy) {
      this.hooks = {
        'before:deploy:deploy': this.beforeDeployDeploy.bind(this),
      };
    } else {
      this.hooks = {
        'before:deploy:deploy': this.beforeDeployDeploy.bind(this),
        'before:remove:remove': this.beforeRemoveRemove.bind(this),
        'after:deploy:deploy': this.afterDeployDeploy.bind(this),
      };
    }
  }

  beforeDeployDeploy() {
    let resources = this.serverless.service.provider.compiledCloudFormationTemplate.Resources;
    let resourceKeys = Object.keys(resources);
    let apiGatewayDeployment;
    resourceKeys.forEach(resource => {
      if (resource.match(/ApiGatewayDeployment/)) {
        apiGatewayDeployment = resource;
      }
    });

    if (apiGatewayDeployment === undefined) {
      return;
    }

    if (resources['ApiGatewayRestApi'] === undefined) {
      return;
    }

    const userResources = this.serverless.service.resources.Resources;
    Object.keys(userResources).forEach(userResource => {
      if (userResources[userResource].Type !== 'AWS::ApiGateway::UsagePlan') {
        return;
      }

      if (this.serverless.service.resources.Resources[userResource].DependsOn === undefined) {
        return this.serverless.service.resources.Resources[userResource].DependsOn = [apiGatewayDeployment];
      }

      this.serverless.service.resources.Resources[userResource].DependsOn.push(apiGatewayDeployment);
    });
  }

  beforeRemoveRemove() {
    const apiGateway = new this.serverless.providers.aws.sdk.APIGateway(this.serverless.providers.aws.getCredentials());
    const cloudFormation = new this.serverless.providers.aws.sdk.CloudFormation(this.serverless.providers.aws.getCredentials());

    const stackName = this.serverless.providers.aws.naming.getStackName();

    let restApiId;
    let usagePlanId;
    let apiKeysIds = [];
    const stageName = this.options.stage || this.serverless.service.provider.stage;

    return cloudFormation.listStackResources({StackName: stackName}).promise()
      .then((resources) => {
        resources.StackResourceSummaries.forEach(resource => {
          if (resource.LogicalResourceId === "ApiGatewayRestApi") {
            restApiId = resource.PhysicalResourceId;
          }

          if (resource.ResourceType === "AWS::ApiGateway::UsagePlan") {
            usagePlanId = resource.PhysicalResourceId;
          }

          if (resource.ResourceType === "AWS::ApiGateway::ApiKey") {
            apiKeysIds.push(resource.PhysicalResourceId);
          }
        });
      })
      .then(() => {
        if (apiKeysIds.length > 0) {
          console.log(usagePlanId);
          const params = {
            keyId: apiKeysIds[0], // Only supporting one API Key.
          };

          return apiGateway.getUsagePlans(params).promise()
            .then(data => {
              let usagePlanExists = false;
              data.items.forEach(item => {
                if (item.id === usagePlanId) {
                  usagePlanExists = true;
                }
              });

              if (usagePlanExists) {
                return apiGateway.deleteUsagePlanKey({usagePlanId: usagePlanId, keyId: apiKeysIds[0]}).promise();
              }
            });
        }
      })
      .then(() => {
        return apiGateway.deleteStage({restApiId: restApiId, stageName: stageName}).promise();
      })
      .then(() => {
        return apiGateway.deleteUsagePlan({ usagePlanId: usagePlanId }).promise();
      });
  }

  afterDeployDeploy() {
    const apiGateway = new this.serverless.providers.aws.sdk.APIGateway(this.serverless.providers.aws.getCredentials());
    const cloudFormation = new this.serverless.providers.aws.sdk.CloudFormation(this.serverless.providers.aws.getCredentials());
    const stackName = this.serverless.providers.aws.naming.getStackName();
    let usagePlanId;
    let apiKeysIds = [];
    return cloudFormation.listStackResources({StackName: stackName}).promise()
      .then((resources) => {
        resources.StackResourceSummaries.forEach(resource => {
          if (resource.ResourceType === "AWS::ApiGateway::UsagePlan") {
            usagePlanId = resource.PhysicalResourceId;
          }

          if (resource.ResourceType === "AWS::ApiGateway::ApiKey") {
            apiKeysIds.push(resource.PhysicalResourceId);
          }
        });
      })
      .then(() => {
        const params = {
          keyId: apiKeysIds[0], // Only supporting one API Key.
        };

        // Would prefer to use getUsagePlanKey but it doesn't behave as expected.
        return apiGateway.getUsagePlans(params).promise();
      })
      .then(data => {
        let createUsagePlanKey = true;
        data.items.forEach(item => {
          if (item.id === usagePlanId) {
            createUsagePlanKey = false;
          }
        });

        if (!createUsagePlanKey) {
          return;
        }

        const params = {
          keyId: apiKeysIds[0],
          keyType: 'API_KEY',
          usagePlanId: usagePlanId,
        };
        return apiGateway.createUsagePlanKey(params).promise();
      })
      .catch(err => {
        console.error("APIGateway error: ", err);
      });
  }
}

module.exports = UsagePlanInjectionPlugin;
```

**Comment by nsimone** [comment] 2017-05-08 14:50
@sime Your plugin works for us as well; packaging it would be great.

**Comment by pmuens** [comment] 2017-05-19 14:39
Unfortunately this is not possible right now, but we track the progress on usage plan in other issues such as #3182.

Feel free to use the described plugin approach above 🔝 

Closing to keep the issue count low.

**Closed by pmuens** 2017-05-19 14:39 UTC
Labels: kind/bug, stage/accepted

**Comment by mmroden** [comment] 2017-07-28 21:16
You closed an issue to keep the issue count low, despite the fact that this is still an image?  Maybe better to actually solve the problem to close the image rather than artificially deflate your issue count.

**Comment by pmuens** [comment] 2017-07-29 06:37
> You closed an issue to keep the issue count low, despite the fact that this is still an issue? Maybe better to actually solve the problem to close the issue rather than artificially deflate your issue count.

Hey @mmroden thanks for commenting 👍

Usage Plan support for the Serverless Framework was added recently. The issue for being able to depend on an `ApiGateway::Deployment` (the root cause for the problem here) can be found here: https://github.com/serverless/serverless/issues/2233

**Comment by skylarmb** [comment] 2018-02-12 21:36
@sime thanks for posting your plugin code. Would be cool to package it up! Your plugin got us through the "Checking Stack update progress" phase but still errors out before everything finishes. This seems to be far enough that the stack doesn't automatically roll back, which is what we needed. After the initial deploy using your plugin we removed the plugin and deployed normally and everything worked fine from there on out. Here is the error


```
APIGateway error:  { MissingRequiredParameter: Missing required key 'usagePlanId' in params
    at ParamValidator.fail (/usr/local/lib/node_modules/serverless/node_modules/aws-sdk/lib/param_validator.js:50:37)
    at ParamValidator.validateStructure (/usr/local/lib/node_modules/serverless/node_modules/aws-sdk/lib/param_validator.js:61:14)
    at ParamValidator.validateMember (/usr/local/lib/node_modules/serverless/node_modules/aws-sdk/lib/param_validator.js:88:21)
    at ParamValidator.validate (/usr/local/lib/node_modules/serverless/node_modules/aws-sdk/lib/param_validator.js:34:10)
    at Request.VALIDATE_PARAMETERS (/usr/local/lib/node_modules/serverless/node_modules/aws-sdk/lib/event_listeners.js:125:42)
    at Request.callListeners (/usr/local/lib/node_modules/serverless/node_modules/aws-sdk/lib/sequential_executor.js:105:20)
    at callNextListener (/usr/local/lib/node_modules/serverless/node_modules/aws-sdk/lib/sequential_executor.js:95:12)
    at /usr/local/lib/node_modules/serverless/node_modules/aws-sdk/lib/event_listeners.js:85:9
    at finish (/usr/local/lib/node_modules/serverless/node_modules/aws-sdk/lib/config.js:320:7)
    at /usr/local/lib/node_modules/serverless/node_modules/aws-sdk/lib/config.js:338:9
    at SharedIniFileCredentials.get (/usr/local/lib/node_modules/serverless/node_modules/aws-sdk/lib/credentials.js:126:7)
    at getAsyncCredentials (/usr/local/lib/node_modules/serverless/node_modules/aws-sdk/lib/config.js:332:24)
    at Config.getCredentials (/usr/local/lib/node_modules/serverless/node_modules/aws-sdk/lib/config.js:352:9)
    at Request.VALIDATE_CREDENTIALS (/usr/local/lib/node_modules/serverless/node_modules/aws-sdk/lib/event_listeners.js:80:26)
    at Request.callListeners (/usr/local/lib/node_modules/serverless/node_modules/aws-sdk/lib/sequential_executor.js:101:18)
    at Request.emit (/usr/local/lib/node_modules/serverless/node_modules/aws-sdk/lib/sequential_executor.js:77:10)
    at Request.emit (/usr/local/lib/node_modules/serverless/node_modules/aws-sdk/lib/request.js:683:14)
    at Request.transition (/usr/local/lib/node_modules/serverless/node_modules/aws-sdk/lib/request.js:22:10)
    at AcceptorStateMachine.runTo (/usr/local/lib/node_modules/serverless/node_modules/aws-sdk/lib/state_machine.js:14:12)
    at Request.runTo (/usr/local/lib/node_modules/serverless/node_modules/aws-sdk/lib/request.js:403:15)
    at /usr/local/lib/node_modules/serverless/node_modules/aws-sdk/lib/request.js:791:12
    at new Promise (<anonymous>)
    at Request.promise (/usr/local/lib/node_modules/serverless/node_modules/aws-sdk/lib/request.js:777:12)
    at cloudFormation.listStackResources.promise.then.then.then.data ([...]/api/.serverless_plugins/usage-plan-injection-plugin.js:154:54)
    at <anonymous>
    at process._tickDomainCallback (internal/process/next_tick.js:228:7)
  message: 'Missing required key \'usagePlanId\' in params',
  code: 'MissingRequiredParameter',
  time: 2018-02-12T21:25:52.846Z }
```

**Comment by sime** [comment] 2018-02-12 23:16
@skylarmb Not actively maintaining a serverless app with this plugin anymore. So not likely going to package it anytime soon.

**Comment by jaylord-github** [comment] 2018-03-20 09:52
If you guys still experiencing this error, here is my solution:

- Create user in the AWS IAM. Create a group of that user and assign full admin access.
- Get the access key id and secret key under the 'Security Credentials' tab of the user in AWS IAM.
    Option 1: If deploying using CircleCI:
		  * Set the AWS_ACCESS_KEY_ID and AWS_SECRET_ACCESS_KEY in the 'Environment Variables' in CircleCI for that service you like to deploy.
    Option 2: If deploying using terminal on your local machine: 
                  * Make a copy also the key id and secret key to your /.aws credentials file on local PC.
                        `[default]
aws_access_key_id = *****************P7A
aws_secret_access_key = *********************************************bYM`

**Comment by agouz** [comment] 2019-02-16 01:38
Adding both the stage and plan to your resources + dependsOn solved for me


> 

> `resources:
  Resources:
    onlyBody: 
      Type: "AWS::ApiGateway::RequestValidator" 
      Properties: 
        Name: 'only-body' 
        RestApiId: 
          Ref: ApiGatewayRestApi 
        ValidateRequestBody: true 
        ValidateRequestParameters: false
    ApiGatewayStage:
      Type: AWS::ApiGateway::Stage
      Properties:
        RestApiId:
          Ref: ApiGatewayRestApi
        MethodSettings:
          - DataTraceEnabled: true
            HttpMethod: "*"
            LoggingLevel: ERROR
            ResourcePath: "/*"
            MetricsEnabled: true
    UsagePlan:
      Type: AWS::ApiGateway::UsagePlan
      DependsOn:
        - "ApiGatewayStage"
      Properties:
        ApiStages:
        - ApiId:
            Ref: "ApiGatewayRestApi"
          Stage: ${self:provider.stage}
        Description: ${self:provider.stage} usage plan
        UsagePlanName: "${self:service}-${self:provider.stage}"`

**Comment by fschroder** [comment] 2019-03-07 02:33
As mentioned by @agouz this helps, however when I tried it serverless was generating 2 usage plans:

```
"UsagePlan": {
  "Type": "AWS::ApiGateway::UsagePlan",
    "DependsOn": [
      "ApiGatewayStage"
    ],
  ...

"ApiGatewayUsagePlan": {
  "Type": "AWS::ApiGateway::UsagePlan",
  "DependsOn": "ApiGatewayDeployment1551923774977",
  ...
```

The 2nd plan was unexpected and was always failing as it entered on a race condition with the APIStage. For me the solution was to rename my UsagePlan from "UsagePlan" to "ApiGatewayUsagePlan". This way serverless generated only one and with the right DependsOn.
The only way to find about this was to check the generated template. 

serverless v1.38.0

**Comment by hdpa** [comment] 2019-09-09 22:41
@sime Can you please forward me the .yml sample with plugins? it's giving me an error "Invalid template property or properties [plugins]"
