### ISSUE TITLE
Mac: aws-go-mod deploy failed Uploaded file must be a non-empty zip

### ISSUE THREAD

**Issue by ifanchu** [serverless/serverless#8772] opened 2021-01-16 08:02 UTC
On my local Mac, I was trying the aws-go-mod template and `sls deploy` failed with 

```
  An error occurred: HelloLambdaFunction - Uploaded file must be a non-empty zip (Service: AWSLambdaInternal; Status Code: 400; Error Code: InvalidParameterValueException; Request ID: a9d772b9-c1d9-4e74-a6ab-6be5af6feb5e; Proxy: null).
```

<details>
<summary><code>serverless.yml</code></summary>

I did not make any change to serverless.yml out of the template.

</details>

<details>
<summary><b><code>⚠️⚠️ REPLACE WITH FULL COMMAND NAME</code> output</b></summary>

```
> serverless config credentials --provider provider --key key --secret secret

> sls create --template aws-go-mod --path myservice
> cd myservice
> make build
> make deploy
  Serverless Error ---------------------------------------

  An error occurred: HelloLambdaFunction - Uploaded file must be a non-empty zip (Service: AWSLambdaInternal; Status Code: 400; Error Code: InvalidParameterValueException; Request ID: 5125656a-c0d3-446d-badd-bca2f7063331; Proxy: null).
```

</details>

<b>Installed version</b> 

```
╰─➤  sls --version
Framework Core: 2.19.0
Plugin: 4.4.2
SDK: 2.3.2
Components: 3.4.7
```

I also tried with `sls package` first then `sls deploy --package`, also same issue. 

```
╰─➤  sls package --package ~/Downloads/test
Serverless: Packaging service...
Serverless: Excluding development dependencies...
╰─➤  ls -ltrh ~/Downloads/test                                                                                                                                       1 ↵
total 12512
-rw-r--r--  1 ifanchu  staff   2.0K Jan 15 23:57 cloudformation-template-create-stack.json
-rw-r--r--  1 ifanchu  staff    11K Jan 15 23:57 cloudformation-template-update-stack.json
-rw-r--r--  1 ifanchu  staff   6.1M Jan 15 23:57 myservice.zip
-rw-r--r--  1 ifanchu  staff    19K Jan 15 23:57 serverless-state.json
╰─➤  sls deploy --package ~/Downloads/test

Serverless Error ---------------------------------------

  An error occurred: WorldLambdaFunction - Uploaded file must be a non-empty zip (Service: AWSLambdaInternal; Status Code: 400; Error Code: InvalidParameterValueException; Request ID: 2f191f1a-2582-4d7d-8c85-1705f2384778; Proxy: null).
```

Am I doing anything wrong with the template? 

AWS Setting

```
╰─➤  cat ~/.aws/config
[default]
region = us-west-2
```

**Comment by pgrzesik** [comment] 2021-01-16 10:05
Hello @ifanchu, thanks for reporting. Did you first build your `go` binary? Serverless Framework won't run the `go` build step and if you don't build it first, there will be nothing to be packed into zip artifact.

**Comment by isbkch** [comment] 2021-01-16 15:39
I have the same issue since yesterday as well. I've spent the evening trying to figure it out thinking it was a problem on my laptop. I've rebooted countless times, removed and installed Serverless again countless times,  I've checked my firewall rules in case it was preventing file upload but that was not it. I also checked the uploaded zip into s3, the files were there but were all empty with 0 bytes size..

I'm actually glad I'm not the only one having this issue.

My function is built with NodeJs. I'm on Mac Os Big Sur running latest everything (node, npm, docker, Brew...) and pushing to us-east-1

**Comment by x00159373** [comment] 2021-01-16 15:55
I'm having the exact same issue today with code that was working perfectly before.  I'm working with serverless 2.19.0 but I've also downgraded to 2.18.0 

I'm testing with a Python lambda function, even a simple hello world function won't deploy with the following error

Uploaded file must be a non-empty zip (Service: AWSLambdaInternal; Status Code: 400; Error Code: InvalidParameterValueException;

**Comment by ifanchu** [comment] 2021-01-16 18:20
> Hello @ifanchu, thanks for reporting. Did you first build your `go` binary? Serverless Framework won't run the `go` build step and if you don't build it first, there will be nothing to be packed into zip artifact.

yes I did, and as I mentioned, I tried `sls package` and size of myservice is

```
-rw-r--r--  1 ifanchu  staff   6.1M Jan 15 23:57 myservice.zip
```

Then I tried to unzip it

```
> unzip myservice.zip
Archive:  myservice.zip
  inflating: bin/hello                bad CRC 27b2eaa3  (should be 00000000)
  inflating: bin/world                bad CRC dd4840b8  (should be 00000000)

> ls -ltrh bin
total 28464
-rwxr-xr-x  1 ifanchu  staff   6.9M Jan  1  1980 world
-rwxr-xr-x  1 ifanchu  staff   6.9M Jan  1  1980 hello
```

Looks a little weird to me...

**Comment by lxwang42** [comment] 2021-01-16 21:32
i'm having the same issue, tested on fresh osx, debian with nodejs helloworld example. got the same error
  Your Environment Information ---------------------------
     Operating System:          darwin
     Node Version:              15.6.0
     Framework Version:         2.19.0
     Plugin Version:            4.4.2
     SDK Version:               2.3.2
     Components Version:        3.4.7

service: helloworld
frameworkVersion: '2'

provider:
  name: aws
  runtime: nodejs12.x
  lambdaHashingVersion: 20201221

functions:
  hello:
    handler: handler.hello

**Comment by ifanchu** [comment] 2021-01-16 21:35
> Hello @ifanchu, thanks for reporting. Did you first build your `go` binary? Serverless Framework won't run the `go` build step and if you don't build it first, there will be nothing to be packed into zip artifact.

I ran `make build` which builds `bin/hello` and `bin/world`.

**Comment by pgrzesik** [comment] 2021-01-17 09:36
Hello everyone - thanks a lot for reporting more details about the issue. I've had a hard time reproducing it, but seeing output from @lxwang42 I've noticed use of the latest version of node `v15.6.0` and in fact, I was able to reproduce the issue on both framework versions `v2.18.0` and `v2.19.0`. Surprisingly, when going back to node `v14` or even to `v15.5.0`, the problem does not exist (or at least I wasn't able to reproduce). It seems like the packaged `zip`s are broken as when even trying to unzip them locally they error out with `bad CRC` as was also shown by @ifanchu. 

The question to everyone reporting - are you all on node `v15.6.0` or is there anyone that experiences the same issue with different node versions? I tried `v10`, `v12`, `v14`, `v15.5.0` and could not reproduce. For now, I'll continue the investigation under the assumption that issue is present only on the `v15.6.0` of node.

Thanks everyone for detailed reports :bow:

**Comment by ifanchu** [comment] 2021-01-17 10:25
I am on `v15.6.0`

```
╰─➤  node --version
v15.6.0
```

I downgraded to 

```
╰─➤  node -v
v14.15.4
╰─➤  npm -v
6.14.10
```
And it is working good now.

**Comment by Nyholm** [comment] 2021-01-17 11:19
I created a small [reproducer repository](https://github.com/Nyholm/serverless-issue-8772). See the [Github action](https://github.com/Nyholm/serverless-issue-8772/blob/master/.github/workflows/deploy.yml) and the [latest output](https://github.com/Nyholm/serverless-issue-8772/runs/1716588753).

**Comment by Nyholm** [comment] 2021-01-17 11:32
I've tested with Node 15.5 and it is working. It seams to be broken only on 15.6.

**Comment by x00159373** [comment] 2021-01-17 13:07
I can also confirm I was running Node v15.6.0 and when I rolled back to Node v14.15.1 all is working fine so it seems to be Node related

**Comment by isbkch** [comment] 2021-01-17 15:31
Confirmed working with node@14

**Comment by pgrzesik** [comment] 2021-01-17 19:41
Thanks everyone for checking out and confirming that it's in fact related to node `v15.6.0`. I've managed to pinpoint the issue to the library that we're using to create zip archives - https://github.com/archiverjs/node-archiver/issues/491. I'll be tracking the issue and make sure to let everyone here know as soon as we have a resolution. :100:

**Comment by fkimani** [comment] 2021-01-19 17:39
> I can also confirm I was running Node v15.6.0 and when I rolled back to Node v14.15.1 all is working fine so it seems to be Node related

I've had to roll back as well from v15.6.0 and v14.15.1 worked.

**Comment by thuringia** [comment] 2021-01-21 12:58
@pgrzesik I can confirm this is working on node `v15.5.x` as well.

I don't know what the timeline for the fix upstream is, it might not be a bad idea to set `engines` via a hotfix for now.
Thanks for the heads-up earlier!

**Comment by pgrzesik** [comment] 2021-01-27 20:58
To let everyone know, it has been confirmed to be a Node issue: https://github.com/nodejs/node/issues/37027

**Comment by jameswoodley** [comment] 2021-02-01 21:31
This is still broken on 15.7.0.. however can confirm it works if downgrading to 14.15.1

**Comment by yongfook** [comment] 2021-02-03 02:04
Confirmed rolling back from node @ 15.6.0 to 14.15.4 fixed the problem for me.

**Comment by bssilveira91** [comment] 2021-02-03 10:20
How can i downgrade the node version? Please...

**Comment by pgrzesik** [comment] 2021-02-03 10:46
@bssilveira91 - that depends on the installation method for Node, one of the options is to use `nvm` (https://github.com/nvm-sh/nvm). Alternatively, you can also use a standalone version of the Framework to be independent of installed Node version: https://www.serverless.com/framework/docs/getting-started#install-as-a-standalone-binary

**Comment by vijaysolanki** [comment] 2021-02-03 12:12
@bssilveira91  [here](https://github.com/serverless/serverless/issues/8794#issuecomment-764191601 ) hints shared by @Sphinxs

**Comment by kimegede** [comment] 2021-02-05 08:46
Same issue with node 15, downgrade to node 14 works.

**Comment by pgrzesik** [comment] 2021-02-11 15:28
Hello everyone :wave: The original issue has been resolved and new version of `crc32-stream` has been published. All new `serverless` installations should use that version by default. I'm closing this issue, but if you're still running into errors please let us know :bow:

**Closed by pgrzesik** 2021-02-11 15:28 UTC
Labels: bug/dependency, cat/packaging

**Comment by electric-al** [comment] 2021-02-15 17:46
How does one make an existing serverless project use this new version?

**Comment by pgrzesik** [comment] 2021-02-16 09:39
Hello @electric-al - the best way is to just do a fresh installation which will install a patched version of `crc32-stream` dependency

**Comment by Sphinxs** [comment] 2021-03-14 01:25
@pgrzesik , is [this](https://www.serverless.com/aws-lambda#languages-runtimes) the place where the last run times are published?

**Comment by pgrzesik** [comment] 2021-03-15 12:02
Hello @Sphinxs - I believe it's an obsolete page - also, what do you mean by `last run times`?

**Comment by Sphinxs** [comment] 2021-03-15 12:25
> Hello @Sphinxs - I believe it's an obsolete page - also, what do you mean by `last run times`? 

I mean the supported languages and the versions, eg. Node 14, Python 3.9...

**Comment by pgrzesik** [comment] 2021-03-15 12:28
Thanks for the clarification - all languages and versions supported by AWS are supported by Serverless Framework

**Comment by eshikerya** [comment] 2021-04-23 14:30
node v16 - same issue...
fixed by overriding `crc32-stream` version by:
```json
"resolutions": {
    "crc32-stream": "4.0.2"
}
```
in `package.json`
