### ISSUE TITLE
Feature proposal : sls deploy function skips deployment if code did not change

### ISSUE THREAD

**Issue by LouisPinsard** [serverless/serverless#8810] opened 2021-01-22 17:02 UTC
### Use case description

Context : My lambda functions are written in typescript and I use `serverless-webpack` to deploy code
When I code, I modify my function code then I use `sls deploy function -f myFunction` to test my changes.
Problem : Even if I did not modify my function code since last deployment the cli displays the same results.
It happens that I make a mistake on the function name that I deploy, I do not have any feedback that I am wrong.

### Proposed solution

I was expecting this code base to skip code deployment if there is no change : https://github.com/serverless/serverless/blob/dc9f1809d1ec6830a6682e7946cb4dfc1c898c72/lib/plugins/aws/deployFunction.js#L364-L366

My guesses : 

- serverless-webpack does not generate twice the same code if I package twice in a row the same ts codebase : but it does not look like it's the case : https://github.com/serverless-heaven/serverless-webpack/issues/303
- Or the check in deploy function does not work anymore and maybe this check https://github.com/serverless/serverless/blob/dc9f1809d1ec6830a6682e7946cb4dfc1c898c72/test/unit/lib/plugins/aws/deployFunction.test.js#L249 is not properly testing the feature

I would be very happy to come up with a PR if you have a better guess than mine.

**Comment by pgrzesik** [comment] 2021-01-22 18:02
Hello @LouisPinsard, thank you for submitting your report. I've tried to replicate the issues you're having on a very simple Node.js example and I couldn't reproduce - when I didn't change my code, it was correctly skipping deployment. However, I'm not using webpack or typescript, just plain Node.js code. 

Would you be able to:
- share what specific version on Serverless Framework are you using?
- share a minimal reproducible example with this bug? 

Thanks in advance :bow:

**Comment by LouisPinsard** [comment] 2021-02-18 09:18
Hello @pgrzesik I just updated my serverless framework version and it works well now. I think we can close the issue.

**Comment by pgrzesik** [comment] 2021-02-18 09:48
Hello @LouisPinsard :wave: Thank you for letting us know - I'm closing this one :100:

**Closed by pgrzesik** 2021-02-18 09:48 UTC
Labels: needs feedback
