### ISSUE TITLE
Serverless not available on npm registry?

### ISSUE THREAD

**Issue by pradyumna1** [serverless/serverless#8057] opened 2020-08-06 10:30 UTC
Tried installing serverless but can't, because it seems serverless or some of it's dependencies aren't available on npm.

<details>
<summary><code>serverless.yml</code></summary>

```yaml
# Not Applicable
```

</details>

<details>
<summary><b><code>npm install serverless</code> output</b></summary>

```
npm install serverless                                                                                                                                     ─╯
npm ERR! code E404
npm ERR! 404 Not Found - GET https://registry.npmjs.org/@serverless%2fcli - Not found
npm ERR! 404 
npm ERR! 404  '@serverless/cli@^1.5.2' is not in the npm registry.
npm ERR! 404 You should bug the author to publish it (or use the name yourself!)
npm ERR! 404 It was specified as a dependency of 'serverless'
npm ERR! 404 
npm ERR! 404 Note that you can also install from a
npm ERR! 404 tarball, folder, http url, or git url.
```

</details>

<b>Installed version</b>

```
Framework Core: 1.61.0
Plugin: 3.2.7
SDK: 2.2.1
Components Core: 1.1.2
Components CLI: 1.4.0
```

**Comment by medikoo** [comment] 2020-08-06 10:32
Duplicate of #8054

**Closed by medikoo** 2020-08-06 10:32 UTC
