### ISSUE TITLE
Create s3 event to existing s3 bucket

### ISSUE THREAD

**Issue by sarenjus** [serverless/serverless#4284] opened 2017-09-19 10:31 UTC
This is a Feature Proposal

## Description

We are managing our AWS resources outside the serverless project. Our external resource management creates e.g. S3 buckets for us. We use serverless to deploy our lambdas, API gateways etc. Serverless has currently nice feature to set S3 event on place during the deployment. However it's not possible to create it to a bucket that serverless is not creating itself. 

To solve the issue we'd propose to add a possibility to give the s3 event a bucket arn to which it will add the event.

````
someFunction:
    handler: handler.handler
    events:
      - s3: 
          existingBucket: arn:aws:s3:::someBucket
````

## Additional Data

* ***Serverless Framework Version***: 1.22.0

**Comment by oskarpearson** [comment] 2017-09-20 20:07
This is similar to https://github.com/serverless/serverless/issues/2154 https://github.com/serverless/serverless/issues/1891 and https://github.com/serverless/serverless/issues/1823

Unfortunately I'm not sure that Serverless is going to be able to support this - since cloudformation can't support adjusting configs, and cloudformation expects NotificationConfiguration to be set on the bucket, rather than managed at the lambda event level.

Personally, I think that this would be a great feature. I have an existing bucket + cloudfront configuration that's been managed by Terraform, and I don't want the serverless framework to try create the bucket.

For now, I've decided I'm going to use Terraform to manage the bucket, and to manage the association with the lambda event.

**Comment by pmuens** [comment] 2017-09-21 06:35
Thanks for opening @sarenjus and thanks for jumping in @oskarpearson 👍

@oskarpearson is right here. We can only support this if CloudFormation adds support for that because the whole deployment is done with the help of CF.

I'll close this issue for now since it's a duplicate of #2154, #1891 and #1823.

However we might want to revisit this once CF adds support for this feature.

**Closed by pmuens** 2017-09-21 06:35 UTC
Labels: kind/enhancement, status/help-wanted

**Comment by sahilkalra1991** [comment] 2018-06-29 09:29
Hello all,
I faced the same issue with my serverless deployment. 
On googling it I found that someone created a plugin to do the same with serverless.

https://www.npmjs.com/package/serverless-plugin-existing-s3

It was to be published 2 days ago, so I am reluctant to use it in production.

What do you guys think about it ?

**Comment by shmuelgutman** [comment] 2018-09-06 18:30
+1.
My workaround is the create the bucket manually and connect it through the lambda console and in the serverless.yml I'm not attaching the s3 event to the function.
Of course is not scalable at all but that's what I have now...

**Comment by Daniela0106** [comment] 2018-11-13 21:19
> +1.
> My workaround is to create the bucket manually and connect it through the lambda console and in the serverless.yml I'm not attaching the s3 event to the function.
> Of course is not scalable at all but that's what I have now...

Hi @shmuelgutman ! Hope you're doing well. I was wondering, how should I declare my bucket name on serverless.yml? 

TY in advance :)

![image](https://user-images.githubusercontent.com/8950672/48443611-b89ce700-e75f-11e8-9e94-218022dd6c41.png)

**Comment by michaelm88** [comment] 2019-01-18 11:56
how can create an event to already exist Bucket with CF ?

**Comment by mtchavez** [comment] 2019-08-12 21:00
This issue shows up when searching for using serverless with existing S3 buckets but serverless has since addressed this issue. For posterity here is the documentation on how to do so by using `existing: true` on the S3 event: https://serverless.com/framework/docs/providers/aws/events/s3/#using-existing-buckets

```yaml
functions:
  users:
    handler: users.handler
    events:
      - s3:
          bucket: legacy-photos
          event: s3:ObjectCreated:*
          rules:
            - prefix: uploads/
            - suffix: .jpg
          existing: true
```
