### ISSUE TITLE
Serverless Login Error: listen EACCES

### ISSUE THREAD

**Issue by studiophanes** [serverless/serverless#6515] opened 2019-08-08 00:37 UTC
someone can help me?

```
sls login
Serverless: Logging you in via your default browser...
Error: listen EACCES: permission denied 0.0.0.0:8000
    at Server.setupListenHandle [as _listen2] (net.js:1262:19)
    at listenInCluster (net.js:1327:12)
    at Server.listen (net.js:1414:7)
```

**Comment by medikoo** [comment] 2019-08-08 07:31
It looks if there's some other process taking over the `8000` port (e.g. it could be Java), once that's freed it should work for you.

Anyway we work on improving that experience (do not rely on `8000` if it's taken)

**Comment by pmuens** [comment] 2019-08-08 07:56
Thanks for opening @studiophanes :+1:

Yes, I think @medikoo is right. I'll close this one as a duplicate of https://github.com/serverless/serverless/issues/5436. Also refing https://github.com/serverless/platform-sdk/issues/67 here.

**Closed by pmuens** 2019-08-08 07:56 UTC
Labels: bug, cat/enterprise
