### ISSUE TITLE
TypeError preventing deployments

### ISSUE THREAD

**Issue by Hendrixer** [serverless/serverless#4196] opened 2017-09-02 04:52 UTC
# This is a (Bug Report / Feature Proposal)
**Bug Report**
## Description
* What went wrong?
  * function(s) do not work and error out when trying to execute, after seemingly successful deployment
* What did you expect should have happened?
  * functions to work as expected when sending API Gateway event, just like the work when using `serverless-offline`, perfectly
* What was the config you used?
```yaml
service: dashboard-api

custom:
  webpackIncludeModules: true
  defaultStage: dev

provider:
  name: aws
  runtime: nodejs6.10
  stage: ${opt:stage, self:custom.defaultStage}

plugins:
  - serverless-webpack
  - serverless-offline

package:
  individually: true

functions:
  api:
    handler: src/api/index.graph
    events:
      - http:
          path: api
          method: post
          cors: true
          authorizer: auth
      - http:
          path: api
          method: get
          cors: true
          authorizer: auth

  docs:
    handler: src/docs/index.handler
    events:
      - http:
          path: api/docs
          method: post
          authorizer: auth
      - http:
          path: api/docs
          method: get
          authorizer: auth
  auth:
    handler: src/auth/index.handler

```
* What stacktrace or error message from your provider did you see?
`TypeError: this.getStage(...).toUpperCase is not a function`

Similar or dependent issues:
* #3818 

## Additional Data
It seems to be something with how vars are read / handles in the serverless.yml. No matter what I do, I can never use vars in the config file

* ***Serverless Framework Version you're using***: 1.20.2

* ***Operating System***:  darwin
* ***Stack Trace***:
```
TypeError: this.getStage(...).toUpperCase is not a function
    at AwsProvider.getCredentials (/Users/hendrixer/.nvm/versions/node/v8.1.1/lib/node_modules/serverless/lib/plugins/aws/provider/awsProvider.js:196:58)
    at AwsProvider.request (/Users/hendrixer/.nvm/versions/node/v8.1.1/lib/node_modules/serverless/lib/plugins/aws/provider/awsProvider.js:143:30)
    at AwsLogs.getLogStreams (/Users/hendrixer/.nvm/versions/node/v8.1.1/lib/node_modules/serverless/lib/plugins/aws/logs/index.js:46:8)
From previous event:
    at Object.logs:logs [as hook] (/Users/hendrixer/.nvm/versions/node/v8.1.1/lib/node_modules/serverless/lib/plugins/aws/logs/index.js:20:10)
    at BbPromise.reduce (/Users/hendrixer/.nvm/versions/node/v8.1.1/lib/node_modules/serverless/lib/classes/PluginManager.js:242:55)
From previous event:
    at PluginManager.invoke (/Users/hendrixer/.nvm/versions/node/v8.1.1/lib/node_modules/serverless/lib/classes/PluginManager.js:242:22)
    at PluginManager.run (/Users/hendrixer/.nvm/versions/node/v8.1.1/lib/node_modules/serverless/lib/classes/PluginManager.js:261:17)
    at variables.populateService.then (/Users/hendrixer/.nvm/versions/node/v8.1.1/lib/node_modules/serverless/lib/Serverless.js:99:33)
    at runCallback (timers.js:800:20)
    at tryOnImmediate (timers.js:762:5)
    at processImmediate [as _immediateCallback] (timers.js:733:5)
From previous event:
    at Serverless.run (/Users/hendrixer/.nvm/versions/node/v8.1.1/lib/node_modules/serverless/lib/Serverless.js:86:74)
    at serverless.init.then (/Users/hendrixer/.nvm/versions/node/v8.1.1/lib/node_modules/serverless/bin/serverless:39:50)
    at <anonymous>

```
* ***Provider Error messages***: `  this.getStage(...).toUpperCase is not a function`

**Comment by winstonewert** [comment] 2017-10-10 20:45
Ensure that you aren't -verbose on the command line where you meant --verbose

**Comment by curtisolson** [comment] 2018-03-29 22:01
This was exactly my problem. Thank you.

**Comment by vincedovyWork** [comment] 2018-04-11 16:00
I had the same issue, but it had nothing to do with -verbose or -stage. The problem is the following line in awsProvider.js in the getCredentials function.

    const stageUpper = this.getStage() ? this.getStage().toUpperCase() : null;

In my case, the stage was being set to a hash (hex value.) If the hex was all numeric, getStage returns a numeric, not a string, and toUpperCase fails. I fixed it in my case by prefixing a letter to the stage hash, but the code should be fixed to allow for numeric stage names.

**Comment by HyperBrain** [comment] 2018-04-11 16:04
Could be fixed by:
```
const stageUpper = this.getStage() ? _.toUpper(_.toString(this.getStage())) : null;
```
or, to cover #4872 too, all command line arguments should be passed through `_.toString()` to ensure that none of them are treated as numbers. If a specific function like some of the `serverless logs` parameters require numeric input they should reconvert them with `_.toInteger()`

**Comment by pmuens** [comment] 2019-02-06 13:01
Thanks for opening @Hendrixer 👍

Looks like this has smth. todo with one of the plugins. Could you re-open an issue in the plugins repository? Thanks!

**Closed by pmuens** 2019-02-06 13:01 UTC
Labels: bug, cat/deployment, help wanted
