### ISSUE TITLE
Serverless framework can't see configuration if it configured with variables when it tries to install plugin

### ISSUE THREAD

**Issue by mohovkm** [serverless/serverless#9731] opened 2021-07-12 10:55 UTC
I have `servless.yml` configured with variables. It works fine with the syntax provided in the docs:
```bash
SLS_PROVIDER=aws sls deploy
```

However, when I use this syntax to install any plugin I receive configuration error:
Example commands (that suppose to work, but outputs an error):
```bash
SLS_PROVIDER=azure sls plugin install -n serverless-azure-functions
```
or
```bash
SLS_PROVIDER=azure sls plugin install -n serverless-python-requirements
```

<details>
<summary><code>serverless.yml</code></summary>

```yaml
service: MultiCloudDev

provider: ${self:custom.provider.${env:SLS_PROVIDER}}

functions: ${self:custom.functions.${env:SLS_PROVIDER}}

plugins:
  - serverless-azure-functions
  - serverless-python-requirements

package:
  patterns:
    - 'classes/**'
    - 'functions/**'

custom:
  provider:
    aws:
      name: aws
      runtime: python3.8
      stage: dev

    azure:
      name: azure
      region: West Europe
      runtime: python3.8
      os: linux 
      prefix: "multicloud"
      stage: dev

  functions:
    aws:
      main:
        handler: lambda_main.handler
        events:
          - http:
              path: /
              method: get
        name: aws-MultiCloudDev
        description: ${self:custom.description}
        memorySize: 512
        timeout: 10
    
    azure:
      azure-MultiCloudDev:
        handler: azure_main.main
        description: ${self:custom.description}
        events:
          - http: true
            methods:
              - GET
            path: /
            authLevel: function

  description: MiltiCloud solution to publish and run code with Azure Functions and AWS Lambda

  pythonRequirements:
    dockerizePip: true
    zip: false

```

</details>

<details>
<summary><b><code>SLS_PROVIDER=azure sls plugin install -n serverless-python-requirements</code> output</b></summary>

```
Serverless Error ----------------------------------------
 
Unexpected "0" function configuration: Expected object received '$')
 
Get Support --------------------------------------------
     Docs:          docs.serverless.com
     Bugs:          github.com/serverless/serverless/issues
     Issues:        forum.serverless.com
 
Your Environment Information ---------------------------
     Operating System:          darwin
     Node Version:              14.16.0
     Framework Version:         2.51.2
     Plugin Version:            5.4.3
     SDK Version:               4.2.3
     Components Version:        3.13.3
```

</details>

<b>Installed version</b>

```
Framework Core: 2.51.2
Plugin: 5.4.3
SDK: 4.2.3
Components: 3.13.3
```

<b>Desired behavior</b>
Support variables in yml with all the commands, especially with plugin install.

It will also be cool if we could install plugins only for desired provider, example:

<details>
<summary><code>serverless.yml</code></summary>

```yaml
service: MultiCloudDev

provider: ${self:custom.provider.${env:SLS_PROVIDER}}

functions: ${self:custom.functions.${env:SLS_PROVIDER}}

plugins: ${self:custom.plugins.${env:SLS_PROVIDER}}

custom:
  plugins:
    azure:
      - serverless-azure-functions
      - serverless-python-requirements
    aws:
      - serverless-python-requirements

...
```

**Comment by mohovkm** [comment] 2021-07-12 11:14
There is another issue, related to config variables. Ping me, if I need to add this as a separate issue.

Serverless framework `plugin install` will not work if the `package` session will be configured with variables. Below is the full yml file, which works fine with the command:
```bash
SLS_PROVIDER=azure sls deploy
```

<details>

<summary><code>serverless.yml</code></summary>

```yaml
service: MultiCloudDev

provider: ${self:custom.provider.${env:SLS_PROVIDER}}

functions: ${self:custom.functions.${env:SLS_PROVIDER}}

plugins: ${self:custom.plugins.${env:SLS_PROVIDER}}

package: ${self:custom.package.${env:SLS_PROVIDER}}

custom:
  provider:
    aws:
      name: aws
      runtime: python3.8
      stage: dev

    azure:
      name: azure
      region: West Europe
      runtime: python3.8
      os: linux 
      prefix: "multicloud"
      stage: dev

  functions:
    aws:
      main:
        handler: lambda_main.handler
        events:
          - http:
              path: /
              method: get
        name: aws-MultiCloudDev
        description: ${self:custom.description}
        memorySize: 512
        timeout: 10
    
    azure:
      azure-MultiCloudDev:
        handler: azure_main.main
        description: ${self:custom.description}
        events:
          - http: true
            methods:
              - GET
            path: /
            authLevel: function

  description: MiltiCloud solution to publish and run code with Azure Functions and AWS Lambda

  pythonRequirements:
    dockerizePip: true
    zip: false

  plugins:
    azure:
      - serverless-azure-functions
      - serverless-python-requirements
    aws:
      - serverless-python-requirements
  
  package:
    azure:
      patterns:
        - 'classes/**'
        - 'functions/**'
        - '!lambda_main.py'
    aws:
      patterns:
        - 'classes/**'
        - 'functions/**'
        - '!azure_main.py'
```
</details>

Output of `plugin install` command with package configured with variables:

<details>

<summary><b><code>SLS_PROVIDER=azure sls plugin install -n serverless-python-requirements</code> output</b>
</summary>

```bash
Serverless Error ----------------------------------------
 
  Cannot resolve serverless.yml: "package.path" property is not accessible (configured behind variables which cannot be resolved at this stage)
 
  Get Support --------------------------------------------
     Docs:          docs.serverless.com
     Bugs:          github.com/serverless/serverless/issues
     Issues:        forum.serverless.com
 
  Your Environment Information ---------------------------
     Operating System:          darwin
     Node Version:              14.16.0
     Framework Version:         2.51.2
     Plugin Version:            5.4.3
     SDK Version:               4.2.3
     Components Version:        3.13.3
```
</details>

**Comment by pgrzesik** [comment] 2021-07-13 16:16
Thanks a lot for reporting @mohovkm. I've managed to reproduce both of these issues and nail down the root cause - in case of `plugin` commands, the variables are not being resolved which results in errors that you've experienced (related https://github.com/serverless/serverless/blob/4eb366b97eeaf3056d16afb6d49e5e9cc1a3ce8f/scripts/serverless.js#L359). I've also tested that ensuring variables resolution makes both of the above commands work. @medikoo do you see any downsides of relaxing that check and resolving variables in cases of `plugin` commands?

**Comment by medikoo** [comment] 2021-07-14 09:06
@pgrzesik  Ideally `plugin install` and `plugin uninstall` should be secluded out of internals, as there's no need to setup service in those cases (we just need to ensure that `plugins` section is resolved, and that's currenlty ensured).
I've opened issue to tackle that at some point: https://github.com/serverless/serverless/issues/9740

And for a meantime I've created a fix that I believe will patch it with current implementation: https://github.com/serverless/serverless/pull/9741 (tested locally, works as expected)

----

> It will also be cool if we could install plugins only for desired provider, example

@mohovkm Currently Framework engine supports deployment only with single provider, so it'll be not natural to introduce mulit-provider sections

In your case I would suggest to use different configuration files per provider, as `serverless.aws.yml` and `serverless.azure.yml` (you can then point those config with `--config` option).

Note that we're also discussing to introduce multi-providers support: https://github.com/serverless/serverless/issues/9583

**Comment by pgrzesik** [comment] 2021-07-14 09:16
Thanks @medikoo :+1: I agree that in such case there's no need to setup service as we only deal with `plugins` part of the configuration. Thanks a lot for addressing it so quickly

**Closed** 2021-07-14 12:15 UTC
Labels: bug, cat/cli, cat/plugin, cat/variable

**Comment by mohovkm** [comment] 2021-07-14 15:16
Thanks a lot, guys! You're the best! 
By the way, how long it takes to update npm repo? Cause I have installed serverless via npm and it seems, like nothing happens with `npm update -g serverless`

**Comment by medikoo** [comment] 2021-07-14 15:20
@mohovkm it'll be visible with next release, which will go out this week

**Comment by Telltak** [comment] 2022-04-05 12:29
Hi, this issue appears to have reappeared in Serverless v3. Currently you can workaround the issue by passing params into the install command. Such as `sls plugin install -n serverless-python-requirements --param="foo=bar"`

```sls -v
Framework Core: 3.11.0
Plugin: 6.2.1
SDK: 4.3.2
```

**Comment by medikoo** [comment] 2022-04-05 12:52
@Telltak It was introduced with v3.0.0 but it was fixed later. Ensure to rely on the latest version
