### ISSUE TITLE
Unresolved resource dependencies [RestApiApigEvent]

### ISSUE THREAD

**Issue by danielfosbery** [serverless/serverless#1822] opened 2016-08-11 11:35 UTC
Hey guys. Firstly love the project, have been using it for our Lambda deployments since seeing the Lambda talk at the recent AWS London Summit and it has really simplified things for us.

I'm getting an error when trying to deploy a project that has a resource that uses `{ "Ref" : "RestApiApigEvent" }`. This only happens when trying to deploy a new project with this reference, it seems to work fine if the resource that uses the Ref is added after the first deployment.

##### Serverless Framework Version: 
Beta1

##### Operating System: 
OSX 10.11.6

##### Expected Behavior:
This should create the 'partnerPostOrder' Lambda function as well as adding the 'AWS::ApiGateway::BasePathMapping'

##### Actual Behavior:
I'm getting the following error when running the first deploy with a 'AWS::ApiGateway::BasePathMapping' resource

`Template format error: Unresolved resource dependencies
     [RestApiApigEvent] in the Resources block of the template`

Now this only happens on the initial deploy. If I remove the 'AWS::ApiGateway::BasePathMapping', then deploy it obviously works fine. However after this initial deploy with just the Lambda function, if I add the BasePathMapping resource back into the yaml file and then deploy again everything works fine, both the Lambda function is deployed and the BasePathMapping resource is created correctly without any errors.

This is my serverless.yaml file.

```
service: api-hooks
provider:
    name: aws

defaults:
    stage: dev
    region: eu-west-1
    memory: 512
    timeout: 5

functions:
    partnerPostOrder:
        handler: lib/functions/partner/order-status.handler
        events:
            - http:
                path: partner/order-status
                method: POST

resources:
    Resources:
        APIDomainMapping:
            Type: AWS::ApiGateway::BasePathMapping
            Properties:
                BasePath: hooks
                DomainName: ${domain}
                RestApiId: { "Ref" : "RestApiApigEvent" }
                Stage: ${stage}
```

##### Stack-Trace (Optional):
```
ValidationError: Template format error: Unresolved resource dependencies [RestApiApigEvent] in the Resources block of the template
    at Request.extractError (/usr/local/lib/node_modules/serverless/node_modules/aws-sdk/lib/protocol/query.js:40:29)
    at Request.callListeners (/usr/local/lib/node_modules/serverless/node_modules/aws-sdk/lib/sequential_executor.js:105:20)
    at Request.emit (/usr/local/lib/node_modules/serverless/node_modules/aws-sdk/lib/sequential_executor.js:77:10)
    at Request.emit (/usr/local/lib/node_modules/serverless/node_modules/aws-sdk/lib/request.js:615:14)
    at Request.transition (/usr/local/lib/node_modules/serverless/node_modules/aws-sdk/lib/request.js:22:10)
    at AcceptorStateMachine.runTo (/usr/local/lib/node_modules/serverless/node_modules/aws-sdk/lib/state_machine.js:14:12)
    at /usr/local/lib/node_modules/serverless/node_modules/aws-sdk/lib/state_machine.js:26:10
    at Request.<anonymous> (/usr/local/lib/node_modules/serverless/node_modules/aws-sdk/lib/request.js:38:9)
    at Request.<anonymous> (/usr/local/lib/node_modules/serverless/node_modules/aws-sdk/lib/request.js:617:12)
    at Request.callListeners (/usr/local/lib/node_modules/serverless/node_modules/aws-sdk/lib/sequential_executor.js:115:18)
    at Request.emit (/usr/local/lib/node_modules/serverless/node_modules/aws-sdk/lib/sequential_executor.js:77:10)
    at Request.emit (/usr/local/lib/node_modules/serverless/node_modules/aws-sdk/lib/request.js:615:14)
    at Request.transition (/usr/local/lib/node_modules/serverless/node_modules/aws-sdk/lib/request.js:22:10)
    at AcceptorStateMachine.runTo (/usr/local/lib/node_modules/serverless/node_modules/aws-sdk/lib/state_machine.js:14:12)
    at /usr/local/lib/node_modules/serverless/node_modules/aws-sdk/lib/state_machine.js:26:10
    at Request.<anonymous> `(/usr/local/lib/node_modules/serverless/node_modules/aws-sdk/lib/request.js:38:9)`
```

**Comment by flomotlik** [comment] 2016-08-11 14:46
@danielfosbery this is a known but yet unresolved feature. The problem is that we're using the custom resource upon initial stack creation (when it should really only have the S3 bucket in it). When you reference resources that we'll create in a later step this will fail.  #1783 is resolving this, but we'll have to jump on this one soon as its a big issue

**Comment by danielfosbery** [comment] 2016-08-11 14:56
Brilliant, looks like its on its way to being sorted. Thanks @flomotlik, keep up the good work!

**Comment by flomotlik** [comment] 2016-08-17 14:05
@danielfosbery can you look into the latest beta and how we're merging resources now? Basically everything should be working fine now.

**Closed** 2016-08-17 14:06 UTC
Labels: bug

**Comment by danielfosbery** [comment] 2016-08-17 14:25
All works as expected. Thanks @flomotlik !

**Comment by jetheurer** [comment] 2016-09-08 21:52
I'm a little confused on how to use this feature in `1.0.0-rc.1`.  Right now my `serverless.yml` looks like:
```
resources:
  Resources:
    APIDomainMapping:
        Type: AWS::ApiGateway::BasePathMapping
        Properties:
            BasePath: ${opt:stage}
            DomainName: ####
            RestApiId:
              Ref: RestApiApigEvent
            Stage: ${opt:stage}
```

I'm not sure how to reference the `RestApiId`

**Comment by flomotlik** [comment] 2016-09-09 07:03
@jetheurer can you run `serverless deploy --noDeploy` to see what the template ends up with? Generally this config looks correct

**Comment by jetheurer** [comment] 2016-09-09 13:24
This is the error message I get from: `serverless deploy --region $region --stage $stage --verbose`

```
Template format error: Unresolved resource dependencies
     [RestApiApigEvent] in the Resources block of the template
```

**Comment by jetheurer** [comment] 2016-09-09 13:58
I get the following:

```    
  "APIDomainMapping": {
      "Type": "AWS::ApiGateway::BasePathMapping",
      "Properties": {
        "BasePath": "liz",
        "DomainName": "######",
        "RestApiId": {
          "Ref": "RestApiApigEvent"
        },
        "Stage": "liz"
      }
    }
```

**Comment by alexanderbh** [comment] 2016-09-28 08:00
@jetheurer The logical name is changed to `ApiGatewayRestApi` in this commit:
https://github.com/serverless/serverless/commit/a5e3c3197474f1eac2672802132ef7c0a26db6a4

So now it looks like this:

```
RestApiId:
    Ref: ApiGatewayRestApi
```

**Comment by jetheurer** [comment] 2016-09-29 03:05
@alexanderbh That's what I was missing.  Thanks so much!

**Comment by alexanderbh** [comment] 2016-09-29 06:17
@jetheurer If you run into the problem that CloudFormation tries to create your BasePathMapping before the actual ApiGateway::Deployment you run into this issue: https://github.com/serverless/serverless/issues/2233

Which I have fixed here: https://github.com/serverless/serverless/pull/2234 waiting for review.

**Comment by citosid** [comment] 2016-09-30 11:38
I have this stack:

```
➔ cat .serverless/cloudformation-template-update-stack.json
{
  "AWSTemplateFormatVersion": "2010-09-09",
  "Description": "The AWS CloudFormation template for this Serverless application",
  "Resources": {
    "ServerlessDeploymentBucket": {
      "Type": "AWS::S3::Bucket"
    },
    "IamRoleLambdaExecution": {
      "Type": "AWS::IAM::Role",
      "Properties": {
        "AssumeRolePolicyDocument": {
          "Version": "2012-10-17",
          "Statement": [
            {
              "Effect": "Allow",
              "Principal": {
                "Service": [
                  "lambda.amazonaws.com"
                ]
              },
              "Action": [
                "sts:AssumeRole"
              ]
            }
          ]
        },
        "Path": "/"
      }
    },
    "IamPolicyLambdaExecution": {
      "Type": "AWS::IAM::Policy",
      "Properties": {
        "PolicyName": "dev-abe-api-site-lambda",
        "PolicyDocument": {
          "Version": "2012-10-17",
          "Statement": [
            {
              "Effect": "Allow",
              "Action": [
                "logs:CreateLogGroup",
                "logs:CreateLogStream",
                "logs:PutLogEvents"
              ],
              "Resource": "arn:aws:logs:us-east-1:*:*"
            }
          ]
        },
        "Roles": [
          {
            "Ref": "IamRoleLambdaExecution"
          }
        ]
      }
    },
    "HelloLambdaFunction": {
      "Type": "AWS::Lambda::Function",
      "Properties": {
        "Code": {
          "S3Bucket": {
            "Ref": "ServerlessDeploymentBucket"
          },
          "S3Key": "1475235324325-2016-09-30T11:35:24.325Z/abe-api-site.zip"
        },
        "FunctionName": "abe-api-site-dev-hello",
        "Handler": "handler.hello",
        "MemorySize": 1024,
        "Role": {
          "Fn::GetAtt": [
            "IamRoleLambdaExecution",
            "Arn"
          ]
        },
        "Runtime": "python2.7",
        "Timeout": 6
      }
    },
    "ProxyResource": {
      "Type": "AWS::ApiGateway::Resource",
      "Properties": {
        "ParentId": {
          "Fn::GetAtt": [
            "ApiGatewayRestApi",
            "RootResourceId"
          ]
        },
        "PathPart": "/auth/keys",
        "RestApiId": {
          "Ref": "ApiGatewayRestApi"
        }
      }
    },
    "ProxyMethod": {
      "Type": "AWS::ApiGateway::Method",
      "Properties": {
        "ResourceId": {
          "Ref": "ProxyResource"
        },
        "RestApiId": {
          "Ref": "ApiGatewayRestApi"
        },
        "HttpMethod": "GET",
        "MethodResponses": [
          {
            "StatusCode": 200
          }
        ],
        "Integration": {
          "IntegrationHttpMethod": "POST",
          "Type": "HTTP",
          "Uri": "https://dev2.site.org/auth/keys",
          "IntegrationResponses": [
            {
              "StatusCode": 200
            }
          ]
        }
      }
    }
  },
  "Outputs": {
    "ServerlessDeploymentBucketName": {
      "Value": {
        "Ref": "ServerlessDeploymentBucket"
      }
    },
    "HelloLambdaFunctionArn": {
      "Description": "Lambda function info",
      "Value": {
        "Fn::GetAtt": [
          "HelloLambdaFunction",
          "Arn"
        ]
      }
    }
  }
}%
```

And I see this error:

```
  Serverless Error ---------------------------------------
 
     Template format error: Unresolved resource dependencies
     [ApiGatewayRestApi] in the Resources block of the template
 
  Get Support --------------------------------------------
     Docs:          docs.serverless.com
     Bugs:          github.com/serverless/serverless/issues
 ```

**Comment by alexanderbh** [comment] 2016-10-03 06:59
@citosid There is no `AWS::ApiGateway::RestApi` in that template. Which version of serverless are you using and how does your `severless.yml` file look?

**Comment by citosid** [comment] 2016-10-03 18:03
@alexanderbh I'm using RC2 and I'm using the default yaml example in the guide to create a http proxy api.
