### ISSUE TITLE
Determine .yml file to be used as a command line argument

### ISSUE THREAD

**Issue by nolde** [serverless/serverless#4267] opened 2017-09-15 00:49 UTC
# This is a Feature Proposal

## Description

Users should be able to determine a file different from `serverless.yml` to run serverless over.

```bash
# runs serverless using "serverless.yml"
sls <command>

# runs serverless using "mysecondaryconfig.yml"
sls <command> --config mysecondaryconfig.yml
```

On projects that contain too many resources, developers may have to be split it into different serverless.yml files; currently, different folders must be used for each different `.yml` file, which is messy.

Also, that allows quick tests of different configurations and other sorts of organisation flexibility, without breaking any existing behaviour.

**Comment by pmuens** [comment] 2017-09-15 05:04
Thanks for opening @nolde 👍

Looks like this is a duplicate of https://github.com/serverless/serverless/issues/4124. Closing this one for now. Let's move the discussion over there 👍.

**Closed by pmuens** 2017-09-15 05:04 UTC
Labels: kind/feature, status/help-wanted
