### ISSUE TITLE
API Gateway Log format not updated

### ISSUE THREAD

**Issue by airmonitor** [serverless/serverless#7093] opened 2019-12-15 21:10 UTC
# Bug Report

## Description

1. What did you do?
sls deploy

1. What happened?
API Gateway custom access logging log format was not updated by using the provided format.

1. What should've happened?
Custom Access Logging Log Format created for the stage should be as specified below in the content of serverless.yml file. Instead default log format is enabled.
1. What's the content of your `serverless.yml` file?
`
provider:
    logs:
    restApi:
      executionLogging: true
      level: INFO
      fullExecutionData: true
      format: '{"requestId":"$context.requestId", "ip": "$context.identity.sourceIp", "api_key": "$context.identity.apiKey", "caller":"$context.identity.caller", "user":"$context.identity.user", "requestTime":"$context.requestTime", "httpMethod":"$context.httpMethod", "resourcePath":"$context.resourcePath", "status":"$context.status", "protocol":"$context.protocol", "responseLength":"$context.responseLength"}'
`

1. What's the output you get when you use the `SLS_DEBUG=*` environment variable (e.g. `SLS_DEBUG=* serverless deploy`)

https://pastebin.com/Es21EedG

Similar or dependent issues:

**Comment by medikoo** [comment] 2019-12-16 09:52
@airmonitor thanks for report. Can you provide content of `serverless.yml` through which we can reproduce thatm in readable form. (can be here, using proper markdown formatting, or via gist) ?

**Comment by airmonitor** [comment] 2019-12-17 22:05
@medikoo yes sure, 

https://pastebin.com/LWYwrsdY

**Comment by medikoo** [comment] 2019-12-18 09:45
@airmonitor I've just tested this simple service: https://github.com/medikoo/test-serverless/blob/3af974a2b3c5ebdcda819bf0d7c8391c4f411fe5/serverless.yml and any update to `format` property is deployed successfully, when relying on latest `serverless` version.

Ensure you're using latest version, and if problem still persist, narrow the problem by removing plugins or any other side configuration, to investigate what exactly causes the issue.

I see your configuration is quite extensive and involves many plugins, hence there are many factors that can be responsible for that. It doesn't necessarily should a bug in a framework itself.

**Comment by airmonitor** [comment] 2019-12-25 20:46
Hi medikoo.

I've moved sliced template for multiple templates. Now it looks like below:

`org: 3twrf
app: y53u-ejgpsf
service: 535erg

plugins:
  - serverless-domain-manager
custom:
  project_name: 'y53u-ejgpsf'
  customDomain:
    domainName: api.${self:custom.project_name}.cloud
    stage: ${self:provider.stage}
    basePath: v1
    certificateName: api.${self:custom.project_name}.cloud
    createRoute53Record: true
    endpointType: 'regional'

provider:
  name: aws
  region: eu-west-1
  account_id: 111111111111
  profile: 3twf3
  versionFunctions: true
  stage: ${opt:stage, 'prd'}
  logRetentionInDays: 5
  logs:
    restApi:
      executionLogging: true # Optional configuration which enables or disables execution logging. Defaults to true.
      level: INFO # Optional configuration which specifies the log level to use for execution logging. May be set to either INFO or ERROR.
      fullExecutionData: true # Optional configuration which specifies whether or not to log full requests/responses for execution logging. Defaults to true.
      format: '{"requestId":"$context.requestId", "ip": "$context.identity.sourceIp", "api_key": "$context.identity.apiKey", "caller":"$context.identity.caller", "user":"$context.identity.user", "requestTime":"$context.requestTime", "httpMethod":"$context.httpMethod", "resourcePath":"$context.resourcePath", "status":"$context.status", "protocol":"$context.protocol", "responseLength":"$context.responseLength", "format":"SLS_ACCESS_LOG","version":"1.0.0"}'
  deploymentBucket:
    name: ${file(resources/shared_resources.yml):deployment_bucket_name}
  runtime: python3.6
  apiKeys:
    - ${self:service}:${self:provider.stage}-aasdf
    - ${self:service}:${self:provider.stage}-adsf
    - ${self:service}:${self:provider.stage}-adsf
    - ${self:service}:${self:provider.stage}-adf
    - ${self:service}:${self:provider.stage}-asdfasdfasdfasdf
    - ${self:service}:${self:provider.stage}-4rwfe
  usagePlan:
    quota:
      limit: 500000
      period: MONTH
      offset: 2
    throttle:
      burstLimit: 500
      rateLimit: 500
  apiGateway:
    apiKeySourceType: HEADER
  tags:
    ${file(resources/shared_resources.yml):tags}
  stackTags:
    ${file(resources/shared_resources.yml):tags}

package:
  individually: true
  exclude:
    - ".*/**"
    - "*.**"
    - documentation/**
    - Makefile
    - makefile_libraries/**
    - models/**
    - node_modules/**
    - resources/**
    - tests/**
    - sub_services/**

functions:
  HelloWorld:
    handler: hello_world.handler
    events:
      - http:
          method: POST
          path: /
          integration: lambda
          cors: true
          private: true
    package:
      include:
        - hello_world.py
    description: Dummy required resource
    memorySize: 128
    timeout: 10
    tracing: PassThrough
    environment:
      LOG_LEVEL: "WARNING"`

log from sls deploy - https://pastebin.com/xuqLEBDS

**Comment by medikoo** [comment] 2019-12-27 20:06
@airmonitor it still involves many plugins. Can you prepare a test case that doesn't involve any plugins? 

If you cannot reproduce it without using plugins, then it's likely that problem is not in a Framework itself

**Comment by airmonitor** [comment] 2020-01-05 15:31
https://github.com/amplify-education/serverless-domain-manager/issues/288

**Comment by medikoo** [comment] 2020-01-07 13:47
Thanks @airmonitor I'm closing this then

**Closed by medikoo** 2020-01-07 13:47 UTC
Labels: cat/api-gw, question
