### ISSUE TITLE
Rebuild serverless-state.json and update/create files without rebuilding the project

### ISSUE THREAD

**Issue by VincentSurelle** [serverless/serverless#9522] opened 2021-05-26 10:03 UTC
I have a big project with a lot of functions. It take around 4 minutes to build the .zip files.
I want to "Build once, Deploy many". So I tried to `sls package` then `sls deploy --stage e2e` & `sls deploy --stage staging`

But, it seem like `sls package` only package for a given environment. Here the default `dev` is used.
My Zips will (I think) remain the same depending on the environnement, only Serverless-state.json and create/update stack files will be changed.

### Use case description

When using `sls deploy --stage staging --package .serverless` rebuild serverless-state.json if stage is different so one build could be used for many deployments without rebuilds zips

**Comment by medikoo** [comment] 2021-06-01 14:12
Duplicate of https://github.com/serverless/serverless/issues/3528

**Closed by medikoo** 2021-06-01 14:12 UTC
Labels: duplicate
