### ISSUE TITLE
Custom resource deployment hangs forever

### ISSUE THREAD

**Issue by sean-legitscript** [serverless/serverless#12597] opened 2024-06-13 20:12 UTC
### Issue description

We have a lambda that uses S3 events to be triggered.
```
processSpreadsheet:
  architecture: arm64
  memorySize: 3008
  timeout: 900
  handler: src/_handlers.processSpreadsheet
  events:
    - s3:
        bucket: example-bucket
        event: s3:ObjectCreated:*
        existing: true
        forceDeploy: true
```

When we deploy this the first time, it and all of the other lambdas are successfully deployed. However, upon subsequent deployments, the following happens:
- The sls deployment hangs
- In the Cloudformation Stack Resources section, I found the following:

```
Logical ID | Physical ID | Type | Status | Module
CustomDashresourceDashexistingDashs3LambdaFunction | example-STAGE-custom-resource-existing-s3 | AWS::Lambda::Function | UPDATE_COMPLETE
ProcessSpreadsheetCustomS31 | CustomResourceExistingS3 | Custom::S3 | UPDATE_IN_PROGRESS
```

- After 60 minutes, the stack goes into ROLLBACK_IN_PROGRESS with the following error messages:

_The following resource(s) failed to update: [ProcessSpreadsheetCustomS31]._
_CloudFormation did not receive a response from your Custom Resource. Please check your logs for requestId [02a99d31-512c-4a2f-a989-a932bee1a310]. If you are using the Python cfn-response module, you may need to update your Lambda function code so that CloudFormation can attach the updated version._

- I've tried finding those cloudwatch logs but they don't seem to exist anywhere. After another 60 minutes, the stack goes into UPDATE_ROLLBACK_FAILED and gives me the same error messages it did when it went into ROLLBACK_IN_PROGRESS.

### Context

**Serverless Version**: 3.38.0

**Plugins**:
  - serverless-api-gateway-caching
  - serverless-v2-aws-documentation
  - serverless-domain-manager
  - serverless-offline
  - serverless-step-functions
  - serverless-plugin-aws-alerts
  - serverless-webpack
  - serverless-dependson-plugin

**Comment by mikybars** [comment] 2024-06-14 09:02
Thanks @sean-legitscript for reporting this as I was about to do the same thing 😅 

In my case I have a `PreSignUp` hook set up for an **existing** (this fact is relevant) Cognito user pool and I was experiencing the same hangs that you describe.
After one week or so of painful debugging (1+ hour feedback loops) I can say that I finally figured it out and had it working. I don't want to bore anyone here with the gritty details but the problem lies within the `custom-resources` code provided by the serverless framework when you add the `existing: true` property in your config. This code, which is auto-generated as part of the `package` phase inside the `.serverless` folder, is responsible for provisioning custom resources in AWS. As I had the opportunity to find out this code is **wrong**:

```js
export default {
  handler: handlerWrapper(handler, 'CustomResourceExistingCognitoUserPool')
};
```

As far as I'm concerned (I'm not a JS guy) ES6 modules are not supported in Node.js environments, which use CommonJS syntax instead:

```js
module.exports = {
  handler: handlerWrapper(handler, 'CustomResourceExistingCognitoUserPool')
};
```

Btw, this would have been _way_ easier to find out should the lambda function responsible for provisioning the custom resource had had a log group set up in CloudWatch in the first place. I guess anyone expected this to ever fail 🤷🏾

**Comment by Mmarzex** [comment] 2024-06-14 15:50
Hi @mikybars your issue is a regression on our part in v4 I believe, so we will get a fix published shortly.

As for what you are seeing @sean-legitscript on v3 there haven't been any changes so not sure what could be causing that. Could you try adding the property `provider.logs.frameworkLambda: true` in your `serverless.yml`, then you should be able to see the logs in Cloudwatch for the custom resource lambda.

**Comment by Mmarzex** [comment] 2024-06-14 17:53
@mikybars We updated v4 with a fix for this, if you want to run `serverless update` and try again?

**Comment by mikybars** [comment] 2024-06-15 08:57
Yep, it seems to be working now. No more hangs. Good job ;)

**Closed** 2024-06-18 17:23 UTC

**Comment by sean-legitscript** [comment] 2024-09-13 01:09
Hey there, I wanted to reach out about this issue as it is still causing all sorts of problems for us. Our team has this lambda deployed for each stage. Because of this, each lambda attempts to create the same Custom S3 resource. This seems to be the reason why these lambda deployments are hanging. Again, we are setting `existing: true` and `forceDeploy: true` Which I thought would help us avoid these hands. Could I get a hand with this please?
