### ISSUE TITLE
sls deploy with AWS cross account profile no longer waits for MFA input

### ISSUE THREAD

**Issue by powelli** [serverless/serverless#6576] opened 2019-08-22 12:17 UTC
# This is a Bug Report

## Description

- What went wrong?
  - Invoking `sls deploy` via `SLS_DEBUG=* sls deploy --stage mystage --aws-profile my-cross-account-role-with-mfa`, the application skips straight past the prompt for "Enter MFA code for..."
  - If an MFA token is entered at the next opportunity on stdin despite the _output_ moving on, then the deploy will continue using the assumed role
  - If the user simply hits enter because it looks like the deploy has stalled, then the deploy will fail with an error about `AWS provider credentials not found`
  - This previously worked OK with 1.37.1, the application waited for an MFA token on stdin but on 1.50.0 the output continues and is quite misleading as the app is still waiting for input
- What did you expect should have happened?
  - Application should wait at the MFA prompt for user input, then continue using the cross-account role
- What was the config you used?
  - ```
    provider:
    name: aws
    runtime: python3.6
    stage: ${opt:stage, 'dev'}
    region: eu-west-1
    ```
  - ~/.aws/credentials
    ```
    [default]
    aws_access_key_id = <my-root-account-access-key-id>
    aws_secret_access_key = <my-root-account-access-key-id>
    ```
  - Root account user has MFA enabled
  - ~/.aws/config
    ```
    [profile my-cross-account-role-with-mfa]
    region = eu-west-1
    role_arn = arn:aws:iam::<target-account-id>:role/<role-name>
    source_profile = default
    ```
    
- What stacktrace or error message from your provider did you see?
  - Initial application output:
    ```
    $ export AWS_SDK_LOAD_CONFIG="true"
    $ SLS_DEBUG=* sls deploy --stage mystage --aws-profile my-cross-account-role-with-mfa
    Serverless: Load command config
    Serverless: Load command config:credentials
    [...]
    Serverless: Invoke deploy
    Serverless: Invoke package
    Serverless: Invoke aws:common:validate
    Enter MFA code for arn:aws:iam::<root-account-id>:mfa/<root-user-name>: Serverless:Invoke aws:common:cleanupTempDir
    Serverless: Generated requirements from /[...]/requirements.txt in /[...]/.serverless/requirements.txt...
    Serverless: Installing requirements from /[...]/.serverless/requirements/requirements.txt ...
    ```
  - Deploy continues
    ```
    AWS Pseudo Parameter: 
    Resources::ChannelDeleteLambdaPermissionS3::Properties::SourceArn Replaced 
    AWS::Region with ${AWS::Region}
    AWS Pseudo Parameter: 
    Resources::ChannelUpdateLambdaPermissionS3::Properties::SourceArn Replaced 
    AWS::Region with ${AWS::Region}
    <enter-MFA-token-here>
    Serverless: [AWS sts 200 0.65s 0 retries] assumeRole({ RoleArn: 
    [...]

    ```

Similar or dependent issues:

- 

## Additional Data

- **_Serverless Framework Version you're using_**: 1.50.0
- **_Operating System_**: MacOS 10.13.6
- **_Stack Trace_**:
- **_Provider Error messages_**:

**Comment by dschep** [comment] 2019-08-22 12:42
You want to use `--profile` not `--aws-profile` IIRC.

**Comment by powelli** [comment] 2019-08-22 15:55
> You want to use `--profile` not `--aws-profile` IIRC.

I'm not sure that's correct @dschep - the docs don't seem to mention that anywhere while `--aws-profile` is well documented: https://serverless.com/framework/docs/providers/aws/guide/credentials#using-the-aws-profile-option

Also that doesn't specifically address this issue, the profile is being correctly identified using these commands and the MFA token prompt is even appearing as expected, it's just that it's not waiting for user input before moving on.

**Comment by dschep** [comment] 2019-08-23 21:01
Oh you are indeed correct, I misremembered when someone did the exact opposite 🤦‍♂ 

Out of curiosity, does it work if you set the profile by using the `AWS_PROFILE` env var instead?

**Comment by odannyboy000** [comment] 2019-08-29 11:45
I'm also facing this issue. I'm able to enter the MFA token at any time and serverless still successfully deploys, but it certainly is confusing.

**Comment by medikoo** [comment] 2019-10-14 12:52
Ufortunately merged fix, broken  other things, and got to be reverted. 

@drexler we'll be happy to help to come up with proper solution, still we're not sure how to reproduce the issue. Your help will be much appreciated

**Comment by drexler** [comment] 2019-10-14 23:15
@medikoo, interesting that my tests didn't catch the one. I have an two accounts setup with one "master" account set to assume a role in the other. Locally, my AWS setup is like: 

.aws/credentials
```
[master-drexler]
aws_access_key_id = THIS_IS_A_KEY
aws_secret_access_key = KEEP_IT_SAFE_KEEP_IT_SECRET
```

./aws/config
```
[profile open-sourcerer]
region = us-east-1
output = table
role_arn = arn:aws:iam::XXXXXXXXXXX:role/OpenSourceStuff
source_profile = master-drexler
mfa_serial=arn:aws:iam::XXXXXXXXXX:mfa/email-address
```

To reproduce, i deploy any Serverless application i had with my `open-sourcerer` account to force the MFA prompt. So: 
```
sls deploy --aws-profile open-sourcerer
```

**Comment by medikoo** [comment] 2019-10-16 15:53
@drexler thanks, I got it reproduced, actually missing part on my side was lack of `AWS_SDK_LOAD_CONFIG=1`

Source of the issue, is that when user is asked for MFA code, we do not hold with further operations (hence the log output that occurs after MFA code question). It stops only when first AWS request occurs (as it waits for the token), then MFA code could be input to move things forward, but ofc it's dirty (with all those logs noise that was just output)

IMO the right solution for that is to make [`awsProfileCredentials`](https://github.com/serverless/serverless/blob/69f4c83d5a7c30ad9ae8344676f7c5b8ca0a9466/lib/plugins/aws/provider/awsProvider.js#L76) method async, and just wait there until token is provided.

Conversion of credentials resolution part to async was already made in https://github.com/serverless/serverless/pull/6430 still that remains not finished (and it also requires a lot of updates, so it doesn't necessarily serve as an elegant base for that improvement)

**Comment by drexler** [comment] 2019-10-28 21:18
> @drexler thanks, I got it reproduced, actually missing part on my side was lack of `AWS_SDK_LOAD_CONFIG=1`
> 
@medikoo  thanks for looking into this. When i get the chance, i might write a cover test we can add around the existing validation - was bit surprised that it didn't get picked up in the unit tests for #6780

> IMO the right solution for that is to make [`awsProfileCredentials`](https://github.com/serverless/serverless/blob/69f4c83d5a7c30ad9ae8344676f7c5b8ca0a9466/lib/plugins/aws/provider/awsProvider.js#L76) method async, and just wait there until token is provided.
> 
I definitely agree that this is the right approach.  I'll see where i can help out on that. 
> Conversion of credentials resolution part to async was already made in #6430 still that remains not finished (and it also requires a lot of updates, so it doesn't necessarily serve as an elegant base for that improvement)

**Comment by zdmytriv** [comment] 2020-01-20 14:04
still an issue :(

**Comment by frank-mkb-brandstof** [comment] 2020-02-13 08:58
Still an issue using Framework version 1.63.0.

frank@frank-HP-EliteBook-850-G3:~/Projects/dwhetl$ unset SLS_DEBUG
frank@frank-HP-EliteBook-850-G3:~/Projects/dwhetl$ sls deploy --stage exp --aws-profile mkbexp
Enter MFA code for arn:aws:iam::***********:mfa/Frank: Serverless: Packaging service...
Serverless: Excluding development dependencies...
Serverless: Excluding development dependencies...
AWS Pseudo Parameters


 
  Serverless Error ---------------------------------------
 
  AWS provider credentials not found. Learn how to set up AWS provider credentials in our docs here: <http://slss.io/aws-creds-setup>.
 
  Get Support --------------------------------------------
     Docs:          docs.serverless.com
     Bugs:          github.com/serverless/serverless/issues
     Issues:        forum.serverless.com
 
  Your Environment Information ---------------------------
     Operating System:          linux
     Node Version:              12.0.0
     Framework Version:         1.63.0
     Plugin Version:            3.3.0
     SDK Version:               2.3.0
     Components Core Version:   1.1.2
     Components CLI Version:    1.4.0

**Comment by ej2015** [comment] 2020-04-21 04:18
Seems to be working in Framework version 1.67.3 now, although probably better if the prompt can wait after 'Endter MFA code' line there. And it's printing out two digits for each I key in.

**Comment by medikoo** [comment] 2020-04-27 15:14
@ej2015 it's still not addressed. See: https://github.com/serverless/serverless/issues/6576#issuecomment-542769484. PR's welcome.

**Comment by medikoo** [comment] 2020-08-07 15:21
I've just looked into it more carefully, and yes, it appears it's no longer an issue.

Most likely it was an AWS SDK bug (as nothing really changed in Framework), where MFA callback was called right at it's registration and not at the point of first AWS request. It's no longer the case.

**Closed by medikoo** 2020-08-07 15:21 UTC
Labels: bug, cat/deployment, help wanted

**Comment by jernaumorat** [comment] 2022-08-15 04:34
I still have this issue when using `AWS_SDK_LOAD_CONFIG=1`:
```
$ aws --version
aws-cli/2.7.4 Python/3.9.13 Darwin/21.3.0 source/arm64 prompt/off
$ sls -v
Framework Core: 3.19.0
Plugin: 6.2.2
SDK: 4.3.2
```

MFA works without issue when using access keys, but when using cross-account roles I get the issue described in this thread.
