### ISSUE TITLE
2.32.0 disables CLI_OPTIONS

### ISSUE THREAD

**Issue by mcbain** [serverless/serverless#9208] opened 2021-03-31 10:06 UTC
The UNSUPPORTED_CLI_OPTIONS seem to be active by default in the release 2.32.0, the 2.31.0 works. 

https://www.serverless.com/framework/docs/deprecations/#UNSUPPORTED_CLI_OPTIONS

**Comment by medikoo** [comment] 2021-03-31 10:13
@mcbain can you provide more details?

The only thing that have changed between to versions, is that new variables resolver does not recognized unsupported CLI options. Still that's not breaking, as by default old variable resolver jumps in if new one errors. And in old one all works as it worked before.

If you feel there's a bug, it'll be great if you answer all questions of bug report (fill the `serverless.yml` example etc)

**Comment by JonAllanBlueberry** [comment] 2021-03-31 11:26
We are experiencing a similar issue.

We are deploying on AWS lambda.

Error from logs:
Serverless: Deprecation warning: Detected unrecgonized CLI options: "--stage-file".

This has killed our build process!

serverless file attached.

[newsstand-invoice-calculator_serverless.zip](https://github.com/serverless/serverless/files/6236205/newsstand-invoice-calculator_serverless.zip)

**Comment by mcbain** [comment] 2021-03-31 11:29
sls.yml
```
provider:
  name: aws
  runtime: nodejs14.x
  stage: ${self:custom.stage.${opt:branch, 'personal'}, opt:branch}
```

we deploy with `serverless deploy --branch abc`

warning `Serverless: Deprecation warning: Detected unrecgonized CLI options: "--branch".`

But then stage will be  `undefined`  as seen in  AWS resource names

**Comment by medikoo** [comment] 2021-03-31 11:32
Thanks for feedback, I believe I know where's an issue, and will prepare a fix.

Otherwise note that "Deprecation warning" is intended to be just a warning, and not an error. It's not expected to change anything in how deployment works.

Still in this case it looks new handling of CLI commands influenced some changes to variable resolution, fix is coming.

**Comment by JonAllanBlueberry** [comment] 2021-03-31 11:42
@medikoo sorry to jump in Mcbrian's post - I hope I am helping :) 

Can you estimate when you think you could push a fix? - I have an understandable frustrated client at the moment :)

**Comment by medikoo** [comment] 2021-03-31 11:46
> @medikoo sorry to jump in Mcbrian's post - I hope I am helping :)

Definitely, your feedback is very valuable. Thank you!

> Can you estimate when you think you could push a fix? - I have an understandable frustrated client at the moment :)

Within next hour I think new version with a fix will be released

**Closed** 2021-03-31 12:00 UTC
Labels: bug, cat/cli, cat/variable

**Comment by JonAllanBlueberry** [comment] 2021-03-31 12:14
@medikoo - I see the build has updated and I see changes in our logs - more information, however we are seeing the same result - build failed.

Here are the logs:

229 | Lambda project successfully packaged: /codebuild/output/src372525198/src/newsstand-invoice-calculator/bin/release/netcoreapp2.1/deploy-package.zip
230 | Serverless: Deprecation warning: Detected unrecgonized CLI options: "--stage-file".
231 | Starting with the next major, Serverless Framework will report them with a thrown error
232 | More Info: https://www.serverless.com/framework/docs/deprecations/#UNSUPPORTED_CLI_OPTIONS
233 | Serverless: Deprecation warning: Variables resolver reports following resolution errors:
234 | - Cannot resolve variable at "functions.service.tracing": Value not found at "self" source
235 | From a next major this will be communicated with a thrown error.
236 | Set "variablesResolutionMode: 20210326" in your service config, to adapt to new behavior now
237 | More Info: https://www.serverless.com/framework/docs/deprecations/#NEW_VARIABLES_RESOLVER
238 |  
239 | Serverless Warning --------------------------------------
240 |  
241 | A valid service attribute to satisfy the declaration 'self:custom.stages.uat.tracing' could not be found.
242 |  
243 | Serverless: Configuration warning:
244 | Serverless:   at 'functions.service.tracing': should be equal to one of the allowed values [Active, PassThrough]
245 | Serverless:   at 'provider': unrecognized property 'aws_unique_id'
246 | Serverless:
247 | Serverless: Learn more about configuration validation here: http://slss.io/configuration-validation
248 | Serverless:
249 | Serverless: Deprecation warning: Starting with next major, Serverless will throw on configuration errors by default. Adapt to this behavior now by adding "configValidationMode: error" to service configuration
250 | More Info: https://www.serverless.com/framework/docs/deprecations/#CONFIG_VALIDATION_MODE_DEFAULT
251 | Serverless: Packaging service...
252 | Serverless: Uploading CloudFormation file to S3...
253 | Serverless: Uploading artifacts...
254 | Serverless: Uploading service deploy-package.zip file to S3 (2.44 MB)...
255 | Serverless: Validating template...
256 | Serverless: Updating Stack...
257 | Serverless: Checking Stack update progress...

**Comment by medikoo** [comment] 2021-03-31 12:16
> @medikoo - I see the build has updated and I see changes in our logs - more information, however we are seeing the same result - build failed.

We haven't yet released the fix (it was just merged to master). Stay tuned, it'll be fixed with v2.32.1, which is now being rolled out.

If after it's published you still observe some issue, please open a new bug report and answer carefully all questions (we really need answers to all questions raised to be able to quickly coin the cause)

**Comment by JonAllanBlueberry** [comment] 2021-03-31 12:17
@thanks I am just too keen :)

**Comment by JonAllanBlueberry** [comment] 2021-03-31 13:22
3.32.1 fixed my issue @medikoo thank you so much!

**Comment by medikoo** [comment] 2021-03-31 13:23
@JonAllanBlueberry you're welcome!

**Comment by mcbain** [comment] 2021-04-01 09:08
from the docs: For that please ensure to add variablesResolutionMode: 20210326 to your service configuration.

After doing that we get:

Serverless: Configuration warning at 'variablesResolutionMode': should be equal to one of the allowed values [20210219]

**Comment by medikoo** [comment] 2021-04-01 09:19
@mcbain ensure to use latest version of a Framework, new value is not recognized until latest version.

**Comment by yhrabovskyinomi** [comment] 2021-04-01 14:16
@medikoo  Stupid question, but is there any chance we can pass custom CLI options in future? because there are definitely some usecases when we need to set dynamic variables , and using .env files will not help here

**Comment by medikoo** [comment] 2021-04-01 14:37
> @medikoo Stupid question, but is there any chance we can pass custom CLI options in future?

@yhrabovskyinomi As you can achieve same with env variables (e.g. `sls command --var=foo` can be achieved via
 `var=FOO sls command`) we do not consider that.

**Comment by mike-suggitt** [comment] 2021-06-17 14:59
> > @medikoo Stupid question, but is there any chance we can pass custom CLI options in future?
> 
> @yhrabovskyinomi As you can achieve same with env variables (e.g. `sls command --var=foo` can be achieved via
> `var=FOO sls command`) we do not consider that.

Really dislike this approach. I much prefer passing in command line args. Typos (as per the docs) should never be something a framework codes against and entirely at the responsibility of the developer using it. This is absolutely a backwards step

**Comment by medikoo** [comment] 2021-08-10 07:42
We're discussing support for arbitrary CLI options at #9817 

Any feedback is highly welcome
