### ISSUE TITLE
excludeDevDependencies: true adds >8 minutes to deploy?

### ISSUE THREAD

**Issue by jelder** [serverless/serverless#4426] opened 2017-10-30 14:07 UTC
Is 12 minutes to deploy typical for Serverless users?

In my particular setup, `excludeDevDependencies: true` adds more than 8 minutes to the deploy process. Without that option, the deployment fails because the .zip file is too big. I added some tracing to zipService.js and here's what I've found. At this point I'm just trying to determine if this is unusual. 

**TL;DR** globbing takes a full minute. Calling `npm --list` takes another 57 seconds. Assembling the .zip file takes _6 minutes_.

Each log statement is prefixed with the `[seconds, nanoseconds]` since the process started. 
Excerpt from running `serverless deploy`:
```
[ 12, 25190919 ] 'Starting excludeNodeDevDependencies'
[ 12, 47845106 ] 'Starting glob'
[ 72, 989709228 ] 'Globbed result is 1505 entries'
[ 73, 30495874 ] 'Calling npm for dev to /tmp/node-dependencies-fb71857233022597-dev'
[ 73, 118999339 ] 'Calling npm for prod to /tmp/node-dependencies-fb71857233022597-prod'
[ 130, 757156996 ] 'Reading and processing files dev to /tmp/node-dependencies-fb71857233022597-dev'
[ 130, 763286285 ] 'Reading and processing files prod to /tmp/node-dependencies-fb71857233022597-prod'
[ 130, 765558586 ] 'Have dev and prod dependencies'
[ 130, 800656639 ] 'Finished excludeNodeDevDependencies'
[ 130, 801608750 ] 'Setting params.include and .exclude'
[ 130, 802846434 ] 'Finished setting params.include and .exclude'
[ 559, 979770199 ] 'In zipFiles()'
[ 560, 7526350 ] 'Adding 20163 files to /usr/src/app/.serverless/saas-dash.zip'
```

To get these logs, I first added this at the top of the file.

```js
const time = process.hrtime();
```

Then, I added statements like this throughout every function (using `console.trace` didn't prove useful).

```js
console.log(process.hrtime(time), "Example"));
```

Full changes to zipService.js: https://github.com/serverless/serverless/compare/master...Blissfully:zipservice_tracing

## Additional Data

* ***Serverless Framework Version you're using***: 1.23.0
* ***Operating System***: Linux via Docker (node:6.10.1-alpine) on Mac

**Comment by horike37** [comment] 2017-11-05 16:12
Thanks @jelder for verifying the zipping process :100: 

>Is 12 minutes to deploy typical for Serverless users?

Umm, that would take too long from my experience :thinking: 
To get root cause, we might need more verification.

You might want to use `sls package` rather than `sls deploy` for the verification since `sls package` do only packaging process without deploy.
When you specify `excludeDevDependencies: false`, is the process faster than `excludeDevDependencies: true`?

**Comment by jelder** [comment] 2017-11-06 15:49
12 minutes was definitely too long for me, too. The solution we came up with a script which:

1) Creates a temporary directory
2) Copies `serverless.yml`, `package.json`, `yarn.lock`, and the application code into it
3) Run `yarn install --production --prefer-offline` in that directory. It's practically instant (well, on Linux; Docker for Mac is another story), even with 800 packages in `node_modules`, and results in a pristine build
4) Run `serverless deploy` in the temp directory

With `excludeDevDependencies: false`, the deploy is fast enough that its not a pain point for us.

**Comment by simlu** [comment] 2018-12-06 22:32
This pr might potentially fix this issue: https://github.com/serverless/serverless/pull/5574#issuecomment-445053851

Would you be able to test @jelder ?

**Comment by pmuens** [comment] 2019-01-15 13:06
Closing this this should've been fixed via #5574

**Closed by pmuens** 2019-01-15 13:06 UTC
Labels: bug

**Comment by FelschR** [comment] 2019-01-22 12:20
For me it's still taking quite a while on v1.36.1.
The whole deployment takes about half an hour currently, probably more.

I just tried setting `excludeDevDependencies` to false and it's down to just a few minutes now.
In my case I do exclude everything anyways and only include what I need manually at the moment so it's working for me.

Here is part of my config with one of my functions:
```yaml
package:
  individually: true
  # excludeDevDependencies: false
  exclude:
    - ./**

functions:
  createCase:
    handler: build/src/cases/createCase.handler
    package:
      include:
        - build/src/cases/createCase.js
        - build/src/common/**
        - node_modules/uuid/**
        - node_modules/rfc6902/**
```

I have more than 20 functions in total.

**Comment by simlu** [comment] 2019-01-22 22:52
@FelschR That's a weird setup. I don't understand how you have things set up or why this is necessary. But the excerpt here is that, while the speed has improved, it's unfortunately still possible to slow down the include / exclude logic. There are some other libraries to blame unfortunately (not sls) and ideally those should be fixed.

**Comment by bennbollay** [comment] 2019-02-26 05:19
Not to commit necromancy on this thread, but why isn't "exclude everything except for explicit includes" a weird setup?  It's exactly the design pattern I reached for, given my mono-repository project setup, and it takes ages to package on 1.36.1.

I'd definitely appreciate some better guidance on how to approach this.  The current solution I have involves explicitly specifying a whole bunch of excludes to avoid a `- ./**` exclude entry.

Note: I've been trying this with the changes from #5825 as well, and that hasn't particularly helped.

Currently, it takes about 16 seconds to do a single function package, or 30 seconds if I use the `./**` exclude.

**Comment by jjpxiii** [comment] 2019-03-07 14:19
This is the setup I also use.
The package operation is kinda faster with 1.36.1 but it still takes an awful lot of time so I tried to set ```excludeDevDependencies``` to ```false``` and got this : 
```Serverless: Packaging service...

<--- Last few GCs --->

[36612:0000025ECE13DE10]   315756 ms: Scavenge 1312.8 (1418.9) -> 1312.7 (1420.9) MB, 9.8 / 0.0 ms  (average mu = 0.155, current mu = 0.110) allocation failure
[36612:0000025ECE13DE10]   315769 ms: Scavenge 1314.6 (1420.9) -> 1314.3 (1422.4) MB, 8.0 / 0.0 ms  (average mu = 0.155, current mu = 0.110) allocation failure
[36612:0000025ECE13DE10]   315780 ms: Scavenge 1316.0 (1422.4) -> 1316.0 (1425.4) MB, 7.2 / 0.0 ms  (average mu = 0.155, current mu = 0.110) allocation failure


<--- JS stacktrace --->

==== JS stack trace =========================================

Security context: 0x0263ce19e6e1 <JSObject>
    0: builtin exit frame: new ArrayBuffer(aka ArrayBuffer)(this=0x026ce9582801 <the_hole>,4,0x026ce9582801 <the_hole>)

    1: ConstructFrame [pc: 00000260E1B8D385]
    2: StubFrame [pc: 00000260E1BD70D7]
    3: StubFrame [pc: 00000260E1BD89B1]
    4: getLongBytes [000000CBB257CD51] [C:\Users\jeanjeromep-aug\AppData\Roaming\npm\node_modules\serverless\node_modules\compress-commons\lib\archivers...

FATAL ERROR: Ineffective mark-compacts near heap limit Allocation failed - JavaScript heap out of memory
 1: 00007FF731BE0EFA v8::internal::GCIdleTimeHandler::GCIdleTimeHandler+4810
 2: 00007FF731BBA296 node::MakeCallback+4518
 3: 00007FF731BBAC80 node_module_register+2160
 4: 00007FF731E509BE v8::internal::FatalProcessOutOfMemory+846
 5: 00007FF731E508EF v8::internal::FatalProcessOutOfMemory+639
 6: 00007FF73238E954 v8::internal::Heap::MaxHeapGrowingFactor+11476
 7: 00007FF7323850B7 v8::internal::ScavengeJob::operator=+25543
 8: 00007FF73238362C v8::internal::ScavengeJob::operator=+18748
 9: 00007FF73238C5A7 v8::internal::Heap::MaxHeapGrowingFactor+2343
10: 00007FF73238C626 v8::internal::Heap::MaxHeapGrowingFactor+2470
11: 00007FF731F2F159 v8::internal::Factory::AllocateRawWithAllocationSite+105
12: 00007FF732141CAE v8::internal::Object::ToInt32+910
13: 00007FF7320E0E1A std::vector<v8::internal::compiler::MoveOperands * __ptr64,v8::internal::ZoneAllocator<v8::internal::compiler::MoveOperands * __ptr64> >::_Move_assign_from+87370
14: 00007FF7320E134B std::vector<v8::internal::compiler::MoveOperands * __ptr64,v8::internal::ZoneAllocator<v8::internal::compiler::MoveOperands * __ptr64> >::_Move_assign_from+88699
15: 00007FF7320E116B std::vector<v8::internal::compiler::MoveOperands * __ptr64,v8::internal::ZoneAllocator<v8::internal::compiler::MoveOperands * __ptr64> >::_Move_assign_from+88219
16: 00000260E1BDC721```

I guess sls and react-boilerplate aren't supposed to be used altogether.

**Comment by jkieberking** [comment] 2019-03-20 21:45
Don't know if this will be useful -

I had my `node_modules` symlinked to another directory inside a docker conainer I was deploying from and was also experiencing very long wait times while excluding dev dependencies.

moving the whole `node_modules` directory to the directory I was deploying from fixed it for me
