### ISSUE TITLE
Cannot install latest code using npm install inside the repo

### ISSUE THREAD

**Issue by rohendra** [serverless/serverless#12807] opened 2024-09-15 07:16 UTC
### Issue description

I want to get the latest code in main branch as it addresses issue #12799  faced my me.

How do I install directly from repo if the required changes are not yet published to npm registry?

*npm install* inside repo gives below error:

npm error code E404
npm error 404 Not Found - GET https://registry.npmjs.org/@serverlessinc%2fsf-core - Not found
npm error 404
npm error 404  '@serverlessinc/sf-core@*' is not in this registry.
npm error 404
npm error 404 Note that you can also install from a
npm error 404 tarball, folder, http url, or git url.

npm error A complete log of this run can be found in: /home/ubuntu/.npm/_logs/2024-09-15T06_53_29_580Z-debug-0.log

**Comment by brettdh** [comment] 2024-09-16 12:22
Duplicate of #12761.

**Comment by skierkowski** [comment] 2024-09-16 15:34
Closing as dup - https://github.com/serverless/serverless/issues/12761

**Closed by skierkowski** 2024-09-16 15:34 UTC
