### ISSUE TITLE
Add --config option to serverless doctor

### ISSUE THREAD

**Issue by talaikis** [serverless/serverless#10597] opened 2022-01-30 12:54 UTC
### Is there an existing issue for this?

- [X] I have searched existing issues, it hasn't been reported yet

### Use case description

Ability to run serverless doctor on custom config files.

**Comment by pgrzesik** [comment] 2022-01-31 10:12
Hello @talaikis - I think there might be a bit of a misunderstanding. `serverless doctor` reports the deprecations that were reported in the last command that you've run, so `--config` would be ineffective here. If you'd like to e.g. check the deprecations for a specific service, you can run `sls package --config <path>` and then `sls doctor`, but please keep in mind that not all deprecations might be reported for specific commands - that's why we cannot just have `sls doctor` report the deprecations directly. I'm going to close this one.

**Closed by pgrzesik** 2022-01-31 10:12 UTC

**Comment by talaikis** [comment] 2022-01-31 10:20
> Hello @talaikis - I think there might be a bit of a misunderstanding. `serverless doctor` reports the deprecations that were 

Well, actually `serverless doctor` shows exact deprecations only when we have `seerverless.yml` in root dir and gives just generic 'Thetre are x deprecations' when there are none.

**Comment by pgrzesik** [comment] 2022-01-31 10:25
I'm not sure exactly what do you mean by that, could you clarify @talaikis? The `serverless doctor` only reads the deprecations that were reported during the last command and reads it out from a stored file.

**Comment by talaikis** [comment] 2022-01-31 12:29
Let's say, we run several comnmands with different `.yml` files, all of them give `1 deprecation found: run 'serverless doctor' for more details`. Then we run `serverless doctor` and it gives `No deprecations were reported [in the last command]`.

**Comment by pgrzesik** [comment] 2022-01-31 12:36
Thanks for explaining @talaikis - I've just tried to reproduce but I could not - if deprecations were reported in the command then it showed up in the subsequent `sls doctor` command - could you provide a small reproducible example with steps that I could run on my side to aid with debugging of this issue? Please note that if you run e.g. command that produces deprecation, then one that does not produce the deprecation then `sls doctor` won't report anything - it only reports for the last command, not any previous ones.

**Comment by coyoteecd** [comment] 2022-02-07 08:48
@pgrzesik just some feedback, when seeing `1 deprecation found: run 'serverless doctor' for more details` I did assume that it would have to be run with a target config as well (and then got errors that it doesn't support the config param and ended up here). I think it's because as a user, we're focused on deploy/package/remove commands that all refer to a specific config.

Not sure how to improve, maybe just expanding the message a bit to `run 'serverless doctor` for more details about the last command`?

**Comment by mnapoli** [comment] 2022-02-07 10:28
Ah that's a good point @coyoteecd. "about the last command" is IMO a bit confusing since this message will be shown in the command with deprecations, so "last command" might be referring to the command that was run even before that 😄 

I think the answer is no, but @pgrzesik is there any possibility to make `serverless doctor`:

- either ignore any argument/option passed
- or throw a clear error if any extra argument/option is passed, like "The "serverless doctor" accepts no option, please run it again without CLI options"

**Comment by mnapoli** [comment] 2022-02-07 17:55
TBH I don't think "about the last command" adds extra information regarding CLI options, and it brings confusion that it's not really the last command that has deprecations, it's the current one?

Maybe we can keep an eye on this and see if there are more reports/more people confused by the command? You made a good point:

> actually the error message is pretty clear because it says that doctor does not support the provided option

**Comment by pgrzesik** [comment] 2022-02-07 20:15
Oh right, it still might be confusing what "last command" means - good point @mnapoli 👍 

Let's wait for more reports and we can try to find a better way to tweak this command then 👍

**Comment by hfhchan** [comment] 2022-12-01 10:19
When people see this message on the CI:
```
4 deprecations found: run 'serverless doctor' for more details
```

It's not immediately apparent you need to run `serverless doctor` on said CI in the same job.
Calling it locally gave an unhelpful `No deprecations were reported in the last command`.
