### ISSUE TITLE
Error deploying when one function name prepends another

### ISSUE THREAD

**Issue by lucascosta** [serverless/serverless#3228] opened 2017-02-10 16:27 UTC
# This is a Bug Report

## Description

For bug reports:
* What went wrong?
**Error when deploying two functions in which one function name prepends another (ex: `foo` and `foobar`**)

* What did you expect should have happened?
**I'd expect it to deploy normally.**

* What was the config you used?

`serverless.yml`:
```yml
service: name-collision

provider:
  name: aws
  runtime: python2.7

functions:
  foo:
    handler: handler.foo
  foobar:
    handler: handler.foobar
```
`handler.py`
```python
def foo(event, context):
    return {
        "message": "Hello",
        "event": event
    }


def foobar(event, context):
    return {
        "message": "Hello Sir",
        "event": event
    }

```

* What stacktrace or error message from your provider did you see?

```
Serverless: Deployment failed!

  Serverless Error ---------------------------------------

     An error occurred while provisioning your stack: IamPolicyLambdaExecution
     - Template error: LogGroup /aws/lambda/name-collision-dev-foo
     doesn't exist.

  Get Support --------------------------------------------
     Docs:          docs.serverless.com
     Bugs:          github.com/serverless/serverless/issues

  Your Environment Information -----------------------------
     OS:                 darwin
     Node Version:       5.4.1
     Serverless Version: 1.6.1
```

## Additional Data

* ***Serverless Framework Version you're using***: 1.6.1
* ***Operating System***: macOS Sierra

**Comment by geoffdutton** [comment] 2017-02-14 12:59
There's more discussion of this in #2614, it's a confirmed AWS issue.

**Comment by pmuens** [comment] 2017-03-09 12:57
Closing this since it's an AWS related problem...

**Closed by pmuens** 2017-03-09 12:57 UTC
Labels: kind/bug
