### ISSUE TITLE
sls deploy ignores changes to the scheduled events

### ISSUE THREAD

**Issue by codepreneur** [serverless/serverless#1805] opened 2016-08-09 15:06 UTC
##### Serverless Framework Version: 

```
1.0.0-beta.1
```

Well to be more accurate I am on `master` and this commit: `d1942f4937a85823f6f7deb9094bd32a4acdea`

##### Operating System: 

![image](https://cloud.githubusercontent.com/assets/3421858/16957931/5fe5d11e-4dd6-11e6-9d95-a5734cdee160.png)

##### Expected Behavior:

To change scheduled events from disabled to enabled and vice versa

##### Actual Behavior:

changing enabled from false to true like so:

```
functions:
  loadvideos:
    handler: handler.loadvideos
    events:
      - schedule: 
          rate: rate(1 minute)
          enabled: true
```

gets me nowhere:

![image](https://cloud.githubusercontent.com/assets/3421858/17521420/2e239e10-5e4b-11e6-9fc6-a4592b4b19f2.png)

`cloudformation`

![image](https://cloud.githubusercontent.com/assets/3421858/17521379/04fab604-5e4b-11e6-884d-bfbf721e518d.png)

 @pmuens ? @eahefnawy ? @wedgybo ?

**Comment by pmuens** [comment] 2016-08-09 16:47
Hey @codepreneur thanks for reporting (you're really rocking here as you're testing everything intensively 🎸 )

Here's the code which checks if the event is `enabled` / `disabled`:
https://github.com/serverless/serverless/blob/master/lib/plugins/aws/deploy/compile/events/schedule/index.js#L44

@eahefnawy do you know what's going on here? Is there maybe a problem with the parsing of boolean variables?

**Comment by eahefnawy** [comment] 2016-08-10 08:31
@codepreneur I just tried to reproduce and found that schedule deployment is working fine. However this seems to be an issue with AWS UI. The "Triggers" page of the lambda doesn't seem to reflect the real state. However if you go to the actual CloudWatch Rule page, you'll see that the state is reflected properly (deployment succeeded).

Could you confirm by visiting the CloudWatch Rule page and check the status?

**Comment by codepreneur** [comment] 2016-08-10 10:43
@eahefnawy CloudWatch Rule page is irrelevant, because when I deploy that function (with enabled: true) it does not run every minute, like its supposed to. I can try with a new (fresh) function and see what happens.

**Comment by codepreneur** [comment] 2016-08-11 17:32
OK, @eahefnawy this is what happens:

Before:

![image](https://cloud.githubusercontent.com/assets/3421858/17598068/b083d8ec-5ff0-11e6-91e3-9ed77f7e9060.png)


and

![image](https://cloud.githubusercontent.com/assets/3421858/17598101/d1804274-5ff0-11e6-98ff-621a42605938.png)


Then, I change this:

![image](https://cloud.githubusercontent.com/assets/3421858/17598035/86cac0b0-5ff0-11e6-94dc-963dba3758be.png)

to this:

![image](https://cloud.githubusercontent.com/assets/3421858/17598042/90a37442-5ff0-11e6-90b2-f4d355866258.png)

then `sls deploy` and...

![image](https://cloud.githubusercontent.com/assets/3421858/17598177/36c05a34-5ff1-11e6-9738-f5ba77594648.png)


and

![image](https://cloud.githubusercontent.com/assets/3421858/17598206/4abd28e6-5ff1-11e6-9ae8-a10da3e09b79.png)


But I can tell lambda is not running, because even after a while, searchable documents is still 0:

![image](https://cloud.githubusercontent.com/assets/3421858/17598307/c225a9d0-5ff1-11e6-9b47-febb318fc419.png)

Therefore I can definitely confirm that setting `enable: true` switches CloudWatch Rule green/on, but lambda trigger is not enabled and thus function does not run.

This is a bug, 500%.

**Comment by flomotlik** [comment] 2016-08-16 03:59
@codepreneur I've just tried this myself with the following:

```
service: random-service-name
provider:
  name: aws
  runtime: nodejs4.3
functions:
  hello:
    handler: handler.hello
    events:
      - schedule:
          rate: rate(1 minute)
          enabled: false
```

After that I've enabled it (false -> true) and checked the logs with `serverless logs -f hello -t` and I'm seeing the messages as they come in. Please make sure to check the logs if the functions get called properly as this might be an issue in the code. I'm closing this issue now as its confirmed it works in general. Please update if you could find out in case it isn't called.

**Closed by flomotlik** 2016-08-16 03:59 UTC
Labels: bug

**Comment by jairenee** [comment] 2019-06-13 18:44
Version 1.45.1 seeing similar behavior. Function deployed with schedule enabled. When adding `enabled: false`, schedule does NOT get disabled, and continues to run on schedule.
