### ISSUE TITLE
Adding custom attribute to Cognito user pool removes Cognito trigger lambda

### ISSUE THREAD

**Issue by chris** [serverless/serverless#9635] opened 2021-06-22 18:40 UTC
When changing an existing Cognito user pool, by adding a custom attribute, an existing lambda trigger is removed (even though it is still set as a trigger in serverless.yml). And by removed, I mean that in the Cognito user pool settings, it has set the trigger back to None (the lambda function itself is still deployed).

I have an existing, deployed Cognito user pool, and a lambda PostConfirmation trigger, with the event set as such:
```
    events:
      - cognitoUserPool:
          pool: my_user_pool 
          trigger: PostConfirmation
          existing: true
```

I update my Cognito user pool to add a custom attribute, e.g. in the `Resources` section I've updated the user pool to look like (note the `Schema` section at the end, which is where the custom attribute is defined):

```
Resources:
  MyUserPool:
    Type: AWS::Cognito::UserPool
    Properties:
      UserPoolName: my_user_pool
      UsernameAttributes: # use email as username/login
        - 'email'
      AutoVerifiedAttributes:
        - 'email'
      UsernameConfiguration:
        CaseSensitive: false
      Policies:
        PasswordPolicy:
          MinimumLength: 8
          RequireLowercase: true
          RequireNumbers: true
          RequireSymbols: false
          RequireUppercase: true
      AccountRecoverySetting:
        RecoveryMechanisms:
          - Name: verified_email
            Priority: 1
      VerificationMessageTemplate:
        DefaultEmailOption: CONFIRM_WITH_CODE
        EmailMessage: 'Thanks for signing up! Your verification code is {####}'
        EmailSubject: 'Your verification code'
      UserPoolTags:
        NatureDose: 'true'
      Schema: # Custom user attributes defined here
        - AttributeDataType: String
          Mutable: true
          Name: appID
```

I then deploy, to add the custom attribute. Upon doing so, the PostConfirmation trigger for my user pool has been removed. If I go into the AWS console and restore the PostConfirmation trigger, subsequent Serverless deploys don't remove it. This seems to be completely associated with adding custom attributes. I've seen this happen twice now (I actually have two custom attributes, and in both cases, it removed the trigger upon deploy of that change).

<details>
<summary><b><code>sls deploy</code></b></summary>

Deploy command output is standard successful deploy, with no specific Cognito information, etc.

</details>

<b>Installed version</b>

```
sls --version
Framework Core: 2.43.1 (standalone)
Plugin: 5.1.3
SDK: 4.2.2
Components: 3.10.0
```

**Comment by pgrzesik** [comment] 2021-06-25 07:52
Hello @chris - thanks for reporting and sorry you've run into trouble. Would you be able to share a minimal reproducible example that I could deploy on my side to try to replicate your issue?

**Comment by chris** [comment] 2021-06-26 22:31
Hi @pgrzesik sorry I didn't provide that - I was hoping the individual bits I provided might be enough. Below is what I think would cover it. You'll likely have to tweak the lambda function itself to point to something you have (I don't think it being Go has anything to do with it, as this seems totally about the Cognito CloudFormation parts, and the cognito trigger of the lambda function, but...?). Sorry, I don't mean to put the work on you, I hope this is sufficient, but if you can't repro, let me know. Here's what I think you'd do with this (after adding in an actual lambda function (that does nothing I believe should be fine)), in order to reproduce:

1. Add some basic lambda so this will deploy.
2. Deploy. This should setup the Cognito user pool, AND it should set the lambda to be the `PostConfirmation` trigger (double check this in the AWS console) for the user pool. It is possible that it won't, but this worked properly for me before (that said, I had already had my user pool in existance before I added this lambda).
3. Assuming the above is true (if not, you can manually set the lambda to be the `PostConfirmation` trigger), uncomment the `Schema` attribute (4 lines, at about line 84, within the `MyUserPool` resource definition. This is the section that will add a custom attribute to the Cognito user pool.
4. Deploy.
5. Go to the AWS console and look at the Triggers section for the user pool (refresh to make sure it's up to date, as they seem to cache this page). You should see that the `PostConfirmation` trigger is now set to `None`. And, if you look in the Attributes of the user pool, you should see the custom attribute. So, it adds the attribute, then for some reason removes the lambda trigger. 

At this point, even another deploy doesn't seem to fix/set the trigger back. I had to manually set the trigger in the console. Future deploys after I manually set it were fine (i.e. they didn't re-remove it). But, I saw this twice, as later I then added another custom attribute, and this same problem happened again (where it silently removed the trigger). This is pretty critical depending on how folks use it, as in my case, it would completley break my user signup process (as I need to sync the Cognito user into my DB and push some data back into the Cognito user, after they sign up - which is how I noticed it, since there were no errors or anything (I just noticed I had user sign up, but then not exist in my own DB).

serverless.yml:
```
service: cognito-test-api

frameworkVersion: '>=2.48.0 <3.0.0'

custom:
  defaultStage: dev

provider:
  name: aws
  runtime: go1.x
  region: us-east-2
  stage: ${opt:stage, self:custom.defaultStage}
  logs:
    # API Gateway logs ("restApi")
    restApi:
      level: INFO
  tracing:
    lambda: true
    apiGateway: true
  apiGateway:
    shouldStartNameWithService: true
plugins:
  - serverless-scriptable-plugin
  - serverless-iam-roles-per-function

package:
  # package individually due to Lambda package size limits and all the binaries we have
  # exclude:
  #   - ./**
  # include:
  #   - ./bin/**
  individually: true

functions:
  cognitoPostConfirmation:
    handler: bin/cognitotriggers/postconfirmation
    package:
      artifact: .serverless/cognitotriggerspostconfirmation.zip
    iamRoleStatements:
      # Cognito rights, for updating attributes
      - Effect: Allow
        Action:
          - cognito-idp:AdminUpdateUserAttributes
        Resource: '*'
    timeout: 5 # Cognito maximum response time, after which it retries
    events:
      - cognitoUserPool:
          pool: my_user_pool # note, can we reference this somehow?
          trigger: PostConfirmation
          existing: true
 
resources:
  #
  # Cognito user pool/auth setup
  #
  Resources:
    MyUserPool:
      Type: AWS::Cognito::UserPool
      Properties:
        UserPoolName: my_user_pool
        UsernameAttributes: # use email as username/login
          - 'email'
        AutoVerifiedAttributes:
          - 'email'
        UsernameConfiguration:
          CaseSensitive: false
        Policies:
          PasswordPolicy:
            MinimumLength: 8
            RequireLowercase: true
            RequireNumbers: true
            RequireSymbols: false
            RequireUppercase: true
        AccountRecoverySetting:
          RecoveryMechanisms:
            - Name: verified_email
              Priority: 1
        VerificationMessageTemplate:
          DefaultEmailOption: CONFIRM_WITH_CODE
          EmailMessage: 'Thanks for signing up with us! Your verification code is {####}'
          EmailSubject: 'Your verification code'
        UserPoolTags:
          My: 'true'
        # Schema: # Custom user attributes defined here
        #   - AttributeDataType: String
        #     Mutable: true
        #     Name: customAttr1

    MyCognitoClient:
      Type: AWS::Cognito::UserPoolClient
      Properties:
        ClientName: my_app_user_pool_client
        UserPoolId:
          Ref: MyUserPool
        AccessTokenValidity: 24 # hours
        IdTokenValidity: 24 # hours
        RefreshTokenValidity: 1825 # days - 5 years
    MyIdentityPool:
      Type: AWS::Cognito::IdentityPool
      Properties:
        IdentityPoolName: my_identity_pool
        AllowUnauthenticatedIdentities: false
        CognitoIdentityProviders:
          - ClientId:
              Ref: MyCognitoClient
            ProviderName:
              Fn::GetAtt: [MyUserPool, ProviderName]
    MyIdentityPoolRoles:
      Type: AWS::Cognito::IdentityPoolRoleAttachment
      Properties:
        IdentityPoolId:
          Ref: MyIdentityPool
        Roles:
          authenticated:
            Fn::GetAtt: [MyUserAuthRole, Arn]
          unauthenticated:
            Fn::GetAtt: [MyUserUnauthRole, Arn]
    MyUserAuthRole:
      Type: AWS::IAM::Role
      Properties:
        RoleName: MyUserAuthRole
        Path: /
        AssumeRolePolicyDocument:
          Version: '2012-10-17'
          Statement:
            - Effect: 'Allow'
              Principal:
                Federated: 'cognito-identity.amazonaws.com'
              Action:
                - 'sts:AssumeRoleWithWebIdentity'
              Condition:
                StringEquals:
                  'cognito-identity.amazonaws.com:aud':
                    Ref: MyIdentityPool
                'ForAnyValue:StringLike':
                  'cognito-identity.amazonaws.com:amr': authenticated
        Policies:
          - PolicyName: 'MyUserAuthorizedPolicy'
            PolicyDocument:
              Version: '2012-10-17'
              Statement:
                - Effect: 'Allow'
                  Action:
                    - 'mobileanalytics:PutEvents'
                    - 'cognito-sync:*'
                    - 'cognito-identity:*'
                  Resource: '*'
                - Effect: 'Allow'
                  Action:
                    - 'execute-api:Invoke'
                  Resource: '*'
    MyUserUnauthRole:
      Type: AWS::IAM::Role
      Properties:
        RoleName: MyUserUnauthRole
        Path: /
        AssumeRolePolicyDocument:
          Version: '2012-10-17'
          Statement:
            - Effect: 'Allow'
              Principal:
                Federated: 'cognito-identity.amazonaws.com'
              Action:
                - 'sts:AssumeRoleWithWebIdentity'
              Condition:
                StringEquals:
                  'cognito-identity.amazonaws.com:aud':
                    Ref: MyIdentityPool
                'ForAnyValue:StringLike':
                  'cognito-identity.amazonaws.com:amr': unauthenticated
        Policies:
          - PolicyName: 'MyUserUnauthorizedPolicy'
            PolicyDocument:
              Version: '2012-10-17'
              Statement:
                - Effect: 'Allow'
                  Action:
                    - 'mobileanalytics:PutEvents'
                    - 'cognito-sync:*'
                    - 'cognito-identity:*'
                  Resource: '*'

    MyAPIAuthorizer:
      Type: AWS::ApiGateway::Authorizer
      Properties:
        AuthorizerResultTtlInSeconds: 300
        AuthType: String
        IdentitySource: method.request.header.Authorization
        Name: MyAPIAuthorizer
        ProviderARNs:
          - Fn::GetAtt: [MyUserPool, Arn]
        RestApiId:
          Ref: ApiGatewayRestApi
        Type: COGNITO_USER_POOLS
```

**Comment by pgrzesik** [comment] 2021-07-01 10:03
Thanks @chris for a very detailed description - I'll try to reproduce the issue and hopefully I'll be able to find the root cause. I'll keep you posted :100:

**Comment by pgrzesik** [comment] 2021-07-02 14:35
Thanks again @chris for the details - I've managed to reproduce it and I believe I know what is the cause. In order to attach triggers to UserPool we're using CustomResources in CloudFormation, which underneath uses SDK calls to update to UserPool directly. However, when a UserPool changes (e.g. you add a new property in schema) it is updated by CloudFormation and clears the previously set triggers and as the inputs to CustomResource are static, update hook of that CustomResource is not triggered which means the triggers won't be re-esablished. This is a big limitation of how custom resources work and I'm not sure if there's a good way to "force" them to update in such situations where no actual properties related to custom resource change. I think one of the paths would be to replace CustomResource-based approach with direct SDK calls during deploy, but it also has it's downsides. 

@medikoo What is your opinion on the above? Do you know any techniques to force running `update` hook on CustomResource handlers, even if their inputs do not change?

**Comment by chris** [comment] 2021-07-02 16:29
@pgrzesik Thanks so much for digging into this! I think that unfortunately, while likely a very small number of folks are using this, it is (or could be) a very serious issue. I'm thinking that one option, at least until there's a solution, is maybe some kind of warning message or similar that a deploy spits out when it detects this configuration (or even the specific case that an attribute is being added on this particular deploy, if that's possible)? While some folks may not see it (or if done via CI it wouldn't help), it at least has a slight chance of telling someone they may need to manually fix things up?

**Comment by medikoo** [comment] 2021-07-05 10:24
@pgrzesik as we discussed on the call. It's probably best to introduce an opt-in way to enforce triggers setup in all cases (and that can probably be achieved by adding some random value to custom resource payload).

I would probably introduce a new `forceDeploy` property on event, which if set to true triggers generation of some random property on custom resource data

**Comment by pgrzesik** [comment] 2021-07-05 20:43
Thanks for your input @medikoo and for the detailed conversation that happened outside of this issue. 

@chris We've determined that the best way to move forward here will be to allow forcing update of the custom resource that backs that integration setup via `forceDeploy` property, which will ensure that randomly generated property will be passed into the Custom Resource, which will always trigger the update. 

As for the potential timeline for the implementation of this - I personally will be off for a few days this week, which means that I won't be able to work on it this week for sure.

**Comment by medikoo** [comment] 2021-07-06 07:09
Nonetheless I believe PR's are welcome!

**Comment by pgrzesik** [comment] 2021-07-06 07:49
@medikoo most definitely, I'm more than happy to provide guidance if anyone is interested in picking this one up :raised_hands:

**Comment by chris** [comment] 2021-09-06 16:53
I've noticed another case that causes these triggers to be removed. This is changing the `VerificationMessageTemplate` attribute in the `AWS::Cognito::UserPool` definition's `Properties`. I changed a value in that, and after deploy it removed my triggers again. So, my guess is maybe any change to Cognito resource will cause this problem.

**Comment by pgrzesik** [comment] 2021-09-08 08:56
Hello @chris - that is correct, any change to the properties of `Cognito` will trigger this issue as it causes the update of the resource `UserPool` via CloudFormation, which clears the triggers that are set up by CustomResource. The CustomResource itself is not updated because the input to it did not change.

**Comment by bldcaveman** [comment] 2021-10-04 13:44
I'm just dropping in to say I had this issue.
All my previously setup triggers got removed by subsequent deploys.

**Comment by aquachris** [comment] 2021-10-12 10:58
> @medikoo most definitely, I'm more than happy to provide guidance if anyone is interested in picking this one up 🙌

We've got this issue, and I'd be interested in trying my hand at implementing the proposed `forceDeploy` flag. Would like to take you up on that guidance offer - just pointing me to the right places.

**Comment by chris** [comment] 2021-10-15 19:23
@pgrzesik I am not familiar with the Serverless internals/implementation, but my guess would be you'd do two things:

1. Check any function to see if it has a `cognitoUserPool` event. These are the triggers and what get broken, so if no function has one of these, you're done. But if one does...
2. If the Resources section contains a `AWS::Cognito::UserPool` definition, and (part b) preferably - if you can see there were any changes to this definition. Part b would be ideal, as that'd truly mean you're detecting the scenario and the user's deploy will for sure be affected. But, if you can not do part b, even then I'd say it could be worth a "warning" message, something like, "You have Cognito triggered lambdas - if you made changes to your Cognito user pool, please check your triggers as they may have been removed. You can fix these manually in the AWS console, or do another Serverless deploy to re-instate them."

**Comment by TsimpDim** [comment] 2021-12-28 21:07
Hey @pgrzesik I may be able to work on this, but I would need some pointers.

I assume that the added `forceDeploy` flag would have to be added [here](https://github.com/serverless/serverless/blob/master/lib/plugins/aws/package/compile/events/cognitoUserPool.js). I'm not sure I totally get the expected changes for this part though

> which will ensure that randomly generated property will be passed into the Custom Resource, which will always trigger the update.

**Comment by mkucharek** [comment] 2022-08-17 13:06
Hey! just stumbled upon exactly the same issue and wanted to say that #10435 fixed that for us!

**Comment by medikoo** [comment] 2022-08-17 13:12
Closing, as I believe that's addressed now.

**Closed by medikoo** 2022-08-17 13:12 UTC
Labels: enhancement, help wanted, cat/aws-event-cognito, accepting-pr
