### ISSUE TITLE
ServerlessError

### ISSUE THREAD

**Issue by vinutha16** [serverless/serverless#6359] opened 2019-07-11 07:00 UTC
# This is a Bug Report

## Description

- What went wrong?
- What did you expect should have happened?
- What was the config you used?
- What stacktrace or error message from your provider did you see?

Similar or dependent issues:

- #12345

## Additional Data

- **_Serverless Framework Version you're using_**:
- **_Operating System_**:
- **_Stack Trace_**:
- **_Provider Error messages_**:

**Comment by pmuens** [comment] 2019-07-11 07:13
Closing this as it's a duplicate of https://github.com/serverless/serverless/issues/6360.

**Closed by pmuens** 2019-07-11 07:13 UTC
