### ISSUE TITLE
Serverless appears to corrupt binary node modules in its package

### ISSUE THREAD

**Issue by zol** [serverless/serverless#4202] opened 2017-09-04 22:18 UTC
# This is a Bug Report

## Description

Running my function on AWS Lambda results in this error:

```
{
  "errorMessage": "/var/task/dist/diff/node_modules/canvas/build/Release/canvas.node: ELF file's phentsize not the expected size",
  "errorType": "Error",
  "stackTrace": [
    "Error (native)",
    "Object.Module._extensions..node (module.js:597:18)",
    "Module.load (module.js:487:32)",
    "tryModuleLoad (module.js:446:12)",
    "Function.Module._load (module.js:438:3)",
    "Module.require (module.js:497:17)",
    "require (internal/module.js:20:19)",
    "Object.<anonymous> (/var/task/dist/diff/node_modules/canvas/lib/bindings.js:3:18)",
    "Module._compile (module.js:570:32)",
    "Object.Module._extensions..js (module.js:579:10)"
  ]
}
```

I noticed that `canvas.node` appears to be different (and corrupt) compared to the file on disk that gets zipped.

```
$ ./node_modules/.bin/serverless package
 
 Serverless Warning --------------------------------------
 
  A valid environment variable to satisfy the declaration 'env:staging_CHROMATIC_INDEX_URL' could not be found.
 
 
 Serverless Warning --------------------------------------
 
  A valid environment variable to satisfy the declaration 'env:staging_CHROMATIC_DIFF_URL' could not be found.
 
 
 Serverless Warning --------------------------------------
 
  A valid environment variable to satisfy the declaration 'env:staging_IGNORE_AWS_CREDENTIALS' could not be found.
 
Serverless: Packaging service...
Serverless: Excluding development dependencies...
Serverless: Excluding development dependencies...
[ec2-user@ip-172-31-1-106 lambda]$ cd temp
[ec2-user@ip-172-31-1-106 temp]$ unzip  ../.serverless/diff.zip "dist/diff/node_modules/canvas/build/Release/canvas.node"
Archive:  ../.serverless/diff.zip
  inflating: dist/diff/node_modules/canvas/build/Release/canvas.node  
[ec2-user@ip-172-31-1-106 temp]$ cd ..
[ec2-user@ip-172-31-1-106 lambda]$ diff temp/dist/diff/node_modules/canvas/build/Release/canvas.node ./dist/diff/node_modules/canvas/build/Release/canvas.node 
Binary files temp/dist/diff/node_modules/canvas/build/Release/canvas.node and ./dist/diff/node_modules/canvas/build/Release/canvas.node differ
[ec2-user@ip-172-31-1-106 lambda]$ file temp/dist/diff/node_modules/canvas/build/Release/canvas.node
temp/dist/diff/node_modules/canvas/build/Release/canvas.node: ELF 64-bit LSB shared object, x86-64, version 1 (SYSV), corrupted program header size, corrupted section header size
[ec2-user@ip-172-31-1-106 lambda]$ file ./dist/diff/node_modules/canvas/build/Release/canvas.node 
./dist/diff/node_modules/canvas/build/Release/canvas.node: ELF 64-bit LSB shared object, x86-64, version 1 (SYSV), dynamically linked, BuildID[sha1]=df73e87f004102ac8c687193aba8eb804c4875e9, not stripped
```

## Additional Data

* ***Serverless Framework Version you're using***: 1.21.0
* ***Operating System***: Linux ip-172-31-1-106 4.9.32-15.41.amzn1.x86_64 #1 SMP Thu Jun 22 06:20:54 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux
* ***Stack Trace***:
* ***Provider Error messages***:

**Comment by zol** [comment] 2017-09-04 22:29
This could be a dupe of #4182

**Comment by pmuens** [comment] 2017-09-05 06:26
Thanks for opening @zol 👍

Yes, that's a duplicate of #4182 so I'll close this one. A PR to fix this is already in the pipeline 💯!

**Closed by pmuens** 2017-09-05 06:26 UTC
Labels: kind/bug, status/help-wanted

**Comment by pmuens** [comment] 2017-09-06 08:04
Hey @zol 👋

Just wanted to post a quick update that we've published a path release which includes a fix for this issue (see: https://github.com/serverless/serverless/releases/tag/v1.21.1).

**Comment by zol** [comment] 2017-09-06 16:04
Thank you for letting me know @pmuens!

**Comment by pmuens** [comment] 2017-09-06 16:05
> Thank you for letting me know @pmuens!

🙌 Just drop us a line if you face any other issues!

**Comment by alexcasalboni** [comment] 2017-09-08 16:37
Thank you @zol & @pmuens, I've just run into this myself.

My scikit-learn model went crazy this morning :)

Tag @v1.21.1 works fine!

**Comment by pmuens** [comment] 2017-09-10 13:07
Great! Thanks for confirming @alexcasalboni 👍

**Comment by Dartv** [comment] 2020-06-24 15:15
I'm having the exact same error and using latest serverless
