### ISSUE TITLE
Custom fonts for AWS Labmda

### ISSUE THREAD

**Issue by SashaShostyr** [serverless/serverless#9285] opened 2021-04-12 09:06 UTC
Is it possible to provide custom fonts for AWS Lambda function? Show an example if it is possible, please.

**Comment by pgrzesik** [comment] 2021-04-12 09:13
Hello @SashaShostyr I'm closing this one as it's not a bug report/enhancement proposal. For these, please create a Github Discussion or a post on our forum - forum.serverless.com

**Closed by pgrzesik** 2021-04-12 09:13 UTC
