### ISSUE TITLE
Cannot use Serverless variables in provider 1.0.2

### ISSUE THREAD

**Issue by jordanmack** [serverless/serverless#2389] opened 2016-10-14 22:39 UTC
# This is a Bug Report
## Description
- What went wrong?

When trying to use a Serverless variable for the provider in serverless.yml the following error was received:

```
     Provider "${file(../lib/mixins.yml):provider}" is not
     supported. Valid values for provider are: aws, azure,
     google, ibm. Please provide one of those values to the
     "provider" property in serverless.yml.
```
- What did you expect should have happened?

It should have parsed the variable normally.
- What was the config you used?

serverless.yml:

```
service: test

provider: ${file(./serverless-mixins.yml):providerDefault}

functions:
  hello:
    handler: handler.hello
```

serverless-mixins.yml:

```
providerDefault:
  name: aws
  runtime: nodejs4.3
```
- What stacktrace or error message from your provider did you see?

See above.
## Additional Data
- **_Serverless Framework Version you're using**_: 1.0.2
- **_Operating System**_: Windows 10 x64
- **_Stack Trace**_: N/A
- **_Provider Error messages**_: See above.

**Comment by dougmoscrop** [comment] 2016-10-15 16:36
I think this is basically the same type of problem as #2269 which is to say, the variable expansion happens after the YML file is loaded, and certain things are validated before variable expansion, because otherwise `--help` calls can fail (imagine you had like `${file(./${opt:stage}/serverless-mixins.yml)`

So it can be fixed by moving the variable expansion back to before displaying help, which means that any unspecified variables would prefer --help from being displayed.

**Comment by dougmoscrop** [comment] 2016-10-15 16:38
@flomotlik @pmuens on a larger design scale, maybe what has to happen is serverless has a config object inside the yml file, which can load things from env, opt, etc. but you MUST specify defaults. And then "variable expansions" within the YML file can only reference "config" vars, so that the file can be loaded/parsed/expanded with 'defaults'.

**Comment by pmuens** [comment] 2016-12-13 10:00
@jordanmack thanks for reporting. I can confirm that this bug still persists.

@dougmoscrop thanks for the proposal. Sounds good!
Ccing @eahefnawy as he authored the variable system!

**Comment by pmuens** [comment] 2017-05-19 14:01
Closing this issue since it's stale and we've pushed lots of changes to the variable system in the past. Feel free to re-open if this is still an issue.

**Closed by pmuens** 2017-05-19 14:01 UTC
Labels: kind/bug, stage/accepted
