### ISSUE TITLE
environment.variables' failed to satisfy constraint on defining _JAVA_OPTIONS for java runtimes in lambda

### ISSUE THREAD

**Issue by AnupamJuniwal** [serverless/serverless#8564] opened 2020-12-01 04:44 UTC
I wanted to define and override some default JVM arguments that are placed by lambda by default, which I was able to do locally using `sam local` and `_JAVA_OPTIONS`. But when publishing the application to the cloud it seems like there is a constraint because of which I won't be able to define any env variables starting with `_` which does not make sense to me.
 

<details>
<summary><code>serverless.yml</code></summary>

```yaml
Globals:
  Function:
    Environment:
      Variables:
        _JAVA_OPTIONS: -Xshare:off
```

</details>

**Comment by medikoo** [comment] 2020-12-01 11:07
@AnupamJuniwal this tracker is purely for confirmed bug reports and feature requests.

For general support please check:
- https://forum.serverless.com/
- https://www.serverless.com/slack
- http://stackoverflow.com/questions/tagged/serverless-framework

**Comment by yyamano** [comment] 2020-12-21 00:54
@AnupamJuniwal You can pass JVM options via the environment variable JAVA_TOOL_OPTIONS. But I'm not sure if it works for -Xshare:off.

See https://docs.aws.amazon.com/lambda/latest/dg/runtimes-modify.html and https://stackoverflow.com/questions/46669693/setting-java-aws-lambda-vm-parameters for more details.

**Comment by AnupamJuniwal** [comment] 2020-12-21 04:26
@yyamano `JAVA_TOOL_OPTIONS` works for Corretto flavours as there ins no `-Xshare:on`, still with the Java-8 (non-corretto) flavour, the `-Xsahre:on` switch is passed to the vm, this was the main reason why use of `_JAVA_OPTIONS`(overriding cmdline args) was required for our case.

**Comment by medikoo** [comment] 2020-12-21 13:02
Closing, as it's not intended to be a general support board

**Closed by medikoo** 2020-12-21 13:02 UTC
Labels: question
