### ISSUE TITLE
Java Support

### ISSUE THREAD

**Issue by ac360** [serverless/serverless#682] opened 2016-02-20 00:49 UTC

**Comment by rehrumesh** [comment] 2016-03-06 17:05
Hi I would love to contribute to this, Can describe more?

**Comment by pmuens** [comment] 2016-03-06 18:08
Hey @rehrumesh thank you for your interest to contribute to Serverless!

Right now Serverless supports Node.js and Python as a runtime we would like to include Java as well (as it's supported by AWS Lambda).

Python was recently implemented. You can take a look at the corresponding issue here:
https://github.com/serverless/serverless/pull/507

Let me know if you have any additional questions!

**Comment by rehrumesh** [comment] 2016-03-07 03:00
:+1: I'll throw questions on the way. Meantime I'll slowly start working on it :)

**Comment by cagataygurturk** [comment] 2016-03-13 12:10
Hi, I am developing a JAVA framework for Lambda and I'll publish it this week.

My project has a bit different approach than serverless, actually it is a JAX-RS implementation for AWS Lambda, meaning that any existing JAX-RS application can be migrated to JAVA with this framework and also projects written for this framework are already compatible with other JAX-RS implementations such as Jersey. The only necessary step will be adding the framework as a maven dependency, and the framework will create the corresponding endpoints in API Gateway scanning JAX-RS annotations.

If you are interested about that I'll be posting the details in this thread.

**Comment by dijitalmunky** [comment] 2016-03-30 22:44
Hrm, would this just be a new runtime class the way that Python and node are now?  If so, I'd love to help out (it might only be on the testing side, depending how much time I can find).

**Comment by russellwhitaker** [comment] 2016-04-08 23:52
@cagataygurturk do tell, please.

@dijitalmunky would be especially interesting if non-Java JVM languages like Clojure & Scala could hook into that.

**Comment by cagataygurturk** [comment] 2016-04-09 04:29
Here you go: https://github.com/lambadaframework/lambadaframework

**Comment by pmpavlov** [comment] 2016-04-20 13:42
When the new runtime environment will be ready to test . We are working on a project that we won't to use java as runtime environment . It will be very helpful if we can use serverless with java8 runtime environment to control all the functions and endpoints with serverless . Can you give us any ETA for finishing the addition

**Comment by eahefnawy** [comment] 2016-04-22 05:22
@pmpavlov Unfortunately none of the core team members have experience with Java, so we're a bit slow in that front. We'd LOVE some help on this though!

**Comment by cagataygurturk** [comment] 2016-04-22 06:39
@pmpavlov my comment above could help you to build your project in java

**Comment by pmpavlov** [comment] 2016-04-22 13:41
ok i will try to use that for now but it is much nicer when you have serverless to manage your function and endpoints . I hope this is finished in the next month so i can use it .

**Comment by hakandilek** [comment] 2016-05-06 15:23
Please check out my PR which scaffolds, compiles Java endpoints. Local runs are working, building and uploading is still WIP.

**Comment by flomotlik** [comment] 2016-05-12 09:31
@hakandilek thanks for your PR, looking through it at the moment. We definitely need stronger Java support in the future. One of the challenges is implementing Java support independently of specific build tools (e.g. Maven or Gradle) so teams can use any kind of tool, create their Jar files and we can deploy it for them.

**Comment by jarikujansuu** [comment] 2016-05-30 21:16
Tool independent JVM support would be great, it would allow all non-Java JVM languages at same time. We would most likely want to use API Gateway & Lambda with Scala so that would be helpful for us. Will see if I could somehow help getting JVM support to Serverless.

**Comment by mamidipalli** [comment] 2016-07-01 03:05
Team, how is this coming up?

**Comment by pmuens** [comment] 2016-07-01 07:33
Hey guys. Thank you for the interesting discussion here so far!

We're currently working on this and have put it on our roadmap for an upcoming, next alpha release!

**Comment by flomotlik** [comment] 2016-08-05 07:21
resolved in #1672

**Closed by flomotlik** 2016-08-05 07:21 UTC
Labels: discussion

**Comment by inakianduaga** [comment] 2016-08-18 14:40
Is Scala supported by the framework? 

I'm using AWS lambdas w/ Scala using Sbt for the build, just taking care of a few things in the lambda input/out to play nice w/ Java. But I don't know if this could be adapted to use the serverless framework

**Comment by flomotlik** [comment] 2016-08-18 14:44
Serverless itself is language independent (especially on the Java side). Currently we don't have a template for Scala/SBT *Hint Hint* but we do have examples for Maven and Gradle with Java. Starting with one of those it should be trivial to get your deployment up and running. Basically all you need to do is either create an artefact yourself and use the package/artifact config variable: https://github.com/serverless/serverless/blob/master/docs/understanding-serverless/serverless-yml.md (they are also used for Maven/Gradle so easy to copy from there) or you put all your files in a specific place and configure the include/exclude variables so we build the zip artefact for you and then deploy it.

**Comment by inakianduaga** [comment] 2016-08-18 14:46
@flomotlik Cool I was too lazy to try it, I'll give it a go now that I know it's possible.

**Comment by flomotlik** [comment] 2016-08-18 14:49
Yeah basically what Serverless does for you is package and deploy your artefact. As long as you can run it on Lambda it doesn't matter to us what we deploy basically.

**Comment by orubel** [comment] 2016-09-09 15:08
@cagataygurturk JAX-RS creates a binding to business logic creating an architectural cross cutting concern. I've spoken about this twice at SpringOne and am speaking about this at API World next week during a talk called 'The New API Pattern'

JAX-RS was based on the OLD API Pattern which was designed for CENTRALIZED Architecture (ie one app, one server). It is not intended for an application where services are distributed across multiple servers and share I/O.

For that, you need an API Pattern that Abstracts communication from Business Logic and can synchronize I/O data and functionality across the architecture.

JAX-RS is an old paradigm much like Lambdas in that they can't share their I/O state.

**Comment by cagataygurturk** [comment] 2016-09-09 15:37
You might be right @orubel about your thought about JAX-RS. Actually Lambada framework has been designed for migrating already developed applications easily  to lambda.

By the way now Cloudformation is also supporting API Gateway. With maven/gradle compiling the code to a JAR and A Cloudformation template as a glue between API Gateway and Lambda, it is pretty easy to develop a JAVA application. Therefore for JAVA stack I don't see any benefit of Serverless framework. Actually I am strongly against the usage of a JS library in a JAVA project for the sake of language purity.

I have serious study about that and soon I will share a boilerplate project to show how to achieve JAVA deployment to AWS only with Gradle.

**Comment by ayush** [comment] 2016-09-20 16:14
@cagataygurturk Good stuff! Lambada framework is really interesting and seems like an easy way to get from Java to Lambda/Gateway driven REST apis. 

> Therefore for JAVA stack I don't see any benefit of Serverless framework. 

I guess that depends on what the needs are. It looks like Serverless framework has more going on especially with the ability to [trigger lambdas from SNS/Schedule/S3](https://github.com/serverless/serverless/blob/master/docs/02-providers/aws/events/README.md) etc.

**Comment by cagataygurturk** [comment] 2016-09-20 16:47
@ayush , triggering lambda via cloud events like s3 etc. is not a serverless-exclusive feature. Serverless is just providing an easy interface to bind those event to Lambda. If your deployment is pure Cloudformation or you wrote your deployment script, you can accomplish the same result. What serverless does is to provide a shortcut,  the underlying functionality is provided by AWS itself.

**Comment by ayush** [comment] 2016-09-20 17:28
@cagataygurturk sure, but these shortcuts/easy-interfaces is where the value of these frameworks is. JAX-RS is http centric, perhaps Lambada framework could support some custom annotations which go beyond JAX-RS and automate bindings to SNS/S3/Scheduling etc.

**Comment by bbilger** [comment] 2016-10-27 23:03
You might want to check out https://github.com/bbilger/jrestless, as well. It's a Jersey container for AWS Lambda and provides JAX-RS functionality through Jersey - the reference implementation for JAX-RS. This allows usage of most JAX-RS features and gives Spring integration, too. You can use serverless to configure and deploy your Lambda functions, as well.

@orubel I don't see why JAX-RS is based on the "OLD API pattern" and "is designed for CENTRALIZED Architecture". JAX-RS is just a standard for Java to write RESTful web services and can, for example, be used for microservices, as well (e.g. Dropwizard uses it). Maybe I am missing your point but I don't see how JAX-RS contradicts with "The New API Pattern". I mean one needs some way to define and develop endpoints/controllers, request-filters, etc.. Using JAX-RS in an AWS Lambda function might be overkill if you use them to develop nanoservices (one endpoint per Lambda function) but if you are using it to develop microservices (multiple endpoints per Lambda function) it's really helpful to route a request (could be a chained one, too) to an endpoint, map the request data to an object (assuming one doesn't want to use AWS API Gateway mapping templates for this), etc. In my opinion using JAX-RS or another standard for another language in whatever form or with whatever framework helps to abstract away AWS Lambda and AWS API Gateway specifics, allowing you to avoid the vendor lock-in and to develop/test/run your application locally.

**Comment by bleshik** [comment] 2016-10-28 04:47
@bbilger Seems like everyone creates AWS Lambda adapters for JAX-RS nowadays. Here is mine as well: https://github.com/bleshik/aws-lambda-servlet :)
BTW, my adapter works with any servlets, not only with JAX-RS implementations.

@orubel come on, JAX-RS is still a very nice API for mapping HTTP requests. Not sure, how it can stop you from running multiple instances of a JAX-RS implementation.
