### ISSUE TITLE
`remove` CLI command not found

### ISSUE THREAD

**Issue by lpil** [serverless/serverless#2163] opened 2016-09-19 13:34 UTC
# This is a Bug Report

## Description

For bug reports:

When running `sls remove` I am presented with an unknown command error, even though the help page lists the command as being valid.

This error started occurring today for multiple members of my team.

```
louis ~/projects/website-honestly [multiple-stacks] $ serverless help

Commands
* Serverless documentation: http://docs.serverless.com
* You can run commands with "serverless" or the shortcut "sls"
* Pass "--help" after any <command> for contextual help

create ................... Create new Serverless Service.
deploy ................... Deploy Service.
deploy function .......... Deploys a single function from the service
info ..................... Displays information about the service.
invoke ................... Invokes a deployed function.
logs ..................... Outputs the logs of a deployed function.
remove ................... Remove resources.
tracking ................. Enable or disable usage tracking.

Plugins
AwsCompileApigEvents, AwsCompileFunctions, AwsCompileS3Events, AwsCompileSNSEvents, AwsCompileScheduledEvents, AwsDeploy, AwsDeployFunction, AwsInfo, AwsInvoke, AwsLogs, AwsRemove, Create, Deploy, Info, Invoke, Logs, Package, Remove, Tracking
louis ~/projects/website-honestly [multiple-stacks] $ serverless remove
 
  Serverless Error ---------------------------------------
 
     The command you entered was not found.
     Did you
     spell it correctly?
 
  Get Support --------------------------------------------
     Docs:          docs.serverless.com
     Bugs:          github.com/serverless/serverless/issues
``` 

## Additional Data

* ***Serverless Framework Version***: 1.0.0-rc.1
* ***Operating System***: OSX, Ubuntu Linux

**Comment by flomotlik** [comment] 2016-09-20 11:08
@lpil thanks, we've seen this as well, but don't know yet why this happens. Will investigate.

**Comment by flomotlik** [comment] 2016-09-20 13:23
@lpil we were now able to reproduce this bug in folders that don't have a `serverless.yml` file. Is the same happening for you in a folder with a serverless.yml as well? If yes could you post this?

In any case we'll need to resolve this and make sure the correct error message is shown.

**Comment by flomotlik** [comment] 2016-09-23 10:27
ok so basically the way we detect to current folder doesn't seem to take this into account then. We'll have to look into this deeper to see how we can fix this.

**Comment by dougmoscrop** [comment] 2016-09-24 16:47
The reason this happens is because no plugins attach hooks to the events. It's "fixed" with a more specific error message in my PluginManager refactor PR

**Comment by dougmoscrop** [comment] 2016-09-24 16:49
(at least if that's the case you can troubleshoot why no plugins hook, I.e. provider mismatched)

**Comment by flomotlik** [comment] 2016-09-26 06:12
Awesome @dougmoscrop , will review today (sorry for the delay)

**Comment by dougmoscrop** [comment] 2016-10-05 15:50
My change has been merged so you should now see the 'not caught on hooks' message. This could be because the serverless configuration does not specify a provider, so the AWS Plugins do not load, which means there's nothing attached to those lifecycleevents.

**Closed** 2016-10-18 17:40 UTC
Labels: bug, help-wanted
