### ISSUE TITLE
Variable resolution broken in 1.30.0

### ISSUE THREAD

**Issue by edholland** [serverless/serverless#5216] opened 2018-08-15 21:35 UTC
# This is a Bug Report

## Description

For bug reports:
* What went wrong?

Variable are being replaced several times in CFN generation.

`Resource: "arn:aws:dynamodb:${opt:region, self:provider.region}:*:table/${self:provider.environment.SURFACES_TABLE}"`

 is becoming 

`"Resource": "arn:aws:dynamodb:eu-west-1:*:table/heat-exchanger-simulator-heat-exchanger-simulator-arn:aws:dynamodb:eu-west-1:*:table/heat-exchanger-simulator-heat-exchanger-simulator-dev-surfaces-surfaces-surfaces-surfaces"` 

in the generated CFN rather than 

`arn:aws:dynamodb:eu-west-1:*:table/heat-exchanger-simulator-dev-surfaces`

* What did you expect should have happened?
`arn:aws:dynamodb:eu-west-1:*:table/heat-exchanger-simulator-dev-surfaces`
* What was the config you used?
serverless 1.30.0 - 1.29.2 is not affected
* What stacktrace or error message from your provider did you see?

For feature proposals:
* What is the use case that should be solved. The more detail you describe this in the easier it is to understand for us.
* If there is additional config how would it look

Similar or dependent issues:
* #5156

## Additional Data

* ***Serverless Framework Version you're using***: 1.30.0
* ***Operating System***: ubuntu, debian, mac
* ***Stack Trace***: n/a
* ***Provider Error messages***: n/a

**Comment by mfalcier** [comment] 2018-08-16 07:00
We're experiencing the same issue after upgrading to Serverless 1.30.
We avoided this problem replacing `${opt:region, self:provider.region}` with `${self:provider.region}` since we deploy only in one region.
We also experienced the same problem using `${opt:stage, self:provider.stage}`, replaced again with `${self:provider.stage}`.
There is probably a bug with that operator.

**Comment by dschep** [comment] 2018-08-16 12:55
I think this is a duplicate of #5205

**Comment by erikerikson** [comment] 2018-08-17 00:04
Looking into this.  Apologies for the issue.

**Comment by erikerikson** [comment] 2018-08-17 01:47
Fix offered on #5224.  See #5205 or PR for explanation.  Please try it out and be sure to let me know if I missed anything in your config.  We continue building out the case coverage.  Thanks for reporting and apologies for the friction!

**Closed** 2018-08-20 16:05 UTC

**Comment by williamdenton** [comment] 2018-08-27 03:37
Thank for this fix. when will the next release be created with this incorporated? `1.30.2`?

**Comment by erikerikson** [comment] 2018-08-28 19:42
Yes @williamdenton: this change was published on 2018-08-28T13:46:44Z in 1.32.2 as noted in the [changelog](https://github.com/serverless/serverless/blob/b2a0b232af725745e9b71b9b3c031cc3fa40de14/CHANGELOG.md).
