### ISSUE TITLE
httpApi custom authorizer does not work by the docs

### ISSUE THREAD

**Issue by srodriki** [serverless/serverless#11580] opened 2022-12-06 14:00 UTC
### Are you certain it's a bug?

- [X] Yes, it looks like a bug

### Is the issue caused by a plugin?

- [X] It is not a plugin issue

### Are you using the latest v3 release?

- [X] Yes, I'm using the latest v3 release

### Is there an existing issue for this?

- [X] I have searched existing issues, it hasn't been reported yet

### Issue description

**Description**

Serverless doesn't allow for custom httpApi authorizers as shown in the documentation.

**Steps to reproduce**

1. Create a simple project using the following serverless.yml definition as found [here](https://www.serverless.com/framework/docs/providers/aws/events/http-api)

```yml
provider:
  name: aws
  httpApi:
    authorizers:
      customAuthorizer:
        type: request
        functionName: authorizerFunc

functions:
  hello:
    handler: handler.hello
    events:
      - httpApi:
          method: get
          path: /hello
          authorizer:
            name: customAuthorizer

  authorizerFunc:
    handler: authorizer.handler

```

2. Run the project using serverless-offline (alternatively, try to deploy it to AWS).

**Expected result**
The API runs normally and the endpoint gets protected by my custom JWT authorizer function.

**Actual result**

The command throws the following error: `Function "authorizerFunc" doesn't exist in this Service`

### Service configuration (serverless.yml) content

```yaml
service: mysimple-api
frameworkVersion: '3'
useDotenv: true

plugins:
  - serverless-dotenv-plugin
  - serverless-offline

provider:
  name: aws
  runtime: nodejs18.x
  versionFunctions: false
  stage: ${opt:stage, 'dev1'}
  region: us-east-1
  memorySize: 512
  timeout: 30
  logRetentionInDays: 30
  environment:
    STAGE: ${self:provider.stage}
    AWS_ACCOUNT_ID: "#{AWS::AccountId}"
  iam:
    role: 
      statements:
        - Effect: Allow
          Action:
            - sns:Publish
            - s3:*
            - lambda:*
            - sqs:*
            - apigateway:*
            - dynamodb:*
          Resource: "*"
  httpApi:
    cors: true
    authorizers:
      customAuthorizer:
        type: request
        functionName: authorizerFunc

functions:

  hello:
    handler: hello/handler.hello
    maximumRetryAttempts: 0
    events:
      - httpApi:
          path: /hello
          method: GET
          cors: true
          authorizer: 
            name: customAuthorizer

  authorizerFunc:
    handler: auth.jwtAuth
```

### Command name and used flags

serverless offline 

### Command output

```shell
Starting Offline at stage local (us-east-1)

Offline [http for lambda] listening on http://localhost:3002
Function names exposed for local invocation by aws-sdk:
           * hello: twittercom-api-local-hello
           * authorizerFunc: twittercom-api-local-authorizerFunc
Configuring Authorization: /hello authorizerFunc
Environment: darwin, node 18.12.1, framework 3.25.0 (local), plugin 6.2.2, SDK 4.3.2
Docs:        docs.serverless.com
Support:     forum.serverless.com
Bugs:        github.com/serverless/serverless/issues

Error:
Function "authorizerFunc" doesn't exist in this Service
```

### Environment information

```shell
Running "serverless" from node_modules
Framework Core: 3.25.0 (local) 3.25.0 (global)
Plugin: 6.2.2
SDK: 4.3.2
```

**Comment by medikoo** [comment] 2022-12-06 14:09
@srodriki If you observe this issue just with the `offline` command, please report it to the `serverless-offline` plugin repository.

**Comment by srodriki** [comment] 2022-12-07 16:50
Hey @medikoo thank you for your assitance. It is also happening when deploying to AWS. 

Nevertheless I also opened a [ticket on the serverless-offline repo](https://github.com/dherault/serverless-offline/issues/1624) and one of the maintainers confirmed the error's source seems to come from the serverless package itself.

Is it possible for you to take a look? 

Thanks

**Comment by medikoo** [comment] 2022-12-07 16:59
@srodriki can we close it? As apparently it's not an issue in the Framework

**Comment by srodriki** [comment] 2022-12-07 17:11
@medikoo maybe I didn't express myself properly. It appears to be an issue in the Framework. It's happening both with serverless-offline and doing a deploy to AWS.

**Comment by medikoo** [comment] 2022-12-07 19:08
@srodriki can you create a reproduction case that doesn't involve any plugins?

**Comment by dnalborczyk** [comment] 2022-12-07 20:39
@medikoo  I had a quick look, I think @srodriki 's example is taken from the serverless docs:   [Lambda (Request) Authorizers](https://www.serverless.com/framework/docs/providers/aws/events/http-api#lambda-request-authorizers)

it's possible it's just a documentation issue. the error thrown by serverless: `Function "customAuthorizer" doesn't exist in this Service`.

current doc:
```yml
    events:
        - httpApi:
            authorizer:
                name: customAuthorizer
```

might need to be:
```yml
    events:
        - httpApi:
            authorizer:
                name: authorizerFunc
```

**Comment by medikoo** [comment] 2022-12-08 11:09
@dnalborczyk I believe the example is correct as by `name` we reference authorizer as defined in top level `provider.httpApi.authorisers` section. (function is referenced in this section under `functionName` property)

If you feel it's otherwise can you show full `serverless.yml` with which you get the such error?

**Comment by dnalborczyk** [comment] 2022-12-08 15:04
just tried to deploy to AWS and it appears to work. the error is being thrown here: https://github.com/serverless/serverless/blob/9a414683090cb3edcac61d9a782c4d136f18c6f6/lib/classes/service.js#L322 likely by an invocation by `serverless-offline`.  I thought we had test cases for this scenario. 🤔 

@srodriki I'll reopen your issue.  @medikoo this issue can be closed.

**Closed** 2022-12-08 15:06 UTC
Labels: question

**Comment by zaus** [comment] 2024-06-17 20:18
Because I somehow ended up here while searching for what seemed like the same problem and was banging my head against a wall, make sure to pay attention to the difference between HTTP (this issue) and REST (what I was using) style declarations:

- HTTP v2 [docs](https://www.serverless.com/framework/docs/providers/aws/events/http-api#using-function-defined-outside-of-your-service-as-an-authorizer) when your function event is `httpApi`, add `provider > httpApi > authorizers > yourCustomAuthorizer > functionArn` and reference in event using `authorizer > name: yourCustomAuthorizer`
- REST v1 [docs](https://www.serverless.com/framework/docs/providers/aws/events/apigateway#http-endpoints-with-custom-authorizers) when your function event is `http`, need to declare everything in the event itself (or use [share the authorizer](https://www.serverless.com/framework/docs/providers/aws/events/apigateway#note-while-using-authorizers-with-shared-api-gateway)) and syntax slightly different:
    - `functionArn` -> `arn`
    - `identitySource` as array -> as comma-separated string
