### ISSUE TITLE
nanomatch so much slower than globby

### ISSUE THREAD

**Issue by ChuckByram** [serverless/serverless#7793] opened 2020-05-29 03:27 UTC
Packaging takes several minutes for me and the issue seems to be in 
[packageService.resolveFilePathsFromPatterns](https://github.com/serverless/serverless/blob/v1.71.3/lib/plugins/package/lib/packageService.js#L229) (v1.71.3).

My serverless.yml includes a single file, but excludes a single glob pattern that expands to a large number of paths (248474 (yikes)).

The count of the starting `allFilePaths` of ** + includes is 255003. This count is determined in a couple of seconds by globby at [line 249](https://github.com/serverless/serverless/blob/v1.71.3/lib/plugins/package/lib/packageService.js#L249).

When the pattern processing gets to my exclude glob at [line 266](https://github.com/serverless/serverless/blob/v1.71.3/lib/plugins/package/lib/packageService.js#L266), it takes about 5 minutes to determine the 248474 paths from that pattern. That pattern represents yarn-linked modules, so follows a bunch of symlinks to modules that have their own yarn-linked modules, so more symlinks, etc.

The final count of file paths to include was 6474.

For fun, I used the [previous resolveFilePathsFromPatterns version](https://github.com/serverless/serverless/blob/80f9a2599f17757daf56ffd42ebb0a1224e29e8b/lib/plugins/package/lib/packageService.js#L174) that just did a straight-up globby on `patterns` and in a couple seconds, it gave me the same 6474 count.

I can't give a slam-dunk example project because it appears to need a huge set of file paths being included in the 

In the past, when I've searched for this problem, I see people saying that removing dev dependencies takes forever. But that's just the last message that gets logged before this function. In my case, removing the dev dependencies themselves was very quick (very few dev dependencies, though). 

For a very long time, I had been at a really downlevel version of serverless because when I upgraded above a certain version, I ran into this issue (can't remember details). But I've been above whatever the version was where this was introduced for several months and finally had to dig into it.

WOOT! I found the workaround was to take my big excluded glob and add it to includes preceded by `!`.

<details>
<summary><code>serverless.yml</code></summary>

```yaml
service: not-a-service
package:
  include:
    - .env
  exclude:
    - node_modules/@MASKEDNAMESPACE/*/node_modules/**
provider:
  name: aws
  runtime: nodejs12.x
  iamRoleStatements:
    - Effect: Allow
      Action:
        - lambda:InvokeFunction
        - "s3:*"
      Resource: "*"
  region: us-east-1
functions:
  fakeFunction:
    handler: handler.fakeFunction
    timeout: 300
    events:
      - schedule: rate(10 minutes)

```

</details>

NOTE: includes my tracing messages `!!TRACER!!` with times. Almost 5 minutes to nanomatch `!node_modules/@MASKED/*/node_modules/**`

<details>
<summary><b><code>SLS_DEBUG=* sls package -s dev</code> output</b></summary>

```
(node:6364) ExperimentalWarning: The fs.promises API is experimental
Serverless: Load command interactiveCli
Serverless: Load command config
Serverless: Load command config:credentials
Serverless: Load command config:tabcompletion
Serverless: Load command config:tabcompletion:install
Serverless: Load command config:tabcompletion:uninstall
Serverless: Load command create
Serverless: Load command install
Serverless: Load command package
Serverless: Load command deploy
Serverless: Load command deploy:function
Serverless: Load command deploy:list
Serverless: Load command deploy:list:functions
Serverless: Load command invoke
Serverless: Load command invoke:local
Serverless: Load command info
Serverless: Load command logs
Serverless: Load command metrics
Serverless: Load command print
Serverless: Load command remove
Serverless: Load command rollback
Serverless: Load command rollback:function
Serverless: Load command slstats
Serverless: Load command plugin
Serverless: Load command plugin
Serverless: Load command plugin:install
Serverless: Load command plugin
Serverless: Load command plugin:uninstall
Serverless: Load command plugin
Serverless: Load command plugin:list
Serverless: Load command plugin
Serverless: Load command plugin:search
Serverless: Load command config
Serverless: Load command config:credentials
Serverless: Load command rollback
Serverless: Load command rollback:function
Serverless: Load command upgrade
Serverless: Load command uninstall
Serverless: Load command login
Serverless: Load command logout
Serverless: Load command generate-event
Serverless: Load command test
Serverless: Load command dashboard
Serverless: Load command output
Serverless: Load command output:get
Serverless: Load command output:list
Serverless: Load command param
Serverless: Load command param:get
Serverless: Load command param:list
Serverless: Load command studio
Serverless: Load command dev
Serverless: Invoke package
Serverless: Invoke aws:common:validate
Serverless: Invoke aws:common:cleanupTempDir
Serverless: Packaging service...
!!TRACER!!: 23:01:20: packageAll
!!TRACER!!: 23:01:20: call resolveFilePathsAll
!!TRACER!!: 23:01:20: resolveFilePathsAll
!!TRACER!!: 23:01:20: getExcludes done
Serverless: Excluding development dependencies...
!!TRACER!!: 23:01:29: excludeDevDependencies done
!!TRACER!!: 23:01:29: resolveFilePathsFromPatterns
!!TRACER!!: 23:01:29: call globby (existing)
!!TRACER!!: 23:01:34: globby done. 255004 filepaths
!!TRACER!!: 23:01:34: call nanomatch for !.git/**
!!TRACER!!: 23:01:34: nanomatch result length 0
!!TRACER!!: 23:01:34: call nanomatch for !.gitignore
!!TRACER!!: 23:01:34: nanomatch result length 1
!!TRACER!!: 23:01:34: call nanomatch for !.DS_Store
!!TRACER!!: 23:01:34: nanomatch result length 0
!!TRACER!!: 23:01:34: call nanomatch for !npm-debug.log
!!TRACER!!: 23:01:34: nanomatch result length 0
!!TRACER!!: 23:01:34: call nanomatch for !yarn-*.log
!!TRACER!!: 23:01:34: nanomatch result length 0
!!TRACER!!: 23:01:34: call nanomatch for !.serverless/**
!!TRACER!!: 23:01:34: nanomatch result length 1
!!TRACER!!: 23:01:34: call nanomatch for !.serverless_plugins/**
!!TRACER!!: 23:01:34: nanomatch result length 0
!!TRACER!!: 23:01:34: call nanomatch for !serverless.yml
!!TRACER!!: 23:01:34: nanomatch result length 1
!!TRACER!!: 23:01:34: call nanomatch for !/Users/chuck/source/MASKED/MASKED/MASKED/.serverless_plugins
!!TRACER!!: 23:01:34: nanomatch result length 0
!!TRACER!!: 23:01:34: call nanomatch for !node_modules/@MASKED/*/node_modules/**
!!TRACER!!: 23:06:15: nanomatch result length 248474
!!TRACER!!: 23:06:15: call nanomatch for !node_modules/serverless-plugin-scripts/**
!!TRACER!!: 23:06:15: nanomatch result length 3
!!TRACER!!: 23:06:15: call nanomatch for !node_modules/test/**
!!TRACER!!: 23:06:15: nanomatch result length 42
!!TRACER!!: 23:06:15: call nanomatch for !node_modules/ansi-font/**
!!TRACER!!: 23:06:15: nanomatch result length 7
!!TRACER!!: 23:06:15: call nanomatch for .env
!!TRACER!!: 23:06:15: nanomatch result length 1
!!TRACER!!: 23:06:15: finalize filepaths done (6475)
!!TRACER!!: 23:06:15: resolveFilePathsFromPatterns done
!!TRACER!!: 23:06:15: resolveFilePathsAll done
!!TRACER!!: 23:06:20: zipFiles done
Serverless: Invoke aws:package:finalize
Serverless: Invoke aws:common:moveArtifactsToPackage
```

</details>

<b>Installed version</b>

```
(node:6412) ExperimentalWarning: The fs.promises API is experimental
Framework Core: 1.71.3
Plugin: 3.6.12
SDK: 2.3.1
Components: 2.30.11
```

**Comment by medikoo** [comment] 2020-06-01 08:54
@ChuckByram great thanks for report. Are you suggesting that https://github.com/serverless/serverless/pull/5574 introduced a regression?

Note that we're aware of buggy (unjustifiably slow) packaging performance, and that problem (in general) is handled here: https://github.com/serverless/serverless/issues/6580

**Comment by ChuckByram** [comment] 2020-06-01 12:54
@medikoo Thanks for the response. After skimming through the issues you mentioned, it's hard for me to say whether #5574 introduced a regression or if it just wasn't a complete fix of the issue as evidenced by the need for #6580. I'm sure #5574 fixed the issue on the table at the time, but it did make my particular scenario slow. For me, globby vs nanomatch for the same set of files was no match. 

- a large number of files in my node_modules due to some inter-related symlinks. We use yarn and `link:../path/to/module` for our local modules
- an exclude glob to remove those symlinks. If that wasn't there, it might package it, but it's hundreds of MB and won't deploy. 

As I was writing up this report, I realized I could try to exclude those symlinks earlier (and by globby) by moving the exclude glob to include and using `!`. In the doc, that syntax is mentioned as valid for exclude, but not include. That workaround worked nicely. 

I would suggest this one can be closed as a duplicate (or kind a close to one) and maybe the info can be helpful for #6580.

**Comment by medikoo** [comment] 2020-06-01 13:02
@ChuckByram yes, symlinks are not handled well, and in many scenarios they cause process to hang when packaging. That's ugly and definitely should be fixed, but it probably cannot be fixed without a bigger refactor.

If anyone has some idea on how bring some smart quick improvements on current ground, we're definitely open for that.

**Comment by medikoo** [comment] 2020-06-01 13:03
Duplicate of #6580

**Closed by medikoo** 2020-06-01 13:03 UTC
Labels: cat/packaging, question
