### ISSUE TITLE
serverless plan option similar to terraform plan

### ISSUE THREAD

**Issue by katamsivakumar** [serverless/serverless#11313] opened 2022-08-05 07:11 UTC
### Is there an existing issue for this?

- [X] I have searched existing issues, it hasn't been reported yet

### Use case description

Hi Team,

Is there any  serverless plan option similar to terraform plan to view the changes before deployment?

To achieve that feature in serverless is there any options available.

**Comment by mnapoli** [comment] 2022-08-05 08:18
Hi @katamsivakumar, this is not something that is currently available as a feature or command.

An alternative is to run `serverless package` and check the generated CloudFormation template in the `.serverless/` directory.

Note that there is also #10139 that is about using CloudFormation changesets to achieve the same result.

**Comment by gruckion** [comment] 2022-09-23 13:57
Team, have you considered moving away from CloudFormation? I found it to be a bit error prone. It can get stuck in roll backs sometimes. Terraform seems to do a better job with infrastructure management. I only use Serverless to make lambda functions, everything else is done in Terraform.

I also like that if I change say my environment variables for a lambda and then update it won't need to bundle up the zip file for no good reason.

**Comment by medikoo** [comment] 2023-06-13 09:16
Closing as duplicate of https://github.com/serverless/serverless/issues/10139

**Closed by medikoo** 2023-06-13 09:16 UTC
Labels: enhancement
