### ISSUE TITLE
Silent merge failure when using resources list

### ISSUE THREAD

**Issue by glb** [serverless/serverless#8118] opened 2020-08-23 17:39 UTC
We're making use of the great feature for breaking up `serverless.yml` file where you can have the `resources` be a list.

With this input:

<details>
<summary><code>serverless.yml</code></summary>

```yaml
service: example

provider:
  name: aws

resources:
  - ${file(resources-1.yml)}
  - ${file(resources-null.yml)}
```

</details>

<details>
<summary><code>resources-1.yml</code></summary>

```yaml
Resources:
  test:
    Type: AWS::SQS::Queue
```

</details>

<details>
<summary><code>resources-null.yml</code></summary>

```yaml
# We will add resources here at some point in the future
Resources:
```

</details>

The resulting `.serverless/cloudformation-template-update-stack.json` is missing the `test` resource from `resources-1.yml`. There is no error reported.

If we fix `resources-null.yml` to have an object:

<details>
<summary><code>resources-null.yml</code></summary>

```yaml
# We will add resources here at some point in the future
Resources: {}
```

</details>

then the resulting `.serverless/cloudformation-template-update-stack.json` has the `test` resources as expected.

<details>
<summary><b><code>SLS_DEBUG='*' sls package</code> output</b></summary>

```
Serverless: Load command interactiveCli
Serverless: Load command config
Serverless: Load command config:credentials
Serverless: Load command config:tabcompletion
Serverless: Load command config:tabcompletion:install
Serverless: Load command config:tabcompletion:uninstall
Serverless: Load command create
Serverless: Load command install
Serverless: Load command package
Serverless: Load command deploy
Serverless: Load command deploy:function
Serverless: Load command deploy:list
Serverless: Load command deploy:list:functions
Serverless: Load command invoke
Serverless: Load command invoke:local
Serverless: Load command info
Serverless: Load command logs
Serverless: Load command metrics
Serverless: Load command print
Serverless: Load command remove
Serverless: Load command rollback
Serverless: Load command rollback:function
Serverless: Load command slstats
Serverless: Load command plugin
Serverless: Load command plugin
Serverless: Load command plugin:install
Serverless: Load command plugin
Serverless: Load command plugin:uninstall
Serverless: Load command plugin
Serverless: Load command plugin:list
Serverless: Load command plugin
Serverless: Load command plugin:search
Serverless: Load command config
Serverless: Load command config:credentials
Serverless: Load command rollback
Serverless: Load command rollback:function
Serverless: Load command upgrade
Serverless: Load command uninstall
Serverless: Load command login
Serverless: Load command logout
Serverless: Load command generate-event
Serverless: Load command test
Serverless: Load command dashboard
Serverless: Load command output
Serverless: Load command output:get
Serverless: Load command output:list
Serverless: Load command param
Serverless: Load command param:get
Serverless: Load command param:list
Serverless: Load command studio
Serverless: Load command dev
Serverless: Invoke package
Serverless: Invoke aws:common:validate
Serverless: Invoke aws:common:cleanupTempDir
Serverless: Packaging service...
Serverless: Invoke aws:package:finalize
Serverless: Invoke aws:common:moveArtifactsToPackage
```

</details>

<b>Installed version</b>

```
% serverless --version
Framework Core: 1.78.1
Plugin: 3.7.0
SDK: 2.3.1
Components: 2.34.5
```

It's _possible_ that this would be resolved by #8014 but I think it would be more helpful to simply exclude any `null` `Resources` when processing the list, as tracking down the offending source file might be tricky.

I believe that this is happening [here](https://github.com/serverless/serverless/blob/796ce0b5ddaf893878912b5edeeec54718bf04ad/lib/classes/Service.js#L176) but am not yet sure what a good approach might be to get the behaviour I'd like. The `mergeArrays` function already discards `null` values from the list, but what's happening appears to be that it's trying to merge `{ "Resources": null }` with the existing object and getting `null` as an output.

Any thoughts? I recognize that ultimately it's the way that we've got `Resources` with a `null` value that is at fault, but it would have been extremely helpful if the framework could have identified this as a problem.

**Comment by glb** [comment] 2020-08-23 17:47
Perhaps `_.mergeWith` with a customizer function that says "when you are merging `null` with an object, return the object"?

**Comment by medikoo** [comment] 2020-08-24 11:25
@glb thanks for reporting.

I'm not convinced that working around`Resources: null` is a good idea, as that translates to supporting this as valid input, which it isn't.

Best solution I think comes with #8014 (note that at some point by default framework will crash with meaningful error when such situation happens).

Not directly related, but we're also tackling the idea of generic approach to _array_ extensions here: https://github.com/serverless/serverless/issues/8037#issuecomment-674751706

I'm going to close this, as it'll be well solved by #8014 (PR's welcome!)

**Closed by medikoo** 2020-08-24 11:25 UTC

**Comment by glb** [comment] 2020-08-26 18:48
@medikoo I've taken a crack at #8014 and with the above input all I get from the validation is

```text
Serverless: Configuration warning at 'resources.Resources': should be object
```

which isn't as enlightening as I would have hoped. It seems like validation happens after `mergeArrays`, which is a bit problematic.

**Comment by medikoo** [comment] 2020-08-27 09:17
@glb that's a valid point. As I think of it, root cause of this DX issues, is doing _deep_ merges on data we fully cannot understand programmatically. We already plan to revert from that when handling `resources`, see https://github.com/serverless/serverless/issues/6575

I believe right solution (to which we can get gradually) is to:

1. Implement generic multi object configuration support to any property (as proposed here https://github.com/serverless/serverless/issues/8037#issuecomment-674751706)
2. In above do only top level merges (as `Object.assign`), and crash on attempt of overwriting an existing property. We may also ignore (not crash on) top level null values

Having above, you won't have chance to run into ambiguity you deal with now, and most error cases should be quite clear.
