### ISSUE TITLE
Can't install plugins when resources are in separate files

### ISSUE THREAD

**Issue by lxop** [serverless/serverless#9746] opened 2021-07-15 00:44 UTC
When I have a block in my `serverless.yml` like
```yaml
resources:
  - ${file(resources/resources_a.yml)}
```
and I try to install a plugin (any plugin), I get an error:
```
$ sls plugin install -n serverless-plugin-common-excludes
 
 Serverless Error ----------------------------------------
 
  Non-object value specified in resources array: ${file(resources/resources_a.yml)}
 
  Get Support --------------------------------------------
     Docs:          docs.serverless.com
     Bugs:          github.com/serverless/serverless/issues
     Issues:        forum.serverless.com
 
  Your Environment Information ---------------------------
     Operating System:          linux
     Node Version:              14.4.0
     Framework Version:         2.51.2 (standalone)
     Plugin Version:            5.4.3
     SDK Version:               4.2.3
     Components Version:        3.13.3
 
Serverless: Deprecation warning: "provider.profile" is not accessible (configured behind variables which cannot be resolved at this stage).
            Starting with next major release, this will be communicated with a thrown error.
            Set "variablesResolutionMode: 20210326" in your service config, to adapt to this behavior now
            More Info: https://www.serverless.com/framework/docs/deprecations/#NEW_VARIABLES_RESOLVER
```

Note that other sls commands (e.g., `deploy`) work fine (after I have installed the plugin(s) by temporarily commenting out the `resources:` block), so the block itself is actually fine.

<details>
<summary><code>serverless.yml</code></summary>

```yaml
service: bug-repro
frameworkVersion: '2'

provider:
  name: aws

resources:
  - ${file(resources/resources_a.yml)}

plugins:
  - serverless-python-requirements
```

</details>
<details>
<summary><code>resources/resources_a.yml</code></summary>

```yaml
Resources:
```

</details>

<details>
<summary><b><code>sls plugin install -n serverless-python-requirements</code> output</b></summary>

```
 
 Serverless Error ----------------------------------------
 
  Non-object value specified in resources array: ${file(resources/resources_a.yml)}
 
  Get Support --------------------------------------------
     Docs:          docs.serverless.com
     Bugs:          github.com/serverless/serverless/issues
     Issues:        forum.serverless.com
 
  Your Environment Information ---------------------------
     Operating System:          linux
     Node Version:              14.4.0
     Framework Version:         2.51.2 (standalone)
     Plugin Version:            5.4.3
     SDK Version:               4.2.3
     Components Version:        3.13.3

```

</details>

<b>Installed version</b>

```
Framework Core: 2.51.2 (standalone)
Plugin: 5.4.3
SDK: 4.2.3
Components: 3.13.3
```

**Comment by medikoo** [comment] 2021-07-15 08:04
@lxop this was fixed with #9741 and will be fixed with today's release.

Closing as duplicate of #9731

**Closed by medikoo** 2021-07-15 08:04 UTC
