### ISSUE TITLE
Generated IAM role name may end as too long

### ISSUE THREAD

**Issue by et304383** [serverless/serverless#7597] opened 2020-04-20 17:25 UTC
# Feature Proposal

Allow setting a custom name for the IAM role serverless auto creates.

## Description

I think the proposal is pretty clear.  

1. What is the use case that should be solved. The more detail you describe this in the easier it is to understand for us.
Trying to get around the auto generated role name being too long.

1. **Optional:** If there is additional config how would it look

I would suggest something like:

```
provider:
  iamRoleName: something-goes-here
```

**Comment by medikoo** [comment] 2020-04-27 15:06
@et304383 thanks for proposal!

> Trying to get around the auto generated role name being too long.

I believe this is more a bug, that should be fixed, by ensuring that auto generated role name fits tha required limit. PR that fixes that is welcome.

**Comment by AhmedFat7y** [comment] 2020-05-04 10:50
@medikoo  the name generator in `lib/naming.js#getRoleName()` ?

**Comment by medikoo** [comment] 2020-05-04 13:43
@AhmedFat7y I've proposed a general solution to that issue at https://github.com/serverless/serverless/issues/7056 and I believe we should track that for this problem (it's not only IAM role name that's affected)

**Comment by medikoo** [comment] 2020-05-04 13:44
Duplicate of #7056

**Closed by medikoo** 2020-05-04 13:44 UTC
Labels: bug, cat/aws-iam, help wanted
