### ISSUE TITLE
Resolving cf: variable happen *before* provider.profile value is resolved

### ISSUE THREAD

**Issue by j0k3r** [serverless/serverless#3659] opened 2017-05-22 16:25 UTC
# This is a Bug Report

## Description

I've my `provider.profile` variable defined dynamically on the stage:

```yaml
provider:
    #...
    stage: ${opt:stage, self:custom.defaultStage}
    profile: ${self:custom.profiles.${self:provider.stage}}

custom:
    defaultStage: dev
    profiles:
        staging: demo
        prod: default
```

When I set a cloudformation variable below in my configuration, for example when defining an environment variable `ES_URL: https://${cf:superstack.ElasticsearchUrl}:9200`, it fails to perform the request.

What I found after debugging a bit in `Variables.js` is that the call to Cloudformation for retrieving the value is performed before the `profile` value is resolved.

So it can't retrieve the value and say:

>   Serverless Error ---------------------------------------
> 
>     Stack with id superstack does not exist
> 

When I switch the `profile` value to a hardcoded one (like `default`) the Cloudformation is working fine.

## Additional Data

* ***Serverless Framework Version you're using***: 1.13.2 (it fails since 1.13.0 in fact)
* ***Operating System***: linux
* ***Provider Error messages***: See anove

<details>
  <summary>Full stacktrace (using `SLS_DEBUG=*`)</summary>
ServerlessError: Stack with id superstack does not exist
    at Response.req.send (/home/jeremy/.nvm/versions/node/v6.3.0/lib/node_modules/serverless/lib/plugins/aws/provider/awsProvider.js:163:8)
    at Request.<anonymous> (/home/jeremy/.nvm/versions/node/v6.3.0/lib/node_modules/serverless/node_modules/aws-sdk/lib/request.js:360:18)
    at Request.callListeners (/home/jeremy/.nvm/versions/node/v6.3.0/lib/node_modules/serverless/node_modules/aws-sdk/lib/sequential_executor.js:105:20)
    at Request.emit (/home/jeremy/.nvm/versions/node/v6.3.0/lib/node_modules/serverless/node_modules/aws-sdk/lib/sequential_executor.js:77:10)
    at Request.emit (/home/jeremy/.nvm/versions/node/v6.3.0/lib/node_modules/serverless/node_modules/aws-sdk/lib/request.js:678:14)
    at Request.transition (/home/jeremy/.nvm/versions/node/v6.3.0/lib/node_modules/serverless/node_modules/aws-sdk/lib/request.js:22:10)
    at AcceptorStateMachine.runTo (/home/jeremy/.nvm/versions/node/v6.3.0/lib/node_modules/serverless/node_modules/aws-sdk/lib/state_machine.js:14:12)
    at /home/jeremy/.nvm/versions/node/v6.3.0/lib/node_modules/serverless/node_modules/aws-sdk/lib/state_machine.js:26:10
    at Request.<anonymous> (/home/jeremy/.nvm/versions/node/v6.3.0/lib/node_modules/serverless/node_modules/aws-sdk/lib/request.js:38:9)
    at Request.<anonymous> (/home/jeremy/.nvm/versions/node/v6.3.0/lib/node_modules/serverless/node_modules/aws-sdk/lib/request.js:680:12)
    at Request.callListeners (/home/jeremy/.nvm/versions/node/v6.3.0/lib/node_modules/serverless/node_modules/aws-sdk/lib/sequential_executor.js:115:18)
    at Request.emit (/home/jeremy/.nvm/versions/node/v6.3.0/lib/node_modules/serverless/node_modules/aws-sdk/lib/sequential_executor.js:77:10)
    at Request.emit (/home/jeremy/.nvm/versions/node/v6.3.0/lib/node_modules/serverless/node_modules/aws-sdk/lib/request.js:678:14)
    at Request.transition (/home/jeremy/.nvm/versions/node/v6.3.0/lib/node_modules/serverless/node_modules/aws-sdk/lib/request.js:22:10)
    at AcceptorStateMachine.runTo (/home/jeremy/.nvm/versions/node/v6.3.0/lib/node_modules/serverless/node_modules/aws-sdk/lib/state_machine.js:14:12)
    at /home/jeremy/.nvm/versions/node/v6.3.0/lib/node_modules/serverless/node_modules/aws-sdk/lib/state_machine.js:26:10
    at Request.<anonymous> (/home/jeremy/.nvm/versions/node/v6.3.0/lib/node_modules/serverless/node_modules/aws-sdk/lib/request.js:38:9)
    at Request.<anonymous> (/home/jeremy/.nvm/versions/node/v6.3.0/lib/node_modules/serverless/node_modules/aws-sdk/lib/request.js:680:12)
    at Request.callListeners (/home/jeremy/.nvm/versions/node/v6.3.0/lib/node_modules/serverless/node_modules/aws-sdk/lib/sequential_executor.js:115:18)
    at callNextListener (/home/jeremy/.nvm/versions/node/v6.3.0/lib/node_modules/serverless/node_modules/aws-sdk/lib/sequential_executor.js:95:12)
    at Request.RESET_RETRY_STATE (/home/jeremy/.nvm/versions/node/v6.3.0/lib/node_modules/serverless/node_modules/aws-sdk/lib/event_listeners.js:426:9)
    at Request.callListeners (/home/jeremy/.nvm/versions/node/v6.3.0/lib/node_modules/serverless/node_modules/aws-sdk/lib/sequential_executor.js:101:18)
From previous event:
    at persistentRequest (/home/jeremy/.nvm/versions/node/v6.3.0/lib/node_modules/serverless/lib/plugins/aws/provider/awsProvider.js:151:14)
    at doCall (/home/jeremy/.nvm/versions/node/v6.3.0/lib/node_modules/serverless/lib/plugins/aws/provider/awsProvider.js:130:9)
    at BbPromise (/home/jeremy/.nvm/versions/node/v6.3.0/lib/node_modules/serverless/lib/plugins/aws/provider/awsProvider.js:141:14)
    at persistentRequest (/home/jeremy/.nvm/versions/node/v6.3.0/lib/node_modules/serverless/lib/plugins/aws/provider/awsProvider.js:128:38)
    at AwsProvider.request (/home/jeremy/.nvm/versions/node/v6.3.0/lib/node_modules/serverless/lib/plugins/aws/provider/awsProvider.js:144:12)
    at Variables.getValueFromCf (/home/jeremy/.nvm/versions/node/v6.3.0/lib/node_modules/serverless/lib/classes/Variables.js:286:8)
    at Variables.getValueFromSource (/home/jeremy/.nvm/versions/node/v6.3.0/lib/node_modules/serverless/lib/classes/Variables.js:177:19)
    at Promise (/home/jeremy/.nvm/versions/node/v6.3.0/lib/node_modules/serverless/lib/classes/Variables.js:97:23)
    at property.match.forEach (/home/jeremy/.nvm/versions/node/v6.3.0/lib/node_modules/serverless/lib/classes/Variables.js:92:39)
    at Array.forEach (native)
    at Variables.populateProperty (/home/jeremy/.nvm/versions/node/v6.3.0/lib/node_modules/serverless/lib/classes/Variables.js:87:43)
    at Promise (/home/jeremy/.nvm/versions/node/v6.3.0/lib/node_modules/serverless/lib/classes/Variables.js:66:12)
    at deepMapValues (/home/jeremy/.nvm/versions/node/v6.3.0/lib/node_modules/serverless/lib/classes/Variables.js:65:40)
    at deepMapValues (/home/jeremy/.nvm/versions/node/v6.3.0/lib/node_modules/serverless/lib/classes/Variables.js:60:14)
From previous event:
    at persistentRequest (/home/jeremy/.nvm/versions/node/v6.3.0/lib/node_modules/serverless/lib/plugins/aws/provider/awsProvider.js:128:38)
    at AwsProvider.request (/home/jeremy/.nvm/versions/node/v6.3.0/lib/node_modules/serverless/lib/plugins/aws/provider/awsProvider.js:144:12)
    at Variables.getValueFromCf (/home/jeremy/.nvm/versions/node/v6.3.0/lib/node_modules/serverless/lib/classes/Variables.js:286:8)
    at Variables.getValueFromSource (/home/jeremy/.nvm/versions/node/v6.3.0/lib/node_modules/serverless/lib/classes/Variables.js:177:19)
    at Promise (/home/jeremy/.nvm/versions/node/v6.3.0/lib/node_modules/serverless/lib/classes/Variables.js:97:23)
    at property.match.forEach (/home/jeremy/.nvm/versions/node/v6.3.0/lib/node_modules/serverless/lib/classes/Variables.js:92:39)
    at Array.forEach (native)
    at Variables.populateProperty (/home/jeremy/.nvm/versions/node/v6.3.0/lib/node_modules/serverless/lib/classes/Variables.js:87:43)
    at Promise (/home/jeremy/.nvm/versions/node/v6.3.0/lib/node_modules/serverless/lib/classes/Variables.js:66:12)
    at deepMapValues (/home/jeremy/.nvm/versions/node/v6.3.0/lib/node_modules/serverless/lib/classes/Variables.js:65:40)
    at deepMapValues (/home/jeremy/.nvm/versions/node/v6.3.0/lib/node_modules/serverless/lib/classes/Variables.js:60:14)
    at deepMapValuesIteratee (/home/jeremy/.nvm/versions/node/v6.3.0/lib/node_modules/serverless/lib/classes/Variables.js:50:25)
    at /home/jeremy/.nvm/versions/node/v6.3.0/lib/node_modules/serverless/node_modules/lodash/lodash.js:13379:38
    at /home/jeremy/.nvm/versions/node/v6.3.0/lib/node_modules/serverless/node_modules/lodash/lodash.js:4944:15
    at baseForOwn (/home/jeremy/.nvm/versions/node/v6.3.0/lib/node_modules/serverless/node_modules/lodash/lodash.js:3001:24)
    at Function.mapValues (/home/jeremy/.nvm/versions/node/v6.3.0/lib/node_modules/serverless/node_modules/lodash/lodash.js:13378:7)
    at deepMapValues (/home/jeremy/.nvm/versions/node/v6.3.0/lib/node_modules/serverless/lib/classes/Variables.js:58:39)
    at deepMapValuesIteratee (/home/jeremy/.nvm/versions/node/v6.3.0/lib/node_modules/serverless/lib/classes/Variables.js:50:25)
    at /home/jeremy/.nvm/versions/node/v6.3.0/lib/node_modules/serverless/node_modules/lodash/lodash.js:13379:38
    at /home/jeremy/.nvm/versions/node/v6.3.0/lib/node_modules/serverless/node_modules/lodash/lodash.js:4944:15
    at baseForOwn (/home/jeremy/.nvm/versions/node/v6.3.0/lib/node_modules/serverless/node_modules/lodash/lodash.js:3001:24)
    at Function.mapValues (/home/jeremy/.nvm/versions/node/v6.3.0/lib/node_modules/serverless/node_modules/lodash/lodash.js:13378:7)
    at deepMapValues (/home/jeremy/.nvm/versions/node/v6.3.0/lib/node_modules/serverless/lib/classes/Variables.js:58:39)
    at deepMapValuesIteratee (/home/jeremy/.nvm/versions/node/v6.3.0/lib/node_modules/serverless/lib/classes/Variables.js:50:25)
    at /home/jeremy/.nvm/versions/node/v6.3.0/lib/node_modules/serverless/node_modules/lodash/lodash.js:13379:38
</details>

**Comment by pmuens** [comment] 2017-05-23 08:46
Thanks for opening @j0k3r 👍 

Related issue is: https://github.com/serverless/serverless/issues/3356

**Comment by direvus** [comment] 2018-01-16 03:08
I just ran full speed into this bug today.  Are you aware of any way to work around it?

It's particularly nasty since the pattern of using a dynamic profile is actually suggested by the Serverless AWS guide itself.

**Comment by jspreddy** [comment] 2018-08-10 21:27
I ran into the same issue. 

serverless v 1.29.2

I have my profile in the provider section like so: 

```yaml
  profile: ${env:AWS_PROFILE, 'my_aws_profile'}
```

and I added the VPN section to the provider like so:

```yaml
  vpc:
    securityGroupIds:
      - ${cf:mystack.LambdaGenericSG}
    subnetIds:
      - ${cf:mystack.PrivateSubnet1}
      - ${cf:mystack.PrivateSubnet2}
      - ${cf:mystack.PrivateSubnet3}
```

The deploy is erroring out saying the profile does not exist.

```
Error --------------------------------------------------

  Profile ${env:AWS_PROFILE, 'my_aws_profile'} does not exist
```

If I remove the vpn section, everything validates and deploy works.

If I put the vpn section back in, it fails again.



Full stack trace:

```
Serverless: Load command config
Serverless: Load command config:credentials
Serverless: Load command create
Serverless: Load command install
Serverless: Load command package
Serverless: Load command deploy
Serverless: Load command deploy:function
Serverless: Load command deploy:list
Serverless: Load command deploy:list:functions
Serverless: Load command invoke
Serverless: Load command invoke:local
Serverless: Load command info
Serverless: Load command logs
Serverless: Load command login
Serverless: Load command logout
Serverless: Load command metrics
Serverless: Load command print
Serverless: Load command remove
Serverless: Load command rollback
Serverless: Load command rollback:function
Serverless: Load command slstats
Serverless: Load command plugin
Serverless: Load command plugin
Serverless: Load command plugin:install
Serverless: Load command plugin
Serverless: Load command plugin:uninstall
Serverless: Load command plugin
Serverless: Load command plugin:list
Serverless: Load command plugin
Serverless: Load command plugin:search
Serverless: Load command config
Serverless: Load command config:credentials
Serverless: Load command rollback
Serverless: Load command rollback:function
Serverless: Load command webpack
Serverless: Load command create
Serverless: Load command create:test
Serverless: Load command create:function
Serverless: Load command invoke
Serverless: Load command invoke:test
Serverless: Load command create_domain
Serverless: Load command delete_domain
Serverless: Load command offline
Serverless: Load command offline:start

  Error --------------------------------------------------

  Profile ${env:AWS_PROFILE, 'my_aws_profile'} does not exist

     For debugging logs, run again after setting the "SLS_DEBUG=*" environment variable.

  Stack Trace --------------------------------------------

Error: Profile ${env:AWS_PROFILE, 'my_aws_profile'} does not exist
    at Object.addProfileCredentials (/Users/...obfuscated_path.../node_modules/serverless/lib/plugins/aws/provider/awsProvider.js:86:15)
    at AwsProvider.getCredentials (/Users/...obfuscated_path.../node_modules/serverless/lib/plugins/aws/provider/awsProvider.js:303:12)
    at AwsProvider.request (/Users/...obfuscated_path.../node_modules/serverless/lib/plugins/aws/provider/awsProvider.js:197:30)
    at Variables.getValueFromCf (/Users/...obfuscated_path.../node_modules/serverless/lib/classes/Variables.js:641:8)
    at Variables.getValueFromSource (/Users/...obfuscated_path.../node_modules/serverless/lib/classes/Variables.js:478:20)
    at Variables.splitAndGet (/Users/...obfuscated_path.../node_modules/serverless/lib/classes/Variables.js:366:17)
    at _.map (/Users/...obfuscated_path.../node_modules/serverless/lib/classes/Variables.js:304:43)
    at arrayMap (/Users/...obfuscated_path.../node_modules/lodash/lodash.js:639:23)
    at Function.map (/Users/...obfuscated_path.../node_modules/lodash/lodash.js:9554:14)
    at Variables.populateMatches (/Users/...obfuscated_path.../node_modules/serverless/lib/classes/Variables.js:304:14)
    at Variables.populateValue (/Users/...obfuscated_path.../node_modules/serverless/lib/classes/Variables.js:335:30)
    at _.map.variable (/Users/...obfuscated_path.../node_modules/serverless/lib/classes/Variables.js:223:24)
    at arrayMap (/Users/...obfuscated_path.../node_modules/lodash/lodash.js:639:23)
    at Function.map (/Users/...obfuscated_path.../node_modules/lodash/lodash.js:9554:14)
    at Variables.populateVariables (/Users/...obfuscated_path.../node_modules/serverless/lib/classes/Variables.js:222:14)
    at Variables.populateObjectImpl (/Users/...obfuscated_path.../node_modules/serverless/lib/classes/Variables.js:251:30)
    at prepopulateService.then (/Users/...obfuscated_path.../node_modules/serverless/lib/classes/Variables.js:135:26)
    at runCallback (timers.js:794:20)
    at tryOnImmediate (timers.js:752:5)
    at processImmediate [as _immediateCallback] (timers.js:729:5)
From previous event:
    at initialCall (/Users/...obfuscated_path.../node_modules/serverless/lib/classes/Variables.js:135:10)
    at Variables.initialCall (/Users/...obfuscated_path.../node_modules/serverless/lib/classes/Variables.js:66:12)
    at Variables.populateService (/Users/...obfuscated_path.../node_modules/serverless/lib/classes/Variables.js:133:17)
    at Serverless.run (/Users/...obfuscated_path.../node_modules/serverless/lib/Serverless.js:111:27)
    at serverless.init.then (/Users/...obfuscated_path.../node_modules/serverless/bin/serverless:43:50)
    at <anonymous>

  Get Support --------------------------------------------
     Docs:          docs.serverless.com
     Bugs:          github.com/serverless/serverless/issues
     Issues:        forum.serverless.com

  Your Environment Information -----------------------------
     OS:                     darwin
     Node Version:           8.10.0
     Serverless Version:     1.29.2


```

**Comment by kevinsperrine** [comment] 2018-08-31 20:31
FWIW, if you just flip the variables and map profile to stage it works. Good enough workaround for me for the time being.

```
custom:
  defaultProfile: AWSONE
  stages:
    AWSONE: dev
    AWSTWO: production

provider:
  stage: ${self:custom.stages.${self:provider.profile}}
  profile: ${opt:aws_profile, self:custom.defaultProfile}
```

`sls deploy --profile AWSONE`

**Comment by kevinsperrine** [comment] 2018-08-31 20:34
FWIW, if you just flip the variables and map profile to stage it works. Good enough workaround for me for the time being.
```
custom:
  defaultProfile: AWSONE
  stages:
    AWSONE: dev
    AWSTWO: production

provider:
  stage: ${self:custom.stages.${self:provider.profile}}
  profile: ${opt:aws-profile, self:custom.defaultProfile}
```

`sls deploy --profile AWSONE`

**Comment by Elias-Serneels** [comment] 2020-01-10 08:35
We have been running into this issue for a while now and only just discovered the cause. Will try the workaround for now but would be nice to see a fix!

**Comment by medikoo** [comment] 2020-11-12 13:09
We have a plan to refactor variable resolution logic in next months, for details check: https://github.com/serverless/serverless/issues/7207 (I'm closing this issue in favor of it)

As a side note `provider.profile` property  is scheduled to be deprecated: https://github.com/serverless/serverless/issues/8356

**Closed by medikoo** 2020-11-12 13:09 UTC
Labels: bug, cat/variable, help wanted
