### ISSUE TITLE
Improve error message for "role defined for the function cannot be assumed"

### ISSUE THREAD

**Issue by Ginden** [serverless/serverless#4384] opened 2017-10-16 11:31 UTC
What I got:

```
  Serverless Error ---------------------------------------
     An error occurred while provisioning your stack: MainLambdaFunction
     - The role defined for the function cannot be assumed by Lambda..
  Get Support --------------------------------------------
...
```

What I would like to see here:

* What role did Lambda tried to assume? Maybe I made a typo (actually I did)?
* Why it failed - this role does not exist, I don't have permissions?

**Comment by horike37** [comment] 2017-10-17 02:02
Thank you for reporting @Ginden :+1: 
We need to know more details so that we can take a look into it :smile: 

- What commands did you run when the error occurred?
- Could you share your serverless.yml so that we can try to reproduce it?

**Comment by horike37** [comment] 2017-11-12 08:18
Closing this issue for now since still not getting any responses.

**Closed by horike37** 2017-11-12 08:18 UTC
Labels: kind/bug, status/more-info-needed
