### ISSUE TITLE
Throw when env variables are missing

### ISSUE THREAD

**Issue by G-Rath** [serverless/serverless#8700] opened 2021-01-01 23:39 UTC
### Use case description

When deploying my functions `serverless` currently will output a warning if I've defined an env variable that cannot be found when running commands like `deploy`:

> A valid environment variable to satisfy the declaration 'env:MISSING' could not be found.

This means I could be deploying a function that will fail due to the that env being missing.

### Proposed solution

A really easy solution could be to use [`dotenv-safe`](https://github.com/rolodato/dotenv-safe) instead of `dotenv`, optionally with exposing it's options.

`dotenv-safe` is a wrapper for `dotenv` that looks for a `.env.example` file and compares the contents to `process.env` *after* having done `dotenv.config` - this means it could be an almost drop-in replacement.

A few thoughts on this:
  * by having a `path_to_example_env_file` property you'd have complete support for dynamic envs since you can just do things like `path_to_example_env_file: ".env.${opt:stage}"`
  * `dotenv-safe`s only dependency is `dotenv`, so you could support allowing disabling validation (and thus the requirement for a `.env.example`) by having both as a dependency, and doing a conditional (`(validEnvAgainstExample ? dotenvSafe : dotenv).load()`) without having to worry about package bloat too much
  * You could go the other way and have something like `validEnvFileAgainst: <path>` that'd trigger the same condition, but that way you'd be letting us devs opt-in so you don't have to worry about what default names, behaviours, etc should be.

Happy to help implement this (either using `dotenv-safe` or via another solution) :)

**Comment by pgrzesik** [comment] 2021-01-04 11:04
Hello @G-Rath, thanks for submitting your proposal. 
I think it makes sense to consider a strict variable resolution, but I'm not sure if using `dotenv-safe` along with example file(s) is the best solution here. 

As you mentioned, we output warnings when there's e.g. a missing environment variable during resolution, so there's "check step" already. `dotenv-safe` is also specific to env variables, where I think, if we would decide to adopt such validation, it would be good to support it universally for different variable types. What do you think?

I'd love to hear your opinion on this one @medikoo as you have way more experience with that topic than I do.

**Comment by pgrzesik** [comment] 2021-01-04 12:30
As @medikoo mentioned to me correctly, we already have a similar issue (along with solution proposal) available here: https://github.com/serverless/serverless/issues/3367 and we'd be happy to accept PR that implements it :bow: 

Due to that, I'm closing this issue as duplicate, please let me know if you feel like env variables should be treated differently (e.g. with `dotenv-safe`).

**Comment by pgrzesik** [comment] 2021-01-04 12:30
Duplicate of #3367

**Closed by pgrzesik** 2021-01-04 12:30 UTC
Labels: cat/variable, enhancement, needs feedback

**Comment by G-Rath** [comment] 2021-01-04 19:42
Cheers - I think its a good idea to check all references like this, but scoped my issue to just env for now as I thought that it could be less breaking to start with just those references than do them all at once.

I've created #8710 implementing this :)
