### ISSUE TITLE
Using -v parameter not working, shows the help text instead

### ISSUE THREAD

**Issue by GHMatty** [serverless/serverless#8963] opened 2021-02-17 14:02 UTC
Using -v parameter not working, shows the help text instead

<details>
<summary><code>serverless.yml</code></summary>

```yaml
```

</details>

<details>
<summary><b><code>sls -v --stage STAGE --param1 P1 --param2 P2</code> output</b></summary>

```
Commands
* You can run commands with "serverless" or the shortcut "sls"
* Pass "--no-color" to disable CLI colors
* Pass "--help" after any <command> for contextual help
Interactive Quickstart
* Run serverless (or shortcut sls) without any arguments to initialize an interactive setup
  of functionalities related to given service or current environment
* Pass "--help-interactive" for contextual help on interactive CLI options
Serverless Components
* Run serverless (or shortcut sls) in context of a component service to initialize a components CLI
* Pass "--help-components" for contextual help on Serverless Components
Framework
* Documentation: http://slss.io/docs
Environment Variables
* Set SLS_DEBUG=* to see debugging logs
* Set SLS_WARNING_DISABLE=* to hide warnings from the output
* Set SLS_DEPRECATION_DISABLE=* to disable deprecation logs
* Set SLS_MAX_CONCURRENT_ARTIFACTS_UPLOADS to control the maximum S3 upload SDK requests that are sent in parallel during the deployment of the service's artifacts. The default is 3. Note: increasing this too high might, actually, downgrade the overall upload speed
General Commands
config ........................ Configure Serverless
config credentials ............ Configures a new provider profile for the Serverless Framework
config tabcompletion install .. Install a <tab> completion for chosen shell
config tabcompletion uninstall  Uninstall a <tab> completion for chosen shell
create ........................ Create new Serverless service
dashboard ..................... Open the Serverless dashboard
deploy ........................ Deploy a Serverless service
deploy function ............... Deploy a single function from the service
deploy list ................... List deployed version of your Serverless Service
deploy list functions ......... List all the deployed functions and their versions
generate-event ................ Generate event
info .......................... Display information about the service
install ....................... Install a Serverless service from GitHub or a plugin from the Serverless registry
invoke ........................ Invoke a deployed function
invoke local .................. Invoke function locally
login ......................... Login or sign up for Serverless
logout ........................ Logout from Serverless
logs .......................... Output the logs of a deployed function
metrics ....................... Show metrics for a specific function
output ........................ 
output get .................... Get value of dashboard deployment profile parameter
output list ................... List all dashboard deployment profile parameters
package ....................... Packages a Serverless service
param ......................... 
param get ..................... Get value of dashboard service output
param list .................... List all dashboard service outputs
plugin ........................ Plugin management for Serverless
plugin install ................ Install and add a plugin to your service
plugin uninstall .............. Uninstall and remove a plugin from your service
plugin list ................... Lists all available plugins
plugin search ................. Search for plugins
print ......................... Print your compiled and resolved config file
remove ........................ Remove Serverless service and all resources
rollback ...................... Rollback the Serverless service to a specific deployment
rollback function ............. Rollback the function to a specific version
slstats ....................... Enable or disable stats
studio ........................ Develop a Serverless application in the cloud.
test .......................... Run HTTP tests
```

</details>

<b>Installed version</b>

```
Version 2.25.1
```

**Comment by GHMatty** [comment] 2021-02-17 14:07
It works with/until Version 2.23.0

**Comment by pgrzesik** [comment] 2021-02-17 14:10
Hello @GHMatty :wave: Could you share the installation method that you're using? What OS are you on?

**Comment by medikoo** [comment] 2021-02-17 14:15
@GHMatty we cannot reproduce it with latest version

<img width="484" alt="Screenshot 2021-02-17 at 15 14 59" src="https://user-images.githubusercontent.com/122434/108216611-f654fb00-7132-11eb-89ef-6321b5653756.png">

**Comment by GHMatty** [comment] 2021-02-17 14:15
gitlab runner with linux

**Comment by GHMatty** [comment] 2021-02-17 14:18
SORRY this is the command i forgot the 'deploy':

sls -v deploy --stage $STAGE --servicename $SERVICENAME --serviceversion $SERVICEVERSION --description "$DESCRIPTION"

**Comment by medikoo** [comment] 2021-02-17 14:27
@GHMatty great thanks for clarification, will be fixed with https://github.com/serverless/serverless/pull/8964

**Closed** 2021-02-18 08:56 UTC
Labels: bug, cat/cli
