### ISSUE TITLE
Error: Cannot find module 'pump' sls create

### ISSUE THREAD

**Issue by bugattie** [serverless/serverless#9087] opened 2021-03-06 13:18 UTC
I'm having an issue creating new sls project.
Command I wrote
`sls create -t aws-nodejs -p sls-notes-app-backend`

I'm using ubuntu 20.04
```
sls -v
Framework Core: 2.28.7
Plugin: 4.4.3
SDK: 2.3.2
Components: 3.7.2
```

Got long long error trace:

> Error --------------------------------------------------
>  
>   Error: Cannot find module 'pump'
>   Require stack:
>   - /usr/lib/node_modules/serverless/node_modules/got/node_modules/get-stream/index.js
>   - /usr/lib/node_modules/serverless/node_modules/got/node_modules/cacheable-request/src/index.js
>   - /usr/lib/node_modules/serverless/node_modules/got/dist/source/core/index.js
>   - /usr/lib/node_modules/serverless/node_modules/got/dist/source/as-promise/types.js
>   - /usr/lib/node_modules/serverless/node_modules/got/dist/source/as-promise/index.js
>   - /usr/lib/node_modules/serverless/node_modules/got/dist/source/create.js
>   - /usr/lib/node_modules/serverless/node_modules/got/dist/source/index.js
>   - /usr/lib/node_modules/serverless/lib/utils/eventuallyUpdate.js
>   - /usr/lib/node_modules/serverless/lib/Serverless.js
>   - /usr/lib/node_modules/serverless/scripts/serverless.js
>   - /usr/lib/node_modules/serverless/bin/serverless.js
>       at Function.Module._resolveFilename (internal/modules/cjs/loader.js:880:15)
>       at Function.Module._load (internal/modules/cjs/loader.js:725:27)
>       at Module.require (internal/modules/cjs/loader.js:952:19)
>       at require (internal/modules/cjs/helpers.js:88:18)
>       at Object.<anonymous> (/usr/lib/node_modules/serverless/node_modules/got/node_modules/get-stream/index.js:3:14)
>       at Module._compile (internal/modules/cjs/loader.js:1063:30)
>       at Object.Module._extensions..js (internal/modules/cjs/loader.js:1092:10)
>       at Module.load (internal/modules/cjs/loader.js:928:32)
>       at Function.Module._load (internal/modules/cjs/loader.js:769:14)
>       at Module.require (internal/modules/cjs/loader.js:952:19)
>       at require (internal/modules/cjs/helpers.js:88:18)
>       at Object.<anonymous> (/usr/lib/node_modules/serverless/node_modules/got/node_modules/cacheable-request/src/index.js:6:19)
>       at Module._compile (internal/modules/cjs/loader.js:1063:30)
>       at Object.Module._extensions..js (internal/modules/cjs/loader.js:1092:10)
>       at Module.load (internal/modules/cjs/loader.js:928:32)
>       at Function.Module._load (internal/modules/cjs/loader.js:769:14)
>       at Module.require (internal/modules/cjs/loader.js:952:19)
>       at require (internal/modules/cjs/helpers.js:88:18)
>       at Object.<anonymous> (/usr/lib/node_modules/serverless/node_modules/got/dist/source/core/index.js:13:26)
>       at Module._compile (internal/modules/cjs/loader.js:1063:30)
>       at Object.Module._extensions..js (internal/modules/cjs/loader.js:1092:10)
>       at Module.load (internal/modules/cjs/loader.js:928:32)
>       at Function.Module._load (internal/modules/cjs/loader.js:769:14)
>       at Module.require (internal/modules/cjs/loader.js:952:19)
>       at require (internal/modules/cjs/helpers.js:88:18)
>       at Object.<anonymous> (/usr/lib/node_modules/serverless/node_modules/got/dist/source/as-promise/types.js:14:16)
>       at Module._compile (internal/modules/cjs/loader.js:1063:30)
>       at Object.Module._extensions..js (internal/modules/cjs/loader.js:1092:10)
>       at Module.load (internal/modules/cjs/loader.js:928:32)
>       at Function.Module._load (internal/modules/cjs/loader.js:769:14)
>       at Module.require (internal/modules/cjs/loader.js:952:19)
>       at require (internal/modules/cjs/helpers.js:88:18)
>       at Object.<anonymous> (/usr/lib/node_modules/serverless/node_modules/got/dist/source/as-promise/index.js:16:17)
>       at Module._compile (internal/modules/cjs/loader.js:1063:30)
>       at Object.Module._extensions..js (internal/modules/cjs/loader.js:1092:10)
>       at Module.load (internal/modules/cjs/loader.js:928:32)
>       at Function.Module._load (internal/modules/cjs/loader.js:769:14)
>       at Module.require (internal/modules/cjs/loader.js:952:19)
>       at require (internal/modules/cjs/helpers.js:88:18)
>       at Object.<anonymous> (/usr/lib/node_modules/serverless/node_modules/got/dist/source/create.js:15:22)
>       at Module._compile (internal/modules/cjs/loader.js:1063:30)
>       at Object.Module._extensions..js (internal/modules/cjs/loader.js:1092:10)
>       at Module.load (internal/modules/cjs/loader.js:928:32)
>       at Function.Module._load (internal/modules/cjs/loader.js:769:14)
>       at Module.require (internal/modules/cjs/loader.js:952:19)
>       at require (internal/modules/cjs/helpers.js:88:18)
>       at Object.<anonymous> (/usr/lib/node_modules/serverless/node_modules/got/dist/source/index.js:14:18)
>       at Module._compile (internal/modules/cjs/loader.js:1063:30)
>       at Object.Module._extensions..js (internal/modules/cjs/loader.js:1092:10)
>       at Module.load (internal/modules/cjs/loader.js:928:32)
>       at Function.Module._load (internal/modules/cjs/loader.js:769:14)
>       at Module.require (internal/modules/cjs/loader.js:952:19)
>       at require (internal/modules/cjs/helpers.js:88:18)
>       at Object.<anonymous> (/usr/lib/node_modules/serverless/lib/utils/eventuallyUpdate.js:11:13)
>       at Module._compile (internal/modules/cjs/loader.js:1063:30)
>       at Object.Module._extensions..js (internal/modules/cjs/loader.js:1092:10)
>       at Module.load (internal/modules/cjs/loader.js:928:32)
>       at Function.Module._load (internal/modules/cjs/loader.js:769:14)
>       at Module.require (internal/modules/cjs/loader.js:952:19)
>       at require (internal/modules/cjs/helpers.js:88:18)
>       at Object.<anonymous> (/usr/lib/node_modules/serverless/lib/Serverless.js:21:26)
>       at Module._compile (internal/modules/cjs/loader.js:1063:30)
>       at Object.Module._extensions..js (internal/modules/cjs/loader.js:1092:10)
>       at Module.load (internal/modules/cjs/loader.js:928:32)
>       at Function.Module._load (internal/modules/cjs/loader.js:769:14)
>       at Module.require (internal/modules/cjs/loader.js:952:19)
>       at require (internal/modules/cjs/helpers.js:88:18)
>       at /usr/lib/node_modules/serverless/scripts/serverless.js:48:24
>       at processTicksAndRejections (internal/process/task_queues.js:93:5)
>  
>      For debugging logs, run again after setting the "SLS_DEBUG=*" environment variable.

**Comment by pgrzesik** [comment] 2021-03-07 19:10
Hello @bugattie, thanks for reporting. Could you share what Node version are you using? Ideally if you could fill out our Issue form that is presented to you when you create a new issue - it will help us diagnosing the problem.

**Comment by bugattie** [comment] 2021-03-08 04:57
@pgrzesik I'm using v14.16.0.
I tried the following solutions:

> https://stackoverflow.com/questions/49484433/not-able-to-clear-npm-cache-throws-error-cannot-find-module-pump
> https://github.com/ampproject/amp-by-example/issues/817

But those solutions didn't work for me.
It was really really urgent, I just reinstalled the serverless framework and it did work.

**Comment by bugattie** [comment] 2021-03-08 04:58
@pgrzesik I'm using v14.16.0.
I tried the following solutions:

> https://stackoverflow.com/questions/49484433/not-able-to-clear-npm-cache-throws-error-cannot-find-module-pump
> ampproject/amp-by-example#817

But those solutions didn't work for me.
It was really really urgent, I just reinstalled the serverless framework and it did work.

**Comment by pgrzesik** [comment] 2021-03-08 08:03
Thanks for responding, glad you managed to resolve your issue. I believe it's not a bug within the Framework but rather an issue with your local setup so I'm going to close this one.

**Closed by pgrzesik** 2021-03-08 08:03 UTC
Labels: question
