### ISSUE TITLE
(AWS) usagePlans: if quota isn't present, throttle is silently ignored

### ISSUE THREAD

**Issue by humodz** [serverless/serverless#8454] opened 2020-10-29 21:46 UTC
API Gateway allows an Usage Plan to have Throttling without having Quota, and vice versa. However, if quota isn't specified in serverless.yml, then throttle is silently ignored.

In the generated CloudFormation template (provided below), the "both" and "only-quota" Usage Plans are as expected, but "only-throttle" is missing the Throttle configuration.

<details>
<summary><code>serverless.yml</code></summary>

```yaml
service: hello-serverless

provider:
  name: aws
  runtime: nodejs12.x

  stage: dev
  stackName: hello-api-gateway
  timeout: 30

  apiKeys:
    - only-throttle:
      - only-throttle-key
    - only-quota:
      - only-quota-key
    - both:
      - both-key

  usagePlan:
    - only-throttle:
        throttle:
          burstLimit: 1111
          rateLimit: 2222
    - only-quota:
        quota:
          limit: 3333
          offset: 2
          period: MONTH
    - both:
        throttle:
          burstLimit: 4444
          rateLimit: 5555
        quota:
          limit: 6666
          offset: 2
          period: MONTH

package:
  excludeDevDependencies: false
  exclude: ['**/**']
  include: ['handler.js']

functions:
  hello:
    handler: handler.hello
    events:
      - http: GET /
```

</details>

<details>
<summary><b><code>sls package</code> output</b></summary>

`cloudformation-template-update-stack.json`
```json
{
  "AWSTemplateFormatVersion": "2010-09-09",
  "Description": "The AWS CloudFormation template for this Serverless application",
  "Resources": {
    "ServerlessDeploymentBucket": {
      "Type": "AWS::S3::Bucket",
      "Properties": {
        "BucketEncryption": {
          "ServerSideEncryptionConfiguration": [
            {
              "ServerSideEncryptionByDefault": {
                "SSEAlgorithm": "AES256"
              }
            }
          ]
        }
      }
    },
    "ServerlessDeploymentBucketPolicy": {
      "Type": "AWS::S3::BucketPolicy",
      "Properties": {
        "Bucket": {
          "Ref": "ServerlessDeploymentBucket"
        },
        "PolicyDocument": {
          "Statement": [
            {
              "Action": "s3:*",
              "Effect": "Deny",
              "Principal": "*",
              "Resource": [
                {
                  "Fn::Join": [
                    "",
                    [
                      "arn:",
                      {
                        "Ref": "AWS::Partition"
                      },
                      ":s3:::",
                      {
                        "Ref": "ServerlessDeploymentBucket"
                      },
                      "/*"
                    ]
                  ]
                }
              ],
              "Condition": {
                "Bool": {
                  "aws:SecureTransport": false
                }
              }
            }
          ]
        }
      }
    },
    "HelloLogGroup": {
      "Type": "AWS::Logs::LogGroup",
      "Properties": {
        "LogGroupName": "/aws/lambda/hello-serverless-dev-hello"
      }
    },
    "IamRoleLambdaExecution": {
      "Type": "AWS::IAM::Role",
      "Properties": {
        "AssumeRolePolicyDocument": {
          "Version": "2012-10-17",
          "Statement": [
            {
              "Effect": "Allow",
              "Principal": {
                "Service": [
                  "lambda.amazonaws.com"
                ]
              },
              "Action": [
                "sts:AssumeRole"
              ]
            }
          ]
        },
        "Policies": [
          {
            "PolicyName": {
              "Fn::Join": [
                "-",
                [
                  "hello-serverless",
                  "dev",
                  "lambda"
                ]
              ]
            },
            "PolicyDocument": {
              "Version": "2012-10-17",
              "Statement": [
                {
                  "Effect": "Allow",
                  "Action": [
                    "logs:CreateLogStream",
                    "logs:CreateLogGroup"
                  ],
                  "Resource": [
                    {
                      "Fn::Sub": "arn:${AWS::Partition}:logs:${AWS::Region}:${AWS::AccountId}:log-group:/aws/lambda/hello-serverless-dev*:*"
                    }
                  ]
                },
                {
                  "Effect": "Allow",
                  "Action": [
                    "logs:PutLogEvents"
                  ],
                  "Resource": [
                    {
                      "Fn::Sub": "arn:${AWS::Partition}:logs:${AWS::Region}:${AWS::AccountId}:log-group:/aws/lambda/hello-serverless-dev*:*:*"
                    }
                  ]
                }
              ]
            }
          }
        ],
        "Path": "/",
        "RoleName": {
          "Fn::Join": [
            "-",
            [
              "hello-serverless",
              "dev",
              {
                "Ref": "AWS::Region"
              },
              "lambdaRole"
            ]
          ]
        }
      }
    },
    "HelloLambdaFunction": {
      "Type": "AWS::Lambda::Function",
      "Properties": {
        "Code": {
          "S3Bucket": {
            "Ref": "ServerlessDeploymentBucket"
          },
          "S3Key": "serverless/hello-serverless/dev/1604007164601-2020-10-29T21:32:44.601Z/hello-serverless.zip"
        },
        "FunctionName": "hello-serverless-dev-hello",
        "Handler": "handler.hello",
        "MemorySize": 1024,
        "Role": {
          "Fn::GetAtt": [
            "IamRoleLambdaExecution",
            "Arn"
          ]
        },
        "Runtime": "nodejs12.x",
        "Timeout": 30
      },
      "DependsOn": [
        "HelloLogGroup"
      ]
    },
    "HelloLambdaVersionLHvlv1Vr1WXSDfXSllnpdYGEUU3kE1zRVKwhylC8": {
      "Type": "AWS::Lambda::Version",
      "DeletionPolicy": "Retain",
      "Properties": {
        "FunctionName": {
          "Ref": "HelloLambdaFunction"
        },
        "CodeSha256": "Ygy50Q3YjaGhnooUbUfrkrD0mDpKr7nZUJRAwZoo0bE="
      }
    },
    "ApiGatewayRestApi": {
      "Type": "AWS::ApiGateway::RestApi",
      "Properties": {
        "Name": "dev-hello-serverless",
        "EndpointConfiguration": {
          "Types": [
            "EDGE"
          ]
        },
        "Policy": ""
      }
    },
    "ApiGatewayMethodGet": {
      "Type": "AWS::ApiGateway::Method",
      "Properties": {
        "HttpMethod": "GET",
        "RequestParameters": {},
        "ResourceId": {
          "Fn::GetAtt": [
            "ApiGatewayRestApi",
            "RootResourceId"
          ]
        },
        "RestApiId": {
          "Ref": "ApiGatewayRestApi"
        },
        "ApiKeyRequired": false,
        "AuthorizationType": "NONE",
        "Integration": {
          "IntegrationHttpMethod": "POST",
          "Type": "AWS_PROXY",
          "Uri": {
            "Fn::Join": [
              "",
              [
                "arn:",
                {
                  "Ref": "AWS::Partition"
                },
                ":apigateway:",
                {
                  "Ref": "AWS::Region"
                },
                ":lambda:path/2015-03-31/functions/",
                {
                  "Fn::GetAtt": [
                    "HelloLambdaFunction",
                    "Arn"
                  ]
                },
                "/invocations"
              ]
            ]
          }
        },
        "MethodResponses": []
      }
    },
    "ApiGatewayDeployment1604007163167": {
      "Type": "AWS::ApiGateway::Deployment",
      "Properties": {
        "RestApiId": {
          "Ref": "ApiGatewayRestApi"
        },
        "StageName": "dev"
      },
      "DependsOn": [
        "ApiGatewayMethodGet"
      ]
    },
    "ApiGatewayApiKeyOnly-throttle1": {
      "Type": "AWS::ApiGateway::ApiKey",
      "Properties": {
        "Enabled": true,
        "Name": "only-throttle-key",
        "StageKeys": [
          {
            "RestApiId": {
              "Ref": "ApiGatewayRestApi"
            },
            "StageName": "dev"
          }
        ]
      },
      "DependsOn": "ApiGatewayDeployment1604007163167"
    },
    "ApiGatewayApiKeyOnly-quota1": {
      "Type": "AWS::ApiGateway::ApiKey",
      "Properties": {
        "Enabled": true,
        "Name": "only-quota-key",
        "StageKeys": [
          {
            "RestApiId": {
              "Ref": "ApiGatewayRestApi"
            },
            "StageName": "dev"
          }
        ]
      },
      "DependsOn": "ApiGatewayDeployment1604007163167"
    },
    "ApiGatewayApiKeyBoth1": {
      "Type": "AWS::ApiGateway::ApiKey",
      "Properties": {
        "Enabled": true,
        "Name": "both-key",
        "StageKeys": [
          {
            "RestApiId": {
              "Ref": "ApiGatewayRestApi"
            },
            "StageName": "dev"
          }
        ]
      },
      "DependsOn": "ApiGatewayDeployment1604007163167"
    },
    "ApiGatewayUsagePlanOnly-throttle": {
      "Type": "AWS::ApiGateway::UsagePlan",
      "DependsOn": "ApiGatewayDeployment1604007163167",
      "Properties": {
        "ApiStages": [
          {
            "ApiId": {
              "Ref": "ApiGatewayRestApi"
            },
            "Stage": "dev"
          }
        ],
        "Description": "Usage plan \"only-throttle\" for hello-serverless dev stage",
        "UsagePlanName": "hello-serverless-only-throttle-dev"
      }
    },
    "ApiGatewayUsagePlanOnly-quota": {
      "Type": "AWS::ApiGateway::UsagePlan",
      "DependsOn": "ApiGatewayDeployment1604007163167",
      "Properties": {
        "ApiStages": [
          {
            "ApiId": {
              "Ref": "ApiGatewayRestApi"
            },
            "Stage": "dev"
          }
        ],
        "Description": "Usage plan \"only-quota\" for hello-serverless dev stage",
        "UsagePlanName": "hello-serverless-only-quota-dev",
        "Quota": {
          "Limit": 3333,
          "Offset": 2,
          "Period": "MONTH"
        },
        "Throttle": {}
      }
    },
    "ApiGatewayUsagePlanBoth": {
      "Type": "AWS::ApiGateway::UsagePlan",
      "DependsOn": "ApiGatewayDeployment1604007163167",
      "Properties": {
        "ApiStages": [
          {
            "ApiId": {
              "Ref": "ApiGatewayRestApi"
            },
            "Stage": "dev"
          }
        ],
        "Description": "Usage plan \"both\" for hello-serverless dev stage",
        "UsagePlanName": "hello-serverless-both-dev",
        "Quota": {
          "Limit": 6666,
          "Offset": 2,
          "Period": "MONTH"
        },
        "Throttle": {
          "BurstLimit": 4444,
          "RateLimit": 5555
        }
      }
    },
    "ApiGatewayUsagePlanKeyOnly-throttle1": {
      "Type": "AWS::ApiGateway::UsagePlanKey",
      "Properties": {
        "KeyId": {
          "Ref": "ApiGatewayApiKeyOnly-throttle1"
        },
        "KeyType": "API_KEY",
        "UsagePlanId": {
          "Ref": "ApiGatewayUsagePlanOnly-throttle"
        }
      }
    },
    "ApiGatewayUsagePlanKeyOnly-quota1": {
      "Type": "AWS::ApiGateway::UsagePlanKey",
      "Properties": {
        "KeyId": {
          "Ref": "ApiGatewayApiKeyOnly-quota1"
        },
        "KeyType": "API_KEY",
        "UsagePlanId": {
          "Ref": "ApiGatewayUsagePlanOnly-quota"
        }
      }
    },
    "ApiGatewayUsagePlanKeyBoth1": {
      "Type": "AWS::ApiGateway::UsagePlanKey",
      "Properties": {
        "KeyId": {
          "Ref": "ApiGatewayApiKeyBoth1"
        },
        "KeyType": "API_KEY",
        "UsagePlanId": {
          "Ref": "ApiGatewayUsagePlanBoth"
        }
      }
    },
    "HelloLambdaPermissionApiGateway": {
      "Type": "AWS::Lambda::Permission",
      "Properties": {
        "FunctionName": {
          "Fn::GetAtt": [
            "HelloLambdaFunction",
            "Arn"
          ]
        },
        "Action": "lambda:InvokeFunction",
        "Principal": "apigateway.amazonaws.com",
        "SourceArn": {
          "Fn::Join": [
            "",
            [
              "arn:",
              {
                "Ref": "AWS::Partition"
              },
              ":execute-api:",
              {
                "Ref": "AWS::Region"
              },
              ":",
              {
                "Ref": "AWS::AccountId"
              },
              ":",
              {
                "Ref": "ApiGatewayRestApi"
              },
              "/*/*"
            ]
          ]
        }
      }
    }
  },
  "Outputs": {
    "ServerlessDeploymentBucketName": {
      "Value": {
        "Ref": "ServerlessDeploymentBucket"
      }
    },
    "HelloLambdaFunctionQualifiedArn": {
      "Description": "Current Lambda function version",
      "Value": {
        "Ref": "HelloLambdaVersionLHvlv1Vr1WXSDfXSllnpdYGEUU3kE1zRVKwhylC8"
      }
    },
    "ServiceEndpoint": {
      "Description": "URL of the service endpoint",
      "Value": {
        "Fn::Join": [
          "",
          [
            "https://",
            {
              "Ref": "ApiGatewayRestApi"
            },
            ".execute-api.",
            {
              "Ref": "AWS::Region"
            },
            ".",
            {
              "Ref": "AWS::URLSuffix"
            },
            "/dev"
          ]
        ]
      }
    }
  }
}
```

</details>

<b>Installed version</b>

```
Framework Core: 2.9.0 (local)
Plugin: 4.1.1
SDK: 2.3.2
Components: 3.3.0
```

**Comment by medikoo** [comment] 2020-10-30 14:26
@humodz thanks for report.

Indeed it's a regression introduced with https://github.com/serverless/serverless/pull/8460 

We can see that due to copy paste, `usagePlan.throttle` was replaced with `usagePlan.quote` https://github.com/serverless/serverless/commit/7bbd04a6933c1631646f16670e3d85c357450e7a#diff-825e8b84a59477e9dc1f90d39ebeef78fb335ca6cc4d88ecfcc19b4fec79e30f (cc @andreizet )

PR with a fix is welcome. Ideally if it comes with test case (configured through [`runServerless`](https://github.com/serverless/serverless/tree/master/test#unit-tests)) that prevents same error in a future

**Comment by andreizet** [comment] 2020-11-02 14:02
Please assign it to me. I've just double checked that merge request and it seems that `usagePlan.throttle` -> `usagePlan.quote` was the only issue.

**Closed** 2020-11-12 08:58 UTC
Labels: bug, cat/aws-event-api-gateway, good first issue, help wanted
