### ISSUE TITLE
Unable to remove License Key

### ISSUE THREAD

**Issue by kdybicz** [serverless/serverless#12698] opened 2024-07-23 12:30 UTC
### Issue description

Whenever I try to remove a License Key in the Serverless Dashboard I get `Something went wrong, please try again`.

### Context

Something that affects only Serverless v4 users:

If you accidentally leak a License Key, you cannot remove it to ensure it cannot be used by someone unauthorized.

**Comment by skierkowski** [comment] 2024-07-24 07:24
Thanks for reporting, @kdybicz. I reproed the issue on our end and we're on it.

**Comment by czubocha** [comment] 2024-07-25 15:04
Hi @kdybicz, sorry for the inconvenience. The issue is fixed now.

**Closed by czubocha** 2024-07-25 15:04 UTC
Labels: V4
