### ISSUE TITLE
Cannot install serverless@2.57.0

### ISSUE THREAD

**Issue by utkrist** [serverless/serverless#9943] opened 2021-09-13 07:58 UTC
When running `yarn add serverless@2.57.0 --dev` or 'npm install serverless'in my project, I am getting following error

```
> serverless@2.57.0 postinstall /home/utkrist/Desktop/IVyi/ivy-serverless/node_modules/serverless
> node ./scripts/postinstall.js

/home/utkrist/Desktop/IVyi/ivy-serverless/node_modules/string-width/index.js:7
        string = string.replace(emojiRegex(), '  ');
                        ^

TypeError: Cannot read property 'replace' of undefined
    at stringWidth (/home/utkrist/Desktop/IVyi/ivy-serverless/node_modules/string-width/index.js:7:18)
    at module.exports (/home/utkrist/Desktop/IVyi/ivy-serverless/node_modules/boxen/index.js:233:6)
    at Object.<anonymous> (/home/utkrist/Desktop/IVyi/ivy-serverless/node_modules/serverless/scripts/postinstall.js:37:11)
    at Module._compile (internal/modules/cjs/loader.js:777:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:788:10)
    at Module.load (internal/modules/cjs/loader.js:643:32)
    at Function.Module._load (internal/modules/cjs/loader.js:556:12)
    at Function.Module.runMain (internal/modules/cjs/loader.js:840:10)
    at internal/main/run_main_module.js:17:11

```

**Comment by pgrzesik** [comment] 2021-09-13 09:21
Hello @utkrist :wave: Do you have the same problem outside of your current project? What version of Node are you using?

**Comment by utkrist** [comment] 2021-09-13 09:48
> Hello @utkrist  Do you have the same problem outside of your current project? What version of Node are you using?

Hi @pgrzesik , I checked both the commands outside of the project. They are working fine. 
The node version I am using is v12.7.0 

This is the content of my package.json

```
{
  "name": "my-serverless",
  "version": "1.0.0",
  "private": true,
  "license": "UNLICENSED",
  "scripts": {
    "deploy:env": "sls deploy --stage $NODE_ENV",
    "deploy": "export NODE_ENV=development && yarn deploy:env",
    "deploy:prod": "export NODE_ENV=production && yarn deploy:env",
    "deploy:stage": "export NODE_ENV=staging && yarn deploy:env",
    "lint": "eslint src --ext ts,js --no-ignore --fix",
    "serve": "sls offline -P 4000",
    "serve:watch": "nodemon -e js,ts,jsx,tsx -x yarn serve",
    "tail:webhook": "sls logs --function webhook --tail",
    "test": "jest",
    "test:watch": "jest --watch",
    "build": "sls webpack",
    "watch:func": "sls invoke local --watch --function func --path fixtures/func-event.json"
  },
  "dependencies": {
    "node-fetch": "^2.6.0"
  },
  "devDependencies": {
    "@babel/core": "7.9.0",
    "@babel/preset-env": "7.9.5",
    "@babel/preset-typescript": "^7.9.0",
    "@types/aws-lambda": "^8.10.50",
    "@types/jest": "^25.2.1",
    "@types/node": "^12.7.5",
    "@types/node-fetch": "^2.5.6",
    "@typescript-eslint/eslint-plugin": "^2.29.0",
    "@typescript-eslint/parser": "^2.29.0",
    "aws-sdk": "^2.660.0",
    "babel-core": "^7.0.0-bridge.0",
    "babel-jest": "^25.4.0",
    "babel-loader": "^8.1.0",
    "eslint": "^6.8.0",
    "eslint-config-prettier": "^6.11.0",
    "eslint-config-standard": "^14.1.1",
    "eslint-import-resolver-typescript": "^2.0.0",
    "eslint-plugin-import": "^2.20.2",
    "eslint-plugin-jest": "^23.8.2",
    "eslint-plugin-jsx-a11y": "^6.2.3",
    "eslint-plugin-node": "^11.1.0",
    "eslint-plugin-promise": "^4.2.1",
    "eslint-plugin-security": "^1.4.0",
    "eslint-plugin-standard": "^4.0.1",
    "husky": "^4.2.5",
    "jest": "^25.4.0",
    "lint-staged": "^10.1.7",
    "nodemon": "^2.0.3",
    "prettier": "^2.0.5",
    "serverless": "^2.57.0",
    "serverless-dotenv-plugin": "^2.4.2",
    "serverless-iam-roles-per-function": "^3.2.0",
    "serverless-offline": "^6.1.4",
    "serverless-plugin-warmup": "5.0.0",
    "serverless-prune-plugin": "^1.4.2",
    "serverless-webpack": "^5.3.1",
    "ts-jest": "^25.4.0",
    "ts-loader": "^7.0.1",
    "typescript": "^3.8.3",
    "webpack": "^4.43.0",
    "webpack-node-externals": "^1.7.2"
  },
  "husky": {
    "hooks": {
      "pre-commit": "lint-staged && yarn test"
    }
  },
  "lint-staged": {
    "src/**/*.{js,ts}": [
      "yarn lint",
      "prettier --write",
      "git add"
    ]
  }
}
```

**Comment by medikoo** [comment] 2021-09-13 10:13
I've just looked into that, and it looks as bug in `boxen` -> https://github.com/sindresorhus/boxen/pull/60

**Comment by Caesarovich** [comment] 2021-09-13 10:31
I'm investigating this bug as soon as possible.

**Comment by ebsaral** [comment] 2021-09-13 11:41
The issue starts at v2.51.0

**Comment by Caesarovich** [comment] 2021-09-13 12:16
Hi,
As the author of the latest boxen feature (Wich is the one causing this issue) I apologize for the trouble caused.

## Bug investigation

I tried to reproduce the crash caused in the `serverless/scripts/postinstall.js:37` file but did not succeed. So I decided to dig deeper.  The issue is caused by a boxen dependency `string-width`. In the boxen's `package.json` file we can find in the dependencies: `"string-width": "^4.2.0"`. This means that whenever the package is installed, NPM will pick the `string-width` package from at least version 4.2.0 or higher. That's why in my local installation of boxen I have `string-width` version `4.2.2`.
I then investigated `string-width` between 4.2.0 and 4.2.2. I found out that in 4.2.0 there is this piece of code at the beginning of the module's main function:

```js
const stringWidth = string => {
	string = string.replace(emojiRegex(), '  ');

	if (typeof string !== 'string' || string.length === 0) {
		return 0;
	}
       // ....
```
This is the piece of code that causes the crash we see in this issue. The problem being that even before checking if the `string` variable is a valid string, it will attempt a regex replace on it. Causing the `TypeError: Cannot read property 'replace' of undefined` error on a null string.

This is later fixed on 4.2.1 with a commit replacing the above code with that:

```js
const stringWidth = string => {
	if (typeof string !== 'string' || string.length === 0) {
		return 0;
	}

        string = string.replace(emojiRegex(), '  ');
       // ....
```

**So the problem is a dependency one minor version too early.**

## Quick fix 

To fix this issue we need to ensure you have the `string-width` package version 4.2.1 or higher.
It is most likely that version 4.2.0 is already cached in your node_modules directory and it is why it doesn't install newer versions.

**That's why the simplest trick to quickly fix the issue is to delete the `string-width` folder inside the `node_modules` directory and re-run the npm installation process, forcing NPM to install the latest 4.2.2 version.**

## Fix

I will make sure to fix this dependency issue on the boxen side as soon as possible. I'll update on this issue regarding the advancement of this.

Again sorry for the troubles caused.

**Comment by medikoo** [comment] 2021-09-13 12:32
@Caesarovich great thanks for thorough explanations

> To fix this issue we need to ensure you have the string-width package version 4.2.1 or higher.

We actually do not use this dependency, this is the dependency of `boxen`. So I believe it's `boxen` that should ensure that at least v4.2.1 version of `string-width` is used, as otherwise there's a room for crash (see it has `^4.2.0` currently: https://github.com/sindresorhus/boxen/blob/012f0d9b5739400dee3eba992246a80da06b0ebb/package.json#L40)

**Comment by sindresorhus** [comment] 2021-09-13 12:53
Fix is out: https://github.com/sindresorhus/boxen/releases/tag/v5.1.1

**Comment by Caesarovich** [comment] 2021-09-13 12:59
Sindresorhus already commented it, so yeah fixed !

> We actually do not use this dependency, this is the dependency of boxen. So I believe it's boxen that should ensure that at least v4.2.1 version of string-width is used, as otherwise there's a room for crash 
My bad if you didn't understand correctly, I was actually speaking to individual installations, and how people could fix it locally. I wasn't blaming your package for it ^^

**Comment by pgrzesik** [comment] 2021-09-13 15:17
With `v2.58.0` that was released today it should be resolved as we depend on upgraded version of `boxen` explicitly.

**Closed by pgrzesik** 2021-09-13 15:17 UTC
Labels: bug/dependency
