### ISSUE TITLE
Can't deploy with master branch: "Cannot read property 'endsWith' of null"

### ISSUE THREAD

**Issue by bobby-brennan** [serverless/serverless#2383] opened 2016-10-14 15:46 UTC
# This is a Bug Report
## Description

Installed from master branch (needed to pull in https://github.com/serverless/serverless/pull/2014), and `serverless deploy` no longer works.  I get the error "Cannot read property 'endsWith' of null".

This happens with full Admin AWS credentials on the hello-world project created by `serverless create --template aws-nodejs`

For bug reports:
- What went wrong?
- What did you expect should have happened?
- What was the config you used?
- What stacktrace or error message from your provider did you see?
## Additional Data
- **_Serverless Framework Version you're using**_: 1.0.2
- **_Operating System**_: Ubuntu 14
- **_Stack Trace**_: below
- **_Provider Error messages**_: none

``` bash
$ SLS_DEBUG=true serverless deploy -v

Serverless: Packaging service...
Serverless: Removing old service versions...
Serverless: Uploading CloudFormation file to S3...
Serverless: Uploading service .zip file to S3...
Serverless: Updating Stack...
Serverless: Checking Stack update progress...

  Serverless Error ---------------------------------------

     Cannot read property 'endsWith' of null

  Stack Trace --------------------------------------------

ServerlessError: Cannot read property 'endsWith' of null
    at sdk.request.then.catch (/home/ubuntu/.npm-global/lib/node_modules/serverless/lib/plugins/aws/lib/monitorStack.js:97:26)
    at tryCatcher (/home/ubuntu/.npm-global/lib/node_modules/serverless/node_modules/bluebird/js/release/util.js:16:23)
    at Promise._settlePromiseFromHandler (/home/ubuntu/.npm-global/lib/node_modules/serverless/node_modules/bluebird/js/release/promise.js:510:31)
    at Promise._settlePromise (/home/ubuntu/.npm-global/lib/node_modules/serverless/node_modules/bluebird/js/release/promise.js:567:18)
    at Promise._settlePromise0 (/home/ubuntu/.npm-global/lib/node_modules/serverless/node_modules/bluebird/js/release/promise.js:612:10)
    at Promise._settlePromises (/home/ubuntu/.npm-global/lib/node_modules/serverless/node_modules/bluebird/js/release/promise.js:687:18)
    at Async._drainQueue (/home/ubuntu/.npm-global/lib/node_modules/serverless/node_modules/bluebird/js/release/async.js:138:16)
    at Async._drainQueues (/home/ubuntu/.npm-global/lib/node_modules/serverless/node_modules/bluebird/js/release/async.js:148:10)
    at Immediate.Async.drainQueues (/home/ubuntu/.npm-global/lib/node_modules/serverless/node_modules/bluebird/js/release/async.js:17:14)
    at runCallback (timers.js:574:20)
    at tryOnImmediate (timers.js:554:5)
    at processImmediate [as _immediateCallback] (timers.js:533:5)

  Get Support --------------------------------------------
     Docs:          docs.serverless.com
     Bugs:          github.com/serverless/serverless/issues

  Your Environment Infomation -----------------------------
     OS:                 linux
     Node Version:       6.7.0
     Serverless Version: 1.0.2
```

**Comment by pmuens** [comment] 2016-10-14 16:07
@bobby-brennan thanks for reporting!

It think I know what introduced the bug (a recent update to the `monitorStack` method). Will work on a fix!

**Comment by pmuens** [comment] 2016-10-14 16:08
BTW. Stack deployment should still work if you omit the `--verbose`/ `-v` flag.

**Comment by pmuens** [comment] 2016-10-14 16:47
@bobby-brennan could you provide your `serverless.yml` and a step-by-step list on how to reproduce this? Unfortunately I'm not able to reporduce this on my machine right now.

THanks for your help!

**Comment by bobby-brennan** [comment] 2016-10-14 18:12
FWIW I wasn't able to reproduce on OSX, just on Ubuntu 14.04.

```
npm install -g serverless/serverless
serverless create --template aws-nodejs && cd aws-nodejs
serverless deploy -v
```

**Comment by pmuens** [comment] 2016-10-14 20:18
Thanks! Hmm. That's really strange. I'll try to make it fail with the steps provided.

**Comment by bobby-brennan** [comment] 2016-10-14 20:22
Awesome, thanks for the quick response!

**Comment by bobby-brennan** [comment] 2016-10-15 04:21
FYI, removing the `-v` option didn't seem to help.

**Comment by bobby-brennan** [comment] 2016-10-15 04:48
Not sure this is the right fix but it stops the crash.

**Comment by shreyu86** [comment] 2016-10-21 22:56
I am also facing this issue:

* ***Serverless Framework Version you're using***: 1.0.3
* ***Operating System***: CentOS Linux 7
* ***Stack Trace***: below
* ***Provider Error messages***: below
```
# SLS_DEBUG=true serverless deploy -v
Serverless: Packaging service…
Serverless: Uploading CloudFormation file to S3…
Serverless: Uploading service .zip file to S3…
Serverless: Updating Stack…
Serverless: Checking Stack update progress…
 
  Serverless Error ---------------------------------------
 
     Cannot read property 'endsWith' of null
 
  Stack Trace --------------------------------------------
 
ServerlessError: Cannot read property 'endsWith' of null
    at provider.request.then.catch (/usr/lib/node_modules/serverless/lib/plugins/aws/lib/monitorStack.js:97:26)
    at tryCatcher (/usr/lib/node_modules/serverless/node_modules/bluebird/js/release/util.js:16:23)
    at Promise._settlePromiseFromHandler (/usr/lib/node_modules/serverless/node_modules/bluebird/js/release/promise.js:510:31)
    at Promise._settlePromise (/usr/lib/node_modules/serverless/node_modules/bluebird/js/release/promise.js:567:18)
    at Promise._settlePromise0 (/usr/lib/node_modules/serverless/node_modules/bluebird/js/release/promise.js:612:10)
    at Promise._settlePromises (/usr/lib/node_modules/serverless/node_modules/bluebird/js/release/promise.js:687:18)
    at Async._drainQueue (/usr/lib/node_modules/serverless/node_modules/bluebird/js/release/async.js:138:16)
    at Async._drainQueues (/usr/lib/node_modules/serverless/node_modules/bluebird/js/release/async.js:148:10)
    at Immediate.Async.drainQueues (/usr/lib/node_modules/serverless/node_modules/bluebird/js/release/async.js:17:14)
    at runCallback (timers.js:637:20)
    at tryOnImmediate (timers.js:610:5)
    at processImmediate [as _immediateCallback] (timers.js:582:5)
 
  Get Support --------------------------------------------
     Docs:          docs.serverless.com
     Bugs:          github.com/serverless/serverless/issues
 
  Your Environment Infomation -----------------------------
     OS:                 linux
     Node Version:       6.9.1
     Serverless Version: 1.0.3

```

**Comment by Raiju1** [comment] 2016-10-24 11:53
I upgraded from 1.0.2 to 1.0.3 today and ran into this issue on OSX.

Serverless Framework Version you're using: 1.0.3
Operating System: OSX 10.11.6
Stack Trace: below
Provider Error messages: below

```
SLS_DEBUG=true serverless deploy -v
Serverless: Packaging service…
Serverless: Uploading CloudFormation file to S3…
Serverless: Uploading service .zip file to S3…
Serverless: Updating Stack…
Serverless: Checking Stack update progress…
 
  Serverless Error ---------------------------------------
 
     Cannot read property 'endsWith' of null
 
  Stack Trace --------------------------------------------
 
ServerlessError: Cannot read property 'endsWith' of null
    at provider.request.then.catch (/usr/local/lib/node_modules/serverless/lib/plugins/aws/lib/monitorStack.js:97:26)
    at tryCatcher (/usr/local/lib/node_modules/serverless/node_modules/bluebird/js/release/util.js:16:23)
    at Promise._settlePromiseFromHandler (/usr/local/lib/node_modules/serverless/node_modules/bluebird/js/release/promise.js:510:31)
    at Promise._settlePromise (/usr/local/lib/node_modules/serverless/node_modules/bluebird/js/release/promise.js:567:18)
    at Promise._settlePromise0 (/usr/local/lib/node_modules/serverless/node_modules/bluebird/js/release/promise.js:612:10)
    at Promise._settlePromises (/usr/local/lib/node_modules/serverless/node_modules/bluebird/js/release/promise.js:687:18)
    at Async._drainQueue (/usr/local/lib/node_modules/serverless/node_modules/bluebird/js/release/async.js:138:16)
    at Async._drainQueues (/usr/local/lib/node_modules/serverless/node_modules/bluebird/js/release/async.js:148:10)
    at Immediate.Async.drainQueues (/usr/local/lib/node_modules/serverless/node_modules/bluebird/js/release/async.js:17:14)
    at runCallback (timers.js:574:20)
    at tryOnImmediate (timers.js:554:5)
    at processImmediate [as _immediateCallback] (timers.js:533:5)
 
  Get Support --------------------------------------------
     Docs:          docs.serverless.com
     Bugs:          github.com/serverless/serverless/issues
 
  Your Environment Infomation -----------------------------
     OS:                 darwin
     Node Version:       6.5.0
     Serverless Version: 1.0.3
```

**Comment by doapp-ryanp** [comment] 2016-10-25 03:30
I can confirm this on osx as well on `v1.0.3` WITHOUT specifying the `-v` flag.

**Comment by scott-wood-vgh** [comment] 2016-10-25 12:56
Same issue on OS X as the above users. If failed deployment wasn't caught by the integration tests, they probably need to be improved. 1.0.3 is not usable at present without deploy functionality, and I don't believe there is a workaround.

`sls deploy
Serverless: Packaging service…
Serverless: Uploading CloudFormation file to S3…
Serverless: Uploading service .zip file to S3…
Serverless: Updating Stack…
Serverless: Checking Stack update progress…

  Serverless Error ---------------------------------------

     Cannot read property 'endsWith' of null

  Get Support --------------------------------------------
     Docs:          docs.serverless.com
     Bugs:          github.com/serverless/serverless/issues

  Your Environment Infomation -----------------------------
     OS:                 darwin
     Node Version:       6.5.0
     Serverless Version: 1.0.3`

**Comment by nickeblewis** [comment] 2016-10-25 13:19
What is happening with this at the moment? Serverless for us guys is currently totally unusable, which is a shame

**Comment by maxfrigge** [comment] 2016-10-25 13:24
Downgrading seems to work
```bash
npm install -g serverless@1.0.2
```

**Comment by doapp-ryanp** [comment] 2016-10-25 14:14
@maxfrigge fwiw downgrade does not work for me due to this blocking bug in 1.0.2 https://github.com/serverless/serverless/issues/2404

**Comment by pmuens** [comment] 2016-10-25 14:26
Thanks for the steps to reproduce it. We got a fix for this which we'll merge soon #2395.

/cc @flomotlik @eahefnawy

**Comment by pmuens** [comment] 2016-10-31 09:50
Thanks for reporting and helping to fix it! #2576 is merged into master and resolves this bug 🎉

**Closed** 2016-10-31 09:49 UTC
Labels: bug, urgent

**Comment by robertoestivill** [comment] 2016-10-31 21:31
@pmuens Considering this is a blocker for osx, any plans to cut a release soon?

**Comment by flomotlik** [comment] 2016-11-01 08:45
@robertoestivill Tomorrow. We're releasing every two weeks on Wednesday going forward. Part of this release will be a blogpost explaining that.
