### ISSUE TITLE
Override functionName of CustomDashresourceDashapigwDashcwDashroleLambdaFunction

### ISSUE THREAD

**Issue by srashish** [serverless/serverless#7768] opened 2020-05-22 14:37 UTC
I'm facing issues while trying to override function name of CustomDashresourceDashapigwDashcwDashroleLambdaFunction which gets generated when using API Logs in serverless yaml under provider section.

I've seen that it follows the name convention - `${self:service}-${self:custom.stage}-custom-resource-apigw-cw-role,` I'm trying to override it to use something like this `${self:service}-${self:custom.prefix, self:custom.stage}-custom-resource-apigw-cw-role`

Initial error while deploying

`An error occurred: ApiGatewayLogGroup - /aws/api-gateway/feature-service-dev already exists.
`
Tried overriding this with renaming LogGroupName under resources

serverless.yml

`logs: restApi: true iamrole: arn:aws:iam::XXXXXXXXXX:role/serverlessApiGatewayCloudWatchRole
`
`resources: extensions: ApiGatewayLogGroup: Properties: LogGroupName: /aws/apigateway/${self:service}-${self:custom.prefix, self:custom.stage}
`
The generated CF template json which this section is below

`"CustomDashresourceDashapigwDashcwDashroleLambdaFunction": { "Type": "AWS::Lambda::Function", "Properties": { "Code": { "S3Bucket": "XXXXXXX", "S3Key": "serverless/service-name/dev/xxxxxxxxxxx-2020-05-18T12:46:39.248Z/custom-resources.zip" }, "FunctionName": "feature-service-dev-custom-resource-apigw-cw-role", "Handler": "apiGatewayCloudWatchRole/handler.handler", "MemorySize": 1024, "Runtime": "nodejs12.x", "Timeout": 180, "Role": { "Fn::GetAtt": [ "IamRoleCustomResourcesLambdaExecution", "Arn" ] } }, "DependsOn": [ "IamRoleCustomResourcesLambdaExecution" ] },`

<details>
<summary><code>serverless.yml</code></summary>

```
service: ${self:custom.service.name}

plugins:
  - serverless-iam-roles-per-function
  - serverless-aws-resource-names
  - serverless-pseudo-parameters
  - serverless-domain-manager
  - serverless-mocha-plugin
  - serverless-prune-plugin

custom:
  stage: ${opt:stage, self:provider.stage}
  region: ${opt:region, self:provider.region}
  prefix: ${opt:prefix, self:provider.stage}
  domain_manager_basemapping:
    dev:
      dev: 'features'
    prod:
      prod: 'features'
    other: ${opt:prefix, 'dev'}-features
  service:
        name: feature-xxxxx
  serverless-aws-resource-names:
    source: mapping.json
    variables:
      prefix: ${self:custom.prefix}
  domains:
    prod: api.${self:provider.region}.wayforward.io
    dev: api.${self:provider.region}.dev.wayforward.io
  customDomain:
    basePath: ${self:custom.domain_manager_basemapping.${self:provider.stage}.${self:custom.prefix, 'dev'}, self:custom.domain_manager_basemapping.other}
    domainName: ${self:custom.domains.${self:custom.stage}}
    stage: "${self:custom.stage}"
    createRoute53Record: true
  names:
    testClientSecretName: xxxxxxxxxxxxxxxx
  url:
    getFeatures: 'v1'
  settings:
    dev:
      xxxxxxxx: xxxxxxxx
      xxxxxxxxxx: xxxxxxxxxxx
      xxxxxxxxxx: xxxxxxxxxxx
      xxxxxxxxxxx: xxxxx-test.xxxxxxxxx.com
    prod:
      xxxxxxxxx: xxxxxxxxxxx
      xxxxxxxxxx: xxxxxxx
      xxxxxxxxxx: xxxxxxxxx
      xxxxxxxxxx: xxxxxxxxxxxxxxxx
  # serverless-prune-plugin
  prune:
    automatic: true
    number: 3
  serverless-iam-roles-per-function:
    defaultInherit: true

provider:
  name: aws
  region: ${opt:region, 'us-east-1'}
  stage: ${opt:stage, 'dev'}
  runtime: nodejs10.x
  environment:
    stage: ${self:custom.stage}
  deploymentBucket:
    name: xxxxxxxxxxxxx
  logs:
    restApi: true
    iamrole:  xxxxxxxxxxxxxxxxxxxxxxx


functions:
  auth:
    handler: functions/auth.handler
    cors: true
    provisionedConcurrency: 1
  get-features:
    handler: functions/feature.handler
    timeout: 60
    events:
      - http:
          path: v1
          method: get
          authorizer:
            name: auth
            resultTtlInSeconds: 0
          cors: true
    provisionedConcurrency: 1
        
resources:
  Resources:
    # This response is needed for custom authorizer failures cors support ¯\_(ツ)_/¯
    GatewayResponse:
      Type: 'AWS::ApiGateway::GatewayResponse'
      Properties:
        ResponseParameters:
          gatewayresponse.header.Access-Control-Allow-Origin: "'*'"
          gatewayresponse.header.Access-Control-Allow-Headers: "'*'"
        ResponseType: EXPIRED_TOKEN
        RestApiId:
          Ref: 'ApiGatewayRestApi'
        StatusCode: '401'
    AuthFailureGatewayResponse:
      Type: 'AWS::ApiGateway::GatewayResponse'
      Properties:
        ResponseParameters:
          gatewayresponse.header.Access-Control-Allow-Origin: "'*'"
          gatewayresponse.header.Access-Control-Allow-Headers: "'*'"
        ResponseType: UNAUTHORIZED
        RestApiId:
          Ref: 'ApiGatewayRestApi'
        StatusCode: '401'
    ApiGatewayLogGroup:
      Type: AWS::Logs::LogGroup
      Properties:
        LogGroupName: /aws/apigateway/${self:service}-${self:custom.prefix, self:custom.stage}
  extensions:
    ApiGatewayLogGroup:
      Properties:
        LogGroupName: /aws/apigateway/${self:service}-${self:custom.prefix, self:custom.stage}
```

</details>

<details>
<summary><b><code>sls --stage=dev --prefix=test deploy</code> output</b></summary>

```
An error occurred: ApiGatewayLogGroup - /aws/api-gateway/feature-service-dev already exists.
```

</details>

<b>1.71.3</b>

```
Serverless: Setting custom naming conventions...
Serverless: Setting custom function names...
Framework Core: 1.71.3
Plugin: 3.6.12
SDK: 2.3.0
Components: 2.30.11
` OUTPUT
```

**Comment by medikoo** [comment] 2020-05-25 06:36
> I'm facing issues while trying to override function name of CustomDashresourceDashapigwDashcwDashroleLambdaFunction

@srashish why do you want to override? There's intentionally no configuration mechanism in a framework that allows overriding it (this is not a bug)

Example of your `serverless.yml` involves a plugins. Please provide a bare framework test case. Otherwise it's likely we deal with issues introduced by plugins and those should be reported at plugin repositories not here

**Comment by medikoo** [comment] 2020-07-20 15:34
Closing as we received not enough details to process this further

**Closed by medikoo** 2020-07-20 15:34 UTC
Labels: question

**Comment by srashish** [comment] 2020-07-21 14:27
@medikoo So I have settings based on stage, I've declared two stages as of now, dev and prod. I'm trying to download multiple stacks using dev settings but tweaking their name to use my opt:param rather than default stage param.

Everything goes fine, till I wanted to use logs, since then I'm facing the trouble as my work-around with naming convention it's being applied to it. So in order to make it use my convention, I made some changes in Resources section,

resources: extensions: ApiGatewayLogGroup: Properties: LogGroupName:/aws/apigateway/${self:service}-${self:custom.prefix, self:custom.stage}

but the moment I did that, I stumbled upon this FunctionName issue using this mapping ${self:service}-${self:custom.prefix, self:custom.stage}-custom-resource-apigw-cw-role

**Comment by medikoo** [comment] 2020-07-21 14:54
@srashish for general support please use https://forum.serverless.com/ or https://www.serverless.com/slack

This issue tracker is purely for bug reports or feature requests, and those should be reported with full respect to template remarks
