### ISSUE TITLE
Issue with sls deploy using shared API Gateway and API Resources on 1.42.3

### ISSUE THREAD

**Issue by ocind** [serverless/serverless#6140] opened 2019-05-15 10:21 UTC
# Issue with sls deploy using shared API Gateway and API Resources on 1.42.3 

## Description
**What went wrong?**
This issue seems to be a regression as this works without issue on 1.41.1. We are creating a common api gateway on which multiple serverless.yml files would deploy their APIs to. We are following the instruction mentioned in  https://serverless.com/framework/docs/providers/aws/events/apigateway#easiest-and-cicd-friendly-example-of-using-shared-api-gateway-and-api-resources to achieve this.

After sls deploy is run, all the API Gateway Resources are deployed successfully, and all endpoints could be used just fine. However, on the post-deploy step of Serverless, a JS exception is being thrown.
The culprit is at line: https://github.com/serverless/serverless/blob/master/lib/plugins/aws/package/compile/events/apiGateway/lib/hack/updateStage.js#L75

This line checks if `provider.apiGateway && provider.apiGateway.restApiId` is a valid ApiGatewayRestApiId using regex which is defined at L8. However, in our use case we are using `Fn::ImportValue: ${self:custom.configFile.apiGatewayId}`, instead of the actual ApiGatewayRestApiId value. When this JS is run, it actually check if  the string `Fn::ImportValue: ${self:custom.configFile.apiGatewayId}` is a valid ApiGatewayRestApiId (which it's obviously not), instead of the actual resolved value of the Fn::ImportValue function.

Since this is not recognized as a valid ApiGatewayRestApiId, the execution will go inside the if clasuse in https://github.com/serverless/serverless/blob/master/lib/plugins/aws/package/compile/events/apiGateway/lib/hack/updateStage.js#L27, and error would be thrown at L40.

In order to fix this, I think we should not check the validity of ApiGatewayRestApiId using regex. I am not familiar with this newly introduced "hack" code, so I hope someone could look into this.

**What did you expect should have happened?**
sls deploy should complete without any error. We reverted Serverless back to 1.41.1 and this issue is not there.

**What stacktrace or error message from your provider did you see?**
Below is the full stack trace of the error:
```
Stack Trace --------------------------------------------
 
Error: Rest API could not be resolved. This might be casued by a custom API Gateway setup. With you current setup stage specific configurations such as `tracing`, `logs` and `tags` are not supportedPlease update your configuration or open up an issue if you feel that there's a way to support your setup.
    at resolveAccountId.call.then.then (/home/nicolas/.npm-global/lib/node_modules/serverless/lib/plugins/aws/package/compile/events/apiGateway/lib/hack/updateStage.js:50:17)
From previous event:
    at AwsCompileApigEvents.updateStage (/home/nicolas/.npm-global/lib/node_modules/serverless/lib/plugins/aws/package/compile/events/apiGateway/lib/hack/updateStage.js:26:8)
    at Object.after:deploy:deploy [as hook] (/home/nicolas/.npm-global/lib/node_modules/serverless/lib/plugins/aws/package/compile/events/apiGateway/index.js:85:28)
    at BbPromise.reduce (/home/nicolas/.npm-global/lib/node_modules/serverless/lib/classes/PluginManager.js:422:55)
From previous event:
    at PluginManager.invoke (/home/nicolas/.npm-global/lib/node_modules/serverless/lib/classes/PluginManager.js:422:22)
    at PluginManager.run (/home/nicolas/.npm-global/lib/node_modules/serverless/lib/classes/PluginManager.js:453:17)
    at variables.populateService.then (/home/nicolas/.npm-global/lib/node_modules/serverless/lib/Serverless.js:110:33)
    at processImmediate (internal/timers.js:443:21)
    at process.topLevelDomainCallback (domain.js:136:23)
From previous event:
    at Serverless.run (/home/nicolas/.npm-global/lib/node_modules/serverless/lib/Serverless.js:97:6)
    at serverless.init.then (/home/nicolas/.npm-global/lib/node_modules/serverless/bin/serverless:43:28)
    at /home/nicolas/.npm-global/lib/node_modules/serverless/node_modules/graceful-fs/graceful-fs.js:111:16
    at /home/nicolas/.npm-global/lib/node_modules/serverless/node_modules/graceful-fs/graceful-fs.js:45:10
    at FSReqCallback.args [as oncomplete] (fs.js:145:20)
From previous event:
    at initializeErrorReporter.then (/home/nicolas/.npm-global/lib/node_modules/serverless/bin/serverless:43:6)
    at processImmediate (internal/timers.js:443:21)
    at process.topLevelDomainCallback (domain.js:136:23)
From previous event:
    at /home/nicolas/.npm-global/lib/node_modules/serverless/bin/serverless:28:46
    at Object.<anonymous> (/home/nicolas/.npm-global/lib/node_modules/serverless/bin/serverless:65:4)
    at Module._compile (internal/modules/cjs/loader.js:816:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:827:10)
    at Module.load (internal/modules/cjs/loader.js:685:32)
    at Function.Module._load (internal/modules/cjs/loader.js:620:12)
    at Function.Module.runMain (internal/modules/cjs/loader.js:877:12)
    at internal/main/run_main_module.js:21:11

```

## Additional Data

* ***Serverless Framework Version you're using***: 1.42.3
* ***Operating System***: Ubuntu 18.04

**Comment by martinmicunda** [comment] 2019-05-15 23:05
I have the same issue when I use `Request Schema Validators` that was introduced in `1.42.0`. I also follow the instruction mentioned in [https://serverless.com/framework/docs/providers/aws/events/apigateway#easiest-and-cicd-friendly-example-of-using-shared-api-gateway-and-api-resources](https://serverless.com/framework/docs/providers/aws/events/apigateway#easiest-and-cicd-friendly-example-of-using-shared-api-gateway-and-api-resources )

**Comment by azakordonets** [comment] 2019-05-20 12:02
Any estimates on this issue ? Getting this problem as well.

**Comment by duro** [comment] 2019-05-20 21:40
It would appear that every release since 1.41.1 has broken usage of a shared API Gateway. I am now getting this error after upgrading:

```
Rest API could not be resolved. This might be casued by a custom API Gateway setup. With you current setup stage specific configurations such as `tracing`, `logs` and `tags` are not supportedPlease update your configuration or open up an issue if you feel that there's a way to support your setup.
```

**Comment by martinmicunda** [comment] 2019-05-28 03:59
Any update on this?

**Comment by duro** [comment] 2019-06-12 22:48
Version 1.45 was just released, has anything been done in that release to address this?

**Comment by duro** [comment] 2019-06-12 23:21
I have just confirmed this is not fixed in 1.45. The way I see it, Serverless has abandoned an upgrade path for people using a shared API Gateway, we've seen 3 or 4 versions go by with barely even an acknowledgement of this issue. I'm stuck on 1.41.

**Comment by akilmadan** [comment] 2019-07-16 06:29
Ouch, this is a painful but presumably trivial issue. Are we likely to see a resolution on this?

**Comment by Manzalber** [comment] 2019-07-16 06:42
I join the request. This is breaking our CI/CD pipeline as it results in a failed deployment although AWS Cloudformation says it's ok without rolling back. This avoids promoting stages and many more troubles, any update on this or if it could be included on 1.48 milestone?

**Comment by duro** [comment] 2019-07-16 22:46
@akilmadan, @Manzalber, @martinmicunda, @azakordonets  I ended up having to move the management of the shared gateway entirely out of serverless and into Terraform. Struggling with this issue really got me to see clearly how using serverless to manage things like shared infrastructure (API Gateway, Kinesis Streams, S3 Buckets, CloudFront distros, etc.) is not a sustainable practice.

Once I migrated the API Gateway out of serverless (which I'll be honest, was a PAINFUL process), and started "hard coding" the API Gateway ID, and Root Resource ID into my serverless services (using an SSM Parameter value, which Terraform also manages), I was able to upgrade to the latest Serverless version.

I'm not entirely sure why this seemed to get me back on the upgrade path, but I think is has to do with the issue at the heart of #6225 which added a warning about using tags, tracing, and log config options with a Shared Gateway.

Either way, I actually feel a lot safer with these shared infrastructure components not being managed by serverless, and in something like Terraform which is battle proven to be excellent at managing infrastructure as code. And these elements are much more "infrastructure" rather than application deployment elements (which is the way I see Lambdas and Route configuration.

**Comment by pbelabbes** [comment] 2019-07-19 08:29
I have the same issue. I had to downgrade my global serverless version to 1.41 to make the deployement to AWS works.

**Comment by joshmello** [comment] 2019-07-19 14:29
Any updates?

**Comment by duro** [comment] 2019-07-19 17:46
@pbelabbes see my comment above, I would highly encourage you to manage you shared gateway outside of serverless rather than how it is recommended in the docs. This was the only solution that managed to work for me.

**Comment by jangia** [comment] 2019-07-29 07:32
Having the same issue. I somehow managed to survive without shared API Gateway but it would be a lot nicer with having it. Is there any update?

**Comment by arjenbrandenburgh** [comment] 2019-08-05 20:15
Any update on this issue? The downgrade to serverless 1.41 works for me for now, but I'd rather use later versions obviously.

**Comment by duro** [comment] 2019-08-05 21:17
@arjenbrandenburgh did you see my comment above? You don't necessarily have to use Terraform to accomplish this, but essentially once I moved away from using the CloudFormation function `Fn::ImportValue` to fetch the API Gateway ID and Root Resource, and instead used a hard coded api ID and resource ID, I was able to get caught up to the latest version.

So the way I work now is I use something outside of serverless (in my case terraform, but you could use your own CF templates, or even something like [CDK](https://aws.amazon.com/cdk/)) to setup the API gateway, and then post the api ID and root ID to an SSM parameter.

Then I have my serverless config fetching the api ID and root ID from SSM like so:

```
  apiGateway:
    restApiId: ${ssm:/api-id-ssm-param}
    restApiRootResourceId: ${ssm:/root-id-ssm-param}
```

This has been working well for us, and I've been able to stay current with all new serverless version.

**Comment by arjenbrandenburgh** [comment] 2019-08-06 06:46
@duro Thanks for the elaboration on your fix. I will use that for now, but since it's still a workaround, it should be fixed at some point.

**Comment by duro** [comment] 2019-08-06 17:39
@arjenbrandenburgh while, yes, as per the serverless documentation, this does appear a workaround. To be be perfectly honest, after using serverless for a little while, this actually feels like a better practice. I started running into a lot of trouble with using serverless to manage these kinds of more persistent "infrastructure" and found serverless really shines in defining things that are purely application layer.

**Comment by pmuens** [comment] 2019-08-07 14:02
@ocind thanks for opening this issue :+1:

This shouldn't happen and it's definitely a regression we have to fix. We're currently looking into potential fixes.

**Comment by medikoo** [comment] 2019-08-07 14:59
Can you provide a minimal example of `serverless.yml` that exposes the issue (which is that: first deploy is successful, the following crash) ?

**Comment by medikoo** [comment] 2019-08-07 15:16
@ocind can you show related part of `serverless.yml` that crashes for you, with sensitive data masked out?

**Comment by coulson84** [comment] 2019-08-16 12:51
Assuming that I have read through everything and it is the same problem I am experiencing then some code like the below should cause the issue.

```
provider:
  apiGateway:
    restApiId:
      'Fn::ImportValue': ${{self:provider.stage}}-apiGateway
    restApiRootResourceId:
      'Fn::ImportValue': ${{self:provider.stage}}-apiGateway-rootResourceId
```

Here the API Gateway is created by external cloud formation templates and I want to import them for use with serverless

**Comment by medikoo** [comment] 2019-08-23 12:31
I've looked into it, and situation is as follows:

Before v1.42.0 We've supported `provider.tags` option service wide (it's used to tag lambda resources), with v1.42.0 we've enhanced it, so it also tags API Gateway stages.

Still as support of tagging API Gateway through CloudFormation is limited, we've introduced implementation that does this through SDK, but for that we need to resolve Rest API id programmatically. This issue is result of fact that we didn't implement resolution of Rest API id out of `Fn::ImportValue` instructions.

Fix for that is here https://github.com/serverless/serverless/pull/6586 (we will no longer crash if `provider.tags` is used with non resolvable programmatically Rest API id).

--- 

With other PR (#6583 )  I've also prepared support for Rest API id resolution through `Fn::ImportValue`. Still when doing that I realized that applying an API Gateway global settings to externally setup API Gateway raises issues. I've described that here: https://github.com/serverless/serverless/issues/6584
 
_(Merging #6583 will also fix this issue, but will add side effect of configured tags being also setup on external API Gateway - not sure whether that's wanted behavior)_

**Closed** 2019-08-23 12:40 UTC
Labels: bug, cat/api-gw

**Comment by christhomas** [comment] 2022-01-24 23:30
> @arjenbrandenburgh did you see my comment above? You don't necessarily have to use Terraform to accomplish this, but essentially once I moved away from using the CloudFormation function `Fn::ImportValue` to fetch the API Gateway ID and Root Resource, and instead used a hard coded api ID and resource ID, I was able to get caught up to the latest version.
> 
> So the way I work now is I use something outside of serverless (in my case terraform, but you could use your own CF templates, or even something like [CDK](https://aws.amazon.com/cdk/)) to setup the API gateway, and then post the api ID and root ID to an SSM parameter.
> 
> Then I have my serverless config fetching the api ID and root ID from SSM like so:
> 
> ```
>   apiGateway:
>     restApiId: ${ssm:/api-id-ssm-param}
>     restApiRootResourceId: ${ssm:/root-id-ssm-param}
> ```
> 
> This has been working well for us, and I've been able to stay current with all new serverless version.

@duro do you mind sharing with me your serverless.yml file? Cause I'm trying to do exactly what you appear to here and every time I do a serverless deploy, it creates a new api-gateway despite giving it an existing id and I'm not sure what it causing that to happen since I'm looking through the -v output and finding no errors. So I'm wondering where my problem is.
