### ISSUE TITLE
Can't disable deprecation warning

### ISSUE THREAD

**Issue by serverlesspolska** [serverless/serverless#8733] opened 2021-01-08 17:11 UTC
Deprecation warning is displayed when using `sls` command (i.e.`sls package` or `sls -version`) even when:
a) `SLS_DEPRECATION_DISABLE` env var is specified (with `LOAD_VARIABLES_FROM_ENV_FILES`)
b) when, in `serverless.yml` file there is the following conf:
```
disabledDeprecations:
  - LOAD_VARIABLES_FROM_ENV_FILES
```
Or `'*'` instead of `LOAD_VARIABLES_FROM_ENV_FILES`

<details>
<summary><b><code>`sls -version`</code> output</b></summary>

```
Serverless: Deprecation warning: Detected ".env" files. Note that Framework now supports loading variables from those files when "useDotenv: true" is set (and that will be the default from next major release)
            More Info: https://www.serverless.com/framework/docs/deprecations/#LOAD_VARIABLES_FROM_ENV_FILES
Framework Core: 2.18.0
Plugin: 4.4.2
SDK: 2.3.2
Components: 3.4.6
```
</details>

**Comment by pgrzesik** [comment] 2021-01-12 08:40
Hello @serverlesspolska, thanks for reporting. It is in fact a bug, that's caused by the fact that `loadEnvVariables` is called before `disabledDeprecations` are resolved as a part of `service.load` method (https://github.com/serverless/serverless/blob/master/lib/Serverless.js#L88-L101). At the moment, the workaround is to use `SLS_DEPRECATION_DISABLE` env variable.

We'd be happy to accept a PR with potential fix :raised_hands:

**Comment by mfogel** [comment] 2021-02-09 19:04
Note that setting ` useDotenv: false` in your serverless.yml does not make the warning go away. Instead, serverless prints a second warning to go along with the original one: `Serverless: Configuration warning at 'useDotenv': should be equal to constant`.

The typing here https://github.com/serverless/serverless/blob/v2.23.0/lib/configSchema.js#L124 might be better as `boolean` rather than `true`.

**Comment by pgrzesik** [comment] 2021-02-10 10:43
Hello @mfogel, thanks for mentioning that - we have a separate discussion about that specific matter available here: https://github.com/serverless/serverless/issues/8566 feel free to chime in with your opinion on the approach :100:

**Comment by mfogel** [comment] 2021-02-10 11:03
Thanks for the pointer @pgrzesik ! That thread was helpful

**Comment by thetumper** [comment] 2021-11-23 20:54
When using the wildcard ('*'), get the following error:

Configuration warning at 'disabledDeprecations[0]': should match pattern "^[A-Z0-9_]+$"

**Comment by pgrzesik** [comment] 2021-11-23 20:58
> When using the wildcard ('*'), get the following error:
> 
> Configuration warning at 'disabledDeprecations[0]': should match pattern "^[A-Z0-9_]+$"

Could you share how are you setting that? According to schema such syntax should work just fine:
```
disabledDeprecations: '*'
```

**Comment by thetumper** [comment] 2021-11-23 21:05
I had it as:

disabledDeprecations:
  - '*'

Copied from the example here:

https://www.serverless.com/framework/docs/deprecations

And then removed the first item ('CODE_1').

Ok -- so the array with only one item seems to have been the issue.  I can change to just the value, like you have, and then it works fine.

**Comment by pgrzesik** [comment] 2021-11-24 11:12
Thanks @thetumper - it looks like the example is wrong, we'd be happy to accept a PR that fixes it :raised_hands:

**Comment by medikoo** [comment] 2021-12-03 17:00
Closing as I believe it was already fixed (I cannot reproduce it.)

Note that `disabledDeprecations` setting in configuration works only for deprecations that are reported after the configuration file is parsed.

It's only `SLS_DEPRECATION_DISABLE` env variables that works for deprecations reported at any point of command processing

**Closed by medikoo** 2021-12-03 17:00 UTC
Labels: bug, help wanted, cat/cli
