### ISSUE TITLE
AWS IAM Role names are limited to 64 characters

### ISSUE THREAD

**Issue by codan84** [serverless/serverless#4918] opened 2018-04-18 16:56 UTC
# This is a Bug Report

## AWS IAM Role names are limited to 64 characters

When Lambda Function name is long enough, the IAM role name generated for this function can exceed the limit of 64 characters.  
The following error message will be shown when deploying:
```
1 validation error detected: Value 'this-is-a-very-very-long-name-far-too-long-for-iam-role-name-int-eu-west-1-lambdaRole' at 'roleName' failed to satisfy constraint: Member must have length less than or equal to 64
```

## Additional Data

* ***Serverless Framework Version you're using***: `1.26.0`
* ***Operating System***: `macOS Sierra (10.12.6)`
* ***Provider Error messages***: see above

**Comment by codan84** [comment] 2018-04-18 16:59
Personally, I think for anything that is generated based on service or function name and has length limits we should be able to provide overrides.  
I wouldn't mind forking the project and working on providing a name for the generated role and then submitting a PR, if people think this is a good solution.

**Comment by mymattcarroll** [comment] 2018-05-08 22:57
possible duplicate of #2856

**Comment by pmuens** [comment] 2019-01-15 12:33
Thanks for opening! Closing this since it's a duplicate of #2856

**Closed by pmuens** 2019-01-15 12:33 UTC
