### ISSUE TITLE
Cant update the logical ID of DynamoDB table

### ISSUE THREAD

**Issue by codepreneur** [serverless/serverless#1677] opened 2016-07-26 16:23 UTC
##### Serverless Framework Version: 

```
1.0.0-alpha.2
```

##### Operating System: 

![image](https://cloud.githubusercontent.com/assets/3421858/16957931/5fe5d11e-4dd6-11e6-9d95-a5734cdee160.png)

##### Expected Behavior:

Logical ID is changed inside cloud formation.

![image](https://cloud.githubusercontent.com/assets/3421858/17146076/e841ec18-5354-11e6-9b87-0dcf7dca8d6b.png)

I have successfully deployed with logical ID (at the top) of `PostsDynamo`, but then I changed `PostsDynamo` -> `LinksDynamo`, saved and redeployed and everything fell apart.

##### Actual Behavior:

![image](https://cloud.githubusercontent.com/assets/3421858/17146163/42a82fc8-5355-11e6-969a-166b5efe7abe.png)

```
17:09:37 UTC+0100	CREATE_FAILED	AWS::DynamoDB::Table	LinksDynamo	egamitv-links-dev already exists in stack arn:aws:cloudformation:us-west-2:12345678:stack/egamitv-dev/a43c123-4e7e-11e6-8a16-43a34a0e3228e
17:09:37 UTC+0100	CREATE_IN_PROGRESS	AWS::DynamoDB::Table	LinksDynamo	
```

so the only way really to change the logical ID of a DynamoDB table is to delete it and create it again

**Comment by codepreneur** [comment] 2016-07-27 12:53
@pmuens @eahefnawy I think this issue is related/similar to #1684

**Comment by eahefnawy** [comment] 2016-08-03 09:37
@codepreneur might be. Although #1684 is more related to APIG resources, while this issue seems like  a traditional CF template issue. Any particular reason you think this might be related?

I think this issue is more of a CloudFormation usage issue, because we simply take the resources you defined and merge them with the template without any manipulation. Maybe it's because of the `DeletionPolicy` you have?

**Comment by svdgraaf** [comment] 2016-08-05 12:06
@codepreneur I can confirm that this is a CF issue.

On the first deploy, you created a DynamoDB table (with a resource name of `PostsDynamo`, and the table name `egamitv-links-dev`. Now on this second go, you changed the resource name. CF thinks you want to create another dynamotable, tries to create it, but fails, because a Dynamo table with that name already exists (your previous one).

CF will only start to cleanup old resources -after- a successful deployment of a stack.

In this case, you have 2 options:
- Remove your custom resources (comment it out). Deploy, add the resource, and deploy.
- Change the name of your table from `${service}-links-${stage}` to `${service}-posts-${stage}` (keep the new resource name).

In both cases, you will lose the current table with it's data, so be aware of that.

**Comment by eahefnawy** [comment] 2016-08-10 06:17
@svdgraaf What a fantastic analysis! 👏

**Comment by flomotlik** [comment] 2016-08-12 07:36
@codepreneur is this also resolved with your finding or what @svdgraaf mentioned? As we're getting closer to beta release I'm currently going through open issues and closing them. I'm closing for now, in case this is still an issue let me know and we'll reopen

**Closed by flomotlik** 2016-08-12 07:36 UTC
Labels: bug

**Comment by codepreneur** [comment] 2016-08-12 08:24
@flomotlik yeap, its a CF issue not `serverless`.
