### ISSUE TITLE
Please don't touch .bashrc

### ISSUE THREAD

**Issue by q42jaap** [serverless/serverless#5829] opened 2019-02-13 09:20 UTC
Just don't...

I'm using serverless as a local dependency and call with `npx serverless` or `npx sls`. I really don't want serverless installed globally, since I use nvm and I don't want to install a bunch of tools every time I switch my node version.

Can the install script detect whether I'm installing locally or globally. If installing locally, it doesn't make any sense what ends up in bashrc anyhow...

**Comment by pmuens** [comment] 2019-02-13 13:41
Thanks for opening @q42jaap 👍

Closing this issue since it's a duplicate of https://github.com/serverless/serverless/issues/4069.

**Closed by pmuens** 2019-02-13 13:41 UTC
Labels: cat/dx, enhancement
