### ISSUE TITLE
deploy development not found in serverless 1.33.0

### ISSUE THREAD

**Issue by hiddestokvis** [serverless/serverless#5493] opened 2018-11-15 16:39 UTC
# This is a Bug Report

## Description

* What went wrong?
After upgrading to serverless 1.33.0 I get the following error:

`Serverless command "deploy development" not found. Did you mean "deploy"? Run "serverless help" for a list of all available commands.`

on running: `serverless deploy --verbose --stage development`

* What did you expect should have happened?

Deploy the application the the development stage. Downgrading to 1.32.0 fixes the issue.

## Additional Data

* ***Serverless Framework Version you're using***: 1.33.0
* ***Operating System***: Darwin
* ***Stack Trace***:
* ***Provider Error messages***:

**Comment by Enase** [comment] 2018-11-15 16:45
duplicate of https://github.com/serverless/serverless/issues/5491

**Comment by jkozera** [comment] 2018-11-15 17:07
> duplicate of #5491

Actually, it's a different issue. See https://github.com/serverless/serverless/issues/5491#issuecomment-439115111

**Comment by Enase** [comment] 2018-11-15 17:39
I found the reason and it has nothing to do with any plugin. it relates to options processing.

**STEPS TO REPRODUCE:**
1. Use any serverless command, e.g. `sls deploy` or `sls invoke local`
2. Add two options in a way when the first option goes without any value and second option set a value. Example: `sls deploy --option1 --option2 optionValue`

_Current result:_
```
sls deploy --option1 --option2 optionValue
 
  Serverless Error ---------------------------------------
 
  Serverless command "deploy optionValue" not found. Did you mean "deploy"? Run "serverless help" for a list of all available commands.
 
  Get Support --------------------------------------------
     Docs:          docs.serverless.com
     Bugs:          github.com/serverless/serverless/issues
     Issues:        forum.serverless.com
 
  Your Environment Information -----------------------------
     OS:                     darwin
     Node Version:           8.10.0
     Serverless Version:     1.33.0
```

**Comment by jkozera** [comment] 2018-11-15 17:50
Indeed, I've just reproduced this case as well, and `v1.32.0` it doesn't occur.

**Comment by jkozera** [comment] 2018-11-15 17:53
> duplicate of #5491

So I've just also verified that https://github.com/serverless/serverless/pull/5492 fixes it too, so it is actually the same issue — sorry about the confusion! :)

**Comment by dschep** [comment] 2018-11-15 18:19
As @jkozera pointed out, #5492 fixes this too.

**Closed by dschep** 2018-11-15 18:19 UTC
