### ISSUE TITLE
1.18.0 - serverless package command acting weird

### ISSUE THREAD

**Issue by newbreedofgeek** [serverless/serverless#3995] opened 2017-07-26 03:10 UTC
# This is possibly a bug

## Description
We use serverless a lot in our org, prior to last week we were using "1.15.3" (in our package.json we use ^1.13.0 and this resolved to 1.15.3 when installed). We use serverless in our build server to package our app and deploy entire cloud formation stacks.

For bug reports:
* What went wrong?
in our serverless.yml we have some rules to exclude some files in the package:
```
package:
  exclude:
    - dist/**
    - README.md
    - node_modules/serverless/**
    - node_modules/nyc/**
    - node_modules/mocha/**
    - node_modules/chai/**
    - node_modules/sinon/**
    - node_modules/sinon-chai/**
  # include:
```
This is primarily to exclude dev dependencies from deployment.

When "1.15.3" was used in our build server, all the package.json "dependencies" were downloaded and packaged but yesterday we ran some builds and "1.18.0" was used in our build servers. Now a lot of our package.json "dependencies" were not packaged for us and our lambdas were all failing.

I tried to debug but no luck. (I took off the entire "package:" section away and it till only packages a few npm modules)

We had to roll back and hardcode "1.15.3" to get it working.

* What did you expect should have happened?
There should no no difference between how package works in these versions.

* What was the config you used?
Standard config, package: given above

* What stacktrace or error message from your provider did you see?
No stack trace, but sometimes in our build server file system we saw files like this "node-dev-dependencies-3f1c419cac0e7885" where the excluded npm modules were listed. One example was "bluebird" - which never got packaged.

## Additional Data

* ***Serverless Framework Version you're using***: 1.18.0
* ***Operating System***: Linux
* ***Stack Trace***:
* ***Provider Error messages***:

**Comment by pmuens** [comment] 2017-07-26 06:43
Hey @newbreedofgeek thanks for opening! 👍

Yes, unfortunately this is currently a bug in the automatic dev dependency exclusion. However we already have a PR in the pipeline which will fix this issue.

I'll close this one for now since it's a duplicate of https://github.com/serverless/serverless/issues/3972.

If you're using 1.18 you can opt out of automatic dev dependency exclusion with the `excludeDevDependencies` config. You can find more about that [here](https://github.com/serverless/serverless/issues/3972#issuecomment-317643149).

Feel free to comment / re-open if you have any questions or the bug is still around after we've merged the fix and published a patch release.

**Closed** 2017-07-26 06:44 UTC
