### ISSUE TITLE
AWS SSO doesn't seem to work with SERVERLESS_LICENSE_KEY

### ISSUE THREAD

**Issue by kdybicz** [serverless/serverless#12620] opened 2024-06-20 16:46 UTC
### Issue description

I'm working on documentation about migration to Serverless v4 and I already somehow managed to make everything work, but to make sure my results were reproducible I've `rm -Rf ~/.serverless ~/.serverlessrc` to start everything from scratch... and here my problems begin. Se're using AWS SSO and I wanted to use `SERVERLESS_LICENSE_KEY` only(!) for validation that I'm allowed to use sls v4. I'm getting such errors now:

```
▶ aws sso login
Attempting to automatically open the SSO authorization page in your default browser.
If the browser does not open or you wish to use a different device to authorize this request, open the following URL:

https://device.sso.eu-west-1.amazonaws.com/

Then enter the code:

FCPP-JSTW
Successfully logged into Start URL: https://company.awsapps.com/start


▶ SERVERLESS_LICENSE_KEY=my-license-key npx sls package --stage staging


✖ AWS credentials missing or invalid. Run "serverless" to set up AWS credentials, or learn more in our docs: http://slss.io/aws-creds-setup. Original error from AWS: Could not load credentials from any providers


▶ yarn sls
yarn run v1.22.19
$ /Users/kamil/work/Phoenix/node_modules/.bin/sls

Serverless ϟ Framework

Welcome to Serverless Framework V.4

This is a Serverless Framework Service. Let's do some quick checks to ensure it's set up correctly.

Your Serverless Framework Service is ready to deploy.


✨  Done in 3.40s.


▶ SERVERLESS_LICENSE_KEY=my-license-key npx sls package --stage staging


✖ AWS credentials missing or invalid. Run "serverless" to set up AWS credentials, or learn more in our docs: http://slss.io/aws-creds-setup. Original error from AWS: Could not load credentials from any providers



▶ yarn sls login
yarn run v1.22.19
$ /Users/kamil/work/Phoenix/node_modules/.bin/sls login

Serverless ϟ Framework

Welcome to Serverless Framework V.4

✔ Please login/register or provide a license key · Add Another License Key

Obtain a Serverless Framework License Key through the dashboard at https://app.serverless.com, suitable for those not using the dashboard personally or in a team. Get licenses via the Dashboard or AWS Marketplace. For pricing, visit https://serverless.com. For inquiries, email support@serverless.com.

✔ Enter your License Key (input will be hidden) · 

✔ Would you like to set "company" as the default Org to use with Serverless Framework? (Y/n) · true


✔ License Key successfully validated and saved.

✨  Done in 11.93s.


▶ npx sls package --stage staging


✖ AWS credentials missing or invalid. Run "serverless" to set up AWS credentials, or learn more in our docs: http://slss.io/aws-creds-setup. Original error from AWS: Could not load credentials from any providers



▶ aws sso login
Attempting to automatically open the SSO authorization page in your default browser.
If the browser does not open or you wish to use a different device to authorize this request, open the following URL:

https://device.sso.eu-west-1.amazonaws.com/

Then enter the code:

HWRD-WJZV
Successfully logged into Start URL: https://company.awsapps.com/start


▶ npx sls package --stage staging


✖ AWS credentials missing or invalid. Run "serverless" to set up AWS credentials, or learn more in our docs: http://slss.io/aws-creds-setup. Original error from AWS: Could not load credentials from any providers


▶ npx sls package --stage staging


✖ AWS credentials missing or invalid. Run "serverless" to set up AWS credentials, or learn more in our docs: http://slss.io/aws-creds-setup. Original error from AWS: Could not load credentials from any providers



▶ npx sls --version

Serverless ϟ Framework

 • 4.1.5

                                                55m ⚑  
▶ rm -Rf ~/.serverless ~/.serverlessrc        

▶ SERVERLESS_LICENSE_KEY=my-license-key npx sls package --stage staging


✖ AWS credentials missing or invalid. Run "serverless" to set up AWS credentials, or learn more in our docs: http://slss.io/aws-creds-setup. Original error from AWS: Could not load credentials from any providers
```

### Context

# Service Overview
- Serverless Framework Version: 4.1.5
- Service Path: /Users/kamil/work/Phoenix
- Service Config File: serverless.yml
- Service Name: phoenix
- Service Runtime: nodejs20.x
- Service Stage: ${opt:stage,'development'}
- Service Region: eu-west-1
- Command: package --stage staging
- Error Code: AWS_CREDENTIALS_MISSING

**Comment by kdybicz** [comment] 2024-06-21 12:48
We use the AWS SSO with `AWS_PROFILE` which might be not supported by SLS. When using `AWS_ACCESS_KEY_ID` and `AWS_SECRET_ACCESS_KEY` it works nicely. This makes our CI/CD work, but it breaks in the local dev environment.

**Comment by austencollins** [comment] 2024-06-21 18:08
@kdybicz Thanks for reporting. We'll look into this.

**Comment by czubocha** [comment] 2024-06-26 14:15
Hey @kdybicz, thanks for sharing more details. I believe I know where the problem is. We’ll release the fix shortly and I’ll keep you updated.

**Comment by czubocha** [comment] 2024-07-03 12:07
Hi @kdybicz, we included a fix for resolving the AWS profile in the latest release, feel free to try this out now.

**Closed** 2024-07-03 12:07 UTC
Labels: V4
