### ISSUE TITLE
After integrating Api getaway and lambda on Amazon console I see error lile "Could not list api-gateway event sources."

### ISSUE THREAD

**Issue by olegZastavnyi** [serverless/serverless#1816] opened 2016-08-10 14:07 UTC
##### Serverless Framework Version:

beta 1.0
##### Operating System:

windows
##### Additional Details:

After integrating Api getaway and lambda on Amazon console(Lambda tab) I see error lile "Could not list api-gateway event sources."

My yaml file:
Functions:
  lambdaFunction:
    handler: com.myHandler.DataExtractorLambda
    events:
      - schedule: cron(0/1 \* \* \* ? *)
      - http:
          path: publicGetaway/getResources
          method: get

Note: Schedule trigger is available for editing and works fine.

**Comment by pmuens** [comment] 2016-08-10 15:56
@olegZastavnyi thanks for reporting!

Could you provide the indentation of your `serverless.yml` file as wrong indentation might lead to the fact that events are not parsed how they should be?

**Comment by olegZastavnyi** [comment] 2016-08-11 08:01
[test.txt](https://github.com/serverless/serverless/files/412738/test.txt)

**Comment by olegZastavnyi** [comment] 2016-08-11 16:23
Any idea what is wrong ?

**Comment by pmuens** [comment] 2016-08-12 05:28
@olegZastavnyi could you post a screenshot of you `serverless.yml` file so that I can see how it is indented?

Have you looked in the API Gateway service section on AWS if the gateway is deployed there?

**Comment by olegZastavnyi** [comment] 2016-08-12 08:38
@pmuens  Yes, it present and works but I cant see it on lambda( see screen)

**Comment by pmuens** [comment] 2016-08-12 15:34
Faced something similar with other AWS resources. Might be an AWS issue and related to this one:

https://github.com/serverless/serverless/issues/1805

/cc @eahefnawy

**Comment by olegZastavnyi** [comment] 2016-08-16 14:32
@pmuens is it possible to change properties (Event) in existing bucket by using serverless ?

**Comment by pmuens** [comment] 2016-08-16 16:56
@olegZastavnyi You can attach an existing bucket through overwriting by using the custom resources section. The PR https://github.com/serverless/serverless/pull/1844 was merged today and will be released in the Beta.2.

However we're also about to improve the overall event syntax and support for those cases.

**Comment by olegZastavnyi** [comment] 2016-08-17 07:40
@pmuens  I need to have it now, no time for waiting release. Any other options ?

**Comment by pmuens** [comment] 2016-08-17 08:43
@olegZastavnyi the Beta 2 was released a few hours ago you can update Serverless and should have everything in place I described above.

**Comment by olegZastavnyi** [comment] 2016-08-17 10:35
@pmuens Could you please provide some detailed description how to update existing s3 bucket(created by other system) for sqs notification by using "custom resources" section ?

**Comment by pmuens** [comment] 2016-08-17 11:44
@olegZastavnyi You can add "normal" CloudFormation definitions (such as `Resources` or `Outputs`) to the `resources` section in the `serverless.yml` file. This way you can add your S3 bucket and SQS definition.

This documentation shows you how you can do it: https://github.com/serverless/serverless/blob/master/docs/guide/custom-provider-resources.md#adding-custom-provider-resources

There's also no direct need to translate the corresponding CloudFormation definitions to Yaml as you can write them in a JSON file and reference them in the `serverless.yml` file with the help of JSON-Ref. You can see an example of JSON-Ref usage at the end of the example `serverless.yml` file here: https://github.com/serverless/serverless/blob/master/docs/understanding-serverless/serverless-yml.md#serverlessyml

**Comment by olegZastavnyi** [comment] 2016-08-17 15:06
@pmuens Thansk for response. One more question, how to install beta2?
 npm install -g serverless@beta2 ?

**Comment by pmuens** [comment] 2016-08-17 15:12
@olegZastavnyi An `npm install -g serverless@beta` should pull the beta 2 :-)

**Comment by olegZastavnyi** [comment] 2016-08-17 15:32
@pmuens  Just tried, and was not able to modify existing s3 bucket(which was created not by serverless) and got exception "bucket already exists"

**Comment by pmuens** [comment] 2016-08-18 14:03
Closing this one as we've moved this conversation to E-Mails

**Comment by yishaic** [comment] 2016-09-13 07:08
Hi, I'm having the same problem("Could not list api-gateway event sources."), what is the solution for that?
I'm using serverless 1.0.0-rc.1, on osx. I only created service with `serverless create -t aws-nodejs` and then edited `serverless.yml` and uncommented the already existing lines of
`    events:
      - http:
          path: users/create
          method: get`
and then deployed.

**Comment by olegZastavnyi** [comment] 2016-09-13 08:58
I've not found the solution.

**Comment by yishaic** [comment] 2016-09-14 05:38
@pmuens can you help?

**Comment by pmuens** [comment] 2016-09-14 06:18
Hmm that's a pretty weird bug. Could you maybe create an example repository with the whole project so that we can clone and inspect it?

/cc @flomotlik @eahefnawy

**Comment by yishaic** [comment] 2016-09-14 07:04
@pmuens here is the example repository:
https://github.com/yishaic/serverless-bug-example

**Comment by flomotlik** [comment] 2016-09-15 13:03
@yishaic this looks like an IAM issue where you don't actually have the rights to do this. Are you admin on this account?

**Comment by yishaic** [comment] 2016-09-16 13:24
@flomotlik if you mean to the user I'm using in my aws cli, then yes I'm in admin group and I have the AdministratorAccess policy. And in any way, the API itself is created and available in the Api Gateway service, I just can't see it on lambda(this is the same behaviour @olegZastavnyi had).

**Comment by andymac4182** [comment] 2016-09-17 02:52
@flomotlik I have this same issue but I don't use the triggers screen normally. Sounds like a AWS bug.

**Comment by yishaic** [comment] 2016-09-19 06:41
@flomotlik @pmuens have you tried to use the example repo I've created? Have you succeeded reproducing the error?
When I create a Lambda function by myself at AWS GUI everything seems ok, only through serverless there is the described behaviour.

**Comment by kbariotis** [comment] 2016-10-25 18:00
I confirm the bug in the latest stable version.

My `serverless.yml`:
```
service: bot

provider:
  name: aws
  runtime: nodejs4.3
  region: eu-west-1

functions:
  trigger:
    handler: handler.trigger
    events:
      - http:
          path: trigger
          method: post
```

**Comment by gozup** [comment] 2016-10-28 15:05
Hi,

Same as @kbariotis for me. Last stable release produces "Could not list api-gateway event sources." error on Lambda's dashboard.

+1

**Comment by flomotlik** [comment] 2016-10-31 12:55
@kbariotis and @gozup could you post a picture of the AWS Console that shows this?

**Comment by pmuens** [comment] 2016-10-31 13:16
@flomotlik here's a screenshot: https://github.com/serverless/serverless/issues/1816#issuecomment-239096534

**Comment by gozup** [comment] 2016-11-02 09:39
@flomotlik here is mine

![aws_lambda](https://cloud.githubusercontent.com/assets/788187/19923613/8f0fbc2e-a0e8-11e6-90f4-3dbc18a8a249.png)

Cheers

**Comment by Some1Else** [comment] 2016-11-14 07:40
Another one with `Could not list api-gateway event sources` in the Dashboard here

**Comment by jhlb** [comment] 2016-11-15 00:35
I'm not even using this project at the moment but I discovered this thread when researching my own issue (same display on API as pictured by gozup) during the AWS Lambda microservice example.

It was due to some Function Policies I had created. I looked at the policies via:

`aws lambda get-policy --function-name myfunction | jq -r .Policy | tr -d '\' | jq` 

(everything after the 1st pipe is just for formatting)

After deleting some policies I had created (via `aws lambda remove-permission`, leaving only the two that (I assume) were created automatically by the Lambda blueprint, the Triggers tab once again showed the API gateway source. 

Just in case this is useful, or for whoever else like me ends up here. Regards --

**Comment by demetrio812** [comment] 2016-12-03 13:12
Same problem here, just created a new java template and tried to deploy the hello function with admin access user...

**Comment by pmuens** [comment] 2016-12-03 16:22
@demetrio812 thanks for posting this.

The Java templates need some updates so that the `LAMBDA-PROXY` integration can be used (which is the default one). Could you try to change the http part from

```yml
http:
  path: hello
  method: get
```

to something like this:

```yml
http:
  path: hello
  method: get
  integration: LAMBDA
```

That should do the trick. The `LAMBDA-PROXY` integration is the default one. The function needs to handle the response parameters, headers etc. programatically if this is used (see https://serverless.com/framework/docs/providers/aws/events/apigateway#lambda-proxy-integration).

**Comment by heapifyman** [comment] 2016-12-14 00:55
I still experience the same issue with serverless 1.3.0 aws-java-maven template, even when adding `integration: lambda` to the http event. I see the same error message as in the screenshots provided by @olegZastavnyi and @gozup above.

**Comment by samuelpowell** [comment] 2017-01-04 09:08
This problem persists, can the issue be reopened?

**Comment by pmuens** [comment] 2017-01-04 10:08
Thanks for reporting that this is still an issue!

Reopening...

**Comment by j3ddesign** [comment] 2017-01-14 13:15
Hi,
I've just run into this issue myself, and was wondering if there was any manual workaround while the automated process gets updated? Not sure if it's related but I'm having cors issues too, and I had assumed this might be connected. (I have cors enabled in my .yml)

**Comment by yhjor1212** [comment] 2017-01-17 11:11
Same here

**Comment by bansalkishan** [comment] 2017-01-25 11:11
is there any ETA?

**Comment by logemann** [comment] 2017-03-03 21:33
same here with serverless v1.8 on macos x. The API gateway basically works but i just cant see the trigger in the AWS console. Wondering how i reveal the URL after i close my shell window with the deploy information printed form serverless which includes the endpoint.

**Comment by pmuens** [comment] 2017-03-05 10:42
@logemann thanks for the update! 👍 

> Wondering how i reveal the URL after i close my shell window with the deploy information printed form serverless which includes the endpoint.

You can run `serverless info` every time which will print out the same service info you'll get after each deployment.

**Comment by lucabarze** [comment] 2017-03-20 16:36
verified using serverless v.19 on macos x. Everything works fine, but I can not see the trigger in AWS console with the error "Could not list api-gateway event sources."

**Comment by destebanm** [comment] 2017-03-21 16:31
Hey!
Same here, with 1.9.0 on Ubuntu, everything works fine, but I can not see the trigger in AWS console with the error "Could not list api-gateway event sources."

I am using JAVA functions.

This is from serverless.yml

```
functions:
  createCustomer:
    handler: com.naevatec.iot.lambda.CustomerRequestHandler::createCustomer
    events:
      - http:
          path: customers/
          method: post
```

Thanks!

**Comment by realseanp** [comment] 2017-03-27 01:16
I am having this same issue

**Comment by outperformit** [comment] 2017-04-05 16:42
I'm also encountering this issue on serverless version 1.10.1.

**Comment by selenarakowski** [comment] 2017-04-05 19:33
I am also having this issue

**Comment by takecian** [comment] 2017-04-08 11:31
+1

**Comment by rikbrown** [comment] 2017-04-12 21:23
+1 on macOS.

**Comment by ilyache** [comment] 2017-04-13 14:03
Also having this on serverless 1.8.0

**Comment by shikhirsingh** [comment] 2017-04-24 06:50
+1 on macOS using serverless 1.11.0

**Comment by rwestbrookjr** [comment] 2017-04-26 22:06
+1 on windows using serverless 1.12.0

**Comment by bouchja1** [comment] 2017-04-28 15:44
+ 1 on macOS Sierra, serverless 1.11.0

**Comment by AaronAmstutz** [comment] 2017-05-05 23:45
+1 on macOS Sierra, serverless 1.12.1

**Comment by vimto** [comment] 2017-05-07 09:38
+1 on macOS Sierra, serverless 1.12.1

**Comment by pmuens** [comment] 2017-05-19 13:46
Thank you everyone for reporting. This seems to be smth. on AWS end 🤔 

I'm closing this issue for now to keep the issue count low since this is just a bug which impacts the displaying in the AWS console and not the functionality.

**Closed by pmuens** 2017-05-19 13:46 UTC
Labels: kind/bug, stage/accepted
