### ISSUE TITLE
Resource DynamoDb Error on deploy in another region

### ISSUE THREAD

**Issue by rdehnhardt** [serverless/serverless#3868] opened 2017-06-27 16:36 UTC
# Bug Report

## Description

Deploy crashes when I try to deploy in multiple regions.

Ex: An error occurred while provisioning your stack: LocalesDynamoDbTable - locales-dev already exists.

**Comment by rdehnhardt** [comment] 2017-06-27 16:53
I try use sa-east-1 region! (https://aws.amazon.com/about-aws/global-infrastructure/regional-product-services/)

**Comment by pmuens** [comment] 2017-06-27 18:12
Hey @rdehnhardt thanks for opening 👍 

Could you please share your `serverless.yml` file and the steps you took to deploy so that we can dig into this?

Thanks!

**Comment by pmuens** [comment] 2017-06-27 18:14
Ok. I took another look at your error messages.

This seems to be a duplicate of https://github.com/serverless/serverless/issues/3183.

I'll close this one since we track the progress in #3183. Feel free to chime in over there 👍

**Closed by pmuens** 2017-06-27 18:14 UTC
Labels: kind/bug, status/more-info-needed
