### ISSUE TITLE
SNS events neither create or bind sns

### ISSUE THREAD

**Issue by jayzalowitz** [serverless/serverless#1077] opened 2016-05-09 22:53 UTC
On 5.5 i was trying to move over to events based binding due to issues with that plugin:
https://github.com/martinlindenberg/serverless-plugin-sns/issues/15

Point being i tried to implement binding a logging function to mulitple sns topics:

"events": [
  {
    "name" : "Create",
    "type": "sns",
    "config": {
      "topicName": "create" 
    }
  },
  {
    "name" : "Compile",
    "type": "sns",
    "config": {
      "topicName": "compile" 
    }
  },
  {
    "name" : "retrieve",
    "type": "sns",
    "config": {
      "topicName": "retrieve" 
    }
  },
  {
    "name" : "deploy",
    "type": "sns",
    "config": {
      "topicName": "deploy" 
    }
  }
  ],

After fully deploying everything no binding occured.

This worked with the plugin outside the multiple binding issue.

**Comment by dijitalmunky** [comment] 2016-05-10 20:26
You did a `sls event deploy -a -s <stage>` correct?  Also, did you define your Topics in the `s-resources-cf.json` file?  We encountered both of these issues before.

**Comment by jayzalowitz** [comment] 2016-05-19 21:42
Theres nothing in the docs wrt s-resources-cf.json needing to be edited, this dosen't behave as expected (create if not exists, subscribe if not subscribed (this is what the plugin currently does)) but regardless, it the topics existed and still didn't bind.

**Comment by jayzalowitz** [comment] 2016-05-19 21:42
Also, shouldn't function or endpoint deploy also deploy events associated directly with them?

**Comment by srg-clearlaunch** [comment] 2016-05-26 19:42
Anyone from the serverless team care to comment here?  I'm also unclear of how this is supposed to work and am not seeing any SNS subscriptions on deploy, as @jayzalowitz indicates - the sns plugin worked before (although of late we've seen issue with it not subscribing on the first deploy)

**Comment by alanwill** [comment] 2016-06-21 00:02
Pretty sure this is a legitimate bug as I'm running into it as well. In my case I have 5 functions that need to subscribe to an SNS topic defined in `s-resources-cf.json`. For some odd reason (the bug) only 1 function actually subscribes to it, not the others and they're all configured identically, i.e. identical `s-function.json`.

The reason I know this is a bug is because `sls dash summary` shows that all the functions have the SNS topic subscribed, however looking at the console only 1 actually does.

```
 _______                             __
|   _   .-----.----.--.--.-----.----|  .-----.-----.-----.
|   |___|  -__|   _|  |  |  -__|   _|  |  -__|__ --|__ --|
|____   |_____|__|  \___/|_____|__| |__|_____|_____|_____|
|   |   |             The Serverless Application Framework
|       |                           serverless.com, v0.5.5
`-------'

Serverless: 1 stages ------------------------------
Serverless:     |_ dev (1 regions)
Serverless:         |_ us-east-1

Serverless: 8 functions --------------------------
Serverless:     |_ talr-cla (0 endpoints - 1 events)
Serverless:             |_ talr-cla-request (sns event)
Serverless:     |_ talr-cloudtrail (0 endpoints - 1 events)
Serverless:             |_ talr-dispatch (sns event)
Serverless:     |_ talr-config (0 endpoints - 1 events)
Serverless:             |_ talr-dispatch (sns event)
Serverless:     |_ talr-director (0 endpoints - 1 events)
Serverless:             |_ talr-cla-response (sns event)
Serverless:     |_ talr-entsupport (0 endpoints - 1 events)
Serverless:             |_ talr-dispatch (sns event)
Serverless:     |_ talr-iam (0 endpoints - 1 events)
Serverless:             |_ talr-dispatch (sns event)
Serverless:     |_ talr-receptionist (0 endpoints - 0 events)
Serverless:     |_ talr-vpc (0 endpoints - 1 events)
Serverless:             |_ talr-dispatch (sns event)

Serverless: SUMMARY -------------------------------
Serverless: stages     : 1
Serverless: regions    : 1
Serverless: functions  : 8
Serverless: endpoints  : 0
Serverless: events     : 7
```

See how `talr-dispatch` the SNS topic is called out as being subscribed by all those functions? Well look what happens when I run `sls event deploy talr-dispatch --debug`

```
...truncated for brevety
Serverless: Deploying events in "dev" to the following regions: us-east-1
Serverless: \   serverless:lib.node_modules.serverless.lib.actions.EventLambdaSNS Removed lambda permission with statement ID: sEvents-talr-cloudtrail-talr-dispatch-dev +526ms
  serverless:lib.node_modules.serverless.lib.actions.EventLambdaSNS Adding lambda permission with statement ID: sEvents-talr-cloudtrail-talr-dispatch-dev +2ms
Serverless: |   serverless:lib.node_modules.serverless.lib.actions.EventLambdaSNS Subscription to SNS topic arn:aws:sns:us-east-1:xxxxxxxxxxxxx:talr-dispatch added for lambda arn:aws:lambda:us-east-1:xxxxxxxxxxxxx:function:talr-cloudtrail:dev +1s
Serverless: Successfully deployed events in "dev" to the following regions:
Serverless: us-east-1 ------------------------
Serverless:   talr-dispatch (sns event)
```

...and sure enough from the AWS Management Console only the talr-cloudtrail function is subscribed but none of the others. 

Lastly the `s-function.json` file's event clause is identical in all the functions:

```
  "events": [
      {
          "name" : "talr-dispatch",
          "type": "sns",
          "config": {
            "topicName": "${sNSTopicNameTalrDispatch}"
          }
      }
  ],
```

Of course, I can manually subscribe the functions and that works but it would be nice if this all worked from sls as intended. Let me know if you need anymore info to help troubleshoot.

**Comment by eahefnawy** [comment] 2016-06-21 18:23
Eslam from the Serverless team here...

First off, really sorry for being away all that time. We're incredibly busy in V1 and we haven't been paying much attention github notifications/issues :/

@alanwill I think you can only subscribe a single function to an SNS topic. Which would explain that only a single function is subscribed. (probably the last one that was deployed). They simply overwrite each other in order.

However you can subscribe a single function to multiple topics as @jayzalowitz is trying to do. Not sure why it's not working for him though. @jayzalowitz could you run in debug mode and show us the output. Also, please note that the function that will subscribe is the **function with the stage alias**, because you're deploying to that stage. So maybe the stage function is subscribed after all but AWS console is a bit confusing?

Hope this helps. Again we're really sorry, and we're determined to make v1 offer better UX :)

**Comment by alanwill** [comment] 2016-06-21 22:08
@eahefnawy to be clear, that's a limitation of serverless and not AWS because I can do it "manually", i.e. a multiple functions can indeed be subscribed to a single topic. 

Is that what you meant? If so, any idea when it would be fixed in Serverless because in it's current state it's confusing since `sls dash summary` clearly shows that the functions are subscribed to the topic, it's just not the case in reality.

**Comment by connaryscott** [comment] 2016-07-20 15:05
It appears that if an sns topic already has a lambda subscriber endpoint, the following execution:

```
(env) C02PQ6FEG3QD:service-catalog-interface chscott$ (cd v1/actions/compile/ && sls event deploy --stage ${STAGE} --region ${REGION}) 

Serverless: Deploying events in "dev" to the following regions: us-east-1  
````

may do nothing because it is trying to add another endpoint to this sns topic?  --debug does not seem to add anything interesting to this.   I would like the ability to have an sns topic to have more than one endpoint subscription w/o using the console or some other out of band process.

**Comment by alanwill** [comment] 2016-07-20 21:13
@connaryscott agreed, that's exactly what I'm seeing.

**Comment by flomotlik** [comment] 2016-08-05 09:04
We now have SNS support in V1, this should resolve this issue: https://github.com/serverless/serverless/blob/master/docs/guide/overview-of-event-sources.md#sns

**Closed by flomotlik** 2016-08-05 09:04 UTC

**Comment by contractorwolf** [comment] 2016-10-02 03:19
@flomotlik that link 404's for me

**Comment by andymac4182** [comment] 2016-10-03 09:21
https://serverless.com/framework/docs/providers/aws/events/sns/
