### ISSUE TITLE
Support packaging a single artefact for deploy to all environments

### ISSUE THREAD

**Issue by clarenceb** [serverless/serverless#3925] opened 2017-07-11 00:48 UTC
# This is a Feature Proposal

## Description

I want to build a package once (`serverless package -p <output_dir>`) and use that in my CD pipeline across all environments (i.e. promote the artefact once it passes my tests).

It seems that packages are tied to a specific stage/environment (see `cloudformation-template-update-stack.json` in `<output_dir>`); the default being `dev`.

It is good practice to build artefacts once in the CI commit stage and then deploy the same tested artefact into each subsequent environment.  Here, I am assuming stage == environment.

## Why?

If I repackage the artefact for each stage there is a chance I might bundle something different.  Granted the chances of this may be small -- for example, if I record the git hash used and checkout the same source version.   Also, `npm install` may pick up newer packages unless a `.lock` file mechanism is in place (e.g. using `yarn`).

## Possible Implementation

It seems like this shouldn't be too hard to implement since the stage is hardcoded only in the `cloudformation-template-update-stack.json` as far as I can tell.  If the template is changed to take a stage parameter then the artefact could be generic and used for all stages.  The `serverless deploy --stage=<stage_name> --package <package_dir>` command could then pass the stage through to the cloud formation template.

Would this work?  Is this a bad idea?  Am I missing something obvious?

**Comment by HyperBrain** [comment] 2017-07-11 08:22
This is a known problem.

Having the stage as template parameter would be a beginning. But the stage is only one of many things that are currently fixed in the templates at build time. Another big thing are the function environment variables and any custom Serverless variables, that are declared per stage in the serverless.yml and used to configure resources located in the resource section on a stage base.

E.g. you can define a DynamoDB table in your resources and use `${self:custom.${self:custom.stage}.readProvisioning}` to define the used provisioning per stage, by setting the `custom.{stage}.readProvisioning` for all stages. This is very flexible and can be used by the user in infinite ways.

For that reason the problem is not trivial and the solution is not trivial too.

@pmuens I think this is a duplicate of #3528

**Comment by pmuens** [comment] 2017-07-15 15:23
Thanks for opening @clarenceb and thanks for the in-depth explanation @HyperBrain 👍 

Yes, I think you're right. This looks like a duplicate of #3528.

I'll close this since we're discussing potential implementation details over there.

**Closed by pmuens** 2017-07-15 15:23 UTC
Labels: kind/feature, status/help-wanted
