### ISSUE TITLE
Bug with verbose flag v1.75

### ISSUE THREAD

**Issue by BrentonWatt** [serverless/serverless#7944] opened 2020-07-15 16:25 UTC
When trying to deploy projects to AWS on version 1.75.0 if your deploy command has the verbose flag then serverless doesn't deploy but instead just prints the version of serverless installed on the host machine.

<details>
<summary><b><code>serverless deploy --stage test -v</code> output</b></summary>

```
Framework Core: 1.75.0
Plugin: 3.6.16
SDK: 2.3.1
Components: 2.32.0
```

</details>

<b>Installed version</b>

```
Framework Core: 1.75.0
Plugin: 3.6.16
SDK: 2.3.1
Components: 2.32.0
```

**Comment by jameswoodley** [comment] 2020-07-15 16:32
I'm also seeing this, just spent the best part of 2 hours wondering why my CI/CD is all of a sudden not working. VERY frustrating, where's the quality control?  😄

**Comment by troybESM** [comment] 2020-07-15 16:33
Same here. Good to know that it is just the -v flag

**Comment by rmykh** [comment] 2020-07-15 17:39
> Installed version

At least it immediately gave you version info to provide in the issue :)

**Comment by liram-vardi** [comment] 2020-07-15 18:03
Same issue on my side!

**Comment by daddyman** [comment] 2020-07-15 19:54
This also caused me a couple of hours of time. Looks to be broken in #7924.

I reverted to 1.74.1 to workaround the problem. Too many projects to change them all to --verbose.

**Comment by msanmartin-cloudhesive** [comment] 2020-07-15 21:35
Thanks, this post saved my work day from being completely lost

**Comment by chrisplyn** [comment] 2020-07-16 01:12
I had similar with my CI/CD pipeline

```
$ sls deploy -v
Framework Core: 1.75.0
Plugin: `3.6.16`
SDK: 2.3.1
Components: 2.32.0
The command "sls deploy -v" exited with 0.
```

My pipeline exited with 0 but nothing is deployed.

**Comment by GavL89** [comment] 2020-07-16 06:33
I also have a similar issue with 20+ pipelines.  Hopefully the fix can be released soon!

**Comment by medikoo** [comment] 2020-07-16 06:56
Great thanks for reporting. Fix will be released in few hours. 

Bug is that `--version` was configured to be a global command (regression introduced with https://github.com/serverless/serverless/pull/7924), and due to that `-v` shortcut shadowed `-v` shortcut for `--verbose`. Workaround for a meantime is to rely on `--verbose` instead of `-v`

Anyway `--version` and `-v` as its alias should be recognized only when used on top level command, that'll be fixed shortly

**Comment by tomaszdudek7** [comment] 2020-07-16 07:17
Connected to https://github.com/serverless/serverless/issues/7948

**Closed** 2020-07-16 08:24 UTC
Labels: bug, cat/cli
