### ISSUE TITLE
Request is missing Authentication Token

### ISSUE THREAD

**Issue by sathishkumar16** [serverless/serverless#11560] opened 2022-11-28 10:11 UTC
### Are you certain it's a bug?

- [X] Yes, it looks like a bug

### Is the issue caused by a plugin?

- [X] It is not a plugin issue

### Are you using the latest v3 release?

- [X] Yes, I'm using the latest v3 release

### Is there an existing issue for this?

- [X] I have searched existing issues, it hasn't been reported yet

### Issue description

When we try to deploy using serverless we are getting the below error and also there is no stack trace to identify the issue.

Serverless AWS authentication and Build were also successful. Everything was working fine until today morning after that it is not working but there has been no code change from our end.

Run cd admin && sls deploy --region eu-west-2 --stage dev --verbose

Deploying admin to stage dev (eu-west-2)

× Stack daive-admin-dev failed to deploy (0s)
Environment: linux, node 1[4](https://github.com/daivebot/daivebot_api/actions/runs/3563667976/jobs/5986727899#step:7:5).21.1, framework 3.2[5](https://github.com/daivebot/daivebot_api/actions/runs/3563667976/jobs/5986727899#step:7:6).0, plugin [6](https://github.com/daivebot/daivebot_api/actions/runs/3563667976/jobs/5986727899#step:7:7).2.2, SDK 4.3.2
Credentials: Local, "default" profile
Docs:        docs.serverless.com
Support:     forum.serverless.com
Bugs:        github.com/serverless/serverless/issues

Error:
Request is missing Authentication Token

2 deprecations found: run 'serverless doctor' for more details
Error: Process completed with exit code 1.

### Service configuration (serverless.yml) content

```yaml
N/A
```

### Command name and used flags

sls deploy --region eu-west-2 --stage dev --verbose

### Command output

```shell
Run cd admin && sls deploy --region eu-west-2 --stage dev --verbose

Deploying admin to stage dev (eu-west-2)

× Stack daive-admin-dev failed to deploy (0s)
Environment: linux, node 1[4](https://github.com/daivebot/daivebot_api/actions/runs/3563667976/jobs/5986727899#step:7:5).21.1, framework 3.2[5](https://github.com/daivebot/daivebot_api/actions/runs/3563667976/jobs/5986727899#step:7:6).0, plugin [6](https://github.com/daivebot/daivebot_api/actions/runs/3563667976/jobs/5986727899#step:7:7).2.2, SDK 4.3.2
Credentials: Local, "default" profile
Docs:        docs.serverless.com
Support:     forum.serverless.com
Bugs:        github.com/serverless/serverless/issues

Error:
Request is missing Authentication Token

2 deprecations found: run 'serverless doctor' for more details
Error: Process completed with exit code 1.
```

### Environment information

```shell
3.25.0
```

**Comment by medikoo** [comment] 2022-11-28 16:30
Duplicate of #11561

**Closed by medikoo** 2022-11-28 16:30 UTC
