### ISSUE TITLE
Support for the new HTTP API Gateway

### ISSUE THREAD

**Issue by casertap** [serverless/serverless#7097] opened 2019-12-16 03:02 UTC
# Feature Proposal
I think we should be able to choose between REST API mode or the new HTTP API mode.

## Description

The link the the new aws feature is here: https://aws.amazon.com/blogs/compute/announcing-http-apis-for-amazon-api-gateway/

1. What is the use case that should be solved. 
If I understand well the HTTP api will be faster because it will have less integrations.

Thanks

**Comment by waynerobinson** [comment] 2019-12-16 05:37
I think this is a duplicate of #7052

**Comment by medikoo** [comment] 2019-12-16 10:11
Duplicate of #7052

**Closed by medikoo** 2019-12-16 10:11 UTC
Labels: duplicate
