### ISSUE TITLE
Invoke local for Python can not run handler in subpackage

### ISSUE THREAD

**Issue by herophuong** [serverless/serverless#4663] opened 2018-01-18 08:47 UTC
# This is a Bug Report

## Description

* What went wrong?

    When I put my python handler function in a subpackage, `invoke local` can not run it.

* What did you expect should have happened?

    `invoke local` should be able to run it, the same as on AWS.

* What was the config you used?

```yaml
functions:
  events-sqs-queuehandler:
    handler: events.sqs.queuehandler.handler
```

## Additional Data

* ***Serverless Framework Version you're using***: 1.25.0
* ***Operating System***: Docker
* ***Stack Trace***:
```
Traceback (most recent call last):
  File "/usr/lib/node_modules/serverless/lib/plugins/aws/invokeLocal/invoke.py", line 61, in <module>
    handler = getattr(module, args.handler_name)
AttributeError: module 'events' has no attribute 'sqs'
```

**Comment by dfee** [comment] 2018-02-17 00:04
I just ran into this, too. Is there a work-around – I'm struggling to think of one without re-inventing a huge swath of `invoke local` functionality.

**Comment by dfee** [comment] 2018-02-17 00:21
FWIW, this is definitely a bug, but solvable through a crude method that looks like the following:

```yaml
# serverless.yaml
functions:
  task_runner:
    handler: invoke-proxy.invoke
    # handler: xyz.scripts.task.entrypoint
```

```python
# /invoke-proxy.py
from xyz.scripts.task import entrypoint
```

**Comment by dfee** [comment] 2018-02-17 00:34
@eahefnawy @hyperbrain sorry to randomly ping you, but it looks like the `invoke` command has largely / recently been maintained by you guys.

Unfortunately, I'm not that great with debugging nodejs scripts – but this seems pretty clear cut as a bug, and fairly core functionality. Can we get this triaged / tagged / etc? Thanks!

**Comment by HyperBrain** [comment] 2018-02-17 11:08
Hi @dfee , thanks for the ping 😄 

I think you're right that this is a bug. Maybe someone who frequently uses Python based Lambdas can have a deeper look and fix it.

**Comment by dfee** [comment] 2018-02-19 18:53
The problem seems to be on the parent process side of the fence – by the time we're in Python, as a forked subprocess, something is wrong with the environment. I'm not clear on where `serverless` is launching the subprocess, so I'm stuck in helping to debug. Can you point out where the subproc is launched?

**Comment by HyperBrain** [comment] 2018-02-20 10:18
On invoke local, the process is spawned in `invokeLocalPython()` here:
https://github.com/serverless/serverless/blob/master/lib/plugins/aws/invokeLocal/index.js#L159

and `invoke.py` is executed. Hope this helps 😄

**Comment by dfee** [comment] 2018-02-20 20:20
Alright – here's the solution, revising [this](https://github.com/serverless/serverless/blob/master/lib/plugins/aws/invokeLocal/index.js#L132)

```javascript
    if (runtime === 'python2.7' || runtime === 'python3.6') {
      const handlerComponents = handler.split(/[.]+/);
      const handlerPath = handlerComponents.slice(0, -1).join('.');  // a.k.a. the "module"
      const handlerName = handlerComponents.pop();  // the module's attribute, a callable
      return this.invokeLocalPython(
        process.platform === 'win32' ? 'python.exe' : runtime,
        handlerPath,
        handlerName,
        this.options.data,
        this.options.context);
    }
```

The problem is that `xyz.scripts.task.entrypoint` is currently getting converted into `handlerPath = 'xyz';` and `handlerName = 'scripts'`, but we actually want `handlerPath = 'xyz.scripts.task'` and `handlerName = 'entrypoint'`.

**Comment by dfee** [comment] 2018-02-21 00:52
@HyperBrain submitted a PR. Might need some assistance getting it merged :)

**Closed** 2018-02-21 17:59 UTC
Labels: help wanted, kind/bug
