### ISSUE TITLE
VPC attachment not working on initial deployment "Your access has been denied by EC2"

### ISSUE THREAD

**Issue by alekstr** [serverless/serverless#2064] opened 2016-09-08 08:14 UTC
# This is a Bug Report

## Description

If you are attaching VPC for a function and initially deploying function - you'll get "Your access has been denied by EC2" with resource creation failed for Lambda function. This is due to Lambda need to have role assigned prior configuring VPC, however in Cloudformation template lambda function does not depend on Role resource - so in some cases role creation is not completed before lambda creation which leads to a failure.

serverless.yml config file:
```
service: test # NOTE: update this with your service name

provider:
    name: aws
    runtime: nodejs4.3
    iamRoleStatements:
        $ref: ../config/iamRolesDefinition.json

defaults:
    stage: dev
    region: eu-west-1

package:
    include:
        - ./lib
        - ./node_modules
        - ./config
functions:
    auth:
        handler: handler.main
        timeout: 120
        events:
            - http:
                path: das/auth
                method: post
                cors: true
        vpc:
            securityGroupIds:
                - sg-g1
            subnetIds:
                - subnet-1
                - subnet-2
```
iamRolesDefinition.json
```
[
    {
      "Effect": "Allow",
      "Action": [
        "logs:CreateLogGroup",
        "logs:CreateLogStream",
        "logs:PutLogEvents",
        "ec2:DescribeInstances",
        "ec2:CreateNetworkInterface",
        "ec2:DescribeNetworkInterfaces",
        "ec2:DeleteNetworkInterface"
      ],
      "Resource": "*"
    },
    {
      "Effect": "Allow",
      "Action": [
        "dynamodb:*"
      ],
      "Resource": [
        "*"
      ]
    }
]
```
## How to reproduce

- Remove stack if exists (sls remove);
- Add VPC configuration int serverless.yml;
- Deploy function.

## Additional Data

* ***Serverless Framework Version you're using***: 1.0.0-beta.2
* ***Operating System***: Red Hat Enterprise Linux Server release 6.7 (Santiago)

To fix issue - I've added "DependsOn" parameter into Function configuration:
aws/deploy/compile/functions/index.js after the line 79:
`
"DependsOn": "IamPolicyLambda",
`
This will require Lambda function to wait till Policy is created.

**Comment by fruffin** [comment] 2016-09-08 09:40
I think this is a duplicate of https://github.com/serverless/serverless/issues/2055 and https://github.com/serverless/serverless/issues/1981

I've had the exact same problem.

I raised an issue here: https://github.com/serverless/serverless/issues/1981 and there is an open PR to fix it here: https://github.com/serverless/serverless/pull/1934

There is a workaround in the comments, which consists in creating the security group required for the VPC integration as a custom resource and making it depend on the IAM policy creation

**Comment by alekstr** [comment] 2016-09-08 10:06
Cool thanks =)

**Comment by mthenw** [comment] 2016-10-28 07:55
Duplicate of https://github.com/serverless/serverless/issues/1981. Closing.

**Closed by mthenw** 2016-10-28 07:55 UTC
