### ISSUE TITLE
project create is failing in non interactive mode using git-bash.exe

### ISSUE THREAD

**Issue by joelnet** [serverless/serverless#778] opened 2016-03-13 00:01 UTC
I'm following the directions on this page http://docs.serverless.com/docs/installing-serverless and I am receiving the error message: **ServerlessError: You must specify all necessary options when in a non-interactive mode.**

UPDATE: this issue seems to be limited to the shell git-bash.exe. There are no issues from within cmd.exe. 

UPDATE 2: Other commands also fail. I created a component and function which did not fail, but did not create correctly. These would not deploy and I had delete and re-create them under cmd.exe.

version: 0.4.2
os: windows 7
shell: git-bash.exe v2.5.0

logs:

```
Serverless: Initializing Serverless Project...
Serverless: Enter a name for this project:  (serverless-nkxvi5) serverless-freexboxloot
Serverless: Enter a universally unique project bucket name:  (serverless-nkxvi5) serverless-freexboxloot
Serverless: Enter an email to use for AWS alarms:  (me@serverless-nkxvi5.com) email@address-here.com
Serverless: Enter the ACCESS KEY ID for your Admin AWS IAM User:  <ACCESS_KEY_ID>
Serverless: Enter the SECRET ACCESS KEY for your Admin AWS IAM User:  <SECRET>
C:\Users\My User\AppData\Roaming\npm\node_modules\serverless\node_modules\bluebird\js\release\async.js:49
        fn = function () { throw arg; };
                           ^

ServerlessError: You must specify all necessary options when in a non-interactive mode.
    at new ServerlessError (C:\Users\My User\AppData\Roaming\npm\node_modules\serverless\lib\ServerlessError.js:17:11)
    at Object.exports.select (C:\Users\My User\AppData\Roaming\npm\node_modules\serverless\lib\utils\cli.js:235:11)
    at ProjectInit.cliPromptSelect (C:\Users\My User\AppData\Roaming\npm\node_modules\serverless\lib\ServerlessPlugin.js:106:19)
    at C:\Users\My User\AppData\Roaming\npm\node_modules\serverless\lib\actions\ProjectInit.js:255:26
    at C:\Users\My User\AppData\Roaming\npm\node_modules\serverless\node_modules\prompt\lib\prompt.js:335:32
    at C:\Users\My User\AppData\Roaming\npm\node_modules\serverless\node_modules\prompt\node_modules\utile\node_modules\async\lib\async.js:142:25
    at assembler (C:\Users\My User\AppData\Roaming\npm\node_modules\serverless\node_modules\prompt\lib\prompt.js:332:9)
    at C:\Users\My User\AppData\Roaming\npm\node_modules\serverless\node_modules\prompt\lib\prompt.js:341:32
    at C:\Users\My User\AppData\Roaming\npm\node_modules\serverless\node_modules\prompt\lib\prompt.js:624:5
From previous event:
    at ProjectInit._prompt (C:\Users\My User\AppData\Roaming\npm\node_modules\serverless\lib\actions\ProjectInit.js:234:10)
From previous event:
    at ProjectInit.projectInit (C:\Users\My User\AppData\Roaming\npm\node_modules\serverless\lib\actions\ProjectInit.js:116:10)
From previous event:
    at C:\Users\My User\AppData\Roaming\npm\node_modules\serverless\lib\Serverless.js:181:25
    at Array.reduce (native)
    at Serverless._execute (C:\Users\My User\AppData\Roaming\npm\node_modules\serverless\lib\Serverless.js:180:26)
    at Object.actions.(anonymous function) [as projectInit] (C:\Users\My User\AppData\Roaming\npm\node_modules\serverless\lib\Serverless.js:381:20)
    at ProjectCreate.createProject (C:\Users\My User\AppData\Roaming\npm\node_modules\serverless\lib\actions\ProjectCreate.js:95:29)
From previous event:
    at C:\Users\My User\AppData\Roaming\npm\node_modules\serverless\lib\Serverless.js:156:29
    at Array.reduce (native)
    at C:\Users\My User\AppData\Roaming\npm\node_modules\serverless\lib\Serverless.js:155:30
    at processImmediate [as _immediateCallback] (timers.js:383:17)
From previous event:
    at Serverless._execute (C:\Users\My User\AppData\Roaming\npm\node_modules\serverless\lib\Serverless.js:153:10)
    at Serverless.actions.(anonymous function) (C:\Users\My User\AppData\Roaming\npm\node_modules\serverless\lib\Serverless.js:381:20)
    at Serverless.command (C:\Users\My User\AppData\Roaming\npm\node_modules\serverless\lib\Serverless.js:350:38)
    at Object.<anonymous> (C:\Users\My User\AppData\Roaming\npm\node_modules\serverless\bin\serverless:16:12)
    at Module._compile (module.js:413:34)
    at Object.Module._extensions..js (module.js:422:10)
    at Module.load (module.js:357:32)
    at Function.Module._load (module.js:314:12)
    at Function.Module.runMain (module.js:447:10)
    at startup (node.js:141:18)
    at node.js:933:3
```

**Comment by ac360** [comment] 2016-03-15 07:33
@joelnet Could you try the `v0.5` branch and let me know if this problem persists?

**Comment by joelnet** [comment] 2016-03-16 03:27
@ac360 dumb question, but where can I get v0.5? I installed is per documentation from https://www.npmjs.com/package/serverless. I am also only seeing 0.4.2 as the latest here: https://github.com/serverless/serverless/releases

**Comment by jordanmack** [comment] 2016-03-16 04:19
@joelnet Try this command to install v0.5: `npm install git://github.com/serverless/serverless#v0.5 -g`

**Comment by joelnet** [comment] 2016-03-17 04:31
I am experiencing the same issues with v0.5 using bit-bash.exe.

```
 _______                             __
|   _   .-----.----.--.--.-----.----|  .-----.-----.-----.
|   |___|  -__|   _|  |  |  -__|   _|  |  -__|__ --|__ --|
|____   |_____|__|  \___/|_____|__| |__|_____|_____|_____|
|   |   |             The Serverless Application Framework
|       |                           serverless.com, v0.5.0
`-------'

Serverless: Initializing Serverless Project...
Serverless: Enter a name for this project:  (serverless-nksabq)
C:\Users\Joel Thoms\AppData\Roaming\npm\node_modules\serverless\node_modules\bluebird\js\release\async.js:49
        fn = function () { throw arg; };
                           ^

ServerlessError: You must specify all necessary options when in a non-interactive mode.
    at new ServerlessError (C:\Users\Joel Thoms\AppData\Roaming\npm\node_modules\serverless\lib\Error.js:17:11)
    at Object.exports.select (C:\Users\Joel Thoms\AppData\Roaming\npm\node_modules\serverless\lib\utils\cli.js:235:11)
    at ProjectInit.cliPromptSelect (C:\Users\Joel Thoms\AppData\Roaming\npm\node_modules\serverless\lib\Plugin.js:103:21)
    at C:\Users\Joel Thoms\AppData\Roaming\npm\node_modules\serverless\lib\actions\ProjectInit.js:278:24
From previous event:
    at ProjectInit._createStageAndRegion (C:\Users\Joel Thoms\AppData\Roaming\npm\node_modules\serverless\lib\actions\ProjectInit.js:275:13)
    at C:\Users\Joel Thoms\AppData\Roaming\npm\node_modules\serverless\node_modules\graceful-fs\graceful-fs.js:43:10
    at FSReqWrap.oncomplete (fs.js:82:15)
From previous event:
    at ProjectInit.projectInit (C:\Users\Joel Thoms\AppData\Roaming\npm\node_modules\serverless\lib\actions\ProjectInit.js:90:12)
From previous event:
    at C:\Users\Joel Thoms\AppData\Roaming\npm\node_modules\serverless\lib\Serverless.js:206:25
    at Array.reduce (native)
    at Serverless._execute (C:\Users\Joel Thoms\AppData\Roaming\npm\node_modules\serverless\lib\Serverless.js:205:26)
    at Object.actions.(anonymous function) [as projectInit] (C:\Users\Joel Thoms\AppData\Roaming\npm\node_modules\serverless\lib\Serverless.js:423:20)
    at ProjectCreate.createProject (C:\Users\Joel Thoms\AppData\Roaming\npm\node_modules\serverless\lib\actions\ProjectCreate.js:75:24)
From previous event:
    at C:\Users\Joel Thoms\AppData\Roaming\npm\node_modules\serverless\lib\Serverless.js:181:31
    at Array.reduce (native)
    at C:\Users\Joel Thoms\AppData\Roaming\npm\node_modules\serverless\lib\Serverless.js:180:32
From previous event:
    at Serverless._execute (C:\Users\Joel Thoms\AppData\Roaming\npm\node_modules\serverless\lib\Serverless.js:178:12)
    at Serverless.actions.(anonymous function) (C:\Users\Joel Thoms\AppData\Roaming\npm\node_modules\serverless\lib\Serverless.js:423:20)
    at Serverless.command (C:\Users\Joel Thoms\AppData\Roaming\npm\node_modules\serverless\lib\Serverless.js:392:38)
    at C:\Users\Joel Thoms\AppData\Roaming\npm\node_modules\serverless\bin\serverless:19:16
    at processImmediate [as _immediateCallback] (timers.js:383:17)
From previous event:
    at Object.<anonymous> (C:\Users\Joel Thoms\AppData\Roaming\npm\node_modules\serverless\bin\serverless:18:4)
    at Module._compile (module.js:413:34)
    at Object.Module._extensions..js (module.js:422:10)
    at Module.load (module.js:357:32)
    at Function.Module._load (module.js:314:12)
    at Function.Module.runMain (module.js:447:10)
    at startup (node.js:141:18)
    at node.js:933:3

```

**Comment by jordanmack** [comment] 2016-03-17 06:33
@ac360 I did some research on this using a Windows 10 x64 emulator and the most recent versions of everything. There are a number of compatibility problems:

* Most colors are missing.
* process.stdout.isTTY is undefined.
* process.stdout.setRawMode is undefined.
* process.stdout.moveCursor is undefined.

I stopped testing there. Too much is broken. According to the [MinTTY Documentation](http://mintty.googlecode.com/svn/branches/1.1/docs/mintty.1.html#30):

> Mintty is not a full replacement for the Windows console window that Cygwin uses by default. Like xterm and rxvt, mintty communicates with the child process through a pseudo terminal device, which Cygwin emulates using Windows pipes. This means that native Windows command line programs started in mintty see a pipe rather than a console device. As a consequence, such programs often disable interactive input. Also, direct calls to low-level Win32 console functions will fail. Programs that access the console as a file should be fine though.

**Using the normal Windows console works without issue.**

**Comment by pmuens** [comment] 2016-05-03 12:16
Unfortunately I was not able to reproduce this on my Windows 7 machine (I run Serverless v0.5.5).

Maybe it's just a Windows 10 issue.

/cc @eahefnawy

**Comment by eahefnawy** [comment] 2016-05-03 12:48
yeah me neither :/

**Comment by jordanmack** [comment] 2016-05-03 20:31
I'm still seeing the same results using Git v2.8.2 from https://git-scm.com/downloads. The results are consistent with my March 16 testing, and it still works fine in cmd. 

Windows 10 x64
```
C:\Users\username>ver
Microsoft Windows [Version 10.0.10240]

C:\Users\username>node -v
v5.10.1

$ bash --version
GNU bash, version 4.3.42(5)-release (x86_64-pc-msys)
```

Windows 7 x86
```
C:\Users\username>ver
Microsoft Windows [Version 6.1.7601]

C:\Users\username>node -v
v5.10.1

$ bash --version
GNU bash, version 4.3.42(5)-release (i686-pc-msys)
```

```
$ sls project create
 _______                             __
|   _   .-----.----.--.--.-----.----|  .-----.-----.-----.
|   |___|  -__|   _|  |  |  -__|   _|  |  -__|__ --|__ --|
|____   |_____|__|  \___/|_____|__| |__|_____|_____|_____|
|   |   |             The Serverless Application Framework
|       |                           serverless.com, v0.5.5
`-------'

Serverless: Initializing Serverless Project...
Serverless: Enter a name for this project:  (serverless-sjzrdk)
Serverless: Enter a new stage name for this project:  (dev)
C:\Users\username\AppData\Roaming\nvm\v5.10.1\node_modules\serverless\node_modules\bluebird\js\release\async.js:61
        fn = function () { throw arg; };
                           ^

ServerlessError: You must specify all necessary options when in a non-interactive mode.
```

**Comment by flomotlik** [comment] 2016-05-12 11:37
@jordanmack currently we don't have enough resources to debug/fix this with git-bash. We're looking into better Windows support in the future with an upcoming version and want to make it work there, but it will have to be at a later point. If you could look into it and provide a fix we'd be happy to help with guidance. I'm going to close this issue for now though until we come back to better windows support

**Closed by flomotlik** 2016-05-12 11:37 UTC
Labels: bug: can't reproduce, discussion, priority: medium

**Comment by jordanmack** [comment] 2016-05-12 18:11
@flomotlik No need to convince me, I don't use git-bash. I was only researching the details. Windows 10 will be getting native a native bash shell soon anyway.

**Comment by danpantry** [comment] 2016-08-01 19:09
Some more information about Windows.

The native Ubuntu bash does not function well either: I'm able to get to the "Create New Profile"/"Use Existing Profile". Pressing either up or down arrows to select one of these crashes the prompt.

**Comment by jordanmack** [comment] 2016-08-01 20:12
@danpantry This issue is specifically in regards to git-bash on Windows. Is your problem related to Windows or Ubuntu?

**Comment by danpantry** [comment] 2016-08-02 06:15
@jordanmack I'm able to reproduce this issue with Git Bash on Windows is in this ticket, however a similar-but-different issue occurs in the native Bash supplied by Canonical on Windows in the Windows 10 preview builds (admittedly, they are still preview).

Perhaps this info would be better suited in another issue?

**Comment by jordanmack** [comment] 2016-08-05 00:45
@danpantry You might also want to try out the new Serverless v1.0 beta that just came out since it has a lot of changes from the currently released version. http://blog.serverless.com/serverless-v1-0-beta-release-1/

If the problem still exists, then I would recommend opening a new issue. I'll be working on getting up a test environment with Windows Bash to help verify and test this issue.

**Comment by danpantry** [comment] 2016-08-05 09:20
@jordanmack sure. I'll try out the new build and feedback here if the issue is fixed, else I'll open a new issue. Should be able to get something back to you in around 8 hours.

**Comment by jordanmack** [comment] 2016-08-08 00:18
I was able to get Bash running under Windows 10. You can tell it's still beta, and it's a little quirky, but it works. I was able to use Bash on Windows 10 to create, deploy, and remove, using Serverless v0.5.6. Git Bash still fails with Serverless v0.5.6.

I also tested Serverless v1.0 Beta. This worked fine on Windows 10 command line, Bash on Windows 10, and Git Bash on Windows 10.

```
username@DESKTOP-ORLL4S6:~$ lsb_release -a
No LSB modules are available.
Distributor ID: Ubuntu
Description:    Ubuntu 14.04.5 LTS
Release:        14.04
Codename:       trusty
username@DESKTOP-ORLL4S6:~$ node -v
v4.4.1
username@DESKTOP-ORLL4S6:~$ bash --version
GNU bash, version 4.3.11(1)-release (x86_64-pc-linux-gnu)
Copyright (C) 2013 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>

This is free software; you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.
username@DESKTOP-ORLL4S6:~$ sls --version
0.5.6
```
