### ISSUE TITLE
Serverless:  No file matches include / exclude patterns

### ISSUE THREAD

**Issue by nomanmaqsood** [serverless/serverless#9873] opened 2021-08-23 13:17 UTC
When I add layers in my serverless.yml file I got the following error

```
 
 Serverless Error ----------------------------------------
 
  No file matches include / exclude patterns
```
 
In the layer, I am giving the path of the folder that is available on the root of the folder where serverless.yml is also located. In the folder, it is a pem file only

this is my serverless.yml

```
service: foundation

useDotenv: true

custom:
  pcFoundationStackName: foundation-${self:provider.stage}

provider:
  name: aws
  stackName: ${self:service}-${self:provider.stage}
  region: eu-west-1
  stage: ${opt:stage, 'dev'}
  environment:
    REGION: ${self:provider.region}
    STAGE: ${self:provider.stage}

layers:
  myLayer:
    path: certificates

plugins:
  - serverless-deployment-bucket
  - serverless-pseudo-parameters
  - serverless-plugin-typescript

functions:
  - ${file(./src/hello/function.yml)}

resources:
  - ${file(./resources/outputs.yml)}

```

runtime: Nodejs

version:

    "serverless": "^2.31.0",
    "serverless-plugin-typescript": "^1.1.9",
    "serverless-pseudo-parameters": "^2.5.0",
    "typescript": "^4.2.4"

**Comment by pgrzesik** [comment] 2021-08-23 13:56
Hello @nomanmaqsood :wave: Could you please upgrade to the latest Framework verison? Do you have any chance to share a full reproducible example that I could run on my side?

**Comment by nomanmaqsood** [comment] 2021-08-23 14:58
Hey @pgrzesik I tried doing it with the latest version as well but still get the same problem. 

I am sorry I cannot share the running code

**Comment by pgrzesik** [comment] 2021-08-23 15:04
Hello @nomanmaqsood - it does not have to be your production code - just a small example with some dummy code that I can use to reproduce on my side. Would you be able to provide such an example?

**Comment by nomanmaqsood** [comment] 2021-08-24 07:11
@pgrzesik I tried to debug it and add a console in serverless frameworks. I see the files array is empty. Serverless framework is not able to read the file path

**Comment by pgrzesik** [comment] 2021-08-24 08:42
@nomanmaqsood Thanks for that detail - I would assume that's what is happening, but it's hard to debug if I don't have a reproducible example. Would you be able to provide simple repo on which I could reproduce this issue?

**Comment by alexandrubese** [comment] 2021-09-01 09:36
I also have the same problem:


layers:
  MyCode:
    path: layers/mycode
    name: my-cod-dependencies
    compatibleRuntimes:
      - nodejs14.x

functions:
  my-func:
    handler: handler
    layers:
      - { Ref: MyCodeLambdaLayer }
    events:
      - http:..

Folder structure is:

layers
--- mycode
------ nodejs
---------node_modules
---------package.json


ServerlessError: No file matches include / exclude patterns
      at /usr/local/lib/node_modules/serverless/lib/plugins/package/lib/packageService.js:296:13
      at processTicksAndRejections (internal/process/task_queues.js:95:5)
      at async /usr/local/lib/node_modules/serverless/lib/plugins/package/lib/packageService.js:107:9
      at async Promise.all (index 1)
      at async Package.packageService (/usr/local/lib/node_modules/serverless/lib/plugins/package/lib/packageService.js:111:5)
 
  Get Support --------------------------------------------
     Docs:          docs.serverless.com
     Bugs:          github.com/serverless/serverless/issues
     Issues:        forum.serverless.com
 
  Your Environment Information ---------------------------
     Operating System:          darwin
     Node Version:              14.17.5
     Framework Version:         2.56.0
     Plugin Version:            5.4.4
     SDK Version:               4.3.0
     Components Version:        3.16.0

**Comment by pgrzesik** [comment] 2021-09-01 14:48
Hello @alexandrubese :wave: Thanks for reporting, I've just tried to reproduce with the following example

```
service: layers-repro

provider:
  name: aws
  runtime: nodejs14.x

layers:
  MyCode:
    path: layers/mycode
    name: my-code-dependencies
    compatibleRuntimes:
      - nodejs14.x

functions:
  my-func:
    handler: handler
    layers:
      - { Ref: MyCodeLambdaLayer }
```

and such `layers` dir

```
layers
└── mycode
    └── nodejs
        ├── node_modules
        │   └── lodash.get
        │       ├── index.js
        │       ├── LICENSE
        │       ├── package.json
        │       └── README.md
        ├── package.json
        └── package-lock.json
```

and it was all packaged correctly. Could you please share a minimal reproducible example of your configuration? Ideally in form of a simple github repo that I can try out on my side and see what might be the case

**Comment by alexandrubese** [comment] 2021-09-02 10:14
Hi @pgrzesik 
Sure thing, a test repo can be found here: https://github.com/alexandrubese/test-serverless-repo
I also added a screen-recording in the root path that you can watch.

**Comment by pgrzesik** [comment] 2021-09-03 14:13
Thanks a lot for extremely detailed report @alexandrubese :bow: I've managed to reproduce the problem and after diving deeper into the logic, it seems like the `serverless-typescript-plugin` does not support `layers` at all at the moment. When considering files to be packaged for layer, it always uses the `layer.path` property as prefix/cwd, but output files from typescript compilation are not available/copied there. Here's the logic in the Framework: https://github.com/serverless/serverless/blob/f096440440dfb2339b4fd1ae1ecbca3b59fb4805/lib/plugins/package/lib/packageService.js#L272 where `layer.path` is used as prefix. 

This PR in the plugin https://github.com/serverless/serverless-plugin-typescript/pull/243 solved the problem with support for `patterns`, but unfortunatelly this ticket is still valid: https://github.com/serverless/serverless-plugin-typescript/issues/240 

I'm going to reopen this and let's continue discussion there as it seems like the original issue is also related to that plugin specifically.

cc @medikoo

**Comment by micheleangioni** [comment] 2022-03-31 15:09
Any update here? :)

**Comment by mnapoli** [comment] 2022-03-31 15:35
@micheleangioni https://github.com/serverless/serverless-plugin-typescript/issues/240 still seems to be open.

By the way, we had users from the community recommend using the `esbuild` plugin instead (for TypeScript projects). It might be worth giving it a try to see if it works better?

**Comment by micheleangioni** [comment] 2022-03-31 15:41
Thanks @mnapoli , I didn't know about https://github.com/floydspace/serverless-esbuild :)

However, I generally prefer to use officially supported plugins. In line of principle, Serverless Framework should provide good support for internally-developed plugins.

**Comment by sunrabbit123** [comment] 2022-07-04 23:30
closed https://github.com/serverless/serverless-plugin-typescript/issues/240
but, [mmeyers-xomly](https://github.com/mmeyers-xomly) said `So the above PR fixes part of the issue, but not fully. It seems this only helps if the thing you want to put in a layer is something that would be packaged by this plugin. However, if it's an external file that wouldn't be included in the TS build, this is still broken with the same error.`

we must solved this problem, Because I faced this problem.

**Comment by talesmgodois** [comment] 2023-01-06 19:01
I am facing this issue currently. Have anyone find a solution? Layers with typescript.

**Comment by nicobistolfi** [comment] 2023-02-21 18:54
Same issue here! we're using typescript monorepo and trying to package on of the local dependencies as a layer

**Comment by alexandrubese** [comment] 2023-02-22 13:29
Why is this not prioritised?  

Layers are a critical part for managing npm_modules and other 3rd party requirements our project need without bundling them inside the lambda layers - them not working IS HUGE !

I actually started reconversion of our project to AWS CDK because of this specific issue.

@pgrzesik - please remove the "needs feedback" flag because you have all the feedback needed and also add a "bug" tag so that this issue appears on the first page of the Issues tab.

Someone needs to work on this because as you can see people from with different setups hit this issue without any means of getting over it.

**Comment by medikoo** [comment] 2023-02-22 13:57
@alexandrubese it was the issue in `serverless-plugin-typescript` which was fixed and released: https://github.com/serverless/serverless-plugin-typescript/issues/240

Closing, as it's out of date and not framework specific

**Closed by medikoo** 2023-02-22 13:57 UTC
Labels: needs feedback, cat/layers
