### ISSUE TITLE
Serverless Deploy Error

### ISSUE THREAD

**Issue by keyurbhole** [serverless/serverless#6693] opened 2019-09-16 07:22 UTC
## Description
I am trying to deploy a function on aws lambda but it gives error as below

plugins used are
- serverless-webpack
- serverless-offline

## Error Details
at ReadStream (/home/keyur/Desktop/SN/node-serverless/states/node_modules/graceful-fs/graceful-fs.js:195:28)
      at ReadStream (/home/keyur/Desktop/SN/node-serverless/states/node_modules/graceful-fs/graceful-fs.js:195:28)
      at ReadStream (/home/keyur/Desktop/SN/node-serverless/states/node_modules/graceful-fs/graceful-fs.js:195:28)
      at ReadStream (/home/keyur/Desktop/SN/node-serverless/states/node_modules/graceful-fs/graceful-fs.js:195:28)
      at ReadStream (/home/keyur/Desktop/SN/node-serverless/states/node_modules/graceful-fs/graceful-fs.js:195:28)
      at ReadStream (/home/keyur/Desktop/SN/node-serverless/states/node_modules/graceful-fs/graceful-fs.js:195:28)
      at ReadStream (/home/keyur/Desktop/SN/node-serverless/states/node_modules/graceful-fs/graceful-fs.js:195:28)
      at ReadStream (/home/keyur/Desktop/SN/node-serverless/states/node_modules/graceful-fs/graceful-fs.js:195:28)
      at ReadStream (/home/keyur/Desktop/SN/node-serverless/states/node_modules/graceful-fs/graceful-fs.js:195:28)
      at ReadStream (/home/keyur/Desktop/SN/node-serverless/states/node_modules/graceful-fs/graceful-fs.js:195:28)
      at ReadStream (/home/keyur/Desktop/SN/node-serverless/states/node_modules/graceful-fs/graceful-fs.js:195:28)
      at ReadStream (/home/keyur/Desktop/SN/node-serverless/states/node_modules/graceful-fs/graceful-fs.js:195:28)
      at ReadStream (/home/keyur/Desktop/SN/node-serverless/states/node_modules/graceful-fs/graceful-fs.js:195:28)
      at new ReadStream (/home/keyur/Desktop/SN/node-serverless/states/node_modules/graceful-fs/graceful-fs.js:195:28)
      at Object.createReadStream (/home/keyur/Desktop/SN/node-serverless/states/node_modules/graceful-fs/graceful-fs.js:237:12)
      at copyFile (/home/keyur/Desktop/SN/node-serverless/states/node_modules/fs-extra/lib/copy/ncp.js:98:25)
      at /home/keyur/Desktop/SN/node-serverless/states/node_modules/fs-extra/lib/copy/ncp.js:82:9
      at /home/keyur/Desktop/SN/node-serverless/states/node_modules/fs-extra/lib/copy/ncp.js:208:43
      at callback (/home/keyur/Desktop/SN/node-serverless/states/node_modules/graceful-fs/polyfills.js:289:20)
      at callback (/home/keyur/.nvm/versions/node/v10.16.3/lib/node_modules/serverless/node_modules/graceful-fs/polyfills.js:295:20)
      at FSReqWrap.oncomplete (fs.js:153:21)

**Comment by medikoo** [comment] 2019-09-16 08:17
@keyurbhole thanks for report. Still it's a duplicate of #6667. See top issue description, there's a details on how to solve this issue locally

**Closed by medikoo** 2019-09-16 08:17 UTC
Labels: duplicate
