### ISSUE TITLE
Content of files in package zip created by serverless is empty on MacOS

### ISSUE THREAD

**Issue by zhemaituk** [serverless/serverless#8814] opened 2021-01-24 00:16 UTC
zip archive created by serverless package appears broken. When unarchived - content size of all files is 0.
If deployed to AWS - content of files is deployed empty as well.

macOS BigSur 11.1 (20C69)

Reproducible: for all files included via `package.include`. Reproducible even with standard serveless examples. It used to work fine on the same system previously.
Works fine: for files added by plugins. E.g. when `serverless-python-requirements` is enabled, files added by this plugin appear just fine in the same archive.

<details>
<summary><code>serverless.yml</code></summary>

```yaml
service: serverless-authorizers

provider:
  name: aws
  runtime: nodejs12.x

functions:
  hello:
    handler: handler.hello
```

</details>

<details>
<summary><b><code>SLS_DEBUG=* serverless package</code> output</b></summary>

```
Serverless: To ensure safe major version upgrades ensure "frameworkVersion" setting in service configuration (recommended setup: "frameworkVersion: ^2.20.1")

Serverless: Load command interactiveCli
Serverless: Load command config
Serverless: Load command config:credentials
Serverless: Load command config:tabcompletion
Serverless: Load command config:tabcompletion:install
Serverless: Load command config:tabcompletion:uninstall
Serverless: Load command create
Serverless: Load command install
Serverless: Load command package
Serverless: Load command deploy
Serverless: Load command deploy:function
Serverless: Load command deploy:list
Serverless: Load command deploy:list:functions
Serverless: Load command invoke
Serverless: Load command invoke:local
Serverless: Load command info
Serverless: Load command logs
Serverless: Load command metrics
Serverless: Load command print
Serverless: Load command remove
Serverless: Load command rollback
Serverless: Load command rollback:function
Serverless: Load command slstats
Serverless: Load command plugin
Serverless: Load command plugin
Serverless: Load command plugin:install
Serverless: Load command plugin
Serverless: Load command plugin:uninstall
Serverless: Load command plugin
Serverless: Load command plugin:list
Serverless: Load command plugin
Serverless: Load command plugin:search
Serverless: Load command config
Serverless: Load command config:credentials
Serverless: Load command rollback
Serverless: Load command rollback:function
Serverless: Load command upgrade
Serverless: Load command uninstall
Serverless: Load command login
Serverless: Load command logout
Serverless: Load command generate-event
Serverless: Load command test
Serverless: Load command dashboard
Serverless: Load command output
Serverless: Load command output:get
Serverless: Load command output:list
Serverless: Load command param
Serverless: Load command param:get
Serverless: Load command param:list
Serverless: Load command studio
Serverless: Deprecation warning: Starting with next major version, default value of provider.lambdaHashingVersion will be equal to "20201221"
            More Info: https://www.serverless.com/framework/docs/deprecations/#LAMBDA_HASHING_VERSION_V2
Serverless: Invoke package
Serverless: Invoke aws:common:validate
Serverless: Invoke aws:common:cleanupTempDir
Serverless: Packaging service...
Serverless: Excluding development dependencies...
Serverless: Invoke aws:package:finalize
Serverless: Invoke aws:common:moveArtifactsToPackage
```

</details>

<details>
<summary><b><code>unzip -vl .serverless/serverless-authorizers.zip</b></summary>

```
Archive:  .serverless/serverless-authorizers.zip
 Length   Method    Size  Cmpr    Date    Time   CRC-32   Name
--------  ------  ------- ---- ---------- ----- --------  ----
       0  Defl:N      256   0% 01-01-1980 00:00 00000000  handler.js
--------          -------  ---                            -------
       0              256   0%                            1 file
```

Notice **Length**,Cmpr,Date,Time,CRC-32 especially, for a valid archive it typically looks like this:
```
     442  Defl:N      254  43% 01-23-2021 18:43 c3f8b799  handler.js
```

</details>

<b>Installed version</b>

```
Framework Core: 2.20.1
Plugin: 4.4.2
SDK: 2.3.2
Components: 3.5.1
```

**Comment by jkeam** [comment] 2021-01-24 02:27
It looks like it has a "size" (256 as opposed to 0).  Just curious, what version of node are you using?  I know I've had trouble with node `v15.6.0` but success with `v15.5.1`.

**Comment by pgrzesik** [comment] 2021-01-24 14:00
Hello @zhemaituk, thanks for reporting, it's a duplicate of an issue that we're already tracking here: https://github.com/serverless/serverless/issues/8772

**Closed** 2021-01-24 14:00 UTC
Labels: duplicate
