### ISSUE TITLE
documentation property produces an unrecognized property error

### ISSUE THREAD

**Issue by hernanc** [serverless/serverless#9733] opened 2021-07-12 14:49 UTC
Hi there,

I have a function defined like this:

```functions:
  index:
    name: index
    handler: serverless.handler
    events:
      - http:
          method: get
          path: /
          documentation: ${file(docs/endpoints/index.doc.yml)}
          cors: true
```

**Current behavior**
Serverless 2.50.0 produces the following error:
```
Serverless Error ----------------------------------------

  Configuration error:
       at 'functions.index.events[0].http': unrecognized property 'documentation'

Get Support --------------------------------------------
     Docs:          docs.serverless.com
     Bugs:          github.com/serverless/serverless/issues
     Issues:        forum.serverless.com

  Your Environment Information ---------------------------
     Operating System:          darwin
     Node Version:              12.22.3
     Framework Version:         2.50.0 (local)
     Plugin Version:            5.4.3
     SDK Version:               4.2.3
     Components Version:        3.13.2
```

**Expected behavior:**

Serverless understands that property and runs normally like v1 does.

**Comment by pgrzesik** [comment] 2021-07-12 14:54
Hello @hernanc - could you please share a full reproducible example? Are you using any plugins? Framework natively does not support such property for that event

**Comment by medikoo** [comment] 2021-07-14 09:53
Closing as duplicate of https://github.com/deliveryhero/serverless-aws-documentation/issues/166

Note, it's likely that we will address this in 1-2 months time on plugin side. Please follow mentioned issue for progress

**Closed by medikoo** 2021-07-14 09:53 UTC
Labels: bug/external, cat/plugin
