### ISSUE TITLE
Serverless fails to deploy service with a kinesis stream event: Unresolved resource dependencies [IamPolicyLambdaExecution] in the Resources block of the template

### ISSUE THREAD

**Issue by aashish004** [serverless/serverless#3142] opened 2017-01-26 03:43 UTC
# This is a Bug Report

## Description

We were trying to deploy service that would read from a Kinesis stream and the deployment failed with the following message:

`Template format error: Unresolved resource dependencies
     [IamPolicyLambdaExecution] in the Resources block of
     the template`

I am including my serverless.yml for reference:

```
provider:
  name: aws
  runtime: python2.7
  region: ap-southeast-1
  role: testKinesisStream

functions:
  hello:
    handler: handler.hello
    events:
      - 
        stream:
          arn: "arn:aws:kinesis:ap-southeast-1:XXXXXXXXXXX:stream/StreamTest"
          batchSize: 100
          startingPosition: LATEST
          enabled: false

resources:
  Resources:
    testKinesisStream:
      Type: AWS::IAM::Role
      Properties:
        RoleName: test-kinesis-stream-dev-role
        AssumeRolePolicyDocument:
          Version: '2012-10-17'
          Statement:
            - Effect: "Allow"
              Principal:
                Service:
                  - "lambda.amazonaws.com"
              Action: "sts:AssumeRole"
        Policies:
          - PolicyName: test-kinesis-stream-dev-policy
            PolicyDocument:
              Version: '2012-10-17'
              Statement:
                - Effect: "Allow"
                  Action:
                    - "kinesis:DescribeStream"
                    - "kinesis:GetShardIterator"
                    - "kinesis:GetRecords"
                    - "kinesis:ListStreams"
                  Resource: "arn:aws:kinesis:ap-southeast-1:XXXXXXXXXXX:stream/StreamTest"
```

## Additional Data

* ***Serverless Framework Version you're using***: 1.4.0
* ***Operating System***: darwin
* ***Provider Error messages***: `Template format error: Unresolved resource dependencies
     [IamPolicyLambdaExecution] in the Resources block of
     the template`

**Comment by pmuens** [comment] 2017-01-26 08:32
Hey @aashish004 thanks for reporting.

We're currently working on fixes for the stream support in those PRs here:

- https://github.com/serverless/serverless/pull/3111
- https://github.com/serverless/serverless/pull/3083
- https://github.com/serverless/serverless/pull/3141

Those will be merged the upcoming days (hopefully) 👍  They should resolve the problem you're currently facing

**Comment by aashish004** [comment] 2017-03-23 07:18
Is this going to be resolved anytime soon?

**Comment by pmuens** [comment] 2017-03-23 08:16
@aashish004 thanks for getting back. Could you please try that again with the new Serverless version?

We've pushed some fixes in the last couple of weeks regarding those kind of issues...

**Comment by driedelreply** [comment] 2017-03-28 08:20
Still got the same problem using the following setup: 
```
Your Environment Information -----------------------------

OS:                 darwin

Node Version:       4.3.2

Serverless Version: 1.9.0
```

**Comment by piohhmy** [comment] 2017-04-11 23:35
I'm also seeing this issue.  Looking into it I can see DependsOn is not being filled out correctly in the compiled CF for a particular case when a custom role defined.

 OK if I submit a PR for a proposed fix?

**Comment by pmuens** [comment] 2017-04-12 11:35
@piohhmy sounds good! Thanks for the PR 👍 . We'll review it ASAP.

**Comment by pmuens** [comment] 2017-04-13 08:47
Was able to reproduce 👍 it locally.

**Closed** 2017-04-13 08:50 UTC
Labels: kind/bug, status/more-info-needed

**Comment by aashish004** [comment] 2017-04-20 10:01
I am still getting error for stream type of integration for serverless version 1.11.0

The error:
```
Template format error: Unresolved resource dependencies [IamRoleLambdaExecution] in the Resources block of the template


Your Environment Information ----------------------------- OS: linux Node Version: 6.10.2 Serverless Version: 1.11.0
```

serverless.yml
```

service: user-activity

provider:
  name: aws
  runtime: nodejs4.3
  role: roleName
  timeout: 300
  region: ${opt:region}
  memorySize: 512
  vpc:
    securityGroupIds:
      - ${opt:securityGroupId}
    subnetIds:
      - ${opt:subnetId1}
      - ${opt:subnetId2}

functions:
  userActivitySync:
    handler: handler.userActivitySync
    events:
      - stream:
          arn: ${env:STREAM_ARN}
          batchSize: 50
          startingPosition: LATEST
          enabled: true
resources:
  Resources:
    roleName:
      Type: AWS::IAM::Role
      Properties:
        RoleName: xxxx-role-name
        AssumeRolePolicyDocument:
          Version: '2012-10-17'
          Statement:
            - Effect: "Allow"
              Principal:
                Service:
                  - "lambda.amazonaws.com"
              Action: "sts:AssumeRole"
        Policies:
          - PolicyName: xxxxx-policy-name
            PolicyDocument:
              Version: '2012-10-17'
              Statement:
                - Effect: "Allow"
                  Action:
                    - "logs:CreateLogGroup"
                    - "logs:CreateLogStream"
                    - "logs:PutLogEvents"
                  Resource: "*"
                - Effect: "Allow"
                  Action:
                    - "ec2:CreateNetworkInterface"
                    - "ec2:DescribeNetworkInterfaces"
                    - "ec2:DetachNetworkInterface"
                    - "ec2:AttachNetworkInterface"
                    - "ec2:DeleteNetworkInterface"
                  Resource: "*"
                - Effect: "Allow"
                  Action:
                    - "dynamodb:GetRecords"
                    - "dynamodb:GetShardIterator"
                    - "dynamodb:DescribeStream"
                    - "dynamodb:ListStreams"
                  Resource:
                    - ${env:STREAM_ARN}
```

**Comment by pmuens** [comment] 2017-04-20 10:23
Thanks for getting back @aashish004 

Looks like there's something off with your IAM policy declaration in the `resources` section.

Could you please check you compiled CloudFormation template? What's the value you get for `${env:STREAM_ARN}`?

**Comment by JariL73** [comment] 2017-06-05 10:25
I have the very same issue with Kinesis Firehose. I can't see any issues in compiled Cloudformation template. I have tested it with default and custom IAM role.

 Serverless Error ---------------------------------------

     An error occurred while provisioning your stack: XXXDeliveryStream
     - Encountered unsupported property RoleArn.

  Your Environment Information -----------------------------
     OS:                 darwin
     Node Version:       6.10.2
     Serverless Version: 1.14.0

FirehosetoS3Role:
      Type: AWS::IAM::Role
      Properties:
        RoleName: FirehosetoS3Role
        AssumeRolePolicyDocument:
          Statement:
          - Effect: Allow
            Principal:
              Service:
                #- iot.amazonaws.com
                - firehose.amazonaws.com
            Action:
            - sts:AssumeRole
        Policies:
          - PolicyName: FirehosetoS3Policy 
            PolicyDocument:
              Statement:
                - Effect: Allow
                  Action:
                    - "s3:AbortMultipartUpload"        
                    - "s3:GetBucketLocation"        
                    - "s3:GetObject"        
                    - "s3:ListBucket"        
                    - "s3:ListBucketMultipartUploads"        
                    - "s3:PutObject"
                  Resource: "*"

    XXXDeliveryStream:
      Type: "AWS::KinesisFirehose::DeliveryStream"
      Properties: 
        DeliveryStreamName: XXXDeliveryStream-${{self:provider.stage}}
        S3DestinationConfiguration:
          BucketARN: 
            Fn::Join:
            - ''
            - - 'arn:aws:s3:::'
              - XXX-datalake-${{self:provider.stage}}"
          BufferingHints: 
            IntervalInSeconds: "60"
            SizeInMBs: "50"
          CompressionFormat: "UNCOMPRESSED"
          Prefix: "raw/"
          RoleArn: { Fn::GetAtt: [ FirehosetoS3Role, Arn ] } 
          #RoleArn:
            #Fn::GetAtt: 
              #- "IamRoleLambdaExecution"
              #- "Arn"
          #CloudWatchLoggingOptions: 
          #  Enabled: true
          #  LogGroupName: "XXXDeliveryStream"
          #  LogStreamName: "s3Backup"
      DependsOn: FirehosetoS3Role

**Comment by pmuens** [comment] 2017-06-05 16:23
@JariL73 it looks like the `RoleArn` property needs to be inside of `ElasticsearchDestinationConfiguration` (see the example at the bottom here: http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-kinesisfirehose-deliverystream.html) and not at the root of the `Properties` config.

That should do the trick...

**Comment by JariL73** [comment] 2017-06-06 05:43
OMG, how blind I am. RoleArn is used anywhere else but still.. thank you a lot!

**Comment by pmuens** [comment] 2017-06-06 06:08
> OMG, how blind I am. RoleArn is used anywhere else but still.. thank you a lot!

Sure thing! Yes, I was also scratching my head about this 😄 Glad to hear that this resolved your problem! 👍

**Comment by aashish004** [comment] 2017-06-06 06:59
The latest version serverless seems to have resolved my problem. Now I am able to use stream integration alongside cloudformation resource definition for lambda IAM role.

Thanks!

**Comment by pmuens** [comment] 2017-06-06 10:33
> The latest version of serverless seems to have resolved my problem. Now I am able to use stream integration alongside cloudformation resource definition for lambda IAM role.

Nice! Thanks for confirming @aashish004 👍
