### ISSUE TITLE
Allow Lambda Authorizer for HTTP API

### ISSUE THREAD

**Issue by jameswoodley-zoopla** [serverless/serverless#8348] opened 2020-10-06 14:06 UTC
Allow the ability to use Lambda Authorizer when using HTTP API as seen in the AWS docs: https://docs.aws.amazon.com/apigateway/latest/developerguide/http-api-lambda-authorizer.html

As per the serverless docs, HTTP API only allows JWT Authorizers in Serverless Framework: https://www.serverless.com/framework/docs/providers/aws/events/http-api#jwt-authorizers

Duplicate Rest API allowing a lambda to be provided

**Comment by medikoo** [comment] 2020-10-06 15:55
Duplicate of https://github.com/serverless/serverless/issues/8210

**Closed by medikoo** 2020-10-06 15:55 UTC
