### ISSUE TITLE
Wrong AWS credentials when using S3 with Serverless

### ISSUE THREAD

**Issue by pmuens** [serverless/serverless#955] opened 2016-04-06 07:33 UTC
I've created a lambda function which should be used to create a `signedUrl` which can then be used to upload a file from the client to the S3 bucket.

However I get an error regarding the authorization because the credentials which are provided through Serverless seems to be "wrong":

```
SignatureDoesNotMatch
The request signature we calculated does not match the signature you provided. Check your key and signing method.
```

Everything works fine If I replace them with the values from my user I've created for the Serverless usage.

Here's my code:
```
// Doesn't work
const S3 = new AWS.S3({ accessKeyId: process.env.AWS_ACCESS_KEY_ID, secretAccessKey: process.env.AWS_SECRET_ACCESS_KEY });

// Also not working:
const S3 = AWS.S3({ sessionToken: process.env.AWS_SESSION_TOKEN })

// working (keys taken from ~/.aws/credentials)
const S3 = AWS.S3({ accessKeyId: "ABC", secretAccessKey: "XYZ" })

S3.getSignedUrl('putObject', params, (err ,data) => { ... }
```

The `AWS_SECRET_ACCESS_KEY` and `AWS_ACCESS_KEY_ID` are different from my credentials I can find at `~/.aws/credentials`.

Do I have to setup special permissions? Am I missing something?

**Comment by pmuens** [comment] 2016-04-06 08:08
May be related to https://github.com/serverless/serverless/issues/459

**Comment by flomotlik** [comment] 2016-05-12 12:30
This looks like the same issue as #459 . Closing for now as it looks like the issue is with using the Lambda IAM integration differently.

**Closed by flomotlik** 2016-05-12 12:30 UTC
Labels: bug: unconfirmed, discussion, priority: high

**Comment by FbPalmabit** [comment] 2017-02-16 11:33
@pmuens i have the same problem. How do you solve it?

thanks

**Comment by pmuens** [comment] 2017-02-16 12:00
@FbPalmabit 

🤔 oh man. That was a long time ago. I'm not sure if I've ever resolved this one...

Have you looked into #495?

**Comment by urielaero** [comment] 2017-10-23 22:33
@FbPalmabit 
I had a similar problem solve it with this:
```
iamRoleStatements:
  - Effect: Allow
    Action:
      - "s3:*"
    Resource:
      - Fn::Join:
      - ''
      - - 'arn:aws:s3:::'
        - Ref: GeneralBucketS3LogicalID
        - "/*"
```
