### ISSUE TITLE
 EPERM: operation not permitted, lstat '...\.serverless\invokeLocal\artifact'

### ISSUE THREAD

**Issue by chanhengseang3** [serverless/serverless#7783] opened 2020-05-27 03:56 UTC
Error occur after execute successfully in the first time. The error points to the path `.serverless\invokeLocal\artifact` as `EPERM: operation not permitted`. Have to wait a period of time so the folder will be deleted automatically. Then can run again.

<details>
<summary><code>serverless.yml</code></summary>

```yaml
service: tenant-maintenance
provider:
  name: aws
  runtime: java11
package:
  artifact: build/distributions/tenant-maintenance.zip
functions:
  hello:
    handler: com.serverless.Handler
```

</details>

<details>
<summary><b><code>REPLACE WITH FULL COMMAND NAME</code> output</b></summary>

```
(node:10768) Warning: Setting the NODE_TLS_REJECT_UNAUTHORIZED environment variable to '0' makes TLS connections and HTTPS requests insecure by disabling certificate verification.

  Error --------------------------------------------------

  Error: EPERM: operation not permitted, lstat 'D:\Work_Space\tenant-maintenance\.serverless\invokeLocal\artifact'
      at Object.lstatSync (fs.js:923:3)
      at Object.fs.lstatSync (pkg/prelude/bootstrap.js:1010:33)
      at Object.lstatSync (C:\snapshot\serverless\node_modules\graceful-fs\polyfills.js:308:16)
      at rimrafSync (C:\snapshot\serverless\node_modules\fs-extra\lib\remove\rimraf.js:237:18)
      at C:\snapshot\serverless\node_modules\fs-extra\lib\remove\rimraf.js:291:39
      at Array.forEach (<anonymous>)
      at rmkidsSync (C:\snapshot\serverless\node_modules\fs-extra\lib\remove\rimraf.js:291:26)
      at rmdirSync (C:\snapshot\serverless\node_modules\fs-extra\lib\remove\rimraf.js:281:7)
      at fixWinEPERMSync (C:\snapshot\serverless\node_modules\fs-extra\lib\remove\rimraf.js:167:5)
      at rimrafSync (C:\snapshot\serverless\node_modules\fs-extra\lib\remove\rimraf.js:260:26)
      at C:\snapshot\serverless\node_modules\fs-extra\lib\remove\rimraf.js:291:39
      at Array.forEach (<anonymous>)
      at rmkidsSync (C:\snapshot\serverless\node_modules\fs-extra\lib\remove\rimraf.js:291:26)
      at rmdirSync (C:\snapshot\serverless\node_modules\fs-extra\lib\remove\rimraf.js:281:7)
      at fixWinEPERMSync (C:\snapshot\serverless\node_modules\fs-extra\lib\remove\rimraf.js:167:5)
      at Object.rimrafSync (C:\snapshot\serverless\node_modules\fs-extra\lib\remove\rimraf.js:260:26)
      at AwsCommon.cleanupTempDir (C:\snapshot\serverless\lib\plugins\aws\common\lib\cleanupTempDir.js:13:13)
      at AwsCommon.tryCatcher (C:\snapshot\serverless\node_modules\bluebird\js\release\util.js:16:23)
      at Promise._settlePromiseFromHandler (C:\snapshot\serverless\node_modules\bluebird\js\release\promise.js:547:31)
      at Promise._settlePromise (C:\snapshot\serverless\node_modules\bluebird\js\release\promise.js:604:18)
      at Promise._settlePromiseCtx (C:\snapshot\serverless\node_modules\bluebird\js\release\promise.js:641:10)
      at _drainQueueStep (C:\snapshot\serverless\node_modules\bluebird\js\release\async.js:97:12)
      at _drainQueue (C:\snapshot\serverless\node_modules\bluebird\js\release\async.js:86:9)
      at Async._drainQueues (C:\snapshot\serverless\node_modules\bluebird\js\release\async.js:102:5)
      at Immediate._onImmediate (C:\snapshot\serverless\node_modules\bluebird\js\release\async.js:15:14)
      at processImmediate (internal/timers.js:456:21)
      at process.topLevelDomainCallback (domain.js:137:15)

     For debugging logs, run again after setting the "SLS_DEBUG=*" environment variable.

  Get Support --------------------------------------------
     Docs:          docs.serverless.com
     Bugs:          github.com/serverless/serverless/issues
     Issues:        forum.serverless.com

  Your Environment Information ---------------------------
     Operating System:          win32
     Node Version:              12.16.1
     Framework Version:         1.71.3 (standalone)
     Plugin Version:            3.6.12
     SDK Version:               2.3.0
     Components Version:        2.30.11
```

</details>

<b>Installed version</b>

```
Framework Core: 1.71.3 (standalone)
Plugin: 3.6.12
SDK: 2.3.0
Components: 2.30.11
```

**Comment by medikoo** [comment] 2020-05-27 07:43
@chanhengseang3 thanks for report. It's a known issue of standalone build we already discuss at https://github.com/serverless/serverless/issues/7407

At this point it's hard to say when fix will be implemented (our resources are limited) but PR with a fix is highly welcome

**Comment by medikoo** [comment] 2020-05-27 07:43
Duplicate of #7407

**Closed by medikoo** 2020-05-27 07:43 UTC
