### ISSUE TITLE
sls never exits after (successful) deploy

### ISSUE THREAD

**Issue by pmuilu** [serverless/serverless#2111] opened 2016-09-13 09:10 UTC
# This is a (Bug Report / Feature Proposal)

## Description

sls deploy never exits, I also tried with --verbose but it prints nothing.

$ sls deploy --verbose --stage prod 
Serverless: Packaging service...
Serverless: Removing old service versions...
Serverless: Uploading CloudFormation file to S3...
Serverless: Uploading service .zip file to S3...
Serverless: Updating Stack...
Serverless: Checking Stack update progress...
... hangs ...

I can see from AWS CloudFormation that the update completed successfully.

## Additional Data

* ***Serverless Framework Version you're using***:
1.0rc1

* ***Operating System***:
Ubuntu

**Comment by flomotlik** [comment] 2016-09-13 18:05
Does your user account have the proper rights to run this?

**Comment by pmuilu** [comment] 2016-09-14 09:39
Good question.

I have following policies defined for CloudFormation:

    {
        "Version": "2012-10-17",
        "Statement": [
            {
                "Effect": "Allow",
                "Action": [
                    "cloudformation:DescribeStacks",
                    "cloudformation:DescribeStackEvents",
                    "cloudformation:DescribeStackResource",
                    "cloudformation:DescribeStackResources",
                    "cloudformation:CreateStack",
                    "cloudformation:UpdateStack",
                    "cloudformation:DeleteStack"
                ],
                "Resource": "*"
            }
        ]
    }

In addition I've also these predefined policies:

 AWSLambdaFullAccess
 IAMFullAccess
 AmazonDynamoDBFullAccess
 AmazonAPIGatewayAdministrator

Thing is that I don't see any errors/failures in CloudFormation logs or in sls output about missing permissions. Updates also work. Any idea how to debug this?

**Comment by flomotlik** [comment] 2016-09-15 13:00
If its reproducible could you try running it with Full admin account credentials, just to see if its something to do with the credentials, or if there is another problem.

If that resolves it then there is probably some IAM credentials limitation issue here, I don't see S3 access for example?

**Comment by pmuilu** [comment] 2016-09-16 17:57
Apparently my dev machine clock was minute or two ahead, synced from ntp and it works now.

**Comment by flomotlik** [comment] 2016-09-17 07:05
ok, thats a nasty bug that we need to look into. Thanks for reporting.

**Comment by rowanu** [comment] 2016-09-18 06:59
Hmm, might not be much that can be done about this. The AWS API *does not* like it when the clocks (i.e. local vs API time) are out by more than a few minutes.

It might even be worth prompting the user to check their clocks under certain scenarios; The built in error message is not helpful in its wording, but it's a relatively common issue.

**Comment by eahefnawy** [comment] 2016-09-22 08:20
@pmuilu @flomotlik I've had this issue lots of times with AWS pre JAWS/Serverless days, and it was because I keep getting out of sync with the ntp servers (maybe due to traveling/change in time zone).

Fixing is super easy though, just sync with ntp

**Comment by sweplatte** [comment] 2016-10-05 10:55
I can confirm this bug. Had the same problem but after syncing the clock it is working.

**Comment by rowanu** [comment] 2016-10-05 22:02
Just to be clear, if it starts working after you sync your clock **it is not a Serverless bug** - the AWS API/SDKs sign all their requests, and AWS will reject them if they're too far out of sync in either direction. There is nothing that can be done directly about this, as it is a security feature  (e.g. would you accept an API request from the future?).

**Comment by mthenw** [comment] 2016-10-28 15:47
Closing as it's not Serverless bug. cc @flomotlik

**Closed by mthenw** 2016-10-28 15:47 UTC
Labels: bug

**Comment by benoahriz** [comment] 2016-11-18 00:54
Ran into this reset my ntp server and started working again.

**Comment by rorlig** [comment] 2016-12-14 19:17
ran it same issue .. was tearing my hair apart. Thanks for reporting this

**Comment by marlonlimaserra** [comment] 2022-08-27 23:30
I have this problem.

I have two projects

In one, serverless exits as soon as the deploy is finished.

On the other, I have to press ctrl+c

I can't solve this for nothing.

**Comment by andrew-vqn** [comment] 2023-04-03 17:01
I found the solution.
You need to update the time in your device
referral: https://docs.aws.amazon.com/AWSEC2/latest/UserGuide/set-time.html
It works for me.
