### ISSUE TITLE
CloudFormation is waiting for NetworkInterfaces associated with the Lambda Function to be cleaned up.

### ISSUE THREAD

**Issue by jamesla** [serverless/serverless#7633] opened 2020-04-29 00:37 UTC
# Bug Report

When removing a serverless deployment (that is configured to use an AWS VPC) the stack hangs on "CloudFormation is waiting for NetworkInterfaces associated with the Lambda Function to be cleaned up." for 45 minutes before AWS killing the stack.

```
provider:
  name: aws
  httpApi:
    id: ${env:APIGW_ID}
  stage: ${env:STAGE}
  runtime: nodejs12.x
  region: us-east-1
  role: ${env:ROLE}
  deploymentBucket:
    name: ${env:DEPLOY_BUCKET}
    serverSideEncryption: AES256
  vpc:
    securityGroupIds:
      - ${env:SECURITY_GROUP}
    subnetIds:
      - ${env:SUBNET_A}
      - ${env:SUBNET_B}
```

Once it times out and cloudformation just force deletes the stack, you can see that it leaves a bunch of network interfaces bound to the security groups which appear to be where the problem lies.

If I remove the VPC: block then it removes quickly.

It would appear there is a race condition in the way that the cloudformation template gets built. Has anybody seen this one before?

**Comment by herebebogans** [comment] 2020-04-29 01:33
Yes - this is a well known issue with VPC attached functions that was supposed to have improved recently. I'm not sure serverless should try work around this as it's an inherent CF issue.

Discussion here.

https://forum.serverless.com/t/very-long-delay-when-doing-sls-remove-of-lambda-in-a-vpc/2535/11

**Comment by medikoo** [comment] 2020-04-29 08:29
@jamesla I've once prepared a plugin to help tackle that issue: https://github.com/medikoo/serverless-plugin-vpc-eni-cleanup#serverless-plugin-vpc-eni-cleanup

I'm not sure if we can do anything on Framework level to improve that

**Comment by jamesla** [comment] 2020-04-30 04:45
Is there a workaround people are using in the meantime while Amazon fixes it? Are people just putting up with it? Are they rearchitecting to not put lambdas in VPC's?

@medikoo thanks for making that plugin. It looks like a perfect solution although I am having an issue but I will make a seperate issue in the plugins repository.

**Comment by medikoo** [comment] 2020-04-30 17:19
@jamesla can we close this then? I believe it's more a problem on provider side, and aside of mentioned plugin it's hard to improve experience in any way.

**Comment by sav-valerio** [comment] 2020-04-30 21:14
FYI, strictly correlated to this https://github.com/serverless/serverless/issues/5008

**Comment by medikoo** [comment] 2020-05-04 07:34
Thanks, let me close it than as duplicate of #5008.

I've also added there a comment pointing a plugin and proposal that we can provide some more meaningful message to the users.

**Comment by medikoo** [comment] 2020-05-04 07:34
Duplicate of #5008

**Closed by medikoo** 2020-05-04 07:34 UTC
Labels: bug/provider, cat/aws-vpc, cat/deployment
