### ISSUE TITLE
Deploying Python package to Lambda

### ISSUE THREAD

**Issue by kevindavee** [serverless/serverless#4612] opened 2017-12-27 16:38 UTC
Hi everyone,

I want to ask how to upload the dependencies of python (3rd party library or other directories). For example, I have a folder structure like this

```
src
  handler.py
  Class
    Base.py
Packages
  some_dependencies
handler_example.py
serverless.yml
```

I defined the `handler.py` and `handler_example.py` function inside the root `serverless.yml`. But `handler_example.py` cannot import dependencies inside Packages folder, and `handler.py` cannot import `Base.py` because Class folder could not be found.

In the serverless.yml, I just defined the provider regularly (stage, runtime, region, name, memorySize) and for the functions I defined each of them with (handler, name, timeout, events)

Is there anything that I missed ? Please help. It is really frustrating
Please let me know if you need me to provide more information. I really appreciate if you guys can help

**Comment by horike37** [comment] 2017-12-28 05:21
Hi @kevindavee, thank you for asking :smile: 
Could you share the pointer where the Serverless project is hosted so that we can take a look into it?

**Comment by kevindavee** [comment] 2017-12-28 06:37
hi @horike37 . I'm new to serverless framework. What do you mean with pointer and where I can find it ? Thanks

**Comment by horike37** [comment] 2017-12-28 11:51
@kevindavee 
Thank you for the response :+1:
We would like to take a look into the source code and the content of serverless.yml file you are using so that we can find the cause.
Where do you host those? If those are hosted on GitHub, could you share your repo URL?
Would be good to upload the zip file which archive your project if those are on only your local laptop :smile:

**Comment by brianneisler** [comment] 2019-01-24 01:36
Closing this issue as author did no respond.

**Closed by brianneisler** 2019-01-24 01:36 UTC
Labels: pr/more-info-needed, question
