### ISSUE TITLE
Version 1.39.0 No <filename>.zip file found in the package path you provided

### ISSUE THREAD

**Issue by c2xbrhdj6u4qs15** [serverless/serverless#5929] opened 2019-03-15 18:31 UTC
Hi, I am getting the following error when running with version 1.39.0

```
Serverless: Packaging service...
Serverless: Excluding development dependencies...
Serverless Error ---------------------------------------
No HelloWorld.zip file found in the package path you provided.
Get Support --------------------------------------------
Docs: docs.serverless.com
Bugs: github.com/serverless/serverless/issues
Issues: forum.serverless.com
Your Environment Information -----------------------------
OS: linux
Node Version: 6.16.0
Serverless Version: 1.39.0
```

With Version 1.38.0 everything works fine. In my serverless.yml I am using 

> package:
>   individually: true

 and in functions I use 

> package:
>       exclude:
>         - '**/*'
>       include:
>         - 'hello-world.py'

Thanks

**Comment by dschep** [comment] 2019-03-15 18:49
Duplicate of #5928

**Closed by dschep** 2019-03-15 18:49 UTC
