### ISSUE TITLE
Variable file() path isn't parsed if it contains `@`

### ISSUE THREAD

**Issue by adambiggs** [serverless/serverless#4494] opened 2017-11-24 21:31 UTC
# This is a Bug Report

## Description

I'm trying to load variables from a scoped npm module in `serverless.yml`:
```yml
custom:
  variableFromFile: ${file(node_modules/@scope/module-name/variables.json):variableName}
```

But when I try to deploy the service, I get the following error:
```
TypeError: Cannot read property 'Policies' of undefined
    at functionObj.events.forEach.event (/Users/adam/.config/yarn/global/node_modules/serverless/lib/plugins/aws/package/compile/events/stream/index.js:182:18)
    at Array.forEach (<anonymous>)
    at serverless.service.getAllFunctions.forEach (/Users/adam/.config/yarn/global/node_modules/serverless/lib/plugins/aws/package/compile/events/stream/index.js:41:28)
    at Array.forEach (<anonymous>)
    at AwsCompileStreamEvents.compileStreamEvents (/Users/adam/.config/yarn/global/node_modules/serverless/lib/plugins/aws/package/compile/events/stream/index.js:16:47)
    at BbPromise.reduce (/Users/adam/.config/yarn/global/node_modules/serverless/lib/classes/PluginManager.js:366:55)
From previous event:
    at PluginManager.invoke (/Users/adam/.config/yarn/global/node_modules/serverless/lib/classes/PluginManager.js:366:22)
    at PluginManager.spawn (/Users/adam/.config/yarn/global/node_modules/serverless/lib/classes/PluginManager.js:384:17)
    at Deploy.BbPromise.bind.then.then (/Users/adam/.config/yarn/global/node_modules/serverless/lib/plugins/deploy/deploy.js:120:50)
From previous event:
    at Object.before:deploy:deploy [as hook] (/Users/adam/.config/yarn/global/node_modules/serverless/lib/plugins/deploy/deploy.js:110:10)
    at BbPromise.reduce (/Users/adam/.config/yarn/global/node_modules/serverless/lib/classes/PluginManager.js:366:55)
From previous event:
    at PluginManager.invoke (/Users/adam/.config/yarn/global/node_modules/serverless/lib/classes/PluginManager.js:366:22)
    at PluginManager.run (/Users/adam/.config/yarn/global/node_modules/serverless/lib/classes/PluginManager.js:397:17)
    at variables.populateService.then (/Users/adam/.config/yarn/global/node_modules/serverless/lib/Serverless.js:104:33)
    at runCallback (timers.js:785:20)
    at tryOnImmediate (timers.js:747:5)
    at processImmediate [as _immediateCallback] (timers.js:718:5)
From previous event:
    at Serverless.run (/Users/adam/.config/yarn/global/node_modules/serverless/lib/Serverless.js:91:74)
    at serverless.init.then (/Users/adam/.config/yarn/global/node_modules/serverless/bin/serverless:42:50)
    at <anonymous>
```

If I copy the JSON file to a path that doesn't contain the `@` symbol, it works.

## Additional Data

* ***Serverless Framework Version you're using***: 1.24.1
* ***Operating System***: OSX

**Comment by horike37** [comment] 2017-11-27 15:38
Thank you for reporting @adambiggs :+1: that's a bug exactly since it has been reproduced on my end too.
I put `@test.yml` file on my test project and set up the following serverless.yml, then ran `sls print`.
However the `${file(./@test.yml):variableName}` did not be parsed properly. When removing `@`, it works fine though.

```yml
service: sls-test
provider:
  name: aws
  runtime: nodejs6.10
  stage: dev
  region: us-east-1

functions:
  hello:
    handler: handler.hello
    events:
      - http:
          path: hello
          method: get

custom:
  test: ${file(./@test.yml):variableName}
```

**Comment by FilipPyrek** [comment] 2017-12-01 14:38
@adambiggs I have exactly the same problem, I'm glad you opened an issue. :+1:

**Comment by HyperBrain** [comment] 2017-12-05 20:50
The reason for this bug is quite simple. The regex we use to parse the file variable syntax just does not allow for `@`.

`/^file\((~?[a-zA-Z0-9._\-/]+?)\)/`

So only alphanumeric characters are allowed including slashes. BTW: Using Windows path separators will also break 🤔 

We should instead use a regex that really matches file paths (including `\` and some special characters.

**Comment by HyperBrain** [comment] 2017-12-05 21:06
We should rather go for a blacklist regex here:
`/^file\(([^?%*:|"<>]+)\).*?$/`

I'm not sure why the file syntax does not even allow for absolute paths. Imo we should allow these.
The regex I wrote above seems to be suitable. It allows for any valid filename. It even works with embedded parenthesis and will correctly match: `file(/an/absolute/file(/with/)parenthesis)` too (due to the `.*?` it will match the outer `)` as the literal closing parenthesis.

**Comment by rdonkin** [comment] 2018-04-25 13:18
I ran into the same problem and it took a while to figure out what was going on - hope we can get the fix in soon!  

On current project, I have an automation repo that's published as NPM package to private NPM registry under `@foo/bar` name - so I have to resort to symbolic links to work around this.

**Comment by nfantone** [comment] 2019-01-07 15:51
Probably related.

Today I tried to load a variable from SSM with a `file:` default and while the value _was_ parsed and replaced, SSM was never reached - as if the `ssm:` portion was a string literal.

This is what I mean:

```yml
# In serverless.yml
SYMMETRIC_KEY: ${ssm:/${opt:environment}/services/config/symmetric-key, '${file(./config/${opt:environment}.json):paseto.key}'}
```

`SYMMETRIC_KEY` resolves to:

```js
console.log(process.env.SYMMETRIC_KEY);
> ${ssm:/development/services/config/symmetric-key, 'cxyzPH2Qb3kaBVeXpGhHb7/+eH6Ir1K/d/rhTCsfsHc='}
```

Changing the default value from `cxyzPH2Qb3kaBVeXpGhHb7/+eH6Ir1K/d/rhTCsfsHc=` to some other using only alphanumeric chars makes it work as expected.

**Closed** 2019-01-07 15:56 UTC
Labels: kind/bug, stage/in-progress
