### ISSUE TITLE
Allow for Predictable inter-Service References (`${local:...}`)

### ISSUE THREAD

**Issue by erikerikson** [serverless/serverless#3233] opened 2017-02-11 03:11 UTC
# This is a Feature Proposal

Add a `local` variable type, that resolves as a reference to the file that contains it, rather than `self` which resolves to the current service.

## Description

For feature proposals:
* What is the use case that should be solved. The more detail you describe this in the easier it is to understand for us.

The use case to be solved is cross-references in serverless services.

For example, I define:

~/svc1/serverless.yml
```
service: svc1

custom:
  svc1Version: 2
  exportSvc1ExportedResource: ${self:service}-svc1ExportedResourceName-${self:custom.svc1Version}
[...]
resources:
  Outputs:
    Svc1ExportedResource:
      Description: A resource that is exported to other services
      Value:
        Ref: Svc1Resource
      Export:
        Name: ${self:custom.exportSvc1ExportedResource}
```

To abide by the [DRY](https://en.wikipedia.org/wiki/Don't_repeat_yourself) principle, I don't want to copy paste the many-part export name, so I load ~/svc1/serverless.yml in a dependent service definition:

~/svc2/serverless.yml
```
service: svc2

custom:
  svc1Version: 1
  svc1: ${file(~/svc1/serverless.yml)}

provider:
  iamRoleStatements:
    -  Effect: "Allow"
       Action:
         - "aws:action"
       Resource:
         Fn::ImportValue: ${self:custom.svc1.exportSvc1ExportedResource}
[...]
```

Right now, the deploy of `~/svc2/serverless.yml` will fail because `${self:custom.svc1.exportSvc1ExportedResource}`, in the context of `svc2` will resolve `${self:service}` (from the `exportSvc1ExportedResource` declaration in `~/svc1/serverless.yml`) to `svc2` instead of `svc1`.  Note that It will also resolve `svc1Version` differently but that's exactly what I want (since I haven't updated my use of the API [or whatever] yet).

As a service defining an export to be used in other services, I'd love to be able to specify where the information is drawn from (i.e. the defining service or the consuming service).  I propose this could be accomplished with the following syntax (`${local:...}`):

```
  exportSvc1ExportedResource: ${local:service}-svc1ExportedResourceName-${self:custom.svc1Version}
```

This way, the right unique prefix is used but other services can choose which version of my first service to depend on.

Originally discussed in the context of https://github.com/serverless/serverless/issues/3206, https://github.com/serverless/serverless/issues/3207, and https://github.com/serverless/serverless/pull/3208.

**Comment by medikoo** [comment] 2020-09-24 15:08
I'm in a process of cleaning older issues, hence my input on that.

That's an interesting proposal, still I'm afraid it may introduce a difficult to solve issues and definitely will make internals way more complicated (as we're introducing another resolution dimension, and that's not free)

Technically _local_ should be resolved by handling file configuration on its own, however other variables which can be used in same file, require resolution in context of a _config_ which then requires the file to be resolved on config. I can imagine many inconvenient quirks and dead ends when trying to attempt such resolution right.

Seeing that solution proposal is challenging, and likely to introduce a significant maintenance debt, I'd rather focus on use case, and that one seems unclear (why exactly do we want to import other `serverless.yml` ? Just that raises a flag) and even if for some reason no better solution has been found. I would simply hardcode _service name_ instead of relying on `${self:service}`, while not perfectly convenient, it allows to move forward with taken approach as intended. 

At this point I've decided to close it as _wont fix_, but I'm open on further elaboration on that, assuming, that it still feels as desired feature.

**Closed by medikoo** 2020-09-24 15:08 UTC
Labels: cat/variable, enhancement, needs feedback

**Comment by erikerikson** [comment] 2020-09-24 15:39
Hi @medikoo - we did this in Hello, Retail as linked above.  The reason for inter-service loading is that it supported being DRY in a large system.  Same reason we don't use magic numbers and we do use header files.

> why exactly do we want to import other serverless.yml ?

Because a service's definition is the best authority of it's definition.  It got weird when a proper and working service failed to load (for reference in another service) because it referenced files and CWD had been changed (some services were 1 directory from a shared config at the root directory and others were 2).

The use case is that shared infrastructure (i.e. an ingest Kinesis)  is deployed in one serverless.yml and other independent services need to reference the shared resources.

It could all be defined in the same service but then we start hitting asset count and other limits and use challenges.

One perspective to take to reject this proposal is that there is a bug in the `${file: ...}` variable code (maybe self and others too?) and that it should always load the defined path relative to the config that is declaring the file variable.  The challenge is that seemed like a breaking change since it could invalidate some existing configs.

BTW what is the flag that is raised?  Or rather, the concern behind it?

**Comment by medikoo** [comment] 2020-09-24 15:51
> BTW what is the flag that is raised? Or rather, the concern behind it?

Requiring top level configuration via `$file()` is susceptible to side effects (In similar way as e.g. requiring a Node.js module which was intended to be used only as _main_ module).

Here side effect is that `service` is a special top level config property (e.g. in which iirc we do not support variable resolution), and here issue was opened as _side effect_ of such approach, is that resolution of file top level `service` property became ambiguous (it works differently in _top_ level config and when file is imported via `$file()`).

Summarizing, top level `serverless.yml` was not designed to be used as input for`$file()` imports, so going that route is likely to introduce issues.

Proper solution would be to export shareable parts to files dedicated for `$file()` imports, and rely on them in top level serverless configurations (at same time not attempting to import them directly in other serverless configs)

**Comment by erikerikson** [comment] 2020-09-24 18:54
Thank you for helping me understand how this raises a flag for you.

You are totally correct that the variable system assumes the first loaded service as context.  This is what would be the source of the breaking change.  It was also the reason this was suggested as a solution, for handling more advanced cases where there would be utility in explicitly preparing a subset of service declarations to not make that assumption.

FWIW - the `service` attribute has long supported variable resolution ([as used in Hello, Retail](https://github.com/Nordstrom/hello-retail/blob/master/retail-stream/serverless.yml#L3)).

Clarification: The references were instead to [resource name specifications](https://github.com/Nordstrom/hello-retail/blob/master/retail-stream/serverless.yml#L14) which were then used to [export references to resources](https://github.com/Nordstrom/hello-retail/blob/master/retail-stream/serverless.yml#L100) that were then [imported](https://github.com/Nordstrom/hello-retail/blob/master/product-catalog/builder/serverless.yml#L42) elsewhere [throughout](https://github.com/Nordstrom/hello-retail/blob/master/product-photos/0.processor/serverless.yml#L35) the [system](https://github.com/Nordstrom/hello-retail-workshop/blob/master/Teachers_Guide/fanout.md#step-b-register-all-source-to-target-mappings--source-is-the-hello-retail-stream-core-stream-in-our-use-case-and-target-is-the-local-copy-of-the-hello-retail-stream--as-an-example-of-registering-one-kinesis-stream-to-another-kinesis-stream).

Clearly it's been a bit.  I remember that there was a blocker to externalizing everything  to config files but I can't remember what it was at this moment.  Certainly one of the advantages of the framework was having everything succinctly and compactly declared/not having everything spread illegibly all over the place.

However, all that written I don't have a stake in this any more and don't mean to contradict the "wontfix" so much as to inform.  There were definitely valuable use cases in the context this came from.  They would have been served by an expansion of capabilities in line with this proposal.  I certainly feel no rights to declare any relative prioritization or weigh in on the added complexity to user value trade offs with this, so please only take all of this as an attempt to share the use case and a few of the motivations that had me open this up originally.
