### ISSUE TITLE
API Gateway deployment fails on 1.42.0

### ISSUE THREAD

**Issue by drissamri** [serverless/serverless#6099] opened 2019-05-09 15:38 UTC
# This is a Bug Report

## Description

* What went wrong?
sls deploy works on 1.41.1 but gives an API Gateway error 1.42.0 - the error seems to be related to tags we are setting - but worked on all version before.

* What did you expect should have happened?
Deployment succeeds like 1.41.1. This happens even after a clean install (sls remove && sls deploy)

* What was the config you used?
We set these tags on stack and tag level, but nowhere else
```
  stackTags:
      xxx-tagguid: "66602c43-d5b3-4f94-a986-b932d8941ca5"
  tags:
    xxx-tagguid: "66602c43-d5b3-4f94-a986-b932d8941ca5"
```

* What stacktrace or error message from your provider did you see?

```
service: xxx-xxx-xxx-adapter-lambda
stage: dev
region: eu-west-1
stack: xx-xxx-xx-adapter-lambda-dev
resources: 17
api keys:
  None
endpoints:
  GET - https://xxxx.execute-api.eu-west-1.amazonaws.com/dev/info
  POST - https://xxx.execute-api.eu-west-1.amazonaws.com/dev/v1/xxx/xx
functions:
  handler: xxx-xx-xx-adapter-lambda-handler-dev
layers:
  None
Serverless: [AWS sts 200 0.394s 0 retries] getCallerIdentity({})
Serverless: [AWS apigateway 200 0.165s 0 retries] getRestApis({ limit: 500 })
Serverless: [AWS apigateway 200 0.129s 0 retries] getStage({ restApiId: 'xxx', stageName: 'dev' })
Serverless: [AWS apigateway 400 0.147s 0 retries] updateStage({ restApiId: 'xxxx',
  stageName: 'dev',
  patchOperations:
   [ { op: 'replace', path: '/tracingEnabled', value: 'false' },
     { op: 'replace', path: '/*/*/logging/dataTrace', value: 'false' },
     { op: 'replace', path: '/*/*/logging/loglevel', value: 'OFF' },
     { op: 'replace',
       path: '/variables/xxx-environment',
       value: 'sandbox' },
     { op: 'replace',
       path: '/variables/xxxx-tagguid',
       value: '66602c43-d5b3-4f94-a986-b932d8941ca5' },
     [length]: 5 ] })

  Serverless Error ---------------------------------------

  Invalid stage variable name: xxxx-tagguid.  Please use names with only word characters.

  Stack Trace --------------------------------------------

ServerlessError: Invalid stage variable name: xxxx-tagguid.  Please use names with only word characters.
    at promise.catch.err (C:\xxxx\workspace\xxx\xx-xxx-adapter-lambda\node_modules\serverless\lib\plugins\aws\provider\awsProvider.js:302:11)
    at process.internalTickCallback (internal/process/next_tick.js:77:7)

  Get Support --------------------------------------------
     Docs:          docs.serverless.com
     Bugs:          github.com/serverless/serverless/issues
     Issues:        forum.serverless.com

  Your Environment Information ---------------------------
     OS:                     win32
     Node Version:           11.6.0
     Serverless Version:     1.42.0`**
```
* ***Serverless Framework Version you're using***:
1.42.0

* ***Operating System***:
Windows 10 locally & on Linux Jenkins

* ***Provider Error messages***:

**Comment by ceefour** [comment] 2019-05-10 05:40
Seems to be a regression of #5693.

**Comment by drissamri** [comment] 2019-05-13 09:19
Yeah, same as that ticket I'm using `stage: ${opt:stage, 'dev'}` with no reference to the hypen guid for my API Gateway stages/name/url's

**Comment by drissamri** [comment] 2019-05-14 14:39
The issue still persist with 1.42.3

**Comment by drissamri** [comment] 2019-05-24 13:58
And also in 1.43.0, is there any more output that I can add which would make troubleshooting/fixing this easier? Let me know if I can be of any assistance.

**Comment by jjasonclark** [comment] 2019-05-24 18:48
I'm getting this same error. My situation is a bit different. I'm not setting any `stackTags`. Only `tags` on the provider settings.

In my case the tags are being added as variables, and some of the tags have spaces in the names. If I remove the tags with spaces it will deploy.

**Comment by efimk-lu** [comment] 2019-05-26 13:45
Having the same issue, I have to revert back to 1.41.1 for it to work.

**Comment by exoego** [comment] 2019-05-26 20:35
This will be fixed in next release.
ref: https://github.com/serverless/serverless/pull/6139

**Closed by exoego** 2019-05-26 20:35 UTC
Labels: bug, cat/api-gw
