### ISSUE TITLE
Unable to create a template 

### ISSUE THREAD

**Issue by dileephell** [serverless/serverless#4520] opened 2017-12-04 10:55 UTC
D:\dataFlow>serverless create --template aws-nodejs

  Serverless Error ---------------------------------------

  Serverless plugin "C:\Users\c_dileep.singh\AppData\Roaming\npm\node_modules\se
rverless\lib\plugins\run\index.js" initialization errored: Cannot find module '@
serverless/fdk'

  Get Support --------------------------------------------
     Docs:          docs.serverless.com
     Bugs:          github.com/serverless/serverless/issues
     Forums:        forum.serverless.com
     Chat:          gitter.im/serverless/serverless

  Your Environment Information -----------------------------
     OS:                     win32
     Node Version:           8.9.1
     Serverless Version:     1.24.1

**Comment by HyperBrain** [comment] 2017-12-04 11:01
Hi @dileephell , thanks for reporting 👍 

This seems to be a duplicate of #4495 . Do you have a `.npmrc` file that routes all private packages (regardless of their scope) to a private registry? If yes, then you should only redirect the ones you use, other wise it could be the npm issue mentioned in the beforementioned issue.

**Comment by dileephell** [comment] 2017-12-11 07:23
Hi @HyperBrain . I don't have the .npmrc file. 

What more info can i provide?

**Closed** 2018-01-24 16:02 UTC
Labels: status/more-info-needed
