### ISSUE TITLE
Could not locate deployment bucket. Error: AWS provider credentials not found.

### ISSUE THREAD

**Issue by mdw2000** [serverless/serverless#6421] opened 2019-07-20 10:37 UTC
## Description

I'm getting the following error when deploying after upgrading to `1.48.2` from `1.45.1`.

I'm using a custom deployment bucket but worked fine.

```
 Serverless Error --------------------------------------- 
  
  Could not locate deployment bucket. Error: AWS provider credentials not found. Learn how to set up AWS provider credentials in our docs here: <http://bit.ly/aws-creds-setup>. 
  
  Get Support -------------------------------------------- 
     Docs:          docs.serverless.com 
     Bugs:          github.com/serverless/serverless/issues 
     Issues:        forum.serverless.com 
  
  Your Environment Information --------------------------- 
     Operating System:          linux 
     Node Version:              10.14.1 
     Serverless Version:        1.48.2 
     Enterprise Plugin Version: 1.3.1 
     Platform SDK Version:      2.0.3 
```

Provider config: 

```
provider:
  name: aws
  runtime: nodejs10.x
  region: eu-west-1
  timeout: 28
  stage: ${opt:stage, "dev"}
  deploymentBucket: bb-deploy
  memorySize: 1024
```

I'm deploying using an AWS CodeBuild project.  No special config there, using the standard Linux image provided by CodeBuild.

**Comment by romaninsh** [comment] 2019-07-20 11:15
Same confirmed on **AWS CodeBuild** project with **a specified deploy role**. Older version of serverless works OK:

```
  Serverless Error --------------------------------------- 
  
  ServerlessError: AWS provider credentials not found. Learn how to set up AWS provider credentials in our docs here: <http://bit.ly/aws-creds-setup>. 
  
  Get Support -------------------------------------------- 
     Docs:          docs.serverless.com 
     Bugs:          github.com/serverless/serverless/issues 
     Issues:        forum.serverless.com 
  
  Your Environment Information --------------------------- 
     Operating System:          linux 
     Node Version:              7.10.1 
     Serverless Version:        1.48.2 
     Enterprise Plugin Version: 1.3.1 
     Platform SDK Version:      2.0.3 
```

**Comment by prabukamal** [comment] 2019-07-20 13:51
I am having the same issue

**Comment by edwards-will** [comment] 2019-07-20 15:09
Same issue

**Comment by jakebenn** [comment] 2019-07-20 20:28
+1

I started seeing the problem in CodeBuild after upgrading to 1.48.2. In my CI/CD pipeline, CodeBuild is using the underlying IAM execution role for security access, rather than AWS credentials. After the upgrade, the CodeBuild job started failing. If I switch to version 1.48.0, the IAM role works, so the bug must have been introduced in release 1.48.1 or 1.48.2.

**Comment by maxieduncan** [comment] 2019-07-20 20:44
Same issue with my CI/CD pipeline and CodeBuild

**Comment by curryfury-slalom** [comment] 2019-07-21 02:19
Same here with Codebuild.  Was pulling my hair out

**Comment by jeffleus** [comment] 2019-07-21 03:10
Same issue w/CodeBuild on a buildspec that was previously working.  I updated the buildspec to force an install of 1.47.0 and it resolved my issue

**Comment by curryfury-slalom** [comment] 2019-07-21 03:34
Working with v1.48.0

**Comment by dashmug** [comment] 2019-07-21 23:30
Broken in v1.48.2.

**Comment by jayai2014** [comment] 2019-07-22 01:45
Not working with v1.48.2

**Comment by DmitryNefedov** [comment] 2019-07-22 06:03
Same here, stopped working in AWS CodeBuild with the assumed role.

**Comment by ebaioni** [comment] 2019-07-22 06:09
same, on aws codebuild too

**Comment by pmuens** [comment] 2019-07-22 10:22
Thanks for opening @mdw2000 :+1:

This issue seems to be a duplicate of https://github.com/serverless/serverless/issues/6414. We'll discuss potential solutions over there.

**Closed by pmuens** 2019-07-22 10:22 UTC
Labels: bug, cat/providers
