### ISSUE TITLE
Stop modifying my bashrc with these tabtab turds

### ISSUE THREAD

**Issue by bugeats** [serverless/serverless#5124] opened 2018-07-12 19:41 UTC
Every time I run serverless (or update?) I find my `bashrc` has been silently modified:

```bash
# tabtab source for serverless package
# uninstall by removing these lines or running `tabtab uninstall serverless`
[ -f /Users/<redacted>/node_modules/tabtab/.completions/serverless.bash ] && . /Users/<redacted>/node_modules/tabtab/.completions/serverless.bash
# tabtab source for sls package
# uninstall by removing these lines or running `tabtab uninstall sls`
[ -f /Users/<redacted>/node_modules/tabtab/.completions/sls.bash ] && . /Users/c<redacted>/node_modules/tabtab/.completions/sls.bash
```

No chill.

**Comment by fellowseb** [comment] 2018-09-28 21:31
I guess it's the use of `tabtab install --auto` that causes that has this unpleasant consequence.

**Comment by ahawkins** [comment] 2018-12-16 05:04
You can short circuit this by adding the installation markers to your config. Here's an example from my dotfiles: https://github.com/ahawkins/dotfiles/commit/bee5e3cfefd5801feebd21467fee6cda31270162.

**Comment by dschep** [comment] 2018-12-19 17:18
Duplicate of #4069

**Closed by dschep** 2018-12-19 17:18 UTC

**Comment by HendrikPetertje** [comment] 2020-01-10 09:50
in zsh, that short circuit doesn't seem to work. Please stop filling my dotfiles with crap. 

That said, It be really nice if Serverless could just stick to normal node-based completions, I don't understand how tabtab integration is relevant enough to be a first class citizen like this.
