### ISSUE TITLE
Multiple developers overwrite each others changes

### ISSUE THREAD

**Issue by kennu** [serverless/serverless#2422] opened 2016-10-17 19:08 UTC
I'd like to add another point about CloudFormation friction, even though @flomotlik is probably not thrilled about my complaining. :-)

In Serverless 1.0, when two or more developers are working on the same service, they can very easily overwrite each others changes, causing the other developers' endpoints and functions to disappear. You can try to alleviate this by using `sls function deploy`, but all it takes is one accidental `sls deploy` and everything is gone. Also, I think adding a new function is not possible without a full `sls deploy`. So multiple developers can't add new functions simultaneously without coordinating their Git repositories, which adds friction and lowers individual productivity.

I can already see there being `sls deploy` wars, where one developer accidentally destroys the other's uncommitted deployment, and because the other is in a hurry, they also run `sls deploy` again to get everything back, and then the other one runs `sls deploy` again, etc.. This is bad for productivity.

In contrast, in Serverless 0.x, it was quite easy for many developers to work on the same service in parallel. That was one of the reasons we started using Serverless (vs. something like Beanstalk, where a new deployment would also overwrite the previous one). We've rarely had conflicts between developers in 0.x and most projects are still using it. Even `sls function deploy -a` or `sls endpoint deploy -a` does not completely remove the other developers' uncommitted stuff.

I just happened to destroy another developers' uncommitted deployment a moment ago, so I wanted to bring up the issue here. I'm a bit worried how this will affect developer workflows when we migrate to 1.0.

(Not sure if this is the right forum for this, since this is a CloudFormation "feature" and probably not much can be done about it. And it's one of the reasons I think CloudFormation is nice for managing production deployments, but not so nice for development.)

**Comment by rowanu** [comment] 2016-10-17 22:58
Part of the benefit of CFN (and any/all other infrastructure as code tools) is that you use the **same** tools in development as production. How else can you guarantee that what you deploy to production is what you tested in development? Deploying un-committed changes to a long-lived environment is a Bad Idea - how do you troubleshoot any issues that arise from a bug being deployed that isn't committed anywhere? How do you know that it isn't those un-committed changes that are making your development environment _work_, and that when you deploy your changes to production you miss it?

Why do you share a development environment? Why not just give each dev their own environment to play with? Then they can do their own deployments without fear of impacting others. If your service requires more than one developer to work on it at a time, can it be broken down in to smaller services?

I think using CFN was one of the best things about Serverless 1.0 (in case you couldn't already tell 😉 ).

**Comment by kennu** [comment] 2016-10-17 23:46
How I see it, creating an individually 100% reproducible development environment will require a significant amount of preparation effort. It will also require developers to constantly ensure that their changes are reproducible for all other developers in their environments. It also adds all kinds of extra delays, when developers must test that things like S3 buckets, DynamoDB tables and CloudFront distributions are properly recreated by scripts. And new developers will have to setup their own development stage somehow.

This is probably fine when working on just one big project already in production, where the extra effort is justified and buried in the total cost. When working on a larger number of small projects and MVPs, the overhead starts to eat into productivity.

For me this is the opposite of the big promise of the cloud and the serverless paradigm. Things are supposed to be quick and effortless, and let developers focus primarily in the true value-add of the application. This is crucial especially for PoC and MVP projects, where the initial product must be developed fast. At that stage nobody wants to pay for a well-polished, fully reproducible architecture yet. The final product might not even get developed.

For these reasons, I've seen a lot projects with a shared AWS development account/stage. We have been quite happy with the productivity of Serverless 0.5. Developers are able to very quickly add new resources and deploy new services. There is no initial overhead for new developers. They just install Serverless and run `sls deploy`. If they need to add an AWS IoT rule, they use the AWS Console wizard to quickly create rule and everybody else can use it too. Only much later on, if the product is actually deployed to production, the extra effort of encoding the full infrastructure into CloudFormation (and checking if it's possible to even add IoT rules with it nowadays ;-) is justified.

I don't want to be completely black-and-white about it though. Maybe it will be feasible to create individual developer-specific Serverless deployments that share existing cloud resources. I'm just trying to find a way to get back into the track of increased, not decreased, productivity.

**Comment by rowanu** [comment] 2016-10-18 00:02
All valid points, thanks for going in to detail.

I guess if there was a Silver Bullet Solution to these issues, we'd all be using/doing it already...

**Comment by flomotlik** [comment] 2016-10-19 16:37
While I understand why you have the need for this in a consulting environment, I think its a fundamentally flawed process to be honest. In my opinion if you deploy into a shared environment the  team needs to come up with processes to manage this, not the tools. While we can add locking or similar things to serverless services (e.g. only this person can deploy now) there will still be situations where its worked around.

Having atomic deployments is a huge upside of V1 in comparison to V0, not just in terms of reproducability of infrastructure, but also much easier for us to build features with.

> Maybe it will be feasible to create individual developer-specific Serverless deployments that share existing cloud resources

I agree that this is a major problem that we need to solve so its easy for you not just to stand up one service, but also the whole infrastructure.

One important point on the whole focus of Serverless though, we're definitely not optimising on PoC and MVP projects, but longer running complex infrastructure. While its obviously important to be able to set up PoC and MVP projects easily we can't focus on it if we want to be a relevant long term project and business. This doesn't have any immediate impact because I think Serverless works great for PoC and MVP, but there will be situations like here where we're steadfast focusing on workflows that are helpful for complex larger scale projects, even at a potential negative for teams who build many short lived and smaller projects.

**Closed by flomotlik** 2016-10-19 16:37 UTC
