### ISSUE TITLE
Intrinsic function short form usage in integration test fixtures causes fixture loading to fail

### ISSUE THREAD

**Issue by fredericbarthelet** [serverless/serverless#8627] opened 2020-12-15 09:34 UTC
When writing an integration test for the framework, using any intrinsic function short syntax - i.e. `!GetAtt` instead of `Fn::GetAtt` - causes `fixtures.setup` to return null without triggering an error. This is quite confusing as short syntax is perfectly fine for deploying the same service in the context of an actual project.

In the exemple of `test/fixtures/httpApiExport/serverless.yml`, using `Ref: HttpApi` works perfectly fine

https://github.com/serverless/serverless/blob/c864fbd4826de27d2796e394b0a100c8d3add33e/test/fixtures/httpApiExport/serverless.yml#L26

However, replacing this with short syntax (https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/intrinsic-function-reference-ref.html#ref-declaration) `!Ref HttpApi` will cause fixture setup to fail.

<details>
<summary><b><code>⚠️⚠️ REPLACE WITH FULL COMMAND NAME</code> output</b></summary>

```
AWS_ACCESS_KEY_ID=xxxx AWS_SECRET_ACCESS_KEY=xxxx npx mocha test/integration/httpApi.test.js
```

</details>

<b>Installed version</b>

```
Framework Core: 2.15.0
Plugin: 4.2.0
SDK: 2.3.2
Components: 3.4.3
```

IMHO, the issue comes from `@serverless/test` package `get-fixtures-engine.js` file code block bellow :
```
try {
  return loadYaml(configContent);
} catch (error) {
  return null;
}
```

**Comment by medikoo** [comment] 2020-12-15 12:25
> When writing an integration test for the framework, using any intrinsic function short syntax - i.e. !GetAtt instead of Fn::GetAtt - causes fixtures.setup to return null without triggering an error.

This should be picked by `runServerless` with config validation, and run should fail with meaningful error. Wasn't that the case?

**Comment by medikoo** [comment] 2020-12-15 12:27
Additionally we accept JSON as config extension, and _short syntax_ is specific to YAML, so I don't think this really apply here.

**Comment by fredericbarthelet** [comment] 2020-12-15 17:02
@medikoo, sorry, I was not precise enough.

The failing line in my exemple command `AWS_ACCESS_KEY_ID=xxxx AWS_SECRET_ACCESS_KEY=xxxx npx mocha test/integration/httpApi.test.js` is https://github.com/serverless/serverless/blob/c864fbd4826de27d2796e394b0a100c8d3add33e/test/integration/httpApi.test.js#L230

This shorthand syntax is not part of the config extension, but is part of the `serverless.yml` file within the `httpApiExport` test fixture. If you go in this fixture directory - `test/fixtures/httpApiExport` - and run the `sls deploy` command with the short syntax in the serverless.yml, everything is fine. If you run a test with this service file, it silently crashes since `fixtures.setup` returns null

Do you see what I mean ?

**Comment by medikoo** [comment] 2020-12-16 16:16
@fredericbarthelet I see, the problem is at part in which fixture engine tries to [assign a generated service name to the config](https://github.com/serverless/test/blob/a1575a97f44e3904c5db0a5e4a821af6624dfcdd/get-fixtures-engine.js#L98-L107). It parses the config and crashes.

While just for fixture setup purpose I would argue, that we can simply not use shorthand syntax. Still I think it's valuable to have support for that, for the sake of testing that short syntax works as expected.

I believe it can be fixed by:
1. Moving [lib/plugins/aws/lib/clouformationSchema.js](https://github.com/serverless/serverless/blob/9bc1060dceb6a155abdb27364a9d0061b4d95983/lib/plugins/aws/lib/cloudformationSchema.js) to [@serverless/utils](https://github.com/serverless/utils) package
2. Parse config with schema option in fixture setup in [@servelress/test/get-fixtures-engine](https://github.com/serverless/test/blob/master/get-fixtures-engine.js)

PR's in all those projects are welcome!

**Closed** 2021-01-06 16:50 UTC
Labels: enhancement, good first issue, help wanted, tests

**Comment by fredericbarthelet** [comment] 2021-01-07 19:37
@medikoo I just realized the issue is actually not resolved until a new version of [@serverless/test](https://github.com/serverless/test) is released with the latest commit updating utils version (https://github.com/serverless/test/commit/85aad008fd5deaa389200bd0cd4b2cea90ebdec0).

Could you release a new version of this package and I'll produce a PR on serverless/serverless to update the @serverlerss/test version ?

**Comment by medikoo** [comment] 2021-01-08 12:56
> Could you release a new version of this package and I'll produce a PR on serverless/serverless to update the @serverlerss/test version ?

Sure, it's released now. Still there's no need to bump version in `serverless`, as CI automatically is run against latest version of dependencies and we always bump dependencies prior releasing new version (so it's guaranteed to happen then)
