### ISSUE TITLE
Serverless 3.x installation fails in ADO release pipeline Ubuntu 20.04, Node 20.x all of a sudden

### ISSUE THREAD

**Issue by sai097** [serverless/serverless#12959] opened 2024-12-16 18:08 UTC
### Issue description

I'm using ADO release pipeline to deploy a service to AWS using Serverless. The deployments started failing all of a sudden today without revealing much information about what exactly went wrong. 

Versions:
ADO Agent job - Ubuntu 20.04
Node - 20.10.0
Serverless - 3.30.1

Below is the error message I can see in the step when I have two commands running **_npm install_** and **_sudo npm install serverless@3.30.1 -g_**

 npm error code TAR_BAD_ARCHIVE
2024-12-16T18:03:18.7625035Z npm error TAR_BAD_ARCHIVE: Unrecognized archive format

<img width="778" alt="image" src="https://github.com/user-attachments/assets/7cc59662-244e-49fe-912d-3fb6ec24897e" />

**Comment by Rbanda52** [comment] 2024-12-16 18:31
I am facing the same issue in my pipelines during the installation step of Serverless.
 npm error code TAR_BAD_ARCHIVE
 npm error TAR_BAD_ARCHIVE: Unrecognized archive format

**Comment by SThakur181** [comment] 2024-12-16 18:44
I am also facing the same issue since today. It was working fine till 13 Feb.
Configuration it worked on 13th:
Node : 18.x
Serverless : 3.0.0

Now even this combination is not working. Tried with latest version too, same issues.

**Comment by czubocha** [comment] 2024-12-16 19:01
@sai097 @Rbanda52 @SThakur181 I couldn’t reproduce the issue on my end. Could you confirm if this issue is specific to Serverless, or if you’re encountering the same error when installing other npm packages? I’ve noticed similar TAR_BAD_ARCHIVE issues being reported in multiple repositories on GitHub ([1](https://github.com/exceljs/exceljs/issues/2864), [2](https://github.com/gendocu-com/grpc-docs/issues/14)), so it might not be directly related to Serverless.

**Comment by sai097** [comment] 2024-12-16 19:21
> @sai097 @Rbanda52 @SThakur181 I couldn’t reproduce the issue on my end. Could you confirm if this issue is specific to Serverless, or if you’re encountering the same error when installing other npm packages? I’ve noticed similar TAR_BAD_ARCHIVE issues being reported in multiple repositories on GitHub ([1](https://github.com/exceljs/exceljs/issues/2864), [2](https://github.com/gendocu-com/grpc-docs/issues/14)), so it might not be directly related to Serverless.

@czubocha Thanks for checking. I only have one command in the ADO pipeline task which is the installation of Serverless through npm and I'm given this error. It certainly looks specific to Serverless in my case 
<img width="730" alt="image" src="https://github.com/user-attachments/assets/44b24752-db5d-41f3-8671-224f592858f2" />

**Comment by czubocha** [comment] 2024-12-16 20:22
Thanks for the update, @sai097. While the error occurs during the installation of Serverless, it’s still unclear if this is specific to Serverless or a broader issue with npm or global installations. Could you try installing another package globally, such as `npm install -g typescript` or any other package, and let us know if the issue persists? This will help us determine whether it’s a Serverless-specific problem or related to the npm environment itself.

**Comment by rohantor** [comment] 2024-12-17 05:41
I am facing the same issue in AWS code pipelines during the installation step of Serverless.
npm error code TAR_BAD_ARCHIVE
<img width="1188" alt="Screenshot 2024-12-17 at 11 12 08 AM" src="https://github.com/user-attachments/assets/06d353f6-6b74-4883-b47e-19814ebc604f" />

npm error TAR_BAD_ARCHIVE: Unrecognized archive format

**Comment by sagrawal31** [comment] 2024-12-17 06:56
This seems to be working for us after 14 hours of outage on AWS production environment

https://github.com/npm/cli/issues/7986#issuecomment-2547612100

**Comment by czubocha** [comment] 2024-12-17 11:39
Closing this as it’s caused by the ongoing npm registry outage: https://github.com/npm/cli/issues/7986

**Closed by czubocha** 2024-12-17 11:39 UTC
