### ISSUE TITLE
AWS non env credentials not working since 1.58

### ISSUE THREAD

**Issue by thomaspeitz** [serverless/serverless#7026] opened 2019-11-28 22:38 UTC
# Bug Report

Hey, first of all thanks for your awesome project contributors! <3
Newest version introduced some problems with aws profiles for me during local testing.

## Description

1. What did you do?
``` 
sls invoke local -f my-function
 ```
1. What happened?
```
/Users/thomaspeitz/git/pubg-api/vendor/bundle/ruby/2.5.0/gems/aws-sdk-core-3.82.0/lib/seahorse/client/plugins/raise_response_errors.rb:15:in `call': The security token included in the request is invalid. (Aws::DynamoDB::Errors::UnrecognizedClientException)
```
1. What should've happened?
My function gets executed without credentials error. Thought that my dynamodb gem update introduced this error but nothing after downgrade of aws sdk. Downgraded serverless package to 1.57 and it worked again.

1. What's the content of your `serverless.yml` file?
Pasting important part:
```
provider:
  name: aws
  runtime: ruby2.5
  stage: testing
  region: eu-west-1
  profile: private
```

Similar or dependent issues:
- I think this pr introduced the bug - https://github.com/serverless/serverless/pull/6938

Opening this today and checking if i can fix this tomorrow. Currently just want to code some fun project.

**Comment by medikoo** [comment] 2019-11-29 09:29
@thomaspeitz thanks for report. It looks as duplicate of https://github.com/serverless/serverless/issues/7013 We'll ensure to fix it with next release.

**Closed by medikoo** 2019-11-29 09:29 UTC
Labels: duplicate
