### ISSUE TITLE
Serverless package does not include all modules when a package.json file is provided

### ISSUE THREAD

**Issue by xmissio** [serverless/serverless#3915] opened 2017-07-07 18:01 UTC
# This is a (Bug Report)
## Description
When deploying multiple versions of a service or just versions of the function within the service, but sometimes some modules are not included in the package in presence of a package.json file

* What went wrong?
When using ``sls deploy`` or ``sls deploy -f functionName`` or ``sls package`` the ``service.zip`` doest not include all my node_modules, when I checked the package I figured out that some modules were missing 
My tree:
```
lamba
  dir
  dir
  index.js
  package.json
  serverless.yml
  node_modules
```

My package.json file was something like this:
```
{
  "name": "lambda",
  "version": "1.0.0",
  "description": "lambda",
  "main": "index.js",
  "dependencies": {
    "handlebars": "^4.0.10",
    "html-pdf": "^2.1.0",
    "mathfinjs": "^1.0.2",
    "moment": "^2.18.1",
    "numeral": "^2.0.6",
    "path": "^0.12.7",
    "pdfkit": "^0.8.3",
    "pg": "^6.4.0",
    "request-promise": "^4.2.1"
  },
  "scripts": {
    "test": "echo \"Error: no test specified\" && exit 1"
  },
  "author": "RAZ",
  "license": "ISC"
}
```
* What did you expect should have happened?

That every time that I deploy a service/function the package be the same but ``request-promise`` and ``pg`` were missing

* What was the config you used?
```
service: service

frameworkVersion: ">=1.8.0 <2.0.0"

provider:
  name: aws
  runtime: nodejs6.10
  region: us-west-2
  versionFunctions: false

functions:
  function:
    handler: index.handler
    description: description
    memorySize: 1024
    timeout: 30
    role: arn-role
    tags:
      Department: IT
      Name: name
      Team: team
      TeamMember: TeamMember
    environment:
      var: value
      var: value
      var: value
      var: value
      var: value
    
```
* What stacktrace or error message from your provider did you see?
```
{
  "errorMessage": "Cannot find module 'request-promise'",
  "errorType": "Error",
  "stackTrace": [
    "Module.require (module.js:497:17)",
    "require (internal/module.js:20:19)",
    "Object.<anonymous> (/var/task/index.js:14:23)",
    "Module._compile (module.js:570:32)",
    "Object.Module._extensions..js (module.js:579:10)",
    "Module.load (module.js:487:32)",
    "tryModuleLoad (module.js:446:12)",
    "Function.Module._load (module.js:438:3)"
  ]
}
```
```
Unable to import module 'index': Error
    at Function.Module._load (module.js:417:25)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/var/task/index.js:14:23)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
```
Similar or dependent issues:

## Additional Data
Even using ``include: file`` was useless

**The solution for me was to rename/remove package.json file**

* ***Serverless Framework Version you're using***: 1.16.1
* ***Operating System***: macOS Sierra 10.12.5

**Comment by pmuens** [comment] 2017-07-07 20:34
Hey @xmissio thanks for opening! 👍

This could be related to https://github.com/serverless/serverless/pull/3889

Could you try to re-deploy while opting out of the dev dependency exclusion functionality?

You can opt out via:

```yml
package:
  excludeDevDependencies: false
```

**Comment by xmissio** [comment] 2017-07-07 21:04
I added those lines but the error persist

**Comment by pmuens** [comment] 2017-07-08 03:10
Hey @xmissio thanks for getting back. I see.

You're running `v1.16.1`. This feature was introduced in `v1.17.0` which was released last Wednesday. So updating Serverless should do the trick here.

**Comment by xmissio** [comment] 2017-07-09 15:27
Fixed, thanks

**Comment by pmuens** [comment] 2017-07-09 20:34
> Fixed, thanks

Glad to hear that this mitigates the problem for now. However we're currently working on a long-term fix for this which should be shipped soon.

**Comment by xmissio** [comment] 2017-07-10 00:30
I'm getting a new error, the first time worked but now I have this:
```
Serverless: Packaging service...
fs.js:953
  binding.stat(pathModule._makeLong(path));
          ^

Error: ENOENT: no such file or directory, stat '~/lambda/node_modules/aws-sdk/node_modules/.bin/uuid'
    at Object.fs.statSync (fs.js:953:11)
    at files.forEach (/usr/local/lib/node_modules/serverless/lib/plugins/package/lib/zipService.js:95:26)
    at Array.forEach (native)
    at WriteStream.output.on (/usr/local/lib/node_modules/serverless/lib/plugins/package/lib/zipService.js:89:13)
    at emitOne (events.js:115:13)
    at WriteStream.emit (events.js:210:7)
    at WriteStream.<anonymous> (fs.js:2110:10)
    at FSReqWrap.oncomplete (fs.js:135:15)
```
But the directory and files exist

I deleted .serverless directory and package.json but I getting the same error every time that I deploy

I'm going to downgrade and I will back to my previous solution, I need to work

**Comment by xmissio** [comment] 2017-07-10 01:10
I downgraded to 1.16.0 but error persisted, I deleted node_module directory, then npm install inside my service directory finally I execute sls deploy and it's working now
I just comment this to help
The new bug started when I :

```
upgrade to 1.17.0
```
added this lines to my serverless.yml

```
package:
  excludeDevDependencies: false
```
and rename my package-json.txt to

```
package.json
```  

and execute
``sls deploy``

**Comment by pmuens** [comment] 2017-07-10 06:23
@xmissio thanks for letting us know and providing steps to reproduce it.

We'll look into it...

**Closed** 2017-07-16 17:21 UTC
Labels: kind/bug, status/more-info-needed

**Comment by pmuens** [comment] 2017-07-16 18:45
@xmissio thanks for closing the issue?

Quick question: How were you able to fix it?

**Comment by xmissio** [comment] 2017-07-17 17:28
I renamed package.json to package-json.txt

**Comment by pmuens** [comment] 2017-07-18 07:07
> I renamed package.json to package-json.txt

Thanks for getting back @xmissio 👍 

Just took another look at it. This should be fixed with #3889.

**Comment by pmcdowell-okta** [comment] 2017-08-14 16:54
Thx for the update, I was having the same problem, renamed the package.json and it worked.

**Comment by pmuens** [comment] 2017-08-14 17:07
> Thx for the update, I was having the same problem, renamed the package.json and it worked.

@pmcdowell-okta thanks for confirming that this resolved the issue 👍 Glad to hear that it's working again 😊.

**Comment by celicoo** [comment] 2018-02-26 20:33
I'm experiencing the same issue in version 1.26.0. Any one else?

**Comment by anojperera** [comment] 2018-03-02 23:38
Yes I am experiencing this with 1.26.1

**Comment by zacacollier** [comment] 2018-05-21 18:02
I was seeing this issue as well on versions 1.26.1 and 1.27.2

```
  Error --------------------------------------------------

  ENOENT: no such file or directory, stat '/home/zac/Workspace/Services/graphql-service/node_modules/contents-service-client/node_modules/aws-sdk/node_modules/.bin/uuid'

     For debugging logs, run again after setting the "SLS_DEBUG=*" environment variable.

  Get Support --------------------------------------------
     Docs:          docs.serverless.com
     Bugs:          github.com/serverless/serverless/issues
     Forums:        forum.serverless.com
     Chat:          gitter.im/serverless/serverless

  Your Environment Information -----------------------------
     OS:                     linux
     Node Version:           8.10.0
     Serverless Version:     1.26.1
```

I fixed it by deleting my `node_modules` directory and reinstalling

**Comment by desmond-phonegap** [comment] 2018-09-16 22:54
I am using sls version 1.28.0 and still facing the issue. I have tried using

>  excludeDevDependencies: false 

option also but error still persist.

**Comment by SergeyAvd** [comment] 2019-07-22 16:51
I am experiencing this issue in 1.46.1. I have not tried `excludeDevDependencies: false`.

**Comment by maazmk** [comment] 2020-07-26 14:44
I am still experiencing this issue in 1.75.1. I have tried excludeDevDependencies: false.

**Comment by jose920405** [comment] 2020-09-15 15:59
> Hey @xmissio thanks for opening! 👍
> 
> This could be related to #3889.
> 
> Could you try to re-deploy while opting out of the dev dependency exclusion functionality?
> 
> You can opt-out via:
> 
> ```yaml
> package:
>   excludeDevDependencies: false
> ```

With the correct management of dependencies this shouldn't be necessary, because your packaged logic should only requiere modules that had to be added in `dependencies` not in `devDependencies`.

**Comment by DilLip-Chowdary-Codes** [comment] 2021-01-25 20:08
I am still experiencing this issue in 1.80.0. I have tried excludeDevDependencies: false.

**Comment by DilLip-Chowdary-Codes** [comment] 2021-01-28 10:50
Using `yarn` instead of `npm install` or `npm i` Fixed this Issue for me 👍

**Comment by lihuelworks** [comment] 2025-04-16 04:02
Same here, this bug is still persistent on 16-abr-2025
