### ISSUE TITLE
Provide support for attaching to existing Cloudformation resources

### ISSUE THREAD

**Issue by ajkerr** [serverless/serverless#1060] opened 2016-04-29 18:25 UTC
* Running Serverless 0.5.5 on Mac OS X El Capitan

We have several stages defined that are shared among developers on our team. These represent qa, staging, and most importantly, production environments/stages.

When users clone our serverless projects from git, we have an initialization script that creates the "canned" stages that we use, along with a user-specific stage.

When working with the pre-defined stages, we use the --noExeCf flag to prevent these shared CloudFormation stacks from being modified or removed. This is especially critical for production or customer facing stages.

When users attempt to deploy endpoints to these shared endpoints, they get an exception:

`serverless:lib.actions.EndpointDeploy TypeError: Cannot read property 'replace' of undefined
    at ServerlessProviderAws.getAccountId (/usr/local/fluid/product/xps-admin-serverless/node_modules/serverless/lib/ProviderAws.js:495:11)
    at Builder._validateAndPrepare (/usr/local/fluid/product/xps-admin-serverless/node_modules/serverless/lib/actions/EndpointBuildApiGateway.js:124:46)
    at Builder.build (/usr/local/fluid/product/xps-admin-serverless/node_modules/serverless/lib/actions/EndpointBuildApiGateway.js:70:20)
    at EndpointBuildApiGateway.endpointBuildApiGateway (/usr/local/fluid/product/xps-admin-serverless/node_modules/serverless/lib/actions/EndpointBuildApiGateway.js:54:22)
    at processImmediate [as _immediateCallback] (timers.js:383:17)`

Looking at the code, this is happening because the iamRoleArnLambda variable is undefined. This variable is only set by Serverless when resources are deployed (either directly or indirectly when creating stages without the --noExeCf flag set to true).

The documentation *does* mention that iamRoleArnLambda needs to be defined manually if you are not using Serverless to deploy CloudFormation resources.

We are thinking that a great feature would be for Serverless to be able to "discover" the values for iamRoleArnLambda by examining the stack for the IamRoleArnLambda output parameter. This would allow us to reattach our stages to existing Cloudformation stacks.

This could perhaps be achieved with a command like:
`serverless stage create --stage qa --region us-east-1 --profile default --noExeCf true --attachToCf my-project-qa-r`

This command would look up the CloudFormation stack by name, and then properly set the resourcesStackName and iamRoleArnLambda variables.

As a stopgap, we've done the following in our initialization script:
`serverless variables set --key iamRoleArnLambda --value $(aws cloudformation describe-stacks --stack-name my-project-qa-r --query 'Stacks[0].Outputs[0].OutputValue' | tr -d '"') --stage qa`

This works, but it'd be really nice if serverless supported this natively.

**Comment by eahefnawy** [comment] 2016-05-02 11:22
Thats a super interesting use case! I think it's a good change. I'm trying to think of ways to shrink the command a little bit though cause it's getting bigger. Maybe we can still use the `--noExeCf` option or tweak it a bit.

How about changing it to the following cases:

- if `--cf` option not provided, it'll deploy resources by default.
- if `--cf false` is provided, it'll NOT deploy resources. Note that this 'false` is actually a string, so we'll just validate it as such for better UX.
- if `--cf <stackName>` (or any string other than `false`) then we'll try to attach to this provided string

I think this way we won't need another option and the command is a bit easier to type. This option of course would replace `--noExeCf`

**Comment by ajkerr** [comment] 2016-05-02 11:51
@eahefnawy I really like the idea of overloading the use of the --cf option.

**Comment by cparis** [comment] 2016-05-06 20:10
I think that the bigger issue is around the CF output variables as a whole.  We have a similar problem, but, because of our federated access management and using stage variables, we can not deploy CF scripts via the API.  We must be logged in to the console.

Looking in the lib/actions/ResourcesDeploy.js, the only time it monitors the CF output is when its actually executing the create or update.  When runnin ghte --noExecCf, this section of code is not executed.

When using the --noExecCf, there needs to be an option to still pull in the variables, maybe like the --cf option above.

Another option would be to do something like:
sls resources pull --region us-east-1 --stage dev

That would go out, get the CF output, and refresh the variables via the CF details for output.

**Comment by flomotlik** [comment] 2016-05-14 16:10
@ajkerr this issue is also discussed in #928 and #1031 . The main problem is that some variables (e.g. ARN for an IAM role) can be savely shared in the repository, but the _meta folder makes this impossible as there is also not a good separation between values that should be kept secret and those that shouldn't.

I'm going to close this issue as it is a duplicate of the ones mentioned above, but we will definitely solve this issue as it makes working together in teams really hard.

**Closed by flomotlik** 2016-05-14 16:10 UTC
Labels: effort: medium, feature: accepted, priority: medium
