### ISSUE TITLE
Deployment appears to fail when removing a Lambda function using EventBridge (but doesn't)

### ISSUE THREAD

**Issue by ThomasAribart** [serverless/serverless#7655] opened 2020-05-02 22:38 UTC
# Bug Report

## Description

1. What did you do?

I deployed a stack with Lambda functions connected to EventBridge, and removed one.

1. What happened?

The deployment appeared to fail: The message "Operation failed!" appeared. However, the lambda is correctly removed.

1. What should've happened?

The deployment should have gone smoothly, and not triggered a false positive.

1. What's the content of your `serverless.yml` file?

```
provider:
  name: aws
  runtime: nodejs10.x
  region: eu-west-2
  stage: test
  usagePlan:
    quota:
      limit: 5000
      offset: 2
      period: MONTH
    throttle:
      burstLimit: 200
      rateLimit: 100

functions:
  test1:
    handler: test.handler
    events:
      - eventBridge:
          eventBus: ${self:custom.eventBusArn}
          pattern:
            source:
              - whatever
            detail-type:
              - whatever
  test2:
    handler: test.handler
    events:
      - eventBridge:
          eventBus: ${self:custom.eventBusArn}
          pattern:
            source:
              - whatever
            detail-type:
              - whatever

custom:
  eventBusArn: arn:aws:events:#{AWS::Region}:#{AWS::AccountId}:event-bus/my-bus
```

1. What's the output you get when you use the `SLS_DEBUG=*` environment variable (e.g. `SLS_DEBUG=* serverless deploy`)

*An error occurred: CustomEventBridge1 - Failed to delete resource. User: ...-custom-resource-event-bridge is not authorized to perform: lambda:RemovePermission on resource: ...test3 See details in CloudWatch Log: ...*

**Comment by medikoo** [comment] 2020-05-04 11:25
If read correctly (from #7656) issue is caused by fact, that on stack update:
- Needed IAM policy is removed from lambda
- Given custom resource is removed, but with that `remove` action is invoked on its lambda, and that fails, as it misses now the IAM policy needed to pursue needed action.

That's an interesting case. I would first check whether is there any way to ensure that `remove` action for removed custom resource could be invoked before any other changes in stack are applied.

If there are no setting which could enforce that. Then I believe we need to register unconditionally IAM policies which are needed for `remove` actions.

**Comment by bratchenko** [comment] 2020-07-26 02:35
Anyone was able to find at least a workaround for this? In our project, we generate some lambda names dynamically, and this bug causes pretty much every deployment to fail :(

**Comment by bratchenko** [comment] 2020-07-26 03:20
After digging into this, my suspicion is that the following happens:

1. [This code](https://github.com/serverless/serverless/blob/6216f359f647258305d26dce64af3c189abc08de/lib/plugins/aws/package/compile/events/eventBridge/index.js#L194-L212) sets a very specific permissions for the custom role: it is allowed the role to update only lambdas that have eventbridge events.
2. This role is updated before cloudfront starts deleting lambdas and unused custom resources. Because the new role definition does not allow access to lambdas that are no longer in the list, the Custom::EventBridge resource loses the ability to modify lambdas that still exist in the stack, but will be deleted later.
3. The delete fails because of the permission issues created on step 2.

I will try to modify the code to give wider permissions to the iamRoleStatements. For example, to modify any lambdas within the current stack. Not sure how to properly do it.

@medikoo, maybe you know how to do this correctly?

**Comment by medikoo** [comment] 2020-07-27 08:09
@bratchenko Are you sure that case is that function is removed _before_ the custom resource lambda is invoked?

To me it looks more that that IAM role (which allows to define permissions) is getting removed before custom resource lambda is invoked, and due to that custom resource no longer has rights to operate on lambda.

And if that's the case, then probably this could be fixed by ensuring that custom resource lambda depends on IAM role resource here: https://github.com/serverless/serverless/blob/ab99b657a3c613b3e9ba072e084d159f5ac6c073/lib/plugins/aws/customResources/index.js#L172

If you have reproducible test case, maybe you can confirm on that locally?

**Comment by bratchenko** [comment] 2020-07-27 17:32
> Are you sure that case is that function is removed before the custom resource lambda is invoked?

The function itself is removed after, but the IAM Role that allows the custom resource to remove permissions from the function is updated before - I'm sure of it (checked the cloudfront events log).

> To me it looks more that that IAM role (which allows to define permissions) is getting removed before custom resource lambda is invoked, and due to that custom resource no longer has rights to operate on lambda.

You are right. Except it does not get removed, but gets updated (in the case if at least one EventBridge event remains in the app). We use the same IAM Role and the same Custom::EventBridge resource for the whole serverless app. This is why dependencies won't work (the role will still be updated before custom resource tries to modify the function).

Here is the test scenario:

1. Download first.yml and second.yml from here: https://gist.github.com/bratchenko/68cc27ea92b4b08b6c0aac81113b8519

2. Run `sls deploy -c first.yml` - it runs successfully.

3. Run `sls deploy -c second.yml` (same config, but one lambda with EventBridge event removed) - it fails with the error in question.

4. Run `sls deploy -c second.yml` now more time - it succeeds (because lambda was actually deleted in step 3, even though it errored). This is because error happens in the cleanup stage, after the update was successfully completed.

I'm going to try playing with IAM Role definition to see if it helps.

**Comment by bratchenko** [comment] 2020-07-27 18:21
@medikoo here is my proposed solution: https://github.com/bratchenko/serverless/pull/1. I've verified it locally by running the manual test.

If you like it, I'll create a PR to this repository (seems like contribution rules require "agreeing on the solution" before creating a PR").

Let me know what is the best way to proceed.

**Comment by medikoo** [comment] 2020-07-28 10:13
@bratchenko great you've coined it! Please prepare a PR to this repo, also it'll be great if it's covered by integration tests here: https://github.com/serverless/serverless/blob/master/tests/integration-all/event-bridge/tests.js

**Closed** 2020-07-31 20:15 UTC
Labels: bug, cat/aws-event-event-bridge, cat/deployment, help wanted
