### ISSUE TITLE
Occasional error while checking stack update progress: Cannot read property 'find' of undefined

### ISSUE THREAD

**Issue by johngwilkinson** [serverless/serverless#3387] opened 2017-03-20 14:24 UTC
# This is a Bug Report

## Description

Sometimes, during deploy, we see an error while waiting for the stack to update. The same deployment will succeed at other times. This happens on the order of one time out of ten. Since there is no problem with the service, we'd expect it to succeed every time.

See stack trace below. The error occurs, in the latest version, at https://github.com/serverless/serverless/blob/master/lib/plugins/aws/lib/monitorStack.js#L47, apparently because the aws request has returned a "successful" response with no `StackEvents` object.

Similar or dependent issues: I haven't found any.

## Additional Data

* ***Serverless Framework Version you're using***: 1.6, 1.9
* ***Operating System***: linux
* ***Stack Trace***:

[This is from 1.6.0; 1.9 has a similar error, but it dies on 'find', rather than 'reverse']
```
Serverless: Checking Stack update progress...
............... 
  Serverless Error ---------------------------------------
 
     Cannot read property 'reverse' of undefined
 
  Stack Trace --------------------------------------------
 
ServerlessError: Cannot read property 'reverse' of undefined
    at provider.request.then.catch (/opt/Jenkins/workspace/EDU-pyxis/AnalyticsDataPlatform/BEF Release/System-Pipeline@3/.install/event-flow-bus/install/node_modules/serverless/lib/plugins/aws/lib/monitorStack.js:101:26)
From previous event:
    at AwsDeploy.monitorStack (/opt/Jenkins/workspace/EDU-pyxis/AnalyticsDataPlatform/BEF Release/System-Pipeline@3/.install/event-flow-bus/install/node_modules/serverless/lib/plugins/aws/lib/monitorStack.js:30:12)
    at provider.request.then (/opt/Jenkins/workspace/EDU-pyxis/AnalyticsDataPlatform/BEF Release/System-Pipeline@3/.install/event-flow-bus/install/node_modules/serverless/lib/plugins/aws/lib/updateStack.js:86:30)
From previous event:
    at AwsDeploy.update (/opt/Jenkins/workspace/EDU-pyxis/AnalyticsDataPlatform/BEF Release/System-Pipeline@3/.install/event-flow-bus/install/node_modules/serverless/lib/plugins/aws/lib/updateStack.js:86:8)
From previous event:
    at AwsDeploy.BbPromise.bind.then.then (/opt/Jenkins/workspace/EDU-pyxis/AnalyticsDataPlatform/BEF Release/System-Pipeline@3/.install/event-flow-bus/install/node_modules/serverless/lib/plugins/aws/lib/updateStack.js:107:12)
From previous event:
    at AwsDeploy.updateStack (/opt/Jenkins/workspace/EDU-pyxis/AnalyticsDataPlatform/BEF Release/System-Pipeline@3/.install/event-flow-bus/install/node_modules/serverless/lib/plugins/aws/lib/updateStack.js:99:8)
From previous event:
    at deploy:deploy (/opt/Jenkins/workspace/EDU-pyxis/AnalyticsDataPlatform/BEF Release/System-Pipeline@3/.install/event-flow-bus/install/node_modules/serverless/lib/plugins/aws/deploy/index.js:55:10)
    at BbPromise.reduce (/opt/Jenkins/workspace/EDU-pyxis/AnalyticsDataPlatform/BEF Release/System-Pipeline@3/.install/event-flow-bus/install/node_modules/serverless/lib/classes/PluginManager.js:160:50)
    at runCallback (timers.js:666:20)
    at tryOnImmediate (timers.js:639:5)
    at processImmediate [as _immediateCallback] (timers.js:611:5)
From previous event:
    at PluginManager.run (/opt/Jenkins/workspace/EDU-pyxis/AnalyticsDataPlatform/BEF Release/System-Pipeline@3/.install/event-flow-bus/install/node_modules/serverless/lib/classes/PluginManager.js:160:22)
    at Serverless.run (/opt/Jenkins/workspace/EDU-pyxis/AnalyticsDataPlatform/BEF Release/System-Pipeline@3/.install/event-flow-bus/install/node_modules/serverless/lib/Serverless.js:91:31)
    at serverless.init.then (/opt/Jenkins/workspace/EDU-pyxis/AnalyticsDataPlatform/BEF Release/System-Pipeline@3/.install/event-flow-bus/install/node_modules/serverless/bin/serverless:23:50)
 
  Get Support --------------------------------------------
     Docs:          docs.serverless.com
     Bugs:          github.com/serverless/serverless/issues
 
  Your Environment Information -----------------------------
     OS:                 linux
     Node Version:       7.7.2
     Serverless Version: 1.6.0
```

* ***Provider Error messages***:

**Comment by johngwilkinson** [comment] 2017-03-20 19:19
Possible fix: https://github.com/serverless/serverless/compare/master...johngwilkinson:3387-retry-missing-stack-details

Please let me know if I should open a PR for that branch.

Because this is an intermittent issue, I can't offer anything more targeted than this "retry a reasonable number of times" fix.

**Comment by pmuens** [comment] 2017-03-21 07:54
Thanks for reporting and jumping into it @johngwilkinson 

Would love to have the PR with a fix for it. Could you please also include a way to reproduce this bug? Thanks!

**Comment by pmuens** [comment] 2017-04-18 08:36
@johngwilkinson do you know why this happens?

We tried to reproduce this in the past but unfortunately were unsuccessful doing so.

**Comment by johngwilkinson** [comment] 2017-04-18 13:31
This seems to be caused an Amazon bug (described above). This workaround basically protects serverless from that bug. Why exactly aws sometimes returns an incomplete response I don't know. Interestingly, it has been happening less recently, although I believe we still see it from time to time.

**Comment by pmuens** [comment] 2017-04-18 13:48
Thanks for the clarification @johngwilkinson 👍 !

**Comment by pmuens** [comment] 2017-04-19 07:33
Hey @johngwilkinson thanks again for bringing this up.

We're closing this for now. Since it might be something on AWS end and we're not able to reproduce it.

More information can be found here: https://github.com/serverless/serverless/pull/3388#issuecomment-295139195.

**Closed by pmuens** 2017-04-19 07:33 UTC
Labels: kind/bug, status/more-info-needed
