### ISSUE TITLE
Access to provider's SDK in external plugin

### ISSUE THREAD

**Issue by mthenw** [serverless/serverless#1826] opened 2016-08-11 15:37 UTC
##### Feature Request:

Access to provider's SDK in external plugin
##### Benefits:

More powerful plugins. If I want to call AWS SDK from within my plugin I need to setup `aws-sdk` manually. I should be able to get SDK used by core plugins through `this.serverless.getSDK()` so I have credentials already setup.
##### Drawbacks:
- none

**Comment by ac360** [comment] 2016-08-11 15:47
Also see #1529

**Comment by flomotlik** [comment] 2016-08-19 12:05
Yup that makes sense. The easiest way is probably for the plugin to set it directly when its loaded? The problem is that it could be overwritten by other plugins if they set different sdks and the question is which plugin should set them up.

@pmuens @eahefnawy where do you think would be the best place to introduce and set `this.serverless.providerSDK` (imho better than a getter?) ?

**Comment by pmuens** [comment] 2016-08-19 15:41
Yep. I like `this.serverless.providerSDK` as a way to access it (without the need for a getter).

No hard feelings about the place where it should be introduced. Maybe @eahefnawy has some idea here.

**Comment by flomotlik** [comment] 2016-08-22 07:16
Yeah imho the Plugin itself should be setting it somehow. The question is only which plugin specifically. Probably deploy but as its done in separate plugins that could easily be overwritten if its not correctly in place.

**Comment by flomotlik** [comment] 2016-11-05 13:59
This was recently implemented, so closing

**Closed by flomotlik** 2016-11-05 13:59 UTC
Labels: discussion
