### ISSUE TITLE
LogGroup doesn't exist when one name is the part of another

### ISSUE THREAD

**Issue by KKomarov** [serverless/serverless#3240] opened 2017-02-13 15:50 UTC
# This is a (Bug Report)

## Description

For bug reports:
* What went wrong?
I cant deploy this simple config. The problem happens when one function has name that is the part of another name.

* What did you expect should have happened?
Stack created.

* What was the config you used?
```
service: myservice

provider:
  name: aws
  stage: ohmydays
  region: us-east-1
  runtime: python2.7

package:
  individually: true
  include:
    - "*.py"

functions:
  omglol:
    handler: handler.lambda_handler

  omglolanother:
    handler: handler.lambda_handler
```

* What stacktrace or error message from your provider did you see?
![image](https://cloud.githubusercontent.com/assets/14128194/22890080/4bfd7112-f21c-11e6-8cc7-b8bf1596c792.png)

## Additional Data

* ***Serverless Framework Version you're using***: >=1.6.0 or cfLogs: true
* ***Operating System***: Ubuntu

**Comment by orthodoc** [comment] 2017-02-13 20:01
I am getting the same error. I noticed that the CF template that's created under .serverless has the following PolicyStatement related to logs:
(snippet on the permitted actions)
```
"Action": [
                "logs:CreateLogStream",
                "logs:PutLogEvents"
              ]
```
Should this be:

```
"Action": [
               "logs:CreateLogGroup",
                "logs:CreateLogStream",
                "logs:PutLogEvents"
              ]
```

**Comment by pmuens** [comment] 2017-02-14 08:09
Thanks for opening @KKomarov and giving feedback @orthodoc !

/cc @eahefnawy

**Comment by KKomarov** [comment] 2017-02-14 12:05
@orthodoc Downgrading to v1.5.1 helps probably due to unsetted `cfLogs: true`. Seems like this is amazon issue.

**Comment by kuldeeprishi** [comment] 2017-02-14 12:40
is there any workaround for this issue apart from downgrading to v1.5.1

**Comment by geoffdutton** [comment] 2017-02-14 12:59
There's more discussion of this in #2614, it's a confirmed AWS issue.

**Comment by pmuens** [comment] 2017-03-09 12:55
Closing this for now since it's an AWS related issue. Feel free to continue the discussion!

**Closed by pmuens** 2017-03-09 12:55 UTC
Labels: kind/bug

**Comment by sharuzzaman** [comment] 2017-08-30 01:19
Hi,

I tested just now with the gist provided by @bsamuel-ui and it looks like the issue of similar name in LogGroup in Cloudformation has been fixed.

The gist is here: https://gist.github.com/bsamuel-ui/cff4632e5894625bb5361646c57d1c4b

Thanks.

**Comment by pmuens** [comment] 2017-08-30 06:18
Great! Thanks for testing and confirming @sharuzzaman 👍

**Comment by marcfielding1** [comment] 2017-09-22 18:18
I just got this today actually, I've got SignUp/SignIn and it's bugging out but I've never had this before.

**Comment by marcfielding1** [comment] 2017-09-22 18:27
Ok so I tried this loads of times, no joy, then I noticed sls offline was running in another terminal, terminated it - it worked first time.

**Comment by mmacheerpuppy** [comment] 2019-12-17 15:39
This is still a problem for me
