### ISSUE TITLE
Package individually at the function level is broken

### ISSUE THREAD

**Issue by juanjoDiaz** [serverless/serverless#7303] opened 2020-02-08 12:30 UTC
# Bug Report

## Description

Set `package individually` at a function level but not at the service level.
This actually works if I set `package individually` to true at the service level 

1. What happened?

The function was package individually:

```yaml
myFunc:
  package:
    individually: true
    exclude:
      - '**'
    include:
      - 'myFolder/**'

```

However, all the services files are included in the generated bundle.

I expected that only the files in `myFolder` would have been added.

The problem seems to be at https://github.com/serverless/serverless/blob/master/lib/plugins/package/lib/packageService.js#L21

`this.serverless.service.package.include` should be empty since it's not defined at the service level instead of containing all the files in the project. But I can't find where it's being populated.
Or is there any other way to achieve this that I'm missing?

**Comment by medikoo** [comment] 2020-02-11 02:16
@juanjoDiaz thanks for report. `exclude` and `include` settings expect an array. Therefore it should be configured as:

```yaml
myFunc:
  package:
    individually: true
    exclude:
      - '**'
    include:
      - 'myFolder/**'
```

Such configuration errors should be picked in future by schema validation: https://github.com/serverless/serverless/issues/6562

**Comment by juanjoDiaz** [comment] 2020-02-11 06:57
Yeah. My bad when fast typing the example. I fixed it.

The issue is still there.
Package individually at the function level doesn't work.

**Comment by medikoo** [comment] 2020-02-11 23:43
@juanjoDiaz I'm not able to reproduce that, e.g. see this test case: https://github.com/medikoo/test-serverless/tree/489b285381bd83029e07906bc101bfc7d6ca63dd It packages lambda per instructions as expected

**Comment by blairexico** [comment] 2020-07-08 20:25
I am seeing same issue:

```
    forwardIncomingHeaders:
        handler: lambdas/forwardIncomingHeaders.handler
        package:
            individually: true
            exclude:
                - node_modules/**
        lambdaAtEdge:
            - distribution: 'ApiDistribution' # this name is set by the cloudfront plugin
              eventType: 'viewer-response'
        memorySize: 128
        timeout: 5
```

I get just one zip file, and I cant deploy because the file is too big for edge.

An error occurred: ApiDistribution - The function code size is larger than the maximum allowed size for functions that are triggered by a CloudFront event: 5028222 Max allowed: 1048576 Function

**Comment by joker-8989** [comment] 2020-08-28 02:33
I'm having the same issue with the latest 1.80.0 version.
If function-level packaging doesn't work,
Only packaging at the service level.
Configurations with many Lambda deployments will have a significant performance penalty.

**Comment by medikoo** [comment] 2020-08-28 11:57
@joker-8989 can you prepare as simple as possible test case that exposes the issue?

**Comment by stevematdavies** [comment] 2021-02-11 14:38
This is now also an issue at the service level

**Comment by medikoo** [comment] 2021-02-11 14:42
@stevematdavies can you prepare as simple as possible test case that reproduces the issue?

**Comment by stevematdavies** [comment] 2021-02-11 14:46
Our code is a rather involved code and has some private / corporate features so I cant copy it here.
However, the issue is exactly as shown above

In our `serverless.yml `file

we have

```
 package:
    individually: true
    package:
      exclude:
        - ./**
      include:
        - handler.js
```

However, on deploy, all excluded folders are added

**Comment by medikoo** [comment] 2021-02-11 16:56
@stevematdavies you have an error in your configuration. Are you relying on latest version of Framework? Note that latest vesrion will clearly communicate this error with `Configuration warning`

**Comment by medikoo** [comment] 2021-02-12 11:30
I'm going to close this issue, as there's no reproduction case provided, and as I checked the posted examples all works as expected.

**Closed by medikoo** 2021-02-12 11:30 UTC
Labels: question

**Comment by tnraddatz** [comment] 2021-04-16 02:40
`exclude` seems to be completely broken (from my perspective).  If you just use `patterns` instead this should work.

**Comment by chandywerks** [comment] 2021-07-15 16:09
I'm also having this issue. I am simply trying to include a file for a specific function and it does not work as documented.

**Comment by pgrzesik** [comment] 2021-07-16 07:21
Hey @chandywerks - could you please share specific example that is not working? Ideally with reproducible steps so I can try to confirm & debug on my side. Thanks :bow:

**Comment by alejandroch1202** [comment] 2023-11-21 17:57
Still having this issue
