### ISSUE TITLE
excludeDevDependencies  excluding too much

### ISSUE THREAD

**Issue by vanerleo** [serverless/serverless#3987] opened 2017-07-25 10:43 UTC
# This is a Bug Report

## Description

* What went wrong?
using the following `package.json`
```
{
  "name": "api-v1",
  "version": "1.0.0",
  "description": "",
  "main": "index.js",
  "scripts": {
    "test": "echo \"Error: no test specified\" && exit 1"
  },
  "keywords": [],
  "author": "",
  "license": "ISC",
  "dependencies": {
    "bluebird": "^3.5.0",
    "jwt-decode": "^2.2.0",
    "moment": "^2.18.1",
    "uuid": "^3.1.0"
  },
  "devDependencies": {
    "aws-sdk": "^2.84.0",
    "aws-xray-sdk": "^1.1.2",
    "serverless-offline": "^3.15.0",
    "serverless-plugin-tracing": "^1.0.6"
  }
}

```

`moment` is not included in the final package

* What did you expect should have happened?
`moment` is a dependency and should be included in the final package

## Additional Data

* ***Serverless Framework Version you're using***: 1.18.0
* ***Operating System***: Linux, Ubuntu

**Comment by gevorggalstyan** [comment] 2017-07-25 11:47
Was just going to file an issue with the same exact problem.

Here is my package.json

`{
  "name": "my-serverless-api",
  "version": "1.0.0",
  "license": "ISC",
  "devDependencies": {
    "chai": "^4.1.0",
    "eslint": "^4.3.0",
    "eslint-config-google": "^0.9.1",
    "lambda-tester": "^3.0.2",
    "serverless-dynamodb-local": "^0.2.22",
    "serverless-offline": "^3.15.1",
    "serverless-secrets-plugin": "0.0.1"
  },
  "dependencies": {
    "bcrypt": "^1.0.2",
    "bitly": "^4.1.1",
    "jsonwebtoken": "^7.4.1",
    "uuid": "^3.1.0"
  }
}
`

Try to require jsonwebtoken and after deploy AWS Lambda will say 
`
Unable to import module 'functions/auth/login': Error
at Function.Module._resolveFilename (module.js:469:15)
at Function.Module._load (module.js:417:25)
at Module.require (module.js:497:17)
at require (internal/module.js:20:19)
at Object.<anonymous> (/var/task/node_modules/jws/lib/data-stream.js:2:36)
at Module._compile (module.js:570:32)
at Object.Module._extensions..js (module.js:579:10)
at Module.load (module.js:487:32)
at tryModuleLoad (module.js:446:12)
at Function.Module._load (module.js:438:3)`

When changing the package.json to something like this, where there are no dev deps, everything works.

This is a pretty important bug, as your package may become several times bigger than needed, in my case, it was 1.8MB vs 14.9MB.

**Comment by pmuens** [comment] 2017-07-25 13:56
Hey @vanerleo and @gevorggalstyan thanks for opening and commenting!

This seems to be a duplicate of https://github.com/serverless/serverless/issues/3972. I'll close this one for now since we track the progress over there.

You can work around this for now with the help of the `excludeDevDependencies` config parameter. You can find more info about it [here](https://github.com/serverless/serverless/issues/3972#issuecomment-317643149).

**Closed** 2017-07-25 13:57 UTC
