### ISSUE TITLE
Use native CloudFormation EventBridge capabilities

### ISSUE THREAD

**Issue by fredericbarthelet** [serverless/serverless#7301] opened 2020-02-07 15:41 UTC
# Feature Proposal

## Description

Event bridge has recently been integrated in serverless -> https://github.com/serverless/serverless/issues/6363. This PR integrates EventBridge using custom lambda provisionned by the framework since CloudFormation did not support Event Bridge at that time.

Today, and since october 2019, AWS CloudFormation now supports templating EventBridge service configuration : https://aws.amazon.com/fr/about-aws/whats-new/2019/10/amazon-eventbridge-supports-aws-cloudformation/

Would it be better to switch to using native Cloudformation templating ? Would be happy to help with a PR on that matter if deemed appropriate :)

Similar or dependent issues:

- #6363

**Comment by rdsedmundo** [comment] 2020-02-08 16:51
Duplicate of #7148.

**Closed** 2020-02-11 00:34 UTC
Labels: duplicate
