### ISSUE TITLE
$ref in resources can't handle variable

### ISSUE THREAD

**Issue by pmuilu** [serverless/serverless#2113] opened 2016-09-13 09:45 UTC
Version: 1.0rc1

	resources:
	  Resources:
	    $ref: resources/${opt:stage, self:custom.default-stage}/main.json # you can use JSON-REF to ref other JSON files

Results:

Serverless Error ---------------------------------------
 
     Template format error: [/Resources/$ref] resource definition
     is malformed

**Comment by eahefnawy** [comment] 2016-09-14 08:58
duplicate of #1665

> this is intentional because we want to also support populating variables that are defined in your CF templates. If we do it the other way around, you'll be able to have the file path as a variable, but you will not be able to reference variables inside your template. So we had to make a tiny compromise 👼

In other words, we have to choose whether to populate variable or resolve $ref first. We chose to resolve $ref first so that you can use variables in any ref-ed file. Unfortunately that means ref paths can't contain variables

**Closed** 2016-09-14 08:58 UTC

**Comment by pmuilu** [comment] 2016-09-14 10:38
This is actually much better and works like a charm! Great.
