### ISSUE TITLE
serverless should be support for apple m1 chip

### ISSUE THREAD

**Issue by bittu664** [serverless/serverless#9444] opened 2021-05-08 16:43 UTC
**Hello serverless community when i am trying to install serverless from this command in my MacBook air:-**

``` curl -o- -L https://slss.io/install | bash ```

Then I got this error!

Installing Serverless!

\033[31m Sorry, there's no serverless binary installer available for arm64 architecture. Please open request for it at https://github.com/serverless/serverless/issues.\033

So I think that you have to build your binary for this m1 chip.

**Comment by pgrzesik** [comment] 2021-05-09 18:43
Hello @bittu664 - thanks for reporting, I will close it as a duplicate of https://github.com/serverless/serverless/issues/8696

**Closed by pgrzesik** 2021-05-09 18:43 UTC
