### ISSUE TITLE
Unable to remove serverless stack that doesn't use API gateway...

### ISSUE THREAD

**Issue by AndrewFarley** [serverless/serverless#4282] opened 2017-09-19 00:08 UTC
Problem: 

- Step 1: Deploy a (simple?) stack that has no events from API Gateway, and it will not create an API Gateway as part of the CloudFormation stack (because it doesn't need it).  Eg: use an event source, such as S3.
- Step 2: Try to `serverless remove` and it reports an error that says ` Resource ApiGatewayRestApi does not exist for stack stackname-goes-here`.

Notes:

There's nothing wrong with the CloudFormation in this instance... I can jump onto the AWS Console and grab the CF and click **Delete Stack** and it deletes the stack perfectly.  I heard that in some of the recent releases of Serverless you added various pre-flight checks to save from a failing CloudFormation change.  But in the case of removal, you probably want to skip these pre-flight checks, and merely check if the name of the CloudFormation stack exists, and if it does, just remove it.

**Comment by pmuens** [comment] 2017-09-19 06:16
Hey @AndrewFarley thanks for opening 👍

Not sure if I'm following. So you've created a Serverless service with an event source other than API Gateway and if you want to remove it you get an error that the `ApiGatewayRestApi` resource does not exist?

Could you provide a step-by-step walkthrough so that we can reproduce this issue on our end? Thanks in advance!

**Comment by araines** [comment] 2017-10-02 14:45
I've just hit this same issue, using Serverless 1.23.0.

Steps to reproduce:
* Create a serverless service which has a single function which is triggered via SNS
* Deploy the service
* Attempt to remove the service

Here is an excerpt from the serverless.yml I was using which describes all the functions:
```
functions:
  add:
    description: Add some media to the gallery
    handler: handler.add
    events:
      - sns:
          topicName: ${self:custom.snsTopic}
          displayName: Add media to gallery
```

And the error message:
```
Serverless: Removing usage plan association...

  Serverless Error ---------------------------------------

  Resource ApiGatewayRestApi does not exist for stack gallery-dev

  Get Support --------------------------------------------
     Docs:          docs.serverless.com
     Bugs:          github.com/serverless/serverless/issues
     Forums:        forum.serverless.com
     Chat:          gitter.im/serverless/serverless

  Your Environment Information -----------------------------
     OS:                     darwin
     Node Version:           6.11.3
     Serverless Version:     1.23.0
```

**Comment by AndrewFarley** [comment] 2017-10-02 19:21
So, I sat down and tried to repeat this because I've seen this three times now but I can't get a repeatable workflow.  Fresh deployments don't have this problem... I tried numerous times I can't get it to repeat.  It seems to happen to stacks that have been around a while.  My workflow with serverless is usually that I deploy a stack with a HTTP endpoint, and then remove that HTTP endpoint, and then eventually remove that stack.  That'd be my best guess.  I do use that usage workflow a bit for initial testing of some of my stacks.

Clearly I'm not the only one with this problem, so lets keep this bug open and if I (or someone else) figures out a way to repeat this bug reliably so this can be fixed, they can find and report it here.

**Comment by horike37** [comment] 2017-10-03 00:04
Hey, @AndrewFarley. Thank you for the reporting and explanation here :thumbsup:
Could you share your serverless.yml you are using so that we can reproduce on our end?

**Comment by mataide** [comment] 2018-03-04 15:03
I got this problem too.

```
 Serverless Error ---------------------------------------            
                                                                     
 Resource ApiGatewayRestApi does not exist for stack proak-api-dev   
                                                                     
 Get Support --------------------------------------------            
    Docs:          docs.serverless.com                               
    Bugs:          github.com/serverless/serverless/issues           
    Forums:        forum.serverless.com                              
    Chat:          gitter.im/serverless/serverless                   
                                                                     
 Your Environment Information -----------------------------          
    OS:                     win32                                    
    Node Version:           6.10.0                                   
    Serverless Version:     1.26.1                                   
```
Serverless: 1.26.1
```
frameworkVersion: ">=1.1.0 <2.0.0"

provider:
   name: aws
   runtime: nodejs6.10
   stage: ${opt:stage, self:custom.defaultStage}
   region: us-east-2 # Overwrite the default region used. Default is us-east-1
   profile: ${self:custom.profiles.${self:provider.stage}}
   apiKeys:
     - ${self:provider.stage}-api-key
   usagePlan:
     quota:
       limit: 5000
       offset: 0
       period: DAY
     throttle:
       burstLimit: 200
       rateLimit: 100
   environment:
     STAGE: ${self:provider.stage}
   iamRoleStatements:
     - Effect: Allow
       Action:
          - dynamodb:DescribeTable
          - dynamodb:Query
          - dynamodb:Scan
          - dynamodb:GetItem
          - dynamodb:PutItem
          - dynamodb:UpdateItem
          - dynamodb:DeleteItem
          - dynamodb:DescribeStream
          - dynamodb:GetRecords
          - dynamodb:GetShardIterator
          - dynamodb:ListStreams
       Resource: "arn:aws:dynamodb:${self:provider.region}:*:*"
     - Effect: Allow
       Action:
         - ec2:CreateNetworkInterface
         - ec2:DescribeNetworkInterfaces
         - ec2:DeleteNetworkInterface
       Resource: '*'
     - Effect: Allow
       Action:
          - s3:ListBucket
       Resource: "arn:aws:s3:::xxxxxx-team"
     - Effect: Allow
       Action:
          - s3:PutObject
          - s3:DeleteObject
          - s3:GetObject
          - s3:PutObjectAcl
       Resource: "arn:aws:s3:::xxxxx-team/*"
     - Effect: Allow
       Action:
         - kms:Decrypt
         - kms:Encrypt
         - kms:DescribeKey
         - kms:GetKeyPolicy
       Resource: "arn:aws:kms:${self:provider.region}:*:*"

plugins:
  - serverless-plugin-optimize
  - serverless-offline
  - serverless-plugin-split-stacks
#  - serverless-dynamodb-autoscaling

custom:
  optimize:
    includePaths: ['api/lib/gameOptions.yml']
  dynamodbProvisions:
    dev: 1
    prod: 5
  streamAccounts:
    dev: xxxxxxxx
    prod: xxxxxxxx
  individually:
    dev: false
    prod: true
  enableScheduleEvents:
    dev: true
    prod: true
  defaultStage: dev
  profiles:
    dev: devProfile
    prod: prodProfile
  serverless-offline:
    babelOptions:
      presets: ["es2015"]
#  capacities:
#      - table: BetaDynamoDbTable  # DynamoDB Resource
#        read:
#          minimum: 3        # Minimum read capacity
#          maximum: 50     # Maximum read capacity
#          usage: 0.5       # Targeted usage percentage
#        write:
#          minimum: 3       # Minimum write capacity
#          maximum: 50      # Maximum write capacity
#          usage: 0.5        # Targeted usage percentage


package:
  excludeDevDependencies: true
  individually: ${self:custom.individually.${self:provider.stage}}
```

**Comment by ozbillwang** [comment] 2018-04-29 12:44
I got same issue, when use serverless as a replacement of cloudformation (yes, I know I can write separate cloudformation yml template directly, but I'd like to have same way to deploy the resources in this project)

So for any serverless.yml without part of `functions:`, when `sls deploy` , it works and all resources in part of `resources:` are created properly. 

But when try to `sls remove`, got the same error

    Resource ApiGatewayRestApi does not exist for stack stackname-goes-here.

**Comment by ajeya** [comment] 2018-06-22 00:57
In my case, I solved this problem, but removing `apiKeys` declaration under `provider`, redeploying the stack and then running `sls remove`. Hope this helps.

**Comment by ozbillwang** [comment] 2018-06-22 01:50
@ajeya 

I didn't have `apiKeys` defined under `provider`, but still has the issue.

**Comment by pmuens** [comment] 2019-02-13 12:28
Closing this issue since it's quite old and there are some solutions in the issue thread.

**Closed by pmuens** 2019-02-13 12:28 UTC
Labels: bug, cat/deployment, help wanted, pr/more-info-needed

**Comment by SteveRoland** [comment] 2019-02-19 01:28
> In my case, I have not http events but I had declared `apiKeys` under `provider`. I solved this problem, by removing the `apiKeys` declaration and then running `sls remove`.

Thank you!

**Comment by christophgysin** [comment] 2019-06-07 12:36
I managed to run into this when using an [external RestApi resource](https://serverless.com/framework/docs/providers/aws/events/apigateway/#share-api-gateway-and-api-resources) **and** defining an API key:
```yaml
service: service-a

provider:
  apiGateway:
    restApiId: xxxxxxxxxx
  apiKeys:
    - myApiKey
```
Deployment succeeds, but removal fails because the code expects the ApiGatewayRestApi resource to be present in the serverless stack.

@pmuens Could we please reopen this?

**Comment by jollifft** [comment] 2019-06-12 19:03
Just ran into the same issue as @christophgysin

**Comment by hoang-innomizetech** [comment] 2019-09-09 07:09
I  got the same issue as @christophgysin, then if I comment apiKeys in the provider configuration, then I am able to remove stack.

**Comment by beanaroo** [comment] 2019-10-06 12:59
Can confirm the issue is still present

**Comment by hoang-innomizetech** [comment] 2019-10-07 04:06
I can confirm that this issue still persists when using the latest version

Framework Core: 1.53.0
Plugin: 3.1.1
SDK: 2.1.1
Components Core: 1.1.1
Components CLI: 1.2.3

**Comment by iamdavidmartin** [comment] 2019-11-25 18:50
I only use API keys and lambda's. I'm not a configuring an API gateway. This is painful because it can take minutes to hours to remove the stack from AWS so getting this right involves hours of sitting around waiting for stack removals. 

  Serverless Error ---------------------------------------

  Resource ApiGatewayRestApi does not exist for stack mystack

  Get Support --------------------------------------------
     Docs:          docs.serverless.com
     Bugs:          github.com/serverless/serverless/issues
     Issues:        forum.serverless.com

  Your Environment Information ---------------------------
     Operating System:          darwin
     Node Version:              12.13.1
     Framework Version:         1.58.0
     Plugin Version:            3.2.5
     SDK Version:               2.2.1
     Components Core Version:   1.1.2
     Components CLI Version:    1.4.0

**Comment by vyusuf** [comment] 2019-12-02 09:19
I have also encountered this issue and can say this is clearly still an issue with the use of `apiKeys` in the serverless (yaml) config file. @pmuens would you mind reopening this issue so it can be fixed? Thanks

**Comment by gauravbhatt13** [comment] 2019-12-08 02:23
I have faced same issue with apiKeys in my serverless yaml and on commenting it I can get sls remove working. It is indeed an issue and my sls version is 1.57.0

**Comment by PatrykMilewski** [comment] 2020-01-20 14:30
I have the same issue with apiKeys blocking stack removal.
