### ISSUE TITLE
After deploying single function, serverless stops sending logs to axiom

### ISSUE THREAD

**Issue by mishabhi** [serverless/serverless#12875] opened 2024-10-20 18:21 UTC
### Issue description

I was testing the feature of disabling logs for a particular function using the property "disableLogs: true". After my testing I set it as true again but it seemed serverless never resumed sending logs to axiom. Moreover, now any function deployed alone (they dont even have disableLogs property at all) stops sending logs to axiom. Additionally, the logs are properly generated on cloudwatch.

I am using severless 4.4.2 version. I tried running full deployment to see if it might work by any chance but no success there as well. All the ones which were never touched are still working.

### Context

V4.4.2

**Comment by czubocha** [comment] 2024-10-21 13:05
Hey @mishabhi, thanks for reporting this.
I was able to reproduce the behaviour you're seeing.
>  Moreover, now any function deployed alone (they dont even have disableLogs property at all) stops sending logs to axiom

There is an issue when using `deploy function` command. This will be fixed in the next release. 
>  I tried running full deployment to see if it might work by any chance but no success there as well.

This is most likely due to how CloudFormation works. When you integrated your functions with a full deployment, the integrated state was saved in CloudFormation. However, when you update using `deploy function`, it bypasses CloudFormation, so it doesn’t attempt to re-integrate your function since it’s already marked as integrated in its state. We mention that in [deploy function docs](https://www.serverless.com/framework/docs/providers/aws/cli-reference/deploy-function):
> this puts your function in an inconsistent state that is out of sync with your CloudFormation stack. Use this for faster development cycles and not production deployments

But after the fix is released, you'll be able to re-integrate your function using the `deploy function` command.

**Comment by mishabhi** [comment] 2024-10-21 13:34
@czubocha Thanks for sharing this. Any timeline when can I anticipate this issue fixed?

**Comment by czubocha** [comment] 2024-10-21 13:36
@mishabhi We’re planning to include the fix in today’s release

**Comment by czubocha** [comment] 2024-10-22 12:24
Hey @mishabhi, the fix has been released in version [4.4.7](https://github.com/serverless/serverless/releases/tag/v4.4.7). Feel free to let us know if you encounter any further issues.

**Closed by czubocha** 2024-10-22 12:24 UTC
Labels: V4

**Comment by mishabhi** [comment] 2024-10-22 21:03
@czubocha Thanks for the update. I just tried and it did not help. I lost couple of my more functions. Just so you know, I am using framework version 4.4.2. If I change it to anything else, it starts breaking with error for some environment variables which are already present.
