### ISSUE TITLE
Function timeout warning even when HTTP API endpoint is not configured

### ISSUE THREAD

**Issue by AntonBazhal** [serverless/serverless#7487] opened 2020-03-19 13:59 UTC
# Bug Report

## Description

1. What did you do?
Updated to `serverless@1.66.0`

1. What happened?
A lot of warning messages `Function timeout setting (30) is greater than maximum allowed timeout for HTTP API endpoint (29s). This may introduce situation where endpoint times out for succesful lambda invocation.` in the console output.

1. What should've happened?
No warning messages are expected since functions do not have HTTP API endpoint configured.

1. What's the content of your `serverless.yml` file?
```yaml
functions:
  createFoo:
    handler: src/handlers/foo-create.handler
    memorySize: 1536
    timeout: 30
```

1. What's the output you get when you use the `SLS_DEBUG=*` environment variable (e.g. `SLS_DEBUG=* serverless deploy`)
Everything looks as expected

This check was introduced in #7420, but it does not account for the fact that not all the lambda functions have HTTP API endpoint configured.
https://github.com/serverless/serverless/pull/7420/files#diff-d50db32c24bd404693e30120025457c1R403

**Comment by medikoo** [comment] 2020-03-19 20:42
Closing as duplicate of #7440 

It's already fixed in master and will be released today

**Closed by medikoo** 2020-03-19 20:42 UTC
Labels: duplicate
