### ISSUE TITLE
exclude devDependencies not working after 1.35.0 on windows, node v8.11.3, npm 5.6.0

### ISSUE THREAD

**Issue by mikehanney** [serverless/serverless#5745] opened 2019-01-24 02:23 UTC
# exclude devDependencies not working after 1.35.0 on windows, node v8.11.3, npm 5.6.0

## Description

Exclude devDependencies does not work in any release after 1.35.0 on windows 10 with node v8.11.3, npm 5.6.0.

I have dozens of projects, all produce small .zips using 1.34.1 , all produce huge .zips using  1.35.0 through 1.36.0.

1.33.2 - working
1.34.0 - working
1.34.1 - working
1.35.0 through 1.36.0 not working 

Similar or dependent issues:
* https://github.com/serverless/serverless/issues/4830

**Comment by pmuens** [comment] 2019-01-24 09:22
Thanks for opening @mikehanney 👍

Could be related to https://github.com/serverless/serverless/pull/5574

**Comment by dschep** [comment] 2019-01-24 14:32
Might be a duplicate of #5609

**Comment by exoego** [comment] 2019-01-25 22:34
@mikehanney 
To reproduce issue, could you provide the config file facing this issue?

**Comment by ImreC** [comment] 2019-02-05 09:33
@exoego 
Size at 1.34 = 26.25 mb, size at 1.36 = 44.23 mb
package.json 
```
{
  "name": "frontend",
  "version": "1.0.0",
  "description": "",
  "main": "index.js",
  "scripts": {
    "deploy": "nuxt build && sls deploy",
    "build": "nuxt build",
    "start": "cross-env LOCAL=true node index.js",
    "dev": "nuxt",
    "generate": "nuxt generate",
    "lint": "eslint --ext .js,.vue --ignore-path .gitignore .",
    "precommit": "npm run lint"
  },
  "keywords": [],
  "author": "",
  "license": "ISC",
  "dependencies": {
    "axios": "^0.18.0",
    "express": "^4.16.4",
    "nuxt": "^2.4.2",
    "nuxt-purgecss": "^0.2.1",
    "serve-favicon": "^2.5.0",
    "serverless-apigw-binary": "^0.4.4",
    "serverless-content-encoding": "^1.1.0",
    "serverless-http": "^1.9.0"
  },
  "devDependencies": {
    "autoprefixer": "^8.6.4",
    "babel-eslint": "^8.2.1",
    "cross-env": "^5.2.0",
    "eslint": "^5.0.1",
    "eslint-config-prettier": "^3.1.0",
    "eslint-loader": "^2.0.0",
    "eslint-plugin-prettier": "2.6.2",
    "eslint-plugin-vue": "^4.0.0",
    "nodemon": "^1.11.0",
    "prettier": "1.14.3",
    "serverless-domain-manager": "^2.6.13",
    "tailwindcss": "~0.6.6",
    "terser": "^3.14.1"
  }
}
```

config 
```
service: frontend

package:
  individually: true

provider:
  name: aws
  runtime: nodejs8.10
  stage: ${self:custom.env.NODE_ENV}
  region: eu-central-1
  environment:
    NODE_ENV: ${self:custom.env.NODE_ENV}

functions:
  nuxt:
    handler: index.nuxt
    events:
      - http: ANY /
      - http: ANY /{proxy+}

plugins:
  - serverless-apigw-binary
  - serverless-content-encoding

custom:
  env: ${file(env.json)}
  apigwBinary:
    types:
      - '*/*'
```

**Comment by deltafactory** [comment] 2019-02-06 14:59
_Cross posting comment from #5396 though it seems this issue report is a closer match to my environment:_

I haven't found the exact version where the issue began, but I have found one source of the issue for **Windows** users.

* The npm ls output returns the OS path separator, \
* globby's file list uses the path separator /, regardless of OS

The patterns generated for exclusion don't match and therefore aren't excluded.

Related? [sindresorhus/globby#84](https://github.com/sindresorhus/globby/issues/84)

**Comment by dschep** [comment] 2019-02-07 18:12
Hey @mikehanney @deltafactory, could you test that my pr works for you too?
```npm i -g serverless/serverless#sls-5745```

**Comment by ImreC** [comment] 2019-02-08 13:38
@dschep I know I wasn't on the list but the PR works. Good job!

**Comment by dschep** [comment] 2019-02-08 14:02
Thanks @ImreC !!

**Comment by deltafactory** [comment] 2019-02-08 14:24
This fixes my issue. Good work chasing it down to nanomatch. Curious to know when that was introduced but nbd.

The contents of node_modules/.bin contains a number of <bin>.cmd files which should have also been removed. This would be a Windows-specific artifact. It has minimal impact on payload size but would be great to address in a future release.

**Comment by tobilg** [comment] 2019-02-08 14:25
@dschep Any chance on an ETA of the PR in a Serverless version? Thanks for your work chasing it down!

**Comment by dschep** [comment] 2019-02-08 15:06
@deltafactory nanomatch was pulled in for performance reasons in 1.35. 

@tobilg. just merged. @pmuens @eahefnawy, when should we push this change out to npm?

**Closed** 2019-02-08 15:06 UTC
Labels: bug, bug/confirmed, cat/packaging

**Comment by yanfeng** [comment] 2019-02-21 04:52
@dschep Exclude devDependencies does not work for me, I'm on Mac and I'm using serverless 1.38.0 with node v10.14.1 and npm 6.8.0.
