### ISSUE TITLE
Provisioned Concurrency Does Not Work As Described

### ISSUE THREAD

**Issue by AndrewBarba** [serverless/serverless#7059] opened 2019-12-05 16:18 UTC
# Bug Report

Provisioned Concurrency was recently added in Serverless v1.59 and described in detail in this blog post: https://serverless.com/blog/aws-lambda-provisioned-concurrency/

The blog post makes the claim that enabling provisioned concurrency is as easy as:

```
functions:
  hello:
    handler: handler.hello
      events:
        - http:
            path: /hello
            method: get
    provisionedConcurrency: 5
```

This is not true.

What this configuration will do is assign provisioned concurrency to the version number that was deployed, but API Gateway will continue invoking the Lambda with the $LATEST alias (no version). What effectively ends up happening is every deploy keeps assigning provisioned concurrency to each new version and never actually utilizes it. If a developer does not use any version pruning they will quickly rack up an expensive bill paying for new provisioned capacity on each version, and potentially worse, eventually exhaust their reserved (or unreserved) concurrency on their AWS account.

I think this is a critical issue and needs to, at the very least, be addressed in the blog post. Without some form of version cleanup or aliasing I don't think there's much Serverless can do to make this work in a simple configuration like that.

**Comment by medikoo** [comment] 2019-12-05 16:37
@AndrewBarba great thanks for reporting that issue

We will shortly (hopefully tomorrow) publish an update that fix the behavior in a framework (to make blog post accurate).

**Comment by AndrewBarba** [comment] 2019-12-05 16:51
Thank you really appreciate it

**Comment by AndrewBarba** [comment] 2019-12-05 16:52
@medikoo Would the fix you guys are making need to be applied/supported on all event types? Example, the API for specifying an alias/version for APIG is different than the api for ALB

**Comment by medikoo** [comment] 2019-12-05 16:57
Current idea is to create an alias `latest` (or similar) onto which provisioned concurrency will be setup, and ensure that APIGW endpoints will run against that.

If you have any better proposal, we'll definitely open to consider, any help is appreciated.

**Comment by AndrewBarba** [comment] 2019-12-05 17:14
Definitely sounds right to me.

**Comment by shaheer-k** [comment] 2019-12-09 13:31
The issue still seems to be there with the new version (1.59.3). Every deployment is creating additional provisioned concurrenies. I have set versionFunctions: false.

**Comment by medikoo** [comment] 2019-12-09 13:59
> Every deployment is creating additional provisioned concurrenies. I have set versionFunctions: false.

@shaheer-k This definitely should not be the case (and it isn't as I was testing, e.g. on example of this simple service: https://github.com/medikoo/test-serverless/tree/lambda-provisioned-concurrency). If it happens for you, can share the config with which I can reproduce that?

**Comment by shaheer-k** [comment] 2019-12-10 14:26
@medikoo  My obervations are following (severless version: 1.59.3)

1. It is not working on existing stack as its creating new concurrency for each deployment.
2. On a new stack:
    a. It works for the first time
    b. If I modify the provisioned concurrency (form 5 to 6) then cloud formation update failing 
         (UPDATE_FAILED:	Internal Failure)
    c. If I change the concurrency number back to 5, then cloud formation update is performed successfully, but no concurrencies are created.

These issues making it really hard to use the provisioned concurrency in serverless

**Comment by medikoo** [comment] 2019-12-10 15:02
> 1. It is not working on existing stack as its creating new concurrency for each deployment.

- v1.59.3 won't delete provisioned concurrency configuration for versions published with v1.59.0-2
- v1.59.3 on first deploy will introduce a new special and only version on which provisioned configuration is configured (it's definitely not the case that with each following deploy you'd have new versions created)

>   b. If I modify the provisioned concurrency (form 5 to 6) then cloud formation update failing 
         (UPDATE_FAILED:	Internal Failure)

This is the issue on AWS side (note `Internal Failure` comes from CloudFormation stack update, you can also see it in AWS console). We've communicated that issue to AWS, still we have no response on that so far.

I'm clarifying with AWS, the best way to handle that, if going through CloudFormation will be communicated as not stable (for prolonged period), we'll probably reconfigure our support to go through custom resources.

**Comment by dkobia** [comment] 2019-12-10 20:57
Definitely some issues. Subsequent deploys leave the provisioned concurrency configuration attached to the special version that is not $LATEST as @medikoo says above.

Also to get this to work with an existing lambda, I had to delete all the versions then set versionFunctions to false. You can use this handy script if you're having issues with that: https://gist.github.com/tobywf/6eb494f4b46cef367540074512161334

**Comment by medikoo** [comment] 2019-12-10 21:01
> Subsequent deploys leave the provisioned concurrency configuration attached to the special version that is not $LATEST

Yes, that's the other issue, we're looking into. Unfortunately this makes it not reliable for setup that involves API Gateway.

**Comment by RogerVFbr** [comment] 2019-12-11 18:17
Problem seems to persist. Any ideas if a fix is underway? This is very important for our project. Provisioned concurrency still seems to be point to a function version instead of $LATEST. "versionFunctions" has been set to "false" and alternative versions have been cleaned via script. However running "sls deploy" with some "provisionedConcurrency" value attached to the function declaration creates an alternative function version and points the provisioned concurrency to it. Redeploying the project does not seem to affect the situation. Is it possible that the version stated is equivalent to $LATEST, therefore it would be working? Can anybody please show a way to test if the invocation of latest is making use of the provisioned concurrency with this configuration?

![Anotação 2019-12-11 151441](https://user-images.githubusercontent.com/29904392/70648034-0157f580-1c29-11ea-951c-6e47112381df.png)


![Anotação 2019-12-11 150936](https://user-images.githubusercontent.com/29904392/70647756-72e37400-1c28-11ea-93af-d7ce51960fb0.png)

![Anotação 2019-12-11 150911](https://user-images.githubusercontent.com/29904392/70647766-7aa31880-1c28-11ea-88fb-53e00a375e6a.png)

**Comment by jplock** [comment] 2019-12-11 18:37
@RogerVFbr i went back to using https://github.com/AntonBazhal/serverless-plugin-lambda-warmup until the provisioned currency issues have been resolved

**Comment by medikoo** [comment] 2019-12-12 07:14
I'll reopen until we have all issues mentioned here solved.

**Comment by RogerVFbr** [comment] 2019-12-12 20:51
@jplock Hi, thank you for your recommendation. This and other similar solutions seem to assure one constantly warmed up instance. Provisioned concurrency seems to be a more advanced solution, though. According to my research AWS SAM already implements an automated IaC solution on it’s configuration YAML. This feature totally brings Lambda usage to a next level, it would be nice to see Serverless provide a proper solution asap.

> @RogerVFbr i went back to using https://github.com/AntonBazhal/serverless-plugin-lambda-warmup until the provisioned currency issues have been resolved

**Comment by vavarodrigues** [comment] 2019-12-20 12:43
Now worked!
![Screen Shot 2019-12-20 at 09 40 44](https://user-images.githubusercontent.com/5587681/71255523-de0a0600-230c-11ea-8263-52f504ac89d9.png)

version sls:
![Screen Shot 2019-12-20 at 09 42 03](https://user-images.githubusercontent.com/5587681/71255578-07c32d00-230d-11ea-8b9d-e41f22868961.png)

**Comment by medikoo** [comment] 2019-12-20 12:45
@vavarodrigues it's still not really fixed, but it should be shortly with v1.60.2, stay tuned.

**Comment by vavarodrigues** [comment] 2019-12-20 12:54
@medikoo tks!

**Comment by medikoo** [comment] 2019-12-23 13:00
All issues (on framework side) should be fixed now. Published as v1.60.2

**Closed by medikoo** 2019-12-23 13:00 UTC
Labels: bug, cat/lambda

**Comment by pgill** [comment] 2020-01-30 02:04
Framework Core: 1.62.0
Plugin: 3.3.0
SDK: 2.3.0
Components Core: 1.1.2
Components CLI: 1.4.0

Following this: https://serverless.com/blog/aws-lambda-provisioned-concurrency/ and not seeing any provisioned concurrency being set on my function after I deploy.
```
auth_test:
    handler: src/services/auth.test
    events:
      - http:
          path: v1/auth/test
          method: get
    provisionedConcurrency: 2
```

I have versioning turned off: `versionFunctions: false`

It seems like no alias is being created after I deploy: https://www.dropbox.com/s/9iq2xgbh0yv3ukf/Screenshot%202020-01-29%2017.58.26.png?dl=0

Any ideas on what the problem may be here?

**Comment by medikoo** [comment] 2020-01-30 06:34
@pgill it's hard to say anything from what you provide.

Can you prepare a minimal case (which doesn't involve any plugins), post full content of its `serverless.yml` and command that you're using for deployment.

**Comment by peterlundberg** [comment] 2020-02-03 09:56
In AWS Provisioned Concurrency can be enabled for a specific Lambda function version or alias, so without `versionFunctions` it will likely not work.

**Comment by medikoo** [comment] 2020-02-10 01:21
@peterlundberg it works with and without `versionFunctions`. In both cases version is created (as it's needed for provisioned concurrency). Difference is that when `versionFunctions` option is on, stale versions are not removed

**Comment by jgcoding** [comment] 2020-03-25 19:29
Are there nuances to consider when the function is connecting with a database?  (not in a VPC).

My specs:
Framework Core: 1.67.0
Plugin: 3.6.0
SDK: 2.3.0
Components: 2.22.3
Nodejs 10.x



Excerpt of my serverless.yml
`service:
  name: my-project

frameworkVersion: ">=1.0.0 <2.0.0"

plugins:
  - serverless-offline
  - serverless-prune-plugin
custom:
  prune:
    automatic: true
    number: 5
  bucket: my-project-${self:provider.stage}-modules
  branch: "dev" #this allows my private branch to use the dev database
  cb_store: ${ssm:/dp_api_store_${self:custom.branch}~true}
  auth_config:
    name: authorize
    resultTtlInSeconds: 0
    identitySource: method.request.header.Authorization
    type: token

provider:
  name: aws
  runtime: nodejs10.x
  role: arn:aws:iam::xxx:role/lambda_basic_execution
  stage: ${opt:stage, 'My_private_repo'} # Set the default stage used. Default is dev
  region: ${opt:region, 'us-east-1'} # Overwrite the default region used. Default is us-east-1
  stackName: my-project-api-${self:provider.stage} # Use a custom name for the CloudFormation stack
  apiName: My Project API (${self:provider.stage}) # Use a custom name for the API Gateway API
  environment:
    BRANCH: ${self:custom.branch, ${self:provider.stage}}
    STORE_CONFIG: ${self:custom.cb_store}
    AUTH_CLIENT_PUBLIC_KEY: ${ssm:/dp_api_${self:custom.branch}_public_key~true}
    LAMBDA_STAGE_PREFIX: my-project-${self:provider.stage}
logs:
  restApi: # Optional configuration which specifies if API Gateway logs are used. This can either be set to true to use defaults, or configured via subproperties.
    executionLogging: true # Optional configuration which enables or disables execution logging. Defaults to true.
    level: INFO # Optional configuration which specifies the log level to use for execution logging. May be set to either INFO or ERROR.
    fullExecutionData: true # Optional configuration which specifies whether or not to log full requests/responses for execution logging. Defaults to true.
    role: arn:aws:iam::xxx:role/serverlessApiGatewayCloudWatchRole
versionFunctions: false
functions:
  authorize:
    handler: auth.authorize
    cors:
      origins:
        - "*"
      headers:
        - Content-Type
        - X-Amz-Date
        - Authorization
        - X-Api-Key
        - X-Amz-Security-Token
      allowCredentials: false
  order_search:
    handler: order/search.handler
    events:
      - http:
          path: screen/search
          method: get
          cors:
            origins:
              - "*"
            headers:
              - Content-Type
              - X-Amz-Date
              - Authorization
              - X-Api-Key
              - X-Amz-Security-Token
            allowCredentials: false
          request:
            parameters:
              limit: false
              offset: false              
              start_date: false
              end_date: false
              search_term: false
          authorizer: ${self:custom.auth_config}
    provisionedConcurrency: 2
  order_detail:
    handler: order/detail.handler
    events:
      - http:
          path: screen/detail/{order_id}
          method: get
          cors:
            origins:
              - "*"
            headers:
              - Content-Type
              - X-Amz-Date
              - Authorization
              - X-Api-Key
              - X-Amz-Security-Token
            allowCredentials: false
          request:
            parameters:
              paths:
                order_id: true
          authorizer: ${self:custom.auth_config}
    provisionedConcurrency: 2
resources:
  Resources:
    # This response is needed for custom authorizer failures cors support ¯\_(ツ)_/¯
    GatewayResponse:
      Type: "AWS::ApiGateway::GatewayResponse"
      Properties:
        ResponseParameters:
          gatewayresponse.header.Access-Control-Allow-Origin: "'*'"
          gatewayresponse.header.Access-Control-Allow-Headers: "'*'"
        ResponseType: EXPIRED_TOKEN
        RestApiId:
          Ref: "ApiGatewayRestApi"
        StatusCode: "401"
    AuthFailureGatewayResponse:
      Type: "AWS::ApiGateway::GatewayResponse"
      Properties:
        ResponseParameters:
          gatewayresponse.header.Access-Control-Allow-Origin: "'*'"
          gatewayresponse.header.Access-Control-Allow-Headers: "'*'"
        ResponseType: UNAUTHORIZED
        RestApiId:
          Ref: "ApiGatewayRestApi"
        StatusCode: "401"
`

**Comment by karocksjoelee** [comment] 2020-04-28 03:53
hey , I am still facing this issue : 
I updated the global package to latest , but it still not showing provisioned concurrency config in my Lambda console. 


Framework Core: 1.68.0
Plugin: 3.6.8
SDK: 2.3.0
Components: 2.30.2

**Comment by medikoo** [comment] 2020-04-28 11:16
> I updated the global package to latest , but it still not showing provisioned concurrency config in my Lambda console.

Are you sure you're inspecting `provisioned` alias?

**Comment by karocksjoelee** [comment] 2020-04-28 11:42
@medikoo I am using alias to separate my build environment . So I didn't add `--alias provisioned` while deploying , do you mean this affects ? 

Is there anyway that I can using my own alias and `provisioned` at same time ? 
`sls deploy --stage dev --alias dev` This is my currently deploy cmd. 

`sls deploy --alias prod` as Production deployment.

**Comment by medikoo** [comment] 2020-04-28 12:36
> So I didn't add --alias provisioned while deploying , do you mean this affects ?

`provisioned` alias is configured by Framework automatically, note that provisioned concurrency can only be set on _alias_ (and it won't work for `$LATEST`)

Therefore to inspect provisioned concurrency in AWS console, you need to visit a `provisioned` alias for your lambda

**Comment by karocksjoelee** [comment] 2020-04-28 12:40
@medikoo  umm .. I see .

**Comment by niketh90** [comment] 2020-06-01 17:20
So there is no way to set provisioned concurrency on $LATEST . Right?

**Comment by shaheer-k** [comment] 2020-06-01 17:28
The issue which I am facing is that when I enable both Provisioned concurrency and Canary, the API invocation is failing due to the alias issue.

**Comment by medikoo** [comment] 2020-06-01 19:57
> So there is no way to set provisioned concurrency on $LATEST . Right?

Yes, it needs to be on _alias_ that's not $LATEST

**Comment by jackmuskopf** [comment] 2020-12-03 23:33
I just ran into an issue with this.  The CloudFormation update initiated by Serverless failed to reconfigure the provisioned concurrency for the new version (ie remove it from 23 and apply it to 24).  This left the CloudFormation stack in an UPDATE_ROLLBACK_FAILED state.

**Comment by medikoo** [comment] 2020-12-04 08:18
> I've since updated, so the problem may be fixed.

We had many fixes related to provisioned concurrency support, since that version. Always ensure to use latest version of a Framework

**Comment by jackmuskopf** [comment] 2020-12-05 20:58
> > I've since updated, so the problem may be fixed.
> 
> We had many fixes related to provisioned concurrency support, since that version. Always ensure to use latest version of a Framework

Yes, apologies for not checking the version before posting.  Thanks!

**Comment by pgrzesik** [comment] 2021-03-11 09:03
Hello @tiivik - do the invocation always result in cold starts or only after deployment? I'm not sure how exactly it's taken care of for provisioned concurrency + image on AWS side, but generally, Docker Images has to be optimized before the first invocation which is done automatically by AWS.

**Comment by tiivik** [comment] 2021-03-11 10:11
> Hello @tiivik - do the invocation always result in cold starts or only after deployment? I'm not sure how exactly it's taken care of for provisioned concurrency + image on AWS side, but generally, Docker Images has to be optimized before the first invocation which is done automatically by AWS.

Thanks for the reply @pgrzesik ! Second request immediately after first results in a warm start as expected, however after waiting ~15 minutes the request results in cold start again. Ran an overnight test invoking function every 30 minutes and resulted 16 cold starts out of 26 requests, while provisioned concurrency was set to 3.

Furthermore, invoking the function in Lambda console
- Test the function without specified alias -> Cold start
- Pick Aliases -> :provisioned -> Test -> Cold start


Similar issue https://stackoverflow.com/questions/65181821/provision-concurrency-not-keeping-aws-lambda-function-warm-and-it-still-has-init

**Comment by pgrzesik** [comment] 2021-03-15 12:16
That is indeed quite surprising @tiivik. However, looking at your report, it seems like it's an issue on AWS side as if I see correctly, the provisioned concurrency seems to be setup properly. Do you run into the same problem when not using Images to package your functions?

**Comment by utkarshdeep** [comment] 2024-12-03 13:28
@tiivik did you ever figure the root cause? I am facing the same issue. Facing cold start issue even after configuring Provisioned concurrency.

From what I understand: If I have configured provisioned concurrency to be say 30, 30 pre-initialized instances of lambda are always up to serve client request. But that doesn't seem to be happening.
